-- Parte 01: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('admiracao', 'O temor do Senhor', 'Provérbios 8:13', 'Provérbios', 8, 13, NULL),
  ('admiracao', 'Ora, amados, pois que temos tais promessas, purifiquemo-nos de toda imundícia da carne e do espírito, aperfeiçoando a santificação no temor de Deus.', '2 Coríntios 7:1', '2 Coríntios', 7, 1, NULL),
  ('admiracao', 'Não sejas sábio a teus próprios olhos; teme ao Senhor', 'Provérbios 3:7-8', 'Provérbios', 3, 7, 8),
  ('admiracao', 'Eis que os olhos do Senhor', 'Salmo 33:18', 'Salmo', 33, 18, NULL),
  ('admiracao', 'Agora, pois, ó Israel, que é o que o Senhor', 'Deuteronômio 10:12-13', 'Deuteronômio', 10, 12, 13),
  ('admiracao', 'O galardão da humildade e o temor do Senhor', 'Provérbios 22:4', 'Provérbios', 22, 4, NULL),
  ('admiracao', 'Bem-aventurado aquele que teme ao Senhor', 'Salmo 128:1', 'Salmo', 128, 1, NULL),
  ('admiracao', 'Enganosa é a graça, e vaidade, a formosura, mas a mulher que teme ao Senhor', 'Provérbios 31:30', 'Provérbios', 31, 30, NULL),
  ('admiracao', 'O temor do Senhor', 'Provérbios 1:7', 'Provérbios', 1, 7, NULL),
  ('admiracao', 'Melhor é o pouco com o temor do Senhor', 'Provérbios 15:16', 'Provérbios', 15, 16, NULL),
  ('admiracao', 'De tudo o que se tem ouvido, o fim é: Teme a Deus e guarda os seus mandamentos; porque este é o dever de todo homem.', 'Eclesiastes 12:13', 'Eclesiastes', 12, 13, NULL),
  ('admiracao', 'Após o Senhor', 'Deuteronômio 13:4', 'Deuteronômio', 13, 4, NULL),
  ('admiracao', 'Mas para vós que temeis o meu nome nascerá o sol da justiça e salvação trará debaixo das suas asas; e saireis e crescereis como os bezerros do cevadouro.', 'Malaquias 4:2', 'Malaquias', 4, 2, NULL),
  ('admiracao', 'E aconteceu que, como as parteiras temeram a Deus, estabeleceu-lhes casas.', 'Êxodo 1:21', 'Êxodo', 1, 21, NULL),
  ('admiracao', 'Louvai ao Senhor', 'Salmo 112:1', 'Salmo', 112, 1, NULL),
  ('admiracao', 'O temor do Senhor', 'Provérbios 15:33', 'Provérbios', 15, 33, NULL),
  ('admiracao', 'O temor do Senhor', 'Provérbios 9:10', 'Provérbios', 9, 10, NULL),
  ('admiracao', 'Quem dera que eles tivessem tal coração que me temessem e guardassem todos os meus mandamentos todos os dias, para que bem lhes fosse a eles e a seus filhos, para sempre!', 'Deuteronômio 5:29', 'Deuteronômio', 5, 29, NULL),
  ('admiracao', 'O temor do Senhor', 'Salmo 111:10', 'Salmo', 111, 10, NULL),
  ('admiracao', 'Portanto, dai a cada um o que deveis: a quem tributo, tributo; a quem imposto, imposto; a quem temor, temor; a quem honra, honra.', 'Romanos 13:7', 'Romanos', 13, 7, NULL),
  ('admiracao', 'Ensina-me, Senhor', 'Salmo 86:11', 'Salmo', 86, 11, NULL),
  ('admiracao', 'Ao que está aflito devia o amigo mostrar compaixão, ainda ao que deixasse o temor do Todo-Poderoso.', 'Jó 6:14', 'Jó', 6, 14, NULL),
  ('admiracao', 'Deus nos abençoará, e todas as extremidades da terra o temerão.', 'Salmo 67:7', 'Salmo', 67, 7, NULL),
  ('admiracao', 'E guarda os mandamentos do Senhor', 'Deuteronômio 8:6', 'Deuteronômio', 8, 6, NULL),
  ('admiracao', 'Assim, pois, as igrejas em toda a Judeia, e Galileia, e Samaria tinham paz e eram edificadas; e se multiplicavam, andando no temor do Senhor e na consolação do Espírito Santo.', 'Atos 9:31', 'Atos', 9, 31, NULL),
  ('admiracao', 'Tão somente temei ao Senhor', '1 Samuel 12:24', '1 Samuel', 12, 24, NULL),
  ('admiracao', 'Agora, pois, seja o temor do Senhor', '2 Crônicas 19:7', '2 Crônicas', 19, 7, NULL),
  ('adoracao', 'Ó Senhor', 'Isaías 25:1', 'Isaías', 25, 1, NULL),
  ('adoracao', 'E servireis ao Senhor', 'Êxodo 23:25', 'Êxodo', 23, 25, NULL),
  ('adoracao', 'Tudo quanto tem fôlego louve ao Senhor', 'Salmo 150:6', 'Salmo', 150, 6, NULL),
  ('adoracao', 'Perto da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros presos os escutavam.', 'Atos 16:25', 'Atos', 16, 25, NULL),
  ('adoracao', 'Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade.', 'João 4:24', 'João', 4, 24, NULL),
  ('adoracao', 'Bendize, ó minha alma, ao Senhor', 'Salmo 103:1', 'Salmo', 103, 1, NULL),
  ('adoracao', 'Porquanto, ainda que a figueira não floresça, nem haja fruto na vide; o produto da oliveira minta, e os campos não produzam mantimento; as ovelhas da malhada sejam arrebatadas, e nos currais não haja vacas, todavia, eu me alegrarei no Senhor', 'Habacuque 3:17-18', 'Habacuque', 3, 17, 18),
  ('adoracao', 'Louvai ao Senhor', '1 Crônicas 16:34', '1 Crônicas', 16, 34, NULL),
  ('adoracao', 'Tua é, Senhor', '1 Crônicas 29:11', '1 Crônicas', 29, 11, NULL),
  ('adoracao', 'Ó Deus, tu és o meu Deus; de madrugada te buscarei; a minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água.', 'Salmo 63:1', 'Salmo', 63, 1, NULL),
  ('adoracao', 'Encha-se a minha boca do teu louvor e da tua glória todo o dia.', 'Salmo 71:8', 'Salmo', 71, 8, NULL),
  ('adoracao', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda consolação, que nos consola em toda a nossa tribulação, para que também possamos consolar os que estiverem em alguma tribulação, com a consolação com que nós mesmos somos consolados de Deus.', '2 Coríntios 1:3-4', '2 Coríntios', 1, 3, 4),
  ('adoracao', 'Portanto, grandioso és, ó Senhor Jeová', '2 Samuel 7:22', '2 Samuel', 7, 22, NULL),
  ('adoracao', 'Porque dele, e por ele, e para ele são todas as coisas; glória, pois, a ele eternamente. Amém!', 'Romanos 11:36', 'Romanos', 11, 36, NULL),
  ('adoracao', 'Cantai a Deus, cantai louvores ao seu nome; louvai aquele que vai sobre os céus, pois o seu nome é Jeová', 'Salmo 68:4-5', 'Salmo', 68, 4, 5),
  ('adoracao', 'Ó, vinde, adoremos e prostremo-nos! Ajoelhemos diante do Senhor', 'Salmo 95:6', 'Salmo', 95, 6, NULL),
  ('adoracao', 'Porque a tua benignidade é melhor do que a vida; os meus lábios te louvarão. Assim, eu te bendirei enquanto viver; em teu nome levantarei as minhas mãos.', 'Salmo 63:3-4', 'Salmo', 63, 3, 4),
  ('adoracao', 'Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei. Ele é a salvação da minha face e o meu Deus.', 'Salmo 42:11', 'Salmo', 42, 11, NULL),
  ('adoracao', 'Então, me invocareis, e ireis, e orareis a mim, e eu vos ouvirei.', 'Jeremias 29:12', 'Jeremias', 29, 12, NULL),
  ('adoracao', 'Porque está escrito: Pela minha vida, diz o Senhor, todo joelho se dobrará diante de mim, e toda língua confessará a Deus.', 'Romanos 14:11', 'Romanos', 14, 11, NULL),
  ('adoracao', 'Louvai ao Senhor', 'Salmo 105:1', 'Salmo', 105, 1, NULL),
  ('adoracao', 'Não há santo como é o Senhor', '1 Samuel 2:2', '1 Samuel', 2, 2, NULL),
  ('adoracao', 'Estendo para ti as minhas mãos; a minha alma tem sede de ti como terra sedenta. (Selá)', 'Salmo 143:6', 'Salmo', 143, 6, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('adoracao', 'O Senhor', 'Salmo 28:7', 'Salmo', 28, 7, NULL),
  ('adoracao', 'A minha alma disse ao Senhor', 'Salmo 16:2', 'Salmo', 16, 2, NULL),
  ('adoracao', 'Agora, pois, eu, Nabucodonosor, louvo, e exalço, e glorifico ao Rei dos céus; porque todas as suas obras são verdades; e os seus caminhos, juízo, e pode humilhar aos que andam na soberba.', 'Daniel 4:37', 'Daniel', 4, 37, NULL),
  ('adoracao', 'A ele clamei com a minha boca, e ele foi exaltado pela minha língua.', 'Salmo 66:17', 'Salmo', 66, 17, NULL),
  ('adoracao', 'Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera, a esse glória na igreja, por Jesus Cristo, em todas as gerações, para todo o sempre. Amém!', 'Efésios 3:20-21', 'Efésios', 3, 20, 21),
  ('adoracao', 'Grande é o Senhor', 'Salmo 145:3', 'Salmo', 145, 3, NULL),
  ('adoracao', 'E ouvi a toda criatura que está no céu, e na terra, e debaixo da terra, e que está no mar, e a todas as coisas que neles há, dizer: Ao que está assentado sobre o trono e ao Cordeiro sejam dadas ações de graças, e honra, e glória, e poder para todo o sempre.', 'Apocalipse 5:13', 'Apocalipse', 5, 13, NULL),
  ('adoracao', 'Louvarei ao Senhor', 'Salmo 34:1', 'Salmo', 34, 1, NULL),
  ('adoracao', 'De uma mesma boca procede bênção e maldição. Meus irmãos, não convém que isto se faça assim.', 'Tiago 3:10', 'Tiago', 3, 10, NULL),
  ('adoracao', 'Amo ao Senhor', 'Salmo 116:1-2', 'Salmo', 116, 1, 2),
  ('adoracao', 'Mas eu confio na tua benignidade; na tua salvação, meu coração se alegrará. Cantarei ao Senhor', 'Salmo 13:5-6', 'Salmo', 13, 5, 6),
  ('adoracao', 'Os céus manifestam a glória de Deus e o firmamento anuncia a obra das suas mãos. Um dia faz declaração a outro dia, e uma noite mostra sabedoria a outra noite.', 'Salmo 19:1-2', 'Salmo', 19, 1, 2),
  ('adoracao', 'A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais; cantando ao Senhor com graça em vosso coração.', 'Colossenses 3:16', 'Colossenses', 3, 16, NULL),
  ('adoracao', 'Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos? Porque fostes comprados por bom preço; glorificai, pois, a Deus no vosso corpo e no vosso espírito, os quais pertencem a Deus.', '1 Coríntios 6:19-20', '1 Coríntios', 6, 19, 20),
  ('adoracao', 'Quem é este Rei da Glória? O Senhor', 'Salmo 24:10', 'Salmo', 24, 10, NULL),
  ('adoracao', 'Eu te louvarei, Senhor', 'Salmo 9:1', 'Salmo', 9, 1, NULL),
  ('adoracao', 'Não a nós, Senhor', 'Salmo 115:1', 'Salmo', 115, 1, NULL),
  ('adoracao', 'Pelo que também Deus o exaltou soberanamente e lhe deu um nome que é sobre todo o nome, para que ao nome de Jesus se dobre todo joelho dos que estão nos céus, e na terra, e debaixo da terra.', 'Filipenses 2:9-10', 'Filipenses', 2, 9, 10),
  ('adoracao', 'Louvar-te-ei entre os povos, Senhor', 'Salmo 108:3', 'Salmo', 108, 3, NULL),
  ('adoracao', 'Bendito seja o Senhor, que de dia em dia nos cumula de benefícios; o Deus que é a nossa salvação. (Selá)', 'Salmo 68:19', 'Salmo', 68, 19, NULL),
  ('adoracao', 'Os meus lábios exultarão quando eu te cantar, assim como a minha alma que tu remiste.', 'Salmo 71:23', 'Salmo', 71, 23, NULL),
  ('adoracao', 'Portanto, quer comais, quer bebais ou façais outra qualquer coisa, fazei tudo para a glória de Deus.', '1 Coríntios 10:31', '1 Coríntios', 10, 31, NULL),
  ('adoracao', 'Eu te exaltarei, ó Deus, Rei meu, e bendirei o teu nome pelos séculos dos séculos.', 'Salmo 145:1', 'Salmo', 145, 1, NULL),
  ('adoracao', 'Ora, ao Rei dos séculos, imortal, invisível, ao único Deus seja honra e glória para todo o sempre. Amém!', '1 Timóteo 1:17', '1 Timóteo', 1, 17, NULL),
  ('adoracao', 'A quem tenho eu no céu senão a ti? E na terra não há quem eu deseje além de ti.', 'Salmo 73:25', 'Salmo', 73, 25, NULL),
  ('adoracao', 'Exalta-te sobre os céus, ó Deus, e a tua glória sobre toda a terra.', 'Salmo 108:5', 'Salmo', 108, 5, NULL),
  ('adoracao', 'Contudo, o Senhor', 'Salmo 42:8', 'Salmo', 42, 8, NULL),
  ('adoracao', 'E direis, naquele dia: Dai graças ao Senhor', 'Isaías 12:4', 'Isaías', 12, 4, NULL),
  ('adoracao', 'Porque tu és a minha rocha e a minha fortaleza; pelo que, por amor do teu nome, guia-me e encaminha-me.', 'Salmo 31:3', 'Salmo', 31, 3, NULL),
  ('adoracao', 'Louvar-te-ei com retidão de coração, quando tiver aprendido os teus justos juízos.', 'Salmo 119:7', 'Salmo', 119, 7, NULL),
  ('adoracao', 'Antes, crescei na graça e conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele seja dada a glória, assim agora como no dia da eternidade. Amém!', '2 Pedro 3:18', '2 Pedro', 3, 18, NULL),
  ('adoracao', 'E acontecerá que todo aquele que invocar o nome do Senhor será salvo.', 'Atos 2:21', 'Atos', 2, 21, NULL),
  ('adoracao', 'Em ti me alegrarei e saltarei de prazer; cantarei louvores ao teu nome, ó Altíssimo.', 'Salmo 9:2', 'Salmo', 9, 2, NULL),
  ('adoracao', 'Ora, a nosso Deus e Pai seja dada glória para todo o sempre. Amém!', 'Filipenses 4:20', 'Filipenses', 4, 20, NULL),
  ('adoracao', 'E, perseverando unânimes todos os dias no templo e partindo o pão em casa, comiam juntos com alegria e singeleza de coração, louvando a Deus e caindo na graça de todo o povo. E todos os dias acrescentava o Senhor à igreja aqueles que se haviam de salvar.', 'Atos 2:46-47', 'Atos', 2, 46, 47),
  ('adoracao', 'Nem se acende a candeia e se coloca debaixo do alqueire, mas, no velador, e dá luz a todos que estão na casa. Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem o vosso Pai, que está nos céus.', 'Mateus 5:15-16', 'Mateus', 5, 15, 16),
  ('adoracao', 'E as multidões, tanto as que iam adiante como as que o seguiam, clamavam, dizendo: Hosana ao Filho de Davi! Bendito o que vem em nome do Senhor! Hosana nas alturas!', 'Mateus 21:9', 'Mateus', 21, 9, NULL),
  ('adoracao', 'Porque todo aquele que invocar o nome do Senhor será salvo.', 'Romanos 10:13', 'Romanos', 10, 13, NULL),
  ('adoracao', 'Portanto, recebei-vos uns aos outros, como também Cristo nos recebeu para glória de Deus.', 'Romanos 15:7', 'Romanos', 15, 7, NULL),
  ('adoracao', 'E o Senhor me livrará de toda má obra e guardar-me-á para o seu Reino celestial; a quem seja glória para todo o sempre. Amém!', '2 Timóteo 4:18', '2 Timóteo', 4, 18, NULL),
  ('adoracao', 'O temor do Senhor', 'Salmo 111:10', 'Salmo', 111, 10, NULL),
  ('adoracao', 'Cantarei ao Senhor', 'Salmo 104:33', 'Salmo', 104, 33, NULL),
  ('adoracao', 'Ó Deus de meus pais, eu te louvo e celebro porque me deste sabedoria e força; e, agora, me fizeste saber o que te pedimos, porque nos fizeste saber este assunto do rei.', 'Daniel 2:23', 'Daniel', 2, 23, NULL),
  ('adoracao', 'Glória a Deus nas alturas, paz na terra, boa vontade para com os homens!', 'Lucas 2:14', 'Lucas', 2, 14, NULL),
  ('adoracao', 'Sê exaltado, ó Deus, sobre os céus; seja a tua glória sobre toda a terra.', 'Salmo 57:5', 'Salmo', 57, 5, NULL),
  ('adoracao', 'Cantai ao Senhor', 'Isaías 12:5', 'Isaías', 12, 5, NULL),
  ('adoracao', 'Então, Jó se levantou, e rasgou o seu manto, e rapou a sua cabeça, e se lançou em terra, e adorou, e disse: Nu saí do ventre de minha mãe e nu tornarei para lá; o Senhor', 'Jó 1:20-21', 'Jó', 1, 20, 21),
  ('adoracao', 'E voltaram os pastores glorificando e louvando a Deus por tudo o que tinham ouvido e visto, como lhes havia sido dito.', 'Lucas 2:20', 'Lucas', 2, 20, NULL),
  ('adoracao', 'Ajuda-nos, ó Deus da nossa salvação, pela glória do teu nome; e livra-nos e perdoa os nossos pecados, por amor do teu nome.', 'Salmo 79:9', 'Salmo', 79, 9, NULL),
  ('adoracao', 'Que do mesmo modo as mulheres se ataviem em traje honesto, com pudor e modéstia, não com tranças, ou com ouro, ou pérolas, ou vestidos preciosos, mas (como convém a mulheres que fazem profissão de servir a Deus) com boas obras.', '1 Timóteo 2:9-10', '1 Timóteo', 2, 9, 10);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('adoracao', 'E, tendo nascido Jesus em Belém da Judeia, no tempo do rei Herodes, eis que uns magos vieram do Oriente a Jerusalém, e perguntaram: Onde está aquele que é nascido rei dos judeus? Porque vimos a sua estrela no Oriente e viemos a adorá-lo.', 'Mateus 2:1-2', 'Mateus', 2, 1, 2),
  ('adoracao', 'E, servindo eles ao Senhor e jejuando, disse o Espírito Santo: Apartai-me a Barnabé e a Saulo para a obra a que os tenho chamado.', 'Atos 13:2', 'Atos', 13, 2, NULL),
  ('alegria', 'Regozijai-vos sempre. Orai sem cessar. Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.', '1 Tessalonicenses 5:16-18', '1 Tessalonicenses', 5, 16, 18),
  ('alegria', 'O Senhor', 'Sofonias 3:17', 'Sofonias', 3, 17, NULL),
  ('alegria', 'Regozijai-vos, sempre, no Senhor; outra vez digo: regozijai-vos.', 'Filipenses 4:4', 'Filipenses', 4, 4, NULL),
  ('alegria', 'Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração.', 'Romanos 12:12', 'Romanos', 12, 12, NULL),
  ('alegria', 'Multiplicando-se dentro de mim os meus cuidados, as tuas consolações reanimaram a minha alma.', 'Salmo 94:19', 'Salmo', 94, 19, NULL),
  ('alegria', 'Este é o dia que fez o Senhor', 'Salmo 118:24', 'Salmo', 118, 24, NULL),
  ('alegria', 'Porquanto, ainda que a figueira não floresça, nem haja fruto na vide; o produto da oliveira minta, e os campos não produzam mantimento; as ovelhas da malhada sejam arrebatadas, e nos currais não haja vacas, todavia, eu me alegrarei no Senhor', 'Habacuque 3:17-18', 'Habacuque', 3, 17, 18),
  ('alegria', 'Far-me-ás ver a vereda da vida; na tua presença há abundância de alegrias; à tua mão direita há delícias perpetuamente.', 'Salmo 16:11', 'Salmo', 16, 11, NULL),
  ('alegria', 'Regozijar-me-ei muito no Senhor', 'Isaías 61:10', 'Isaías', 61, 10, NULL),
  ('alegria', 'Tenho-vos dito isso para que a minha alegria permaneça em vós, e a vossa alegria seja completa.', 'João 15:11', 'João', 15, 11, NULL),
  ('alegria', 'Ao qual, não o havendo visto, amais; no qual, não o vendo agora, mas crendo, vos alegrais com gozo inefável e glorioso, alcançando o fim da vossa fé, a salvação da alma.', '1 Pedro 1:8-9', '1 Pedro', 1, 8, 9),
  ('alegria', 'Até agora, nada pedistes em meu nome; pedi e recebereis, para que a vossa alegria se cumpra.', 'João 16:24', 'João', 16, 24, NULL),
  ('alegria', 'Pelo que sinto prazer nas fraquezas, nas injúrias, nas necessidades, nas perseguições, nas angústias, por amor de Cristo. Porque, quando estou fraco, então, sou forte.', '2 Coríntios 12:10', '2 Coríntios', 12, 10, NULL),
  ('alegria', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('alegria', 'O homem se alegra na resposta da sua boca, e a palavra, a seu tempo, quão boa é!', 'Provérbios 15:23', 'Provérbios', 15, 23, NULL),
  ('alegria', 'Tu és o lugar em que me escondo; tu me preservas da angústia; tu me cinges de alegres cantos de livramento. (Selá)', 'Salmo 32:7', 'Salmo', 32, 7, NULL),
  ('alegria', 'Cada um contribua segundo propôs no seu coração, não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria.', '2 Coríntios 9:7', '2 Coríntios', 9, 7, NULL),
  ('alegria', 'O coração alegre serve de bom remédio, mas o espírito abatido virá a secar os ossos.', 'Provérbios 17:22', 'Provérbios', 17, 22, NULL),
  ('alegria', 'Alegrai-vos com os que se alegram e chorai com os que choram.', 'Romanos 12:15', 'Romanos', 12, 15, NULL),
  ('alegria', 'Em ti me alegrarei e saltarei de prazer; cantarei louvores ao teu nome, ó Altíssimo.', 'Salmo 9:2', 'Salmo', 9, 2, NULL),
  ('alegria', 'A fim de que, pela vontade de Deus, chegue a vós com alegria e possa recrear-me convosco.', 'Romanos 15:32', 'Romanos', 15, 32, NULL),
  ('alegria', 'Os teus testemunhos tenho eu tomado por herança para sempre, pois são o gozo do meu coração.', 'Salmo 119:111', 'Salmo', 119, 111, NULL),
  ('alegria', 'Porque o Senhor', 'Salmo 149:4', 'Salmo', 149, 4, NULL),
  ('alegria', 'Não tenho maior gozo do que este: o de ouvir que os meus filhos andam na verdade.', '3 João 1:4', '3 João', 1, 4, NULL),
  ('alegria', 'Ora, sem fé é impossível agradar-lhe, porque é necessário que aquele que se aproxima de Deus creia que ele existe e que é galardoador dos que o buscam.', 'Hebreus 11:6', 'Hebreus', 11, 6, NULL),
  ('alegria', 'No dia da prosperidade, goza do bem, mas, no dia da adversidade, considera; porque também Deus fez este em oposição àquele, para que o homem nada ache que tenha de vir depois dele.', 'Eclesiastes 7:14', 'Eclesiastes', 7, 14, NULL),
  ('alegria', 'Mas é grande ganho a piedade com contentamento.', '1 Timóteo 6:6', '1 Timóteo', 6, 6, NULL),
  ('alegria', 'Já tenho conhecido que não há coisa melhor para eles do que se alegrarem e fazerem bem na sua vida; e também que todo homem coma e beba e goze do bem de todo o seu trabalho. Isso é um dom de Deus.', 'Eclesiastes 3:12-13', 'Eclesiastes', 3, 12, 13),
  ('alegria', 'Folgo mais com o caminho dos teus testemunhos do que com todas as riquezas.', 'Salmo 119:14', 'Salmo', 119, 14, NULL),
  ('alegria', 'Manda aos ricos deste mundo que não sejam altivos, nem ponham a esperança na incerteza das riquezas, mas em Deus, que abundantemente nos dá todas as coisas para delas gozarmos.', '1 Timóteo 6:17', '1 Timóteo', 6, 17, NULL),
  ('alegria', 'Como contristados, mas sempre alegres; como pobres, mas enriquecendo a muitos; como nada tendo e possuindo tudo.', '2 Coríntios 6:10', '2 Coríntios', 6, 10, NULL),
  ('alegria', 'Grandemente se regozijará o pai do justo, e o que gerar a um sábio se alegrará nele.', 'Provérbios 23:24', 'Provérbios', 23, 24, NULL),
  ('alegria', 'Disse-lhes mais: Ide, e comei as gorduras, e bebei as doçuras, e enviai porções aos que não têm nada preparado para si; porque esse dia é consagrado ao nosso Senhor; portanto, não vos entristeçais, porque a alegria do Senhor', 'Neemias 8:10', 'Neemias', 8, 10, NULL),
  ('alegria', 'Vai, pois, come com alegria o teu pão e bebe com bom coração o teu vinho, pois já Deus se agrada das tuas obras.', 'Eclesiastes 9:7', 'Eclesiastes', 9, 7, NULL),
  ('alegria', 'E não somente isto, mas também nos gloriamos nas tribulações, sabendo que a tribulação produz a paciência; e a paciência, a experiência; e a experiência, a esperança.', 'Romanos 5:3-4', 'Romanos', 5, 3, 4),
  ('alegria', 'E o anjo lhes disse: Não temais, porque eis aqui vos trago novas de grande alegria, que será para todo o povo.', 'Lucas 2:10', 'Lucas', 2, 10, NULL),
  ('alegria', 'Os preceitos do Senhor', 'Salmo 19:8', 'Salmo', 19, 8, NULL),
  ('alegria', 'Filho meu, se o teu coração for sábio, alegrar-se-á o meu coração, sim, o meu próprio.', 'Provérbios 23:15', 'Provérbios', 23, 15, NULL),
  ('alegria', 'E, estando ele ainda a falar, eis que uma nuvem luminosa os cobriu. E da nuvem saiu uma voz que dizia: Este é o meu Filho amado, em quem me comprazo; escutai-o.', 'Mateus 17:5', 'Mateus', 17, 5, NULL),
  ('alegria', 'Mas não vos alegreis porque se vos sujeitem os espíritos; alegrai-vos, antes, por estar o vosso nome escrito nos céus.', 'Lucas 10:20', 'Lucas', 10, 20, NULL),
  ('alegria', 'Mas para vós que temeis o meu nome nascerá o sol da justiça e salvação trará debaixo das suas asas; e saireis e crescereis como os bezerros do cevadouro.', 'Malaquias 4:2', 'Malaquias', 4, 2, NULL),
  ('alegria', 'Engano há no coração dos que maquinam mal, mas alegria têm os que aconselham a paz.', 'Provérbios 12:20', 'Provérbios', 12, 20, NULL),
  ('alegria', 'Lembra-te do teu Criador nos dias da tua mocidade, antes que venham os maus dias, e cheguem os anos dos quais venhas a dizer: Não tenho neles contentamento.', 'Eclesiastes 12:1', 'Eclesiastes', 12, 1, NULL),
  ('alegria', 'Digo-vos que assim haverá alegria no céu por um pecador que se arrepende, mais do que por noventa e nove justos que não necessitam de arrependimento.', 'Lucas 15:7', 'Lucas', 15, 7, NULL),
  ('alegria', 'A esperança dos justos é alegria, mas a expectação dos ímpios perecerá.', 'Provérbios 10:28', 'Provérbios', 10, 28, NULL),
  ('alegria', 'E quanto ao homem, a quem Deus deu riquezas e fazenda e lhe deu poder para delas comer, e tomar a sua porção, e gozar do seu trabalho, isso é dom de Deus.', 'Eclesiastes 5:19', 'Eclesiastes', 5, 19, NULL),
  ('alegria', 'Assim vos digo que há alegria diante dos anjos de Deus por um pecador que se arrepende.', 'Lucas 15:10', 'Lucas', 15, 10, NULL),
  ('alegria', 'A vide se secou, a figueira se murchou; a romeira também, e a palmeira, e a macieira; todas as árvores do campo se secaram, e a alegria se secou entre os filhos dos homens.', 'Joel 1:12', 'Joel', 1, 12, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('alegria', 'O filho sábio alegra a seu pai, mas o filho louco é a tristeza de sua mãe.', 'Provérbios 10:1', 'Provérbios', 10, 1, NULL),
  ('alegria', 'Também o Reino dos céus é semelhante a um tesouro escondido n um campo que um homem achou e escondeu; e, pelo gozo dele, vai, vende tudo quanto tem e compra aquele campo.', 'Mateus 13:44', 'Mateus', 13, 44, NULL),
  ('alianca', 'Saberás, pois, que o Senhor', 'Deuteronômio 7:9', 'Deuteronômio', 7, 9, NULL),
  ('alianca', 'O meu arco tenho posto na nuvem; este será por sinal do concerto entre mim e a terra.', 'Gênesis 9:13', 'Gênesis', 9, 13, NULL),
  ('alianca', 'O Senhor', 'Deuteronômio 31:8', 'Deuteronômio', 31, 8, NULL),
  ('alianca', 'Mas a misericórdia do Senhor', 'Salmo 103:17-18', 'Salmo', 103, 17, 18),
  ('alianca', 'E, por isso, é Mediador de um novo testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna.', 'Hebreus 9:15', 'Hebreus', 9, 15, NULL),
  ('alianca', 'Agora, pois, se diligentemente ouvirdes a minha voz e guardardes o meu concerto, então, sereis a minha propriedade peculiar dentre todos os povos; porque toda a terra é minha.', 'Êxodo 19:5', 'Êxodo', 19, 5, NULL),
  ('alianca', 'Porque as montanhas se desviarão e os outeiros tremerão; mas a minha benignidade não se desviará de ti, e o concerto da minha paz não mudará, diz o Senhor', 'Isaías 54:10', 'Isaías', 54, 10, NULL),
  ('alianca', 'Ora, o Deus de paz, que pelo sangue do concerto eterno tornou a trazer dos mortos a nosso Senhor Jesus Cristo, grande Pastor das ovelhas, vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável por Cristo Jesus, ao qual seja glória para todo o sempre. Amém!', 'Hebreus 13:20-21', 'Hebreus', 13, 20, 21),
  ('alianca', 'Mas agora alcançou ele ministério tanto mais excelente, quanto é mediador de um melhor concerto, que está confirmado em melhores promessas.', 'Hebreus 8:6', 'Hebreus', 8, 6, NULL),
  ('alianca', 'Semelhantemente, tomou o cálice, depois da ceia, dizendo: Este cálice é o Novo Testamento no meu sangue, que é derramado por vós.', 'Lucas 22:20', 'Lucas', 22, 20, NULL),
  ('alianca', 'Então, vos anunciou ele o seu concerto, que vos prescreveu, os dez mandamentos, e os escreveu em duas tábuas de pedra.', 'Deuteronômio 4:13', 'Deuteronômio', 4, 13, NULL),
  ('alianca', 'Fiz concerto com os meus olhos; como, pois, os fixaria numa virgem?', 'Jó 31:1', 'Jó', 31, 1, NULL),
  ('alianca', 'E eu convosco estabeleço o meu concerto, que não será mais destruída toda carne pelas águas do dilúvio e que não haverá mais dilúvio para destruir a terra.', 'Gênesis 9:11', 'Gênesis', 9, 11, NULL),
  ('alianca', 'E esteve Moisés ali com o Senhor', 'Êxodo 34:28', 'Êxodo', 34, 28, NULL),
  ('alianca', 'E, tomando o cálice e dando graças, deu-lho, dizendo: Bebei dele todos. Porque isto é o meu sangue, o sangue do Novo Testamento, que é derramado por muitos, para remissão dos pecados.', 'Mateus 26:27-28', 'Mateus', 26, 27, 28),
  ('alimento', 'Pois fartou a alma sedenta e encheu de bens a alma faminta.', 'Salmo 107:9', 'Salmo', 107, 9, NULL),
  ('alimento', 'E Jesus lhes disse: Eu sou o pão da vida; aquele que vem a mim não terá fome; e quem crê em mim nunca terá sede.', 'João 6:35', 'João', 6, 35, NULL),
  ('alimento', 'Portanto, quer comais, quer bebais ou façais outra qualquer coisa, fazei tudo para a glória de Deus.', '1 Coríntios 10:31', '1 Coríntios', 10, 31, NULL),
  ('alimento', 'Isto comereis de tudo o que há nas águas: tudo o que tem barbatanas e escamas comereis. Mas tudo o que não tiver barbatanas nem escamas não o comereis; imundo vos será.', 'Deuteronômio 14:9-10', 'Deuteronômio', 14, 9, 10),
  ('alimento', 'O que come não despreze o que não come; e o que não come não julgue o que come; porque Deus o recebeu por seu.', 'Romanos 14:3', 'Romanos', 14, 3, NULL),
  ('alimento', 'E disse Deus: Eis que vos tenho dado toda erva que dá semente e que está sobre a face de toda a terra e toda árvore em que há fruto de árvore que dá semente; ser-vos-ão para mantimento.', 'Gênesis 1:29', 'Gênesis', 1, 29, NULL),
  ('alimento', 'A alma generosa engordará, e o que regar também será regado.', 'Provérbios 11:25', 'Provérbios', 11, 25, NULL),
  ('alimento', 'Tudo quanto se move, que é vivente, será para vosso mantimento; tudo vos tenho dado, como a erva verde. A carne, porém, com sua vida, isto é, com seu sangue, não comereis.', 'Gênesis 9:3-4', 'Gênesis', 9, 3, 4),
  ('alimento', 'Ele, porém, respondendo, disse: Está escrito: Nem só de pão viverá o homem, mas de toda a palavra que sai da boca de Deus.', 'Mateus 4:4', 'Mateus', 4, 4, NULL),
  ('alimento', 'Porque nada trouxemos para este mundo e manifesto é que nada podemos levar dele. Tendo, porém, sustento e com que nos cobrirmos, estejamos com isso contentes.', '1 Timóteo 6:7-8', '1 Timóteo', 6, 7, 8),
  ('alimento', 'Por isso, vos digo: não andeis cuidadosos quanto à vossa vida, pelo que haveis de comer ou pelo que haveis de beber; nem quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o mantimento, e o corpo, mais do que a vestimenta?', 'Mateus 6:25', 'Mateus', 6, 25, NULL),
  ('alimento', 'E, tomando os cinco pães e os dois peixes e olhando para o céu, abençoou-os, e partiu-os, e deu-os aos seus discípulos para os porem diante da multidão. E comeram todos e saciaram-se; e levantaram, do que lhes sobejou, doze cestos de pedaços.', 'Lucas 9:16-17', 'Lucas', 9, 16, 17),
  ('alimento', 'Vai, pois, come com alegria o teu pão e bebe com bom coração o teu vinho, pois já Deus se agrada das tuas obras.', 'Eclesiastes 9:7', 'Eclesiastes', 9, 7, NULL),
  ('alimento', 'Portanto, ninguém vos julgue pelo comer, ou pelo beber, ou por causa dos dias de festa, ou da lua nova, ou dos sábados, que são sombras das coisas futuras, mas o corpo é de Cristo.', 'Colossenses 2:16-17', 'Colossenses', 2, 16, 17),
  ('alimento', 'Disse-lhes mais: Ide, e comei as gorduras, e bebei as doçuras, e enviai porções aos que não têm nada preparado para si; porque esse dia é consagrado ao nosso Senhor; portanto, não vos entristeçais, porque a alegria do Senhor', 'Neemias 8:10', 'Neemias', 8, 10, NULL),
  ('alimento', 'Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e com ele cearei, e ele, comigo.', 'Apocalipse 3:20', 'Apocalipse', 3, 20, NULL),
  ('alimento', 'Trabalhai não pela comida que perece, mas pela comida que permanece para a vida eterna, a qual o Filho do Homem vos dará, porque a este o Pai, Deus, o selou.', 'João 6:27', 'João', 6, 27, NULL),
  ('alimento', 'Favo de mel são as palavras suaves: doces para a alma e saúde para os ossos.', 'Provérbios 16:24', 'Provérbios', 16, 24, NULL),
  ('alimento', 'E, perseverando unânimes todos os dias no templo e partindo o pão em casa, comiam juntos com alegria e singeleza de coração, louvando a Deus e caindo na graça de todo o povo. E todos os dias acrescentava o Senhor à igreja aqueles que se haviam de salvar.', 'Atos 2:46-47', 'Atos', 2, 46, 47),
  ('alimento', 'Ora, aquele que dá a semente ao que semeia e pão para comer também multiplicará a vossa sementeira e aumentará os frutos da vossa justiça.', '2 Coríntios 9:10', '2 Coríntios', 9, 10, NULL),
  ('alimento', 'Manjar desejável não comi, nem carne nem vinho entraram na minha boca, nem me ungi com unguento, até que se cumpriram as três semanas.', 'Daniel 10:3', 'Daniel', 10, 3, NULL),
  ('alimento', 'Já tenho conhecido que não há coisa melhor para eles do que se alegrarem e fazerem bem na sua vida; e também que todo homem coma e beba e goze do bem de todo o seu trabalho. Isso é um dom de Deus.', 'Eclesiastes 3:12-13', 'Eclesiastes', 3, 12, 13),
  ('alimento', 'Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.', 'Mateus 5:6', 'Mateus', 5, 6, NULL),
  ('alimento', 'Desejai afetuosamente, como meninos novamente nascidos, o leite racional, não falsificado, para que, por ele, vades crescendo.', '1 Pedro 2:2', '1 Pedro', 2, 2, NULL),
  ('alimento', 'E te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conheceste, nem teus pais o conheceram, para te dar a entender que o homem não viverá só de pão, mas que de tudo o que sai da boca do Senhor', 'Deuteronômio 8:3', 'Deuteronômio', 8, 3, NULL),
  ('alimento', 'Mas buscai primeiro o Reino de Deus, e a sua justiça, e todas essas coisas vos serão acrescentadas.', 'Mateus 6:33', 'Mateus', 6, 33, NULL),
  ('alimento', 'Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa, e depois fazei prova de mim, diz o Senhor', 'Malaquias 3:10', 'Malaquias', 3, 10, NULL),
  ('alimento', 'Afasta de mim a vaidade e a palavra mentirosa; não me dês nem a pobreza nem a riqueza; mantém-me do pão da minha porção acostumada.', 'Provérbios 30:8', 'Provérbios', 30, 8, NULL),
  ('alimento', 'Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas nem todas as coisas edificam.', '1 Coríntios 10:23', '1 Coríntios', 10, 23, NULL),
  ('alimento', 'Eis aqui o que eu vi, uma boa e bela coisa: comer, e beber, e gozar cada um do bem de todo o seu trabalho, em que trabalhou debaixo do sol, todos os dias da sua vida que Deus lhe deu; porque esta é a sua porção.', 'Eclesiastes 5:18', 'Eclesiastes', 5, 18, NULL),
  ('alimento', 'Não estejais apreensivos pela vossa vida, sobre o que comereis, nem pelo corpo, sobre o que vestireis. Mais é a vida do que o sustento, e o corpo, mais do que as vestes.', 'Lucas 12:22b-23', 'Lucas 12:22b-23', NULL, NULL, NULL),
  ('alimento', 'E, no último dia, o grande dia da festa, Jesus pôs-se em pé e clamou, dizendo: Se alguém tem sede, que venha a mim e beba.', 'João 7:37', 'João', 7, 37, NULL),
  ('alimento', 'Sei estar abatido e sei também ter abundância; em toda a maneira e em todas as coisas, estou instruído, tanto a ter fartura como a ter fome, tanto a ter abundância como a padecer necessidade.', 'Filipenses 4:12', 'Filipenses', 4, 12, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('alimento', 'E ele disse-lhes: Assim também vós estais sem entendimento? Não compreendeis que tudo o que de fora entra no homem não o pode contaminar, porque não entra no seu coração, mas no ventre e é lançado fora, ficando puras todas as comidas?', 'Marcos 7:18-19', 'Marcos', 7, 18, 19),
  ('alimento', 'E quanto ao homem, a quem Deus deu riquezas e fazenda e lhe deu poder para delas comer, e tomar a sua porção, e gozar do seu trabalho, isso é dom de Deus.', 'Eclesiastes 5:19', 'Eclesiastes', 5, 19, NULL),
  ('alimento', 'E, respondendo ele, disse-lhes: Quem tiver duas túnicas, que reparta com o que não tem, e quem tiver alimentos, que faça da mesma maneira.', 'Lucas 3:11', 'Lucas', 3, 11, NULL),
  ('alimento', 'Considerai os corvos, que nem semeiam, nem segam, nem têm despensa nem celeiro, e Deus os alimenta; quanto mais valeis vós do que as aves?', 'Lucas 12:24', 'Lucas', 12, 24, NULL),
  ('alimento', 'Assim como o Pai, que vive, me enviou, e eu vivo pelo Pai, assim quem de mim se alimenta também viverá por mim.', 'João 6:57', 'João', 6, 57, NULL),
  ('alimento', 'E este João tinha a sua veste de pelos de camelo e um cinto de couro em torno de seus lombos e alimentava-se de gafanhotos e de mel silvestre.', 'Mateus 3:4', 'Mateus', 3, 4, NULL),
  ('alimento', 'A vide se secou, a figueira se murchou; a romeira também, e a palmeira, e a macieira; todas as árvores do campo se secaram, e a alegria se secou entre os filhos dos homens.', 'Joel 1:12', 'Joel', 1, 12, NULL),
  ('alimento', 'Depois, eles se fartaram em proporção do seu pasto; estando fartos, ensoberbeceu-se o seu coração; por isso, se esqueceram de mim.', 'Oseias 13:6', 'Oseias', 13, 6, NULL),
  ('alimento', 'Assim que, quanto ao comer das coisas sacrificadas aos ídolos, sabemos que o ídolo nada é no mundo e que não há outro Deus, senão um só.', '1 Coríntios 8:4', '1 Coríntios', 8, 4, NULL),
  ('alma', 'Então, dali, buscarás ao Senhor', 'Deuteronômio 4:29', 'Deuteronômio', 4, 29, NULL),
  ('alma', 'Pois que aproveita ao homem ganhar o mundo inteiro, se perder a sua alma? Ou que dará o homem em recompensa da sua alma?', 'Mateus 16:26', 'Mateus', 16, 26, NULL),
  ('alma', 'A minha alma espera somente em Deus; dele vem a minha salvação.', 'Salmo 62:1', 'Salmo', 62, 1, NULL),
  ('alma', 'Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei. Ele é a salvação da minha face e o meu Deus.', 'Salmo 42:11', 'Salmo', 42, 11, NULL),
  ('alma', 'Assim diz o Senhor', 'Jeremias 6:16', 'Jeremias', 6, 16, NULL),
  ('alma', 'E Jesus disse-lhe: Amarás o Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todo o teu pensamento.', 'Mateus 22:37', 'Mateus', 22, 37, NULL),
  ('alma', 'Amado, desejo que te vá bem em todas as coisas e que tenhas saúde, assim como bem vai a tua alma.', '3 João 1:2', '3 João', 1, 2, NULL),
  ('alma', 'E não temais os que matam o corpo e não podem matar a alma; temei, antes, aquele que pode fazer perecer no inferno a alma e o corpo.', 'Mateus 10:28', 'Mateus', 10, 28, NULL),
  ('alma', 'Pois possuíste o meu interior; entreteceste-me no ventre de minha mãe. Eu te louvarei, porque de um modo terrível e tão maravilhoso fui formado; maravilhosas são as tuas obras, e a minha alma o sabe muito bem.', 'Salmo 139:13-14', 'Salmo', 139, 13, 14),
  ('alma', 'E buscar-me-eis e me achareis quando me buscardes de todo o vosso coração.', 'Jeremias 29:13', 'Jeremias', 29, 13, NULL),
  ('alma', 'Ó Deus, tu és o meu Deus; de madrugada te buscarei; a minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água.', 'Salmo 63:1', 'Salmo', 63, 1, NULL),
  ('alma', 'Bendize, ó minha alma, ao Senhor', 'Salmo 103:1', 'Salmo', 103, 1, NULL),
  ('alma', 'Favo de mel são as palavras suaves: doces para a alma e saúde para os ossos.', 'Provérbios 16:24', 'Provérbios', 16, 24, NULL),
  ('alma', 'Aguardo o Senhor', 'Salmo 130:5', 'Salmo', 130, 5, NULL),
  ('alma', 'Senhor', 'Salmo 120:2', 'Salmo', 120, 2, NULL),
  ('alma', 'A lei do Senhor', 'Salmo 19:7', 'Salmo', 19, 7, NULL),
  ('alma', 'Tão somente tende cuidado de guardar com diligência o mandamento e a lei que Moisés, o servo do Senhor', 'Josué 22:5', 'Josué', 22, 5, NULL),
  ('alma', 'Os meus lábios exultarão quando eu te cantar, assim como a minha alma que tu remiste.', 'Salmo 71:23', 'Salmo', 71, 23, NULL),
  ('alma', 'E eis aqui eu vou, hoje, pelo caminho de toda a terra; e vós bem sabeis, com todo o vosso coração e com toda a vossa alma que nem uma só palavra caiu de todas as boas palavras que falou de vós o Senhor', 'Josué 23:14', 'Josué', 23, 14, NULL),
  ('alma', 'Ó minha alma, espera somente em Deus, porque dele vem a minha esperança.', 'Salmo 62:5', 'Salmo', 62, 5, NULL),
  ('alma', 'Porque satisfiz a alma cansada, e toda a alma entristecida saciei.', 'Jeremias 31:25', 'Jeremias', 31, 25, NULL),
  ('alma', 'A minha alma tem sede de Deus, do Deus vivo; quando entrarei e me apresentarei ante a face de Deus?', 'Salmo 42:2', 'Salmo', 42, 2, NULL),
  ('amizade', 'Em todo o tempo ama o amigo; e na angústia nasce o irmão.', 'Provérbios 17:17', 'Provérbios', 17, 17, NULL),
  ('amizade', 'O homem que tem muitos amigos pode congratular-se, mas há amigo mais chegado do que um irmão.', 'Provérbios 18:24', 'Provérbios', 18, 24, NULL),
  ('amizade', 'Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus amigos.', 'João 15:13', 'João', 15, 13, NULL),
  ('amizade', 'Porque, se um cair, o outro levanta o seu companheiro; mas ai do que estiver só; pois, caindo, não haverá outro que o levante.', 'Eclesiastes 4:10', 'Eclesiastes', 4, 10, NULL),
  ('amizade', 'Oh! Quão bom e quão suave é que os irmãos vivam em união!', 'Salmo 133:1', 'Salmo', 133, 1, NULL),
  ('amizade', 'O que encobre a transgressão busca a amizade, mas o que renova a questão separa os maiores amigos.', 'Provérbios 17:9', 'Provérbios', 17, 9, NULL),
  ('amizade', 'Amados, amemo-nos uns aos outros, porque o amor é de Deus; e qualquer que ama é nascido de Deus e conhece a Deus.', '1 João 4:7', '1 João', 4, 7, NULL),
  ('amizade', 'E, se alguém quiser prevalecer contra um, os dois lhe resistirão; e o cordão de três dobras não se quebra tão depressa.', 'Eclesiastes 4:12', 'Eclesiastes', 4, 12, NULL),
  ('amizade', 'Como o ferro com o ferro se aguça, assim o homem afia o rosto do seu amigo.', 'Provérbios 27:17', 'Provérbios', 27, 17, NULL),
  ('amizade', 'Melhor é serem dois do que um, porque têm melhor paga do seu trabalho.', 'Eclesiastes 4:9', 'Eclesiastes', 4, 9, NULL),
  ('amizade', 'Ao que está aflito devia o amigo mostrar compaixão, ainda ao que deixasse o temor do Todo-Poderoso.', 'Jó 6:14', 'Jó', 6, 14, NULL),
  ('amizade', 'E dele temos este mandamento: que quem ama a Deus, ame também seu irmão.', '1 João 4:21', '1 João', 4, 21, NULL),
  ('amizade', 'O homem perverso levanta a contenda, e o difamador separa os maiores amigos.', 'Provérbios 16:28', 'Provérbios', 16, 28, NULL),
  ('amizade', 'Não vos enganeis: as más conversações corrompem os bons costumes.', '1 Coríntios 15:33', '1 Coríntios', 15, 33, NULL),
  ('amizade', 'Não abandones o teu amigo, nem o amigo de teu pai, nem entres na casa de teu irmão no dia da tua adversidade; melhor é o vizinho perto do que o irmão longe.', 'Provérbios 27:10', 'Provérbios', 27, 10, NULL),
  ('amizade', 'Porque desejo ver-vos, para vos comunicar algum dom espiritual, a fim de que sejais confortados, isto é, para que juntamente convosco eu seja consolado pela fé mútua, tanto vossa como minha.', 'Romanos 1:11-12', 'Romanos', 1, 11, 12),
  ('amizade', 'Adúlteros e adúlteras, não sabeis vós que a amizade do mundo é inimizade contra Deus? Portanto, qualquer que quiser ser amigo do mundo constitui-se inimigo de Deus.', 'Tiago 4:4', 'Tiago', 4, 4, NULL),
  ('amizade', 'Deus faz que o solitário viva em família; liberta aqueles que estão presos em grilhões; mas os rebeldes habitam em terra seca.', 'Salmo 68:6', 'Salmo', 68, 6, NULL),
  ('amor', 'O amor é sofredor, é benigno; o amor não é invejoso; o amor não trata com leviandade, não se ensoberbece, não se porta com indecência, não busca os seus interesses, não se irrita, não suspeita mal.', '1 Coríntios 13:4-5', '1 Coríntios', 13, 4, 5);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('amor', 'Todas as vossas coisas sejam feitas com amor.', '1 Coríntios 16:14', '1 Coríntios', 16, 14, NULL),
  ('amor', 'Faze-me ouvir a tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti levanto a minha alma.', 'Salmo 143:8', 'Salmo', 143, 8, NULL),
  ('amor', 'E, sobre tudo isto, revesti-vos de amor, que é o vínculo da perfeição.', 'Colossenses 3:14', 'Colossenses', 3, 14, NULL),
  ('amor', 'Não te desamparem a benignidade e a fidelidade; ata-as ao teu pescoço; escreve-as na tábua do teu coração e acharás graça e bom entendimento aos olhos de Deus e dos homens.', 'Provérbios 3:3-4', 'Provérbios', 3, 3, 4),
  ('amor', 'E nós conhecemos e cremos no amor que Deus nos tem. Deus é amor e quem está em amor está em Deus, e Deus, nele.', '1 João 4:16', '1 João', 4, 16, NULL),
  ('amor', 'Agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor.', '1 Coríntios 13:13', '1 Coríntios', 13, 13, NULL),
  ('amor', 'Nós o amamos porque ele nos amou primeiro.', '1 João 4:19', '1 João', 4, 19, NULL),
  ('amor', 'Com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros em amor.', 'Efésios 4:2', 'Efésios', 4, 2, NULL),
  ('amor', 'Mas, sobretudo, tende ardente amor uns para com os outros, porque o amor cobrirá a multidão de pecados.', '1 Pedro 4:8', '1 Pedro', 4, 8, NULL),
  ('amor', 'O amor seja não fingido. Aborrecei o mal e apegai-vos ao bem.', 'Romanos 12:9', 'Romanos', 12, 9, NULL),
  ('amor', 'Para que, segundo as riquezas da sua glória, vos conceda que sejais corroborados com poder pelo seu Espírito no homem interior; para que Cristo habite, pela fé, no vosso coração; a fim de, estando arraigados e fundados em amor.', 'Efésios 3:16-17', 'Efésios', 3, 16, 17),
  ('amor', 'O meu mandamento é este: Que vos ameis uns aos outros, assim como eu vos amei.', 'João 15:12', 'João', 15, 12, NULL),
  ('amor', 'E ainda que tivesse o dom de profecia, e conhecesse todos os mistérios e toda a ciência, e ainda que tivesse toda a fé, de maneira tal que transportasse os montes, e não tivesse amor, nada seria.', '1 Coríntios 13:2', '1 Coríntios', 13, 2, NULL),
  ('amor', 'Ora, o Senhor encaminhe o vosso coração no amor de Deus e na paciência de Cristo.', '2 Tessalonicenses 3:5', '2 Tessalonicenses', 3, 5, NULL),
  ('amor', 'Pode uma mulher esquecer-se tanto do filho que cria, que se não compadeça dele, do filho do seu ventre? Mas, ainda que esta se esquecesse, eu, todavia, me não esquecerei de ti. Eis que, na palma das minhas mãos, te tenho gravado; os teus muros estão continuamente perante mim.', 'Isaías 49:15-16', 'Isaías', 49, 15, 16),
  ('amor', 'Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros.', 'Romanos 12:10', 'Romanos', 12, 10, NULL),
  ('amor', 'Vós, maridos, amai vossa mulher, como também Cristo amou a igreja e a si mesmo se entregou por ela, para a santificar, purificando-a com a lavagem da água, pela palavra.', 'Efésios 5:25-26', 'Efésios', 5, 25, 26),
  ('amor', 'Ninguém jamais viu a Deus; se nós amamos uns aos outros, Deus está em nós, e em nós é perfeito o seu amor.', '1 João 4:12', '1 João', 4, 12, NULL),
  ('amor', 'Põe-me como selo sobre o teu coração, como selo sobre o teu braço, porque o amor é forte como a morte, e duro como a sepultura o ciúme; as suas brasas são brasas de fogo, labaredas do Senhor', 'Cantares 8:6', 'Cantares', 8, 6, NULL),
  ('amor', 'Se alguém diz: Eu amo a Deus e aborrece a seu irmão, é mentiroso. Pois quem não ama seu irmão, ao qual viu, como pode amar a Deus, a quem não viu?', '1 João 4:20', '1 João', 4, 20, NULL),
  ('amor', 'Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus amigos.', 'João 15:13', 'João', 15, 13, NULL),
  ('amor', 'No amor, não há temor; antes, o perfeito amor lança fora o temor; porque o temor tem consigo a pena, e o que teme não é perfeito em amor.', '1 João 4:18', '1 João', 4, 18, NULL),
  ('amor', 'Enquanto foste precioso aos meus olhos, também foste glorificado, e eu te amei, pelo que dei os homens por ti, e os povos, pela tua alma.', 'Isaías 43:4', 'Isaías', 43, 4, NULL),
  ('amor', 'Mas, como está escrito: As coisas que o olho não viu, e o ouvido não ouviu, e não subiram ao coração do homem são as que Deus preparou para os que o amam.', '1 Coríntios 2:9', '1 Coríntios', 2, 9, NULL),
  ('amor', 'A ninguém devais coisa alguma, a não ser o amor com que vos ameis uns aos outros; porque quem ama aos outros cumpriu a lei.', 'Romanos 13:8', 'Romanos', 13, 8, NULL),
  ('amor', 'E o Senhor vos aumente e faça crescer em amor uns para com os outros e para com todos, como também nós para convosco.', '1 Tessalonicenses 3:12', '1 Tessalonicenses', 3, 12, NULL),
  ('amor', 'Vede quão grande amor nos tem concedido o Pai: que fôssemos chamados filhos de Deus. Por isso, o mundo não nos conhece, porque não conhece a ele.', '1 João 3:1', '1 João', 3, 1, NULL),
  ('amor', 'Aquele que não ama não conhece a Deus, porque Deus é amor.', '1 João 4:8', '1 João', 4, 8, NULL),
  ('amor', 'O ódio excita contendas, mas o amor cobre todas as transgressões.', 'Provérbios 10:12', 'Provérbios', 10, 12, NULL),
  ('amor', 'O que segue a justiça e a bondade achará a vida, a justiça e a honra.', 'Provérbios 21:21', 'Provérbios', 21, 21, NULL),
  ('amor', 'As misericórdias do Senhor', 'Lamentações 3:22-23', 'Lamentações', 3, 22, 23),
  ('amor', 'Porque estou certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir, nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus, nosso Senhor!', 'Romanos 8:38-39', 'Romanos', 8, 38, 39),
  ('amor', 'Não folga com a injustiça, mas folga com a verdade; tudo sofre, tudo crê, tudo espera, tudo suporta.', '1 Coríntios 13:6-7', '1 Coríntios', 13, 6, 7),
  ('amor', 'Amarás, pois, ao Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todo o teu entendimento, e de todas as tuas forças; este é o primeiro mandamento.', 'Marcos 12:30', 'Marcos', 12, 30, NULL),
  ('amor', 'A misericórdia, e a paz, e o amor vos sejam multiplicadas.', 'Judas 1:2', 'Judas', 1, 2, NULL),
  ('amor', 'E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo. Não há outro mandamento maior do que estes.', 'Marcos 12:31', 'Marcos', 12, 31, NULL),
  ('amor', 'Ninguém busque o proveito próprio; antes, cada um, o que é de outrem.', '1 Coríntios 10:24', '1 Coríntios', 10, 24, NULL),
  ('amor', 'Amo ao Senhor', 'Salmo 116:1-2', 'Salmo', 116, 1, 2),
  ('amor', 'Antes, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo.', 'Efésios 4:15', 'Efésios', 4, 15, NULL),
  ('amor', 'Ainda que eu falasse as línguas dos homens e dos anjos e não tivesse amor, seria como o metal que soa ou como o sino que tine.', '1 Coríntios 13:1', '1 Coríntios', 13, 1, NULL),
  ('amor', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('amor', 'O amor não faz mal ao próximo; de sorte que o cumprimento da lei é o amor.', 'Romanos 13:10', 'Romanos', 13, 10, NULL),
  ('amor', 'Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', '2 Timóteo 1:7', '2 Timóteo', 1, 7, NULL),
  ('amor', 'Eu, porém, vos digo: Amai a vossos inimigos, bendizei os que vos maldizem, fazei bem aos que vos odeiam e orai pelos que vos maltratam e vos perseguem.', 'Mateus 5:44', 'Mateus', 5, 44, NULL),
  ('amor', 'Porque quem quer amar a vida e ver os dias bons, refreie a sua língua do mal, e os seus lábios não falem engano; aparte-se do mal e faça o bem; busque a paz e siga-a.', '1 Pedro 3:10-11', '1 Pedro', 3, 10, 11),
  ('amor', 'Ninguém despreze a tua mocidade; mas sê o exemplo dos fiéis, na palavra, no trato, no amor, no espírito, na fé, na pureza.', '1 Timóteo 4:12', '1 Timóteo', 4, 12, NULL),
  ('amor', 'Nisto está o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou e enviou seu Filho para propiciação pelos nossos pecados.', '1 João 4:10', '1 João', 4, 10, NULL),
  ('amor', 'Quem nos separará do amor de Cristo? A tribulação, ou a angústia, ou a perseguição, ou a fome, ou a nudez, ou o perigo, ou a espada?', 'Romanos 8:35', 'Romanos', 8, 35, NULL),
  ('amor', 'Porque a tua benignidade é melhor do que a vida; os meus lábios te louvarão. Assim, eu te bendirei enquanto viver; em teu nome levantarei as minhas mãos.', 'Salmo 63:3-4', 'Salmo', 63, 3, 4),
  ('amor', 'Misericordioso e piedoso é o Senhor', 'Salmo 103:8', 'Salmo', 103, 8, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('amor', 'Porque a sua ira dura só um momento; no seu favor está a vida; o choro pode durar uma noite, mas a alegria vem pela manhã.', 'Salmo 30:5', 'Salmo', 30, 5, NULL),
  ('amor', 'Contudo, o Senhor', 'Salmo 42:8', 'Salmo', 42, 8, NULL),
  ('amor', 'E vós também, pondo nisto mesmo toda a diligência, acrescentai à vossa fé a virtude, e à virtude, a ciência, e à ciência, a temperança, e à temperança, a paciência, e à paciência, a piedade, e à piedade, a fraternidade, e à fraternidade, o amor.', '2 Pedro 1:5-7', '2 Pedro', 1, 5, 7),
  ('amor', 'Não aborrecerás a teu irmão no teu coração; não deixarás de repreender o teu próximo e nele não sofrerás pecado. Não te vingarás, nem guardarás ira contra os filhos do teu povo; mas amarás o teu próximo como a ti mesmo. Eu sou o Senhor', 'Levítico 19:17-18', 'Levítico', 19, 17, 18),
  ('amor', 'E ainda que distribuísse toda a minha fortuna para sustento dos pobres, e ainda que entregasse o meu corpo para ser queimado, e não tivesse amor, nada disso me aproveitaria.', '1 Coríntios 13:3', '1 Coríntios', 13, 3, NULL),
  ('amor', 'Mas tu, ó homem de Deus, foge destas coisas e segue a justiça, a piedade, a fé, o amor, a paciência, a mansidão.', '1 Timóteo 6:11', '1 Timóteo', 6, 11, NULL),
  ('amor', 'E andai em amor, como também Cristo vos amou e se entregou a si mesmo por nós, em oferta e sacrifício a Deus, em cheiro suave.', 'Efésios 5:2', 'Efésios', 5, 2, NULL),
  ('amor', 'Quando eu disse: O meu pé vacila; a tua benignidade, Senhor', 'Salmo 94:18', 'Salmo', 94, 18, NULL),
  ('amor', 'Amados, se Deus assim nos amou, também nós devemos amar uns aos outros.', '1 João 4:11', '1 João', 4, 11, NULL),
  ('amor', 'Porque esta é a mensagem que ouvistes desde o princípio: que nos amemos uns aos outros.', '1 João 3:11', '1 João', 3, 11, NULL),
  ('amor', 'Permaneça o amor fraternal. Não vos esqueçais da hospitalidade, porque, por ela, alguns, não o sabendo, hospedaram anjos.', 'Hebreus 13:1-2', 'Hebreus', 13, 1, 2),
  ('amor', 'Porque as montanhas se desviarão e os outeiros tremerão; mas a minha benignidade não se desviará de ti, e o concerto da minha paz não mudará, diz o Senhor', 'Isaías 54:10', 'Isaías', 54, 10, NULL),
  ('amor', 'Amados, amemo-nos uns aos outros, porque o amor é de Deus; e qualquer que ama é nascido de Deus e conhece a Deus.', '1 João 4:7', '1 João', 4, 7, NULL),
  ('amor', 'Pois a tua misericórdia é grande até aos céus, e a tua verdade até às nuvens.', 'Salmo 57:10', 'Salmo', 57, 10, NULL),
  ('amor', 'Mas em todas estas coisas somos mais do que vencedores, por aquele que nos amou.', 'Romanos 8:37', 'Romanos', 8, 37, NULL),
  ('amor', 'E, respondendo ele, disse: Amarás ao Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todas as tuas forças, e de todo o teu entendimento e ao teu próximo como a ti mesmo.', 'Lucas 10:27', 'Lucas', 10, 27, NULL),
  ('amor', 'Não ameis o mundo, nem o que no mundo há. Se alguém ama o mundo, o amor do Pai não está nele.', '1 João 2:15', '1 João', 2, 15, NULL),
  ('amor', 'Um novo mandamento vos dou: Que vos ameis uns aos outros; como eu vos amei a vós, que também vós uns aos outros vos ameis.', 'João 13:34', 'João', 13, 34, NULL),
  ('amor', 'Se me amardes, guardareis os meus mandamentos.', 'João 14:15', 'João', 14, 15, NULL),
  ('amor', 'Pois tu, Senhor, és bom, e pronto a perdoar, e abundante em benignidade para com todos os que te invocam.', 'Salmo 86:5', 'Salmo', 86, 5, NULL),
  ('amor', 'E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu decreto.', 'Romanos 8:28', 'Romanos', 8, 28, NULL),
  ('amor', 'Porque toda a lei se cumpre numa só palavra, nesta: Amarás o teu próximo como a ti mesmo.', 'Gálatas 5:14', 'Gálatas', 5, 14, NULL),
  ('amor', 'Nisto se manifestou o amor de Deus para conosco: que Deus enviou seu Filho unigênito ao mundo, para que por ele vivamos.', '1 João 4:9', '1 João', 4, 9, NULL),
  ('amor', 'E a esperança não traz confusão, porquanto o amor de Deus está derramado em nosso coração pelo Espírito Santo que nos foi dado.', 'Romanos 5:5', 'Romanos', 5, 5, NULL),
  ('amor', 'Eu repreendo e castigo a todos quantos amo; sê, pois, zeloso e arrepende-te.', 'Apocalipse 3:19', 'Apocalipse', 3, 19, NULL),
  ('amor', 'Nisto todos conhecerão que sois meus discípulos, se vos amardes uns aos outros.', 'João 13:35', 'João', 13, 35, NULL),
  ('amor', 'Aquele que tem os meus mandamentos e os guarda, este é o que me ama; e aquele que me ama será amado de meu Pai, e eu o amarei e me manifestarei a ele.', 'João 14:21', 'João', 14, 21, NULL),
  ('amor', 'Mas Deus, que é riquíssimo em misericórdia, pelo seu muito amor com que nos amou, estando nós ainda mortos em nossas ofensas, nos vivificou juntamente com Cristo (pela graça sois salvos).', 'Efésios 2:4-5', 'Efésios', 2, 4, 5),
  ('amor', 'Quanto ao mais, irmãos, regozijai-vos, sede perfeitos, sede consolados, sede de um mesmo parecer, vivei em paz; e o Deus de amor e de paz será convosco.', '2 Coríntios 13:11', '2 Coríntios', 13, 11, NULL),
  ('amor', 'Filho meu, não rejeites a correção do Senhor', 'Provérbios 3:11-12', 'Provérbios', 3, 11, 12),
  ('amor', 'Conhecemos o amor nisto: que ele deu a sua vida por nós, e nós devemos dar a vida pelos irmãos.', '1 João 3:16', '1 João', 3, 16, NULL),
  ('amor', 'Porque vós, irmãos, fostes chamados à liberdade. Não useis, então, da liberdade para dar ocasião à carne, mas servi-vos uns aos outros pelo amor.', 'Gálatas 5:13', 'Gálatas', 5, 13, NULL),
  ('amor', 'Ele ama a justiça e o juízo; a terra está cheia da bondade do Senhor', 'Salmo 33:5', 'Salmo', 33, 5, NULL),
  ('amor', 'Com efeito: Não adulterarás, não matarás, não furtarás, não darás falso testemunho, não cobiçarás, e, se há algum outro mandamento, tudo nesta palavra se resume: Amarás ao teu próximo como a ti mesmo.', 'Romanos 13:9', 'Romanos', 13, 9, NULL),
  ('amor', 'Para que os seus corações sejam consolados, e estejam unidos em amor e enriquecidos da plenitude da inteligência, para conhecimento do mistério de Deus — Cristo.', 'Colossenses 2:2', 'Colossenses', 2, 2, NULL),
  ('amor', 'A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com vós todos. Amém!', '2 Coríntios 13:13', '2 Coríntios', 13, 13, NULL),
  ('amor', 'E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo.', 'Mateus 22:39', 'Mateus', 22, 39, NULL),
  ('amor', 'Jesus respondeu e disse-lhe: Se alguém me ama, guardará a minha palavra, e meu Pai o amará, e viremos para ele e faremos nele morada.', 'João 14:23', 'João', 14, 23, NULL),
  ('amor', 'Uma coisa pedi ao Senhor', 'Salmo 27:4', 'Salmo', 27, 4, NULL),
  ('amor', 'Quem, pois, tiver bens do mundo e, vendo o seu irmão necessitado, lhe cerrar o seu coração, como estará nele o amor de Deus?', '1 João 3:17', '1 João', 3, 17, NULL),
  ('amor', 'Ouve, Israel, o Senhor', 'Deuteronômio 6:4-5', 'Deuteronômio', 6, 4, 5),
  ('amor', 'E eu lhes fiz conhecer o teu nome e lho farei conhecer mais, para que o amor com que me tens amado esteja neles, e eu neles esteja.', 'João 17:26', 'João', 17, 26, NULL),
  ('amor', 'E dele temos este mandamento: que quem ama a Deus, ame também seu irmão.', '1 João 4:21', '1 João', 4, 21, NULL),
  ('amor', 'Mas vós, amados, edificando-vos a vós mesmos sobre a vossa santíssima fé, orando no Espírito Santo, conservai a vós mesmos no amor de Deus, esperando a misericórdia de nosso Senhor Jesus Cristo, para a vida eterna.', 'Judas 1:20-21', 'Judas', 1, 20, 21),
  ('amor', 'Faze resplandecer o teu rosto sobre o teu servo; salva-me por tuas misericórdias.', 'Salmo 31:16', 'Salmo', 31, 16, NULL),
  ('amor', 'Não detenhas para comigo, Senhor', 'Salmo 40:11', 'Salmo', 40, 11, NULL),
  ('amor', 'Sempre devemos, irmãos, dar graças a Deus por vós, como é de razão, porque a vossa fé cresce muitíssimo, e o amor de cada um de vós aumenta de uns para com os outros.', '2 Tessalonicenses 1:3', '2 Tessalonicenses', 1, 3, NULL),
  ('amor', 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'João', 3, 16, NULL),
  ('amor', 'Porque o amor de Cristo nos constrange, julgando nós assim: que, se um morreu por todos, logo, todos morreram. E ele morreu por todos, para que os que vivem não vivam mais para si, mas para aquele que por eles morreu e ressuscitou.', '2 Coríntios 5:14-15', '2 Coríntios', 5, 14, 15),
  ('amor', 'Como um pai se compadece de seus filhos, assim o Senhor', 'Salmo 103:13', 'Salmo', 103, 13, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('amor', 'Se guardardes os meus mandamentos, permanecereis no meu amor, do mesmo modo que eu tenho guardado os mandamentos de meu Pai e permaneço no seu amor.', 'João 15:10', 'João', 15, 10, NULL),
  ('amor', 'E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor', 'Joel 2:13', 'Joel', 2, 13, NULL),
  ('amor', 'Não matarás, não cometerás adultério, não furtarás, não dirás falso testemunho; honra teu pai e tua mãe, e amarás o teu próximo como a ti mesmo.', 'Mateus 19:18b-19', 'Mateus 19:18b-19', NULL, NULL, NULL),
  ('amor', 'Não a nós, Senhor', 'Salmo 115:1', 'Salmo', 115, 1, NULL),
  ('amor', 'Louvai ao Senhor', 'Salmo 112:1', 'Salmo', 112, 1, NULL),
  ('amor', 'Porque, em Jesus Cristo, nem a circuncisão nem a incircuncisão têm virtude alguma, mas, sim, a fé que opera por amor.', 'Gálatas 5:6', 'Gálatas', 5, 6, NULL),
  ('amor', 'Pois não conquistaram a terra pela sua espada, nem o seu braço os salvou, e sim a tua destra, e o teu braço, e a luz da tua face, porquanto te agradaste deles.', 'Salmo 44:3', 'Salmo', 44, 3, NULL),
  ('amor', 'E que amá-lo de todo o coração, e de todo o entendimento, e de toda a alma, e de todas as forças e amar o próximo como a si mesmo é mais do que todos os holocaustos e sacrifícios.', 'Marcos 12:33', 'Marcos', 12, 33, NULL),
  ('amor', 'Foge, também, dos desejos da mocidade; e segue a justiça, a fé, o amor e a paz com os que, com um coração puro, invocam o Senhor.', '2 Timóteo 2:22', '2 Timóteo', 2, 22, NULL),
  ('amor', 'A ti também, Senhor, pertence a misericórdia; pois retribuirás a cada um segundo a sua obra.', 'Salmo 62:12', 'Salmo', 62, 12, NULL),
  ('anjos', 'Ou pensas tu que eu não poderia, agora, orar a meu Pai e que ele não me daria mais de doze legiões de anjos?', 'Mateus 26:53', 'Mateus', 26, 53, NULL),
  ('anjos', 'Permaneça o amor fraternal. Não vos esqueçais da hospitalidade, porque, por ela, alguns, não o sabendo, hospedaram anjos.', 'Hebreus 13:1-2', 'Hebreus', 13, 1, 2),
  ('anjos', 'E o anjo lhes disse: Não temais, porque eis aqui vos trago novas de grande alegria, que será para todo o povo.', 'Lucas 2:10', 'Lucas', 2, 10, NULL),
  ('anjos', 'Porque o mesmo Senhor descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus; e os que morreram em Cristo ressuscitarão primeiro; depois, nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o Senhor nos ares, e assim estaremos sempre com o Senhor.', '1 Tessalonicenses 4:16-17', '1 Tessalonicenses', 4, 16, 17),
  ('anjos', 'Porque estou certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir, nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus, nosso Senhor!', 'Romanos 8:38-39', 'Romanos', 8, 38, 39),
  ('anjos', 'Ainda que eu falasse as línguas dos homens e dos anjos e não tivesse amor, seria como o metal que soa ou como o sino que tine.', '1 Coríntios 13:1', '1 Coríntios', 13, 1, NULL),
  ('anjos', 'Assim vos digo que há alegria diante dos anjos de Deus por um pecador que se arrepende.', 'Lucas 15:10', 'Lucas', 15, 10, NULL),
  ('anjos', 'Mas o anjo, respondendo, disse às mulheres: Não tenhais medo; pois eu sei que buscai a Jesus, que foi crucificado. Ele não está aqui, porque já ressuscitou, como tinha dito. Vinde e vede o lugar onde o Senhor jazia.', 'Mateus 28:5-6', 'Mateus', 28, 5, 6),
  ('anjos', 'Glória a Deus nas alturas, paz na terra, boa vontade para com os homens!', 'Lucas 2:14', 'Lucas', 2, 14, NULL),
  ('anjos', 'O que vencer será vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; e confessarei o seu nome diante de meu Pai e diante dos seus anjos.', 'Apocalipse 3:5', 'Apocalipse', 3, 5, NULL),
  ('anjos', 'Disse-lhe, então, o anjo: Maria, não temas, porque achaste graça diante de Deus, E eis que em teu ventre conceberás, e darás à luz um filho, e pôr-lhe-ás o nome de Jesus.', 'Lucas 1:30-31', 'Lucas', 1, 30, 31),
  ('anjos', 'E, estando com os olhos fitos no céu, enquanto ele subia, eis que junto deles se puseram dois varões vestidos de branco, os quais lhes disseram: Varões galileus, por que estais olhando para o céu? Esse Jesus, que dentre vós foi recebido em cima no céu, há de vir assim como para o céu o vistes ir.', 'Atos 1:10-11', 'Atos', 1, 10, 11),
  ('anjos', 'E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo e recebido acima, na glória.', '1 Timóteo 3:16', '1 Timóteo', 3, 16, NULL),
  ('anjos', 'E, projetando ele isso, eis que, em sonho, lhe apareceu um anjo do Senhor, dizendo: José, filho de Davi, não temas receber a Maria, tua mulher, porque o que nela está gerado é do Espírito Santo.', 'Mateus 1:20', 'Mateus', 1, 20, NULL),
  ('anjos', 'Porque o Filho do Homem virá na glória de seu Pai, com os seus anjos; e, então, dará a cada um segundo as suas obras.', 'Mateus 16:27', 'Mateus', 16, 27, NULL),
  ('aprender', 'Instruir-te-ei e ensinar-te-ei o caminho que deves seguir; guiar-te-ei com os meus olhos.', 'Salmo 32:8', 'Salmo', 32, 8, NULL),
  ('aprender', 'O que também aprendestes, e recebestes, e ouvistes, e vistes em mim, isso fazei; e o Deus de paz será convosco.', 'Filipenses 4:9', 'Filipenses', 4, 9, NULL),
  ('aprender', 'Pelo que exortai-vos uns aos outros e edificai-vos uns aos outros, como também o fazeis.', '1 Tessalonicenses 5:11', '1 Tessalonicenses', 5, 11, NULL),
  ('aprender', 'O temor do Senhor', 'Provérbios 1:7', 'Provérbios', 1, 7, NULL),
  ('aprender', 'Faze-me saber os teus caminhos, Senhor', 'Salmo 25:4', 'Salmo', 25, 4, NULL),
  ('aprender', 'A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais; cantando ao Senhor com graça em vosso coração.', 'Colossenses 3:16', 'Colossenses', 3, 16, NULL),
  ('aprender', 'Filho meu, não rejeites a correção do Senhor', 'Provérbios 3:11-12', 'Provérbios', 3, 11, 12),
  ('aprender', 'O que ama a correção ama o conhecimento, mas o que aborrece a repreensão é um bruto.', 'Provérbios 12:1', 'Provérbios', 12, 1, NULL),
  ('aprender', 'No caminho da sabedoria, te ensinei e, pelas carreiras direitas, te fiz andar.', 'Provérbios 4:11', 'Provérbios', 4, 11, NULL),
  ('aprender', 'Guia-me na tua verdade e ensina-me, pois tu és o Deus da minha salvação; por ti estou esperando todo o dia.', 'Salmo 25:5', 'Salmo', 25, 5, NULL),
  ('aprender', 'Ensina-me a fazer a tua vontade, pois és o meu Deus; guie-me o teu bom Espírito por terra plana.', 'Salmo 143:10', 'Salmo', 143, 10, NULL),
  ('aprender', 'Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração, e encontrareis descanso para a vossa alma. Porque o meu jugo é suave, e o meu fardo é leve.', 'Mateus 11:29-30', 'Mateus', 11, 29, 30),
  ('aprender', 'Bom e reto é o Senhor', 'Salmo 25:8-9', 'Salmo', 25, 8, 9),
  ('aprender', 'E a unção que vós recebestes dele fica em vós, e não tendes necessidade de que alguém vos ensine; mas, como a sua unção vos ensina todas as coisas, e é verdadeira, e não é mentira, como ela vos ensinou, assim nele permanecereis.', '1 João 2:27', '1 João', 2, 27, NULL),
  ('aprender', 'Tu, porém, fala o que convém à sã doutrina.', 'Tito 2:1', 'Tito', 2, 1, NULL),
  ('aprender', 'Jesus respondeu e disse-lhes: A minha doutrina não é minha, mas daquele que me enviou.', 'João 7:16', 'João', 7, 16, NULL),
  ('aprender', 'Ensina-me, Senhor', 'Salmo 86:11', 'Salmo', 86, 11, NULL),
  ('aprender', 'Portanto, ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo; ensinando-as a guardar todas as coisas que eu vos tenho mandado; e eis que eu estou convosco todos os dias, até à consumação dos séculos. Amém!', 'Mateus 28:19-20', 'Mateus', 28, 19, 20),
  ('aprender', 'Goteje a minha doutrina como a chuva, destile o meu dito como o orvalho, como chuvisco sobre a erva e como gotas de água sobre a relva.', 'Deuteronômio 32:2', 'Deuteronômio', 32, 2, NULL),
  ('aprender', 'E todos os dias, no templo e nas casas, não cessavam de ensinar e de anunciar a Jesus Cristo.', 'Atos 5:42', 'Atos', 5, 42, NULL),
  ('aprender', 'Confessa, pois, no teu coração que, como um homem castiga a seu filho, assim te castiga o Senhor', 'Deuteronômio 8:5', 'Deuteronômio', 8, 5, NULL),
  ('aprender', 'Com minha alma te desejei de noite e, com o meu espírito, que está dentro de mim, madrugarei a buscar-te; porque, havendo os teus juízos na terra, os moradores do mundo aprendem justiça.', 'Isaías 26:9', 'Isaías', 26, 9, NULL),
  ('aprender', 'Mas aquele Consolador, o Espírito Santo, que o Pai enviará em meu nome, vos ensinará todas as coisas e vos fará lembrar de tudo quanto vos tenho dito.', 'João 14:26', 'João', 14, 26, NULL),
  ('aprender', 'Como nada, que útil seja, deixei de vos anunciar e ensinar publicamente e pelas casas.', 'Atos 20:20', 'Atos', 20, 20, NULL),
  ('aprender', 'Qualquer, pois, que violar um destes menores mandamentos e assim ensinar aos homens será chamado o menor no Reino dos céus; aquele, porém, que os cumprir e ensinar será chamado grande no Reino dos céus.', 'Mateus 5:19', 'Mateus', 5, 19, NULL);

