-- Parte 02: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('aprender', 'E percorria Jesus toda a Galileia, ensinando nas suas sinagogas, e pregando o evangelho do Reino, e curando todas as enfermidades e moléstias entre o povo.', 'Mateus 4:23', 'Mateus', 4, 23, NULL),
  ('arrependimento', 'E se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar a minha face, e se converter dos seus maus caminhos, então, eu ouvirei dos céus, e perdoarei os seus pecados, e sararei a sua terra.', '2 Crônicas 7:14', '2 Crônicas', 7, 14, NULL),
  ('arrependimento', 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, e venham, assim, os tempos do refrigério pela presença do Senhor.', 'Atos 3:19', 'Atos', 3, 19, NULL),
  ('arrependimento', 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.', '1 João 1:9', '1 João', 1, 9, NULL),
  ('arrependimento', 'O que encobre as suas transgressões nunca prosperará; mas o que as confessa e deixa alcançará misericórdia.', 'Provérbios 28:13', 'Provérbios', 28, 13, NULL),
  ('arrependimento', 'Porque o Senhor, vosso Deus, é piedoso e misericordioso e não desviará de vós o rosto, se vos converterdes a ele.', '2 Crônicas 30:9b', '2 Crônicas 30:9b', NULL, NULL, NULL),
  ('arrependimento', 'Produzi, pois, frutos dignos de arrependimento.', 'Mateus 3:8', 'Mateus', 3, 8, NULL),
  ('arrependimento', 'O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se.', '2 Pedro 3:9', '2 Pedro', 3, 9, NULL),
  ('arrependimento', 'Desde então, começou Jesus a pregar e a dizer: Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 4:17', 'Mateus', 4, 17, NULL),
  ('arrependimento', 'Ide, porém, e aprendei o que significa: Misericórdia quero e não sacrifício. Porque eu não vim para chamar os justos, mas os pecadores, ao arrependimento.', 'Mateus 9:13', 'Mateus', 9, 13, NULL),
  ('arrependimento', 'Chegai-vos a Deus, e ele se chegará a vós. Limpai as mãos, pecadores; e, vós de duplo ânimo, purificai o coração.', 'Tiago 4:8', 'Tiago', 4, 8, NULL),
  ('arrependimento', 'Eu repreendo e castigo a todos quantos amo; sê, pois, zeloso e arrepende-te.', 'Apocalipse 3:19', 'Apocalipse', 3, 19, NULL),
  ('arrependimento', 'Porque não tomo prazer na morte do que morre, diz o Senhor Jeová; convertei-vos, pois, e vivei.', 'Ezequiel 18:32', 'Ezequiel', 18, 32, NULL),
  ('arrependimento', 'E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor, vosso Deus; porque ele é misericordioso, e compassivo, e tardio em irar-se, e grande em beneficência e se arrepende do mal.', 'Joel 2:13', 'Joel', 2, 13, NULL),
  ('arrependimento', 'Mas Deus, não tendo em conta os tempos da ignorância, anuncia agora a todos os homens, em todo lugar, que se arrependam.', 'Atos 17:30', 'Atos', 17, 30, NULL),
  ('arrependimento', 'Digo-vos que assim haverá alegria no céu por um pecador que se arrepende, mais do que por noventa e nove justos que não necessitam de arrependimento.', 'Lucas 15:7', 'Lucas', 15, 7, NULL),
  ('arrependimento', 'O tempo está cumprido, e o Reino de Deus está próximo. Arrependei-vos e crede no evangelho.', 'Marcos 1:15', 'Marcos', 1, 15, NULL),
  ('arrependimento', 'Eu não vim chamar os justos, mas sim os pecadores, ao arrependimento.', 'Lucas 5:32', 'Lucas', 5, 32, NULL),
  ('arrependimento', 'Não, vos digo; antes, se vos não arrependerdes, todos de igual modo perecereis.', 'Lucas 13:3', 'Lucas', 13, 3, NULL),
  ('arrependimento', 'Tornai para mim, diz o Senhor dos Exércitos, e eu tornarei para vós, diz o Senhor dos Exércitos.', 'Zacarias 1:3b', 'Zacarias 1:3b', NULL, NULL, NULL),
  ('arrependimento', 'E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo.', 'Atos 2:38', 'Atos', 2, 38, NULL),
  ('arrependimento', 'Convertei-vos pela minha repreensão; eis que abundantemente derramarei sobre vós meu espírito e vos farei saber as minhas palavras.', 'Provérbios 1:23', 'Provérbios', 1, 23, NULL),
  ('arrependimento', 'Assim vos digo que há alegria diante dos anjos de Deus por um pecador que se arrepende.', 'Lucas 15:10', 'Lucas', 15, 10, NULL),
  ('arrependimento', 'Porque a tristeza segundo Deus opera arrependimento para a salvação, da qual ninguém se arrepende; mas a tristeza do mundo opera a morte.', '2 Coríntios 7:10', '2 Coríntios', 7, 10, NULL),
  ('arrependimento', 'E, se teu irmão pecar contra ti, repreende-o; e, se ele se arrepender, perdoa-lhe; e, se pecar contra ti sete vezes no dia e sete vezes no dia vier ter contigo, dizendo: Arrependo-me, perdoa-lhe.', 'Lucas 17:3b-4', 'Lucas 17:3b-4', NULL, NULL, NULL),
  ('arrependimento', 'Os sacrifícios para Deus são o espírito quebrantado; a um coração quebrantado e contrito não desprezarás, ó Deus.', 'Salmo 51:17', 'Salmo', 51, 17, NULL),
  ('arrependimento', 'Esquadrinhemos os nossos caminhos, experimentemo-los e voltemos para o Senhor.', 'Lamentações 3:40', 'Lamentações', 3, 40, NULL),
  ('arrependimento', 'Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 3:2', 'Mateus', 3, 2, NULL),
  ('arrependimento', 'Pelo que, deixando os rudimentos da doutrina de Cristo, prossigamos até a perfeição, não lançando de novo o fundamento do arrependimento de obras mortas e de fé em Deus, e da doutrina dos batismos, e da imposição das mãos, e da ressurreição dos mortos, e do juízo eterno.', 'Hebreus 6:1-2', 'Hebreus', 6, 1, 2),
  ('arrependimento', 'O publicano, porém, estando em pé, de longe, nem ainda queria levantar os olhos ao céu, mas batia no peito, dizendo: Ó Deus, tem misericórdia de mim, pecador!', 'Lucas 18:13', 'Lucas', 18, 13, NULL),
  ('arrependimento', 'E Deus viu as obras deles, como se converteram do seu mau caminho; e Deus se arrependeu do mal que tinha dito lhes faria e não o fez.', 'Jonas 3:10', 'Jonas', 3, 10, NULL),
  ('ascensao', 'E, quando dizia isto, vendo-o eles, foi elevado às alturas, e uma nuvem o recebeu, ocultando-o a seus olhos.', 'Atos 1:9', 'Atos', 1, 9, NULL),
  ('ascensao', 'E levou-os fora, até Betânia; e, levantando as mãos, os abençoou. E aconteceu que, abençoando-os ele, se apartou deles e foi elevado ao céu.', 'Lucas 24:50-51', 'Lucas', 24, 50, 51),
  ('ascensao', 'E, estando com os olhos fitos no céu, enquanto ele subia, eis que junto deles se puseram dois varões vestidos de branco, os quais lhes disseram: Varões galileus, por que estais olhando para o céu? Esse Jesus, que dentre vós foi recebido em cima no céu, há de vir assim como para o céu o vistes ir.', 'Atos 1:10-11', 'Atos', 1, 10, 11),
  ('ascensao', 'Ora, o Senhor, depois de lhes ter falado, foi recebido no céu e assentou-se à direita de Deus.', 'Marcos 16:19', 'Marcos', 16, 19, NULL),
  ('ascensao', 'Saí do Pai e vim ao mundo; outra vez, deixo o mundo e vou para o Pai.', 'João 16:28', 'João', 16, 28, NULL),
  ('ascensao', 'Na casa de meu Pai há muitas moradas; se não fosse assim, eu vo-lo teria dito, pois vou preparar-vos lugar.', 'João 14:2', 'João', 14, 2, NULL),
  ('ascensao', 'E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo e recebido acima, na glória.', '1 Timóteo 3:16', '1 Timóteo', 3, 16, NULL),
  ('ascensao', 'Disse-lhe Jesus: Não me detenhas, porque ainda não subi para meu Pai, mas vai para meus irmãos e dize-lhes que eu subo para meu Pai e vosso Pai, meu Deus e vosso Deus.', 'João 20:17', 'João', 20, 17, NULL),
  ('ascensao', 'Que seria, pois, se vísseis subir o Filho do Homem para onde primeiro estava?', 'João 6:62', 'João', 6, 62, NULL),
  ('ascensao', 'Na verdade, na verdade vos digo que aquele que crê em mim também fará as obras que eu faço e as fará maiores do que estas, porque eu vou para meu Pai.', 'João 14:12', 'João', 14, 12, NULL),
  ('ascensao', 'Disse-lhes, pois, Jesus: Ainda um pouco de tempo estou convosco e, depois, vou para aquele que me enviou.', 'João 7:33', 'João', 7, 33, NULL),
  ('ascensao', 'De sorte que, exaltado pela destra de Deus e tendo recebido do Pai a promessa do Espírito Santo, derramou isto que vós agora vedes e ouvis.', 'Atos 2:33', 'Atos', 2, 33, NULL),
  ('autocontrole', 'Como a cidade derribada, que não tem muros, assim é o homem que não pode conter o seu espírito.', 'Provérbios 25:28', 'Provérbios', 25, 28, NULL),
  ('autocontrole', 'Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', '2 Timóteo 1:7', '2 Timóteo', 1, 7, NULL),
  ('autocontrole', 'E vós também, pondo nisto mesmo toda a diligência, acrescentai à vossa fé a virtude, e à virtude, a ciência, e à ciência, a temperança, e à temperança, a paciência, e à paciência, a piedade, e à piedade, a fraternidade, e à fraternidade, o amor.', '2 Pedro 1:5-7', '2 Pedro', 1, 5, 7),
  ('autocontrole', 'Melhor é o longânimo do que o valente, e o que governa o seu espírito do que o que toma uma cidade.', 'Provérbios 16:32', 'Provérbios', 16, 32, NULL),
  ('autocontrole', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('autocontrole', 'Sabeis isto, meus amados irmãos; mas todo o homem seja pronto para ouvir, tardio para falar, tardio para se irar.', 'Tiago 1:19', 'Tiago', 1, 19, NULL),
  ('autocontrole', 'A morte e a vida estão no poder da língua; e aquele que a ama comerá do seu fruto.', 'Provérbios 18:21', 'Provérbios', 18, 21, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('autocontrole', 'Não veio sobre vós tentação, senão humana; mas fiel é Deus, que vos não deixará tentar acima do que podeis; antes, com a tentação dará também o escape, para que a possais suportar.', '1 Coríntios 10:13', '1 Coríntios', 10, 13, NULL),
  ('autocontrole', 'Não durmamos, pois, como os demais, mas vigiemos e sejamos sóbrios.', '1 Tessalonicenses 5:6', '1 Tessalonicenses', 5, 6, NULL),
  ('autocontrole', 'A ira do louco se conhece no mesmo dia, mas o avisado encobre a afronta.', 'Provérbios 12:16', 'Provérbios', 12, 16, NULL),
  ('autocontrole', 'Um tolo expande toda a sua ira, mas o sábio a encobre e reprime.', 'Provérbios 29:11', 'Provérbios', 29, 11, NULL),
  ('autocontrole', 'Porque a graça de Deus se há manifestado, trazendo salvação a todos os homens, ensinando-nos que, renunciando à impiedade e às concupiscências mundanas, vivamos neste presente século sóbria, justa e piamente.', 'Tito 2:11-12', 'Tito', 2, 11, 12),
  ('autocontrole', 'Antes, subjugo o meu corpo e o reduzo à servidão, para que, pregando aos outros, eu mesmo não venha de alguma maneira a ficar reprovado.', '1 Coríntios 9:27', '1 Coríntios', 9, 27, NULL),
  ('autocontrole', 'E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.', 'Romanos 12:2', 'Romanos', 12, 2, NULL),
  ('autocontrole', 'E todo aquele que luta de tudo se abstém; eles o fazem para alcançar uma coroa corruptível, nós, porém, uma incorruptível.', '1 Coríntios 9:25', '1 Coríntios', 9, 25, NULL),
  ('autocontrole', 'Porque não temos que lutar contra carne e sangue, mas, sim, contra os principados, contra as potestades, contra os príncipes das trevas deste século, contra as hostes espirituais da maldade, nos lugares celestiais.', 'Efésios 6:12', 'Efésios', 6, 12, NULL),
  ('autocontrole', 'Não declines nem para a direita nem para a esquerda; retira o teu pé do mal.', 'Provérbios 4:27', 'Provérbios', 4, 27, NULL),
  ('autocontrole', 'Olhai por vós mesmos, para que não percamos o que temos ganhado; antes, recebamos o inteiro galardão.', '2 João 1:8', '2 João', 1, 8, NULL),
  ('autocontrole', 'Fiz concerto com os meus olhos; como, pois, os fixaria numa virgem?', 'Jó 31:1', 'Jó', 31, 1, NULL),
  ('autocontrole', 'Não vos defraudeis um ao outro, senão por consentimento mútuo, por algum tempo, para vos aplicardes à oração; e, depois, ajuntai-vos outra vez, para que Satanás vos não tente pela vossa incontinência.', '1 Coríntios 7:5', '1 Coríntios', 7, 5, NULL),
  ('autocontrole', 'Porque esta é a vontade de Deus, a vossa santificação: que vos abstenhais da prostituição, que cada um de vós saiba possuir o seu vaso em santificação e honra, não na paixão de concupiscência, como os gentios, que não conhecem a Deus.', '1 Tessalonicenses 4:3-5', '1 Tessalonicenses', 4, 3, 5),
  ('batismo', 'Porque todos sois filhos de Deus pela fé em Cristo Jesus; porque todos quantos fostes batizados em Cristo já vos revestistes de Cristo.', 'Gálatas 3:26-27', 'Gálatas', 3, 26, 27),
  ('batismo', 'Portanto, ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo; ensinando-as a guardar todas as coisas que eu vos tenho mandado; e eis que eu estou convosco todos os dias, até à consumação dos séculos. Amém!', 'Mateus 28:19-20', 'Mateus', 28, 19, 20),
  ('batismo', 'Que também, como uma verdadeira figura, agora vos salva, batismo, não do despojamento da imundícia da carne, mas da indagação de uma boa consciência para com Deus, pela ressurreição de Jesus Cristo.', '1 Pedro 3:21', '1 Pedro', 3, 21, NULL),
  ('batismo', 'E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo.', 'Atos 2:38', 'Atos', 2, 38, NULL),
  ('batismo', 'Quem crer e for batizado será salvo; mas quem não crer será condenado.', 'Marcos 16:16', 'Marcos', 16, 16, NULL),
  ('batismo', 'Jesus respondeu: Na verdade, na verdade te digo que aquele que não nascer da água e do Espírito não pode entrar no Reino de Deus.', 'João 3:5', 'João', 3, 5, NULL),
  ('batismo', 'E, agora, por que te deténs? Levanta-te, e batiza-te, e lava os teus pecados, invocando o nome do Senhor.', 'Atos 22:16', 'Atos', 22, 16, NULL),
  ('batismo', 'Ou não sabeis que todos quantos fomos batizados em Jesus Cristo fomos batizados na sua morte?', 'Romanos 6:3', 'Romanos', 6, 3, NULL),
  ('batismo', 'E aconteceu que, como todo o povo se batizava, sendo batizado também Jesus, orando ele, o céu se abriu, e o Espírito Santo desceu sobre ele em forma corpórea, como uma pomba; e ouviu-se uma voz do céu, que dizia: Tu és meu Filho amado; em ti me tenho comprazido.', 'Lucas 3:21-22', 'Lucas', 3, 21, 22),
  ('batismo', 'Respondeu, então, Pedro: Pode alguém, porventura, recusar a água, para que não sejam batizados estes que também receberam, como nós, o Espírito Santo?', 'Atos 10:47', 'Atos', 10, 47, NULL),
  ('batismo', 'Pois todos nós fomos batizados em um Espírito, formando um corpo, quer judeus, quer gregos, quer servos, quer livres, e todos temos bebido de um Espírito.', '1 Coríntios 12:13', '1 Coríntios', 12, 13, NULL),
  ('batismo', 'E os que ouviram foram batizados em nome do Senhor Jesus. E, impondo-lhes Paulo as mãos, veio sobre eles o Espírito Santo; e falavam línguas e profetizavam.', 'Atos 19:5-6', 'Atos', 19, 5, 6),
  ('batismo', 'De sorte que foram batizados os que de bom grado receberam a sua palavra; e, naquele dia, agregaram-se quase três mil almas.', 'Atos 2:41', 'Atos', 2, 41, NULL),
  ('batismo', 'Mas Paulo disse: Certamente João batizou com o batismo do arrependimento, dizendo ao povo que cresse no que após ele havia de vir, isto é, em Jesus Cristo.', 'Atos 19:4', 'Atos', 19, 4, NULL),
  ('batismo', 'Não pelas obras de justiça que houvéssemos feito, mas, segundo a sua misericórdia, nos salvou pela lavagem da regeneração e da renovação do Espírito Santo.', 'Tito 3:5', 'Tito', 3, 5, NULL),
  ('batismo', 'E eu não o conhecia, mas o que me mandou a batizar com água, esse me disse: Sobre aquele que vires descer o Espírito e sobre ele repousar, esse é o que batiza com o Espírito Santo.', 'João 1:33', 'João', 1, 33, NULL),
  ('batismo', 'Pelo que, deixando os rudimentos da doutrina de Cristo, prossigamos até a perfeição, não lançando de novo o fundamento do arrependimento de obras mortas e de fé em Deus, e da doutrina dos batismos, e da imposição das mãos, e da ressurreição dos mortos, e do juízo eterno.', 'Hebreus 6:1-2', 'Hebreus', 6, 1, 2),
  ('batismo', 'E eu, em verdade, vos batizo com água, para o arrependimento; mas aquele que vem após mim é mais poderoso do que eu; não sou digno de levar as suas sandálias; ele vos batizará com o Espírito Santo e com fogo.', 'Mateus 3:11', 'Mateus', 3, 11, NULL),
  ('beleza', 'Tu és toda formosa, amiga minha, e em ti não há mancha.', 'Cantares 4:7', 'Cantares', 4, 7, NULL),
  ('beleza', 'O enfeite delas não seja o exterior, no frisado dos cabelos, no uso de joias de ouro, na compostura de vestes, mas o homem encoberto no coração, no incorruptível trajo de um espírito manso e quieto, que é precioso diante de Deus.', '1 Pedro 3:3-4', '1 Pedro', 3, 3, 4),
  ('beleza', 'Enganosa é a graça, e vaidade, a formosura, mas a mulher que teme ao Senhor, essa será louvada.', 'Provérbios 31:30', 'Provérbios', 31, 30, NULL),
  ('beleza', 'Levanta-te, resplandece, porque já vem a tua luz, e a glória do Senhor vai nascendo sobre ti.', 'Isaías 60:1', 'Isaías', 60, 1, NULL),
  ('beleza', 'Pois possuíste o meu interior; entreteceste-me no ventre de minha mãe. Eu te louvarei, porque de um modo terrível e tão maravilhoso fui formado; maravilhosas são as tuas obras, e a minha alma o sabe muito bem.', 'Salmo 139:13-14', 'Salmo', 139, 13, 14),
  ('beleza', 'Porém o Senhor disse a Samuel: Não atentes para a sua aparência, nem para a altura da sua estatura, porque o tenho rejeitado; porque o Senhor não vê como vê o homem. Pois o homem vê o que está diante dos olhos, porém o Senhor olha para o coração.', '1 Samuel 16:7', '1 Samuel', 16, 7, NULL),
  ('beleza', 'Por isso, não desfalecemos; mas, ainda que o nosso homem exterior se corrompa, o interior, contudo, se renova de dia em dia.', '2 Coríntios 4:16', '2 Coríntios', 4, 16, NULL),
  ('beleza', 'Que do mesmo modo as mulheres se ataviem em traje honesto, com pudor e modéstia, não com tranças, ou com ouro, ou pérolas, ou vestidos preciosos, mas (como convém a mulheres que fazem profissão de servir a Deus) com boas obras.', '1 Timóteo 2:9-10', '1 Timóteo', 2, 9, 10),
  ('beleza', 'Seca-se a erva, e caem as flores, mas a palavra de nosso Deus subsiste eternamente.', 'Isaías 40:8', 'Isaías', 40, 8, NULL),
  ('beleza', 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas.', 'Efésios 2:10', 'Efésios', 2, 10, NULL),
  ('beleza', 'Por isso, vos digo: não andeis cuidadosos quanto à vossa vida, pelo que haveis de comer ou pelo que haveis de beber; nem quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o mantimento, e o corpo, mais do que a vestimenta?', 'Mateus 6:25', 'Mateus', 6, 25, NULL),
  ('beleza', 'E criou Deus o homem à sua imagem; à imagem de Deus o criou; macho e fêmea os criou.', 'Gênesis 1:27', 'Gênesis', 1, 27, NULL),
  ('bem', 'Antes, sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.', 'Efésios 4:32', 'Efésios', 4, 32, NULL),
  ('bem', 'Então, enquanto temos tempo, façamos o bem a todos, mas principalmente aos domésticos da fé.', 'Gálatas 6:10', 'Gálatas', 6, 10, NULL),
  ('bem', 'O Senhor é bom, uma fortaleza no dia da angústia, e conhece os que confiam nele.', 'Naum 1:7', 'Naum', 1, 7, NULL),
  ('bem', 'Não te deixes vencer do mal, mas vence o mal com o bem.', 'Romanos 12:21', 'Romanos', 12, 21, NULL),
  ('bem', 'Justo é o Senhor em todos os seus caminhos e santo em todas as suas obras.', 'Salmo 145:17', 'Salmo', 145, 17, NULL),
  ('bem', 'Pereceria sem dúvida, se não cresse que veria os bens do Senhor na terra dos viventes.', 'Salmo 27:13', 'Salmo', 27, 13, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('bem', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('bem', 'O amor seja não fingido. Aborrecei o mal e apegai-vos ao bem.', 'Romanos 12:9', 'Romanos', 12, 9, NULL),
  ('bem', 'Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas nem todas as coisas edificam.', '1 Coríntios 10:23', '1 Coríntios', 10, 23, NULL),
  ('bem', 'E Deus é poderoso para tornar abundante em vós toda graça, a fim de que, tendo sempre, em tudo, toda suficiência, superabundeis em toda boa obra.', '2 Coríntios 9:8', '2 Coríntios', 9, 8, NULL),
  ('bem', 'E vós também, pondo nisto mesmo toda a diligência, acrescentai à vossa fé a virtude, e à virtude, a ciência, e à ciência, a temperança, e à temperança, a paciência, e à paciência, a piedade, e à piedade, a fraternidade, e à fraternidade, o amor.', '2 Pedro 1:5-7', '2 Pedro', 1, 5, 7),
  ('bem', 'Nem se acende a candeia e se coloca debaixo do alqueire, mas, no velador, e dá luz a todos que estão na casa. Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem o vosso Pai, que está nos céus.', 'Mateus 5:15-16', 'Mateus', 5, 15, 16),
  ('bem', 'Confia no Senhor e faze o bem; habitarás na terra e, verdadeiramente, serás alimentado.', 'Salmo 37:3', 'Salmo', 37, 3, NULL),
  ('bem', 'O desejo do homem é a sua beneficência; mas o pobre é melhor do que o mentiroso.', 'Provérbios 19:22', 'Provérbios', 19, 22, NULL),
  ('bem', 'Sede, pois, misericordiosos, como também vosso Pai é misericordioso.', 'Lucas 6:36', 'Lucas', 6, 36, NULL),
  ('bem', 'E qual é aquele que vos fará mal, se fordes zelosos do bem?', '1 Pedro 3:13', '1 Pedro', 3, 13, NULL),
  ('bem', 'Aparta-te do mal e faze o bem; procura a paz e segue-a.', 'Salmo 34:14', 'Salmo', 34, 14, NULL),
  ('bem', 'Lembra-te, Senhor, das tuas misericórdias e das tuas benignidades, porque são desde a eternidade. Não te lembres dos pecados da minha mocidade nem das minhas transgressões; mas, segundo a tua misericórdia, lembra-te de mim, por tua bondade, Senhor.', 'Salmo 25:6-7', 'Salmo', 25, 6, 7),
  ('bem', 'Não saia da vossa boca nenhuma palavra torpe, mas só a que for boa para promover a edificação, para que dê graça aos que a ouvem.', 'Efésios 4:29', 'Efésios', 4, 29, NULL),
  ('bem', 'Assim diz o Senhor: Ponde-vos nos caminhos, e vede, e perguntai pelas veredas antigas, qual é o bom caminho, e andai por ele; e achareis descanso para a vossa alma; mas eles dizem: Não andaremos.', 'Jeremias 6:16', 'Jeremias', 6, 16, NULL),
  ('bem', 'Não vos enganeis: as más conversações corrompem os bons costumes.', '1 Coríntios 15:33', '1 Coríntios', 15, 33, NULL),
  ('bem', 'Então, entenderás justiça, e juízo, e equidade, e todas as boas veredas.', 'Provérbios 2:9', 'Provérbios', 2, 9, NULL),
  ('bem', 'Porque o fruto do Espírito está em toda bondade, e justiça, e verdade.', 'Efésios 5:9', 'Efésios', 5, 9, NULL),
  ('bem', 'O qual se deu a si mesmo por nós, para nos remir de toda iniquidade e purificar para si um povo seu especial, zeloso de boas obras.', 'Tito 2:14', 'Tito', 2, 14, NULL),
  ('bem', 'Que do mesmo modo as mulheres se ataviem em traje honesto, com pudor e modéstia, não com tranças, ou com ouro, ou pérolas, ou vestidos preciosos, mas (como convém a mulheres que fazem profissão de servir a Deus) com boas obras.', '1 Timóteo 2:9-10', '1 Timóteo', 2, 9, 10),
  ('bem', 'Então, disse o Senhor Deus: Eis que o homem é como um de nós, sabendo o bem e o mal; ora, pois, para que não estenda a sua mão, e tome também da árvore da vida, e coma, e viva eternamente, o Senhor Deus, pois, o lançou fora do jardim do Éden, para lavrar a terra, de que fora tomado.', 'Gênesis 3:22-23', 'Gênesis', 3, 22, 23),
  ('bem', 'Com o benigno te mostrarás benigno; e com o homem sincero te mostrarás sincero.', 'Salmo 18:25', 'Salmo', 18, 25, NULL),
  ('bem', 'Aquele, pois, que sabe fazer o bem e o não faz comete pecado.', 'Tiago 4:17', 'Tiago', 4, 17, NULL),
  ('bencao', 'O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti e tenha misericórdia de ti; o Senhor sobre ti levante o seu rosto e te dê a paz.', 'Números 6:24-26', 'Números', 6, 24, 26),
  ('bencao', 'Bendito o varão que confia no Senhor, e cuja esperança é o Senhor. Porque ele será como a árvore plantada junto às águas, que estende as suas raízes para o ribeiro e não receia quando vem o calor, mas a sua folha fica verde; e, no ano de sequidão, não se afadiga nem deixa de dar fruto.', 'Jeremias 17:7-8', 'Jeremias', 17, 7, 8),
  ('bencao', 'Conceda-te conforme o teu coração e cumpra todo o teu desígnio.', 'Salmo 20:4', 'Salmo', 20, 4, NULL),
  ('bencao', 'Confia ao Senhor as tuas obras, e teus pensamentos serão estabelecidos.', 'Provérbios 16:3', 'Provérbios', 16, 3, NULL),
  ('bencao', 'Porque eu bem sei os pensamentos que penso de vós, diz o Senhor; pensamentos de paz e não de mal, para vos dar o fim que esperais.', 'Jeremias 29:11', 'Jeremias', 29, 11, NULL),
  ('bencao', 'O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades em glória, por Cristo Jesus.', 'Filipenses 4:19', 'Filipenses', 4, 19, NULL),
  ('bencao', 'E servireis ao Senhor, vosso Deus, e ele abençoará o vosso pão e a vossa água; e eu tirarei do meio de ti as enfermidades.', 'Êxodo 23:25', 'Êxodo', 23, 25, NULL),
  ('bencao', 'Provai e vede que o Senhor é bom; bem-aventurado o homem que nele confia.', 'Salmo 34:8', 'Salmo', 34, 8, NULL),
  ('bencao', 'Porquanto te ordeno, hoje, que ames o Senhor, teu Deus, que andes nos seus caminhos e que guardes os seus mandamentos, e os seus estatutos, e os seus juízos, para que vivas e te multipliques, e o Senhor, teu Deus, te abençoe na terra, a qual passas a possuir.', 'Deuteronômio 30:16', 'Deuteronômio', 30, 16, NULL),
  ('bencao', 'O Senhor é o meu pastor; nada me faltará. Deitar-me faz em verdes pastos, guia-me mansamente a águas tranquilas.', 'Salmo 23:1-2', 'Salmo', 23, 1, 2),
  ('bencao', 'O que atenta prudentemente para a palavra achará o bem, e o que confia no Senhor será bem-aventurado.', 'Provérbios 16:20', 'Provérbios', 16, 20, NULL),
  ('bencao', 'E Deus é poderoso para tornar abundante em vós toda graça, a fim de que, tendo sempre, em tudo, toda suficiência, superabundeis em toda boa obra.', '2 Coríntios 9:8', '2 Coríntios', 9, 8, NULL),
  ('bencao', 'Abençoai aos que vos perseguem; abençoai e não amaldiçoeis.', 'Romanos 12:14', 'Romanos', 12, 14, NULL),
  ('bencao', 'Oh! Quão grande é a tua bondade, que guardaste para os que te temem, e que tu mostraste àqueles que em ti confiam na presença dos filhos dos homens!', 'Salmo 31:19', 'Salmo', 31, 19, NULL),
  ('bencao', 'A graça de nosso Senhor Jesus Cristo seja com o vosso espírito. Amém!', 'Filemom 1:25', 'Filemom', 1, 25, NULL),
  ('bencao', 'Amado, desejo que te vá bem em todas as coisas e que tenhas saúde, assim como bem vai a tua alma.', '3 João 1:2', '3 João', 1, 2, NULL),
  ('bencao', 'A bênção do Senhor é que enriquece, e ele não acrescenta dores.', 'Provérbios 10:22', 'Provérbios', 10, 22, NULL),
  ('bencao', 'Mas a vós, que ouvis, digo: Amai a vossos inimigos, fazei bem aos que vos aborrecem, bendizei os que vos maldizem e orai pelos que vos caluniam.', 'Lucas 6:27-28', 'Lucas', 6, 27, 28),
  ('bencao', 'Não tornando mal por mal ou injúria por injúria; antes, pelo contrário, bendizendo, sabendo que para isto fostes chamados, para que, por herança, alcanceis a bênção.', '1 Pedro 3:9', '1 Pedro', 3, 9, NULL),
  ('bencao', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('bencao', 'E será que, se ouvires a voz do Senhor, teu Deus, tendo cuidado de guardar todos os seus mandamentos que eu te ordeno hoje, o Senhor, teu Deus, te exaltará sobre todas as nações da terra.', 'Deuteronômio 28:1', 'Deuteronômio', 28, 1, NULL),
  ('bencao', 'A graça de nosso Senhor Jesus Cristo seja com vós todos. Amém!', 'Filipenses 4:23', 'Filipenses', 4, 23, NULL),
  ('bencao', 'Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.', 'Mateus 5:6', 'Mateus', 5, 6, NULL),
  ('bencao', 'A misericórdia, e a paz, e o amor vos sejam multiplicadas.', 'Judas 1:2', 'Judas', 1, 2, NULL),
  ('bencao', 'Bem-aventurados os que guardam os seus testemunhos e o buscam de todo o coração.', 'Salmo 119:2', 'Salmo', 119, 2, NULL),
  ('bencao', 'E o seu senhor lhe disse: Bem está, servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor.', 'Mateus 25:21', 'Mateus', 25, 21, NULL),
  ('bencao', 'Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus.', 'Mateus 5:9', 'Mateus', 5, 9, NULL),
  ('bencao', 'Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa, e depois fazei prova de mim, diz o Senhor dos Exércitos, se eu não vos abrir as janelas do céu e não derramar sobre vós uma bênção tal, que dela vos advenha a maior abastança.', 'Malaquias 3:10', 'Malaquias', 3, 10, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('bencao', 'O homem bom, do bom tesouro do seu coração, tira o bem, e o homem mau, do mau tesouro do seu coração, tira o mal, porque da abundância do seu coração fala a boca.', 'Lucas 6:45', 'Lucas', 6, 45, NULL),
  ('bencao', 'Jeová, o Senhor, é minha força, e fará os meus pés como os das cervas, e me fará andar sobre as minhas alturas.', 'Habacuque 3:19', 'Habacuque', 3, 19, NULL),
  ('bencao', 'Bem-aventurado o varão que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores.', 'Salmo 1:1', 'Salmo', 1, 1, NULL),
  ('bencao', 'Porque o Senhor, teu Deus, te abençoará, como te tem dito; assim, emprestarás a muitas nações, mas não tomarás empréstimos; e dominarás sobre muitas nações, mas elas não dominarão sobre ti.', 'Deuteronômio 15:6', 'Deuteronômio', 15, 6, NULL),
  ('bencao', 'A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com vós todos. Amém!', '2 Coríntios 13:13', '2 Coríntios', 13, 13, NULL),
  ('bencao', 'E a elas e aos lugares ao redor do meu outeiro, eu porei por bênção; e farei descer a chuva a seu tempo; chuvas de bênção serão.', 'Ezequiel 34:26', 'Ezequiel', 34, 26, NULL),
  ('bencao', 'Para que em tudo enriqueçais para toda a beneficência, a qual faz que por nós se deem graças a Deus.', '2 Coríntios 9:11', '2 Coríntios', 9, 11, NULL),
  ('bencao', 'Deus nos abençoará, e todas as extremidades da terra o temerão.', 'Salmo 67:7', 'Salmo', 67, 7, NULL),
  ('bencao', 'Ora, o Deus de paz, que pelo sangue do concerto eterno tornou a trazer dos mortos a nosso Senhor Jesus Cristo, grande Pastor das ovelhas, vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável por Cristo Jesus, ao qual seja glória para todo o sempre. Amém!', 'Hebreus 13:20-21', 'Hebreus', 13, 20, 21),
  ('bencao', 'Não sejas sábio a teus próprios olhos; teme ao Senhor e aparta-te do mal. Isso será remédio para o teu umbigo e medula para os teus ossos.', 'Provérbios 3:7-8', 'Provérbios', 3, 7, 8),
  ('bencao', 'Bem-aventurados os limpos de coração, porque eles verão a Deus.', 'Mateus 5:8', 'Mateus', 5, 8, NULL),
  ('bencao', 'O Senhor dará força ao seu povo; o Senhor abençoará o seu povo com paz.', 'Salmo 29:11', 'Salmo', 29, 11, NULL),
  ('bencao', 'O que acha uma mulher acha uma coisa boa e alcançou a benevolência do Senhor.', 'Provérbios 18:22', 'Provérbios', 18, 22, NULL),
  ('bencao', 'Louvarei ao Senhor em todo o tempo; o seu louvor estará continuamente na minha boca.', 'Salmo 34:1', 'Salmo', 34, 1, NULL),
  ('bencao', 'Não se aparte da tua boca o livro desta Lei; antes, medita nele dia e noite, para que tenhas cuidado de fazer conforme tudo quanto nele está escrito; porque, então, farás prosperar o teu caminho e, então, prudentemente te conduzirás.', 'Josué 1:8', 'Josué', 1, 8, NULL),
  ('bencao', 'Porque o Senhor se agrada do seu povo; ele adornará os mansos com a salvação.', 'Salmo 149:4', 'Salmo', 149, 4, NULL),
  ('bencao', 'Graça e paz de Deus, nosso Pai, e do Senhor Jesus Cristo.', 'Romanos 1:7b', 'Romanos 1:7b', NULL, NULL, NULL),
  ('bencao', 'Bendito o Deus e Pai de nosso Senhor Jesus Cristo, o qual nos abençoou com todas as bênçãos espirituais nos lugares celestiais em Cristo.', 'Efésios 1:3', 'Efésios', 1, 3, NULL),
  ('bencao', 'Pois tu, Senhor, abençoarás ao justo; circundá-lo-ás da tua benevolência como de um escudo.', 'Salmo 5:12', 'Salmo', 5, 12, NULL),
  ('bencao', 'Disse-lhe Jesus: Porque me viste, Tomé, creste; bem-aventurados os que não viram e creram!', 'João 20:29', 'João', 20, 29, NULL),
  ('bencao', 'A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém!', 'Apocalipse 22:21', 'Apocalipse', 22, 21, NULL),
  ('bencao', 'A salvação vem do Senhor; sobre o teu povo seja a tua bênção. (Selá)', 'Salmo 3:8', 'Salmo', 3, 8, NULL),
  ('bencao', 'Bênçãos há sobre a cabeça do justo, mas a violência cobre a boca dos ímpios.', 'Provérbios 10:6', 'Provérbios', 10, 6, NULL),
  ('bencao', 'Agora, pois, ó Israel, que é o que o Senhor, teu Deus, pede de ti, senão que temas o Senhor, teu Deus, e que andes em todos os seus caminhos, e o ames, e sirvas ao Senhor, teu Deus, com todo o teu coração e com toda a tua alma, para guardares os mandamentos do Senhor e os seus estatutos, que hoje te ordeno, para o teu bem?', 'Deuteronômio 10:12-13', 'Deuteronômio', 10, 12, 13),
  ('bencao', 'E guarda a observância do Senhor, teu Deus, para andares nos seus caminhos e para guardares os seus estatutos, e os seus mandamentos, e os seus juízos, e os seus testemunhos, como está escrito na Lei de Moisés, para que prosperes em tudo quanto fizeres, para onde quer que te voltares.', '1 Reis 2:3', '1 Reis', 2, 3, NULL),
  ('bencao', 'Bem-aventurada é a nação cujo Deus é o Senhor, e o povo que ele escolheu para a sua herança.', 'Salmo 33:12', 'Salmo', 33, 12, NULL),
  ('bencao', 'Bem-aventurados os que choram, porque eles serão consolados.', 'Mateus 5:4', 'Mateus', 5, 4, NULL),
  ('bencao', 'A morte e a vida estão no poder da língua; e aquele que a ama comerá do seu fruto.', 'Provérbios 18:21', 'Provérbios', 18, 21, NULL),
  ('bencao', 'Faze resplandecer o teu rosto sobre o teu servo; salva-me por tuas misericórdias.', 'Salmo 31:16', 'Salmo', 31, 16, NULL),
  ('bencao', 'Aquele, porém, que atenta bem para a lei perfeita da liberdade e nisso persevera, não sendo ouvinte esquecido, mas fazedor da obra, este tal será bem-aventurado no seu feito.', 'Tiago 1:25', 'Tiago', 1, 25, NULL),
  ('bencao', 'Ele reserva a verdadeira sabedoria para os retos; escudo é para os que caminham na sinceridade.', 'Provérbios 2:7', 'Provérbios', 2, 7, NULL),
  ('bencao', 'Honra a teu pai e a tua mãe, para que se prolonguem os teus dias na terra que o Senhor, teu Deus, te dá.', 'Êxodo 20:12', 'Êxodo', 20, 12, NULL),
  ('bencao', 'Oh! Salva, Senhor, nós te pedimos; ó Senhor, nós te pedimos, prospera! Bendito aquele que vem em nome do Senhor; nós vos bendizemos desde a Casa do Senhor.', 'Salmo 118:25-26', 'Salmo', 118, 25, 26),
  ('bencao', 'Bem-aventurado aquele cuja transgressão é perdoada, e cujo pecado é coberto.', 'Salmo 32:1', 'Salmo', 32, 1, NULL),
  ('bencao', 'Ouve, filho meu, e aceita as minhas palavras, e se te multiplicarão os anos de vida.', 'Provérbios 4:10', 'Provérbios', 4, 10, NULL),
  ('bencao', 'A memória do justo é abençoada, mas o nome dos ímpios apodrecerá.', 'Provérbios 10:7', 'Provérbios', 10, 7, NULL),
  ('bencao', 'De uma mesma boca procede bênção e maldição. Meus irmãos, não convém que isto se faça assim.', 'Tiago 3:10', 'Tiago', 3, 10, NULL),
  ('bencao', 'E levou-os fora, até Betânia; e, levantando as mãos, os abençoou. E aconteceu que, abençoando-os ele, se apartou deles e foi elevado ao céu.', 'Lucas 24:50-51', 'Lucas', 24, 50, 51),
  ('bencao', 'Que é o homem mortal para que te lembres dele? E o filho do homem, para que o visites?', 'Salmo 8:4', 'Salmo', 8, 4, NULL),
  ('bencao', 'E o Senhor virou o cativeiro de Jó, quando orava pelos seus amigos; e o Senhor acrescentou a Jó outro tanto em dobro a tudo quanto dantes possuía.', 'Jó 42:10', 'Jó', 42, 10, NULL),
  ('bencao', 'Se andardes nos meus estatutos, e guardardes os meus mandamentos, e os fizerdes, então, eu vos darei as vossas chuvas a seu tempo; e a terra dará a sua novidade, e a árvore do campo dará o seu fruto.', 'Levítico 26:3-4', 'Levítico', 26, 3, 4),
  ('bencao', 'E aconteceu que, como as parteiras temeram a Deus, estabeleceu-lhes casas.', 'Êxodo 1:21', 'Êxodo', 1, 21, NULL),
  ('bencao', 'Se o não ouvirdes e se não propuserdes no vosso coração dar honra ao meu nome, diz o Senhor dos Exércitos, enviarei a maldição contra vós e amaldiçoarei as vossas bênçãos; e já as tenho amaldiçoado, porque vós não pondes isso no coração.', 'Malaquias 2:2', 'Malaquias', 2, 2, NULL),
  ('bencao', 'Bem-aventurados sereis quando os homens vos aborrecerem, e quando vos separarem, e vos injuriarem, e rejeitarem o vosso nome como mau, por causa do Filho do Homem.', 'Lucas 6:22', 'Lucas', 6, 22, NULL),
  ('bencao', 'E multiplicarei a tua semente como as estrelas dos céus e darei à tua semente todas estas terras. E em tua semente serão benditas todas as nações da terra, porquanto Abraão obedeceu à minha voz e guardou o meu mandado, os meus preceitos, os meus estatutos e as minhas leis.', 'Gênesis 26:4-5', 'Gênesis', 26, 4, 5),
  ('bencao', 'Eis que bem-aventurado é o homem a quem Deus castiga; não desprezes, pois, o castigo do Todo-Poderoso.', 'Jó 5:17', 'Jó', 5, 17, NULL),
  ('bencao', 'E Jesus, respondendo, disse: Em verdade vos digo que ninguém há, que tenha deixado casa, ou irmãos, ou irmãs, ou pai, ou mãe, ou mulher, ou filhos, ou campos, por amor de mim e do evangelho, que não receba cem vezes tanto, já neste tempo, em casas, e irmãos, e irmãs, e mães, e filhos, e campos, com perseguições, e, no século futuro, a vida eterna.', 'Marcos 10:29-30', 'Marcos', 10, 29, 30),
  ('bencao', 'E guardarás os seus estatutos e os seus mandamentos, que te ordeno hoje, para que bem te vá a ti e a teus filhos depois de ti e para que prolongues os dias na terra que o Senhor, teu Deus, te dá para todo o sempre.', 'Deuteronômio 4:40', 'Deuteronômio', 4, 40, NULL),
  ('bencao', 'Quem dera que eles tivessem tal coração que me temessem e guardassem todos os meus mandamentos todos os dias, para que bem lhes fosse a eles e a seus filhos, para sempre!', 'Deuteronômio 5:29', 'Deuteronômio', 5, 29, NULL),
  ('bencao', 'Bem-aventurados sois vós quando vos injuriarem, e perseguirem, e, mentindo, disserem todo o mal contra vós, por minha causa.', 'Mateus 5:11', 'Mateus', 5, 11, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('bencao', 'E abençoou Deus o dia sétimo e o santificou; porque nele descansou de toda a sua obra, que Deus criara e fizera.', 'Gênesis 2:3', 'Gênesis', 2, 3, NULL),
  ('bencao', 'Mas, se deveras melhorardes os vossos caminhos e as vossas obras, se deveras fizerdes juízo entre um homem e entre o seu companheiro, se não oprimirdes o estrangeiro, e o órfão, e a viúva, nem derramardes sangue inocente neste lugar, nem andardes após outros deuses para vosso próprio mal, eu vos farei habitar neste lugar, na terra que dei a vossos pais, de século em século.', 'Jeremias 7:5-7', 'Jeremias', 7, 5, 7),
  ('bencao', 'Ressuscitando Deus a seu Filho Jesus, primeiro o enviou a vós, para que nisso vos abençoasse, e vos desviasse, a cada um, das vossas maldades.', 'Atos 3:26', 'Atos', 3, 26, NULL),
  ('bencao', 'Então, jejuando, e orando, e pondo sobre eles as mãos, os despediram.', 'Atos 13:3', 'Atos', 13, 3, NULL),
  ('bencao', 'E Deus os abençoou e Deus lhes disse: Frutificai, e multiplicai-vos, e enchei a terra, e sujeitai-a; e dominai sobre os peixes do mar, e sobre as aves dos céus, e sobre todo o animal que se move sobre a terra.', 'Gênesis 1:28', 'Gênesis', 1, 28, NULL),
  ('bencao', 'Mas isto lhes ordenei, dizendo: Dai ouvidos à minha voz, e eu serei o vosso Deus, e vós sereis o meu povo; e andai em todo o caminho que eu vos mandar, para que vos vá bem.', 'Jeremias 7:23', 'Jeremias', 7, 23, NULL),
  ('bencao', 'E o Senhor nos ordenou que fizéssemos todos estes estatutos, para temermos ao Senhor, nosso Deus, para o nosso perpétuo bem, para nos guardar em vida, como no dia de hoje.', 'Deuteronômio 6:24', 'Deuteronômio', 6, 24, NULL),
  ('bencao', 'Bem-aventurados os pobres de espírito, porque deles é o Reino dos céus.', 'Mateus 5:3', 'Mateus', 5, 3, NULL),
  ('busca', 'E buscar-me-eis e me achareis quando me buscardes de todo o vosso coração.', 'Jeremias 29:13', 'Jeremias', 29, 13, NULL),
  ('busca', 'O Senhor está convosco, enquanto vós estais com ele, e, se o buscardes, o achareis; porém, se o deixardes, vos deixará.', '2 Crônicas 15:2b', '2 Crônicas 15:2b', NULL, NULL, NULL),
  ('busca', 'Buscai o Senhor e a sua força; buscai a sua face continuamente.', '1 Crônicas 16:11', '1 Crônicas', 16, 11, NULL),
  ('busca', 'Ó Deus, tu és o meu Deus; de madrugada te buscarei; a minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água.', 'Salmo 63:1', 'Salmo', 63, 1, NULL),
  ('busca', 'Pedi, e dar-se-vos-á; buscai e encontrareis; batei, e abrir-se-vos-á.', 'Mateus 7:7', 'Mateus', 7, 7, NULL),
  ('busca', 'Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração.', 'Salmo 37:4', 'Salmo', 37, 4, NULL),
  ('busca', 'E em ti confiarão os que conhecem o teu nome; porque tu, Senhor, nunca desamparaste os que te buscam.', 'Salmo 9:10', 'Salmo', 9, 10, NULL),
  ('busca', 'Busquei ao Senhor, e ele me respondeu; livrou-me de todos os meus temores.', 'Salmo 34:4', 'Salmo', 34, 4, NULL),
  ('busca', 'Buscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto.', 'Isaías 55:6', 'Isaías', 55, 6, NULL),
  ('busca', 'Fui buscado pelos que não perguntavam por mim; fui achado por aqueles que me não buscavam; a um povo que se não chamava do meu nome eu disse: Eis-me aqui.', 'Isaías 65:1', 'Isaías', 65, 1, NULL),
  ('busca', 'Buscai ao Senhor e a sua força; buscai a sua face continuamente.', 'Salmo 105:4', 'Salmo', 105, 4, NULL),
  ('busca', 'Porque assim diz o Senhor à casa de Israel: Buscai-me e vivei.', 'Amós 5:4', 'Amós', 5, 4, NULL),
  ('busca', 'Senhor, tu me sondaste e me conheces. Tu conheces o meu assentar e o meu levantar; de longe entendes o meu pensamento.', 'Salmo 139:1-2', 'Salmo', 139, 1, 2),
  ('busca', 'Porque o Filho do Homem veio buscar e salvar o que se havia perdido.', 'Lucas 19:10', 'Lucas', 19, 10, NULL),
  ('busca', 'Bem-aventurados os que guardam os seus testemunhos e o buscam de todo o coração.', 'Salmo 119:2', 'Salmo', 119, 2, NULL),
  ('busca', 'Os filhos dos leões necessitam e sofrem fome, mas aqueles que buscam ao Senhor de nada têm falta.', 'Salmo 34:10', 'Salmo', 34, 10, NULL),
  ('busca', 'Buscai o bem e não o mal, para que vivais; e assim o Senhor, o Deus dos Exércitos, estará convosco, como dizeis.', 'Amós 5:14', 'Amós', 5, 14, NULL),
  ('busca', 'Ora, sem fé é impossível agradar-lhe, porque é necessário que aquele que se aproxima de Deus creia que ele existe e que é galardoador dos que o buscam.', 'Hebreus 11:6', 'Hebreus', 11, 6, NULL),
  ('busca', 'O que acha uma mulher acha uma coisa boa e alcançou a benevolência do Senhor.', 'Provérbios 18:22', 'Provérbios', 18, 22, NULL),
  ('busca', 'No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder.', 'Efésios 6:10', 'Efésios', 6, 10, NULL),
  ('busca', 'Tal será o conhecimento da sabedoria para a tua alma; se a achares, haverá para ti galardão, e não será cortada a tua expectação.', 'Provérbios 24:14', 'Provérbios', 24, 14, NULL),
  ('busca', 'E andarei em liberdade, pois busquei os teus preceitos.', 'Salmo 119:45', 'Salmo', 119, 45, NULL),
  ('busca', 'A minha alma tem sede de Deus, do Deus vivo; quando entrarei e me apresentarei ante a face de Deus?', 'Salmo 42:2', 'Salmo', 42, 2, NULL),
  ('busca', 'Buscai o Senhor, vós todos os mansos da terra, que pondes por obra o seu juízo; buscai a justiça, buscai a mansidão; porventura sereis escondidos no dia da ira do Senhor.', 'Sofonias 2:3', 'Sofonias', 2, 3, NULL),
  ('busca', 'E eu vos digo a vós: Pedi, e dar-se-vos-á; buscai, e achareis; batei, e abrir-se-vos-á.', 'Lucas 11:9', 'Lucas', 11, 9, NULL),
  ('busca', 'A saber: a vida eterna aos que, com perseverança em fazer bem, procuram glória, e honra, e incorrupção.', 'Romanos 2:7', 'Romanos', 2, 7, NULL),
  ('busca', 'Também o Reino dos céus é semelhante a um tesouro escondido n um campo que um homem achou e escondeu; e, pelo gozo dele, vai, vende tudo quanto tem e compra aquele campo.', 'Mateus 13:44', 'Mateus', 13, 44, NULL),
  ('canto', 'Eu, porém, cantarei a tua força; pela manhã, louvarei com alegria a tua misericórdia, porquanto tu foste o meu alto refúgio e proteção no dia da minha angústia.', 'Salmo 59:16', 'Salmo', 59, 16, NULL),
  ('canto', 'Porque a tua benignidade é melhor do que a vida; os meus lábios te louvarão. Assim, eu te bendirei enquanto viver; em teu nome levantarei as minhas mãos.', 'Salmo 63:3-4', 'Salmo', 63, 3, 4),
  ('canto', 'A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais; cantando ao Senhor com graça em vosso coração.', 'Colossenses 3:16', 'Colossenses', 3, 16, NULL),
  ('canto', 'O Senhor, teu Deus, está no meio de ti, poderoso para te salvar; ele se deleitará em ti com alegria; calar-se-á por seu amor, regozijar-se-á em ti com júbilo.', 'Sofonias 3:17', 'Sofonias', 3, 17, NULL),
  ('canto', 'Perto da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros presos os escutavam.', 'Atos 16:25', 'Atos', 16, 25, NULL),
  ('canto', 'Cantai a Deus, cantai louvores ao seu nome; louvai aquele que vai sobre os céus, pois o seu nome é Jeová; exultai diante dele. Pai de órfãos e juiz de viúvas é Deus no seu lugar santo.', 'Salmo 68:4-5', 'Salmo', 68, 4, 5),
  ('canto', 'Em ti me alegrarei e saltarei de prazer; cantarei louvores ao teu nome, ó Altíssimo.', 'Salmo 9:2', 'Salmo', 9, 2, NULL),
  ('canto', 'Cantarei ao Senhor enquanto eu viver; cantarei louvores ao meu Deus, enquanto existir.', 'Salmo 104:33', 'Salmo', 104, 33, NULL),
  ('canto', 'Mas eu confio na tua benignidade; na tua salvação, meu coração se alegrará. Cantarei ao Senhor, porquanto me tem feito muito bem.', 'Salmo 13:5-6', 'Salmo', 13, 5, 6),
  ('canto', 'Os meus lábios exultarão quando eu te cantar, assim como a minha alma que tu remiste.', 'Salmo 71:23', 'Salmo', 71, 23, NULL),
  ('canto', 'Cantai ao Senhor, porque fez coisas grandiosas; saiba-se isso em toda a terra.', 'Isaías 12:5', 'Isaías', 12, 5, NULL),
  ('canto', 'Louvar-te-ei entre os povos, Senhor, e a ti cantarei salmos entre as nações.', 'Salmo 108:3', 'Salmo', 108, 3, NULL),
  ('canto', 'Tu és o lugar em que me escondo; tu me preservas da angústia; tu me cinges de alegres cantos de livramento. (Selá)', 'Salmo 32:7', 'Salmo', 32, 7, NULL),
  ('canto', 'A ele clamei com a minha boca, e ele foi exaltado pela minha língua.', 'Salmo 66:17', 'Salmo', 66, 17, NULL),
  ('canto', 'Porque eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse. A bênção do que ia perecendo vinha sobre mim, e eu fazia que rejubilasse o coração da viúva.', 'Jó 29:12-13', 'Jó', 29, 12, 13);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('casamento', 'O que acha uma mulher acha uma coisa boa e alcançou a benevolência do Senhor.', 'Provérbios 18:22', 'Provérbios', 18, 22, NULL),
  ('casamento', 'Ele, porém, respondendo, disse-lhes: Não tendes lido que, no princípio, o Criador os fez macho e fêmea e disse: Portanto, deixará o homem pai e mãe e se unirá à sua mulher, e serão dois numa só carne? Assim não são mais dois, mas uma só carne. Portanto, o que Deus ajuntou não separe o homem.', 'Mateus 19:4-6', 'Mateus', 19, 4, 6),
  ('casamento', 'Vós, mulheres, estai sujeitas a vosso próprio marido, como convém no Senhor. Vós, maridos, amai a vossa mulher e não vos irriteis contra ela.', 'Colossenses 3:18-19', 'Colossenses', 3, 18, 19),
  ('casamento', 'Venerado seja entre todos o matrimônio e o leito sem mácula; porém aos que se dão à prostituição e aos adúlteros Deus os julgará.', 'Hebreus 13:4', 'Hebreus', 13, 4, NULL),
  ('casamento', 'Mulher virtuosa, quem a achará? O seu valor muito excede o de rubins.', 'Provérbios 31:10', 'Provérbios', 31, 10, NULL),
  ('casamento', 'Vós, maridos, amai vossa mulher, como também Cristo amou a igreja e a si mesmo se entregou por ela, para a santificar, purificando-a com a lavagem da água, pela palavra.', 'Efésios 5:25-26', 'Efésios', 5, 25, 26),
  ('casamento', 'O coração do homem considera o seu caminho, mas o Senhor lhe dirige os passos.', 'Provérbios 16:9', 'Provérbios', 16, 9, NULL),
  ('casamento', 'Mas, por causa da prostituição, cada um tenha a sua própria mulher, e cada uma tenha o seu próprio marido.', '1 Coríntios 7:2', '1 Coríntios', 7, 2, NULL),
  ('casamento', 'E disse o Senhor Deus: Não é bom que o homem esteja só; far-lhe-ei uma adjutora que esteja como diante dele.', 'Gênesis 2:18', 'Gênesis', 2, 18, NULL),
  ('casamento', 'Quando algum homem tomar uma mulher nova, não sairá à guerra, nem se lhe imporá carga alguma; por um ano inteiro ficará livre na sua casa e alegrará a sua mulher, que tomou.', 'Deuteronômio 24:5', 'Deuteronômio', 24, 5, NULL),
  ('casamento', 'Tu és toda formosa, amiga minha, e em ti não há mancha.', 'Cantares 4:7', 'Cantares', 4, 7, NULL),
  ('casamento', 'E da costela que o Senhor Deus tomou do homem formou uma mulher; e trouxe-a a Adão. E disse Adão: Esta é agora osso dos meus ossos e carne da minha carne; esta será chamada varoa, porquanto do varão foi tomada. Portanto, deixará o varão o seu pai e a sua mãe e apegar-se-á à sua mulher, e serão ambos uma carne.', 'Gênesis 2:22-24', 'Gênesis', 2, 22, 24),
  ('casamento', 'Vós, mulheres, sujeitai-vos a vosso marido, como ao Senhor; porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo.', 'Efésios 5:22-23', 'Efésios', 5, 22, 23),
  ('casamento', 'O marido pague à mulher a devida benevolência, e da mesma sorte a mulher, ao marido. A mulher não tem poder sobre o seu próprio corpo, mas tem-no o marido; e também, da mesma maneira, o marido não tem poder sobre o seu próprio corpo, mas tem-no a mulher.', '1 Coríntios 7:3-4', '1 Coríntios', 7, 3, 4),
  ('casamento', 'Igualmente vós, maridos, coabitai com ela com entendimento, dando honra à mulher, como vaso mais fraco; como sendo vós os seus coerdeiros da graça da vida; para que não sejam impedidas as vossas orações.', '1 Pedro 3:7', '1 Pedro', 3, 7, NULL),
  ('casamento', 'Por isso, deixará o homem seu pai e sua mãe e se unirá à sua mulher; e serão dois numa carne.', 'Efésios 5:31', 'Efésios', 5, 31, NULL),
  ('casamento', 'Assim devem os maridos amar a sua própria mulher como a seu próprio corpo. Quem ama a sua mulher ama-se a si mesmo.', 'Efésios 5:28', 'Efésios', 5, 28, NULL),
  ('casamento', 'Não vos defraudeis um ao outro, senão por consentimento mútuo, por algum tempo, para vos aplicardes à oração; e, depois, ajuntai-vos outra vez, para que Satanás vos não tente pela vossa incontinência.', '1 Coríntios 7:5', '1 Coríntios', 7, 5, NULL),
  ('casamento', 'Assim também vós, cada um em particular ame a sua própria mulher como a si mesmo, e a mulher reverencie o marido.', 'Efésios 5:33', 'Efésios', 5, 33, NULL),
  ('casamento', 'Ouvistes que foi dito aos antigos: Não cometerás adultério. Eu porém, vos digo que qualquer que atentar numa mulher para a cobiçar já em seu coração cometeu adultério com ela.', 'Mateus 5:27-28', 'Mateus', 5, 27, 28),
  ('casamento', 'Regozijar-me-ei muito no Senhor, a minha alma se alegra no meu Deus, porque me vestiu de vestes de salvação, me cobriu com o manto de justiça, como um noivo que se adorna com atavios e como noiva que se enfeita com as suas joias.', 'Isaías 61:10', 'Isaías', 61, 10, NULL),
  ('casamento', 'Porém, desde o princípio da criação, Deus os fez macho e fêmea. Por isso, deixará o homem a seu pai e a sua mãe e unir-se-á a sua mulher. E serão os dois uma só carne e, assim, já não serão dois, mas uma só carne. Portanto, o que Deus ajuntou, não o separe o homem.', 'Marcos 10:6-9', 'Marcos', 10, 6, 9),
  ('ceu', 'Porque o mesmo Senhor descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus; e os que morreram em Cristo ressuscitarão primeiro; depois, nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o Senhor nos ares, e assim estaremos sempre com o Senhor.', '1 Tessalonicenses 4:16-17', '1 Tessalonicenses', 4, 16, 17),
  ('ceu', 'Na casa de meu Pai há muitas moradas; se não fosse assim, eu vo-lo teria dito, pois vou preparar-vos lugar.', 'João 14:2', 'João', 14, 2, NULL),
  ('ceu', 'Pensai nas coisas que são de cima e não nas que são da terra.', 'Colossenses 3:2', 'Colossenses', 3, 2, NULL),
  ('ceu', 'Mas a nossa cidade está nos céus, donde também esperamos o Salvador, o Senhor Jesus Cristo.', 'Filipenses 3:20', 'Filipenses', 3, 20, NULL),
  ('ceu', 'A quem tenho eu no céu senão a ti? E na terra não há quem eu deseje além de ti.', 'Salmo 73:25', 'Salmo', 73, 25, NULL),
  ('ceu', 'Os céus manifestam a glória de Deus e o firmamento anuncia a obra das suas mãos. Um dia faz declaração a outro dia, e uma noite mostra sabedoria a outra noite.', 'Salmo 19:1-2', 'Salmo', 19, 1, 2),
  ('ceu', 'Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu.', 'Eclesiastes 3:1', 'Eclesiastes', 3, 1, NULL),
  ('ceu', 'Não ajunteis tesouros na terra, onde a traça e a ferrugem tudo consomem, e onde os ladrões minam e roubam. Mas ajuntai tesouros no céu, onde nem a traça nem a ferrugem consomem, e onde os ladrões não minam, nem roubam.', 'Mateus 6:19-20', 'Mateus', 6, 19, 20),
  ('ceu', 'E o Senhor me livrará de toda má obra e guardar-me-á para o seu Reino celestial; a quem seja glória para todo o sempre. Amém!', '2 Timóteo 4:18', '2 Timóteo', 4, 18, NULL),
  ('ceu', 'O céu e a terra passarão, mas as minhas palavras não hão de passar.', 'Mateus 24:35', 'Mateus', 24, 35, NULL),
  ('ceu', 'E, quando dizia isto, vendo-o eles, foi elevado às alturas, e uma nuvem o recebeu, ocultando-o a seus olhos.', 'Atos 1:9', 'Atos', 1, 9, NULL),
  ('ceu', 'Porque sabemos que, se a nossa casa terrestre deste tabernáculo se desfizer, temos de Deus um edifício, uma casa não feita por mãos, eterna, nos céus.', '2 Coríntios 5:1', '2 Coríntios', 5, 1, NULL),
  ('ceu', 'Porque não temos que lutar contra carne e sangue, mas, sim, contra os principados, contra as potestades, contra os príncipes das trevas deste século, contra as hostes espirituais da maldade, nos lugares celestiais.', 'Efésios 6:12', 'Efésios', 6, 12, NULL),
  ('ceu', 'Exalta-te sobre os céus, ó Deus, e a tua glória sobre toda a terra.', 'Salmo 108:5', 'Salmo', 108, 5, NULL),
  ('ceu', 'Jesus, porém, disse: Deixai os pequeninos e não os estorveis de vir a mim, porque dos tais é o Reino dos céus.', 'Mateus 19:14', 'Mateus', 19, 14, NULL),
  ('ceu', 'Ah! Senhor Jeová! Eis que tu fizeste os céus e a terra com o teu grande poder e com o teu braço estendido; não te é maravilhosa demais coisa alguma.', 'Jeremias 32:17', 'Jeremias', 32, 17, NULL),
  ('ceu', 'E levou-os fora, até Betânia; e, levantando as mãos, os abençoou. E aconteceu que, abençoando-os ele, se apartou deles e foi elevado ao céu.', 'Lucas 24:50-51', 'Lucas', 24, 50, 51),
  ('ceu', 'O nosso socorro está em o nome do Senhor, que fez o céu e a terra.', 'Salmo 124:8', 'Salmo', 124, 8, NULL),
  ('ceu', 'Amados, agora somos filhos de Deus, e ainda não é manifesto o que havemos de ser. Mas sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como é o veremos. E qualquer que nele tem esta esperança purifica-se a si mesmo, como também ele é puro.', '1 João 3:2-3', '1 João', 3, 2, 3),
  ('ceu', 'Ele é o que edifica as suas câmaras no céu, e a sua abóbada fundou na terra, e o que chama as águas do mar, e as derrama sobre a terra; o Senhor é o seu nome.', 'Amós 9:6', 'Amós', 9, 6, NULL),
  ('ceu', 'Porque nada trouxemos para este mundo e manifesto é que nada podemos levar dele. Tendo, porém, sustento e com que nos cobrirmos, estejamos com isso contentes.', '1 Timóteo 6:7-8', '1 Timóteo', 6, 7, 8),
  ('ceu', 'Porque, assim como os céus são mais altos do que a terra, assim são os meus caminhos mais altos do que os vossos caminhos, e os meus pensamentos, mais altos do que os vossos pensamentos.', 'Isaías 55:9', 'Isaías', 55, 9, NULL),
  ('ceu', 'E, estando com os olhos fitos no céu, enquanto ele subia, eis que junto deles se puseram dois varões vestidos de branco, os quais lhes disseram: Varões galileus, por que estais olhando para o céu? Esse Jesus, que dentre vós foi recebido em cima no céu, há de vir assim como para o céu o vistes ir.', 'Atos 1:10-11', 'Atos', 1, 10, 11),
  ('ceu', 'E, no Hades, ergueu os olhos, estando em tormentos, e viu ao longe Abraão e Lázaro, no seu seio. E, clamando, disse: Abraão, meu pai, tem misericórdia de mim e manda a Lázaro que molhe na água a ponta do seu dedo e me refresque a língua, porque estou atormentado nesta chama.', 'Lucas 16:23-24', 'Lucas', 16, 23, 24),
  ('ceu', 'Esconder-se-ia alguém em esconderijos, de modo que eu não o veja? — diz o Senhor. Porventura, não encho eu os céus e a terra? — diz o Senhor.', 'Jeremias 23:24', 'Jeremias', 23, 24, NULL),
  ('ceu', 'Como saiu do ventre de sua mãe, assim nu voltará, indo-se como veio; e nada tomará do seu trabalho, que possa levar na sua mão.', 'Eclesiastes 5:15', 'Eclesiastes', 5, 15, NULL),
  ('ceu', 'Ao que vencer, lhe concederei que se assente comigo no meu trono, assim como eu venci e me assentei com meu Pai no seu trono.', 'Apocalipse 3:21', 'Apocalipse', 3, 21, NULL),
  ('ceu', 'E eu te darei as chaves do Reino dos céus, e tudo o que ligares na terra será ligado nos céus, e tudo o que desligares na terra será desligado nos céus.', 'Mateus 16:19', 'Mateus', 16, 19, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('ceu', 'Ora, o Senhor, depois de lhes ter falado, foi recebido no céu e assentou-se à direita de Deus.', 'Marcos 16:19', 'Marcos', 16, 19, NULL),
  ('ceu', 'Pelo que hoje saberás e refletirás no teu coração que só o Senhor é Deus em cima no céu e embaixo na terra; nenhum outro há.', 'Deuteronômio 4:39', 'Deuteronômio', 4, 39, NULL),
  ('ceu', 'Disse-lhe Jesus: Se queres ser perfeito, vai, vende tudo o que tens, dá-o aos pobres e terás um tesouro no céu; e vem e segue-me.', 'Mateus 19:21', 'Mateus', 19, 21, NULL),
  ('ceu', 'Mas não vos alegreis porque se vos sujeitem os espíritos; alegrai-vos, antes, por estar o vosso nome escrito nos céus.', 'Lucas 10:20', 'Lucas', 10, 20, NULL),
  ('ceu', 'No princípio, criou Deus os céus e a terra. E a terra era sem forma e vazia; e havia trevas sobre a face do abismo; e o Espírito de Deus se movia sobre a face das águas.', 'Gênesis 1:1-2', 'Gênesis', 1, 1, 2),
  ('ceu', 'Pela palavra do Senhor foram feitos os céus; e todo o exército deles, pelo espírito da sua boca.', 'Salmo 33:6', 'Salmo', 33, 6, NULL),
  ('ceu', 'O que vencer será vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; e confessarei o seu nome diante de meu Pai e diante dos seus anjos.', 'Apocalipse 3:5', 'Apocalipse', 3, 5, NULL),
  ('ceu', 'E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo e recebido acima, na glória.', '1 Timóteo 3:16', '1 Timóteo', 3, 16, NULL),
  ('ceu', 'Digo-vos que assim haverá alegria no céu por um pecador que se arrepende, mais do que por noventa e nove justos que não necessitam de arrependimento.', 'Lucas 15:7', 'Lucas', 15, 7, NULL),
  ('ceu', 'Para onde me irei do teu Espírito ou para onde fugirei da tua face? Se subir ao céu, tu aí estás; se fizer no Seol a minha cama, eis que tu ali estás também.', 'Salmo 139:7-8', 'Salmo', 139, 7, 8),
  ('ceu', 'Cumprindo-se o dia de Pentecostes, estavam todos reunidos no mesmo lugar; e, de repente, veio do céu um som, como de um vento veemente e impetuoso, e encheu toda a casa em que estavam assentados.', 'Atos 2:1-2', 'Atos', 2, 1, 2),
  ('ceu', 'Pelo que também Deus o exaltou soberanamente e lhe deu um nome que é sobre todo o nome, para que ao nome de Jesus se dobre todo joelho dos que estão nos céus, e na terra, e debaixo da terra.', 'Filipenses 2:9-10', 'Filipenses', 2, 9, 10),
  ('ceu', 'Sê exaltado, ó Deus, sobre os céus; seja a tua glória sobre toda a terra.', 'Salmo 57:5', 'Salmo', 57, 5, NULL),
  ('ceu', 'Portanto, vós orareis assim: Pai nosso, que estás nos céus, santificado seja o teu nome. Venha o teu Reino. Seja feita a tua vontade, tanto na terra como no céu.', 'Mateus 6:9-10', 'Mateus', 6, 9, 10),
  ('ceu', 'Desde então, começou Jesus a pregar e a dizer: Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 4:17', 'Mateus', 4, 17, NULL),
  ('ceu', 'Mas o nosso Deus está nos céus e faz tudo o que lhe apraz.', 'Salmo 115:3', 'Salmo', 115, 3, NULL),
  ('ceu', 'Nem todo o que me diz: Senhor, Senhor! entrará no Reino dos céus, mas aquele que faz a vontade de meu Pai, que está nos céus.', 'Mateus 7:21', 'Mateus', 7, 21, NULL),
  ('ceu', 'Qualquer, pois, que violar um destes menores mandamentos e assim ensinar aos homens será chamado o menor no Reino dos céus; aquele, porém, que os cumprir e ensinar será chamado grande no Reino dos céus.', 'Mateus 5:19', 'Mateus', 5, 19, NULL),
  ('ceu', 'Eu sou o pão vivo que desceu do céu; se alguém comer desse pão, viverá para sempre; e o pão que eu der é a minha carne, que eu darei pela vida do mundo.', 'João 6:51', 'João', 6, 51, NULL),
  ('ceu', 'Bendito o Deus e Pai de nosso Senhor Jesus Cristo, o qual nos abençoou com todas as bênçãos espirituais nos lugares celestiais em Cristo.', 'Efésios 1:3', 'Efésios', 1, 3, NULL),
  ('ceu', 'Porque em verdade vos digo que, até que o céu e a terra passem, nem um jota ou um til se omitirá da lei sem que tudo seja cumprido.', 'Mateus 5:18', 'Mateus', 5, 18, NULL),
  ('ceu', 'Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 3:2', 'Mateus', 3, 2, NULL),
  ('ceu', 'E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles e será o seu Deus. E Deus limpará de seus olhos toda lágrima, e não haverá mais morte, nem pranto, nem clamor, nem dor, porque já as primeiras coisas são passadas.', 'Apocalipse 21:3-4', 'Apocalipse', 21, 3, 4),
  ('ceu', 'Bem-aventurados os pobres de espírito, porque deles é o Reino dos céus.', 'Mateus 5:3', 'Mateus', 5, 3, NULL),
  ('ceu', 'Eu, porém, vos digo que, de maneira nenhuma, jureis nem pelo céu, porque é o trono de Deus, nem pela terra, porque é o escabelo de seus pés, nem por Jerusalém, porque é a cidade do grande Rei.', 'Mateus 5:34-35', 'Mateus', 5, 34, 35),
  ('ceu', 'Mas o Dia do Senhor virá como o ladrão de noite, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se desfarão, e a terra e as obras que nela há se queimarão.', '2 Pedro 3:10', '2 Pedro', 3, 10, NULL),
  ('ceu', 'Também o Reino dos céus é semelhante a um tesouro escondido n um campo que um homem achou e escondeu; e, pelo gozo dele, vai, vende tudo quanto tem e compra aquele campo.', 'Mateus 13:44', 'Mateus', 13, 44, NULL),
  ('chamada', 'Não me escolhestes vós a mim, mas eu vos escolhi a vós, e vos nomeei, para que vades e deis fruto, e o vosso fruto permaneça, a fim de que tudo quanto em meu nome pedirdes ao Pai ele vos conceda.', 'João 15:16', 'João', 15, 16, NULL),
  ('chamada', 'Fiel é o que vos chama, o qual também o fará.', '1 Tessalonicenses 5:24', '1 Tessalonicenses', 5, 24, NULL),
  ('chamada', 'E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu decreto.', 'Romanos 8:28', 'Romanos', 8, 28, NULL),
  ('chamada', 'E Deus escolheu as coisas vis deste mundo, e as desprezíveis, e as que não são para aniquilar as que são; para que nenhuma carne se glorie perante ele.', '1 Coríntios 1:28-29', '1 Coríntios', 1, 28, 29),
  ('chamada', 'Para o que, pelo nosso evangelho, vos chamou, para alcançardes a glória de nosso Senhor Jesus Cristo.', '2 Tessalonicenses 2:14', '2 Tessalonicenses', 2, 14, NULL),
  ('chamada', 'Porque para isto sois chamados, pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas.', '1 Pedro 2:21', '1 Pedro', 2, 21, NULL),
  ('chamada', 'Portanto, irmãos, procurai fazer cada vez mais firme a vossa vocação e eleição; porque, fazendo isto, nunca jamais tropeçareis. Porque assim vos será amplamente concedida a entrada no Reino eterno de nosso Senhor e Salvador Jesus Cristo.', '2 Pedro 1:10-11', '2 Pedro', 1, 10, 11),
  ('chamada', 'Prossigo para o alvo, pelo prêmio da soberana vocação de Deus em Cristo Jesus.', 'Filipenses 3:14', 'Filipenses', 3, 14, NULL),
  ('chamada', 'Que nos salvou e chamou com uma santa vocação; não segundo as nossas obras, mas segundo o seu próprio propósito e graça que nos foi dada em Cristo Jesus, antes dos tempos dos séculos.', '2 Timóteo 1:9', '2 Timóteo', 1, 9, NULL),
  ('chamada', 'Fui buscado pelos que não perguntavam por mim; fui achado por aqueles que me não buscavam; a um povo que se não chamava do meu nome eu disse: Eis-me aqui.', 'Isaías 65:1', 'Isaías', 65, 1, NULL),
  ('chamada', 'Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo, nosso Senhor.', '1 Coríntios 1:9', '1 Coríntios', 1, 9, NULL),
  ('chamada', 'Há um só corpo e um só Espírito, como também fostes chamados em uma só esperança da vossa vocação.', 'Efésios 4:4', 'Efésios', 4, 4, NULL),
  ('chamada', 'Mas, como é santo aquele que vos chamou, sede vós também santos em toda a vossa maneira de viver, porquanto escrito está: Sede santos, porque eu sou santo.', '1 Pedro 1:15-16', '1 Pedro', 1, 15, 16),
  ('chamada', 'Não tornando mal por mal ou injúria por injúria; antes, pelo contrário, bendizendo, sabendo que para isto fostes chamados, para que, por herança, alcanceis a bênção.', '1 Pedro 3:9', '1 Pedro', 3, 9, NULL),
  ('chamada', 'E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo.', 'Atos 2:38', 'Atos', 2, 38, NULL),
  ('colheita', 'Ora, aquele que dá a semente ao que semeia e pão para comer também multiplicará a vossa sementeira e aumentará os frutos da vossa justiça.', '2 Coríntios 9:10', '2 Coríntios', 9, 10, NULL),
  ('colheita', 'E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não houvermos desfalecido.', 'Gálatas 6:9', 'Gálatas', 6, 9, NULL),
  ('colheita', 'Não erreis: Deus não se deixa escarnecer; porque tudo o que o homem semear, isso também ceifará.', 'Gálatas 6:7', 'Gálatas', 6, 7, NULL),
  ('colheita', 'E digo isto: Que o que semeia pouco pouco também ceifará; e o que semeia em abundância em abundância também ceifará.', '2 Coríntios 9:6', '2 Coríntios', 9, 6, NULL),
  ('colheita', 'Porquanto, ainda que a figueira não floresça, nem haja fruto na vide; o produto da oliveira minta, e os campos não produzam mantimento; as ovelhas da malhada sejam arrebatadas, e nos currais não haja vacas, todavia, eu me alegrarei no Senhor, exultarei no Deus da minha salvação.', 'Habacuque 3:17-18', 'Habacuque', 3, 17, 18),
  ('colheita', 'Honra ao Senhor com a tua fazenda e com as primícias de toda a tua renda.', 'Provérbios 3:9', 'Provérbios', 3, 9, NULL),
  ('colheita', 'Se andardes nos meus estatutos, e guardardes os meus mandamentos, e os fizerdes, então, eu vos darei as vossas chuvas a seu tempo; e a terra dará a sua novidade, e a árvore do campo dará o seu fruto.', 'Levítico 26:3-4', 'Levítico', 26, 3, 4),
  ('colheita', 'Porque o que semeia na sua carne da carne ceifará a corrupção; mas o que semeia no Espírito do Espírito ceifará a vida eterna.', 'Gálatas 6:8', 'Gálatas', 6, 8, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('colheita', 'Olhai para as aves do céu, que não semeiam, nem segam, nem ajuntam em celeiros; e vosso Pai celestial as alimenta. Não tendes vós muito mais valor do que elas?', 'Mateus 6:26', 'Mateus', 6, 26, NULL),
  ('colheita', 'Ora, o fruto da justiça semeia-se na paz, para os que exercitam a paz.', 'Tiago 3:18', 'Tiago', 3, 18, NULL),
  ('colheita', 'E, na verdade, toda correção, ao presente, não parece ser de gozo, senão de tristeza, mas, depois, produz um fruto pacífico de justiça nos exercitados por ela.', 'Hebreus 12:11', 'Hebreus', 12, 11, NULL),
  ('colheita', 'Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa, e depois fazei prova de mim, diz o Senhor dos Exércitos, se eu não vos abrir as janelas do céu e não derramar sobre vós uma bênção tal, que dela vos advenha a maior abastança.', 'Malaquias 3:10', 'Malaquias', 3, 10, NULL),
  ('colheita', 'A vide se secou, a figueira se murchou; a romeira também, e a palmeira, e a macieira; todas as árvores do campo se secaram, e a alegria se secou entre os filhos dos homens.', 'Joel 1:12', 'Joel', 1, 12, NULL),
  ('compaixao', 'Antes, sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.', 'Efésios 4:32', 'Efésios', 4, 32, NULL),
  ('compaixao', 'As misericórdias do Senhor são a causa de não sermos consumidos; porque as suas misericórdias não têm fim. Novas são cada manhã; grande é a tua fidelidade.', 'Lamentações 3:22-23', 'Lamentações', 3, 22, 23),
  ('compaixao', 'E, finalmente, sede todos de um mesmo sentimento, compassivos, amando os irmãos, entranhavelmente misericordiosos e afáveis.', '1 Pedro 3:8', '1 Pedro', 3, 8, NULL),
  ('compaixao', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda consolação, que nos consola em toda a nossa tribulação, para que também possamos consolar os que estiverem em alguma tribulação, com a consolação com que nós mesmos somos consolados de Deus.', '2 Coríntios 1:3-4', '2 Coríntios', 1, 3, 4),
  ('compaixao', 'Revesti-vos, pois, como eleitos de Deus, santos e amados, de entranhas de misericórdia, de benignidade, humildade, mansidão, longanimidade.', 'Colossenses 3:12', 'Colossenses', 3, 12, NULL),
  ('compaixao', 'Alegrai-vos com os que se alegram e chorai com os que choram.', 'Romanos 12:15', 'Romanos', 12, 15, NULL),
  ('compaixao', 'Assim falou o Senhor dos Exércitos, dizendo: Executai juízo verdadeiro, mostrai piedade e misericórdia cada um a seu irmão; e não oprimais a viúva, nem o órfão, nem o estrangeiro, nem o pobre, nem intente o mal cada um contra o seu irmão, no seu coração.', 'Zacarias 7:9-10', 'Zacarias', 7, 9, 10),
  ('compaixao', 'Quem, pois, tiver bens do mundo e, vendo o seu irmão necessitado, lhe cerrar o seu coração, como estará nele o amor de Deus?', '1 João 3:17', '1 João', 3, 17, NULL),
  ('compaixao', 'Pode uma mulher esquecer-se tanto do filho que cria, que se não compadeça dele, do filho do seu ventre? Mas, ainda que esta se esquecesse, eu, todavia, me não esquecerei de ti. Eis que, na palma das minhas mãos, te tenho gravado; os teus muros estão continuamente perante mim.', 'Isaías 49:15-16', 'Isaías', 49, 15, 16),
  ('compaixao', 'Como um pai se compadece de seus filhos, assim o Senhor se compadece daqueles que o temem.', 'Salmo 103:13', 'Salmo', 103, 13, NULL),
  ('compaixao', 'Por isso, o Senhor esperará para ter misericórdia de vós; e, por isso, será exalçado para se compadecer de vós, porque o Senhor é um Deus de equidade. Bem-aventurados todos os que nele esperam.', 'Isaías 30:18', 'Isaías', 30, 18, NULL),
  ('compaixao', 'Porque as montanhas se desviarão e os outeiros tremerão; mas a minha benignidade não se desviará de ti, e o concerto da minha paz não mudará, diz o Senhor, que se compadece de ti.', 'Isaías 54:10', 'Isaías', 54, 10, NULL),
  ('compaixao', 'Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado.', 'Hebreus 4:15', 'Hebreus', 4, 15, NULL),
  ('compaixao', 'E fortalecerei a casa de Judá, e salvarei a casa de José, e tornarei a plantá-los, porque me apiedei deles; e serão como se os não tivera rejeitado; porque eu sou o Senhor, seu Deus, e os ouvirei.', 'Zacarias 10:6', 'Zacarias', 10, 6, NULL),
  ('compaixao', 'Tornará a apiedar-se de nós, subjugará as nossas iniquidades e lançará todos os nossos pecados nas profundezas do mar.', 'Miqueias 7:19', 'Miqueias', 7, 19, NULL),
  ('compaixao', 'Mas tu, Senhor, és um Deus cheio de compaixão, e piedoso, e sofredor, e grande em benignidade e em verdade.', 'Salmo 86:15', 'Salmo', 86, 15, NULL),
  ('compreensao', 'Clama a mim, e responder-te-ei e anunciar-te-ei coisas grandes e firmes, que não sabes.', 'Jeremias 33:3', 'Jeremias', 33, 3, NULL),
  ('compreensao', 'Assim como tu não sabes qual o caminho do vento, nem como se formam os ossos no ventre da que está grávida, assim também não sabes as obras de Deus, que faz todas as coisas.', 'Eclesiastes 11:5', 'Eclesiastes', 11, 5, NULL),
  ('compreensao', 'O longânimo é grande em entendimento, mas o de ânimo precipitado exalta a loucura.', 'Provérbios 14:29', 'Provérbios', 14, 29, NULL),
  ('compreensao', 'Instruir-te-ei e ensinar-te-ei o caminho que deves seguir; guiar-te-ei com os meus olhos.', 'Salmo 32:8', 'Salmo', 32, 8, NULL),
  ('compreensao', 'A sabedoria é a coisa principal; adquire, pois, a sabedoria; sim, com tudo o que possuis, adquire o conhecimento.', 'Provérbios 4:7', 'Provérbios', 4, 7, NULL),
  ('compreensao', 'Todo caminho do homem é reto aos seus olhos, mas o Senhor sonda os corações.', 'Provérbios 21:2', 'Provérbios', 21, 2, NULL),
  ('compreensao', 'Não atentando nós nas coisas que se veem, mas nas que se não veem; porque as que se veem são temporais, e as que se não veem são eternas.', '2 Coríntios 4:18', '2 Coríntios', 4, 18, NULL),
  ('compreensao', 'Para que o Deus de nosso Senhor Jesus Cristo, o Pai da glória, vos dê em seu conhecimento o espírito de sabedoria e de revelação.', 'Efésios 1:17', 'Efésios', 1, 17, NULL),
  ('compreensao', 'Muitos propósitos há no coração do homem, mas o conselho do Senhor permanecerá.', 'Provérbios 19:21', 'Provérbios', 19, 21, NULL),
  ('compreensao', 'Examinai tudo. Retende o bem. Abstende-vos de toda aparência do mal.', '1 Tessalonicenses 5:21-22', '1 Tessalonicenses', 5, 21, 22),
  ('compreensao', 'A exposição das tuas palavras dá luz e dá entendimento aos símplices.', 'Salmo 119:130', 'Salmo', 119, 130, NULL),
  ('compreensao', 'E Jesus, olhando para eles, disse-lhes: Aos homens é isso impossível, mas a Deus tudo é possível.', 'Mateus 19:26', 'Mateus', 19, 26, NULL),
  ('compreensao', 'Porque, assim como os céus são mais altos do que a terra, assim são os meus caminhos mais altos do que os vossos caminhos, e os meus pensamentos, mais altos do que os vossos pensamentos.', 'Isaías 55:9', 'Isaías', 55, 9, NULL),
  ('compreensao', 'Não sabes, não ouviste que o eterno Deus, o Senhor, o Criador dos confins da terra, nem se cansa, nem se fatiga? Não há esquadrinhação do seu entendimento.', 'Isaías 40:28', 'Isaías', 40, 28, NULL),
  ('compreensao', 'Porque, andando na carne, não militamos segundo a carne.', '2 Coríntios 10:3', '2 Coríntios', 10, 3, NULL),
  ('compreensao', 'Antes, crescei na graça e conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele seja dada a glória, assim agora como no dia da eternidade. Amém!', '2 Pedro 3:18', '2 Pedro', 3, 18, NULL),
  ('compreensao', 'Ai daquele que contende com o seu Criador, caco entre outros cacos de barro! Porventura, dirá o barro ao que o formou: Que fazes? Ou a tua obra: Não tens mãos?', 'Isaías 45:9', 'Isaías', 45, 9, NULL),
  ('compreensao', 'Ó profundidade das riquezas, tanto da sabedoria, como da ciência de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis, os seus caminhos!', 'Romanos 11:33', 'Romanos', 11, 33, NULL),
  ('compreensao', 'Bem-aventurado o homem que acha sabedoria, e o homem que adquire conhecimento.', 'Provérbios 3:13', 'Provérbios', 3, 13, NULL),
  ('compreensao', 'Adquire a sabedoria, adquire a inteligência e não te esqueças nem te apartes das palavras da minha boca.', 'Provérbios 4:5', 'Provérbios', 4, 5, NULL),
  ('compreensao', 'Para que os seus corações sejam consolados, e estejam unidos em amor e enriquecidos da plenitude da inteligência, para conhecimento do mistério de Deus — Cristo.', 'Colossenses 2:2', 'Colossenses', 2, 2, NULL),
  ('compreensao', 'Ninguém, sendo tentado, diga: De Deus sou tentado; porque Deus não pode ser tentado pelo mal e a ninguém tenta.', 'Tiago 1:13', 'Tiago', 1, 13, NULL),
  ('compreensao', 'O temor do Senhor é o princípio da sabedoria, e a ciência do Santo, a prudência.', 'Provérbios 9:10', 'Provérbios', 9, 10, NULL),
  ('compreensao', 'Jesus respondeu e disse-lhe: Na verdade, na verdade te digo que aquele que não nascer de novo não pode ver o Reino de Deus.', 'João 3:3', 'João', 3, 3, NULL),
  ('compreensao', 'Porque mil anos são aos teus olhos como o dia de ontem que passou, e como a vigília da noite.', 'Salmo 90:4', 'Salmo', 90, 4, NULL),
  ('compreensao', 'Nisto não há judeu nem grego; não há servo nem livre; não há macho nem fêmea; porque todos vós sois um em Cristo Jesus.', 'Gálatas 3:28', 'Gálatas', 3, 28, NULL),
  ('compreensao', 'E ele, assentando-se, chamou os doze e disse-lhes: Se alguém quiser ser o primeiro, será o derradeiro de todos e o servo de todos.', 'Marcos 9:35', 'Marcos', 9, 35, NULL),
  ('compreensao', 'Senhor, tu me sondaste e me conheces. Tu conheces o meu assentar e o meu levantar; de longe entendes o meu pensamento.', 'Salmo 139:1-2', 'Salmo', 139, 1, 2),
  ('compreensao', 'Antes que os montes nascessem, ou que tu formasses a terra e o mundo, sim, de eternidade a eternidade, tu és Deus.', 'Salmo 90:2', 'Salmo', 90, 2, NULL);

