-- Parte 03: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('compreensao', 'E sabemos que já o Filho de Deus é vindo e nos deu entendimento para conhecermos o que é verdadeiro; e no que é verdadeiro estamos, isto é, em seu Filho Jesus Cristo. Este é o verdadeiro Deus e a vida eterna.', '1 João 5:20', '1 João', 5, 20, NULL),
  ('compreensao', 'Grande é o Senhor', 'Salmo 145:3', 'Salmo', 145, 3, NULL),
  ('compreensao', 'Tendo iluminados os olhos do vosso entendimento, para que saibais qual seja a esperança da sua vocação e quais as riquezas da glória da sua herança nos santos.', 'Efésios 1:18', 'Efésios', 1, 18, NULL),
  ('compreensao', 'Mas Deus no-las revelou pelo seu Espírito; porque o Espírito penetra todas as coisas, ainda as profundezas de Deus.', '1 Coríntios 2:10', '1 Coríntios', 2, 10, NULL),
  ('compreensao', 'Tudo fez formoso em seu tempo; também pôs o mundo no coração deles, sem que o homem possa descobrir a obra que Deus fez desde o princípio até ao fim.', 'Eclesiastes 3:11', 'Eclesiastes', 3, 11, NULL),
  ('compreensao', 'Quem é sábio, para que entenda estas coisas? Prudente, para que as saiba? Porque os caminhos do Senhor', 'Oseias 14:9', 'Oseias', 14, 9, NULL),
  ('compreensao', 'Muitos serão purificados, e embranquecidos, e provados; mas os ímpios procederão impiamente, e nenhum dos ímpios entenderá, mas os sábios entenderão.', 'Daniel 12:10', 'Daniel', 12, 10, NULL),
  ('compreensao', 'Vigiai justamente e não pequeis; porque alguns ainda não têm o conhecimento de Deus; digo-o para vergonha vossa.', '1 Coríntios 15:34', '1 Coríntios', 15, 34, NULL),
  ('compreensao', 'O que ama a correção ama o conhecimento, mas o que aborrece a repreensão é um bruto.', 'Provérbios 12:1', 'Provérbios', 12, 1, NULL),
  ('compreensao', 'Sem que haja uma palavra na minha língua, eis que, ó Senhor', 'Salmo 139:4', 'Salmo', 139, 4, NULL),
  ('compreensao', 'Porque qual dos homens sabe as coisas do homem, senão o espírito do homem, que nele está? Assim também ninguém sabe as coisas de Deus, senão o Espírito de Deus.', '1 Coríntios 2:11', '1 Coríntios', 2, 11, NULL),
  ('compreensao', 'Mas o nosso Deus está nos céus e faz tudo o que lhe apraz.', 'Salmo 115:3', 'Salmo', 115, 3, NULL),
  ('compreensao', 'Então, entrou também o outro discípulo, que chegara primeiro ao sepulcro, e viu, e creu. Porque ainda não sabiam a Escritura, que diz que era necessário que ressuscitasse dos mortos.', 'João 20:8-9', 'João', 20, 8, 9),
  ('comunidade', 'E consideremo-nos uns aos outros, para nos estimularmos ao amor e às boas obras, não deixando a nossa congregação, como é costume de alguns; antes, admoestando-nos uns aos outros; e tanto mais quanto vedes que se vai aproximando aquele Dia.', 'Hebreus 10:24-25', 'Hebreus', 10, 24, 25),
  ('comunidade', 'Porque assim como em um corpo temos muitos membros, e nem todos os membros têm a mesma operação, assim nós, que somos muitos, somos um só corpo em Cristo, mas individualmente somos membros uns dos outros.', 'Romanos 12:4-5', 'Romanos', 12, 4, 5),
  ('comunidade', 'Oh! Quão bom e quão suave é que os irmãos vivam em união!', 'Salmo 133:1', 'Salmo', 133, 1, NULL),
  ('comunidade', 'Porque onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles.', 'Mateus 18:20', 'Mateus', 18, 20, NULL),
  ('comunidade', 'E, finalmente, sede todos de um mesmo sentimento, compassivos, amando os irmãos, entranhavelmente misericordiosos e afáveis.', '1 Pedro 3:8', '1 Pedro', 3, 8, NULL),
  ('comunidade', 'Rogo-vos, porém, irmãos, pelo nome de nosso Senhor Jesus Cristo, que digais todos uma mesma coisa e que não haja entre vós dissensões; antes, sejais unidos, em um mesmo sentido e em um mesmo parecer.', '1 Coríntios 1:10', '1 Coríntios', 1, 10, NULL),
  ('comunidade', 'E, perseverando unânimes todos os dias no templo e partindo o pão em casa, comiam juntos com alegria e singeleza de coração, louvando a Deus e caindo na graça de todo o povo. E todos os dias acrescentava o Senhor à igreja aqueles que se haviam de salvar.', 'Atos 2:46-47', 'Atos', 2, 46, 47),
  ('comunidade', 'E, sobre tudo isto, revesti-vos de amor, que é o vínculo da perfeição.', 'Colossenses 3:14', 'Colossenses', 3, 14, NULL),
  ('comunidade', 'Sede unânimes entre vós; não ambicioneis coisas altas, mas acomodai-vos às humildes; não sejais sábios em vós mesmos.', 'Romanos 12:16', 'Romanos', 12, 16, NULL),
  ('comunidade', 'Amados, se Deus assim nos amou, também nós devemos amar uns aos outros.', '1 João 4:11', '1 João', 4, 11, NULL),
  ('comunidade', 'Procurando guardar a unidade do Espírito pelo vínculo da paz.', 'Efésios 4:3', 'Efésios', 4, 3, NULL),
  ('comunidade', 'Ora, o Deus de paciência e consolação vos conceda o mesmo sentimento uns para com os outros, segundo Cristo Jesus.', 'Romanos 15:5', 'Romanos', 15, 5, NULL),
  ('comunidade', 'E era um o coração e a alma da multidão dos que criam, e ninguém dizia que coisa alguma do que possuía era sua própria, mas todas as coisas lhes eram comuns.', 'Atos 4:32', 'Atos', 4, 32, NULL),
  ('comunidade', 'Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo pecado.', '1 João 1:7', '1 João', 1, 7, NULL),
  ('comunidade', 'Nisto não há judeu nem grego; não há servo nem livre; não há macho nem fêmea; porque todos vós sois um em Cristo Jesus.', 'Gálatas 3:28', 'Gálatas', 3, 28, NULL),
  ('comunidade', 'Ora, quanto ao que está enfermo na fé, recebei-o, não em contendas sobre dúvidas.', 'Romanos 14:1', 'Romanos', 14, 1, NULL),
  ('comunidade', 'E rogo-vos, irmãos, que noteis os que promovem dissensões e escândalos contra a doutrina que aprendestes; desviai-vos deles.', 'Romanos 16:17', 'Romanos', 16, 17, NULL),
  ('comunidade', 'Na verdade, na verdade vos digo que se alguém receber o que eu enviar, me recebe a mim, e quem me recebe a mim recebe aquele que me enviou.', 'João 13:20', 'João', 13, 20, NULL),
  ('comunidade', 'Todos estes perseveravam unanimemente em oração e súplicas, com as mulheres, e Maria, mãe de Jesus, e com seus irmãos.', 'Atos 1:14', 'Atos', 1, 14, NULL),
  ('comunidade', 'Pois todos nós fomos batizados em um Espírito, formando um corpo, quer judeus, quer gregos, quer servos, quer livres, e todos temos bebido de um Espírito.', '1 Coríntios 12:13', '1 Coríntios', 12, 13, NULL),
  ('comunidade', 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações.', 'Atos 2:42', 'Atos', 2, 42, NULL),
  ('comunidade', 'Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também.', '1 Coríntios 12:12', '1 Coríntios', 12, 12, NULL),
  ('comunidade', 'Pedro, pois, era guardado na prisão; mas a igreja fazia contínua oração por ele a Deus.', 'Atos 12:5', 'Atos', 12, 5, NULL),
  ('comunidade', 'Honra as viúvas que verdadeiramente são viúvas.', '1 Timóteo 5:3', '1 Timóteo', 5, 3, NULL),
  ('comunidade', 'Não sabeis vós que sois o templo de Deus e que o Espírito de Deus habita em vós?', '1 Coríntios 3:16', '1 Coríntios', 3, 16, NULL),
  ('comunidade', 'Se alguém destruir o templo de Deus, Deus o destruirá; porque o templo de Deus, que sois vós, é santo.', '1 Coríntios 3:17', '1 Coríntios', 3, 17, NULL),
  ('comunidade', 'Pois também eu te digo que tu és Pedro e sobre esta pedra edificarei a minha igreja, e as portas do inferno não prevalecerão contra ela.', 'Mateus 16:18', 'Mateus', 16, 18, NULL),
  ('confiabilidade', 'Mas fiel é o Senhor, que vos confortará e guardará do maligno.', '2 Tessalonicenses 3:3', '2 Tessalonicenses', 3, 3, NULL),
  ('confiabilidade', 'Saberás, pois, que o Senhor', 'Deuteronômio 7:9', 'Deuteronômio', 7, 9, NULL),
  ('confiabilidade', 'As misericórdias do Senhor', 'Lamentações 3:22-23', 'Lamentações', 3, 22, 23),
  ('confiabilidade', 'Ó Senhor', 'Isaías 25:1', 'Isaías', 25, 1, NULL),
  ('confiabilidade', 'O desejo do homem é a sua beneficência; mas o pobre é melhor do que o mentiroso.', 'Provérbios 19:22', 'Provérbios', 19, 22, NULL),
  ('confiabilidade', 'Lança o teu cuidado sobre o Senhor', 'Salmo 55:22', 'Salmo', 55, 22, NULL),
  ('confiabilidade', 'Não deixará vacilar o teu pé; aquele que te guarda não tosquenejará.', 'Salmo 121:3', 'Salmo', 121, 3, NULL),
  ('confiabilidade', 'O Senhor', 'Deuteronômio 31:8', 'Deuteronômio', 31, 8, NULL),
  ('confiabilidade', 'Não veio sobre vós tentação, senão humana; mas fiel é Deus, que vos não deixará tentar acima do que podeis; antes, com a tentação dará também o escape, para que a possais suportar.', '1 Coríntios 10:13', '1 Coríntios', 10, 13, NULL),
  ('confiabilidade', 'Perto está o Senhor', 'Salmo 145:18', 'Salmo', 145, 18, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('confiabilidade', 'O Senhor', 'Salmo 138:8', 'Salmo', 138, 8, NULL),
  ('confiabilidade', 'Louvai ao Senhor', '1 Crônicas 16:34', '1 Crônicas', 16, 34, NULL),
  ('confiabilidade', 'E o seu senhor lhe disse: Bem está, servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor.', 'Mateus 25:21', 'Mateus', 25, 21, NULL),
  ('confiabilidade', 'Eu, porém, cantarei a tua força; pela manhã, louvarei com alegria a tua misericórdia, porquanto tu foste o meu alto refúgio e proteção no dia da minha angústia.', 'Salmo 59:16', 'Salmo', 59, 16, NULL),
  ('confiabilidade', 'Fiel é o que vos chama, o qual também o fará.', '1 Tessalonicenses 5:24', '1 Tessalonicenses', 5, 24, NULL),
  ('confiabilidade', 'A sinceridade dos sinceros os encaminhará, mas a perversidade dos desleais os destruirá.', 'Provérbios 11:3', 'Provérbios', 11, 3, NULL),
  ('confiabilidade', 'Mas a misericórdia do Senhor', 'Salmo 103:17-18', 'Salmo', 103, 17, 18),
  ('confiabilidade', 'Eis que os olhos do Senhor', 'Salmo 33:18', 'Salmo', 33, 18, NULL),
  ('confiabilidade', 'O que anda praguejando descobre o segredo, mas o fiel de espírito encobre o negócio.', 'Provérbios 11:13', 'Provérbios', 11, 13, NULL),
  ('confiabilidade', 'Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes, em quem não há mudança, nem sombra de variação.', 'Tiago 1:17', 'Tiago', 1, 17, NULL),
  ('confiabilidade', 'Até agora, nada pedistes em meu nome; pedi e recebereis, para que a vossa alegria se cumpra.', 'João 16:24', 'João', 16, 24, NULL),
  ('confiabilidade', 'Pois tu, Senhor, és bom, e pronto a perdoar, e abundante em benignidade para com todos os que te invocam.', 'Salmo 86:5', 'Salmo', 86, 5, NULL),
  ('confiabilidade', 'Eu sou o Alfa e o Ômega, o Princípio e o Fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-Poderoso.', 'Apocalipse 1:8', 'Apocalipse', 1, 8, NULL),
  ('confiabilidade', 'Pois fartou a alma sedenta e encheu de bens a alma faminta.', 'Salmo 107:9', 'Salmo', 107, 9, NULL),
  ('confiabilidade', 'Tu, Senhor', 'Lamentações 5:19', 'Lamentações', 5, 19, NULL),
  ('confiabilidade', 'Deus é o nosso refúgio e fortaleza, socorro bem-presente na angústia.', 'Salmo 46:1', 'Salmo', 46, 1, NULL),
  ('confiabilidade', 'E até à velhice eu serei o mesmo e ainda até às cãs eu vos trarei; eu o fiz, e eu vos levarei, e eu vos trarei e vos guardarei.', 'Isaías 46:4', 'Isaías', 46, 4, NULL),
  ('confiabilidade', 'Retenhamos firmes a confissão da nossa esperança, porque fiel é o que prometeu.', 'Hebreus 10:23', 'Hebreus', 10, 23, NULL),
  ('confiabilidade', 'Porque o Senhor', 'Salmo 37:28', 'Salmo', 37, 28, NULL),
  ('confiabilidade', 'Porque a Escritura diz: Todo aquele que nele crer não será confundido.', 'Romanos 10:11', 'Romanos', 10, 11, NULL),
  ('confiabilidade', 'O Senhor', '2 Crônicas 15:2b', '2 Crônicas 15:2b', NULL, NULL, NULL),
  ('confiabilidade', 'E tudo o que pedirdes na oração, crendo, o recebereis.', 'Mateus 21:22', 'Mateus', 21, 22, NULL),
  ('confiabilidade', 'Esforçai-vos, e animai-vos; não temais, nem vos espanteis diante deles, porque o Senhor', 'Deuteronômio 31:6', 'Deuteronômio', 31, 6, NULL),
  ('confiabilidade', 'E em ti confiarão os que conhecem o teu nome; porque tu, Senhor', 'Salmo 9:10', 'Salmo', 9, 10, NULL),
  ('confiabilidade', 'Jesus Cristo é o mesmo ontem, e hoje, e eternamente.', 'Hebreus 13:8', 'Hebreus', 13, 8, NULL),
  ('confiabilidade', 'Aquele, porém, que se gloria, glorie-se no Senhor. Porque não é aprovado quem a si mesmo se louva, mas, sim, aquele a quem o Senhor louva.', '2 Coríntios 10:17-18', '2 Coríntios', 10, 17, 18),
  ('confiabilidade', 'Pois a tua misericórdia é grande até aos céus, e a tua verdade até às nuvens.', 'Salmo 57:10', 'Salmo', 57, 10, NULL),
  ('confiabilidade', 'Porque a palavra do Senhor', 'Salmo 33:4', 'Salmo', 33, 4, NULL),
  ('confiabilidade', 'Em todo trabalho há proveito, mas a palavra dos lábios só encaminha para a pobreza.', 'Provérbios 14:23', 'Provérbios', 14, 23, NULL),
  ('confiabilidade', 'Quando eu disse: O meu pé vacila; a tua benignidade, Senhor', 'Salmo 94:18', 'Salmo', 94, 18, NULL),
  ('confiabilidade', 'Porque as montanhas se desviarão e os outeiros tremerão; mas a minha benignidade não se desviará de ti, e o concerto da minha paz não mudará, diz o Senhor', 'Isaías 54:10', 'Isaías', 54, 10, NULL),
  ('confiabilidade', 'Vós que amais ao Senhor', 'Salmo 97:10', 'Salmo', 97, 10, NULL),
  ('confiabilidade', 'Ele é a Rocha cuja obra é perfeita, porque todos os seus caminhos juízo são; Deus é a verdade, e não há nele injustiça; justo e reto é.', 'Deuteronômio 32:4', 'Deuteronômio', 32, 4, NULL),
  ('confiabilidade', 'Portanto, dize-lhes: Assim diz o Senhor Jeová', 'Ezequiel 12:28', 'Ezequiel', 12, 28, NULL),
  ('confiabilidade', 'Os teus olhos olhem direitos, e as tuas pálpebras olhem diretamente diante de ti.', 'Provérbios 4:25', 'Provérbios', 4, 25, NULL),
  ('confiabilidade', 'Ele te cobrirá com as suas penas, e debaixo das suas asas estarás seguro; a sua verdade é escudo e broquel.', 'Salmo 91:4', 'Salmo', 91, 4, NULL),
  ('confiabilidade', 'Ó Senhor', 'Salmo 143:1', 'Salmo', 143, 1, NULL),
  ('confiabilidade', 'Seja a tua misericórdia, Senhor', 'Salmo 33:22', 'Salmo', 33, 22, NULL),
  ('confiabilidade', 'Não detenhas para comigo, Senhor', 'Salmo 40:11', 'Salmo', 40, 11, NULL),
  ('confiabilidade', 'Seca-se a erva, e caem as flores, mas a palavra de nosso Deus subsiste eternamente.', 'Isaías 40:8', 'Isaías', 40, 8, NULL),
  ('confiabilidade', 'Porque, quem é Deus senão o Senhor', 'Salmo 18:31', 'Salmo', 18, 31, NULL),
  ('confiabilidade', 'Justo é o Senhor', 'Salmo 145:17', 'Salmo', 145, 17, NULL),
  ('confiabilidade', 'Só ele é a minha rocha e a minha salvação; é a minha defesa; não serei grandemente abalado.', 'Salmo 62:2', 'Salmo', 62, 2, NULL),
  ('confiabilidade', 'Assim será a palavra que sair da minha boca; ela não voltará para mim vazia; antes, fará o que me apraz e prosperará naquilo para que a enviei.', 'Isaías 55:11', 'Isaías', 55, 11, NULL),
  ('confiabilidade', 'O caminho do Senhor', 'Provérbios 10:29', 'Provérbios', 10, 29, NULL),
  ('confiabilidade', 'Afasta de mim a vaidade e a palavra mentirosa; não me dês nem a pobreza nem a riqueza; mantém-me do pão da minha porção acostumada.', 'Provérbios 30:8', 'Provérbios', 30, 8, NULL),
  ('confiabilidade', 'Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo, nosso Senhor.', '1 Coríntios 1:9', '1 Coríntios', 1, 9, NULL),
  ('confiabilidade', 'Ele ama a justiça e o juízo; a terra está cheia da bondade do Senhor', 'Salmo 33:5', 'Salmo', 33, 5, NULL),
  ('confiabilidade', 'Deus não é homem, para que minta; nem filho de homem, para que se arrependa; porventura, diria ele e não o faria? Ou falaria e não o confirmaria?', 'Números 23:19', 'Números', 23, 19, NULL),
  ('confiabilidade', 'A tua palavra é a verdade desde o princípio, e cada um dos teus juízos dura para sempre.', 'Salmo 119:160', 'Salmo', 119, 160, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('confiabilidade', 'Tornai para mim, diz o Senhor', 'Zacarias 1:3b', 'Zacarias 1:3b', NULL, NULL, NULL),
  ('confiabilidade', 'Não vos deixarei órfãos; voltarei para vós.', 'João 14:18', 'João', 14, 18, NULL),
  ('confiabilidade', 'O céu e a terra passarão, mas as minhas palavras não hão de passar.', 'Mateus 24:35', 'Mateus', 24, 35, NULL),
  ('confiabilidade', 'Eis que a sua alma se incha, não é reta nele; mas o justo, pela sua fé, viverá.', 'Habacuque 2:4', 'Habacuque', 2, 4, NULL),
  ('confiabilidade', 'Palavra fiel é esta: que, se morrermos com ele, também com ele viveremos.', '2 Timóteo 2:11', '2 Timóteo', 2, 11, NULL),
  ('confiabilidade', 'Ensina-me, Senhor', 'Salmo 86:11', 'Salmo', 86, 11, NULL),
  ('confiabilidade', 'E eis aqui eu vou, hoje, pelo caminho de toda a terra; e vós bem sabeis, com todo o vosso coração e com toda a vossa alma que nem uma só palavra caiu de todas as boas palavras que falou de vós o Senhor', 'Josué 23:14', 'Josué', 23, 14, NULL),
  ('confiabilidade', 'Certamente o Senhor Jeová', 'Amós 3:7', 'Amós', 3, 7, NULL),
  ('confiabilidade', 'Porque, quem é Deus, senão o Senhor', '2 Samuel 22:32', '2 Samuel', 22, 32, NULL),
  ('confiabilidade', 'Porque em verdade vos digo que, até que o céu e a terra passem, nem um jota ou um til se omitirá da lei sem que tudo seja cumprido.', 'Mateus 5:18', 'Mateus', 5, 18, NULL),
  ('confiabilidade', 'A testemunha verdadeira não mentirá, mas a testemunha falsa se desboca em mentiras.', 'Provérbios 14:5', 'Provérbios', 14, 5, NULL),
  ('confiabilidade', 'E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor', 'Joel 2:13', 'Joel', 2, 13, NULL),
  ('confiabilidade', 'O Senhor', '1 Reis 8:57', '1 Reis', 8, 57, NULL),
  ('confiabilidade', 'Os lábios mentirosos são abomináveis ao Senhor', 'Provérbios 12:22', 'Provérbios', 12, 22, NULL),
  ('confiabilidade', 'Não matarás, não cometerás adultério, não furtarás, não dirás falso testemunho; honra teu pai e tua mãe, e amarás o teu próximo como a ti mesmo.', 'Mateus 19:18b-19', 'Mateus 19:18b-19', NULL, NULL, NULL),
  ('confiabilidade', 'Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos; o que votares, paga-o.', 'Eclesiastes 5:4', 'Eclesiastes', 5, 4, NULL),
  ('confiabilidade', 'Seja, porém, o vosso falar: Sim, sim; não, não, porque o que passa disso é de procedência maligna.', 'Mateus 5:37', 'Mateus', 5, 37, NULL),
  ('confiabilidade', 'E eu vos digo a vós: Pedi, e dar-se-vos-á; buscai, e achareis; batei, e abrir-se-vos-á.', 'Lucas 11:9', 'Lucas', 11, 9, NULL),
  ('confiabilidade', 'Com o benigno te mostrarás benigno; e com o homem sincero te mostrarás sincero.', 'Salmo 18:25', 'Salmo', 18, 25, NULL),
  ('confiabilidade', 'Eu, porém, vos digo que, de maneira nenhuma, jureis nem pelo céu, porque é o trono de Deus, nem pela terra, porque é o escabelo de seus pés, nem por Jerusalém, porque é a cidade do grande Rei.', 'Mateus 5:34-35', 'Mateus', 5, 34, 35),
  ('confiabilidade', 'Mas tu, Senhor, és um Deus cheio de compaixão, e piedoso, e sofredor, e grande em benignidade e em verdade.', 'Salmo 86:15', 'Salmo', 86, 15, NULL),
  ('confianca', 'Confia no Senhor', 'Provérbios 3:5-6', 'Provérbios', 3, 5, 6),
  ('confianca', 'Bendito o varão que confia no Senhor', 'Jeremias 17:7-8', 'Jeremias', 17, 7, 8),
  ('confianca', 'No dia em que eu temer, hei de confiar em ti.', 'Salmo 56:3', 'Salmo', 56, 3, NULL),
  ('confianca', 'Confia ao Senhor', 'Provérbios 16:3', 'Provérbios', 16, 3, NULL),
  ('confianca', 'Quando passares pelas águas, estarei contigo, e, quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti.', 'Isaías 43:2', 'Isaías', 43, 2, NULL),
  ('confianca', 'Faze-me ouvir a tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti levanto a minha alma.', 'Salmo 143:8', 'Salmo', 143, 8, NULL),
  ('confianca', 'E esta é a confiança que temos nele: que, se pedirmos alguma coisa, segundo a sua vontade, ele nos ouve.', '1 João 5:14', '1 João', 5, 14, NULL),
  ('confianca', 'Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. Direi do Senhor', 'Salmo 91:1-2', 'Salmo', 91, 1, 2),
  ('confianca', 'Porque andamos por fé e não por vista.', '2 Coríntios 5:7', '2 Coríntios', 5, 7, NULL),
  ('confianca', 'O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades em glória, por Cristo Jesus.', 'Filipenses 4:19', 'Filipenses', 4, 19, NULL),
  ('confianca', 'Em Deus está a minha salvação e a minha glória; a rocha da minha fortaleza e o meu refúgio estão em Deus.', 'Salmo 62:7', 'Salmo', 62, 7, NULL),
  ('confianca', 'Não deixará vacilar o teu pé; aquele que te guarda não tosquenejará.', 'Salmo 121:3', 'Salmo', 121, 3, NULL),
  ('confianca', 'Peça-a, porém, com fé, não duvidando; porque o que duvida é semelhante à onda do mar, que é levada pelo vento e lançada de uma para outra parte.', 'Tiago 1:6', 'Tiago', 1, 6, NULL),
  ('confianca', 'Perto está o Senhor', 'Salmo 145:18', 'Salmo', 145, 18, NULL),
  ('confianca', 'Olhai para as aves do céu, que não semeiam, nem segam, nem ajuntam em celeiros; e vosso Pai celestial as alimenta. Não tendes vós muito mais valor do que elas?', 'Mateus 6:26', 'Mateus', 6, 26, NULL),
  ('confianca', 'E, assim, com confiança, ousemos dizer: O Senhor é o meu ajudador, e não temerei o que me possa fazer o homem.', 'Hebreus 13:6', 'Hebreus', 13, 6, NULL),
  ('confianca', 'O receio do homem armará laços, mas o que confia no Senhor', 'Provérbios 29:25', 'Provérbios', 29, 25, NULL),
  ('confianca', 'Entrega o teu caminho ao Senhor', 'Salmo 37:5-6', 'Salmo', 37, 5, 6),
  ('confianca', 'O que atenta prudentemente para a palavra achará o bem, e o que confia no Senhor', 'Provérbios 16:20', 'Provérbios', 16, 20, NULL),
  ('confianca', 'A quem tenho eu no céu senão a ti? E na terra não há quem eu deseje além de ti.', 'Salmo 73:25', 'Salmo', 73, 25, NULL),
  ('confianca', 'Sejam vossos costumes sem avareza, contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei.', 'Hebreus 13:5', 'Hebreus', 13, 5, NULL),
  ('confianca', 'Espera no Senhor', 'Salmo 27:14', 'Salmo', 27, 14, NULL),
  ('confianca', 'O Senhor', 'Naum 1:7', 'Naum', 1, 7, NULL),
  ('confianca', 'Confia no Senhor', 'Salmo 37:3', 'Salmo', 37, 3, NULL),
  ('confianca', 'E nós conhecemos e cremos no amor que Deus nos tem. Deus é amor e quem está em amor está em Deus, e Deus, nele.', '1 João 4:16', '1 João', 4, 16, NULL),
  ('confianca', 'Oh! Quão grande é a tua bondade, que guardaste para os que te temem, e que tu mostraste àqueles que em ti confiam na presença dos filhos dos homens!', 'Salmo 31:19', 'Salmo', 31, 19, NULL),
  ('confianca', 'Em Deus louvarei a sua palavra; em Deus pus a minha confiança e não temerei; que me pode fazer a carne?', 'Salmo 56:4', 'Salmo', 56, 4, NULL),
  ('confianca', 'E, se sabemos que nos ouve em tudo o que pedimos, sabemos que alcançamos as petições que lhe fizemos.', '1 João 5:15', '1 João', 5, 15, NULL),
  ('confianca', 'Amados, não creiais em todo espírito, mas provai se os espíritos são de Deus, porque já muitos falsos profetas se têm levantado no mundo.', '1 João 4:1', '1 João', 4, 1, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('confianca', 'É melhor confiar no Senhor', 'Salmo 118:8', 'Salmo', 118, 8, NULL),
  ('confianca', 'O Senhor', 'Salmo 28:7', 'Salmo', 28, 7, NULL),
  ('confianca', 'Não se turbe o vosso coração; credes em Deus, crede também em mim.', 'João 14:1', 'João', 14, 1, NULL),
  ('confianca', 'Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti.', 'Isaías 26:3', 'Isaías', 26, 3, NULL),
  ('confianca', 'E em ti confiarão os que conhecem o teu nome; porque tu, Senhor', 'Salmo 9:10', 'Salmo', 9, 10, NULL),
  ('confianca', 'Amados, se o nosso coração nos não condena, temos confiança para com Deus; e qualquer coisa que lhe pedirmos, dele a receberemos, porque guardamos os seus mandamentos e fazemos o que é agradável à sua vista.', '1 João 3:21-22', '1 João', 3, 21, 22),
  ('confianca', 'Guarda-me, ó Deus, porque em ti confio.', 'Salmo 16:1', 'Salmo', 16, 1, NULL),
  ('confianca', 'Mas, se esperamos o que não vemos, com paciência o esperamos.', 'Romanos 8:25', 'Romanos', 8, 25, NULL),
  ('confianca', 'Não digo isto como por necessidade, porque já aprendi a contentar-me com o que tenho.', 'Filipenses 4:11', 'Filipenses', 4, 11, NULL),
  ('confianca', 'Ainda que um exército me cercasse, o meu coração não temeria; ainda que a guerra se levantasse contra mim, nele confiaria.', 'Salmo 27:3', 'Salmo', 27, 3, NULL),
  ('confianca', 'Mas eu confio na tua benignidade; na tua salvação, meu coração se alegrará. Cantarei ao Senhor', 'Salmo 13:5-6', 'Salmo', 13, 5, 6),
  ('confianca', 'E Jesus lhes disse: Por causa da vossa pequena fé; porque em verdade vos digo que, se tiverdes fé como um grão de mostarda, direis a este monte: Passa daqui para acolá — e há de passar; e nada vos será impossível.', 'Mateus 17:20', 'Mateus', 17, 20, NULL),
  ('confianca', 'Seja a tua misericórdia, Senhor', 'Salmo 33:22', 'Salmo', 33, 22, NULL),
  ('confianca', 'Porque as montanhas se desviarão e os outeiros tremerão; mas a minha benignidade não se desviará de ti, e o concerto da minha paz não mudará, diz o Senhor', 'Isaías 54:10', 'Isaías', 54, 10, NULL),
  ('confianca', 'Não folga com a injustiça, mas folga com a verdade; tudo sofre, tudo crê, tudo espera, tudo suporta.', '1 Coríntios 13:6-7', '1 Coríntios', 13, 6, 7),
  ('confianca', 'Os passos de um homem bom são confirmados pelo Senhor', 'Salmo 37:23', 'Salmo', 37, 23, NULL),
  ('confianca', 'Só ele é a minha rocha e a minha salvação; é a minha defesa; não serei abalado.', 'Salmo 62:6', 'Salmo', 62, 6, NULL),
  ('confianca', 'Porque em verdade vos digo que qualquer que disser a este monte: Ergue-te e lança-te no mar, e não duvidar em seu coração, mas crer que se fará aquilo que diz, tudo o que disser lhe será feito.', 'Marcos 11:23', 'Marcos', 11, 23, NULL),
  ('confianca', 'Pereceria sem dúvida, se não cresse que veria os bens do Senhor', 'Salmo 27:13', 'Salmo', 27, 13, NULL),
  ('confianca', 'Não tenhas inveja do homem violento, nem escolhas nenhum de seus caminhos. Porque o perverso é abominação para o Senhor', 'Provérbios 3:31-32', 'Provérbios', 3, 31, 32),
  ('confianca', 'Porque nos tornamos participantes de Cristo, se retivermos firmemente o princípio da nossa confiança até ao fim.', 'Hebreus 3:14', 'Hebreus', 3, 14, NULL),
  ('confianca', 'E agora, filhinhos, permanecei nele, para que, quando ele se manifestar, tenhamos confiança e não sejamos confundidos por ele na sua vinda.', '1 João 2:28', '1 João', 2, 28, NULL),
  ('confianca', 'Jesus, porém, respondendo, disse-lhes: Em verdade vos digo que, se tiverdes fé e não duvidardes, não só fareis o que foi feito à figueira, mas até, se a este monte disserdes: Ergue-te e precipita-te no mar, assim será feito.', 'Mateus 21:21', 'Mateus', 21, 21, NULL),
  ('confianca', 'Pela fé, também a mesma Sara recebeu a virtude de conceber e deu à luz já fora da idade; porquanto teve por fiel aquele que lho tinha prometido.', 'Hebreus 11:11', 'Hebreus', 11, 11, NULL),
  ('confianca', 'Uns confiam em carros, e outros, em cavalos, mas nós faremos menção do nome do Senhor', 'Salmo 20:7', 'Salmo', 20, 7, NULL),
  ('confianca', 'Mas a Escritura encerrou tudo debaixo do pecado, para que a promessa pela fé em Jesus Cristo fosse dada aos crentes.', 'Gálatas 3:22', 'Gálatas', 3, 22, NULL),
  ('confianca', 'Toda alma esteja sujeita às autoridades superiores; porque não há autoridade que não venha de Deus; e as autoridades que há foram ordenadas por Deus.', 'Romanos 13:1', 'Romanos', 13, 1, NULL),
  ('confissao', 'Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis; a oração feita por um justo pode muito em seus efeitos.', 'Tiago 5:16', 'Tiago', 5, 16, NULL),
  ('confissao', 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.', '1 João 1:9', '1 João', 1, 9, NULL),
  ('confissao', 'O que encobre as suas transgressões nunca prosperará; mas o que as confessa e deixa alcançará misericórdia.', 'Provérbios 28:13', 'Provérbios', 28, 13, NULL),
  ('confissao', 'Confessei-te o meu pecado e a minha maldade não encobri; dizia eu: Confessarei ao Senhor', 'Salmo 32:5', 'Salmo', 32, 5, NULL),
  ('confissao', 'Será, pois, que, culpado sendo numa destas coisas, confessará aquilo em que pecou.', 'Levítico 5:5', 'Levítico', 5, 5, NULL),
  ('confissao', 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, e venham, assim, os tempos do refrigério pela presença do Senhor.', 'Atos 3:19', 'Atos', 3, 19, NULL),
  ('confissao', 'Visto que com o coração se crê para a justiça, e com a boca se faz confissão para a salvação.', 'Romanos 10:10', 'Romanos', 10, 10, NULL),
  ('confissao', 'Enquanto eu me calei, envelheceram os meus ossos pelo meu bramido em todo o dia.', 'Salmo 32:3', 'Salmo', 32, 3, NULL),
  ('confissao', 'Pecamos, e cometemos iniquidade, e procedemos impiamente, e fomos rebeldes, apartando-nos dos teus mandamentos e dos teus juízos.', 'Daniel 9:5', 'Daniel', 9, 5, NULL),
  ('confissao', 'A saber: Se, com a tua boca, confessares ao Senhor Jesus e, em teu coração, creres que Deus o ressuscitou dos mortos, serás salvo.', 'Romanos 10:9', 'Romanos', 10, 9, NULL),
  ('confissao', 'Porque todos pecaram e destituídos estão da glória de Deus, sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus.', 'Romanos 3:23-24', 'Romanos', 3, 23, 24),
  ('confissao', 'Chegai-vos a Deus, e ele se chegará a vós. Limpai as mãos, pecadores; e, vós de duplo ânimo, purificai o coração.', 'Tiago 4:8', 'Tiago', 4, 8, NULL),
  ('confissao', 'Milita a boa milícia da fé, toma posse da vida eterna, para a qual também foste chamado, tendo já feito boa confissão diante de muitas testemunhas.', '1 Timóteo 6:12', '1 Timóteo', 6, 12, NULL),
  ('confissao', 'Qualquer que nega o Filho também não tem o Pai; e aquele que confessa o Filho tem também o Pai.', '1 João 2:23', '1 João', 2, 23, NULL),
  ('consolador', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda consolação, que nos consola em toda a nossa tribulação, para que também possamos consolar os que estiverem em alguma tribulação, com a consolação com que nós mesmos somos consolados de Deus.', '2 Coríntios 1:3-4', '2 Coríntios', 1, 3, 4),
  ('consolador', 'Não vos deixarei órfãos; voltarei para vós.', 'João 14:18', 'João', 14, 18, NULL),
  ('consolador', 'Multiplicando-se dentro de mim os meus cuidados, as tuas consolações reanimaram a minha alma.', 'Salmo 94:19', 'Salmo', 94, 19, NULL),
  ('consolador', 'Mas aquele Consolador, o Espírito Santo, que o Pai enviará em meu nome, vos ensinará todas as coisas e vos fará lembrar de tudo quanto vos tenho dito.', 'João 14:26', 'João', 14, 26, NULL),
  ('consolador', 'Bem-aventurados os que choram, porque eles serão consolados.', 'Mateus 5:4', 'Mateus', 5, 4, NULL),
  ('consolador', 'Todavia, digo-vos a verdade: que vos convém que eu vá, porque, se eu não for, o Consolador não virá a vós; mas, se eu for, enviar-vo-lo-ei.', 'João 16:7', 'João', 16, 7, NULL),
  ('consolador', 'E eu rogarei ao Pai, e ele vos dará outro Consolador, para que fique convosco para sempre.', 'João 14:16', 'João', 14, 16, NULL),
  ('consolador', 'Invoquei o Senhor', 'Salmo 118:5', 'Salmo', 118, 5, NULL),
  ('consolador', 'Eu, eu sou aquele que vos consola; quem pois és tu, para que temas o homem, que é mortal, ou o filho do homem, que se tornará em feno?', 'Isaías 51:12', 'Isaías', 51, 12, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('consolador', 'Nunca mais terão fome, nunca mais terão sede; nem sol nem calma alguma cairá sobre eles, porque o Cordeiro que está no meio do trono os apascentará e lhes servirá de guia para as fontes das águas da vida; e Deus limpará de seus olhos toda lágrima.', 'Apocalipse 7:16-17', 'Apocalipse', 7, 16, 17),
  ('consolador', 'Porque, como as aflições de Cristo são abundantes em nós, assim também a nossa consolação sobeja por meio de Cristo.', '2 Coríntios 1:5', '2 Coríntios', 1, 5, NULL),
  ('consolador', 'Mas, quando vier o Consolador, que eu da parte do Pai vos hei de enviar, aquele Espírito da verdade, que procede do Pai, testificará de mim.', 'João 15:26', 'João', 15, 26, NULL),
  ('consolador', 'Ora, o Deus de paciência e consolação vos conceda o mesmo sentimento uns para com os outros, segundo Cristo Jesus.', 'Romanos 15:5', 'Romanos', 15, 5, NULL),
  ('contentamento', 'Sei estar abatido e sei também ter abundância; em toda a maneira e em todas as coisas, estou instruído, tanto a ter fartura como a ter fome, tanto a ter abundância como a padecer necessidade.', 'Filipenses 4:12', 'Filipenses', 4, 12, NULL),
  ('contentamento', 'Porque nada trouxemos para este mundo e manifesto é que nada podemos levar dele. Tendo, porém, sustento e com que nos cobrirmos, estejamos com isso contentes.', '1 Timóteo 6:7-8', '1 Timóteo', 6, 7, 8),
  ('contentamento', 'Sejam vossos costumes sem avareza, contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei.', 'Hebreus 13:5', 'Hebreus', 13, 5, NULL),
  ('contentamento', 'Mas é grande ganho a piedade com contentamento.', '1 Timóteo 6:6', '1 Timóteo', 6, 6, NULL),
  ('contentamento', 'Não digo isto como por necessidade, porque já aprendi a contentar-me com o que tenho.', 'Filipenses 4:11', 'Filipenses', 4, 11, NULL),
  ('contentamento', 'Pelo que sinto prazer nas fraquezas, nas injúrias, nas necessidades, nas perseguições, nas angústias, por amor de Cristo. Porque, quando estou fraco, então, sou forte.', '2 Coríntios 12:10', '2 Coríntios', 12, 10, NULL),
  ('contentamento', 'E disse-lhes: Acautelai-vos e guardai-vos da avareza, porque a vida de qualquer não consiste na abundância do que possui.', 'Lucas 12:15', 'Lucas', 12, 15, NULL),
  ('contentamento', 'Por isso, vos digo: não andeis cuidadosos quanto à vossa vida, pelo que haveis de comer ou pelo que haveis de beber; nem quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o mantimento, e o corpo, mais do que a vestimenta?', 'Mateus 6:25', 'Mateus', 6, 25, NULL),
  ('contentamento', 'Melhor é o pouco com justiça do que a abundância de colheita com injustiça.', 'Provérbios 16:8', 'Provérbios', 16, 8, NULL),
  ('contentamento', 'Sede unânimes entre vós; não ambicioneis coisas altas, mas acomodai-vos às humildes; não sejais sábios em vós mesmos.', 'Romanos 12:16', 'Romanos', 12, 16, NULL),
  ('contentamento', 'Não estejais apreensivos pela vossa vida, sobre o que comereis, nem pelo corpo, sobre o que vestireis. Mais é a vida do que o sustento, e o corpo, mais do que as vestes.', 'Lucas 12:22b-23', 'Lucas 12:22b-23', NULL, NULL, NULL),
  ('contentamento', 'Então, Jó se levantou, e rasgou o seu manto, e rapou a sua cabeça, e se lançou em terra, e adorou, e disse: Nu saí do ventre de minha mãe e nu tornarei para lá; o Senhor', 'Jó 1:20-21', 'Jó', 1, 20, 21),
  ('contentamento', 'Disse-lhe Filipe: Senhor, mostra-nos o Pai, o que nos basta.', 'João 14:8', 'João', 14, 8, NULL),
  ('conversao', 'E se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar a minha face, e se converter dos seus maus caminhos, então, eu ouvirei dos céus, e perdoarei os seus pecados, e sararei a sua terra.', '2 Crônicas 7:14', '2 Crônicas', 7, 14, NULL),
  ('conversao', 'Porque o Senhor', '2 Crônicas 30:9b', '2 Crônicas 30:9b', NULL, NULL, NULL),
  ('conversao', 'Mortificai, pois, os vossos membros que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência e a avareza, que é idolatria.', 'Colossenses 3:5', 'Colossenses', 3, 5, NULL),
  ('conversao', 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, e venham, assim, os tempos do refrigério pela presença do Senhor.', 'Atos 3:19', 'Atos', 3, 19, NULL),
  ('conversao', 'O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se.', '2 Pedro 3:9', '2 Pedro', 3, 9, NULL),
  ('conversao', 'Porque não tomo prazer na morte do que morre, diz o Senhor Jeová', 'Ezequiel 18:32', 'Ezequiel', 18, 32, NULL),
  ('conversao', 'E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor', 'Joel 2:13', 'Joel', 2, 13, NULL),
  ('conversao', 'Produzi, pois, frutos dignos de arrependimento.', 'Mateus 3:8', 'Mateus', 3, 8, NULL),
  ('conversao', 'Eu não vim chamar os justos, mas sim os pecadores, ao arrependimento.', 'Lucas 5:32', 'Lucas', 5, 32, NULL),
  ('conversao', 'E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo.', 'Atos 2:38', 'Atos', 2, 38, NULL),
  ('conversao', 'Digo-vos que assim haverá alegria no céu por um pecador que se arrepende, mais do que por noventa e nove justos que não necessitam de arrependimento.', 'Lucas 15:7', 'Lucas', 15, 7, NULL),
  ('conversao', 'Pelo que, rejeitando toda imundícia e acúmulo de malícia, recebei com mansidão a palavra em vós enxertada, a qual pode salvar a vossa alma.', 'Tiago 1:21', 'Tiago', 1, 21, NULL),
  ('conversao', 'Desfaço as tuas transgressões como a névoa, e os teus pecados, como a nuvem; torna-te para mim, porque eu te remi.', 'Isaías 44:22', 'Isaías', 44, 22, NULL),
  ('conversao', 'Desde então, começou Jesus a pregar e a dizer: Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 4:17', 'Mateus', 4, 17, NULL),
  ('conversao', 'O tempo está cumprido, e o Reino de Deus está próximo. Arrependei-vos e crede no evangelho.', 'Marcos 1:15', 'Marcos', 1, 15, NULL),
  ('conversao', 'Tornai para mim, diz o Senhor', 'Zacarias 1:3b', 'Zacarias 1:3b', NULL, NULL, NULL),
  ('conversao', 'Deixe o ímpio o seu caminho, e o homem maligno, os seus pensamentos e se converta ao Senhor', 'Isaías 55:7', 'Isaías', 55, 7, NULL),
  ('conversao', 'Mas, se o ímpio se converter de todos os seus pecados que cometeu, e guardar todos os meus estatutos, e fizer juízo e justiça, certamente viverá; não morrerá.', 'Ezequiel 18:21', 'Ezequiel', 18, 21, NULL),
  ('conversao', 'Eu repreendo e castigo a todos quantos amo; sê, pois, zeloso e arrepende-te.', 'Apocalipse 3:19', 'Apocalipse', 3, 19, NULL),
  ('conversao', 'Ainda assim, agora mesmo diz o Senhor', 'Joel 2:12', 'Joel', 2, 12, NULL),
  ('conversao', 'Vinde e convertei-vos de todas as vossas transgressões, e a iniquidade não vos servirá de tropeço.', 'Ezequiel 18:30b', 'Ezequiel 18:30b', NULL, NULL, NULL),
  ('conversao', 'Mas Deus, não tendo em conta os tempos da ignorância, anuncia agora a todos os homens, em todo lugar, que se arrependam.', 'Atos 17:30', 'Atos', 17, 30, NULL),
  ('conversao', 'Nem tampouco apresenteis os vossos membros ao pecado por instrumentos de iniquidade; mas apresentai-vos a Deus, como vivos dentre mortos, e os vossos membros a Deus, como instrumentos de justiça.', 'Romanos 6:13', 'Romanos', 6, 13, NULL),
  ('conversao', 'Assim vos digo que há alegria diante dos anjos de Deus por um pecador que se arrepende.', 'Lucas 15:10', 'Lucas', 15, 10, NULL),
  ('conversao', 'Vigiai justamente e não pequeis; porque alguns ainda não têm o conhecimento de Deus; digo-o para vergonha vossa.', '1 Coríntios 15:34', '1 Coríntios', 15, 34, NULL),
  ('conversao', 'Irmãos, se algum homem chegar a ser surpreendido nalguma ofensa, vós, que sois espirituais, encaminhai o tal com espírito de mansidão, olhando por ti mesmo, para que não sejas também tentado.', 'Gálatas 6:1', 'Gálatas', 6, 1, NULL),
  ('conversao', 'Tomai convosco palavras e convertei-vos ao Senhor', 'Oseias 14:2', 'Oseias', 14, 2, NULL),
  ('conversao', 'Convertei-vos pela minha repreensão; eis que abundantemente derramarei sobre vós meu espírito e vos farei saber as minhas palavras.', 'Provérbios 1:23', 'Provérbios', 1, 23, NULL),
  ('conversao', 'Não mintais uns aos outros, pois que já vos despistes do velho homem com os seus feitos e vos vestistes do novo, que se renova para o conhecimento, segundo a imagem daquele que o criou.', 'Colossenses 3:9-10', 'Colossenses', 3, 9, 10),
  ('conversao', 'E não sejais como vossos pais, aos quais clamavam os primeiros profetas, dizendo: Assim diz o Senhor', 'Zacarias 1:4', 'Zacarias', 1, 4, NULL),
  ('conversao', 'Não, vos digo; antes, se vos não arrependerdes, todos de igual modo perecereis.', 'Lucas 13:3', 'Lucas', 13, 3, NULL),
  ('conversao', 'Esquadrinhemos os nossos caminhos, experimentemo-los e voltemos para o Senhor', 'Lamentações 3:40', 'Lamentações', 3, 40, NULL),
  ('conversao', 'Porque a tristeza segundo Deus opera arrependimento para a salvação, da qual ninguém se arrepende; mas a tristeza do mundo opera a morte.', '2 Coríntios 7:10', '2 Coríntios', 7, 10, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('conversao', 'Mas Paulo disse: Certamente João batizou com o batismo do arrependimento, dizendo ao povo que cresse no que após ele havia de vir, isto é, em Jesus Cristo.', 'Atos 19:4', 'Atos', 19, 4, NULL),
  ('conversao', 'Ressuscitando Deus a seu Filho Jesus, primeiro o enviou a vós, para que nisso vos abençoasse, e vos desviasse, a cada um, das vossas maldades.', 'Atos 3:26', 'Atos', 3, 26, NULL),
  ('conversao', 'Desejaria eu, de qualquer maneira, a morte do ímpio? Diz o Senhor Jeová', 'Ezequiel 18:23', 'Ezequiel', 18, 23, NULL),
  ('conversao', 'Mas, se deveras melhorardes os vossos caminhos e as vossas obras, se deveras fizerdes juízo entre um homem e entre o seu companheiro, se não oprimirdes o estrangeiro, e o órfão, e a viúva, nem derramardes sangue inocente neste lugar, nem andardes após outros deuses para vosso próprio mal, eu vos farei habitar neste lugar, na terra que dei a vossos pais, de século em século.', 'Jeremias 7:5-7', 'Jeremias', 7, 5, 7),
  ('conversao', 'Pelo que, deixando os rudimentos da doutrina de Cristo, prossigamos até a perfeição, não lançando de novo o fundamento do arrependimento de obras mortas e de fé em Deus, e da doutrina dos batismos, e da imposição das mãos, e da ressurreição dos mortos, e do juízo eterno.', 'Hebreus 6:1-2', 'Hebreus', 6, 1, 2),
  ('conversao', 'O publicano, porém, estando em pé, de longe, nem ainda queria levantar os olhos ao céu, mas batia no peito, dizendo: Ó Deus, tem misericórdia de mim, pecador!', 'Lucas 18:13', 'Lucas', 18, 13, NULL),
  ('conversao', 'E eu, em verdade, vos batizo com água, para o arrependimento; mas aquele que vem após mim é mais poderoso do que eu; não sou digno de levar as suas sandálias; ele vos batizará com o Espírito Santo e com fogo.', 'Mateus 3:11', 'Mateus', 3, 11, NULL),
  ('conversao', 'E Deus viu as obras deles, como se converteram do seu mau caminho; e Deus se arrependeu do mal que tinha dito lhes faria e não o fez.', 'Jonas 3:10', 'Jonas', 3, 10, NULL),
  ('coracao', 'Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as saídas da vida.', 'Provérbios 4:23', 'Provérbios', 4, 23, NULL),
  ('coracao', 'Como na água o rosto corresponde ao rosto, assim o coração do homem ao homem.', 'Provérbios 27:19', 'Provérbios', 27, 19, NULL),
  ('coracao', 'Enganoso é o coração, mais do que todas as coisas, e perverso; quem o conhecerá? Eu, o Senhor', 'Jeremias 17:9-10', 'Jeremias', 17, 9, 10),
  ('coracao', 'E buscar-me-eis e me achareis quando me buscardes de todo o vosso coração.', 'Jeremias 29:13', 'Jeremias', 29, 13, NULL),
  ('coracao', 'Cria em mim, ó Deus, um coração puro e renova em mim um espírito reto.', 'Salmo 51:10', 'Salmo', 51, 10, NULL),
  ('coracao', 'O enfeite delas não seja o exterior, no frisado dos cabelos, no uso de joias de ouro, na compostura de vestes, mas o homem encoberto no coração, no incorruptível trajo de um espírito manso e quieto, que é precioso diante de Deus.', '1 Pedro 3:3-4', '1 Pedro', 3, 3, 4),
  ('coracao', 'Conceda-te conforme o teu coração e cumpra todo o teu desígnio.', 'Salmo 20:4', 'Salmo', 20, 4, NULL),
  ('coracao', 'Porém o Senhor', '1 Samuel 16:7', '1 Samuel', 16, 7, NULL),
  ('coracao', 'Confia no Senhor', 'Provérbios 3:5-6', 'Provérbios', 3, 5, 6),
  ('coracao', 'E vos darei um coração novo e porei dentro de vós um espírito novo; e tirarei o coração de pedra da vossa carne e vos darei um coração de carne.', 'Ezequiel 36:26', 'Ezequiel', 36, 26, NULL),
  ('coracao', 'Porque onde estiver o vosso tesouro, aí estará também o vosso coração.', 'Mateus 6:21', 'Mateus', 6, 21, NULL),
  ('coracao', 'E Jesus disse-lhe: Amarás o Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todo o teu pensamento.', 'Mateus 22:37', 'Mateus', 22, 37, NULL),
  ('coracao', 'Não te desamparem a benignidade e a fidelidade; ata-as ao teu pescoço; escreve-as na tábua do teu coração e acharás graça e bom entendimento aos olhos de Deus e dos homens.', 'Provérbios 3:3-4', 'Provérbios', 3, 3, 4),
  ('coracao', 'Deleita-te também no Senhor', 'Salmo 37:4', 'Salmo', 37, 4, NULL),
  ('coracao', 'O coração alegre serve de bom remédio, mas o espírito abatido virá a secar os ossos.', 'Provérbios 17:22', 'Provérbios', 17, 22, NULL),
  ('coracao', 'Sara os quebrantados de coração e liga-lhes as feridas.', 'Salmo 147:3', 'Salmo', 147, 3, NULL),
  ('coracao', 'Filho meu, não te esqueças da minha lei, e o teu coração guarde os meus mandamentos. Porque eles aumentarão os teus dias e te acrescentarão anos de vida e paz.', 'Provérbios 3:1-2', 'Provérbios', 3, 1, 2),
  ('coracao', 'Cada um contribua segundo propôs no seu coração, não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria.', '2 Coríntios 9:7', '2 Coríntios', 9, 7, NULL),
  ('coracao', 'O sábio de coração aceita os mandamentos, mas o louco palrador será transtornado.', 'Provérbios 10:8', 'Provérbios', 10, 8, NULL),
  ('coracao', 'Bem-aventurados os limpos de coração, porque eles verão a Deus.', 'Mateus 5:8', 'Mateus', 5, 8, NULL),
  ('coracao', 'De todo o meu coração te busquei; não me deixes desviar dos teus mandamentos.', 'Salmo 119:10', 'Salmo', 119, 10, NULL),
  ('coracao', 'Esforçai-vos, e ele fortalecerá o vosso coração, vós todos os que esperais no Senhor', 'Salmo 31:24', 'Salmo', 31, 24, NULL),
  ('coracao', 'Afasta, pois, a ira do teu coração e remove da tua carne o mal, porque a adolescência e a juventude são vaidade.', 'Eclesiastes 11:10', 'Eclesiastes', 11, 10, NULL),
  ('coracao', 'Ensina-nos a contar os nossos dias, de tal maneira que alcancemos coração sábio.', 'Salmo 90:12', 'Salmo', 90, 12, NULL),
  ('coracao', 'Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, Senhor', 'Salmo 19:14', 'Salmo', 19, 14, NULL),
  ('coracao', 'Bem-aventurados os que guardam os seus testemunhos e o buscam de todo o coração.', 'Salmo 119:2', 'Salmo', 119, 2, NULL),
  ('coracao', 'Porque em verdade vos digo que qualquer que disser a este monte: Ergue-te e lança-te no mar, e não duvidar em seu coração, mas crer que se fará aquilo que diz, tudo o que disser lhe será feito.', 'Marcos 11:23', 'Marcos', 11, 23, NULL),
  ('coracao', 'Louvar-te-ei com retidão de coração, quando tiver aprendido os teus justos juízos.', 'Salmo 119:7', 'Salmo', 119, 7, NULL),
  ('coracao', 'A solicitude no coração do homem o abate, mas uma boa palavra o alegra.', 'Provérbios 12:25', 'Provérbios', 12, 25, NULL),
  ('coracao', 'Vede, irmãos, que nunca haja em qualquer de vós um coração mau e infiel, para se apartar do Deus vivo.', 'Hebreus 3:12', 'Hebreus', 3, 12, NULL),
  ('coracao', 'Põe-me como selo sobre o teu coração, como selo sobre o teu braço, porque o amor é forte como a morte, e duro como a sepultura o ciúme; as suas brasas são brasas de fogo, labaredas do Senhor', 'Cantares 8:6', 'Cantares', 8, 6, NULL),
  ('coracao', 'A esperança demorada enfraquece o coração, mas o desejo chegado é árvore de vida.', 'Provérbios 13:12', 'Provérbios', 13, 12, NULL),
  ('coracao', 'Tão somente tende cuidado de guardar com diligência o mandamento e a lei que Moisés, o servo do Senhor', 'Josué 22:5', 'Josué', 22, 5, NULL),
  ('coracao', 'Escondi a tua palavra no meu coração, para eu não pecar contra ti.', 'Salmo 119:11', 'Salmo', 119, 11, NULL),
  ('coracao', 'Mas eu confio na tua benignidade; na tua salvação, meu coração se alegrará. Cantarei ao Senhor', 'Salmo 13:5-6', 'Salmo', 13, 5, 6),
  ('coracao', 'E a esperança não traz confusão, porquanto o amor de Deus está derramado em nosso coração pelo Espírito Santo que nos foi dado.', 'Romanos 5:5', 'Romanos', 5, 5, NULL),
  ('coracao', 'Vai, pois, come com alegria o teu pão e bebe com bom coração o teu vinho, pois já Deus se agrada das tuas obras.', 'Eclesiastes 9:7', 'Eclesiastes', 9, 7, NULL),
  ('coracao', 'Ensina-me, Senhor', 'Salmo 86:11', 'Salmo', 86, 11, NULL),
  ('coracao', 'E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor', 'Joel 2:13', 'Joel', 2, 13, NULL),
  ('coracao', 'Os teus testemunhos tenho eu tomado por herança para sempre, pois são o gozo do meu coração.', 'Salmo 119:111', 'Salmo', 119, 111, NULL),
  ('coracao', 'Filho meu, atenta para as minhas palavras; às minhas razões inclina o teu ouvido. Não as deixes apartar-se dos teus olhos; guarda-as no meio do teu coração.', 'Provérbios 4:20-21', 'Provérbios', 4, 20, 21),
  ('coracao', 'Filho meu, se o teu coração for sábio, alegrar-se-á o meu coração, sim, o meu próprio.', 'Provérbios 23:15', 'Provérbios', 23, 15, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('coracao', 'E ele disse-lhes: Assim também vós estais sem entendimento? Não compreendeis que tudo o que de fora entra no homem não o pode contaminar, porque não entra no seu coração, mas no ventre e é lançado fora, ficando puras todas as comidas?', 'Marcos 7:18-19', 'Marcos', 7, 18, 19),
  ('coracao', 'Ainda assim, agora mesmo diz o Senhor', 'Joel 2:12', 'Joel', 2, 12, NULL),
  ('coracao', 'Ainda que um exército me cercasse, o meu coração não temeria; ainda que a guerra se levantasse contra mim, nele confiaria.', 'Salmo 27:3', 'Salmo', 27, 3, NULL),
  ('coracao', 'Inclina o meu coração a teus testemunhos e não à cobiça.', 'Salmo 119:36', 'Salmo', 119, 36, NULL),
  ('coracao', 'Eu te louvarei, Senhor', 'Salmo 9:1', 'Salmo', 9, 1, NULL),
  ('coracao', 'Ouvistes que foi dito aos antigos: Não cometerás adultério. Eu porém, vos digo que qualquer que atentar numa mulher para a cobiçar já em seu coração cometeu adultério com ela.', 'Mateus 5:27-28', 'Mateus', 5, 27, 28),
  ('coracao', 'E que amá-lo de todo o coração, e de todo o entendimento, e de toda a alma, e de todas as forças e amar o próximo como a si mesmo é mais do que todos os holocaustos e sacrifícios.', 'Marcos 12:33', 'Marcos', 12, 33, NULL),
  ('coracao', 'Os preceitos do Senhor', 'Salmo 19:8', 'Salmo', 19, 8, NULL),
  ('coracao', 'E eis aqui eu vou, hoje, pelo caminho de toda a terra; e vós bem sabeis, com todo o vosso coração e com toda a vossa alma que nem uma só palavra caiu de todas as boas palavras que falou de vós o Senhor', 'Josué 23:14', 'Josué', 23, 14, NULL),
  ('coracao', 'Só ele é a minha rocha e a minha salvação; é a minha defesa; não serei abalado.', 'Salmo 62:6', 'Salmo', 62, 6, NULL),
  ('coracao', 'Tão somente temei ao Senhor', '1 Samuel 12:24', '1 Samuel', 12, 24, NULL),
  ('coracao', 'Foge, também, dos desejos da mocidade; e segue a justiça, a fé, o amor e a paz com os que, com um coração puro, invocam o Senhor.', '2 Timóteo 2:22', '2 Timóteo', 2, 22, NULL),
  ('coracao', 'Agora, pois, deitai fora os deuses estranhos que há no meio de vós: e inclinai o vosso coração ao Senhor', 'Josué 24:23', 'Josué', 24, 23, NULL),
  ('coracao', 'Visto como se não executa logo o juízo sobre a má obra, por isso o coração dos filhos dos homens está inteiramente disposto para praticar o mal.', 'Eclesiastes 8:11', 'Eclesiastes', 8, 11, NULL),
  ('coracao', 'Deleito-me em fazer a tua vontade, ó Deus meu; sim, a tua lei está dentro do meu coração.', 'Salmo 40:8', 'Salmo', 40, 8, NULL),
  ('coragem', 'O Senhor', 'Deuteronômio 31:8', 'Deuteronômio', 31, 8, NULL),
  ('coragem', 'Não to mandei eu? Esforça-te e tem bom ânimo; não pasmes, nem te espantes, porque o Senhor', 'Josué 1:9', 'Josué', 1, 9, NULL),
  ('coragem', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda consolação, que nos consola em toda a nossa tribulação, para que também possamos consolar os que estiverem em alguma tribulação, com a consolação com que nós mesmos somos consolados de Deus.', '2 Coríntios 1:3-4', '2 Coríntios', 1, 3, 4),
  ('coragem', 'Vigiai, estai firmes na fé, portai-vos varonilmente e fortalecei-vos.', '1 Coríntios 16:13', '1 Coríntios', 16, 13, NULL),
  ('coragem', 'Esforçai-vos, e ele fortalecerá o vosso coração, vós todos os que esperais no Senhor', 'Salmo 31:24', 'Salmo', 31, 24, NULL),
  ('coragem', 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.', 'João 14:27', 'João', 14, 27, NULL),
  ('coragem', 'Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo; a tua vara e o teu cajado me consolam.', 'Salmo 23:4', 'Salmo', 23, 4, NULL),
  ('coragem', 'Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', '2 Timóteo 1:7', '2 Timóteo', 1, 7, NULL),
  ('coragem', 'Esforçai-vos, e animai-vos; não temais, nem vos espanteis diante deles, porque o Senhor', 'Deuteronômio 31:6', 'Deuteronômio', 31, 6, NULL),
  ('coragem', 'Espera no Senhor', 'Salmo 27:14', 'Salmo', 27, 14, NULL),
  ('coragem', 'Mas, quando eles o viram andar sobre o mar, pensaram que era um fantasma e deram grandes gritos. Porque todos o viram e perturbaram-se; mas logo falou com eles e disse-lhes: Tende bom ânimo, sou eu; não temais.', 'Marcos 6:49-50', 'Marcos', 6, 49, 50),
  ('corpo', 'Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos? Porque fostes comprados por bom preço; glorificai, pois, a Deus no vosso corpo e no vosso espírito, os quais pertencem a Deus.', '1 Coríntios 6:19-20', '1 Coríntios', 6, 19, 20),
  ('corpo', 'Porque assim como em um corpo temos muitos membros, e nem todos os membros têm a mesma operação, assim nós, que somos muitos, somos um só corpo em Cristo, mas individualmente somos membros uns dos outros.', 'Romanos 12:4-5', 'Romanos', 12, 4, 5),
  ('corpo', 'Pois possuíste o meu interior; entreteceste-me no ventre de minha mãe. Eu te louvarei, porque de um modo terrível e tão maravilhoso fui formado; maravilhosas são as tuas obras, e a minha alma o sabe muito bem.', 'Salmo 139:13-14', 'Salmo', 139, 13, 14),
  ('corpo', 'A minha carne e o meu coração desfalecem; mas Deus é a fortaleza do meu coração e a minha porção para sempre.', 'Salmo 73:26', 'Salmo', 73, 26, NULL),
  ('corpo', 'Afasta, pois, a ira do teu coração e remove da tua carne o mal, porque a adolescência e a juventude são vaidade.', 'Eclesiastes 11:10', 'Eclesiastes', 11, 10, NULL),
  ('corpo', 'O coração alegre serve de bom remédio, mas o espírito abatido virá a secar os ossos.', 'Provérbios 17:22', 'Provérbios', 17, 22, NULL),
  ('corpo', 'Vigiai e orai, para que não entreis em tentação; na verdade, o espírito está pronto, mas a carne é fraca.', 'Mateus 26:41', 'Mateus', 26, 41, NULL),
  ('corpo', 'Porque o exercício corporal para pouco aproveita, mas a piedade para tudo é proveitosa, tendo a promessa da vida presente e da que há de vir.', '1 Timóteo 4:8', '1 Timóteo', 4, 8, NULL),
  ('corpo', 'Não sejas sábio a teus próprios olhos; teme ao Senhor', 'Provérbios 3:7-8', 'Provérbios', 3, 7, 8),
  ('corpo', 'Por isso, não desfalecemos; mas, ainda que o nosso homem exterior se corrompa, o interior, contudo, se renova de dia em dia.', '2 Coríntios 4:16', '2 Coríntios', 4, 16, NULL),
  ('corpo', 'Antes, subjugo o meu corpo e o reduzo à servidão, para que, pregando aos outros, eu mesmo não venha de alguma maneira a ficar reprovado.', '1 Coríntios 9:27', '1 Coríntios', 9, 27, NULL),
  ('corpo', 'E a paz de Deus, para a qual também fostes chamados em um corpo, domine em vossos corações; e sede agradecidos.', 'Colossenses 3:15', 'Colossenses', 3, 15, NULL),
  ('corpo', 'Favo de mel são as palavras suaves: doces para a alma e saúde para os ossos.', 'Provérbios 16:24', 'Provérbios', 16, 24, NULL),
  ('corpo', 'Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também.', '1 Coríntios 12:12', '1 Coríntios', 12, 12, NULL),
  ('corpo', 'Por isso, vos digo: não andeis cuidadosos quanto à vossa vida, pelo que haveis de comer ou pelo que haveis de beber; nem quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o mantimento, e o corpo, mais do que a vestimenta?', 'Mateus 6:25', 'Mateus', 6, 25, NULL),
  ('corpo', 'Há um só corpo e um só Espírito, como também fostes chamados em uma só esperança da vossa vocação.', 'Efésios 4:4', 'Efésios', 4, 4, NULL),
  ('corpo', 'E não temais os que matam o corpo e não podem matar a alma; temei, antes, aquele que pode fazer perecer no inferno a alma e o corpo.', 'Mateus 10:28', 'Mateus', 10, 28, NULL),
  ('corpo', 'Porque todos tropeçamos em muitas coisas. Se alguém não tropeça em palavra, o tal varão é perfeito e poderoso para também refrear todo o corpo.', 'Tiago 3:2', 'Tiago', 3, 2, NULL),
  ('corpo', 'Portanto, se o teu olho direito te escandalizar, arranca-o e atira-o para longe de ti, pois te é melhor que se perca um dos teus membros do que todo o teu corpo seja lançado no inferno.', 'Mateus 5:29', 'Mateus', 5, 29, NULL),
  ('corpo', 'Não estejais apreensivos pela vossa vida, sobre o que comereis, nem pelo corpo, sobre o que vestireis. Mais é a vida do que o sustento, e o corpo, mais do que as vestes.', 'Lucas 12:22b-23', 'Lucas 12:22b-23', NULL, NULL, NULL),
  ('corpo', 'Porque sabemos que, se a nossa casa terrestre deste tabernáculo se desfizer, temos de Deus um edifício, uma casa não feita por mãos, eterna, nos céus.', '2 Coríntios 5:1', '2 Coríntios', 5, 1, NULL),
  ('corpo', 'O marido pague à mulher a devida benevolência, e da mesma sorte a mulher, ao marido. A mulher não tem poder sobre o seu próprio corpo, mas tem-no o marido; e também, da mesma maneira, o marido não tem poder sobre o seu próprio corpo, mas tem-no a mulher.', '1 Coríntios 7:3-4', '1 Coríntios', 7, 3, 4),
  ('corpo', 'Ó Deus, tu és o meu Deus; de madrugada te buscarei; a minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água.', 'Salmo 63:1', 'Salmo', 63, 1, NULL),
  ('corpo', 'E da costela que o Senhor', 'Gênesis 2:22-24', 'Gênesis', 2, 22, 24);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('corpo', 'E, tomando o pão e havendo dado graças, partiu-o e deu-lho, dizendo: Isto é o meu corpo, que por vós é dado; fazei isso em memória de mim.', 'Lucas 22:19', 'Lucas', 22, 19, NULL),
  ('corpo', 'Quem come a minha carne e bebe o meu sangue permanece em mim, e eu, nele.', 'João 6:56', 'João', 6, 56, NULL),
  ('corpo', 'Pois todos nós fomos batizados em um Espírito, formando um corpo, quer judeus, quer gregos, quer servos, quer livres, e todos temos bebido de um Espírito.', '1 Coríntios 12:13', '1 Coríntios', 12, 13, NULL),
  ('corpo', 'Mas revesti-vos do Senhor Jesus Cristo e não tenhais cuidado da carne em suas concupiscências.', 'Romanos 13:14', 'Romanos', 13, 14, NULL),
  ('corpo', 'E ainda que distribuísse toda a minha fortuna para sustento dos pobres, e ainda que entregasse o meu corpo para ser queimado, e não tivesse amor, nada disso me aproveitaria.', '1 Coríntios 13:3', '1 Coríntios', 13, 3, NULL),
  ('corpo', 'Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, pudéssemos viver para a justiça; e pelas suas feridas fostes sarados.', '1 Pedro 2:24', '1 Pedro', 2, 24, NULL),
  ('corpo', 'Assim devem os maridos amar a sua própria mulher como a seu próprio corpo. Quem ama a sua mulher ama-se a si mesmo.', 'Efésios 5:28', 'Efésios', 5, 28, NULL),
  ('corpo', 'Eu sou o pão vivo que desceu do céu; se alguém comer desse pão, viverá para sempre; e o pão que eu der é a minha carne, que eu darei pela vida do mundo.', 'João 6:51', 'João', 6, 51, NULL),
  ('corpo', 'Vós, mulheres, sujeitai-vos a vosso marido, como ao Senhor; porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo.', 'Efésios 5:22-23', 'Efésios', 5, 22, 23),
  ('corpo', 'Por isso, deixará o homem seu pai e sua mãe e se unirá à sua mulher; e serão dois numa carne.', 'Efésios 5:31', 'Efésios', 5, 31, NULL),
  ('corpo', 'E ele disse-lhes: Assim também vós estais sem entendimento? Não compreendeis que tudo o que de fora entra no homem não o pode contaminar, porque não entra no seu coração, mas no ventre e é lançado fora, ficando puras todas as comidas?', 'Marcos 7:18-19', 'Marcos', 7, 18, 19),
  ('corpo', 'Porque esta é a vontade de Deus, a vossa santificação: que vos abstenhais da prostituição, que cada um de vós saiba possuir o seu vaso em santificação e honra, não na paixão de concupiscência, como os gentios, que não conhecem a Deus.', '1 Tessalonicenses 4:3-5', '1 Tessalonicenses', 4, 3, 5),
  ('corpo', 'Porque as obras da carne são manifestas, as quais são: prostituição, impureza, lascívia, idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias, invejas, homicídios, bebedices, glutonarias e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas não herdarão o Reino de Deus.', 'Gálatas 5:19-21', 'Gálatas', 5, 19, 21),
  ('corpo', 'Porque os que são segundo a carne inclinam-se para as coisas da carne; mas os que são segundo o Espírito, para as coisas do Espírito.', 'Romanos 8:5', 'Romanos', 8, 5, NULL),
  ('corpo', 'Porém, desde o princípio da criação, Deus os fez macho e fêmea. Por isso, deixará o homem a seu pai e a sua mãe e unir-se-á a sua mulher. E serão os dois uma só carne e, assim, já não serão dois, mas uma só carne. Portanto, o que Deus ajuntou, não o separe o homem.', 'Marcos 10:6-9', 'Marcos', 10, 6, 9),
  ('corpo', 'Fugi da prostituição. Todo pecado que o homem comete é fora do corpo; mas o que se prostitui peca contra o seu próprio corpo.', '1 Coríntios 6:18', '1 Coríntios', 6, 18, NULL),
  ('corpo', 'Enquanto comiam, Jesus tomou o pão, e, abençoando-o, o partiu, e o deu aos discípulos, e disse: Tomai, comei, isto é o meu corpo.', 'Mateus 26:26', 'Mateus', 26, 26, NULL),
  ('corpo', 'A candeia do corpo são os olhos; de sorte que, se os teus olhos forem bons, todo o teu corpo terá luz. Se, porém, os teus olhos forem maus, o teu corpo será tenebroso. Se, portanto, a luz que em ti há são trevas, quão grandes serão tais trevas!', 'Mateus 6:22-23', 'Mateus', 6, 22, 23),
  ('criacao', 'No princípio, criou Deus os céus e a terra. E a terra era sem forma e vazia; e havia trevas sobre a face do abismo; e o Espírito de Deus se movia sobre a face das águas.', 'Gênesis 1:1-2', 'Gênesis', 1, 1, 2),
  ('criacao', 'Pois possuíste o meu interior; entreteceste-me no ventre de minha mãe. Eu te louvarei, porque de um modo terrível e tão maravilhoso fui formado; maravilhosas são as tuas obras, e a minha alma o sabe muito bem.', 'Salmo 139:13-14', 'Salmo', 139, 13, 14),
  ('criacao', 'Porque toda casa é edificada por alguém, mas o que edificou todas as coisas é Deus.', 'Hebreus 3:4', 'Hebreus', 3, 4, NULL),
  ('criacao', 'Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder como a sua divindade, se entendem e claramente se veem pelas coisas que estão criadas, para que eles fiquem inescusáveis.', 'Romanos 1:20', 'Romanos', 1, 20, NULL),
  ('criacao', 'Ah! Senhor Jeová', 'Jeremias 32:17', 'Jeremias', 32, 17, NULL),
  ('criacao', 'E abençoou Deus o dia sétimo e o santificou; porque nele descansou de toda a sua obra, que Deus criara e fizera.', 'Gênesis 2:3', 'Gênesis', 2, 3, NULL),
  ('criacao', 'Porque dele, e por ele, e para ele são todas as coisas; glória, pois, a ele eternamente. Amém!', 'Romanos 11:36', 'Romanos', 11, 36, NULL),
  ('criacao', 'Elevo os olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor', 'Salmo 121:1-2', 'Salmo', 121, 1, 2),
  ('criacao', 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas.', 'Efésios 2:10', 'Efésios', 2, 10, NULL),
  ('criacao', 'E criou Deus o homem à sua imagem; à imagem de Deus o criou; macho e fêmea os criou.', 'Gênesis 1:27', 'Gênesis', 1, 27, NULL),
  ('criacao', 'Pela palavra do Senhor', 'Salmo 33:6', 'Salmo', 33, 6, NULL),
  ('criacao', 'Não sabes, não ouviste que o eterno Deus, o Senhor', 'Isaías 40:28', 'Isaías', 40, 28, NULL),
  ('criacao', 'Tudo fez formoso em seu tempo; também pôs o mundo no coração deles, sem que o homem possa descobrir a obra que Deus fez desde o princípio até ao fim.', 'Eclesiastes 3:11', 'Eclesiastes', 3, 11, NULL),
  ('criacao', 'Antes que os montes nascessem, ou que tu formasses a terra e o mundo, sim, de eternidade a eternidade, tu és Deus.', 'Salmo 90:2', 'Salmo', 90, 2, NULL),
  ('criacao', 'Porque a ardente expectação da criatura espera a manifestação dos filhos de Deus.', 'Romanos 8:19', 'Romanos', 8, 19, NULL),
  ('criacao', 'E disse Deus: Façamos o homem à nossa imagem, conforme a nossa semelhança; e domine sobre os peixes do mar, e sobre as aves dos céus, e sobre o gado, e sobre toda a terra, e sobre todo réptil que se move sobre a terra.', 'Gênesis 1:26', 'Gênesis', 1, 26, NULL),
  ('criacao', 'Este é o dia que fez o Senhor', 'Salmo 118:24', 'Salmo', 118, 24, NULL),
  ('criacao', 'Ele é o que edifica as suas câmaras no céu, e a sua abóbada fundou na terra, e o que chama as águas do mar, e as derrama sobre a terra; o Senhor', 'Amós 9:6', 'Amós', 9, 6, NULL),
  ('criacao', 'Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez.', 'João 1:3', 'João', 1, 3, NULL),
  ('criacao', 'O nosso socorro está em o nome do Senhor', 'Salmo 124:8', 'Salmo', 124, 8, NULL),
  ('criacao', 'Assim que, se alguém está em Cristo, nova criatura é: as coisas velhas já passaram; eis que tudo se fez novo.', '2 Coríntios 5:17', '2 Coríntios', 5, 17, NULL),
  ('criacao', 'E ouvi a toda criatura que está no céu, e na terra, e debaixo da terra, e que está no mar, e a todas as coisas que neles há, dizer: Ao que está assentado sobre o trono e ao Cordeiro sejam dadas ações de graças, e honra, e glória, e poder para todo o sempre.', 'Apocalipse 5:13', 'Apocalipse', 5, 13, NULL),
  ('criacao', 'Porque nele vivemos, e nos movemos, e existimos, como também alguns dos vossos poetas disseram: Pois somos também sua geração.', 'Atos 17:28', 'Atos', 17, 28, NULL),
  ('criacao', 'Segundo a sua vontade, ele nos gerou pela palavra da verdade, para que fôssemos como primícias das suas criaturas.', 'Tiago 1:18', 'Tiago', 1, 18, NULL),
  ('criacao', 'Ai daquele que contende com o seu Criador, caco entre outros cacos de barro! Porventura, dirá o barro ao que o formou: Que fazes? Ou a tua obra: Não tens mãos?', 'Isaías 45:9', 'Isaías', 45, 9, NULL),
  ('criacao', 'E disse o Senhor', 'Gênesis 2:18', 'Gênesis', 2, 18, NULL),
  ('criacao', 'Ó, vinde, adoremos e prostremo-nos! Ajoelhemos diante do Senhor', 'Salmo 95:6', 'Salmo', 95, 6, NULL),
  ('criacao', 'Todavia, para nós há um só Deus, o Pai, de quem é tudo e para quem nós vivemos; e um só Senhor, Jesus Cristo, pelo qual são todas as coisas, e nós por ele.', '1 Coríntios 8:6', '1 Coríntios', 8, 6, NULL),
  ('criacao', 'Lembra-te do teu Criador nos dias da tua mocidade, antes que venham os maus dias, e cheguem os anos dos quais venhas a dizer: Não tenho neles contentamento.', 'Eclesiastes 12:1', 'Eclesiastes', 12, 1, NULL),
  ('criacao', 'E da costela que o Senhor', 'Gênesis 2:22-24', 'Gênesis', 2, 22, 24),
  ('criacao', 'E disse Deus: Haja luz. E houve luz.', 'Gênesis 1:3', 'Gênesis', 1, 3, NULL),
  ('criacao', 'E Deus os abençoou e Deus lhes disse: Frutificai, e multiplicai-vos, e enchei a terra, e sujeitai-a; e dominai sobre os peixes do mar, e sobre as aves dos céus, e sobre todo o animal que se move sobre a terra.', 'Gênesis 1:28', 'Gênesis', 1, 28, NULL);

