-- Parte 04: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('criacao', 'Mas, agora, ó Senhor, tu és o nosso Pai; nós, o barro, e tu, o nosso oleiro; e todos nós, obra das tuas mãos.', 'Isaías 64:8', 'Isaías', 64, 8, NULL),
  ('criacao', 'Então, disse o Senhor Deus: Eis que o homem é como um de nós, sabendo o bem e o mal; ora, pois, para que não estenda a sua mão, e tome também da árvore da vida, e coma, e viva eternamente, o Senhor Deus, pois, o lançou fora do jardim do Éden, para lavrar a terra, de que fora tomado.', 'Gênesis 3:22-23', 'Gênesis', 3, 22, 23),
  ('criacao', 'Ele, porém, respondendo, disse-lhes: Não tendes lido que, no princípio, o Criador os fez macho e fêmea e disse: Portanto, deixará o homem pai e mãe e se unirá à sua mulher, e serão dois numa só carne? Assim não são mais dois, mas uma só carne. Portanto, o que Deus ajuntou não separe o homem.', 'Mateus 19:4-6', 'Mateus', 19, 4, 6),
  ('criancas', 'Jesus, porém, disse: Deixai os pequeninos e não os estorveis de vir a mim, porque dos tais é o Reino dos céus.', 'Mateus 19:14', 'Mateus', 19, 14, NULL),
  ('criancas', 'E estas palavras que hoje te ordeno estarão no teu coração; e as intimarás a teus filhos e delas falarás assentado em tua casa, e andando pelo caminho, e deitando-te, e levantando-te.', 'Deuteronômio 6:6-7', 'Deuteronômio', 6, 6, 7),
  ('criancas', 'Instrui o menino no caminho em que deve andar, e, até quando envelhecer, não se desviará dele.', 'Provérbios 22:6', 'Provérbios', 22, 6, NULL),
  ('criancas', 'Pode uma mulher esquecer-se tanto do filho que cria, que se não compadeça dele, do filho do seu ventre? Mas, ainda que esta se esquecesse, eu, todavia, me não esquecerei de ti. Eis que, na palma das minhas mãos, te tenho gravado; os teus muros estão continuamente perante mim.', 'Isaías 49:15-16', 'Isaías', 49, 15, 16),
  ('criancas', 'Coroa dos velhos são os filhos dos filhos; e a glória dos filhos são seus pais.', 'Provérbios 17:6', 'Provérbios', 17, 6, NULL),
  ('criancas', 'E, na verdade, toda correção, ao presente, não parece ser de gozo, senão de tristeza, mas, depois, produz um fruto pacífico de justiça nos exercitados por ela.', 'Hebreus 12:11', 'Hebreus', 12, 11, NULL),
  ('criancas', 'E vós, pais, não provoqueis a ira a vossos filhos, mas criai-os na doutrina e admoestação do Senhor.', 'Efésios 6:4', 'Efésios', 6, 4, NULL),
  ('criancas', 'Não tenho maior gozo do que este: o de ouvir que os meus filhos andam na verdade.', '3 João 1:4', '3 João', 1, 4, NULL),
  ('criancas', 'Sede, pois, imitadores de Deus, como filhos amados.', 'Efésios 5:1', 'Efésios', 5, 1, NULL),
  ('criancas', 'Filhinhos, guardai-vos dos ídolos. Amém!', '1 João 5:21', '1 João', 5, 21, NULL),
  ('criancas', 'Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus.', 'Mateus 5:9', 'Mateus', 5, 9, NULL),
  ('criancas', 'E eles disseram: Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa.', 'Atos 16:31', 'Atos', 16, 31, NULL),
  ('criancas', 'Porque todos sois filhos de Deus pela fé em Cristo Jesus; porque todos quantos fostes batizados em Cristo já vos revestistes de Cristo.', 'Gálatas 3:26-27', 'Gálatas', 3, 26, 27),
  ('criancas', 'O tolo despreza a correção de seu pai, mas o que observa a repreensão prudentemente se haverá.', 'Provérbios 15:5', 'Provérbios', 15, 5, NULL),
  ('criancas', 'Porque todos os que são guiados pelo Espírito de Deus, esses são filhos de Deus.', 'Romanos 8:14', 'Romanos', 8, 14, NULL),
  ('criancas', 'Vede quão grande amor nos tem concedido o Pai: que fôssemos chamados filhos de Deus. Por isso, o mundo não nos conhece, porque não conhece a ele.', '1 João 3:1', '1 João', 3, 1, NULL),
  ('criancas', 'Mas, se alguém não tem cuidado dos seus e principalmente dos da sua família, negou a fé e é pior do que o infiel.', '1 Timóteo 5:8', '1 Timóteo', 5, 8, NULL),
  ('criancas', 'Quem dera que eles tivessem tal coração que me temessem e guardassem todos os meus mandamentos todos os dias, para que bem lhes fosse a eles e a seus filhos, para sempre!', 'Deuteronômio 5:29', 'Deuteronômio', 5, 29, NULL),
  ('criancas', 'Mas a todos quantos o receberam deu-lhes o poder de serem feitos filhos de Deus: aos que creem no seu nome.', 'João 1:12', 'João', 1, 12, NULL),
  ('criancas', 'O mesmo Espírito testifica com o nosso espírito que somos filhos de Deus.', 'Romanos 8:16', 'Romanos', 8, 16, NULL),
  ('criancas', 'E guardarás os seus estatutos e os seus mandamentos, que te ordeno hoje, para que bem te vá a ti e a teus filhos depois de ti e para que prolongues os dias na terra que o Senhor, teu Deus, te dá para todo o sempre.', 'Deuteronômio 4:40', 'Deuteronômio', 4, 40, NULL),
  ('criancas', 'Porque não recebestes o espírito de escravidão, para, outra vez, estardes em temor, mas recebestes o espírito de adoção de filhos, pelo qual clamamos: Aba, Pai.', 'Romanos 8:15', 'Romanos', 8, 15, NULL),
  ('criancas', 'Amados, agora somos filhos de Deus, e ainda não é manifesto o que havemos de ser. Mas sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como é o veremos. E qualquer que nele tem esta esperança purifica-se a si mesmo, como também ele é puro.', '1 João 3:2-3', '1 João', 3, 2, 3),
  ('criancas', 'Porque a ardente expectação da criatura espera a manifestação dos filhos de Deus.', 'Romanos 8:19', 'Romanos', 8, 19, NULL),
  ('criancas', 'Porque, noutro tempo, éreis trevas, mas, agora, sois luz no Senhor; andai como filhos da luz.', 'Efésios 5:8', 'Efésios', 5, 8, NULL),
  ('crucificacao', 'Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, pudéssemos viver para a justiça; e pelas suas feridas fostes sarados.', '1 Pedro 2:24', '1 Pedro', 2, 24, NULL),
  ('crucificacao', 'Verdadeiramente, ele tomou sobre si as nossas enfermidades e as nossas dores levou sobre si; e nós o reputamos por aflito, ferido de Deus e oprimido.', 'Isaías 53:4', 'Isaías', 53, 4, NULL),
  ('crucificacao', 'Porque a palavra da cruz é loucura para os que perecem; mas para nós, que somos salvos, é o poder de Deus.', '1 Coríntios 1:18', '1 Coríntios', 1, 18, NULL),
  ('crucificacao', 'Que, sendo em forma de Deus, não teve por usurpação ser igual a Deus. Mas aniquilou-se a si mesmo, tomando a forma de servo, fazendo-se semelhante aos homens; e, achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte e morte de cruz.', 'Filipenses 2:6-8', 'Filipenses', 2, 6, 8),
  ('crucificacao', 'Olhando para Jesus, autor e consumador da fé, o qual, pelo gozo que lhe estava proposto, suportou a cruz, desprezando a afronta, e assentou-se à destra do trono de Deus.', 'Hebreus 12:2', 'Hebreus', 12, 2, NULL),
  ('crucificacao', 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne vivo-a na fé do Filho de Deus, o qual me amou e se entregou a si mesmo por mim.', 'Gálatas 2:20', 'Gálatas', 2, 20, NULL),
  ('crucificacao', 'Mas o anjo, respondendo, disse às mulheres: Não tenhais medo; pois eu sei que buscai a Jesus, que foi crucificado. Ele não está aqui, porque já ressuscitou, como tinha dito. Vinde e vede o lugar onde o Senhor jazia.', 'Mateus 28:5-6', 'Mateus', 28, 5, 6),
  ('crucificacao', 'E quem não toma a sua cruz e não segue após mim não é digno de mim.', 'Mateus 10:38', 'Mateus', 10, 38, NULL),
  ('crucificacao', 'Eis que vamos para Jerusalém, e o Filho do Homem será entregue aos príncipes dos sacerdotes e aos escribas, e condená-lo-ão à morte. E o entregarão aos gentios para que dele escarneçam, e o açoitem, e crucifiquem, e ao terceiro dia ressuscitará.', 'Mateus 20:18-19', 'Mateus', 20, 18, 19),
  ('crucificacao', 'Não está aqui, mas ressuscitou. Lembrai-vos como vos falou, estando ainda na Galileia, dizendo: Convém que o Filho do Homem seja entregue nas mãos de homens pecadores, e seja crucificado, e, ao terceiro dia, ressuscite.', 'Lucas 24:6-7', 'Lucas', 24, 6, 7),
  ('crucificacao', 'E dizia Jesus: Pai, perdoa-lhes, porque não sabem o que fazem. E, repartindo as suas vestes, lançaram sortes.', 'Lucas 23:34', 'Lucas', 23, 34, NULL),
  ('crucificacao', 'Porque, se fomos plantados juntamente com ele na semelhança da sua morte, também o seremos na da sua ressurreição; sabendo isto: que o nosso velho homem foi com ele crucificado, para que o corpo do pecado seja desfeito, a fim de que não sirvamos mais ao pecado.', 'Romanos 6:5-6', 'Romanos', 6, 5, 6),
  ('crucificacao', 'E dizia a todos: Se alguém quer vir após mim, negue-se a si mesmo, e tome cada dia a sua cruz, e siga-me.', 'Lucas 9:23', 'Lucas', 9, 23, NULL),
  ('crucificacao', 'Porém ele disse-lhes: Não vos assusteis; buscais a Jesus, o Nazareno, que foi crucificado; já ressuscitou, não está aqui; eis aqui o lugar onde o puseram.', 'Marcos 16:6', 'Marcos', 16, 6, NULL),
  ('crucificacao', 'Mas longe esteja de mim gloriar-me, a não ser na cruz de nosso Senhor Jesus Cristo, pela qual o mundo está crucificado para mim e eu, para o mundo.', 'Gálatas 6:14', 'Gálatas', 6, 14, NULL),
  ('crucificacao', 'Eis que vem com as nuvens, e todo olho o verá, até os mesmos que o traspassaram; e todas as tribos da terra se lamentarão sobre ele. Sim! Amém!', 'Apocalipse 1:7', 'Apocalipse', 1, 7, NULL),
  ('crucificacao', 'Porque nada me propus saber entre vós, senão a Jesus Cristo e este crucificado.', '1 Coríntios 2:2', '1 Coríntios', 2, 2, NULL),
  ('crucificacao', 'E, chamando a si a multidão, com os seus discípulos, disse-lhes: Se alguém quiser vir após mim, negue-se a si mesmo, e tome a sua cruz, e siga-me.', 'Marcos 8:34', 'Marcos', 8, 34, NULL),
  ('crucificacao', 'Eu sou o bom Pastor; o bom Pastor dá a sua vida pelas ovelhas.', 'João 10:11', 'João', 10, 11, NULL),
  ('crucificacao', 'E, clamando Jesus com grande voz, disse: Pai, nas tuas mãos entrego o meu espírito. E, havendo dito isso, expirou.', 'Lucas 23:46', 'Lucas', 23, 46, NULL),
  ('crucificacao', 'E, quando Jesus tomou o vinagre, disse: Está consumado. E, inclinando a cabeça, entregou o espírito.', 'João 19:30', 'João', 19, 30, NULL),
  ('crucificacao', 'E, por cima da sua cabeça, puseram escrita a sua acusação: Este é Jesus, O Rei dos Judeus.', 'Mateus 27:37', 'Mateus', 27, 37, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('cura', 'E Jesus disse-lhe: Se tu podes crer; tudo é possível ao que crê.', 'Marcos 9:23', 'Marcos', 9, 23, NULL),
  ('cura', 'Jesus, porém, ouvindo-o, respondeu-lhe, dizendo: Não temas; crê somente, e será salva.', 'Lucas 8:50', 'Lucas', 8, 50, NULL),
  ('cura', 'Sara os quebrantados de coração e liga-lhes as feridas.', 'Salmo 147:3', 'Salmo', 147, 3, NULL),
  ('cura', 'Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor; e a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados.', 'Tiago 5:14-15', 'Tiago', 5, 14, 15),
  ('cura', 'E Jesus lhe disse: Vai, a tua fé te salvou. E logo viu, e seguiu a Jesus pelo caminho.', 'Marcos 10:52', 'Marcos', 10, 52, NULL),
  ('cura', 'Sara-me, Senhor, e sararei; salva-me, e serei salvo; porque tu és o meu louvor.', 'Jeremias 17:14', 'Jeremias', 17, 14, NULL),
  ('cura', 'Curai os enfermos, limpai os leprosos, ressuscitai os mortos, expulsai os demônios; de graça recebestes, de graça dai.', 'Mateus 10:8', 'Mateus', 10, 8, NULL),
  ('cura', 'O coração alegre serve de bom remédio, mas o espírito abatido virá a secar os ossos.', 'Provérbios 17:22', 'Provérbios', 17, 22, NULL),
  ('cura', 'Mas ele foi ferido pelas nossas transgressões e moído pelas nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e, pelas suas pisaduras, fomos sarados.', 'Isaías 53:5', 'Isaías', 53, 5, NULL),
  ('cura', 'Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis; a oração feita por um justo pode muito em seus efeitos.', 'Tiago 5:16', 'Tiago', 5, 16, NULL),
  ('cura', 'Mas para vós que temeis o meu nome nascerá o sol da justiça e salvação trará debaixo das suas asas; e saireis e crescereis como os bezerros do cevadouro.', 'Malaquias 4:2', 'Malaquias', 4, 2, NULL),
  ('cura', 'E se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar a minha face, e se converter dos seus maus caminhos, então, eu ouvirei dos céus, e perdoarei os seus pecados, e sararei a sua terra.', '2 Crônicas 7:14', '2 Crônicas', 7, 14, NULL),
  ('cura', 'Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, pudéssemos viver para a justiça; e pelas suas feridas fostes sarados.', '1 Pedro 2:24', '1 Pedro', 2, 24, NULL),
  ('cura', 'Volta e dize a Ezequias, chefe do meu povo: Assim diz o Senhor, Deus de Davi, teu pai: Ouvi a tua oração e vi as tuas lágrimas; eis que eu te sararei; ao terceiro dia subirás à Casa do Senhor.', '2 Reis 20:5', '2 Reis', 20, 5, NULL),
  ('cura', 'E curai os enfermos que nela houver e dizei-lhes: É chegado a vós o Reino de Deus.', 'Lucas 10:9', 'Lucas', 10, 9, NULL),
  ('cura', 'Enviou a sua palavra, e os sarou, e os livrou da sua destruição.', 'Salmo 107:20', 'Salmo', 107, 20, NULL),
  ('cura', 'Jesus, porém, ouvindo, disse-lhes: Não necessitam de médico os sãos, mas sim, os doentes.', 'Mateus 9:12', 'Mateus', 9, 12, NULL),
  ('cura', 'Se ouvires atento a voz do Senhor, teu Deus, e fizeres o que é reto diante de seus olhos, e inclinares os teus ouvidos aos seus mandamentos, e guardares todos os seus estatutos, nenhuma das enfermidades porei sobre ti, que pus sobre o Egito; porque eu sou o Senhor, que te sara.', 'Êxodo 15:26', 'Êxodo', 15, 26, NULL),
  ('cura', 'O Senhor abre os olhos aos cegos; o Senhor levanta os abatidos; o Senhor ama os justos.', 'Salmo 146:8', 'Salmo', 146, 8, NULL),
  ('cura', 'E ensinava no sábado, numa das sinagogas. E eis que estava ali uma mulher que tinha um espírito de enfermidade havia já dezoito anos; e andava curvada e não podia de modo algum endireitar-se. E, vendo-a Jesus, chamou-a a si, e disse-lhe: Mulher, estás livre da tua enfermidade. E impôs as mãos sobre ela, e logo se endireitou e glorificava a Deus. E, tomando a palavra o príncipe da sinagoga, indignado porque Jesus curava no sábado, disse à multidão: Seis dias há em que é mister trabalhar; nestes, pois, vinde para serdes curados e não no dia de sábado. Respondeu-lhe, porém, o Senhor e disse: Hipócrita, no sábado não desprende da manjedoura cada um de vós o seu boi ou jumento e não o leva a beber água? E não convinha soltar desta prisão, no dia de sábado, esta filha de Abraão, a qual há dezoito anos Satanás mantinha presa? E, dizendo ele isso, todos os seus adversários ficaram envergonhados, e todo o povo se alegrava por todas as coisas gloriosas que eram feitas por ele.', 'Lucas 13:10-17', 'Lucas', 13, 10, 17),
  ('cura', 'O Espírito do Senhor é sobre mim, pois que me ungiu para evangelizar os pobres, enviou-me a curar os quebrantados do coração.', 'Lucas 4:18', 'Lucas', 4, 18, NULL),
  ('cura', 'E percorria Jesus toda a Galileia, ensinando nas suas sinagogas, e pregando o evangelho do Reino, e curando todas as enfermidades e moléstias entre o povo.', 'Mateus 4:23', 'Mateus', 4, 23, NULL),
  ('dar', 'Cada um contribua segundo propôs no seu coração, não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria.', '2 Coríntios 9:7', '2 Coríntios', 9, 7, NULL),
  ('dar', 'Porque quem sou eu, e quem é o meu povo, que tivéssemos poder para tão voluntariamente dar semelhantes coisas? Porque tudo vem de ti, e da tua mão to damos.', '1 Crônicas 29:14', '1 Crônicas', 29, 14, NULL),
  ('dar', 'O presente do homem alarga-lhe o caminho e leva-o à presença dos grandes.', 'Provérbios 18:16', 'Provérbios', 18, 16, NULL),
  ('dar', 'A alma generosa engordará, e o que regar também será regado.', 'Provérbios 11:25', 'Provérbios', 11, 25, NULL),
  ('dar', 'Porque, se há prontidão de vontade, será aceita segundo o que qualquer tem e não segundo o que não tem.', '2 Coríntios 8:12', '2 Coríntios', 8, 12, NULL),
  ('dar', 'Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando vos darão; porque com a mesma medida com que medirdes também vos medirão de novo.', 'Lucas 6:38', 'Lucas', 6, 38, NULL),
  ('dar', 'Honra ao Senhor com a tua fazenda e com as primícias de toda a tua renda.', 'Provérbios 3:9', 'Provérbios', 3, 9, NULL),
  ('dar', 'Para que em tudo enriqueçais para toda a beneficência, a qual faz que por nós se deem graças a Deus.', '2 Coríntios 9:11', '2 Coríntios', 9, 11, NULL),
  ('dar', 'Ora, aquele que dá a semente ao que semeia e pão para comer também multiplicará a vossa sementeira e aumentará os frutos da vossa justiça.', '2 Coríntios 9:10', '2 Coríntios', 9, 10, NULL),
  ('dar', 'E Deus é poderoso para tornar abundante em vós toda graça, a fim de que, tendo sempre, em tudo, toda suficiência, superabundeis em toda boa obra.', '2 Coríntios 9:8', '2 Coríntios', 9, 8, NULL),
  ('dar', 'Não detenhas dos seus donos o bem, estando na tua mão poder fazê-lo.', 'Provérbios 3:27', 'Provérbios', 3, 27, NULL),
  ('dar', 'Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa, e depois fazei prova de mim, diz o Senhor dos Exércitos, se eu não vos abrir as janelas do céu e não derramar sobre vós uma bênção tal, que dela vos advenha a maior abastança.', 'Malaquias 3:10', 'Malaquias', 3, 10, NULL),
  ('dar', 'Quando, pois, deres esmola, não faças tocar trombeta diante de ti, como fazem os hipócritas nas sinagogas e nas ruas, para serem glorificados pelos homens. Em verdade vos digo que já receberam o seu galardão.', 'Mateus 6:2', 'Mateus', 6, 2, NULL),
  ('dar', 'E dá a qualquer que te pedir; e ao que tomar o que é teu, não lho tornes a pedir.', 'Lucas 6:30', 'Lucas', 6, 30, NULL),
  ('dar', 'Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração.', 'Salmo 37:4', 'Salmo', 37, 4, NULL),
  ('dar', 'Todo o dia avidamente cobiça, mas o justo dá e nada retém.', 'Provérbios 21:26', 'Provérbios', 21, 26, NULL),
  ('dar', 'Disse-lhe Jesus: Se queres ser perfeito, vai, vende tudo o que tens, dá-o aos pobres e terás um tesouro no céu; e vem e segue-me.', 'Mateus 19:21', 'Mateus', 19, 21, NULL),
  ('dar', 'E ainda que distribuísse toda a minha fortuna para sustento dos pobres, e ainda que entregasse o meu corpo para ser queimado, e não tivesse amor, nada disso me aproveitaria.', '1 Coríntios 13:3', '1 Coríntios', 13, 3, NULL),
  ('dar', 'O ímpio toma emprestado e não paga; mas o justo se compadece e dá.', 'Salmo 37:21', 'Salmo', 37, 21, NULL),
  ('dar', 'Mas, quando tu deres esmola, não saiba a tua mão esquerda o que faz a tua direita, para que a tua esmola seja dada ocultamente, e teu Pai, que vê em secreto, te recompensará publicamente.', 'Mateus 6:3-4', 'Mateus', 6, 3, 4),
  ('dar', 'Curai os enfermos, limpai os leprosos, ressuscitai os mortos, expulsai os demônios; de graça recebestes, de graça dai.', 'Mateus 10:8', 'Mateus', 10, 8, NULL),
  ('dar', 'E digo isto: Que o que semeia pouco pouco também ceifará; e o que semeia em abundância em abundância também ceifará.', '2 Coríntios 9:6', '2 Coríntios', 9, 6, NULL),
  ('dar', 'Disse-lhes mais: Ide, e comei as gorduras, e bebei as doçuras, e enviai porções aos que não têm nada preparado para si; porque esse dia é consagrado ao nosso Senhor; portanto, não vos entristeçais, porque a alegria do Senhor é a vossa força.', 'Neemias 8:10', 'Neemias', 8, 10, NULL),
  ('dar', 'Abre a tua boca, julga retamente e faze justiça aos pobres e aos necessitados.', 'Provérbios 31:9', 'Provérbios', 31, 9, NULL),
  ('dar', 'E, respondendo ele, disse-lhes: Quem tiver duas túnicas, que reparta com o que não tem, e quem tiver alimentos, que faça da mesma maneira.', 'Lucas 3:11', 'Lucas', 3, 11, NULL),
  ('dependencia', 'Porque eu, o Senhor, teu Deus, te tomo pela tua mão direita e te digo: não temas, que eu te ajudo.', 'Isaías 41:13', 'Isaías', 41, 13, NULL),
  ('dependencia', 'Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.', 'Provérbios 3:5-6', 'Provérbios', 3, 5, 6),
  ('dependencia', 'O coração do homem considera o seu caminho, mas o Senhor lhe dirige os passos.', 'Provérbios 16:9', 'Provérbios', 16, 9, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('dependencia', 'A minha carne e o meu coração desfalecem; mas Deus é a fortaleza do meu coração e a minha porção para sempre.', 'Salmo 73:26', 'Salmo', 73, 26, NULL),
  ('dependencia', 'Elevo os olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor, que fez o céu e a terra.', 'Salmo 121:1-2', 'Salmo', 121, 1, 2),
  ('dependencia', 'Muitos propósitos há no coração do homem, mas o conselho do Senhor permanecerá.', 'Provérbios 19:21', 'Provérbios', 19, 21, NULL),
  ('dependencia', 'Eu sou a videira, vós, as varas; quem está em mim, e eu nele, este dá muito fruto, porque sem mim nada podereis fazer.', 'João 15:5', 'João', 15, 5, NULL),
  ('dependencia', 'Dá vigor ao cansado e multiplica as forças ao que não tem nenhum vigor.', 'Isaías 40:29', 'Isaías', 40, 29, NULL),
  ('dependencia', 'Não digo isto como por necessidade, porque já aprendi a contentar-me com o que tenho.', 'Filipenses 4:11', 'Filipenses', 4, 11, NULL),
  ('dependencia', 'Não vos inquieteis, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal.', 'Mateus 6:34', 'Mateus', 6, 34, NULL),
  ('dependencia', 'Não deixará vacilar o teu pé; aquele que te guarda não tosquenejará.', 'Salmo 121:3', 'Salmo', 121, 3, NULL),
  ('dependencia', 'Tenho posto o Senhor continuamente diante de mim; por isso que ele está à minha mão direita, nunca vacilarei.', 'Salmo 16:8', 'Salmo', 16, 8, NULL),
  ('dependencia', 'O Senhor é o meu pastor; nada me faltará. Deitar-me faz em verdes pastos, guia-me mansamente a águas tranquilas.', 'Salmo 23:1-2', 'Salmo', 23, 1, 2),
  ('dependencia', 'Sede unânimes entre vós; não ambicioneis coisas altas, mas acomodai-vos às humildes; não sejais sábios em vós mesmos.', 'Romanos 12:16', 'Romanos', 12, 16, NULL),
  ('dependencia', 'Se o Senhor não edificar a casa, em vão trabalham os que edificam; se o Senhor não guardar a cidade, em vão vigia a sentinela.', 'Salmo 127:1', 'Salmo', 127, 1, NULL),
  ('dependencia', 'O Senhor pelejará por vós, e vos calareis.', 'Êxodo 14:14', 'Êxodo', 14, 14, NULL),
  ('dependencia', 'A bênção do Senhor é que enriquece, e ele não acrescenta dores.', 'Provérbios 10:22', 'Provérbios', 10, 22, NULL),
  ('dependencia', 'Quando eu disse: O meu pé vacila; a tua benignidade, Senhor, me susteve.', 'Salmo 94:18', 'Salmo', 94, 18, NULL),
  ('dependencia', 'No dia da prosperidade, goza do bem, mas, no dia da adversidade, considera; porque também Deus fez este em oposição àquele, para que o homem nada ache que tenha de vir depois dele.', 'Eclesiastes 7:14', 'Eclesiastes', 7, 14, NULL),
  ('dependencia', 'Invoquei o Senhor na angústia; o Senhor me ouviu e me pôs em um lugar largo.', 'Salmo 118:5', 'Salmo', 118, 5, NULL),
  ('dependencia', 'Porque quem sou eu, e quem é o meu povo, que tivéssemos poder para tão voluntariamente dar semelhantes coisas? Porque tudo vem de ti, e da tua mão to damos.', '1 Crônicas 29:14', '1 Crônicas', 29, 14, NULL),
  ('dependencia', 'Guarda-me, ó Deus, porque em ti confio.', 'Salmo 16:1', 'Salmo', 16, 1, NULL),
  ('dependencia', 'Portanto, os que estão na carne não podem agradar a Deus.', 'Romanos 8:8', 'Romanos', 8, 8, NULL),
  ('dependencia', 'Pois não conquistaram a terra pela sua espada, nem o seu braço os salvou, e sim a tua destra, e o teu braço, e a luz da tua face, porquanto te agradaste deles.', 'Salmo 44:3', 'Salmo', 44, 3, NULL),
  ('dependencia', 'Faze-nos voltar, Senhor, Deus dos Exércitos; faze resplandecer o teu rosto, e seremos salvos.', 'Salmo 80:19', 'Salmo', 80, 19, NULL),
  ('dependencia', 'Bendito seja o Senhor, que de dia em dia nos cumula de benefícios; o Deus que é a nossa salvação. (Selá)', 'Salmo 68:19', 'Salmo', 68, 19, NULL),
  ('dependencia', 'Porque assim como em um corpo temos muitos membros, e nem todos os membros têm a mesma operação, assim nós, que somos muitos, somos um só corpo em Cristo, mas individualmente somos membros uns dos outros.', 'Romanos 12:4-5', 'Romanos', 12, 4, 5),
  ('dependencia', 'Eis que Deus é o meu ajudador; o Senhor está com aqueles que sustêm a minha alma.', 'Salmo 54:4', 'Salmo', 54, 4, NULL),
  ('dependencia', 'Em ti, Senhor, confio; nunca me deixes confundido; livra-me pela tua justiça.', 'Salmo 31:1', 'Salmo', 31, 1, NULL),
  ('dependencia', 'Mas tu, Senhor, és um escudo para mim, a minha glória e o que exalta a minha cabeça.', 'Salmo 3:3', 'Salmo', 3, 3, NULL),
  ('dependencia', 'Tudo fez formoso em seu tempo; também pôs o mundo no coração deles, sem que o homem possa descobrir a obra que Deus fez desde o princípio até ao fim.', 'Eclesiastes 3:11', 'Eclesiastes', 3, 11, NULL),
  ('dependencia', 'Das profundezas a ti clamo, ó Senhor! Senhor, escuta a minha voz! Sejam os teus ouvidos atentos à voz das minhas súplicas.', 'Salmo 130:1-2', 'Salmo', 130, 1, 2),
  ('dependencia', 'O Senhor empobrece e enriquece; abaixa e também exalta.', '1 Samuel 2:7', '1 Samuel', 2, 7, NULL),
  ('dependencia', 'A salvação vem do Senhor; sobre o teu povo seja a tua bênção. (Selá)', 'Salmo 3:8', 'Salmo', 3, 8, NULL),
  ('dependencia', 'Então, Jó se levantou, e rasgou o seu manto, e rapou a sua cabeça, e se lançou em terra, e adorou, e disse: Nu saí do ventre de minha mãe e nu tornarei para lá; o Senhor o deu e o Senhor o tomou; bendito seja o nome do Senhor.', 'Jó 1:20-21', 'Jó', 1, 20, 21),
  ('dependencia', 'O pão nosso de cada dia dá-nos hoje.', 'Mateus 6:11', 'Mateus', 6, 11, NULL),
  ('dependencia', 'A fim de que, pela vontade de Deus, chegue a vós com alegria e possa recrear-me convosco.', 'Romanos 15:32', 'Romanos', 15, 32, NULL),
  ('dependencia', 'Mas o nosso Deus está nos céus e faz tudo o que lhe apraz.', 'Salmo 115:3', 'Salmo', 115, 3, NULL),
  ('dependencia', 'Pedro, pois, era guardado na prisão; mas a igreja fazia contínua oração por ele a Deus.', 'Atos 12:5', 'Atos', 12, 5, NULL),
  ('dependencia', 'Depois, eles se fartaram em proporção do seu pasto; estando fartos, ensoberbeceu-se o seu coração; por isso, se esqueceram de mim.', 'Oseias 13:6', 'Oseias', 13, 6, NULL),
  ('dependencia', 'Porque tu acenderás a minha candeia; o Senhor, meu Deus, alumiará as minhas trevas.', 'Salmo 18:28', 'Salmo', 18, 28, NULL),
  ('dependencia', 'Porque os que são segundo a carne inclinam-se para as coisas da carne; mas os que são segundo o Espírito, para as coisas do Espírito.', 'Romanos 8:5', 'Romanos', 8, 5, NULL),
  ('dependencia', 'Estendo para ti as minhas mãos; a minha alma tem sede de ti como terra sedenta. (Selá)', 'Salmo 143:6', 'Salmo', 143, 6, NULL),
  ('dependencia', 'Mas, agora, ó Senhor, tu és o nosso Pai; nós, o barro, e tu, o nosso oleiro; e todos nós, obra das tuas mãos.', 'Isaías 64:8', 'Isaías', 64, 8, NULL),
  ('desejos', 'Digo, porém: Andai em Espírito e não cumprireis a concupiscência da carne.', 'Gálatas 5:16', 'Gálatas', 5, 16, NULL),
  ('desejos', 'Mortificai, pois, os vossos membros que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência e a avareza, que é idolatria.', 'Colossenses 3:5', 'Colossenses', 3, 5, NULL),
  ('desejos', 'Cobiçais e nada tendes; sois invejosos e cobiçosos e não podeis alcançar; combateis e guerreais e nada tendes, porque não pedis.', 'Tiago 4:2', 'Tiago', 4, 2, NULL),
  ('desejos', 'E o mundo passa, e a sua concupiscência; mas aquele que faz a vontade de Deus permanece para sempre.', '1 João 2:17', '1 João', 2, 17, NULL),
  ('desejos', 'Ou andará alguém sobre as brasas, sem que se queimem os seus pés?', 'Provérbios 6:28', 'Provérbios', 6, 28, NULL),
  ('desejos', 'Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas eu não me deixarei dominar por nenhuma.', '1 Coríntios 6:12', '1 Coríntios', 6, 12, NULL),
  ('desejos', 'Porque onde estiver o vosso tesouro, aí estará também o vosso coração.', 'Mateus 6:21', 'Mateus', 6, 21, NULL),
  ('desejos', 'Mas, por causa da prostituição, cada um tenha a sua própria mulher, e cada uma tenha o seu próprio marido.', '1 Coríntios 7:2', '1 Coríntios', 7, 2, NULL),
  ('desejos', 'Fiz concerto com os meus olhos; como, pois, os fixaria numa virgem?', 'Jó 31:1', 'Jó', 31, 1, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('desejos', 'Sede sóbrios, vigiai, porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar.', '1 Pedro 5:8', '1 Pedro', 5, 8, NULL),
  ('desejos', 'Porque tudo o que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a soberba da vida, não é do Pai, mas do mundo.', '1 João 2:16', '1 João', 2, 16, NULL),
  ('desejos', 'Porque vós, irmãos, fostes chamados à liberdade. Não useis, então, da liberdade para dar ocasião à carne, mas servi-vos uns aos outros pelo amor.', 'Gálatas 5:13', 'Gálatas', 5, 13, NULL),
  ('desejos', 'Venerado seja entre todos o matrimônio e o leito sem mácula; porém aos que se dão à prostituição e aos adúlteros Deus os julgará.', 'Hebreus 13:4', 'Hebreus', 13, 4, NULL),
  ('desejos', 'Como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus!', 'Salmo 42:1', 'Salmo', 42, 1, NULL),
  ('desejos', 'Vigiai e orai, para que não entreis em tentação; na verdade, o espírito está pronto, mas a carne é fraca.', 'Mateus 26:41', 'Mateus', 26, 41, NULL),
  ('desejos', 'Não veio sobre vós tentação, senão humana; mas fiel é Deus, que vos não deixará tentar acima do que podeis; antes, com a tentação dará também o escape, para que a possais suportar.', '1 Coríntios 10:13', '1 Coríntios', 10, 13, NULL),
  ('desejos', 'Até no caminho dos teus juízos, Senhor, te esperamos; no teu nome e na tua memória está o desejo da nossa alma.', 'Isaías 26:8', 'Isaías', 26, 8, NULL),
  ('desejos', 'Ninguém, sendo tentado, diga: De Deus sou tentado; porque Deus não pode ser tentado pelo mal e a ninguém tenta.', 'Tiago 1:13', 'Tiago', 1, 13, NULL),
  ('desejos', 'Pelas quais ele nos tem dado grandíssimas e preciosas promessas, para que por elas fiqueis participantes da natureza divina, havendo escapado da corrupção, que, pela concupiscência, há no mundo.', '2 Pedro 1:4', '2 Pedro', 1, 4, NULL),
  ('desejos', 'Porque o amor do dinheiro é a raiz de toda espécie de males; e nessa cobiça alguns se desviaram da fé e se traspassaram a si mesmos com muitas dores.', '1 Timóteo 6:10', '1 Timóteo', 6, 10, NULL),
  ('desejos', 'Todo o dia avidamente cobiça, mas o justo dá e nada retém.', 'Provérbios 21:26', 'Provérbios', 21, 26, NULL),
  ('desejos', 'Porventura, fitarás os olhos naquilo que não é nada? Porque, certamente, isso se fará asas e voará ao céu como a águia.', 'Provérbios 23:5', 'Provérbios', 23, 5, NULL),
  ('desejos', 'Portanto, os que estão na carne não podem agradar a Deus.', 'Romanos 8:8', 'Romanos', 8, 8, NULL),
  ('desejos', 'Que diremos, pois? É a lei pecado? De modo nenhum! Mas eu não conheci o pecado senão pela lei; porque eu não conheceria a concupiscência, se a lei não dissesse: Não cobiçarás.', 'Romanos 7:7', 'Romanos', 7, 7, NULL),
  ('desejos', 'Como a cidade derribada, que não tem muros, assim é o homem que não pode conter o seu espírito.', 'Provérbios 25:28', 'Provérbios', 25, 28, NULL),
  ('desejos', 'Irmãos, se algum homem chegar a ser surpreendido nalguma ofensa, vós, que sois espirituais, encaminhai o tal com espírito de mansidão, olhando por ti mesmo, para que não sejas também tentado.', 'Gálatas 6:1', 'Gálatas', 6, 1, NULL),
  ('desejos', 'E não nos induzas à tentação, mas livra-nos do mal; porque teu é o Reino, e o poder, e a glória, para sempre. Amém!', 'Mateus 6:13', 'Mateus', 6, 13, NULL),
  ('desejos', 'Onde a fazenda se multiplica, aí se multiplicam também os que a comem; que mais proveito, pois, têm os seus donos do que a verem com os seus olhos?', 'Eclesiastes 5:11', 'Eclesiastes', 5, 11, NULL),
  ('desejos', 'Também vi eu que todo trabalho e toda destreza em obras trazem ao homem a inveja do seu próximo. Também isso é vaidade e aflição de espírito.', 'Eclesiastes 4:4', 'Eclesiastes', 4, 4, NULL),
  ('desejos', 'Mas revesti-vos do Senhor Jesus Cristo e não tenhais cuidado da carne em suas concupiscências.', 'Romanos 13:14', 'Romanos', 13, 14, NULL),
  ('desejos', 'Portanto, se o teu olho direito te escandalizar, arranca-o e atira-o para longe de ti, pois te é melhor que se perca um dos teus membros do que todo o teu corpo seja lançado no inferno.', 'Mateus 5:29', 'Mateus', 5, 29, NULL),
  ('desejos', 'E nas franjas vos estará, para que o vejais, e vos lembreis de todos os mandamentos do Senhor, e os façais; e não seguireis após o vosso coração, nem após os vossos olhos, após os quais andais adulterando.', 'Números 15:39', 'Números', 15, 39, NULL),
  ('desejos', 'Ouvistes que foi dito aos antigos: Não cometerás adultério. Eu porém, vos digo que qualquer que atentar numa mulher para a cobiçar já em seu coração cometeu adultério com ela.', 'Mateus 5:27-28', 'Mateus', 5, 27, 28),
  ('desejos', 'Não matarás, não cometerás adultério, não furtarás, não dirás falso testemunho; honra teu pai e tua mãe, e amarás o teu próximo como a ti mesmo.', 'Mateus 19:18b-19', 'Mateus 19:18b-19', NULL, NULL, NULL),
  ('desejos', 'Vós tendes por pai ao diabo e quereis satisfazer os desejos de vosso pai; ele foi homicida desde o princípio e não se firmou na verdade, porque não há verdade nele; quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira.', 'João 8:44', 'João', 8, 44, NULL),
  ('desejos', 'Foge, também, dos desejos da mocidade; e segue a justiça, a fé, o amor e a paz com os que, com um coração puro, invocam o Senhor.', '2 Timóteo 2:22', '2 Timóteo', 2, 22, NULL),
  ('desejos', 'Pois mudaram a verdade de Deus em mentira e honraram e serviram mais a criatura do que o Criador, que é bendito eternamente. Amém! Pelo que Deus os abandonou às paixões infames. Porque até as suas mulheres mudaram o uso natural, no contrário à natureza. E, semelhantemente, também os varões, deixando o uso natural da mulher, se inflamaram em sua sensualidade uns para com os outros, varão com varão, cometendo torpeza e recebendo em si mesmos a recompensa que convinha ao seu erro. E, como eles se não importaram de ter conhecimento de Deus, assim Deus os entregou a um sentimento perverso, para fazerem coisas que não convém.', 'Romanos 1:25-28', 'Romanos', 1, 25, 28),
  ('desejos', 'Porque esta é a vontade de Deus, a vossa santificação: que vos abstenhais da prostituição, que cada um de vós saiba possuir o seu vaso em santificação e honra, não na paixão de concupiscência, como os gentios, que não conhecem a Deus.', '1 Tessalonicenses 4:3-5', '1 Tessalonicenses', 4, 3, 5),
  ('desejos', 'Os quais vos diziam que, no último tempo, haveria escarnecedores que andariam segundo as suas ímpias concupiscências. Estes são os que causam divisões, sensuais, que não têm o Espírito.', 'Judas 1:18-19', 'Judas', 1, 18, 19),
  ('deus', 'O Senhor, teu Deus, está no meio de ti, poderoso para te salvar; ele se deleitará em ti com alegria; calar-se-á por seu amor, regozijar-se-á em ti com júbilo.', 'Sofonias 3:17', 'Sofonias', 3, 17, NULL),
  ('deus', 'Não to mandei eu? Esforça-te e tem bom ânimo; não pasmes, nem te espantes, porque o Senhor, teu Deus, é contigo, por onde quer que andares.', 'Josué 1:9', 'Josué', 1, 9, NULL),
  ('deus', 'Porque eu, o Senhor, teu Deus, te tomo pela tua mão direita e te digo: não temas, que eu te ajudo.', 'Isaías 41:13', 'Isaías', 41, 13, NULL),
  ('deus', 'Então, dali, buscarás ao Senhor, teu Deus, e o acharás, quando o buscares de todo o teu coração e de toda a tua alma.', 'Deuteronômio 4:29', 'Deuteronômio', 4, 29, NULL),
  ('deus', 'A quem tenho eu no céu senão a ti? E na terra não há quem eu deseje além de ti.', 'Salmo 73:25', 'Salmo', 73, 25, NULL),
  ('deus', 'No dia em que eu temer, hei de confiar em ti.', 'Salmo 56:3', 'Salmo', 56, 3, NULL),
  ('deus', 'Ó Senhor, tu és o meu Deus; exaltar-te-ei e louvarei o teu nome, porque fizeste maravilhas; os teus conselhos antigos são verdade e firmeza.', 'Isaías 25:1', 'Isaías', 25, 1, NULL),
  ('deus', 'Porque tu és a minha rocha e a minha fortaleza; pelo que, por amor do teu nome, guia-me e encaminha-me.', 'Salmo 31:3', 'Salmo', 31, 3, NULL),
  ('deus', 'Posso todas as coisas naquele que me fortalece.', 'Filipenses 4:13', 'Filipenses', 4, 13, NULL),
  ('deus', 'Portanto, grandioso és, ó Senhor Jeová, porque não há semelhante a ti, e não há outro Deus, senão tu só, segundo tudo o que temos ouvido com os nossos ouvidos.', '2 Samuel 7:22', '2 Samuel', 7, 22, NULL),
  ('deus', 'Porque toda casa é edificada por alguém, mas o que edificou todas as coisas é Deus.', 'Hebreus 3:4', 'Hebreus', 3, 4, NULL),
  ('deus', 'Nós o amamos porque ele nos amou primeiro.', '1 João 4:19', '1 João', 4, 19, NULL),
  ('deus', 'Provai e vede que o Senhor é bom; bem-aventurado o homem que nele confia.', 'Salmo 34:8', 'Salmo', 34, 8, NULL),
  ('deus', 'E nós conhecemos e cremos no amor que Deus nos tem. Deus é amor e quem está em amor está em Deus, e Deus, nele.', '1 João 4:16', '1 João', 4, 16, NULL),
  ('deus', 'Levanta-te, resplandece, porque já vem a tua luz, e a glória do Senhor vai nascendo sobre ti.', 'Isaías 60:1', 'Isaías', 60, 1, NULL),
  ('deus', 'Seca-se a erva, e caem as flores, mas a palavra de nosso Deus subsiste eternamente.', 'Isaías 40:8', 'Isaías', 40, 8, NULL),
  ('deus', 'Não erreis: Deus não se deixa escarnecer; porque tudo o que o homem semear, isso também ceifará.', 'Gálatas 6:7', 'Gálatas', 6, 7, NULL),
  ('deus', 'Porque o que me achar achará a vida e alcançará favor do Senhor.', 'Provérbios 8:35', 'Provérbios', 8, 35, NULL),
  ('deus', 'Ninguém jamais viu a Deus; se nós amamos uns aos outros, Deus está em nós, e em nós é perfeito o seu amor.', '1 João 4:12', '1 João', 4, 12, NULL),
  ('deus', 'Porque os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos, os meus caminhos, diz o Senhor.', 'Isaías 55:8', 'Isaías', 55, 8, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('deus', 'Não há santo como é o Senhor; porque não há outro fora de ti; e rocha nenhuma há como o nosso Deus.', '1 Samuel 2:2', '1 Samuel', 2, 2, NULL),
  ('deus', 'A minha alma disse ao Senhor: Tu és o meu Senhor; não tenho outro bem além de ti.', 'Salmo 16:2', 'Salmo', 16, 2, NULL),
  ('deus', 'Se alguém diz: Eu amo a Deus e aborrece a seu irmão, é mentiroso. Pois quem não ama seu irmão, ao qual viu, como pode amar a Deus, a quem não viu?', '1 João 4:20', '1 João', 4, 20, NULL),
  ('deus', 'Eis que eu sou o Senhor, o Deus de toda a carne. Acaso, seria qualquer coisa maravilhosa demais para mim?', 'Jeremias 32:27', 'Jeremias', 32, 27, NULL),
  ('deus', 'Humilhai-vos perante o Senhor, e ele vos exaltará.', 'Tiago 4:10', 'Tiago', 4, 10, NULL),
  ('deus', 'No princípio, era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.', 'João 1:1', 'João', 1, 1, NULL),
  ('deus', 'Regozijai-vos, sempre, no Senhor; outra vez digo: regozijai-vos.', 'Filipenses 4:4', 'Filipenses', 4, 4, NULL),
  ('deus', 'Em Deus está a minha salvação e a minha glória; a rocha da minha fortaleza e o meu refúgio estão em Deus.', 'Salmo 62:7', 'Salmo', 62, 7, NULL),
  ('deus', 'Honra a teu pai e a tua mãe, para que se prolonguem os teus dias na terra que o Senhor, teu Deus, te dá.', 'Êxodo 20:12', 'Êxodo', 20, 12, NULL),
  ('deus', 'Eu sou o Alfa e o Ômega, o Princípio e o Fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-Poderoso.', 'Apocalipse 1:8', 'Apocalipse', 1, 8, NULL),
  ('deus', 'Assim como tu não sabes qual o caminho do vento, nem como se formam os ossos no ventre da que está grávida, assim também não sabes as obras de Deus, que faz todas as coisas.', 'Eclesiastes 11:5', 'Eclesiastes', 11, 5, NULL),
  ('deus', 'Ora, ao Rei dos séculos, imortal, invisível, ao único Deus seja honra e glória para todo o sempre. Amém!', '1 Timóteo 1:17', '1 Timóteo', 1, 17, NULL),
  ('deus', 'Saberás, pois, que o Senhor, teu Deus, é Deus, o Deus fiel, que guarda o concerto e a misericórdia até mil gerações aos que o amam e guardam os seus mandamentos.', 'Deuteronômio 7:9', 'Deuteronômio', 7, 9, NULL),
  ('deus', 'Amarás, pois, ao Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todo o teu entendimento, e de todas as tuas forças; este é o primeiro mandamento.', 'Marcos 12:30', 'Marcos', 12, 30, NULL),
  ('deus', 'O nosso socorro está em o nome do Senhor, que fez o céu e a terra.', 'Salmo 124:8', 'Salmo', 124, 8, NULL),
  ('deus', 'Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.', '1 João 5:4', '1 João', 5, 4, NULL),
  ('deus', 'Buscai ao Senhor e a sua força; buscai a sua face continuamente.', 'Salmo 105:4', 'Salmo', 105, 4, NULL),
  ('deus', 'Pelo que hoje saberás e refletirás no teu coração que só o Senhor é Deus em cima no céu e embaixo na terra; nenhum outro há.', 'Deuteronômio 4:39', 'Deuteronômio', 4, 39, NULL),
  ('deus', 'O Senhor aperfeiçoará o que me concerne; a tua benignidade, ó Senhor, é para sempre; não desampares as obras das tuas mãos.', 'Salmo 138:8', 'Salmo', 138, 8, NULL),
  ('deus', 'Porque todo aquele que invocar o nome do Senhor será salvo.', 'Romanos 10:13', 'Romanos', 10, 13, NULL),
  ('deus', 'Uma coisa pedi ao Senhor e a buscarei: que possa morar na Casa do Senhor todos os dias da minha vida, para contemplar a formosura do Senhor e aprender no seu templo.', 'Salmo 27:4', 'Salmo', 27, 4, NULL),
  ('deus', 'Aquele que não ama não conhece a Deus, porque Deus é amor.', '1 João 4:8', '1 João', 4, 8, NULL),
  ('deus', 'Porque há um só Deus e um só mediador entre Deus e os homens, Jesus Cristo, homem.', '1 Timóteo 2:5', '1 Timóteo', 2, 5, NULL),
  ('deus', 'Até isto procede do Senhor dos Exércitos, porque é maravilhoso em conselho e grande em obra.', 'Isaías 28:29', 'Isaías', 28, 29, NULL),
  ('deus', 'Se o Senhor não edificar a casa, em vão trabalham os que edificam; se o Senhor não guardar a cidade, em vão vigia a sentinela.', 'Salmo 127:1', 'Salmo', 127, 1, NULL),
  ('deus', 'E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu decreto.', 'Romanos 8:28', 'Romanos', 8, 28, NULL),
  ('deus', 'E o Senhor será rei sobre toda a terra; naquele dia, um será o Senhor, e um será o seu nome.', 'Zacarias 14:9', 'Zacarias', 14, 9, NULL),
  ('deus', 'Torre forte é o nome do Senhor; para ela correrá o justo e estará em alto retiro.', 'Provérbios 18:10', 'Provérbios', 18, 10, NULL),
  ('deus', 'Porque, quem é Deus senão o Senhor? E quem é rochedo senão o nosso Deus?', 'Salmo 18:31', 'Salmo', 18, 31, NULL),
  ('deus', 'E, estando ele ainda a falar, eis que uma nuvem luminosa os cobriu. E da nuvem saiu uma voz que dizia: Este é o meu Filho amado, em quem me comprazo; escutai-o.', 'Mateus 17:5', 'Mateus', 17, 5, NULL),
  ('deus', 'Antes que os montes nascessem, ou que tu formasses a terra e o mundo, sim, de eternidade a eternidade, tu és Deus.', 'Salmo 90:2', 'Salmo', 90, 2, NULL),
  ('deus', 'E esta é a mensagem que dele ouvimos e vos anunciamos: que Deus é luz, e não há nele treva nenhuma.', '1 João 1:5', '1 João', 1, 5, NULL),
  ('deus', 'Vós bem intentastes mal contra mim, porém Deus o tornou em bem, para fazer como se vê neste dia, para conservar em vida a um povo grande.', 'Gênesis 50:20', 'Gênesis', 50, 20, NULL),
  ('deus', 'E toda língua confesse que Jesus Cristo é o Senhor, para glória de Deus Pai.', 'Filipenses 2:11', 'Filipenses', 2, 11, NULL),
  ('deus', 'Quem operou e fez isso, chamando as gerações desde o princípio? Eu, o Senhor, o primeiro, e com os últimos, eu mesmo.', 'Isaías 41:4', 'Isaías', 41, 4, NULL),
  ('deus', 'Aquietai-vos e sabei que eu sou Deus; serei exaltado entre as nações; serei exaltado sobre a terra.', 'Salmo 46:10', 'Salmo', 46, 10, NULL),
  ('deus', 'No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder.', 'Efésios 6:10', 'Efésios', 6, 10, NULL),
  ('deus', 'Deus nos abençoará, e todas as extremidades da terra o temerão.', 'Salmo 67:7', 'Salmo', 67, 7, NULL),
  ('deus', 'Os filhos dos leões necessitam e sofrem fome, mas aqueles que buscam ao Senhor de nada têm falta.', 'Salmo 34:10', 'Salmo', 34, 10, NULL),
  ('deus', 'Eis que os olhos do Senhor estão sobre os que o temem, sobre os que esperam na sua misericórdia.', 'Salmo 33:18', 'Salmo', 33, 18, NULL),
  ('deus', 'Nisto conhecemos que estamos nele, e ele em nós, pois que nos deu do seu Espírito.', '1 João 4:13', '1 João', 4, 13, NULL),
  ('deus', 'E a vida eterna é esta: que conheçam a ti só por único Deus verdadeiro e a Jesus Cristo, a quem enviaste.', 'João 17:3', 'João', 17, 3, NULL),
  ('deus', 'Ó profundidade das riquezas, tanto da sabedoria, como da ciência de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis, os seus caminhos!', 'Romanos 11:33', 'Romanos', 11, 33, NULL),
  ('deus', 'E aquele que guarda os seus mandamentos nele está, e ele nele. E nisto conhecemos que ele está em nós: pelo Espírito que nos tem dado.', '1 João 3:24', '1 João', 3, 24, NULL),
  ('deus', 'Pelo que guardareis os meus mandamentos e os fareis. Eu sou o Senhor.', 'Levítico 22:31', 'Levítico', 22, 31, NULL),
  ('deus', 'Jesus respondeu e disse-lhes: A obra de Deus é esta: que creiais naquele que ele enviou.', 'João 6:29', 'João', 6, 29, NULL),
  ('deus', 'Como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus!', 'Salmo 42:1', 'Salmo', 42, 1, NULL),
  ('deus', 'O mesmo Espírito testifica com o nosso espírito que somos filhos de Deus.', 'Romanos 8:16', 'Romanos', 8, 16, NULL),
  ('deus', 'Que diremos, pois, a estas coisas? Se Deus é por nós, quem será contra nós?', 'Romanos 8:31', 'Romanos', 8, 31, NULL),
  ('deus', 'Deus não é homem, para que minta; nem filho de homem, para que se arrependa; porventura, diria ele e não o faria? Ou falaria e não o confirmaria?', 'Números 23:19', 'Números', 23, 19, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('deus', 'Tu, Senhor, permaneces eternamente, e o teu trono, de geração em geração.', 'Lamentações 5:19', 'Lamentações', 5, 19, NULL),
  ('deus', 'Mas em todas estas coisas somos mais do que vencedores, por aquele que nos amou.', 'Romanos 8:37', 'Romanos', 8, 37, NULL),
  ('deus', 'Mas Deus no-las revelou pelo seu Espírito; porque o Espírito penetra todas as coisas, ainda as profundezas de Deus.', '1 Coríntios 2:10', '1 Coríntios', 2, 10, NULL),
  ('deus', 'Esconder-se-ia alguém em esconderijos, de modo que eu não o veja? — diz o Senhor. Porventura, não encho eu os céus e a terra? — diz o Senhor.', 'Jeremias 23:24', 'Jeremias', 23, 24, NULL),
  ('deus', 'E criou Deus o homem à sua imagem; à imagem de Deus o criou; macho e fêmea os criou.', 'Gênesis 1:27', 'Gênesis', 1, 27, NULL),
  ('deus', 'Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo, nosso Senhor.', '1 Coríntios 1:9', '1 Coríntios', 1, 9, NULL),
  ('deus', 'Amados, se Deus assim nos amou, também nós devemos amar uns aos outros.', '1 João 4:11', '1 João', 4, 11, NULL),
  ('deus', 'Todavia, eu sou o Senhor, teu Deus, desde a terra do Egito; portanto, não reconhecerás outro deus além de mim, porque não há Salvador, senão eu.', 'Oseias 13:4', 'Oseias', 13, 4, NULL),
  ('deus', 'Ouve, Israel, o Senhor, nosso Deus, é o único Senhor. Amarás, pois, o Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todo o teu poder.', 'Deuteronômio 6:4-5', 'Deuteronômio', 6, 4, 5),
  ('deus', 'Bem-aventurada é a nação cujo Deus é o Senhor, e o povo que ele escolheu para a sua herança.', 'Salmo 33:12', 'Salmo', 33, 12, NULL),
  ('deus', 'Assim, eu me engrandecerei, e me santificarei, e me farei conhecer aos olhos de muitas nações; e saberão que eu sou o Senhor.', 'Ezequiel 38:23', 'Ezequiel', 38, 23, NULL),
  ('deus', 'Mas, amados, não ignoreis uma coisa: que um dia para o Senhor é como mil anos, e mil anos, como um dia.', '2 Pedro 3:8', '2 Pedro', 3, 8, NULL),
  ('deus', 'A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com vós todos. Amém!', '2 Coríntios 13:13', '2 Coríntios', 13, 13, NULL),
  ('deus', 'Toda alma esteja sujeita às autoridades superiores; porque não há autoridade que não venha de Deus; e as autoridades que há foram ordenadas por Deus.', 'Romanos 13:1', 'Romanos', 13, 1, NULL),
  ('deus', 'Do Senhor é a terra e a sua plenitude, o mundo e aqueles que nele habitam.', 'Salmo 24:1', 'Salmo', 24, 1, NULL),
  ('deus', 'E disse Deus: Façamos o homem à nossa imagem, conforme a nossa semelhança; e domine sobre os peixes do mar, e sobre as aves dos céus, e sobre o gado, e sobre toda a terra, e sobre todo réptil que se move sobre a terra.', 'Gênesis 1:26', 'Gênesis', 1, 26, NULL),
  ('deus', 'Porque, quem é Deus, senão o Senhor? E quem é rochedo, senão o nosso Deus?', '2 Samuel 22:32', '2 Samuel', 22, 32, NULL),
  ('deus', 'Em ti me alegrarei e saltarei de prazer; cantarei louvores ao teu nome, ó Altíssimo.', 'Salmo 9:2', 'Salmo', 9, 2, NULL),
  ('deus', 'Mas o nosso Deus está nos céus e faz tudo o que lhe apraz.', 'Salmo 115:3', 'Salmo', 115, 3, NULL),
  ('deus', 'Ele revela o profundo e o escondido e conhece o que está em trevas; e com ele mora a luz.', 'Daniel 2:22', 'Daniel', 2, 22, NULL),
  ('deus', 'Adúlteros e adúlteras, não sabeis vós que a amizade do mundo é inimizade contra Deus? Portanto, qualquer que quiser ser amigo do mundo constitui-se inimigo de Deus.', 'Tiago 4:4', 'Tiago', 4, 4, NULL),
  ('deus', 'Ao Todo-Poderoso não podemos alcançar; grande é em poder; porém a ninguém oprime em juízo e grandeza de justiça.', 'Jó 37:23', 'Jó', 37, 23, NULL),
  ('deus', 'Porque mil anos são aos teus olhos como o dia de ontem que passou, e como a vigília da noite.', 'Salmo 90:4', 'Salmo', 90, 4, NULL),
  ('deus', 'Ele é o que edifica as suas câmaras no céu, e a sua abóbada fundou na terra, e o que chama as águas do mar, e as derrama sobre a terra; o Senhor é o seu nome.', 'Amós 9:6', 'Amós', 9, 6, NULL),
  ('deus', 'E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles e será o seu Deus. E Deus limpará de seus olhos toda lágrima, e não haverá mais morte, nem pranto, nem clamor, nem dor, porque já as primeiras coisas são passadas.', 'Apocalipse 21:3-4', 'Apocalipse', 21, 3, 4),
  ('deus', 'E eu santificarei o meu grande nome, que foi profanado entre as nações, o qual profanastes no meio delas; e as nações saberão que eu sou o Senhor, diz o Senhor Jeová, quando eu for santificado aos seus olhos.', 'Ezequiel 36:23', 'Ezequiel', 36, 23, NULL),
  ('deus', 'E eis que uma voz dos céus dizia: Este é o meu Filho amado, em quem me comprazo.', 'Mateus 3:17', 'Mateus', 3, 17, NULL),
  ('deus', 'Tu crês que há um só Deus? Fazes bem; também os demônios o creem e estremecem.', 'Tiago 2:19', 'Tiago', 2, 19, NULL),
  ('deus', 'Esta é a palavra do Senhor a Zorobabel, dizendo: Não por força, nem por violência, mas pelo meu Espírito, diz o Senhor dos Exércitos.', 'Zacarias 4:6', 'Zacarias', 4, 6, NULL),
  ('deus', 'E que amá-lo de todo o coração, e de todo o entendimento, e de toda a alma, e de todas as forças e amar o próximo como a si mesmo é mais do que todos os holocaustos e sacrifícios.', 'Marcos 12:33', 'Marcos', 12, 33, NULL),
  ('deus', 'Mas tu, Senhor, és um Deus cheio de compaixão, e piedoso, e sofredor, e grande em benignidade e em verdade.', 'Salmo 86:15', 'Salmo', 86, 15, NULL),
  ('diabo', 'Sede sóbrios, vigiai, porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar.', '1 Pedro 5:8', '1 Pedro', 5, 8, NULL),
  ('diabo', 'Porque não temos que lutar contra carne e sangue, mas, sim, contra os principados, contra as potestades, contra os príncipes das trevas deste século, contra as hostes espirituais da maldade, nos lugares celestiais.', 'Efésios 6:12', 'Efésios', 6, 12, NULL),
  ('diabo', 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo.', 'Efésios 6:11', 'Efésios', 6, 11, NULL),
  ('diabo', 'Mas fiel é o Senhor, que vos confortará e guardará do maligno.', '2 Tessalonicenses 3:3', '2 Tessalonicenses', 3, 3, NULL),
  ('diabo', 'Sujeitai-vos, pois, a Deus; resisti ao diabo, e ele fugirá de vós.', 'Tiago 4:7', 'Tiago', 4, 7, NULL),
  ('diabo', 'Quem pratica o pecado é do diabo, porque o diabo vive pecando desde o princípio. Para isto o Filho de Deus se manifestou: para desfazer as obras do diabo.', '1 João 3:8', '1 João', 3, 8, NULL),
  ('diabo', 'Irai-vos e não pequeis; não se ponha o sol sobre a vossa ira. Não deis lugar ao diabo.', 'Efésios 4:26-27', 'Efésios', 4, 26, 27),
  ('diabo', 'Vós tendes por pai ao diabo e quereis satisfazer os desejos de vosso pai; ele foi homicida desde o princípio e não se firmou na verdade, porque não há verdade nele; quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira.', 'João 8:44', 'João', 8, 44, NULL),
  ('diabo', 'E o Deus de paz esmagará em breve Satanás debaixo dos vossos pés. A graça de nosso Senhor Jesus Cristo seja convosco. Amém!', 'Romanos 16:20', 'Romanos', 16, 20, NULL),
  ('diabo', 'Ordena os meus passos na tua palavra, e não se apodere de mim iniquidade alguma.', 'Salmo 119:133', 'Salmo', 119, 133, NULL),
  ('diabo', 'E disse o Senhor a Satanás: Eis que tudo quanto tem está na tua mão; somente contra ele não estendas a tua mão. E Satanás saiu da presença do Senhor.', 'Jó 1:12', 'Jó', 1, 12, NULL),
  ('diabo', 'Não veio sobre vós tentação, senão humana; mas fiel é Deus, que vos não deixará tentar acima do que podeis; antes, com a tentação dará também o escape, para que a possais suportar.', '1 Coríntios 10:13', '1 Coríntios', 10, 13, NULL),
  ('diabo', 'Portanto, tomai toda a armadura de Deus, para que possais resistir no dia mau e, havendo feito tudo, ficar firmes.', 'Efésios 6:13', 'Efésios', 6, 13, NULL),
  ('diabo', 'Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor, em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados.', 'Colossenses 1:13-14', 'Colossenses', 1, 13, 14),
  ('diabo', 'E não nos induzas à tentação, mas livra-nos do mal; porque teu é o Reino, e o poder, e a glória, para sempre. Amém!', 'Mateus 6:13', 'Mateus', 6, 13, NULL),
  ('diabo', 'Disse, então, Pedro: Ananias, por que encheu Satanás o teu coração, para que mentisses ao Espírito Santo e retivesses parte do preço da herdade? Guardando-a, não ficava para ti? E, vendida, não estava em teu poder? Por que formaste este desígnio em teu coração? Não mentiste aos homens, mas a Deus.', 'Atos 5:3-4', 'Atos', 5, 3, 4),
  ('diabo', 'Não peço que os tires do mundo, mas que os livres do mal.', 'João 17:15', 'João', 17, 15, NULL),
  ('diabo', 'Tu crês que há um só Deus? Fazes bem; também os demônios o creem e estremecem.', 'Tiago 2:19', 'Tiago', 2, 19, NULL),
  ('diabo', 'E Jesus, cheio do Espírito Santo, voltou do Jordão e foi levado pelo Espírito ao deserto. E quarenta dias foi tentado pelo diabo, e, naqueles dias, não comeu coisa alguma, e, terminados eles, teve fome.', 'Lucas 4:1-2', 'Lucas', 4, 1, 2);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('diabo', 'Não vos defraudeis um ao outro, senão por consentimento mútuo, por algum tempo, para vos aplicardes à oração; e, depois, ajuntai-vos outra vez, para que Satanás vos não tente pela vossa incontinência.', '1 Coríntios 7:5', '1 Coríntios', 7, 5, NULL),
  ('dinheiro', 'Sejam vossos costumes sem avareza, contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei.', 'Hebreus 13:5', 'Hebreus', 13, 5, NULL),
  ('dinheiro', 'A fazenda que procede da vaidade diminuirá, mas quem a ajunta pelo trabalho terá aumento.', 'Provérbios 13:11', 'Provérbios', 13, 11, NULL),
  ('dinheiro', 'Mas os que querem ser ricos caem em tentação, e em laço, e em muitas concupiscências loucas e nocivas, que submergem os homens na perdição e ruína.', '1 Timóteo 6:9', '1 Timóteo', 6, 9, NULL),
  ('dinheiro', 'A bênção do Senhor é que enriquece, e ele não acrescenta dores.', 'Provérbios 10:22', 'Provérbios', 10, 22, NULL),
  ('dinheiro', 'Não te canses para enriqueceres; dá de mão à tua própria sabedoria.', 'Provérbios 23:4', 'Provérbios', 23, 4, NULL),
  ('dinheiro', 'O que amar o dinheiro nunca se fartará de dinheiro; e quem amar a abundância nunca se fartará da renda; também isso é vaidade.', 'Eclesiastes 5:10', 'Eclesiastes', 5, 10, NULL),
  ('dinheiro', 'Honra ao Senhor com a tua fazenda e com as primícias de toda a tua renda.', 'Provérbios 3:9', 'Provérbios', 3, 9, NULL),
  ('dinheiro', 'Melhor é o pouco com o temor do Senhor do que um grande tesouro onde há inquietação.', 'Provérbios 15:16', 'Provérbios', 15, 16, NULL),
  ('dinheiro', 'Porque onde estiver o vosso tesouro, aí estará também o vosso coração.', 'Mateus 6:21', 'Mateus', 6, 21, NULL),
  ('dinheiro', 'E disse-lhes: Acautelai-vos e guardai-vos da avareza, porque a vida de qualquer não consiste na abundância do que possui.', 'Lucas 12:15', 'Lucas', 12, 15, NULL),
  ('dinheiro', 'Portanto, dai a cada um o que deveis: a quem tributo, tributo; a quem imposto, imposto; a quem temor, temor; a quem honra, honra.', 'Romanos 13:7', 'Romanos', 13, 7, NULL),
  ('dinheiro', 'Quanto melhor é adquirir a sabedoria do que o ouro! E quanto mais excelente, adquirir a prudência do que a prata!', 'Provérbios 16:16', 'Provérbios', 16, 16, NULL),
  ('dinheiro', 'Porque quem sou eu, e quem é o meu povo, que tivéssemos poder para tão voluntariamente dar semelhantes coisas? Porque tudo vem de ti, e da tua mão to damos.', '1 Crônicas 29:14', '1 Crônicas', 29, 14, NULL),
  ('dinheiro', 'Manda aos ricos deste mundo que não sejam altivos, nem ponham a esperança na incerteza das riquezas, mas em Deus, que abundantemente nos dá todas as coisas para delas gozarmos.', '1 Timóteo 6:17', '1 Timóteo', 6, 17, NULL),
  ('dinheiro', 'Porque o amor do dinheiro é a raiz de toda espécie de males; e nessa cobiça alguns se desviaram da fé e se traspassaram a si mesmos com muitas dores.', '1 Timóteo 6:10', '1 Timóteo', 6, 10, NULL),
  ('dinheiro', 'E o seu senhor lhe disse: Bem está, servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor.', 'Mateus 25:21', 'Mateus', 25, 21, NULL),
  ('dinheiro', 'Afasta de mim a vaidade e a palavra mentirosa; não me dês nem a pobreza nem a riqueza; mantém-me do pão da minha porção acostumada.', 'Provérbios 30:8', 'Provérbios', 30, 8, NULL),
  ('dinheiro', 'O desejo do homem é a sua beneficência; mas o pobre é melhor do que o mentiroso.', 'Provérbios 19:22', 'Provérbios', 19, 22, NULL),
  ('dinheiro', 'Vale mais o pouco que tem o justo do que as riquezas de muitos ímpios. Pois os braços dos ímpios se quebrarão, mas o Senhor sustém os justos.', 'Salmo 37:16-17', 'Salmo', 37, 16, 17),
  ('dinheiro', 'Porque o Senhor, teu Deus, te abençoará, como te tem dito; assim, emprestarás a muitas nações, mas não tomarás empréstimos; e dominarás sobre muitas nações, mas elas não dominarão sobre ti.', 'Deuteronômio 15:6', 'Deuteronômio', 15, 6, NULL),
  ('dinheiro', 'Mais digno de ser escolhido é o bom nome do que as muitas riquezas; e a graça é melhor do que a riqueza e o ouro.', 'Provérbios 22:1', 'Provérbios', 22, 1, NULL),
  ('dinheiro', 'Porventura, fitarás os olhos naquilo que não é nada? Porque, certamente, isso se fará asas e voará ao céu como a águia.', 'Provérbios 23:5', 'Provérbios', 23, 5, NULL),
  ('dinheiro', 'E quanto ao homem, a quem Deus deu riquezas e fazenda e lhe deu poder para delas comer, e tomar a sua porção, e gozar do seu trabalho, isso é dom de Deus.', 'Eclesiastes 5:19', 'Eclesiastes', 5, 19, NULL),
  ('dinheiro', 'Por esta razão também pagais tributos, porque são ministros de Deus, atendendo sempre a isto mesmo.', 'Romanos 13:6', 'Romanos', 13, 6, NULL),
  ('dinheiro', 'Pois qual de vós, querendo edificar uma torre, não se assenta primeiro a fazer as contas dos gastos, para ver se tem com que a acabar?', 'Lucas 14:28', 'Lucas', 14, 28, NULL),
  ('dinheiro', 'A fazenda do rico é sua cidade forte e, como um muro alto, na sua imaginação.', 'Provérbios 18:11', 'Provérbios', 18, 11, NULL),
  ('dinheiro', 'Sei estar abatido e sei também ter abundância; em toda a maneira e em todas as coisas, estou instruído, tanto a ter fartura como a ter fome, tanto a ter abundância como a padecer necessidade.', 'Filipenses 4:12', 'Filipenses', 4, 12, NULL),
  ('dinheiro', 'Não aproveitam as riquezas no dia da ira, mas a justiça livra da morte.', 'Provérbios 11:4', 'Provérbios', 11, 4, NULL),
  ('dinheiro', 'Os tesouros da impiedade de nada aproveitam; mas a justiça livra da morte.', 'Provérbios 10:2', 'Provérbios', 10, 2, NULL),
  ('dinheiro', 'Folgo mais com o caminho dos teus testemunhos do que com todas as riquezas.', 'Salmo 119:14', 'Salmo', 119, 14, NULL),
  ('dinheiro', 'Ninguém pode servir a dois senhores, porque ou há de odiar um e amar o outro ou se dedicará a um e desprezará o outro. Não podeis servir a Deus e a Mamom.', 'Mateus 6:24', 'Mateus', 6, 24, NULL),
  ('dinheiro', 'E riquezas e glória vêm de diante de ti, e tu dominas sobre tudo, e na tua mão há força e poder; e na tua mão está o engrandecer e dar força a tudo.', '1 Crônicas 29:12', '1 Crônicas', 29, 12, NULL),
  ('dinheiro', 'Quem, pois, tiver bens do mundo e, vendo o seu irmão necessitado, lhe cerrar o seu coração, como estará nele o amor de Deus?', '1 João 3:17', '1 João', 3, 17, NULL),
  ('dinheiro', 'A casa e a fazenda são a herança dos pais; mas do Senhor vem a mulher prudente.', 'Provérbios 19:14', 'Provérbios', 19, 14, NULL),
  ('dinheiro', 'O Senhor empobrece e enriquece; abaixa e também exalta.', '1 Samuel 2:7', '1 Samuel', 2, 7, NULL),
  ('dinheiro', 'Como contristados, mas sempre alegres; como pobres, mas enriquecendo a muitos; como nada tendo e possuindo tudo.', '2 Coríntios 6:10', '2 Coríntios', 6, 10, NULL),
  ('dinheiro', 'Melhor é o pouco com justiça do que a abundância de colheita com injustiça.', 'Provérbios 16:8', 'Provérbios', 16, 8, NULL),
  ('dinheiro', 'E o Senhor virou o cativeiro de Jó, quando orava pelos seus amigos; e o Senhor acrescentou a Jó outro tanto em dobro a tudo quanto dantes possuía.', 'Jó 42:10', 'Jó', 42, 10, NULL),
  ('dinheiro', 'Onde a fazenda se multiplica, aí se multiplicam também os que a comem; que mais proveito, pois, têm os seus donos do que a verem com os seus olhos?', 'Eclesiastes 5:11', 'Eclesiastes', 5, 11, NULL),
  ('dinheiro', 'O ímpio toma emprestado e não paga; mas o justo se compadece e dá.', 'Salmo 37:21', 'Salmo', 37, 21, NULL),
  ('dinheiro', 'O rico domina sobre os pobres, e o que toma emprestado é servo do que empresta.', 'Provérbios 22:7', 'Provérbios', 22, 7, NULL),
  ('dinheiro', 'Disse, então, Pedro: Ananias, por que encheu Satanás o teu coração, para que mentisses ao Espírito Santo e retivesses parte do preço da herdade? Guardando-a, não ficava para ti? E, vendida, não estava em teu poder? Por que formaste este desígnio em teu coração? Não mentiste aos homens, mas a Deus.', 'Atos 5:3-4', 'Atos', 5, 3, 4),
  ('dinheiro', 'E o que foi semeado entre espinhos é o que ouve a palavra, mas os cuidados deste mundo e a sedução das riquezas sufocam a palavra, e fica infrutífera.', 'Mateus 13:22', 'Mateus', 13, 22, NULL),
  ('dinheiro', 'Não fareis outros deuses comigo; deuses de prata ou deuses de ouro não fareis para vós.', 'Êxodo 20:23', 'Êxodo', 20, 23, NULL),
  ('dinheiro', 'O resgate da vida de cada um são as suas riquezas, mas o pobre não ouve as ameaças.', 'Provérbios 13:8', 'Provérbios', 13, 8, NULL),
  ('dinheiro', 'Mas glorie-se o irmão abatido na sua exaltação, e o rico, em seu abatimento, porque ele passará como a flor da erva.', 'Tiago 1:9-10', 'Tiago', 1, 9, 10),
  ('dividas', 'O ímpio toma emprestado e não paga; mas o justo se compadece e dá.', 'Salmo 37:21', 'Salmo', 37, 21, NULL),
  ('dividas', 'A ninguém devais coisa alguma, a não ser o amor com que vos ameis uns aos outros; porque quem ama aos outros cumpriu a lei.', 'Romanos 13:8', 'Romanos', 13, 8, NULL),
  ('dividas', 'Portanto, dai a cada um o que deveis: a quem tributo, tributo; a quem imposto, imposto; a quem temor, temor; a quem honra, honra.', 'Romanos 13:7', 'Romanos', 13, 7, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('dividas', 'O rico domina sobre os pobres, e o que toma emprestado é servo do que empresta.', 'Provérbios 22:7', 'Provérbios', 22, 7, NULL),
  ('dividas', 'E dá a qualquer que te pedir; e ao que tomar o que é teu, não lho tornes a pedir.', 'Lucas 6:30', 'Lucas', 6, 30, NULL),
  ('dividas', 'Porque o Senhor, teu Deus, te abençoará, como te tem dito; assim, emprestarás a muitas nações, mas não tomarás empréstimos; e dominarás sobre muitas nações, mas elas não dominarão sobre ti.', 'Deuteronômio 15:6', 'Deuteronômio', 15, 6, NULL),
  ('dividas', 'Pois qual de vós, querendo edificar uma torre, não se assenta primeiro a fazer as contas dos gastos, para ver se tem com que a acabar?', 'Lucas 14:28', 'Lucas', 14, 28, NULL),
  ('dividas', 'A fazenda que procede da vaidade diminuirá, mas quem a ajunta pelo trabalho terá aumento.', 'Provérbios 13:11', 'Provérbios', 13, 11, NULL),
  ('dividas', 'Perdoa-nos as nossas dívidas, assim como nós perdoamos aos nossos devedores.', 'Mateus 6:12', 'Mateus', 6, 12, NULL),
  ('dividas', 'Não detenhas dos seus donos o bem, estando na tua mão poder fazê-lo.', 'Provérbios 3:27', 'Provérbios', 3, 27, NULL),
  ('dividas', 'Sejam vossos costumes sem avareza, contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei.', 'Hebreus 13:5', 'Hebreus', 13, 5, NULL),
  ('dividas', 'Ninguém pode servir a dois senhores, porque ou há de odiar um e amar o outro ou se dedicará a um e desprezará o outro. Não podeis servir a Deus e a Mamom.', 'Mateus 6:24', 'Mateus', 6, 24, NULL),
  ('doenca', 'Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor; e a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados.', 'Tiago 5:14-15', 'Tiago', 5, 14, 15),
  ('doenca', 'E servireis ao Senhor, vosso Deus, e ele abençoará o vosso pão e a vossa água; e eu tirarei do meio de ti as enfermidades.', 'Êxodo 23:25', 'Êxodo', 23, 25, NULL),
  ('doenca', 'Amado, desejo que te vá bem em todas as coisas e que tenhas saúde, assim como bem vai a tua alma.', '3 João 1:2', '3 João', 1, 2, NULL),
  ('doenca', 'Sara os quebrantados de coração e liga-lhes as feridas.', 'Salmo 147:3', 'Salmo', 147, 3, NULL),
  ('doenca', 'Verdadeiramente, ele tomou sobre si as nossas enfermidades e as nossas dores levou sobre si; e nós o reputamos por aflito, ferido de Deus e oprimido.', 'Isaías 53:4', 'Isaías', 53, 4, NULL),
  ('doenca', 'O coração alegre serve de bom remédio, mas o espírito abatido virá a secar os ossos.', 'Provérbios 17:22', 'Provérbios', 17, 22, NULL),
  ('doenca', 'Sara-me, Senhor, e sararei; salva-me, e serei salvo; porque tu és o meu louvor.', 'Jeremias 17:14', 'Jeremias', 17, 14, NULL),
  ('doenca', 'Se ouvires atento a voz do Senhor, teu Deus, e fizeres o que é reto diante de seus olhos, e inclinares os teus ouvidos aos seus mandamentos, e guardares todos os seus estatutos, nenhuma das enfermidades porei sobre ti, que pus sobre o Egito; porque eu sou o Senhor, que te sara.', 'Êxodo 15:26', 'Êxodo', 15, 26, NULL),
  ('doenca', 'Curai os enfermos, limpai os leprosos, ressuscitai os mortos, expulsai os demônios; de graça recebestes, de graça dai.', 'Mateus 10:8', 'Mateus', 10, 8, NULL),
  ('doenca', 'Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis; a oração feita por um justo pode muito em seus efeitos.', 'Tiago 5:16', 'Tiago', 5, 16, NULL),
  ('doenca', 'E curai os enfermos que nela houver e dizei-lhes: É chegado a vós o Reino de Deus.', 'Lucas 10:9', 'Lucas', 10, 9, NULL),
  ('doenca', 'A esperança demorada enfraquece o coração, mas o desejo chegado é árvore de vida.', 'Provérbios 13:12', 'Provérbios', 13, 12, NULL),
  ('doenca', 'O Senhor abre os olhos aos cegos; o Senhor levanta os abatidos; o Senhor ama os justos.', 'Salmo 146:8', 'Salmo', 146, 8, NULL),
  ('doenca', 'Enquanto eu me calei, envelheceram os meus ossos pelo meu bramido em todo o dia.', 'Salmo 32:3', 'Salmo', 32, 3, NULL),
  ('doenca', 'Era desprezado e o mais indigno entre os homens, homem de dores, experimentado nos trabalhos e, como um de quem os homens escondiam o rosto, era desprezado, e não fizemos dele caso algum.', 'Isaías 53:3', 'Isaías', 53, 3, NULL),
  ('doenca', 'E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles e será o seu Deus. E Deus limpará de seus olhos toda lágrima, e não haverá mais morte, nem pranto, nem clamor, nem dor, porque já as primeiras coisas são passadas.', 'Apocalipse 21:3-4', 'Apocalipse', 21, 3, 4),
  ('doenca', 'E percorria Jesus toda a Galileia, ensinando nas suas sinagogas, e pregando o evangelho do Reino, e curando todas as enfermidades e moléstias entre o povo.', 'Mateus 4:23', 'Mateus', 4, 23, NULL),
  ('egoismo', 'Nada façais por contenda ou por vanglória, mas por humildade; cada um considere os outros superiores a si mesmo.', 'Filipenses 2:3', 'Filipenses', 2, 3, NULL),
  ('egoismo', 'Ninguém busque o proveito próprio; antes, cada um, o que é de outrem.', '1 Coríntios 10:24', '1 Coríntios', 10, 24, NULL),
  ('egoismo', 'O amor é sofredor, é benigno; o amor não é invejoso; o amor não trata com leviandade, não se ensoberbece, não se porta com indecência, não busca os seus interesses, não se irrita, não suspeita mal.', '1 Coríntios 13:4-5', '1 Coríntios', 13, 4, 5),
  ('egoismo', 'Porque, onde há inveja e espírito faccioso, aí há perturbação e toda obra perversa.', 'Tiago 3:16', 'Tiago', 3, 16, NULL),
  ('egoismo', 'A alma generosa engordará, e o que regar também será regado.', 'Provérbios 11:25', 'Provérbios', 11, 25, NULL),
  ('egoismo', 'Não toma prazer o tolo no entendimento, senão em que se descubra o seu coração.', 'Provérbios 18:2', 'Provérbios', 18, 2, NULL),
  ('egoismo', 'Portanto, cada um de nós agrade ao seu próximo no que é bom para edificação.', 'Romanos 15:2', 'Romanos', 15, 2, NULL),
  ('egoismo', 'E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo. Não há outro mandamento maior do que estes.', 'Marcos 12:31', 'Marcos', 12, 31, NULL),
  ('egoismo', 'Ninguém se engane a si mesmo: se alguém dentre vós se tem por sábio neste mundo, faça-se louco para ser sábio.', '1 Coríntios 3:18', '1 Coríntios', 3, 18, NULL),
  ('egoismo', 'Inclina o meu coração a teus testemunhos e não à cobiça.', 'Salmo 119:36', 'Salmo', 119, 36, NULL),
  ('egoismo', 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne vivo-a na fé do Filho de Deus, o qual me amou e se entregou a si mesmo por mim.', 'Gálatas 2:20', 'Gálatas', 2, 20, NULL),
  ('egoismo', 'Mas em nada tenho a minha vida por preciosa, contanto que cumpra com alegria a minha carreira e o ministério que recebi do Senhor Jesus, para dar testemunho do evangelho da graça de Deus.', 'Atos 20:24', 'Atos', 20, 24, NULL),
  ('egoismo', 'E, chamando a si a multidão, com os seus discípulos, disse-lhes: Se alguém quiser vir após mim, negue-se a si mesmo, e tome a sua cruz, e siga-me.', 'Marcos 8:34', 'Marcos', 8, 34, NULL),
  ('encorajamento', 'O Senhor, pois, é aquele que vai adiante de ti; ele será contigo, não te deixará, nem te desamparará; não temas, nem te espantes.', 'Deuteronômio 31:8', 'Deuteronômio', 31, 8, NULL),
  ('encorajamento', 'Mas os que esperam no Senhor renovarão as suas forças e subirão com asas como águias; correrão e não se cansarão; caminharão e não se fatigarão.', 'Isaías 40:31', 'Isaías', 40, 31, NULL),
  ('encorajamento', 'Pelo que exortai-vos uns aos outros e edificai-vos uns aos outros, como também o fazeis.', '1 Tessalonicenses 5:11', '1 Tessalonicenses', 5, 11, NULL),
  ('encorajamento', 'Quando passares pelas águas, estarei contigo, e, quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti.', 'Isaías 43:2', 'Isaías', 43, 2, NULL),
  ('encorajamento', 'Não to mandei eu? Esforça-te e tem bom ânimo; não pasmes, nem te espantes, porque o Senhor, teu Deus, é contigo, por onde quer que andares.', 'Josué 1:9', 'Josué', 1, 9, NULL),
  ('encorajamento', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda consolação, que nos consola em toda a nossa tribulação, para que também possamos consolar os que estiverem em alguma tribulação, com a consolação com que nós mesmos somos consolados de Deus.', '2 Coríntios 1:3-4', '2 Coríntios', 1, 3, 4),
  ('encorajamento', 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.', 'Mateus 11:28', 'Mateus', 11, 28, NULL),
  ('encorajamento', 'Elevo os olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor, que fez o céu e a terra.', 'Salmo 121:1-2', 'Salmo', 121, 1, 2),
  ('encorajamento', 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.', '1 Coríntios 15:58', '1 Coríntios', 15, 58, NULL),
  ('encorajamento', 'Instruir-te-ei e ensinar-te-ei o caminho que deves seguir; guiar-te-ei com os meus olhos.', 'Salmo 32:8', 'Salmo', 32, 8, NULL),
  ('encorajamento', 'Esforçai-vos, e ele fortalecerá o vosso coração, vós todos os que esperais no Senhor.', 'Salmo 31:24', 'Salmo', 31, 24, NULL);

