-- Parte 05: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('encorajamento', 'E consideremo-nos uns aos outros, para nos estimularmos ao amor e às boas obras, não deixando a nossa congregação, como é costume de alguns; antes, admoestando-nos uns aos outros; e tanto mais quanto vedes que se vai aproximando aquele Dia.', 'Hebreus 10:24-25', 'Hebreus', 10, 24, 25),
  ('encorajamento', 'Vigiai, estai firmes na fé, portai-vos varonilmente e fortalecei-vos.', '1 Coríntios 16:13', '1 Coríntios', 16, 13, NULL),
  ('encorajamento', 'Tenho-vos dito isso, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo; eu venci o mundo.', 'João 16:33', 'João', 16, 33, NULL),
  ('encorajamento', 'Em todo trabalho há proveito, mas a palavra dos lábios só encaminha para a pobreza.', 'Provérbios 14:23', 'Provérbios', 14, 23, NULL),
  ('encorajamento', 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.', 'João 14:27', 'João', 14, 27, NULL),
  ('encorajamento', 'Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo; a tua vara e o teu cajado me consolam.', 'Salmo 23:4', 'Salmo', 23, 4, NULL),
  ('encorajamento', 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente.', '2 Coríntios 4:17', '2 Coríntios', 4, 17, NULL),
  ('encorajamento', 'Enquanto foste precioso aos meus olhos, também foste glorificado, e eu te amei, pelo que dei os homens por ti, e os povos, pela tua alma.', 'Isaías 43:4', 'Isaías', 43, 4, NULL),
  ('encorajamento', 'Que diremos, pois, a estas coisas? Se Deus é por nós, quem será contra nós?', 'Romanos 8:31', 'Romanos', 8, 31, NULL),
  ('encorajamento', 'Ora, o Deus de paciência e consolação vos conceda o mesmo sentimento uns para com os outros, segundo Cristo Jesus.', 'Romanos 15:5', 'Romanos', 15, 5, NULL),
  ('encorajamento', 'E seja sobre nós a graça do Senhor, nosso Deus; e confirma sobre nós a obra das nossas mãos; sim, confirma a obra das nossas mãos.', 'Salmo 90:17', 'Salmo', 90, 17, NULL),
  ('encorajamento', 'Por isso, não desfalecemos; mas, ainda que o nosso homem exterior se corrompa, o interior, contudo, se renova de dia em dia.', '2 Coríntios 4:16', '2 Coríntios', 4, 16, NULL),
  ('encorajamento', 'Não se vendem cinco passarinhos por dois ceitis? E nenhum deles está esquecido diante de Deus. E até os cabelos da vossa cabeça estão todos contados. Não temais, pois; mais valeis vós do que muitos passarinhos.', 'Lucas 12:6-7', 'Lucas', 12, 6, 7),
  ('encorajamento', 'Portanto, cada um de nós agrade ao seu próximo no que é bom para edificação.', 'Romanos 15:2', 'Romanos', 15, 2, NULL),
  ('encorajamento', 'Porque, se há prontidão de vontade, será aceita segundo o que qualquer tem e não segundo o que não tem.', '2 Coríntios 8:12', '2 Coríntios', 8, 12, NULL),
  ('encorajamento', 'Para que os seus corações sejam consolados, e estejam unidos em amor e enriquecidos da plenitude da inteligência, para conhecimento do mistério de Deus — Cristo.', 'Colossenses 2:2', 'Colossenses', 2, 2, NULL),
  ('encorajamento', 'Nunca mais terão fome, nunca mais terão sede; nem sol nem calma alguma cairá sobre eles, porque o Cordeiro que está no meio do trono os apascentará e lhes servirá de guia para as fontes das águas da vida; e Deus limpará de seus olhos toda lágrima.', 'Apocalipse 7:16-17', 'Apocalipse', 7, 16, 17),
  ('encorajamento', 'Eu, eu sou aquele que vos consola; quem pois és tu, para que temas o homem, que é mortal, ou o filho do homem, que se tornará em feno?', 'Isaías 51:12', 'Isaías', 51, 12, NULL),
  ('encorajamento', 'Porque, como as aflições de Cristo são abundantes em nós, assim também a nossa consolação sobeja por meio de Cristo.', '2 Coríntios 1:5', '2 Coríntios', 1, 5, NULL),
  ('encorajamento', 'Porque desejo ver-vos, para vos comunicar algum dom espiritual, a fim de que sejais confortados, isto é, para que juntamente convosco eu seja consolado pela fé mútua, tanto vossa como minha.', 'Romanos 1:11-12', 'Romanos', 1, 11, 12),
  ('encorajamento', 'Porque tudo que dantes foi escrito para nosso ensino foi escrito, para que, pela paciência e consolação das Escrituras, tenhamos esperança.', 'Romanos 15:4', 'Romanos', 15, 4, NULL),
  ('equipamentos', 'E consideremo-nos uns aos outros, para nos estimularmos ao amor e às boas obras, não deixando a nossa congregação, como é costume de alguns; antes, admoestando-nos uns aos outros; e tanto mais quanto vedes que se vai aproximando aquele Dia.', 'Hebreus 10:24-25', 'Hebreus', 10, 24, 25),
  ('equipamentos', 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo.', 'Efésios 6:11', 'Efésios', 6, 11, NULL),
  ('equipamentos', 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te esforço, e te ajudo, e te sustento com a destra da minha justiça.', 'Isaías 41:10', 'Isaías', 41, 10, NULL),
  ('equipamentos', 'Toda Escritura divinamente inspirada é proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça, para que o homem de Deus seja perfeito e perfeitamente instruído para toda boa obra.', '2 Timóteo 3:16-17', '2 Timóteo', 3, 16, 17),
  ('equipamentos', 'Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.', 'Provérbios 3:5-6', 'Provérbios', 3, 5, 6),
  ('equipamentos', 'Tenho posto o Senhor continuamente diante de mim; por isso que ele está à minha mão direita, nunca vacilarei.', 'Salmo 16:8', 'Salmo', 16, 8, NULL),
  ('equipamentos', 'Dá vigor ao cansado e multiplica as forças ao que não tem nenhum vigor.', 'Isaías 40:29', 'Isaías', 40, 29, NULL),
  ('equipamentos', 'E até à velhice eu serei o mesmo e ainda até às cãs eu vos trarei; eu o fiz, e eu vos levarei, e eu vos trarei e vos guardarei.', 'Isaías 46:4', 'Isaías', 46, 4, NULL),
  ('equipamentos', 'Como purificará o jovem o seu caminho? Observando-o conforme a tua palavra.', 'Salmo 119:9', 'Salmo', 119, 9, NULL),
  ('equipamentos', 'Porque nele habita corporalmente toda a plenitude da divindade. E estais perfeitos nele, que é a cabeça de todo principado e potestade.', 'Colossenses 2:9-10', 'Colossenses', 2, 9, 10),
  ('equipamentos', 'Jeová, o Senhor, é minha força, e fará os meus pés como os das cervas, e me fará andar sobre as minhas alturas.', 'Habacuque 3:19', 'Habacuque', 3, 19, NULL),
  ('equipamentos', 'Eis que Deus é o meu ajudador; o Senhor está com aqueles que sustêm a minha alma.', 'Salmo 54:4', 'Salmo', 54, 4, NULL),
  ('equipamentos', 'E da mesma maneira também o Espírito ajuda as nossas fraquezas; porque não sabemos o que havemos de pedir como convém, mas o mesmo Espírito intercede por nós com gemidos inexprimíveis.', 'Romanos 8:26', 'Romanos', 8, 26, NULL),
  ('equipamentos', 'Quem és tu que julgas o servo alheio? Para seu próprio senhor ele está em pé ou cai; mas estará firme, porque poderoso é Deus para o firmar.', 'Romanos 14:4', 'Romanos', 14, 4, NULL),
  ('equipamentos', 'E, no último dia, o grande dia da festa, Jesus pôs-se em pé e clamou, dizendo: Se alguém tem sede, que venha a mim e beba.', 'João 7:37', 'João', 7, 37, NULL),
  ('escravidao', 'Estai, pois, firmes na liberdade com que Cristo nos libertou e não torneis a meter-vos debaixo do jugo da servidão.', 'Gálatas 5:1', 'Gálatas', 5, 1, NULL),
  ('escravidao', 'Respondeu-lhes Jesus: Em verdade, em verdade vos digo que todo aquele que comete pecado é servo do pecado.', 'João 8:34', 'João', 8, 34, NULL),
  ('escravidao', 'Exorta os servos a que se sujeitem a seu senhor e em tudo agradem, não contradizendo, não defraudando; antes, mostrando toda a boa lealdade, para que, em tudo, sejam ornamento da doutrina de Deus, nosso Salvador.', 'Tito 2:9-10', 'Tito', 2, 9, 10),
  ('escravidao', 'Porque não recebestes o espírito de escravidão, para, outra vez, estardes em temor, mas recebestes o espírito de adoção de filhos, pelo qual clamamos: Aba, Pai.', 'Romanos 8:15', 'Romanos', 8, 15, NULL),
  ('escravidao', 'Porque te lembrarás que foste servo na terra do Egito e que o Senhor, teu Deus, te tirou dali com mão forte e braço estendido; pelo que o Senhor, teu Deus, te ordenou que guardasses o dia de sábado.', 'Deuteronômio 5:15', 'Deuteronômio', 5, 15, NULL),
  ('escravidao', 'Se, pois, o Filho vos libertar, verdadeiramente, sereis livres.', 'João 8:36', 'João', 8, 36, NULL),
  ('escravidao', 'O rico domina sobre os pobres, e o que toma emprestado é servo do que empresta.', 'Provérbios 22:7', 'Provérbios', 22, 7, NULL),
  ('escravidao', 'Mas, agora, libertados do pecado e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna.', 'Romanos 6:22', 'Romanos', 6, 22, NULL),
  ('escravidao', 'Como livres e não tendo a liberdade por cobertura da malícia, mas como servos de Deus.', '1 Pedro 2:16', '1 Pedro', 2, 16, NULL),
  ('escravidao', 'Porventura, não é este o jejum que escolhi: que soltes as ligaduras da impiedade, que desfaças as ataduras do jugo, e que deixes livres os quebrantados, e que despedaces todo o jugo?', 'Isaías 58:6', 'Isaías', 58, 6, NULL),
  ('escravidao', 'Não será assim entre vós; mas todo aquele que quiser, entre vós, fazer-se grande, que seja vosso serviçal; e qualquer que, entre vós, quiser ser o primeiro, que seja vosso servo.', 'Mateus 20:26-27', 'Mateus', 20, 26, 27),
  ('escravidao', 'Porque, se fomos plantados juntamente com ele na semelhança da sua morte, também o seremos na da sua ressurreição; sabendo isto: que o nosso velho homem foi com ele crucificado, para que o corpo do pecado seja desfeito, a fim de que não sirvamos mais ao pecado.', 'Romanos 6:5-6', 'Romanos', 6, 5, 6),
  ('escravidao', 'Nisto não há judeu nem grego; não há servo nem livre; não há macho nem fêmea; porque todos vós sois um em Cristo Jesus.', 'Gálatas 3:28', 'Gálatas', 3, 28, NULL),
  ('escravidao', 'O Espírito do Senhor é sobre mim, pois que me ungiu para evangelizar os pobres, enviou-me a curar os quebrantados do coração.', 'Lucas 4:18', 'Lucas', 4, 18, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('escravidao', 'A mão dos diligentes dominará, mas os enganadores serão tributários.', 'Provérbios 12:24', 'Provérbios', 12, 24, NULL),
  ('escravidao', 'Pois todos nós fomos batizados em um Espírito, formando um corpo, quer judeus, quer gregos, quer servos, quer livres, e todos temos bebido de um Espírito.', '1 Coríntios 12:13', '1 Coríntios', 12, 13, NULL),
  ('escravidao', 'Na verdade, na verdade vos digo que não é o servo maior do que o seu senhor, nem o enviado, maior do que aquele que o enviou.', 'João 13:16', 'João', 13, 16, NULL),
  ('escravidao', 'Sabendo isto: que a lei não é feita para o justo, mas para os injustos e obstinados, para os ímpios e pecadores, para os profanos e irreligiosos, para os parricidas e matricidas, para os homicidas, para os fornicadores, para os sodomitas, para os roubadores de homens, para os mentirosos, para os perjuros e para o que for contrário à sã doutrina, conforme o evangelho da glória do Deus bem-aventurado, que me foi confiado.', '1 Timóteo 1:9-11', '1 Timóteo', 1, 9, 11),
  ('esperanca', 'Porque eu bem sei os pensamentos que penso de vós, diz o Senhor; pensamentos de paz e não de mal, para vos dar o fim que esperais.', 'Jeremias 29:11', 'Jeremias', 29, 11, NULL),
  ('esperanca', 'Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei. Ele é a salvação da minha face e o meu Deus.', 'Salmo 42:11', 'Salmo', 42, 11, NULL),
  ('esperanca', 'Mas os que esperam no Senhor renovarão as suas forças e subirão com asas como águias; correrão e não se cansarão; caminharão e não se fatigarão.', 'Isaías 40:31', 'Isaías', 40, 31, NULL),
  ('esperanca', 'O Senhor te guardará de todo mal; ele guardará a tua alma. O Senhor guardará a tua entrada e a tua saída, desde agora e para sempre.', 'Salmo 121:7-8', 'Salmo', 121, 7, 8),
  ('esperanca', 'Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo.', 'Romanos 15:13', 'Romanos', 15, 13, NULL),
  ('esperanca', 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.', 'Mateus 11:28', 'Mateus', 11, 28, NULL),
  ('esperanca', 'E não somente isto, mas também nos gloriamos nas tribulações, sabendo que a tribulação produz a paciência; e a paciência, a experiência; e a experiência, a esperança.', 'Romanos 5:3-4', 'Romanos', 5, 3, 4),
  ('esperanca', 'Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem.', 'Hebreus 11:1', 'Hebreus', 11, 1, NULL),
  ('esperanca', 'Agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor.', '1 Coríntios 13:13', '1 Coríntios', 13, 13, NULL),
  ('esperanca', 'Tu és o meu refúgio e o meu escudo; espero na tua palavra.', 'Salmo 119:114', 'Salmo', 119, 114, NULL),
  ('esperanca', 'Retenhamos firmes a confissão da nossa esperança, porque fiel é o que prometeu.', 'Hebreus 10:23', 'Hebreus', 10, 23, NULL),
  ('esperanca', 'Esforçai-vos, e ele fortalecerá o vosso coração, vós todos os que esperais no Senhor.', 'Salmo 31:24', 'Salmo', 31, 24, NULL),
  ('esperanca', 'Eu, porém, esperarei no Senhor; esperei no Deus da minha salvação; o meu Deus me ouvirá.', 'Miqueias 7:7', 'Miqueias', 7, 7, NULL),
  ('esperanca', 'Mas, se esperamos o que não vemos, com paciência o esperamos.', 'Romanos 8:25', 'Romanos', 8, 25, NULL),
  ('esperanca', 'A esperança demorada enfraquece o coração, mas o desejo chegado é árvore de vida.', 'Provérbios 13:12', 'Provérbios', 13, 12, NULL),
  ('esperanca', 'A minha porção é o Senhor, diz a minha alma; portanto, esperarei nele.', 'Lamentações 3:24', 'Lamentações', 3, 24, NULL),
  ('esperanca', 'Guia-me na tua verdade e ensina-me, pois tu és o Deus da minha salvação; por ti estou esperando todo o dia.', 'Salmo 25:5', 'Salmo', 25, 5, NULL),
  ('esperanca', 'E a esperança não traz confusão, porquanto o amor de Deus está derramado em nosso coração pelo Espírito Santo que nos foi dado.', 'Romanos 5:5', 'Romanos', 5, 5, NULL),
  ('esperanca', 'Seja a tua misericórdia, Senhor, sobre nós, como em ti esperamos.', 'Salmo 33:22', 'Salmo', 33, 22, NULL),
  ('esperanca', 'Aguardo o Senhor; a minha alma o aguarda, e espero na sua palavra.', 'Salmo 130:5', 'Salmo', 130, 5, NULL),
  ('esperanca', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que, segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos.', '1 Pedro 1:3', '1 Pedro', 1, 3, NULL),
  ('esperanca', 'O Espírito do Senhor Jeová está sobre mim, porque o Senhor me ungiu para pregar boas-novas aos mansos; enviou-me a restaurar os contritos de coração, a proclamar liberdade aos cativos e a abertura de prisão aos presos.', 'Isaías 61:1', 'Isaías', 61, 1, NULL),
  ('esperanca', 'Antes, santificai a Cristo, como Senhor, em vosso coração; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós.', '1 Pedro 3:15', '1 Pedro', 3, 15, NULL),
  ('esperanca', 'Há um só corpo e um só Espírito, como também fostes chamados em uma só esperança da vossa vocação.', 'Efésios 4:4', 'Efésios', 4, 4, NULL),
  ('esperanca', 'Aos quais Deus quis fazer conhecer quais são as riquezas da glória deste mistério entre os gentios, que é Cristo em vós, esperança da glória.', 'Colossenses 1:27', 'Colossenses', 1, 27, NULL),
  ('esperanca', 'Tal será o conhecimento da sabedoria para a tua alma; se a achares, haverá para ti galardão, e não será cortada a tua expectação.', 'Provérbios 24:14', 'Provérbios', 24, 14, NULL),
  ('esperanca', 'Tendo iluminados os olhos do vosso entendimento, para que saibais qual seja a esperança da sua vocação e quais as riquezas da glória da sua herança nos santos.', 'Efésios 1:18', 'Efésios', 1, 18, NULL),
  ('esperanca', 'Não folga com a injustiça, mas folga com a verdade; tudo sofre, tudo crê, tudo espera, tudo suporta.', '1 Coríntios 13:6-7', '1 Coríntios', 13, 6, 7),
  ('esperanca', 'Ó minha alma, espera somente em Deus, porque dele vem a minha esperança.', 'Salmo 62:5', 'Salmo', 62, 5, NULL),
  ('esperanca', 'A esperança dos justos é alegria, mas a expectação dos ímpios perecerá.', 'Provérbios 10:28', 'Provérbios', 10, 28, NULL),
  ('esperanca', 'Porque tudo que dantes foi escrito para nosso ensino foi escrito, para que, pela paciência e consolação das Escrituras, tenhamos esperança.', 'Romanos 15:4', 'Romanos', 15, 4, NULL),
  ('espirito', 'Ora, o Senhor é Espírito; e onde está o Espírito do Senhor, aí há liberdade.', '2 Coríntios 3:17', '2 Coríntios', 3, 17, NULL),
  ('espirito', 'Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo.', 'Romanos 15:13', 'Romanos', 15, 13, NULL),
  ('espirito', 'Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos? Porque fostes comprados por bom preço; glorificai, pois, a Deus no vosso corpo e no vosso espírito, os quais pertencem a Deus.', '1 Coríntios 6:19-20', '1 Coríntios', 6, 19, 20),
  ('espirito', 'Para que, segundo as riquezas da sua glória, vos conceda que sejais corroborados com poder pelo seu Espírito no homem interior; para que Cristo habite, pela fé, no vosso coração; a fim de, estando arraigados e fundados em amor.', 'Efésios 3:16-17', 'Efésios', 3, 16, 17),
  ('espirito', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('espirito', 'E porei dentro de vós o meu espírito e farei que andeis nos meus estatutos, e guardeis os meus juízos, e os observeis.', 'Ezequiel 36:27', 'Ezequiel', 36, 27, NULL),
  ('espirito', 'Não sabeis vós que sois o templo de Deus e que o Espírito de Deus habita em vós?', '1 Coríntios 3:16', '1 Coríntios', 3, 16, NULL),
  ('espirito', 'E foram vistas por eles línguas repartidas, como que de fogo, as quais pousaram sobre cada um deles. E todos foram cheios do Espírito Santo e começaram a falar em outras línguas, conforme o Espírito Santo lhes concedia que falassem.', 'Atos 2:3-4', 'Atos', 2, 3, 4),
  ('espirito', 'Ensina-me a fazer a tua vontade, pois és o meu Deus; guie-me o teu bom Espírito por terra plana.', 'Salmo 143:10', 'Salmo', 143, 10, NULL),
  ('espirito', 'Pois, se vós, sendo maus, sabeis dar boas dádivas aos vossos filhos, quanto mais dará o Pai celestial o Espírito Santo àqueles que lho pedirem?', 'Lucas 11:13', 'Lucas', 11, 13, NULL),
  ('espirito', 'E a esperança não traz confusão, porquanto o amor de Deus está derramado em nosso coração pelo Espírito Santo que nos foi dado.', 'Romanos 5:5', 'Romanos', 5, 5, NULL),
  ('espirito', 'Nisto conhecemos que estamos nele, e ele em nós, pois que nos deu do seu Espírito.', '1 João 4:13', '1 João', 4, 13, NULL),
  ('espirito', 'Se vivemos no Espírito, andemos também no Espírito.', 'Gálatas 5:25', 'Gálatas', 5, 25, NULL),
  ('espirito', 'O Espírito do Senhor Jeová está sobre mim, porque o Senhor me ungiu para pregar boas-novas aos mansos; enviou-me a restaurar os contritos de coração, a proclamar liberdade aos cativos e a abertura de prisão aos presos.', 'Isaías 61:1', 'Isaías', 61, 1, NULL),
  ('espirito', 'Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade.', 'João 4:24', 'João', 4, 24, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('espirito', 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas tanto em Jerusalém como em toda a Judeia e Samaria e até aos confins da terra.', 'Atos 1:8', 'Atos', 1, 8, NULL),
  ('espirito', 'Esta é a palavra do Senhor a Zorobabel, dizendo: Não por força, nem por violência, mas pelo meu Espírito, diz o Senhor dos Exércitos.', 'Zacarias 4:6', 'Zacarias', 4, 6, NULL),
  ('espirito', 'Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', '2 Timóteo 1:7', '2 Timóteo', 1, 7, NULL),
  ('espirito', 'E da mesma maneira também o Espírito ajuda as nossas fraquezas; porque não sabemos o que havemos de pedir como convém, mas o mesmo Espírito intercede por nós com gemidos inexprimíveis.', 'Romanos 8:26', 'Romanos', 8, 26, NULL),
  ('espirito', 'Porque qual dos homens sabe as coisas do homem, senão o espírito do homem, que nele está? Assim também ninguém sabe as coisas de Deus, senão o Espírito de Deus.', '1 Coríntios 2:11', '1 Coríntios', 2, 11, NULL),
  ('espirito', 'Porque todos os que são guiados pelo Espírito de Deus, esses são filhos de Deus.', 'Romanos 8:14', 'Romanos', 8, 14, NULL),
  ('espirito', 'Para onde me irei do teu Espírito ou para onde fugirei da tua face? Se subir ao céu, tu aí estás; se fizer no Seol a minha cama, eis que tu ali estás também.', 'Salmo 139:7-8', 'Salmo', 139, 7, 8),
  ('espirito', 'E nós somos testemunhas acerca destas palavras, nós e também o Espírito Santo, que Deus deu àqueles que lhe obedecem.', 'Atos 5:32', 'Atos', 5, 32, NULL),
  ('espirito', 'E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo.', 'Atos 2:38', 'Atos', 2, 38, NULL),
  ('espirito', 'Amados, não creiais em todo espírito, mas provai se os espíritos são de Deus, porque já muitos falsos profetas se têm levantado no mundo.', '1 João 4:1', '1 João', 4, 1, NULL),
  ('espirito', 'Porque a carne cobiça contra o Espírito, e o Espírito, contra a carne; e estes opõem-se um ao outro; para que não façais o que quereis.', 'Gálatas 5:17', 'Gálatas', 5, 17, NULL),
  ('espirito', 'Para que o Deus de nosso Senhor Jesus Cristo, o Pai da glória, vos dê em seu conhecimento o espírito de sabedoria e de revelação.', 'Efésios 1:17', 'Efésios', 1, 17, NULL),
  ('espirito', 'E, servindo eles ao Senhor e jejuando, disse o Espírito Santo: Apartai-me a Barnabé e a Saulo para a obra a que os tenho chamado.', 'Atos 13:2', 'Atos', 13, 2, NULL),
  ('espirito', 'No princípio, criou Deus os céus e a terra. E a terra era sem forma e vazia; e havia trevas sobre a face do abismo; e o Espírito de Deus se movia sobre a face das águas.', 'Gênesis 1:1-2', 'Gênesis', 1, 1, 2),
  ('espirito', 'O mesmo Espírito testifica com o nosso espírito que somos filhos de Deus.', 'Romanos 8:16', 'Romanos', 8, 16, NULL),
  ('espirito', 'Porque a profecia nunca foi produzida por vontade de homem algum, mas os homens santos de Deus falaram inspirados pelo Espírito Santo.', '2 Pedro 1:21', '2 Pedro', 1, 21, NULL),
  ('espirito', 'Quando, pois, vos conduzirem para vos entregarem, não estejais solícitos de antemão pelo que haveis de dizer; mas o que vos for dado naquela hora, isso falai; porque não sois vós os que falais, mas o Espírito Santo.', 'Marcos 13:11', 'Marcos', 13, 11, NULL),
  ('espirito', 'Porque a inclinação da carne é morte; mas a inclinação do Espírito é vida e paz.', 'Romanos 8:6', 'Romanos', 8, 6, NULL),
  ('espirito', 'E aconteceu que, como todo o povo se batizava, sendo batizado também Jesus, orando ele, o céu se abriu, e o Espírito Santo desceu sobre ele em forma corpórea, como uma pomba; e ouviu-se uma voz do céu, que dizia: Tu és meu Filho amado; em ti me tenho comprazido.', 'Lucas 3:21-22', 'Lucas', 3, 21, 22),
  ('espirito', 'Mas todos nós, com cara descoberta, refletindo, como um espelho, a glória do Senhor, somos transformados de glória em glória, na mesma imagem, como pelo Espírito do Senhor.', '2 Coríntios 3:18', '2 Coríntios', 3, 18, NULL),
  ('espirito', 'Porque não recebestes o espírito de escravidão, para, outra vez, estardes em temor, mas recebestes o espírito de adoção de filhos, pelo qual clamamos: Aba, Pai.', 'Romanos 8:15', 'Romanos', 8, 15, NULL),
  ('espirito', 'Digo, porém: Andai em Espírito e não cumprireis a concupiscência da carne.', 'Gálatas 5:16', 'Gálatas', 5, 16, NULL),
  ('espirito', 'Não sejais vagarosos no cuidado; sede fervorosos no espírito, servindo ao Senhor.', 'Romanos 12:11', 'Romanos', 12, 11, NULL),
  ('espirito', 'Porque sei que disto me resultará salvação, pela vossa oração e pelo socorro do Espírito de Jesus Cristo.', 'Filipenses 1:19', 'Filipenses', 1, 19, NULL),
  ('espirito', 'Procurando guardar a unidade do Espírito pelo vínculo da paz.', 'Efésios 4:3', 'Efésios', 4, 3, NULL),
  ('espirito', 'E eu não o conhecia, mas o que me mandou a batizar com água, esse me disse: Sobre aquele que vires descer o Espírito e sobre ele repousar, esse é o que batiza com o Espírito Santo.', 'João 1:33', 'João', 1, 33, NULL),
  ('espirito', 'Portanto, eu vos digo: todo pecado e blasfêmia se perdoará aos homens, mas a blasfêmia contra o Espírito não será perdoada aos homens.', 'Mateus 12:31', 'Mateus', 12, 31, NULL),
  ('espirito', 'Cria em mim, ó Deus, um coração puro e renova em mim um espírito reto.', 'Salmo 51:10', 'Salmo', 51, 10, NULL),
  ('espirito', 'E, se o Espírito daquele que dos mortos ressuscitou a Jesus habita em vós, aquele que dos mortos ressuscitou a Cristo também vivificará o vosso corpo mortal, pelo seu Espírito que em vós habita.', 'Romanos 8:11', 'Romanos', 8, 11, NULL),
  ('espirito', 'E vos darei um coração novo e porei dentro de vós um espírito novo; e tirarei o coração de pedra da vossa carne e vos darei um coração de carne.', 'Ezequiel 36:26', 'Ezequiel', 36, 26, NULL),
  ('espirito', 'Não vos deixarei órfãos; voltarei para vós.', 'João 14:18', 'João', 14, 18, NULL),
  ('espirito', 'O que é nascido da carne é carne, e o que é nascido do Espírito é espírito.', 'João 3:6', 'João', 3, 6, NULL),
  ('espirito', 'Mas Deus no-las revelou pelo seu Espírito; porque o Espírito penetra todas as coisas, ainda as profundezas de Deus.', '1 Coríntios 2:10', '1 Coríntios', 2, 10, NULL),
  ('espirito', 'E aquele que examina os corações sabe qual é a intenção do Espírito; e é ele que segundo Deus intercede pelos santos.', 'Romanos 8:27', 'Romanos', 8, 27, NULL),
  ('espirito', 'Cumprindo-se o dia de Pentecostes, estavam todos reunidos no mesmo lugar; e, de repente, veio do céu um som, como de um vento veemente e impetuoso, e encheu toda a casa em que estavam assentados.', 'Atos 2:1-2', 'Atos', 2, 1, 2),
  ('espirito', 'Todavia, digo-vos a verdade: que vos convém que eu vá, porque, se eu não for, o Consolador não virá a vós; mas, se eu for, enviar-vo-lo-ei.', 'João 16:7', 'João', 16, 7, NULL),
  ('espirito', 'E aquele que guarda os seus mandamentos nele está, e ele nele. E nisto conhecemos que ele está em nós: pelo Espírito que nos tem dado.', '1 João 3:24', '1 João', 3, 24, NULL),
  ('espirito', 'Aquele, pois, que vos dá o Espírito e que opera maravilhas entre vós o faz pelas obras da lei ou pela pregação da fé?', 'Gálatas 3:5', 'Gálatas', 3, 5, NULL),
  ('espirito', 'Jesus respondeu: Na verdade, na verdade te digo que aquele que não nascer da água e do Espírito não pode entrar no Reino de Deus.', 'João 3:5', 'João', 3, 5, NULL),
  ('espirito', 'Até que se derrame sobre nós o Espírito lá do alto; então, o deserto se tornará em campo fértil, e o campo fértil será reputado por um bosque.', 'Isaías 32:15', 'Isaías', 32, 15, NULL),
  ('espirito', 'Porque não temos que lutar contra carne e sangue, mas, sim, contra os principados, contra as potestades, contra os príncipes das trevas deste século, contra as hostes espirituais da maldade, nos lugares celestiais.', 'Efésios 6:12', 'Efésios', 6, 12, NULL),
  ('espirito', 'Porque o que semeia na sua carne da carne ceifará a corrupção; mas o que semeia no Espírito do Espírito ceifará a vida eterna.', 'Gálatas 6:8', 'Gálatas', 6, 8, NULL),
  ('espirito', 'Uma língua saudável é árvore de vida, mas a perversidade nela quebranta o espírito.', 'Provérbios 15:4', 'Provérbios', 15, 4, NULL),
  ('espirito', 'Há um só corpo e um só Espírito, como também fostes chamados em uma só esperança da vossa vocação.', 'Efésios 4:4', 'Efésios', 4, 4, NULL),
  ('espirito', 'Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera, a esse glória na igreja, por Jesus Cristo, em todas as gerações, para todo o sempre. Amém!', 'Efésios 3:20-21', 'Efésios', 3, 20, 21),
  ('espirito', 'Orando em todo tempo com toda oração e súplica no Espírito e vigiando nisso com toda perseverança e súplica por todos os santos.', 'Efésios 6:18', 'Efésios', 6, 18, NULL),
  ('espirito', 'O Espírito do Senhor é sobre mim, pois que me ungiu para evangelizar os pobres, enviou-me a curar os quebrantados do coração.', 'Lucas 4:18', 'Lucas', 4, 18, NULL),
  ('espirito', 'Convertei-vos pela minha repreensão; eis que abundantemente derramarei sobre vós meu espírito e vos farei saber as minhas palavras.', 'Provérbios 1:23', 'Provérbios', 1, 23, NULL),
  ('espirito', 'Pois todos nós fomos batizados em um Espírito, formando um corpo, quer judeus, quer gregos, quer servos, quer livres, e todos temos bebido de um Espírito.', '1 Coríntios 12:13', '1 Coríntios', 12, 13, NULL),
  ('espirito', 'E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo e recebido acima, na glória.', '1 Timóteo 3:16', '1 Timóteo', 3, 16, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('espirito', 'Tomai também o capacete da salvação e a espada do Espírito, que é a palavra de Deus.', 'Efésios 6:17', 'Efésios', 6, 17, NULL),
  ('espirito', 'Nisto conhecereis o Espírito de Deus: todo espírito que confessa que Jesus Cristo veio em carne é de Deus; e todo espírito que não confessa que Jesus Cristo veio em carne não é de Deus; mas este é o espírito do anticristo, do qual já ouvistes que há de vir, e eis que está já no mundo.', '1 João 4:2-3', '1 João', 4, 2, 3),
  ('espirito', 'Porque os que são segundo a carne inclinam-se para as coisas da carne; mas os que são segundo o Espírito, para as coisas do Espírito.', 'Romanos 8:5', 'Romanos', 8, 5, NULL),
  ('espirito', 'Portanto, cingindo os lombos do vosso entendimento, sede sóbrios e esperai inteiramente na graça que se vos ofereceu na revelação de Jesus Cristo.', '1 Pedro 1:13', '1 Pedro', 1, 13, NULL),
  ('espirito', 'Quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus, purificará a vossa consciência das obras mortas, para servirdes ao Deus vivo?', 'Hebreus 9:14', 'Hebreus', 9, 14, NULL),
  ('espirito', 'E, clamando Jesus com grande voz, disse: Pai, nas tuas mãos entrego o meu espírito. E, havendo dito isso, expirou.', 'Lucas 23:46', 'Lucas', 23, 46, NULL),
  ('espirito', 'E, quando Jesus tomou o vinagre, disse: Está consumado. E, inclinando a cabeça, entregou o espírito.', 'João 19:30', 'João', 19, 30, NULL),
  ('espirito', 'Os quais vos diziam que, no último tempo, haveria escarnecedores que andariam segundo as suas ímpias concupiscências. Estes são os que causam divisões, sensuais, que não têm o Espírito.', 'Judas 1:18-19', 'Judas', 1, 18, 19),
  ('espirito', 'Todos os caminhos do homem são limpos aos seus olhos, mas o Senhor pesa os espíritos.', 'Provérbios 16:2', 'Provérbios', 16, 2, NULL),
  ('espirito-santo', 'Ora, o Senhor é Espírito; e onde está o Espírito do Senhor, aí há liberdade.', '2 Coríntios 3:17', '2 Coríntios', 3, 17, NULL),
  ('espirito-santo', 'Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo.', 'Romanos 15:13', 'Romanos', 15, 13, NULL),
  ('espirito-santo', 'Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos? Porque fostes comprados por bom preço; glorificai, pois, a Deus no vosso corpo e no vosso espírito, os quais pertencem a Deus.', '1 Coríntios 6:19-20', '1 Coríntios', 6, 19, 20),
  ('espirito-santo', 'E eu rogarei ao Pai, e ele vos dará outro Consolador, para que fique convosco para sempre.', 'João 14:16', 'João', 14, 16, NULL),
  ('espirito-santo', 'Mas aquele Consolador, o Espírito Santo, que o Pai enviará em meu nome, vos ensinará todas as coisas e vos fará lembrar de tudo quanto vos tenho dito.', 'João 14:26', 'João', 14, 26, NULL),
  ('espirito-santo', 'Não sabeis vós que sois o templo de Deus e que o Espírito de Deus habita em vós?', '1 Coríntios 3:16', '1 Coríntios', 3, 16, NULL),
  ('espirito-santo', 'E porei dentro de vós o meu espírito e farei que andeis nos meus estatutos, e guardeis os meus juízos, e os observeis.', 'Ezequiel 36:27', 'Ezequiel', 36, 27, NULL),
  ('espirito-santo', 'E foram vistas por eles línguas repartidas, como que de fogo, as quais pousaram sobre cada um deles. E todos foram cheios do Espírito Santo e começaram a falar em outras línguas, conforme o Espírito Santo lhes concedia que falassem.', 'Atos 2:3-4', 'Atos', 2, 3, 4),
  ('espirito-santo', 'E a esperança não traz confusão, porquanto o amor de Deus está derramado em nosso coração pelo Espírito Santo que nos foi dado.', 'Romanos 5:5', 'Romanos', 5, 5, NULL),
  ('espirito-santo', 'E não entristeçais o Espírito Santo de Deus, no qual estais selados para o Dia da redenção.', 'Efésios 4:30', 'Efésios', 4, 30, NULL),
  ('espirito-santo', 'E, tendo eles orado, moveu-se o lugar em que estavam reunidos; e todos foram cheios do Espírito Santo e anunciavam com ousadia a palavra de Deus.', 'Atos 4:31', 'Atos', 4, 31, NULL),
  ('espirito-santo', 'Pois, se vós, sendo maus, sabeis dar boas dádivas aos vossos filhos, quanto mais dará o Pai celestial o Espírito Santo àqueles que lho pedirem?', 'Lucas 11:13', 'Lucas', 11, 13, NULL),
  ('espirito-santo', 'Ensina-me a fazer a tua vontade, pois és o meu Deus; guie-me o teu bom Espírito por terra plana.', 'Salmo 143:10', 'Salmo', 143, 10, NULL),
  ('espirito-santo', 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas tanto em Jerusalém como em toda a Judeia e Samaria e até aos confins da terra.', 'Atos 1:8', 'Atos', 1, 8, NULL),
  ('espirito-santo', 'Mas vós, amados, edificando-vos a vós mesmos sobre a vossa santíssima fé, orando no Espírito Santo, conservai a vós mesmos no amor de Deus, esperando a misericórdia de nosso Senhor Jesus Cristo, para a vida eterna.', 'Judas 1:20-21', 'Judas', 1, 20, 21),
  ('espirito-santo', 'Portanto, ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo; ensinando-as a guardar todas as coisas que eu vos tenho mandado; e eis que eu estou convosco todos os dias, até à consumação dos séculos. Amém!', 'Mateus 28:19-20', 'Mateus', 28, 19, 20),
  ('espirito-santo', 'Porque qual dos homens sabe as coisas do homem, senão o espírito do homem, que nele está? Assim também ninguém sabe as coisas de Deus, senão o Espírito de Deus.', '1 Coríntios 2:11', '1 Coríntios', 2, 11, NULL),
  ('espirito-santo', 'A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com vós todos. Amém!', '2 Coríntios 13:13', '2 Coríntios', 13, 13, NULL),
  ('espirito-santo', 'Mas, quando vier o Consolador, que eu da parte do Pai vos hei de enviar, aquele Espírito da verdade, que procede do Pai, testificará de mim.', 'João 15:26', 'João', 15, 26, NULL),
  ('espirito-santo', 'Esta é a palavra do Senhor a Zorobabel, dizendo: Não por força, nem por violência, mas pelo meu Espírito, diz o Senhor dos Exércitos.', 'Zacarias 4:6', 'Zacarias', 4, 6, NULL),
  ('espirito-santo', 'E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo.', 'Atos 2:38', 'Atos', 2, 38, NULL),
  ('espirito-santo', 'E nós somos testemunhas acerca destas palavras, nós e também o Espírito Santo, que Deus deu àqueles que lhe obedecem.', 'Atos 5:32', 'Atos', 5, 32, NULL),
  ('espirito-santo', 'Para onde me irei do teu Espírito ou para onde fugirei da tua face? Se subir ao céu, tu aí estás; se fizer no Seol a minha cama, eis que tu ali estás também.', 'Salmo 139:7-8', 'Salmo', 139, 7, 8),
  ('espirito-santo', 'E os que ouviram foram batizados em nome do Senhor Jesus. E, impondo-lhes Paulo as mãos, veio sobre eles o Espírito Santo; e falavam línguas e profetizavam.', 'Atos 19:5-6', 'Atos', 19, 5, 6),
  ('espirito-santo', 'E, servindo eles ao Senhor e jejuando, disse o Espírito Santo: Apartai-me a Barnabé e a Saulo para a obra a que os tenho chamado.', 'Atos 13:2', 'Atos', 13, 2, NULL),
  ('espirito-santo', 'Quando, pois, vos conduzirem para vos entregarem, não estejais solícitos de antemão pelo que haveis de dizer; mas o que vos for dado naquela hora, isso falai; porque não sois vós os que falais, mas o Espírito Santo.', 'Marcos 13:11', 'Marcos', 13, 11, NULL),
  ('espirito-santo', 'Porque a profecia nunca foi produzida por vontade de homem algum, mas os homens santos de Deus falaram inspirados pelo Espírito Santo.', '2 Pedro 1:21', '2 Pedro', 1, 21, NULL),
  ('espirito-santo', 'E, quando comecei a falar, caiu sobre eles o Espírito Santo, como também sobre nós ao princípio.', 'Atos 11:15', 'Atos', 11, 15, NULL),
  ('espirito-santo', 'E aconteceu que, como todo o povo se batizava, sendo batizado também Jesus, orando ele, o céu se abriu, e o Espírito Santo desceu sobre ele em forma corpórea, como uma pomba; e ouviu-se uma voz do céu, que dizia: Tu és meu Filho amado; em ti me tenho comprazido.', 'Lucas 3:21-22', 'Lucas', 3, 21, 22),
  ('espirito-santo', 'O Espírito do Senhor Jeová está sobre mim, porque o Senhor me ungiu para pregar boas-novas aos mansos; enviou-me a restaurar os contritos de coração, a proclamar liberdade aos cativos e a abertura de prisão aos presos.', 'Isaías 61:1', 'Isaías', 61, 1, NULL),
  ('espirito-santo', 'Não pelas obras de justiça que houvéssemos feito, mas, segundo a sua misericórdia, nos salvou pela lavagem da regeneração e da renovação do Espírito Santo.', 'Tito 3:5', 'Tito', 3, 5, NULL),
  ('espirito-santo', 'Respondeu, então, Pedro: Pode alguém, porventura, recusar a água, para que não sejam batizados estes que também receberam, como nós, o Espírito Santo?', 'Atos 10:47', 'Atos', 10, 47, NULL),
  ('espirito-santo', 'E, se qualquer disser alguma palavra contra o Filho do Homem, ser-lhe-á perdoado, mas, se alguém falar contra o Espírito Santo, não lhe será perdoado, nem neste século nem no futuro.', 'Mateus 12:32', 'Mateus', 12, 32, NULL),
  ('espirito-santo', 'E eu não o conhecia, mas o que me mandou a batizar com água, esse me disse: Sobre aquele que vires descer o Espírito e sobre ele repousar, esse é o que batiza com o Espírito Santo.', 'João 1:33', 'João', 1, 33, NULL),
  ('espirito-santo', 'E, projetando ele isso, eis que, em sonho, lhe apareceu um anjo do Senhor, dizendo: José, filho de Davi, não temas receber a Maria, tua mulher, porque o que nela está gerado é do Espírito Santo.', 'Mateus 1:20', 'Mateus', 1, 20, NULL),
  ('espirito-santo', 'De sorte que, exaltado pela destra de Deus e tendo recebido do Pai a promessa do Espírito Santo, derramou isto que vós agora vedes e ouvis.', 'Atos 2:33', 'Atos', 2, 33, NULL),
  ('espirito-santo', 'No princípio, criou Deus os céus e a terra. E a terra era sem forma e vazia; e havia trevas sobre a face do abismo; e o Espírito de Deus se movia sobre a face das águas.', 'Gênesis 1:1-2', 'Gênesis', 1, 1, 2),
  ('espirito-santo', 'Assim, pois, as igrejas em toda a Judeia, e Galileia, e Samaria tinham paz e eram edificadas; e se multiplicavam, andando no temor do Senhor e na consolação do Espírito Santo.', 'Atos 9:31', 'Atos', 9, 31, NULL),
  ('espirito-santo', 'Portanto, eu vos digo: todo pecado e blasfêmia se perdoará aos homens, mas a blasfêmia contra o Espírito não será perdoada aos homens.', 'Mateus 12:31', 'Mateus', 12, 31, NULL),
  ('espirito-santo', 'E, respondendo o anjo, disse-lhe: Descerá sobre ti o Espírito Santo, e a virtude do Altíssimo te cobrirá com a sua sombra; pelo que também o Santo, que de ti há de nascer, será chamado Filho de Deus.', 'Lucas 1:35', 'Lucas', 1, 35, NULL),
  ('espirito-santo', 'Ora, o nascimento de Jesus Cristo foi assim: Estando Maria, sua mãe, desposada com José, antes de se ajuntarem, achou-se ter concebido do Espírito Santo.', 'Mateus 1:18', 'Mateus', 1, 18, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('espirito-santo', 'E, quando ele vier, convencerá o mundo do pecado, e da justiça, e do juízo.', 'João 16:8', 'João', 16, 8, NULL),
  ('espirito-santo', 'E eu, em verdade, vos batizo com água, para o arrependimento; mas aquele que vem após mim é mais poderoso do que eu; não sou digno de levar as suas sandálias; ele vos batizará com o Espírito Santo e com fogo.', 'Mateus 3:11', 'Mateus', 3, 11, NULL),
  ('espirito-santo', 'Porque, com uma só oblação, aperfeiçoou para sempre os que são santificados.', 'Hebreus 10:14', 'Hebreus', 10, 14, NULL),
  ('evangelizacao', 'Porque o Senhor assim no-lo mandou: Eu te pus para luz dos gentios, para que sejas de salvação até aos confins da terra.', 'Atos 13:47', 'Atos', 13, 47, NULL),
  ('evangelizacao', 'E disse-lhes: Ide por todo o mundo, pregai o evangelho a toda criatura.', 'Marcos 16:15', 'Marcos', 16, 15, NULL),
  ('evangelizacao', 'Mas em nada tenho a minha vida por preciosa, contanto que cumpra com alegria a minha carreira e o ministério que recebi do Senhor Jesus, para dar testemunho do evangelho da graça de Deus.', 'Atos 20:24', 'Atos', 20, 24, NULL),
  ('evangelizacao', 'Nem se acende a candeia e se coloca debaixo do alqueire, mas, no velador, e dá luz a todos que estão na casa. Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem o vosso Pai, que está nos céus.', 'Mateus 5:15-16', 'Mateus', 5, 15, 16),
  ('evangelizacao', 'Portanto, ide, ensinai todas as nações, batizando-as em nome do Pai, e do Filho, e do Espírito Santo; ensinando-as a guardar todas as coisas que eu vos tenho mandado; e eis que eu estou convosco todos os dias, até à consumação dos séculos. Amém!', 'Mateus 28:19-20', 'Mateus', 28, 19, 20),
  ('evangelizacao', 'Porque não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê, primeiro do judeu e também do grego.', 'Romanos 1:16', 'Romanos', 1, 16, NULL),
  ('evangelizacao', 'Louvai ao Senhor e invocai o seu nome; fazei conhecidas as suas obras entre os povos.', 'Salmo 105:1', 'Salmo', 105, 1, NULL),
  ('evangelizacao', 'De sorte que a fé é pelo ouvir, e o ouvir pela palavra de Deus.', 'Romanos 10:17', 'Romanos', 10, 17, NULL),
  ('evangelizacao', 'Antes, santificai a Cristo, como Senhor, em vosso coração; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós.', '1 Pedro 3:15', '1 Pedro', 3, 15, NULL),
  ('evangelizacao', 'O Espírito do Senhor é sobre mim, pois que me ungiu para evangelizar os pobres, enviou-me a curar os quebrantados do coração.', 'Lucas 4:18', 'Lucas', 4, 18, NULL),
  ('evangelizacao', 'Também vos notifico, irmãos, o evangelho que já vos tenho anunciado, o qual também recebestes e no qual também permaneceis; pelo qual também sois salvos, se o retiverdes tal como vo-lo tenho anunciado, se não é que crestes em vão.', '1 Coríntios 15:1-2', '1 Coríntios', 15, 1, 2),
  ('evangelizacao', 'Que pregues a palavra, instes a tempo e fora de tempo, redarguas, repreendas, exortes, com toda a longanimidade e doutrina.', '2 Timóteo 4:2', '2 Timóteo', 4, 2, NULL),
  ('evangelizacao', 'Vós sois a luz do mundo; não se pode esconder uma cidade edificada sobre um monte.', 'Mateus 5:14', 'Mateus', 5, 14, NULL),
  ('evangelizacao', 'Para o que, pelo nosso evangelho, vos chamou, para alcançardes a glória de nosso Senhor Jesus Cristo.', '2 Tessalonicenses 2:14', '2 Tessalonicenses', 2, 14, NULL),
  ('evangelizacao', 'Porque qualquer que quiser salvar a sua vida perdê-la-á, mas qualquer que perder a sua vida por amor de mim e do evangelho, esse a salvará.', 'Marcos 8:35', 'Marcos', 8, 35, NULL),
  ('evangelizacao', 'E Jesus, respondendo, disse: Em verdade vos digo que ninguém há, que tenha deixado casa, ou irmãos, ou irmãs, ou pai, ou mãe, ou mulher, ou filhos, ou campos, por amor de mim e do evangelho, que não receba cem vezes tanto, já neste tempo, em casas, e irmãos, e irmãs, e mães, e filhos, e campos, com perseguições, e, no século futuro, a vida eterna.', 'Marcos 10:29-30', 'Marcos', 10, 29, 30),
  ('evangelizacao', 'E direis, naquele dia: Dai graças ao Senhor, invocai o seu nome, tornai manifestos os seus feitos entre os povos e contai quão excelso é o seu nome.', 'Isaías 12:4', 'Isaías', 12, 4, NULL),
  ('evangelizacao', 'Tu, porém, fala o que convém à sã doutrina.', 'Tito 2:1', 'Tito', 2, 1, NULL),
  ('evangelizacao', 'Desde então, começou Jesus a pregar e a dizer: Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 4:17', 'Mateus', 4, 17, NULL),
  ('evangelizacao', 'Nisto todos conhecerão que sois meus discípulos, se vos amardes uns aos outros.', 'João 13:35', 'João', 13, 35, NULL),
  ('evangelizacao', 'Assim, eu me engrandecerei, e me santificarei, e me farei conhecer aos olhos de muitas nações; e saberão que eu sou o Senhor.', 'Ezequiel 38:23', 'Ezequiel', 38, 23, NULL),
  ('evangelizacao', 'Nisto é glorificado meu Pai: que deis muito fruto; e assim sereis meus discípulos.', 'João 15:8', 'João', 15, 8, NULL),
  ('evangelizacao', 'Vós sois o sal da terra; e, se o sal for insípido, com que se há de salgar? Para nada mais presta, senão para se lançar fora e ser pisado pelos homens.', 'Mateus 5:13', 'Mateus', 5, 13, NULL),
  ('evangelizacao', 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas tanto em Jerusalém como em toda a Judeia e Samaria e até aos confins da terra.', 'Atos 1:8', 'Atos', 1, 8, NULL),
  ('evangelizacao', 'Aos quais Deus quis fazer conhecer quais são as riquezas da glória deste mistério entre os gentios, que é Cristo em vós, esperança da glória.', 'Colossenses 1:27', 'Colossenses', 1, 27, NULL),
  ('evangelizacao', 'Porque nada me propus saber entre vós, senão a Jesus Cristo e este crucificado.', '1 Coríntios 2:2', '1 Coríntios', 2, 2, NULL),
  ('evangelizacao', 'Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz.', '1 Pedro 2:9', '1 Pedro', 2, 9, NULL),
  ('evangelizacao', 'Disse-lhes, pois, Jesus outra vez: Paz seja convosco! Assim como o Pai me enviou, também eu vos envio a vós.', 'João 20:21', 'João', 20, 21, NULL),
  ('evangelizacao', 'E todos os dias, no templo e nas casas, não cessavam de ensinar e de anunciar a Jesus Cristo.', 'Atos 5:42', 'Atos', 5, 42, NULL),
  ('evangelizacao', 'E disse-lhes: Vinde após mim, e eu vos farei pescadores de homens.', 'Mateus 4:19', 'Mateus', 4, 19, NULL),
  ('evangelizacao', 'E, abrindo Pedro a boca, disse: Reconheço, por verdade, que Deus não faz acepção de pessoas; mas que lhe é agradável aquele que, em qualquer nação, o teme e faz o que é justo.', 'Atos 10:34-35', 'Atos', 10, 34, 35),
  ('evangelizacao', 'Porque nós somos cooperadores de Deus; vós sois lavoura de Deus e edifício de Deus.', '1 Coríntios 3:9', '1 Coríntios', 3, 9, NULL),
  ('evangelizacao', 'Depois disso, ouvi a voz do Senhor, que dizia: A quem enviarei, e quem há de ir por nós? Então, disse eu: eis-me aqui, envia-me a mim.', 'Isaías 6:8', 'Isaías', 6, 8, NULL),
  ('evangelizacao', 'Como nada, que útil seja, deixei de vos anunciar e ensinar publicamente e pelas casas.', 'Atos 20:20', 'Atos', 20, 20, NULL),
  ('evangelizacao', 'E tudo isso provém de Deus, que nos reconciliou consigo mesmo por Jesus Cristo e nos deu o ministério da reconciliação.', '2 Coríntios 5:18', '2 Coríntios', 5, 18, NULL),
  ('evangelizacao', 'Portanto, o que desde o princípio ouvistes permaneça em vós. Se em vós permanecer o que desde o princípio ouvistes, também permanecereis no Filho e no Pai.', '1 João 2:24', '1 João', 2, 24, NULL),
  ('evangelizacao', 'Mas, alcançando socorro de Deus, ainda até ao dia de hoje permaneço, dando testemunho, tanto a pequenos como a grandes, não dizendo nada mais do que o que os profetas e Moisés disseram que devia acontecer, isto é, que o Cristo devia padecer e, sendo o primeiro da ressurreição dos mortos, devia anunciar a luz a este povo e aos gentios.', 'Atos 26:22-23', 'Atos', 26, 22, 23),
  ('evangelizacao', 'E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo e recebido acima, na glória.', '1 Timóteo 3:16', '1 Timóteo', 3, 16, NULL),
  ('evangelizacao', 'Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça, e calçados os pés na preparação do evangelho da paz; tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno.', 'Efésios 6:14-16', 'Efésios', 6, 14, 16),
  ('evangelizacao', 'E este evangelho do Reino será pregado em todo o mundo, em testemunho a todas as gentes, e então virá o fim.', 'Mateus 24:14', 'Mateus', 24, 14, NULL),
  ('evangelizacao', 'E curai os enfermos que nela houver e dizei-lhes: É chegado a vós o Reino de Deus.', 'Lucas 10:9', 'Lucas', 10, 9, NULL),
  ('evangelizacao', 'E percorria Jesus toda a Galileia, ensinando nas suas sinagogas, e pregando o evangelho do Reino, e curando todas as enfermidades e moléstias entre o povo.', 'Mateus 4:23', 'Mateus', 4, 23, NULL),
  ('evangelizacao', 'A Lei e os Profetas duraram até João; desde então, é anunciado o Reino de Deus, e todo homem emprega força para entrar nele.', 'Lucas 16:16', 'Lucas', 16, 16, NULL),
  ('falar', 'A morte e a vida estão no poder da língua; e aquele que a ama comerá do seu fruto.', 'Provérbios 18:21', 'Provérbios', 18, 21, NULL),
  ('falar', 'O homem bom, do bom tesouro do seu coração, tira o bem, e o homem mau, do mau tesouro do seu coração, tira o mal, porque da abundância do seu coração fala a boca.', 'Lucas 6:45', 'Lucas', 6, 45, NULL),
  ('falar', 'Não saia da vossa boca nenhuma palavra torpe, mas só a que for boa para promover a edificação, para que dê graça aos que a ouvem.', 'Efésios 4:29', 'Efésios', 4, 29, NULL),
  ('falar', 'O que guarda a sua boca conserva a sua alma, mas o que muito abre os lábios tem perturbação.', 'Provérbios 13:3', 'Provérbios', 13, 3, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('falar', 'Não tornando mal por mal ou injúria por injúria; antes, pelo contrário, bendizendo, sabendo que para isto fostes chamados, para que, por herança, alcanceis a bênção.', '1 Pedro 3:9', '1 Pedro', 3, 9, NULL),
  ('falar', 'Uma língua saudável é árvore de vida, mas a perversidade nela quebranta o espírito.', 'Provérbios 15:4', 'Provérbios', 15, 4, NULL),
  ('falar', 'Mas eu vos digo que de toda palavra ociosa que os homens disserem hão de dar conta no Dia do Juízo.', 'Mateus 12:36', 'Mateus', 12, 36, NULL),
  ('falar', 'Até o tolo, quando se cala, será reputado por sábio; e o que cerrar os seus lábios, por sábio.', 'Provérbios 17:28', 'Provérbios', 17, 28, NULL),
  ('falar', 'Na multidão de palavras não falta transgressão, mas o que modera os seus lábios é prudente.', 'Provérbios 10:19', 'Provérbios', 10, 19, NULL),
  ('falar', 'Sabeis isto, meus amados irmãos; mas todo o homem seja pronto para ouvir, tardio para falar, tardio para se irar.', 'Tiago 1:19', 'Tiago', 1, 19, NULL),
  ('falar', 'Abre a tua boca a favor do mudo, pelo direito de todos os que se acham em desolação.', 'Provérbios 31:8', 'Provérbios', 31, 8, NULL),
  ('falar', 'O homem se alegra na resposta da sua boca, e a palavra, a seu tempo, quão boa é!', 'Provérbios 15:23', 'Provérbios', 15, 23, NULL),
  ('falar', 'A resposta branda desvia o furor, mas a palavra dura suscita a ira.', 'Provérbios 15:1', 'Provérbios', 15, 1, NULL),
  ('falar', 'Meus filhinhos, não amemos de palavra, nem de língua, mas por obra e em verdade.', '1 João 3:18', '1 João', 3, 18, NULL),
  ('falar', 'Porque todos tropeçamos em muitas coisas. Se alguém não tropeça em palavra, o tal varão é perfeito e poderoso para também refrear todo o corpo.', 'Tiago 3:2', 'Tiago', 3, 2, NULL),
  ('falar', 'Nas palavras da boca do sábio, há favor, mas os lábios do tolo o devoram.', 'Eclesiastes 10:12', 'Eclesiastes', 10, 12, NULL),
  ('falar', 'O que anda praguejando descobre o segredo, mas o fiel de espírito encobre o negócio.', 'Provérbios 11:13', 'Provérbios', 11, 13, NULL),
  ('falar', 'De uma mesma boca procede bênção e maldição. Meus irmãos, não convém que isto se faça assim.', 'Tiago 3:10', 'Tiago', 3, 10, NULL),
  ('falar', 'Encha-se a minha boca do teu louvor e da tua glória todo o dia.', 'Salmo 71:8', 'Salmo', 71, 8, NULL),
  ('falar', 'Andai com sabedoria para com os que estão de fora, remindo o tempo. A vossa palavra seja sempre agradável, temperada com sal, para que saibais como vos convém responder a cada um.', 'Colossenses 4:5-6', 'Colossenses', 4, 5, 6),
  ('falar', 'Ora, se teu irmão pecar contra ti, vai e repreende-o entre ti e ele só; se te ouvir, ganhaste a teu irmão.', 'Mateus 18:15', 'Mateus', 18, 15, NULL),
  ('falar', 'Porquanto tudo o que em trevas dissestes à luz será ouvido; e o que falastes ao ouvido no gabinete sobre os telhados será apregoado.', 'Lucas 12:3', 'Lucas', 12, 3, NULL),
  ('falar', 'A saber: Se, com a tua boca, confessares ao Senhor Jesus e, em teu coração, creres que Deus o ressuscitou dos mortos, serás salvo.', 'Romanos 10:9', 'Romanos', 10, 9, NULL),
  ('falar', 'Onde não há conselho os projetos saem vãos, mas, com a multidão de conselheiros, se confirmarão.', 'Provérbios 15:22', 'Provérbios', 15, 22, NULL),
  ('falar', 'E da mesma maneira também o Espírito ajuda as nossas fraquezas; porque não sabemos o que havemos de pedir como convém, mas o mesmo Espírito intercede por nós com gemidos inexprimíveis.', 'Romanos 8:26', 'Romanos', 8, 26, NULL),
  ('falar', 'E, orando, não useis de vãs repetições, como os gentios, que pensam que, por muito falarem, serão ouvidos.', 'Mateus 6:7', 'Mateus', 6, 7, NULL),
  ('falar', 'Favo de mel são as palavras suaves: doces para a alma e saúde para os ossos.', 'Provérbios 16:24', 'Provérbios', 16, 24, NULL),
  ('falar', 'Louvai ao Senhor e invocai o seu nome; fazei conhecidas as suas obras entre os povos.', 'Salmo 105:1', 'Salmo', 105, 1, NULL),
  ('falar', 'Assim será a palavra que sair da minha boca; ela não voltará para mim vazia; antes, fará o que me apraz e prosperará naquilo para que a enviei.', 'Isaías 55:11', 'Isaías', 55, 11, NULL),
  ('falar', 'Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, Senhor, rocha minha e libertador meu!', 'Salmo 19:14', 'Salmo', 19, 14, NULL),
  ('falar', 'Não toma prazer o tolo no entendimento, senão em que se descubra o seu coração.', 'Provérbios 18:2', 'Provérbios', 18, 2, NULL),
  ('falar', 'Senhor, livra a minha alma dos lábios mentirosos e da língua enganadora.', 'Salmo 120:2', 'Salmo', 120, 2, NULL),
  ('falar', 'O hipócrita, com a boca, danifica o seu próximo, mas os justos são libertados pelo conhecimento.', 'Provérbios 11:9', 'Provérbios', 11, 9, NULL),
  ('falar', 'Os lábios do tolo entram na contenda, e a sua boca brada por açoites.', 'Provérbios 18:6', 'Provérbios', 18, 6, NULL),
  ('falar', 'A solicitude no coração do homem o abate, mas uma boa palavra o alegra.', 'Provérbios 12:25', 'Provérbios', 12, 25, NULL),
  ('falar', 'Em todo trabalho há proveito, mas a palavra dos lábios só encaminha para a pobreza.', 'Provérbios 14:23', 'Provérbios', 14, 23, NULL),
  ('falar', 'Se alguém entre vós cuida ser religioso e não refreia a sua língua, antes, engana o seu coração, a religião desse é vã.', 'Tiago 1:26', 'Tiago', 1, 26, NULL),
  ('falar', 'Ainda que eu falasse as línguas dos homens e dos anjos e não tivesse amor, seria como o metal que soa ou como o sino que tine.', '1 Coríntios 13:1', '1 Coríntios', 13, 1, NULL),
  ('falar', 'Guarda a tua língua do mal e os teus lábios, de falarem enganosamente.', 'Salmo 34:13', 'Salmo', 34, 13, NULL),
  ('falar', 'E, quanto fizerdes por palavras ou por obras, fazei tudo em nome do Senhor Jesus, dando por ele graças a Deus Pai.', 'Colossenses 3:17', 'Colossenses', 3, 17, NULL),
  ('falar', 'E não comuniqueis com as obras infrutuosas das trevas, mas, antes, condenai-as. Porque o que eles fazem em oculto, até dizê-lo é torpe.', 'Efésios 5:11-12', 'Efésios', 5, 11, 12),
  ('falar', 'Enquanto eu me calei, envelheceram os meus ossos pelo meu bramido em todo o dia.', 'Salmo 32:3', 'Salmo', 32, 3, NULL),
  ('falar', 'Os lábios do justo sabem o que agrada, mas a boca dos ímpios anda cheia de perversidades.', 'Provérbios 10:32', 'Provérbios', 10, 32, NULL),
  ('falar', 'Honroso é para o homem o desviar-se de questões, mas todo tolo se entremete nelas.', 'Provérbios 20:3', 'Provérbios', 20, 3, NULL),
  ('falar', 'Seja, porém, o vosso falar: Sim, sim; não, não, porque o que passa disso é de procedência maligna.', 'Mateus 5:37', 'Mateus', 5, 37, NULL),
  ('falar', 'Desvia de ti a tortuosidade da boca e alonga de ti a perversidade dos lábios.', 'Provérbios 4:24', 'Provérbios', 4, 24, NULL),
  ('falar', 'Tu, porém, fala o que convém à sã doutrina.', 'Tito 2:1', 'Tito', 2, 1, NULL),
  ('falar', 'Quando, pois, vos conduzirem para vos entregarem, não estejais solícitos de antemão pelo que haveis de dizer; mas o que vos for dado naquela hora, isso falai; porque não sois vós os que falais, mas o Espírito Santo.', 'Marcos 13:11', 'Marcos', 13, 11, NULL),
  ('falar', 'Pela palavra do Senhor foram feitos os céus; e todo o exército deles, pelo espírito da sua boca.', 'Salmo 33:6', 'Salmo', 33, 6, NULL),
  ('falar', 'Abre a tua boca, julga retamente e faze justiça aos pobres e aos necessitados.', 'Provérbios 31:9', 'Provérbios', 31, 9, NULL),
  ('falar', 'Jesus, porém, respondendo, disse-lhes: Em verdade vos digo que, se tiverdes fé e não duvidardes, não só fareis o que foi feito à figueira, mas até, se a este monte disserdes: Ergue-te e precipita-te no mar, assim será feito.', 'Mateus 21:21', 'Mateus', 21, 21, NULL),
  ('falar', 'Visto que com o coração se crê para a justiça, e com a boca se faz confissão para a salvação.', 'Romanos 10:10', 'Romanos', 10, 10, NULL),
  ('falar', 'Sem que haja uma palavra na minha língua, eis que, ó Senhor, tudo conheces.', 'Salmo 139:4', 'Salmo', 139, 4, NULL),
  ('falar', 'O que encobre o ódio tem lábios falsos, e o que difama é um insensato.', 'Provérbios 10:18', 'Provérbios', 10, 18, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('falar', 'Bênçãos há sobre a cabeça do justo, mas a violência cobre a boca dos ímpios.', 'Provérbios 10:6', 'Provérbios', 10, 6, NULL),
  ('falar', 'Prata escolhida é a língua do justo; o coração dos ímpios é de nenhum preço.', 'Provérbios 10:20', 'Provérbios', 10, 20, NULL),
  ('falar', 'Não convém ao tolo a fala excelente; quanto menos ao príncipe, o lábio mentiroso!', 'Provérbios 17:7', 'Provérbios', 17, 7, NULL),
  ('falar', 'E, se teu irmão pecar contra ti, repreende-o; e, se ele se arrepender, perdoa-lhe; e, se pecar contra ti sete vezes no dia e sete vezes no dia vier ter contigo, dizendo: Arrependo-me, perdoa-lhe.', 'Lucas 17:3b-4', 'Lucas 17:3b-4', NULL, NULL, NULL),
  ('falar', 'Louvarei ao Senhor em todo o tempo; o seu louvor estará continuamente na minha boca.', 'Salmo 34:1', 'Salmo', 34, 1, NULL),
  ('falar', 'E se disseres no teu coração: Como conheceremos a palavra que o Senhor não falou? Quando o tal profeta falar em nome do Senhor, e tal palavra se não cumprir, nem suceder assim, esta é palavra que o Senhor não falou; com soberba a falou o tal profeta; não tenhas temor dele.', 'Deuteronômio 18:21-22', 'Deuteronômio', 18, 21, 22),
  ('falar', 'Na angústia, invoquei ao Senhor e clamei ao meu Deus; desde o seu templo ouviu a minha voz e aos seus ouvidos chegou o meu clamor perante a sua face.', 'Salmo 18:6', 'Salmo', 18, 6, NULL),
  ('falar', 'Mas, sobretudo, meus irmãos, não jureis nem pelo céu nem pela terra, nem façais qualquer outro juramento; mas que a vossa palavra seja sim, sim e não, não, para que não caiais em condenação.', 'Tiago 5:12', 'Tiago', 5, 12, NULL),
  ('falar', 'E disse Deus: Haja luz. E houve luz.', 'Gênesis 1:3', 'Gênesis', 1, 3, NULL),
  ('falar', 'Do preceito de seus lábios nunca me apartei e as palavras da sua boca prezei mais do que o meu alimento.', 'Jó 23:12', 'Jó', 23, 12, NULL),
  ('falar', 'Porque a profecia nunca foi produzida por vontade de homem algum, mas os homens santos de Deus falaram inspirados pelo Espírito Santo.', '2 Pedro 1:21', '2 Pedro', 1, 21, NULL),
  ('falar', 'Os lábios mentirosos são abomináveis ao Senhor, mas os que agem fielmente são o seu deleite.', 'Provérbios 12:22', 'Provérbios', 12, 22, NULL),
  ('falar', 'E caí por terra e ouvi uma voz que me dizia: Saulo, Saulo, por que me persegues?', 'Atos 22:7', 'Atos', 22, 7, NULL),
  ('falar', 'E direis, naquele dia: Dai graças ao Senhor, invocai o seu nome, tornai manifestos os seus feitos entre os povos e contai quão excelso é o seu nome.', 'Isaías 12:4', 'Isaías', 12, 4, NULL),
  ('falar', 'As palavras do linguareiro são como doces bocados, e elas descem ao íntimo do ventre.', 'Provérbios 18:8', 'Provérbios', 18, 8, NULL),
  ('falar', 'Eu te louvarei, Senhor, de todo o meu coração; contarei todas as tuas maravilhas.', 'Salmo 9:1', 'Salmo', 9, 1, NULL),
  ('falar', 'E foram vistas por eles línguas repartidas, como que de fogo, as quais pousaram sobre cada um deles. E todos foram cheios do Espírito Santo e começaram a falar em outras línguas, conforme o Espírito Santo lhes concedia que falassem.', 'Atos 2:3-4', 'Atos', 2, 3, 4),
  ('falar', 'E, tendo eles orado, moveu-se o lugar em que estavam reunidos; e todos foram cheios do Espírito Santo e anunciavam com ousadia a palavra de Deus.', 'Atos 4:31', 'Atos', 4, 31, NULL),
  ('falar', 'Vós já estais limpos pela palavra que vos tenho falado.', 'João 15:3', 'João', 15, 3, NULL),
  ('falar', 'Eu, porém, vos digo que, de maneira nenhuma, jureis nem pelo céu, porque é o trono de Deus, nem pela terra, porque é o escabelo de seus pés, nem por Jerusalém, porque é a cidade do grande Rei.', 'Mateus 5:34-35', 'Mateus', 5, 34, 35),
  ('falar', 'Depois disso, ouvi a voz do Senhor, que dizia: A quem enviarei, e quem há de ir por nós? Então, disse eu: eis-me aqui, envia-me a mim.', 'Isaías 6:8', 'Isaías', 6, 8, NULL),
  ('familia', 'E estas palavras que hoje te ordeno estarão no teu coração; e as intimarás a teus filhos e delas falarás assentado em tua casa, e andando pelo caminho, e deitando-te, e levantando-te.', 'Deuteronômio 6:6-7', 'Deuteronômio', 6, 6, 7),
  ('familia', 'E eles disseram: Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa.', 'Atos 16:31', 'Atos', 16, 31, NULL),
  ('familia', 'Rogo-vos, porém, irmãos, pelo nome de nosso Senhor Jesus Cristo, que digais todos uma mesma coisa e que não haja entre vós dissensões; antes, sejais unidos, em um mesmo sentido e em um mesmo parecer.', '1 Coríntios 1:10', '1 Coríntios', 1, 10, NULL),
  ('familia', 'Filho meu, guarda o mandamento de teu pai e não deixes a lei de tua mãe.', 'Provérbios 6:20', 'Provérbios', 6, 20, NULL),
  ('familia', 'Oh! Quão bom e quão suave é que os irmãos vivam em união!', 'Salmo 133:1', 'Salmo', 133, 1, NULL),
  ('familia', 'Se alguém diz: Eu amo a Deus e aborrece a seu irmão, é mentiroso. Pois quem não ama seu irmão, ao qual viu, como pode amar a Deus, a quem não viu?', '1 João 4:20', '1 João', 4, 20, NULL),
  ('familia', 'Mas a misericórdia do Senhor é de eternidade a eternidade sobre aqueles que o temem, e a sua justiça sobre os filhos dos filhos; sobre aqueles que guardam o seu concerto, e sobre os que se lembram dos seus mandamentos para os cumprirem.', 'Salmo 103:17-18', 'Salmo', 103, 17, 18),
  ('familia', 'Pode uma mulher esquecer-se tanto do filho que cria, que se não compadeça dele, do filho do seu ventre? Mas, ainda que esta se esquecesse, eu, todavia, me não esquecerei de ti. Eis que, na palma das minhas mãos, te tenho gravado; os teus muros estão continuamente perante mim.', 'Isaías 49:15-16', 'Isaías', 49, 15, 16),
  ('familia', 'Mas, se alguém não tem cuidado dos seus e principalmente dos da sua família, negou a fé e é pior do que o infiel.', '1 Timóteo 5:8', '1 Timóteo', 5, 8, NULL),
  ('familia', 'Instrui o menino no caminho em que deve andar, e, até quando envelhecer, não se desviará dele.', 'Provérbios 22:6', 'Provérbios', 22, 6, NULL),
  ('familia', 'E vós, pais, não provoqueis a ira a vossos filhos, mas criai-os na doutrina e admoestação do Senhor.', 'Efésios 6:4', 'Efésios', 6, 4, NULL),
  ('familia', 'Honra a teu pai e a tua mãe, para que se prolonguem os teus dias na terra que o Senhor, teu Deus, te dá.', 'Êxodo 20:12', 'Êxodo', 20, 12, NULL),
  ('familia', 'Coroa dos velhos são os filhos dos filhos; e a glória dos filhos são seus pais.', 'Provérbios 17:6', 'Provérbios', 17, 6, NULL),
  ('familia', 'Em todo o tempo ama o amigo; e na angústia nasce o irmão.', 'Provérbios 17:17', 'Provérbios', 17, 17, NULL),
  ('familia', 'O Senhor, nosso Deus, seja conosco, como foi com nossos pais; não nos desampare e não nos deixe.', '1 Reis 8:57', '1 Reis', 8, 57, NULL),
  ('familia', 'O homem que tem muitos amigos pode congratular-se, mas há amigo mais chegado do que um irmão.', 'Provérbios 18:24', 'Provérbios', 18, 24, NULL),
  ('familia', 'Porém, se vos parece mal aos vossos olhos servir ao Senhor, escolhei hoje a quem sirvais: se os deuses a quem serviram vossos pais, que estavam dalém do rio, ou os deuses dos amorreus, em cuja terra habitais; porém eu e a minha casa serviremos ao Senhor.', 'Josué 24:15', 'Josué', 24, 15, NULL),
  ('familia', 'Amados, agora somos filhos de Deus, e ainda não é manifesto o que havemos de ser. Mas sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como é o veremos. E qualquer que nele tem esta esperança purifica-se a si mesmo, como também ele é puro.', '1 João 3:2-3', '1 João', 3, 2, 3),
  ('familia', 'Pois, se vós, sendo maus, sabeis dar boas dádivas aos vossos filhos, quanto mais dará o Pai celestial o Espírito Santo àqueles que lho pedirem?', 'Lucas 11:13', 'Lucas', 11, 13, NULL),
  ('familia', 'Grandemente se regozijará o pai do justo, e o que gerar a um sábio se alegrará nele.', 'Provérbios 23:24', 'Provérbios', 23, 24, NULL),
  ('familia', 'Filho meu, se o teu coração for sábio, alegrar-se-á o meu coração, sim, o meu próprio.', 'Provérbios 23:15', 'Provérbios', 23, 15, NULL),
  ('familia', 'O filho sábio alegra a seu pai, mas o filho louco é a tristeza de sua mãe.', 'Provérbios 10:1', 'Provérbios', 10, 1, NULL),
  ('familia', 'Não abandones o teu amigo, nem o amigo de teu pai, nem entres na casa de teu irmão no dia da tua adversidade; melhor é o vizinho perto do que o irmão longe.', 'Provérbios 27:10', 'Provérbios', 27, 10, NULL),
  ('familia', 'Não matarás, não cometerás adultério, não furtarás, não dirás falso testemunho; honra teu pai e tua mãe, e amarás o teu próximo como a ti mesmo.', 'Mateus 19:18b-19', 'Mateus 19:18b-19', NULL, NULL, NULL),
  ('fe', 'Por isso, vos digo que tudo o que pedirdes, orando, crede que o recebereis e tê-lo-eis.', 'Marcos 11:24', 'Marcos', 11, 24, NULL),
  ('fe', 'Para que, segundo as riquezas da sua glória, vos conceda que sejais corroborados com poder pelo seu Espírito no homem interior; para que Cristo habite, pela fé, no vosso coração; a fim de, estando arraigados e fundados em amor.', 'Efésios 3:16-17', 'Efésios', 3, 16, 17),
  ('fe', 'Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem.', 'Hebreus 11:1', 'Hebreus', 11, 1, NULL),
  ('fe', 'Porque andamos por fé e não por vista.', '2 Coríntios 5:7', '2 Coríntios', 5, 7, NULL),
  ('fe', 'Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo.', 'Romanos 15:13', 'Romanos', 15, 13, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('fe', 'Peça-a, porém, com fé, não duvidando; porque o que duvida é semelhante à onda do mar, que é levada pelo vento e lançada de uma para outra parte.', 'Tiago 1:6', 'Tiago', 1, 6, NULL),
  ('fe', 'Ora, sem fé é impossível agradar-lhe, porque é necessário que aquele que se aproxima de Deus creia que ele existe e que é galardoador dos que o buscam.', 'Hebreus 11:6', 'Hebreus', 11, 6, NULL),
  ('fe', 'Disse-lhe Jesus: Não te hei dito que, se creres, verás a glória de Deus?', 'João 11:40', 'João', 11, 40, NULL),
  ('fe', 'E Jesus disse-lhe: Se tu podes crer; tudo é possível ao que crê.', 'Marcos 9:23', 'Marcos', 9, 23, NULL),
  ('fe', 'Sabendo que a prova da vossa fé produz a paciência.', 'Tiago 1:3', 'Tiago', 1, 3, NULL),
  ('fe', 'Ao qual, não o havendo visto, amais; no qual, não o vendo agora, mas crendo, vos alegrais com gozo inefável e glorioso, alcançando o fim da vossa fé, a salvação da alma.', '1 Pedro 1:8-9', '1 Pedro', 1, 8, 9),
  ('fe', 'E tudo o que pedirdes na oração, crendo, o recebereis.', 'Mateus 21:22', 'Mateus', 21, 22, NULL),
  ('fe', 'Disse-lhe Jesus: Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá; e todo aquele que vive e crê em mim nunca morrerá. Crês tu isso?', 'João 11:25-26', 'João', 11, 25, 26),
  ('fe', 'Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.', '1 João 5:4', '1 João', 5, 4, NULL),
  ('fe', 'Vigiai, estai firmes na fé, portai-vos varonilmente e fortalecei-vos.', '1 Coríntios 16:13', '1 Coríntios', 16, 13, NULL),
  ('fe', 'Ora, quanto ao que está enfermo na fé, recebei-o, não em contendas sobre dúvidas.', 'Romanos 14:1', 'Romanos', 14, 1, NULL),
  ('fe', 'Mas tu, ó homem de Deus, foge destas coisas e segue a justiça, a piedade, a fé, o amor, a paciência, a mansidão.', '1 Timóteo 6:11', '1 Timóteo', 6, 11, NULL),
  ('fe', 'E Jesus lhe disse: Vai, a tua fé te salvou. E logo viu, e seguiu a Jesus pelo caminho.', 'Marcos 10:52', 'Marcos', 10, 52, NULL),
  ('fe', 'E ainda que tivesse o dom de profecia, e conhecesse todos os mistérios e toda a ciência, e ainda que tivesse toda a fé, de maneira tal que transportasse os montes, e não tivesse amor, nada seria.', '1 Coríntios 13:2', '1 Coríntios', 13, 2, NULL),
  ('fe', 'Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor; e a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados.', 'Tiago 5:14-15', 'Tiago', 5, 14, 15),
  ('fe', 'E Jesus lhes disse: Eu sou o pão da vida; aquele que vem a mim não terá fome; e quem crê em mim nunca terá sede.', 'João 6:35', 'João', 6, 35, NULL),
  ('fe', 'Visto que com o coração se crê para a justiça, e com a boca se faz confissão para a salvação.', 'Romanos 10:10', 'Romanos', 10, 10, NULL),
  ('fe', 'Escolhi o caminho da verdade; propus-me seguir os teus juízos.', 'Salmo 119:30', 'Salmo', 119, 30, NULL),
  ('fe', 'Pela fé, também a mesma Sara recebeu a virtude de conceber e deu à luz já fora da idade; porquanto teve por fiel aquele que lho tinha prometido.', 'Hebreus 11:11', 'Hebreus', 11, 11, NULL),
  ('fe', 'Porque nele se descobre a justiça de Deus de fé em fé, como está escrito: Mas o justo viverá da fé.', 'Romanos 1:17', 'Romanos', 1, 17, NULL),
  ('fe', 'Porque todos sois filhos de Deus pela fé em Cristo Jesus; porque todos quantos fostes batizados em Cristo já vos revestistes de Cristo.', 'Gálatas 3:26-27', 'Gálatas', 3, 26, 27),
  ('fe', 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'João', 3, 16, NULL),
  ('fe', 'Agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor.', '1 Coríntios 13:13', '1 Coríntios', 13, 13, NULL),
  ('fe', 'Assim também a fé, se não tiver as obras, é morta em si mesma.', 'Tiago 2:17', 'Tiago', 2, 17, NULL),
  ('fe', 'E Jesus lhes disse: Por causa da vossa pequena fé; porque em verdade vos digo que, se tiverdes fé como um grão de mostarda, direis a este monte: Passa daqui para acolá — e há de passar; e nada vos será impossível.', 'Mateus 17:20', 'Mateus', 17, 20, NULL),
  ('fe', 'Porque a Escritura diz: Todo aquele que nele crer não será confundido.', 'Romanos 10:11', 'Romanos', 10, 11, NULL),
  ('fe', 'De sorte que a fé é pelo ouvir, e o ouvir pela palavra de Deus.', 'Romanos 10:17', 'Romanos', 10, 17, NULL),
  ('fe', 'E eles disseram: Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa.', 'Atos 16:31', 'Atos', 16, 31, NULL),
  ('fe', 'Quem crer e for batizado será salvo; mas quem não crer será condenado.', 'Marcos 16:16', 'Marcos', 16, 16, NULL),
  ('fe', 'Milita a boa milícia da fé, toma posse da vida eterna, para a qual também foste chamado, tendo já feito boa confissão diante de muitas testemunhas.', '1 Timóteo 6:12', '1 Timóteo', 6, 12, NULL),
  ('fe', 'Ninguém despreze a tua mocidade; mas sê o exemplo dos fiéis, na palavra, no trato, no amor, no espírito, na fé, na pureza.', '1 Timóteo 4:12', '1 Timóteo', 4, 12, NULL),
  ('fe', 'Olhando para Jesus, autor e consumador da fé, o qual, pelo gozo que lhe estava proposto, suportou a cruz, desprezando a afronta, e assentou-se à destra do trono de Deus.', 'Hebreus 12:2', 'Hebreus', 12, 2, NULL),
  ('fe', 'E vós também, pondo nisto mesmo toda a diligência, acrescentai à vossa fé a virtude, e à virtude, a ciência, e à ciência, a temperança, e à temperança, a paciência, e à paciência, a piedade, e à piedade, a fraternidade, e à fraternidade, o amor.', '2 Pedro 1:5-7', '2 Pedro', 1, 5, 7),
  ('fe', 'Estas coisas vos escrevi, para que saibais que tendes a vida eterna e para que creiais no nome do Filho de Deus.', '1 João 5:13', '1 João', 5, 13, NULL),
  ('fe', 'Porque pela graça sois salvos, por meio da fé; e isso não vem de vós; é dom de Deus. Não vem das obras, para que ninguém se glorie.', 'Efésios 2:8-9', 'Efésios', 2, 8, 9),
  ('fe', 'Quem crê em mim, como diz a Escritura, rios de água viva correrão do seu ventre.', 'João 7:38', 'João', 7, 38, NULL),
  ('fe', 'Jesus respondeu e disse-lhes: A obra de Deus é esta: que creiais naquele que ele enviou.', 'João 6:29', 'João', 6, 29, NULL),
  ('fe', 'A saber: Se, com a tua boca, confessares ao Senhor Jesus e, em teu coração, creres que Deus o ressuscitou dos mortos, serás salvo.', 'Romanos 10:9', 'Romanos', 10, 9, NULL),
  ('fe', 'Porque em verdade vos digo que qualquer que disser a este monte: Ergue-te e lança-te no mar, e não duvidar em seu coração, mas crer que se fará aquilo que diz, tudo o que disser lhe será feito.', 'Marcos 11:23', 'Marcos', 11, 23, NULL),
  ('fe', 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne vivo-a na fé do Filho de Deus, o qual me amou e se entregou a si mesmo por mim.', 'Gálatas 2:20', 'Gálatas', 2, 20, NULL),
  ('fe', 'Sempre devemos, irmãos, dar graças a Deus por vós, como é de razão, porque a vossa fé cresce muitíssimo, e o amor de cada um de vós aumenta de uns para com os outros.', '2 Tessalonicenses 1:3', '2 Tessalonicenses', 1, 3, NULL),
  ('fe', 'Disse-lhe Jesus: Porque me viste, Tomé, creste; bem-aventurados os que não viram e creram!', 'João 20:29', 'João', 20, 29, NULL),
  ('fe', 'Eis que a sua alma se incha, não é reta nele; mas o justo, pela sua fé, viverá.', 'Habacuque 2:4', 'Habacuque', 2, 4, NULL),
  ('fe', 'Jesus, porém, ouvindo-o, respondeu-lhe, dizendo: Não temas; crê somente, e será salva.', 'Lucas 8:50', 'Lucas', 8, 50, NULL),
  ('fe', 'Jesus, porém, respondendo, disse-lhes: Em verdade vos digo que, se tiverdes fé e não duvidardes, não só fareis o que foi feito à figueira, mas até, se a este monte disserdes: Ergue-te e precipita-te no mar, assim será feito.', 'Mateus 21:21', 'Mateus', 21, 21, NULL),
  ('fe', 'Porque a vós vos foi concedido, em relação a Cristo, não somente crer nele, como também padecer por ele.', 'Filipenses 1:29', 'Filipenses', 1, 29, NULL),
  ('fe', 'Sendo, pois, justificados pela fé, temos paz com Deus por nosso Senhor Jesus Cristo.', 'Romanos 5:1', 'Romanos', 5, 1, NULL),
  ('fe', 'Quem é que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus?', '1 João 5:5', '1 João', 5, 5, NULL),
  ('fe', 'Então, enquanto temos tempo, façamos o bem a todos, mas principalmente aos domésticos da fé.', 'Gálatas 6:10', 'Gálatas', 6, 10, NULL),
  ('fe', 'Mas a Escritura encerrou tudo debaixo do pecado, para que a promessa pela fé em Jesus Cristo fosse dada aos crentes.', 'Gálatas 3:22', 'Gálatas', 3, 22, NULL);

