-- Parte 06: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('fe', 'Porque, pela graça que me é dada, digo a cada um dentre vós que não saiba mais do que convém saber, mas que saiba com temperança, conforme a medida da fé que Deus repartiu a cada um.', 'Romanos 12:3', 'Romanos', 12, 3, NULL),
  ('fe', 'Mas é grande ganho a piedade com contentamento.', '1 Timóteo 6:6', '1 Timóteo', 6, 6, NULL),
  ('fe', 'Porque, se cremos que Jesus morreu e ressuscitou, assim também aos que em Jesus dormem Deus os tornará a trazer com ele.', '1 Tessalonicenses 4:14', '1 Tessalonicenses', 4, 14, NULL),
  ('fe', 'Combati o bom combate, acabei a carreira, guardei a fé. Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele Dia; e não somente a mim, mas também a todos os que amarem a sua vinda.', '2 Timóteo 4:7-8', '2 Timóteo', 4, 7, 8),
  ('fe', 'Mas a todos quantos o receberam deu-lhes o poder de serem feitos filhos de Deus: aos que creem no seu nome.', 'João 1:12', 'João', 1, 12, NULL),
  ('fe', 'Quem és tu que julgas o servo alheio? Para seu próprio senhor ele está em pé ou cai; mas estará firme, porque poderoso é Deus para o firmar.', 'Romanos 14:4', 'Romanos', 14, 4, NULL),
  ('fe', 'Porque não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê, primeiro do judeu e também do grego.', 'Romanos 1:16', 'Romanos', 1, 16, NULL),
  ('fe', 'Porque o fim da lei é Cristo para justiça de todo aquele que crê.', 'Romanos 10:4', 'Romanos', 10, 4, NULL),
  ('fe', 'Também vos notifico, irmãos, o evangelho que já vos tenho anunciado, o qual também recebestes e no qual também permaneceis; pelo qual também sois salvos, se o retiverdes tal como vo-lo tenho anunciado, se não é que crestes em vão.', '1 Coríntios 15:1-2', '1 Coríntios', 15, 1, 2),
  ('fe', 'Nós somos judeus por natureza e não pecadores dentre os gentios. Sabendo que o homem não é justificado pelas obras da lei, mas pela fé em Jesus Cristo, temos também crido em Jesus Cristo, para sermos justificados pela fé de Cristo e não pelas obras da lei, porquanto pelas obras da lei nenhuma carne será justificada.', 'Gálatas 2:15-16', 'Gálatas', 2, 15, 16),
  ('fe', 'Mas, agora, se manifestou, sem a lei, a justiça de Deus, tendo o testemunho da Lei e dos Profetas, isto é, a justiça de Deus pela fé em Jesus Cristo para todos e sobre todos os que creem; porque não há diferença.', 'Romanos 3:21-22', 'Romanos', 3, 21, 22),
  ('fe', 'Porque nos tornamos participantes de Cristo, se retivermos firmemente o princípio da nossa confiança até ao fim.', 'Hebreus 3:14', 'Hebreus', 3, 14, NULL),
  ('fe', 'Porque o amor do dinheiro é a raiz de toda espécie de males; e nessa cobiça alguns se desviaram da fé e se traspassaram a si mesmos com muitas dores.', '1 Timóteo 6:10', '1 Timóteo', 6, 10, NULL),
  ('fe', 'Mas vós, amados, edificando-vos a vós mesmos sobre a vossa santíssima fé, orando no Espírito Santo, conservai a vós mesmos no amor de Deus, esperando a misericórdia de nosso Senhor Jesus Cristo, para a vida eterna.', 'Judas 1:20-21', 'Judas', 1, 20, 21),
  ('fe', 'Porque, em Jesus Cristo, nem a circuncisão nem a incircuncisão têm virtude alguma, mas, sim, a fé que opera por amor.', 'Gálatas 5:6', 'Gálatas', 5, 6, NULL),
  ('fe', 'Porque desejo ver-vos, para vos comunicar algum dom espiritual, a fim de que sejais confortados, isto é, para que juntamente convosco eu seja consolado pela fé mútua, tanto vossa como minha.', 'Romanos 1:11-12', 'Romanos', 1, 11, 12),
  ('fe', 'Na verdade, na verdade vos digo que aquele que crê em mim também fará as obras que eu faço e as fará maiores do que estas, porque eu vou para meu Pai.', 'João 14:12', 'João', 14, 12, NULL),
  ('fe', 'Vede, irmãos, que nunca haja em qualquer de vós um coração mau e infiel, para se apartar do Deus vivo.', 'Hebreus 3:12', 'Hebreus', 3, 12, NULL),
  ('fe', 'E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo e recebido acima, na glória.', '1 Timóteo 3:16', '1 Timóteo', 3, 16, NULL),
  ('fe', 'Aquele que crê no Filho tem a vida eterna, mas aquele que não crê no Filho não verá a vida, mas a ira de Deus sobre ele permanece.', 'João 3:36', 'João', 3, 36, NULL),
  ('fe', 'Quem crê nele não é condenado; mas quem não crê já está condenado, porquanto não crê no nome do unigênito Filho de Deus.', 'João 3:18', 'João', 3, 18, NULL),
  ('fe', 'O tempo está cumprido, e o Reino de Deus está próximo. Arrependei-vos e crede no evangelho.', 'Marcos 1:15', 'Marcos', 1, 15, NULL),
  ('fe', 'Mas Paulo disse: Certamente João batizou com o batismo do arrependimento, dizendo ao povo que cresse no que após ele havia de vir, isto é, em Jesus Cristo.', 'Atos 19:4', 'Atos', 19, 4, NULL),
  ('fe', 'De sorte que foram batizados os que de bom grado receberam a sua palavra; e, naquele dia, agregaram-se quase três mil almas.', 'Atos 2:41', 'Atos', 2, 41, NULL),
  ('fe', 'Foge, também, dos desejos da mocidade; e segue a justiça, a fé, o amor e a paz com os que, com um coração puro, invocam o Senhor.', '2 Timóteo 2:22', '2 Timóteo', 2, 22, NULL),
  ('fe', 'Tu crês que há um só Deus? Fazes bem; também os demônios o creem e estremecem.', 'Tiago 2:19', 'Tiago', 2, 19, NULL),
  ('fe', 'Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça, e calçados os pés na preparação do evangelho da paz; tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno.', 'Efésios 6:14-16', 'Efésios', 6, 14, 16),
  ('fe', 'Examinai-vos a vós mesmos se permaneceis na fé; provai-vos a vós mesmos. Ou não sabeis, quanto a vós mesmos, que Jesus Cristo está em vós? Se não é que já estais reprovados.', '2 Coríntios 13:5', '2 Coríntios', 13, 5, NULL),
  ('fe', 'Pelo que, deixando os rudimentos da doutrina de Cristo, prossigamos até a perfeição, não lançando de novo o fundamento do arrependimento de obras mortas e de fé em Deus, e da doutrina dos batismos, e da imposição das mãos, e da ressurreição dos mortos, e do juízo eterno.', 'Hebreus 6:1-2', 'Hebreus', 6, 1, 2),
  ('fe', 'A este dão testemunho todos os profetas, de que todos os que nele creem receberão o perdão dos pecados pelo seu nome.', 'Atos 10:43', 'Atos', 10, 43, NULL),
  ('fiel', 'As misericórdias do Senhor', 'Lamentações 3:22-23', 'Lamentações', 3, 22, 23),
  ('fiel', 'Mas fiel é o Senhor, que vos confortará e guardará do maligno.', '2 Tessalonicenses 3:3', '2 Tessalonicenses', 3, 3, NULL),
  ('fiel', 'Fiel é o que vos chama, o qual também o fará.', '1 Tessalonicenses 5:24', '1 Tessalonicenses', 5, 24, NULL),
  ('fiel', 'Não te desamparem a benignidade e a fidelidade; ata-as ao teu pescoço; escreve-as na tábua do teu coração e acharás graça e bom entendimento aos olhos de Deus e dos homens.', 'Provérbios 3:3-4', 'Provérbios', 3, 3, 4),
  ('fiel', 'Retenhamos firmes a confissão da nossa esperança, porque fiel é o que prometeu.', 'Hebreus 10:23', 'Hebreus', 10, 23, NULL),
  ('fiel', 'Saberás, pois, que o Senhor', 'Deuteronômio 7:9', 'Deuteronômio', 7, 9, NULL),
  ('fiel', 'Ó Senhor', 'Isaías 25:1', 'Isaías', 25, 1, NULL),
  ('fiel', 'Ele te cobrirá com as suas penas, e debaixo das suas asas estarás seguro; a sua verdade é escudo e broquel.', 'Salmo 91:4', 'Salmo', 91, 4, NULL),
  ('fiel', 'Louvai ao Senhor', '1 Crônicas 16:34', '1 Crônicas', 16, 34, NULL),
  ('fiel', 'Não veio sobre vós tentação, senão humana; mas fiel é Deus, que vos não deixará tentar acima do que podeis; antes, com a tentação dará também o escape, para que a possais suportar.', '1 Coríntios 10:13', '1 Coríntios', 10, 13, NULL),
  ('fiel', 'Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo, nosso Senhor.', '1 Coríntios 1:9', '1 Coríntios', 1, 9, NULL),
  ('fiel', 'Ora, o Senhor encaminhe o vosso coração no amor de Deus e na paciência de Cristo.', '2 Tessalonicenses 3:5', '2 Tessalonicenses', 3, 5, NULL),
  ('fiel', 'Para que guarde as veredas do juízo e conserve o caminho dos seus santos.', 'Provérbios 2:8', 'Provérbios', 2, 8, NULL),
  ('fiel', 'Justo é o Senhor', 'Salmo 145:17', 'Salmo', 145, 17, NULL),
  ('fiel', 'Mas a misericórdia do Senhor', 'Salmo 103:17-18', 'Salmo', 103, 17, 18),
  ('fiel', 'Não a nós, Senhor', 'Salmo 115:1', 'Salmo', 115, 1, NULL),
  ('fiel', 'O Senhor', 'Salmo 138:8', 'Salmo', 138, 8, NULL),
  ('fiel', 'Ó Senhor', 'Salmo 143:1', 'Salmo', 143, 1, NULL),
  ('fiel', 'Porque o Senhor', 'Salmo 37:28', 'Salmo', 37, 28, NULL),
  ('fiel', 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.', '1 João 1:9', '1 João', 1, 9, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('fiel', 'Não detenhas para comigo, Senhor', 'Salmo 40:11', 'Salmo', 40, 11, NULL),
  ('fiel', 'Eis que a sua alma se incha, não é reta nele; mas o justo, pela sua fé, viverá.', 'Habacuque 2:4', 'Habacuque', 2, 4, NULL),
  ('fiel', 'Vós que amais ao Senhor', 'Salmo 97:10', 'Salmo', 97, 10, NULL),
  ('fim-dos-tempos', 'Ninguém, de maneira alguma, vos engane, porque não será assim sem que antes venha a apostasia e se manifeste o homem do pecado, o filho da perdição, o qual se opõe e se levanta contra tudo o que se chama Deus ou se adora; de sorte que se assentará, como Deus, no templo de Deus, querendo parecer Deus.', '2 Tessalonicenses 2:3-4', '2 Tessalonicenses', 2, 3, 4),
  ('fim-dos-tempos', 'Os quais vos diziam que, no último tempo, haveria escarnecedores que andariam segundo as suas ímpias concupiscências. Estes são os que causam divisões, sensuais, que não têm o Espírito.', 'Judas 1:18-19', 'Judas', 1, 18, 19),
  ('fim-dos-tempos', 'Por isso, estai vós apercebidos também, porque o Filho do Homem há de vir à hora em que não penseis.', 'Mateus 24:44', 'Mateus', 24, 44, NULL),
  ('fim-dos-tempos', 'Porque o mesmo Senhor descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus; e os que morreram em Cristo ressuscitarão primeiro; depois, nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o Senhor nos ares, e assim estaremos sempre com o Senhor.', '1 Tessalonicenses 4:16-17', '1 Tessalonicenses', 4, 16, 17),
  ('fim-dos-tempos', 'E já está próximo o fim de todas as coisas; portanto, sede sóbrios e vigiai em oração.', '1 Pedro 4:7', '1 Pedro', 4, 7, NULL),
  ('fim-dos-tempos', 'E eis que cedo venho, e o meu galardão está comigo para dar a cada um segundo a sua obra.', 'Apocalipse 22:12', 'Apocalipse', 22, 12, NULL),
  ('fim-dos-tempos', 'Muitos serão purificados, e embranquecidos, e provados; mas os ímpios procederão impiamente, e nenhum dos ímpios entenderá, mas os sábios entenderão.', 'Daniel 12:10', 'Daniel', 12, 10, NULL),
  ('fim-dos-tempos', 'E este evangelho do Reino será pregado em todo o mundo, em testemunho a todas as gentes, e então virá o fim.', 'Mateus 24:14', 'Mateus', 24, 14, NULL),
  ('fim-dos-tempos', 'O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se.', '2 Pedro 3:9', '2 Pedro', 3, 9, NULL),
  ('fim-dos-tempos', 'Mas aquele que perseverar até ao fim será salvo.', 'Mateus 24:13', 'Mateus', 24, 13, NULL),
  ('fim-dos-tempos', 'Não durmamos, pois, como os demais, mas vigiemos e sejamos sóbrios.', '1 Tessalonicenses 5:6', '1 Tessalonicenses', 5, 6, NULL),
  ('fim-dos-tempos', 'E consideremo-nos uns aos outros, para nos estimularmos ao amor e às boas obras, não deixando a nossa congregação, como é costume de alguns; antes, admoestando-nos uns aos outros; e tanto mais quanto vedes que se vai aproximando aquele Dia.', 'Hebreus 10:24-25', 'Hebreus', 10, 24, 25),
  ('fim-dos-tempos', 'Portanto, se vos disserem: Eis que ele está no deserto, não saiais; ou: Eis que ele está no interior da casa, não acrediteis. Porque, assim como o relâmpago sai do oriente e se mostra até ao ocidente, assim será também a vinda do Filho do Homem.', 'Mateus 24:26-27', 'Mateus', 24, 26, 27),
  ('fim-dos-tempos', 'Aquele que testifica estas coisas diz: Certamente, cedo venho. Amém! Ora, vem, Senhor Jesus!', 'Apocalipse 22:20', 'Apocalipse', 22, 20, NULL),
  ('fim-dos-tempos', 'Vigiai, pois, porque não sabeis a que hora há de vir o vosso Senhor.', 'Mateus 24:42', 'Mateus', 24, 42, NULL),
  ('fim-dos-tempos', 'E eles serão meus, diz o Senhor', 'Malaquias 3:17', 'Malaquias', 3, 17, NULL),
  ('fim-dos-tempos', 'O céu e a terra passarão, mas as minhas palavras não hão de passar.', 'Mateus 24:35', 'Mateus', 24, 35, NULL),
  ('fim-dos-tempos', 'E agora, filhinhos, permanecei nele, para que, quando ele se manifestar, tenhamos confiança e não sejamos confundidos por ele na sua vinda.', '1 João 2:28', '1 João', 2, 28, NULL),
  ('fim-dos-tempos', 'Mas, amados, não ignoreis uma coisa: que um dia para o Senhor é como mil anos, e mil anos, como um dia.', '2 Pedro 3:8', '2 Pedro', 3, 8, NULL),
  ('fim-dos-tempos', 'Mas o Dia do Senhor virá como o ladrão de noite, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se desfarão, e a terra e as obras que nela há se queimarão.', '2 Pedro 3:10', '2 Pedro', 3, 10, NULL),
  ('fofoca', 'O homem perverso levanta a contenda, e o difamador separa os maiores amigos.', 'Provérbios 16:28', 'Provérbios', 16, 28, NULL),
  ('fofoca', 'Aquele que anda em sinceridade, e pratica a justiça, e fala verazmente segundo o seu coração; aquele que não difama com a sua língua, nem faz mal ao seu próximo, nem aceita nenhuma afronta contra o seu próximo.', 'Salmo 15:2-3', 'Salmo', 15, 2, 3),
  ('fofoca', 'O que anda praguejando descobre o segredo, mas o fiel de espírito encobre o negócio.', 'Provérbios 11:13', 'Provérbios', 11, 13, NULL),
  ('fofoca', 'Não saia da vossa boca nenhuma palavra torpe, mas só a que for boa para promover a edificação, para que dê graça aos que a ouvem.', 'Efésios 4:29', 'Efésios', 4, 29, NULL),
  ('fofoca', 'O hipócrita, com a boca, danifica o seu próximo, mas os justos são libertados pelo conhecimento.', 'Provérbios 11:9', 'Provérbios', 11, 9, NULL),
  ('fofoca', 'O que encobre o ódio tem lábios falsos, e o que difama é um insensato.', 'Provérbios 10:18', 'Provérbios', 10, 18, NULL),
  ('fofoca', 'Bem-aventurados sois vós quando vos injuriarem, e perseguirem, e, mentindo, disserem todo o mal contra vós, por minha causa.', 'Mateus 5:11', 'Mateus', 5, 11, NULL),
  ('fofoca', 'Não sabeis que os injustos não hão de herdar o Reino de Deus? Não erreis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas, nem os ladrões, nem os avarentos, nem os bêbados, nem os maldizentes, nem os roubadores herdarão o Reino de Deus.', '1 Coríntios 6:9-10', '1 Coríntios', 6, 9, 10),
  ('fofoca', 'Guarda a tua língua do mal e os teus lábios, de falarem enganosamente.', 'Salmo 34:13', 'Salmo', 34, 13, NULL),
  ('fofoca', 'Uma língua saudável é árvore de vida, mas a perversidade nela quebranta o espírito.', 'Provérbios 15:4', 'Provérbios', 15, 4, NULL),
  ('fofoca', 'As palavras do linguareiro são como doces bocados, e elas descem ao íntimo do ventre.', 'Provérbios 18:8', 'Provérbios', 18, 8, NULL),
  ('forca', 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te esforço, e te ajudo, e te sustento com a destra da minha justiça.', 'Isaías 41:10', 'Isaías', 41, 10, NULL),
  ('forca', 'Mas os que esperam no Senhor', 'Isaías 40:31', 'Isaías', 40, 31, NULL),
  ('forca', 'A minha carne e o meu coração desfalecem; mas Deus é a fortaleza do meu coração e a minha porção para sempre.', 'Salmo 73:26', 'Salmo', 73, 26, NULL),
  ('forca', 'Posso todas as coisas naquele que me fortalece.', 'Filipenses 4:13', 'Filipenses', 4, 13, NULL),
  ('forca', 'Dá vigor ao cansado e multiplica as forças ao que não tem nenhum vigor.', 'Isaías 40:29', 'Isaías', 40, 29, NULL),
  ('forca', 'Pelo que sinto prazer nas fraquezas, nas injúrias, nas necessidades, nas perseguições, nas angústias, por amor de Cristo. Porque, quando estou fraco, então, sou forte.', '2 Coríntios 12:10', '2 Coríntios', 12, 10, NULL),
  ('forca', 'Eu te amarei do coração, ó Senhor', 'Salmo 18:1-2', 'Salmo', 18, 1, 2),
  ('forca', 'Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', '2 Timóteo 1:7', '2 Timóteo', 1, 7, NULL),
  ('forca', 'Buscai o Senhor', '1 Crônicas 16:11', '1 Crônicas', 16, 11, NULL),
  ('forca', 'Mas fiel é o Senhor, que vos confortará e guardará do maligno.', '2 Tessalonicenses 3:3', '2 Tessalonicenses', 3, 3, NULL),
  ('forca', 'Vigiai, estai firmes na fé, portai-vos varonilmente e fortalecei-vos.', '1 Coríntios 16:13', '1 Coríntios', 16, 13, NULL),
  ('forca', 'Eu, porém, cantarei a tua força; pela manhã, louvarei com alegria a tua misericórdia, porquanto tu foste o meu alto refúgio e proteção no dia da minha angústia.', 'Salmo 59:16', 'Salmo', 59, 16, NULL),
  ('forca', 'O Senhor', 'Salmo 28:7', 'Salmo', 28, 7, NULL),
  ('forca', 'Ah! Senhor Jeová', 'Jeremias 32:17', 'Jeremias', 32, 17, NULL),
  ('forca', 'Jeová', 'Habacuque 3:19', 'Habacuque', 3, 19, NULL),
  ('forca', 'No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder.', 'Efésios 6:10', 'Efésios', 6, 10, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('forca', 'Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera, a esse glória na igreja, por Jesus Cristo, em todas as gerações, para todo o sempre. Amém!', 'Efésios 3:20-21', 'Efésios', 3, 20, 21),
  ('forca', 'Porque a palavra de Deus é viva, e eficaz, e mais penetrante do que qualquer espada de dois gumes, e penetra até à divisão da alma, e do espírito, e das juntas e medulas, e é apta para discernir os pensamentos e intenções do coração.', 'Hebreus 4:12', 'Hebreus', 4, 12, NULL),
  ('forca', 'Amarás, pois, ao Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todo o teu entendimento, e de todas as tuas forças; este é o primeiro mandamento.', 'Marcos 12:30', 'Marcos', 12, 30, NULL),
  ('forca', 'Tua é, Senhor', '1 Crônicas 29:11', '1 Crônicas', 29, 11, NULL),
  ('forca', 'Esta é a palavra do Senhor', 'Zacarias 4:6', 'Zacarias', 4, 6, NULL),
  ('forca', 'E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. De boa vontade, pois, me gloriarei nas minhas fraquezas, para que em mim habite o poder de Cristo.', '2 Coríntios 12:9', '2 Coríntios', 12, 9, NULL),
  ('forca', 'O Senhor', 'Salmo 29:11', 'Salmo', 29, 11, NULL),
  ('forca', 'Porque a palavra da cruz é loucura para os que perecem; mas para nós, que somos salvos, é o poder de Deus.', '1 Coríntios 1:18', '1 Coríntios', 1, 18, NULL),
  ('forca', 'Pois não conquistaram a terra pela sua espada, nem o seu braço os salvou, e sim a tua destra, e o teu braço, e a luz da tua face, porquanto te agradaste deles.', 'Salmo 44:3', 'Salmo', 44, 3, NULL),
  ('forca', 'Porque, quem é Deus senão o Senhor', 'Salmo 18:31', 'Salmo', 18, 31, NULL),
  ('forca', 'Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder como a sua divindade, se entendem e claramente se veem pelas coisas que estão criadas, para que eles fiquem inescusáveis.', 'Romanos 1:20', 'Romanos', 1, 20, NULL),
  ('forca', 'Tu, pois, meu filho, fortifica-te na graça que há em Cristo Jesus.', '2 Timóteo 2:1', '2 Timóteo', 2, 1, NULL),
  ('forca', 'Porque nele habita corporalmente toda a plenitude da divindade. E estais perfeitos nele, que é a cabeça de todo principado e potestade.', 'Colossenses 2:9-10', 'Colossenses', 2, 9, 10),
  ('forca', 'E, se alguém quiser prevalecer contra um, os dois lhe resistirão; e o cordão de três dobras não se quebra tão depressa.', 'Eclesiastes 4:12', 'Eclesiastes', 4, 12, NULL),
  ('forca', 'E riquezas e glória vêm de diante de ti, e tu dominas sobre tudo, e na tua mão há força e poder; e na tua mão está o engrandecer e dar força a tudo.', '1 Crônicas 29:12', '1 Crônicas', 29, 12, NULL),
  ('forca', 'Quem operou e fez isso, chamando as gerações desde o princípio? Eu, o Senhor', 'Isaías 41:4', 'Isaías', 41, 4, NULL),
  ('forca', 'Visto como o seu divino poder nos deu tudo o que diz respeito à vida e piedade, pelo conhecimento daquele que nos chamou por sua glória e virtude.', '2 Pedro 1:3', '2 Pedro', 1, 3, NULL),
  ('forca', 'Ao Todo-Poderoso não podemos alcançar; grande é em poder; porém a ninguém oprime em juízo e grandeza de justiça.', 'Jó 37:23', 'Jó', 37, 23, NULL),
  ('forca', 'Porque desejo ver-vos, para vos comunicar algum dom espiritual, a fim de que sejais confortados, isto é, para que juntamente convosco eu seja consolado pela fé mútua, tanto vossa como minha.', 'Romanos 1:11-12', 'Romanos', 1, 11, 12),
  ('forca', 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas tanto em Jerusalém como em toda a Judeia e Samaria e até aos confins da terra.', 'Atos 1:8', 'Atos', 1, 8, NULL),
  ('forca', 'E fortalecerei a casa de Judá, e salvarei a casa de José, e tornarei a plantá-los, porque me apiedei deles; e serão como se os não tivera rejeitado; porque eu sou o Senhor', 'Zacarias 10:6', 'Zacarias', 10, 6, NULL),
  ('forca', 'E que amá-lo de todo o coração, e de todo o entendimento, e de toda a alma, e de todas as forças e amar o próximo como a si mesmo é mais do que todos os holocaustos e sacrifícios.', 'Marcos 12:33', 'Marcos', 12, 33, NULL),
  ('forca', 'E, respondendo o anjo, disse-lhe: Descerá sobre ti o Espírito Santo, e a virtude do Altíssimo te cobrirá com a sua sombra; pelo que também o Santo, que de ti há de nascer, será chamado Filho de Deus.', 'Lucas 1:35', 'Lucas', 1, 35, NULL),
  ('forca', 'O Senhor', 'Naum 1:3', 'Naum', 1, 3, NULL),
  ('fraqueza', 'Pelo que sinto prazer nas fraquezas, nas injúrias, nas necessidades, nas perseguições, nas angústias, por amor de Cristo. Porque, quando estou fraco, então, sou forte.', '2 Coríntios 12:10', '2 Coríntios', 12, 10, NULL),
  ('fraqueza', 'E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. De boa vontade, pois, me gloriarei nas minhas fraquezas, para que em mim habite o poder de Cristo.', '2 Coríntios 12:9', '2 Coríntios', 12, 9, NULL),
  ('fraqueza', 'A minha carne e o meu coração desfalecem; mas Deus é a fortaleza do meu coração e a minha porção para sempre.', 'Salmo 73:26', 'Salmo', 73, 26, NULL),
  ('fraqueza', 'Dá vigor ao cansado e multiplica as forças ao que não tem nenhum vigor.', 'Isaías 40:29', 'Isaías', 40, 29, NULL),
  ('fraqueza', 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.', '1 Pedro 5:7', '1 Pedro', 5, 7, NULL),
  ('fraqueza', 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.', 'Mateus 11:28', 'Mateus', 11, 28, NULL),
  ('fraqueza', 'E da mesma maneira também o Espírito ajuda as nossas fraquezas; porque não sabemos o que havemos de pedir como convém, mas o mesmo Espírito intercede por nós com gemidos inexprimíveis.', 'Romanos 8:26', 'Romanos', 8, 26, NULL),
  ('fraqueza', 'Posso todas as coisas naquele que me fortalece.', 'Filipenses 4:13', 'Filipenses', 4, 13, NULL),
  ('fraqueza', 'Vigiai e orai, para que não entreis em tentação; na verdade, o espírito está pronto, mas a carne é fraca.', 'Mateus 26:41', 'Mateus', 26, 41, NULL),
  ('fraqueza', 'Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', '2 Timóteo 1:7', '2 Timóteo', 1, 7, NULL),
  ('fraqueza', 'Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado.', 'Hebreus 4:15', 'Hebreus', 4, 15, NULL),
  ('fraqueza', 'O coração alegre serve de bom remédio, mas o espírito abatido virá a secar os ossos.', 'Provérbios 17:22', 'Provérbios', 17, 22, NULL),
  ('fraqueza', 'Abre a tua boca a favor do mudo, pelo direito de todos os que se acham em desolação.', 'Provérbios 31:8', 'Provérbios', 31, 8, NULL),
  ('fraqueza', 'Defendei o pobre e o órfão; fazei justiça ao aflito e necessitado.', 'Salmo 82:3', 'Salmo', 82, 3, NULL),
  ('fraqueza', 'Um abismo chama outro abismo, ao ruído das tuas catadupas; todas as tuas ondas e vagas têm passado sobre mim.', 'Salmo 42:7', 'Salmo', 42, 7, NULL),
  ('frutos', 'Bendito o varão que confia no Senhor', 'Jeremias 17:7-8', 'Jeremias', 17, 7, 8),
  ('frutos', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('frutos', 'Não me escolhestes vós a mim, mas eu vos escolhi a vós, e vos nomeei, para que vades e deis fruto, e o vosso fruto permaneça, a fim de que tudo quanto em meu nome pedirdes ao Pai ele vos conceda.', 'João 15:16', 'João', 15, 16, NULL),
  ('frutos', 'Produzi, pois, frutos dignos de arrependimento.', 'Mateus 3:8', 'Mateus', 3, 8, NULL),
  ('frutos', 'Eu sou a videira, vós, as varas; quem está em mim, e eu nele, este dá muito fruto, porque sem mim nada podereis fazer.', 'João 15:5', 'João', 15, 5, NULL),
  ('frutos', 'Nisto é glorificado meu Pai: que deis muito fruto; e assim sereis meus discípulos.', 'João 15:8', 'João', 15, 8, NULL),
  ('frutos', 'E o que foi semeado entre espinhos é o que ouve a palavra, mas os cuidados deste mundo e a sedução das riquezas sufocam a palavra, e fica infrutífera.', 'Mateus 13:22', 'Mateus', 13, 22, NULL),
  ('frutos', 'Se andardes nos meus estatutos, e guardardes os meus mandamentos, e os fizerdes, então, eu vos darei as vossas chuvas a seu tempo; e a terra dará a sua novidade, e a árvore do campo dará o seu fruto.', 'Levítico 26:3-4', 'Levítico', 26, 3, 4),
  ('frutos', 'Ora, o fruto da justiça semeia-se na paz, para os que exercitam a paz.', 'Tiago 3:18', 'Tiago', 3, 18, NULL),
  ('frutos', 'Porquanto, ainda que a figueira não floresça, nem haja fruto na vide; o produto da oliveira minta, e os campos não produzam mantimento; as ovelhas da malhada sejam arrebatadas, e nos currais não haja vacas, todavia, eu me alegrarei no Senhor', 'Habacuque 3:17-18', 'Habacuque', 3, 17, 18),
  ('frutos', 'A morte e a vida estão no poder da língua; e aquele que a ama comerá do seu fruto.', 'Provérbios 18:21', 'Provérbios', 18, 21, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('frutos', 'Assim será a palavra que sair da minha boca; ela não voltará para mim vazia; antes, fará o que me apraz e prosperará naquilo para que a enviei.', 'Isaías 55:11', 'Isaías', 55, 11, NULL),
  ('frutos', 'E não comuniqueis com as obras infrutuosas das trevas, mas, antes, condenai-as. Porque o que eles fazem em oculto, até dizê-lo é torpe.', 'Efésios 5:11-12', 'Efésios', 5, 11, 12),
  ('frutos', 'E, na verdade, toda correção, ao presente, não parece ser de gozo, senão de tristeza, mas, depois, produz um fruto pacífico de justiça nos exercitados por ela.', 'Hebreus 12:11', 'Hebreus', 12, 11, NULL),
  ('frutos', 'E Deus os abençoou e Deus lhes disse: Frutificai, e multiplicai-vos, e enchei a terra, e sujeitai-a; e dominai sobre os peixes do mar, e sobre as aves dos céus, e sobre todo o animal que se move sobre a terra.', 'Gênesis 1:28', 'Gênesis', 1, 28, NULL),
  ('frutos', 'E disse Deus: Eis que vos tenho dado toda erva que dá semente e que está sobre a face de toda a terra e toda árvore em que há fruto de árvore que dá semente; ser-vos-ão para mantimento.', 'Gênesis 1:29', 'Gênesis', 1, 29, NULL),
  ('frutos', 'Eu sou a videira verdadeira, e meu Pai é o lavrador. Toda vara em mim que não dá fruto, a tira; e limpa toda aquela que dá fruto, para que dê mais fruto.', 'João 15:1-2', 'João', 15, 1, 2),
  ('frutos', 'Pela fé, também a mesma Sara recebeu a virtude de conceber e deu à luz já fora da idade; porquanto teve por fiel aquele que lho tinha prometido.', 'Hebreus 11:11', 'Hebreus', 11, 11, NULL),
  ('ganancia', 'O que amar o dinheiro nunca se fartará de dinheiro; e quem amar a abundância nunca se fartará da renda; também isso é vaidade.', 'Eclesiastes 5:10', 'Eclesiastes', 5, 10, NULL),
  ('ganancia', 'Mas os que querem ser ricos caem em tentação, e em laço, e em muitas concupiscências loucas e nocivas, que submergem os homens na perdição e ruína.', '1 Timóteo 6:9', '1 Timóteo', 6, 9, NULL),
  ('ganancia', 'E disse-lhes: Acautelai-vos e guardai-vos da avareza, porque a vida de qualquer não consiste na abundância do que possui.', 'Lucas 12:15', 'Lucas', 12, 15, NULL),
  ('ganancia', 'Porque o amor do dinheiro é a raiz de toda espécie de males; e nessa cobiça alguns se desviaram da fé e se traspassaram a si mesmos com muitas dores.', '1 Timóteo 6:10', '1 Timóteo', 6, 10, NULL),
  ('ganancia', 'Pois que aproveitaria ao homem ganhar todo o mundo e perder a sua alma?', 'Marcos 8:36', 'Marcos', 8, 36, NULL),
  ('ganancia', 'Não ajunteis tesouros na terra, onde a traça e a ferrugem tudo consomem, e onde os ladrões minam e roubam. Mas ajuntai tesouros no céu, onde nem a traça nem a ferrugem consomem, e onde os ladrões não minam, nem roubam.', 'Mateus 6:19-20', 'Mateus', 6, 19, 20),
  ('ganancia', 'Todo o dia avidamente cobiça, mas o justo dá e nada retém.', 'Provérbios 21:26', 'Provérbios', 21, 26, NULL),
  ('ganancia', 'A fazenda que procede da vaidade diminuirá, mas quem a ajunta pelo trabalho terá aumento.', 'Provérbios 13:11', 'Provérbios', 13, 11, NULL),
  ('ganancia', 'Como saiu do ventre de sua mãe, assim nu voltará, indo-se como veio; e nada tomará do seu trabalho, que possa levar na sua mão.', 'Eclesiastes 5:15', 'Eclesiastes', 5, 15, NULL),
  ('ganancia', 'Não te canses para enriqueceres; dá de mão à tua própria sabedoria.', 'Provérbios 23:4', 'Provérbios', 23, 4, NULL),
  ('ganancia', 'Ninguém pode servir a dois senhores, porque ou há de odiar um e amar o outro ou se dedicará a um e desprezará o outro. Não podeis servir a Deus e a Mamom.', 'Mateus 6:24', 'Mateus', 6, 24, NULL),
  ('ganancia', 'Inclina o meu coração a teus testemunhos e não à cobiça.', 'Salmo 119:36', 'Salmo', 119, 36, NULL),
  ('ganancia', 'Mortificai, pois, os vossos membros que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência e a avareza, que é idolatria.', 'Colossenses 3:5', 'Colossenses', 3, 5, NULL),
  ('ganancia', 'Não sabeis que os injustos não hão de herdar o Reino de Deus? Não erreis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas, nem os ladrões, nem os avarentos, nem os bêbados, nem os maldizentes, nem os roubadores herdarão o Reino de Deus.', '1 Coríntios 6:9-10', '1 Coríntios', 6, 9, 10),
  ('ganancia', 'Não cobiçarás a casa do teu próximo; não cobiçarás a mulher do teu próximo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma do teu próximo.', 'Êxodo 20:17', 'Êxodo', 20, 17, NULL),
  ('ganancia', 'Mas a prostituição e toda impureza ou avareza nem ainda se nomeiem entre vós, como convém a santos.', 'Efésios 5:3', 'Efésios', 5, 3, NULL),
  ('ganancia', 'Por esta razão também pagais tributos, porque são ministros de Deus, atendendo sempre a isto mesmo.', 'Romanos 13:6', 'Romanos', 13, 6, NULL),
  ('ganancia', 'A candeia do corpo são os olhos; de sorte que, se os teus olhos forem bons, todo o teu corpo terá luz. Se, porém, os teus olhos forem maus, o teu corpo será tenebroso. Se, portanto, a luz que em ti há são trevas, quão grandes serão tais trevas!', 'Mateus 6:22-23', 'Mateus', 6, 22, 23),
  ('generosidade', 'A alma generosa engordará, e o que regar também será regado.', 'Provérbios 11:25', 'Provérbios', 11, 25, NULL),
  ('generosidade', 'Cada um contribua segundo propôs no seu coração, não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria.', '2 Coríntios 9:7', '2 Coríntios', 9, 7, NULL),
  ('generosidade', 'Para que em tudo enriqueçais para toda a beneficência, a qual faz que por nós se deem graças a Deus.', '2 Coríntios 9:11', '2 Coríntios', 9, 11, NULL),
  ('generosidade', 'Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando vos darão; porque com a mesma medida com que medirdes também vos medirão de novo.', 'Lucas 6:38', 'Lucas', 6, 38, NULL),
  ('generosidade', 'Porque, se há prontidão de vontade, será aceita segundo o que qualquer tem e não segundo o que não tem.', '2 Coríntios 8:12', '2 Coríntios', 8, 12, NULL),
  ('generosidade', 'Bem irá ao homem que se compadece e empresta; disporá as suas coisas com juízo.', 'Salmo 112:5', 'Salmo', 112, 5, NULL),
  ('generosidade', 'Ora, aquele que dá a semente ao que semeia e pão para comer também multiplicará a vossa sementeira e aumentará os frutos da vossa justiça.', '2 Coríntios 9:10', '2 Coríntios', 9, 10, NULL),
  ('generosidade', 'E dá a qualquer que te pedir; e ao que tomar o que é teu, não lho tornes a pedir.', 'Lucas 6:30', 'Lucas', 6, 30, NULL),
  ('generosidade', 'E digo isto: Que o que semeia pouco pouco também ceifará; e o que semeia em abundância em abundância também ceifará.', '2 Coríntios 9:6', '2 Coríntios', 9, 6, NULL),
  ('generosidade', 'Dá vigor ao cansado e multiplica as forças ao que não tem nenhum vigor.', 'Isaías 40:29', 'Isaías', 40, 29, NULL),
  ('generosidade', 'E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada.', 'Tiago 1:5', 'Tiago', 1, 5, NULL),
  ('generosidade', 'Pois, se vós, sendo maus, sabeis dar boas dádivas aos vossos filhos, quanto mais dará o Pai celestial o Espírito Santo àqueles que lho pedirem?', 'Lucas 11:13', 'Lucas', 11, 13, NULL),
  ('gentileza', 'Seja a vossa equidade notória a todos os homens. Perto está o Senhor.', 'Filipenses 4:5', 'Filipenses', 4, 5, NULL),
  ('gentileza', 'Revesti-vos, pois, como eleitos de Deus, santos e amados, de entranhas de misericórdia, de benignidade, humildade, mansidão, longanimidade.', 'Colossenses 3:12', 'Colossenses', 3, 12, NULL),
  ('gentileza', 'A resposta branda desvia o furor, mas a palavra dura suscita a ira.', 'Provérbios 15:1', 'Provérbios', 15, 1, NULL),
  ('gentileza', 'Favo de mel são as palavras suaves: doces para a alma e saúde para os ossos.', 'Provérbios 16:24', 'Provérbios', 16, 24, NULL),
  ('gentileza', 'Andai com sabedoria para com os que estão de fora, remindo o tempo. A vossa palavra seja sempre agradável, temperada com sal, para que saibais como vos convém responder a cada um.', 'Colossenses 4:5-6', 'Colossenses', 4, 5, 6),
  ('gentileza', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('gentileza', 'Não aborrecerás a teu irmão no teu coração; não deixarás de repreender o teu próximo e nele não sofrerás pecado. Não te vingarás, nem guardarás ira contra os filhos do teu povo; mas amarás o teu próximo como a ti mesmo. Eu sou o Senhor', 'Levítico 19:17-18', 'Levítico', 19, 17, 18),
  ('gentileza', 'Assim que não nos julguemos mais uns aos outros; antes, seja o vosso propósito não pôr tropeço ou escândalo ao irmão.', 'Romanos 14:13', 'Romanos', 14, 13, NULL),
  ('gentileza', 'Então, enquanto temos tempo, façamos o bem a todos, mas principalmente aos domésticos da fé.', 'Gálatas 6:10', 'Gálatas', 6, 10, NULL),
  ('gentileza', 'Permaneça o amor fraternal. Não vos esqueçais da hospitalidade, porque, por ela, alguns, não o sabendo, hospedaram anjos.', 'Hebreus 13:1-2', 'Hebreus', 13, 1, 2),
  ('gentileza', 'Assim falou o Senhor', 'Zacarias 7:9-10', 'Zacarias', 7, 9, 10),
  ('gentileza', 'Na verdade, na verdade vos digo que se alguém receber o que eu enviar, me recebe a mim, e quem me recebe a mim recebe aquele que me enviou.', 'João 13:20', 'João', 13, 20, NULL),
  ('graca', 'Cheguemos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno.', 'Hebreus 4:16', 'Hebreus', 4, 16, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('graca', 'O Senhor', 'Números 6:24-26', 'Números', 6, 24, 26),
  ('graca', 'Mas Deus, que é riquíssimo em misericórdia, pelo seu muito amor com que nos amou, estando nós ainda mortos em nossas ofensas, nos vivificou juntamente com Cristo (pela graça sois salvos).', 'Efésios 2:4-5', 'Efésios', 2, 4, 5),
  ('graca', 'E o Deus de toda a graça, que em Cristo Jesus vos chamou à sua eterna glória, depois de haverdes padecido um pouco, ele mesmo vos aperfeiçoará, confirmará, fortificará e fortalecerá.', '1 Pedro 5:10', '1 Pedro', 5, 10, NULL),
  ('graca', 'Misericordioso e piedoso é o Senhor', 'Salmo 103:8', 'Salmo', 103, 8, NULL),
  ('graca', 'Porque a graça de Deus se há manifestado, trazendo salvação a todos os homens, ensinando-nos que, renunciando à impiedade e às concupiscências mundanas, vivamos neste presente século sóbria, justa e piamente.', 'Tito 2:11-12', 'Tito', 2, 11, 12),
  ('graca', 'Porque pela graça sois salvos, por meio da fé; e isso não vem de vós; é dom de Deus. Não vem das obras, para que ninguém se glorie.', 'Efésios 2:8-9', 'Efésios', 2, 8, 9),
  ('graca', 'Que nos salvou e chamou com uma santa vocação; não segundo as nossas obras, mas segundo o seu próprio propósito e graça que nos foi dada em Cristo Jesus, antes dos tempos dos séculos.', '2 Timóteo 1:9', '2 Timóteo', 1, 9, NULL),
  ('graca', 'Porque o pecado não terá domínio sobre vós, pois não estais debaixo da lei, mas debaixo da graça.', 'Romanos 6:14', 'Romanos', 6, 14, NULL),
  ('graca', 'Por isso, o Senhor', 'Isaías 30:18', 'Isaías', 30, 18, NULL),
  ('graca', 'E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. De boa vontade, pois, me gloriarei nas minhas fraquezas, para que em mim habite o poder de Cristo.', '2 Coríntios 12:9', '2 Coríntios', 12, 9, NULL),
  ('graca', 'A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém!', 'Apocalipse 22:21', 'Apocalipse', 22, 21, NULL),
  ('graca', 'Porque todos pecaram e destituídos estão da glória de Deus, sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus.', 'Romanos 3:23-24', 'Romanos', 3, 23, 24),
  ('graca', 'Pois quê? Pecaremos porque não estamos debaixo da lei, mas debaixo da graça? De modo nenhum!', 'Romanos 6:15', 'Romanos', 6, 15, NULL),
  ('graca', 'Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós.', 'Mateus 6:14', 'Mateus', 6, 14, NULL),
  ('graca', 'Porque o Senhor', '2 Crônicas 30:9b', '2 Crônicas 30:9b', NULL, NULL, NULL),
  ('graca', 'E seja sobre nós a graça do Senhor, nosso Deus; e confirma sobre nós a obra das nossas mãos; sim, confirma a obra das nossas mãos.', 'Salmo 90:17', 'Salmo', 90, 17, NULL),
  ('graca', 'Certamente que a bondade e a misericórdia me seguirão todos os dias da minha vida; e habitarei na Casa do Senhor', 'Salmo 23:6', 'Salmo', 23, 6, NULL),
  ('graca', 'A graça de nosso Senhor Jesus Cristo seja com o vosso espírito. Amém!', 'Filemom 1:25', 'Filemom', 1, 25, NULL),
  ('graca', 'Portanto, cingindo os lombos do vosso entendimento, sede sóbrios e esperai inteiramente na graça que se vos ofereceu na revelação de Jesus Cristo.', '1 Pedro 1:13', '1 Pedro', 1, 13, NULL),
  ('graca', 'Antes, crescei na graça e conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele seja dada a glória, assim agora como no dia da eternidade. Amém!', '2 Pedro 3:18', '2 Pedro', 3, 18, NULL),
  ('graca', 'Mas não é assim o dom gratuito como a ofensa; porque, se, pela ofensa de um, morreram muitos, muito mais a graça de Deus e o dom pela graça, que é de um só homem, Jesus Cristo, abundou sobre muitos.', 'Romanos 5:15', 'Romanos', 5, 15, NULL),
  ('graca', 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'João', 3, 16, NULL),
  ('graca', 'Das profundezas a ti clamo, ó Senhor', 'Salmo 130:1-2', 'Salmo', 130, 1, 2),
  ('graca', 'Para que, assim como o pecado reinou na morte, também a graça reinasse pela justiça para a vida eterna, por Jesus Cristo, nosso Senhor.', 'Romanos 5:21', 'Romanos', 5, 21, NULL),
  ('graca', 'Mas em nada tenho a minha vida por preciosa, contanto que cumpra com alegria a minha carreira e o ministério que recebi do Senhor Jesus, para dar testemunho do evangelho da graça de Deus.', 'Atos 20:24', 'Atos', 20, 24, NULL),
  ('graca', 'Tu, pois, meu filho, fortifica-te na graça que há em Cristo Jesus.', '2 Timóteo 2:1', '2 Timóteo', 2, 1, NULL),
  ('graca', 'A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com vós todos. Amém!', '2 Coríntios 13:13', '2 Coríntios', 13, 13, NULL),
  ('graca', 'O que encobre as suas transgressões nunca prosperará; mas o que as confessa e deixa alcançará misericórdia.', 'Provérbios 28:13', 'Provérbios', 28, 13, NULL),
  ('graca', 'Que diremos, pois? Permaneceremos no pecado, para que a graça seja mais abundante? De modo nenhum! Nós que estamos mortos para o pecado, como viveremos ainda nele?', 'Romanos 6:1-2', 'Romanos', 6, 1, 2),
  ('graca', 'A graça de nosso Senhor Jesus Cristo seja com vós todos. Amém!', 'Filipenses 4:23', 'Filipenses', 4, 23, NULL),
  ('graca', 'Porque serei misericordioso para com as suas iniquidades e de seus pecados e de suas prevaricações não me lembrarei mais.', 'Hebreus 8:12', 'Hebreus', 8, 12, NULL),
  ('graca', 'Graça e paz de Deus, nosso Pai, e do Senhor Jesus Cristo.', 'Romanos 1:7b', 'Romanos 1:7b', NULL, NULL, NULL),
  ('graca', 'Mas, pela tua grande misericórdia, não os destruíste nem desamparaste; porque és um Deus clemente e misericordioso.', 'Neemias 9:31', 'Neemias', 9, 31, NULL),
  ('graca', 'Não aniquilo a graça de Deus; porque, se a justiça provém da lei, segue-se que Cristo morreu debalde.', 'Gálatas 2:21', 'Gálatas', 2, 21, NULL),
  ('graca', 'Que é o homem mortal para que te lembres dele? E o filho do homem, para que o visites?', 'Salmo 8:4', 'Salmo', 8, 4, NULL),
  ('graca', 'Porque, pela graça que me é dada, digo a cada um dentre vós que não saiba mais do que convém saber, mas que saiba com temperança, conforme a medida da fé que Deus repartiu a cada um.', 'Romanos 12:3', 'Romanos', 12, 3, NULL),
  ('graca', 'Porque a vós vos foi concedido, em relação a Cristo, não somente crer nele, como também padecer por ele.', 'Filipenses 1:29', 'Filipenses', 1, 29, NULL),
  ('graca', 'E o Deus de paz esmagará em breve Satanás debaixo dos vossos pés. A graça de nosso Senhor Jesus Cristo seja convosco. Amém!', 'Romanos 16:20', 'Romanos', 16, 20, NULL),
  ('graca', 'Separados estais de Cristo, vós os que vos justificais pela lei; da graça tendes caído.', 'Gálatas 5:4', 'Gálatas', 5, 4, NULL),
  ('graca', 'E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor', 'Joel 2:13', 'Joel', 2, 13, NULL),
  ('graca', 'Então, Pedro, aproximando-se dele, disse: Senhor, até quantas vezes pecará meu irmão contra mim, e eu lhe perdoarei? Até sete? Jesus lhe disse: Não te digo que até sete, mas até setenta vezes sete.', 'Mateus 18:21-22', 'Mateus', 18, 21, 22),
  ('graca', 'Volta, ó rebelde Israel, diz o Senhor', 'Jeremias 3:12b', 'Jeremias 3:12b', NULL, NULL, NULL),
  ('graca', 'Deixe o ímpio o seu caminho, e o homem maligno, os seus pensamentos e se converta ao Senhor', 'Isaías 55:7', 'Isaías', 55, 7, NULL),
  ('graca', 'Igualmente vós, maridos, coabitai com ela com entendimento, dando honra à mulher, como vaso mais fraco; como sendo vós os seus coerdeiros da graça da vida; para que não sejam impedidas as vossas orações.', '1 Pedro 3:7', '1 Pedro', 3, 7, NULL),
  ('graca', 'O publicano, porém, estando em pé, de longe, nem ainda queria levantar os olhos ao céu, mas batia no peito, dizendo: Ó Deus, tem misericórdia de mim, pecador!', 'Lucas 18:13', 'Lucas', 18, 13, NULL),
  ('graca', 'E Deus viu as obras deles, como se converteram do seu mau caminho; e Deus se arrependeu do mal que tinha dito lhes faria e não o fez.', 'Jonas 3:10', 'Jonas', 3, 10, NULL),
  ('graca', 'Mas tu, Senhor, és um Deus cheio de compaixão, e piedoso, e sofredor, e grande em benignidade e em verdade.', 'Salmo 86:15', 'Salmo', 86, 15, NULL),
  ('gratidao', 'Regozijai-vos sempre. Orai sem cessar. Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.', '1 Tessalonicenses 5:16-18', '1 Tessalonicenses', 5, 16, 18),
  ('gratidao', 'Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.', 'Filipenses 4:6-7', 'Filipenses', 4, 6, 7),
  ('gratidao', 'Mas graças a Deus, que nos dá a vitória por nosso Senhor Jesus Cristo.', '1 Coríntios 15:57', '1 Coríntios', 15, 57, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('gratidao', 'Louvai ao Senhor', '1 Crônicas 16:34', '1 Crônicas', 16, 34, NULL),
  ('gratidao', 'Sempre devemos, irmãos, dar graças a Deus por vós, como é de razão, porque a vossa fé cresce muitíssimo, e o amor de cada um de vós aumenta de uns para com os outros.', '2 Tessalonicenses 1:3', '2 Tessalonicenses', 1, 3, NULL),
  ('gratidao', 'Porque dele, e por ele, e para ele são todas as coisas; glória, pois, a ele eternamente. Amém!', 'Romanos 11:36', 'Romanos', 11, 36, NULL),
  ('gratidao', 'Eu te louvarei, Senhor', 'Salmo 9:1', 'Salmo', 9, 1, NULL),
  ('gratidao', 'E, quanto fizerdes por palavras ou por obras, fazei tudo em nome do Senhor Jesus, dando por ele graças a Deus Pai.', 'Colossenses 3:17', 'Colossenses', 3, 17, NULL),
  ('gratidao', 'E a paz de Deus, para a qual também fostes chamados em um corpo, domine em vossos corações; e sede agradecidos.', 'Colossenses 3:15', 'Colossenses', 3, 15, NULL),
  ('gratidao', 'Perseverai em oração, velando nela com ação de graças.', 'Colossenses 4:2', 'Colossenses', 4, 2, NULL),
  ('gratidao', 'Para que em tudo enriqueçais para toda a beneficência, a qual faz que por nós se deem graças a Deus.', '2 Coríntios 9:11', '2 Coríntios', 9, 11, NULL),
  ('gratidao', 'A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais; cantando ao Senhor com graça em vosso coração.', 'Colossenses 3:16', 'Colossenses', 3, 16, NULL),
  ('gratidao', 'E ouvi a toda criatura que está no céu, e na terra, e debaixo da terra, e que está no mar, e a todas as coisas que neles há, dizer: Ao que está assentado sobre o trono e ao Cordeiro sejam dadas ações de graças, e honra, e glória, e poder para todo o sempre.', 'Apocalipse 5:13', 'Apocalipse', 5, 13, NULL),
  ('gratidao', 'Mas eu te oferecerei sacrifício com a voz do agradecimento; o que votei pagarei; do Senhor', 'Jonas 2:9', 'Jonas', 2, 9, NULL),
  ('gratidao', 'E, tomando o pão e havendo dado graças, partiu-o e deu-lho, dizendo: Isto é o meu corpo, que por vós é dado; fazei isso em memória de mim.', 'Lucas 22:19', 'Lucas', 22, 19, NULL),
  ('guerra-espiritual', 'Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça, e calçados os pés na preparação do evangelho da paz; tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno.', 'Efésios 6:14-16', 'Efésios', 6, 14, 16),
  ('guerra-espiritual', 'Porque não temos que lutar contra carne e sangue, mas, sim, contra os principados, contra as potestades, contra os príncipes das trevas deste século, contra as hostes espirituais da maldade, nos lugares celestiais.', 'Efésios 6:12', 'Efésios', 6, 12, NULL),
  ('guerra-espiritual', 'O Senhor', 'Êxodo 14:14', 'Êxodo', 14, 14, NULL),
  ('guerra-espiritual', 'Porque, andando na carne, não militamos segundo a carne.', '2 Coríntios 10:3', '2 Coríntios', 10, 3, NULL),
  ('guerra-espiritual', 'Ainda que um exército me cercasse, o meu coração não temeria; ainda que a guerra se levantasse contra mim, nele confiaria.', 'Salmo 27:3', 'Salmo', 27, 3, NULL),
  ('guerra-espiritual', 'Tu crês que há um só Deus? Fazes bem; também os demônios o creem e estremecem.', 'Tiago 2:19', 'Tiago', 2, 19, NULL),
  ('guerra-espiritual', 'Uns confiam em carros, e outros, em cavalos, mas nós faremos menção do nome do Senhor', 'Salmo 20:7', 'Salmo', 20, 7, NULL),
  ('guerra-espiritual', 'Sujeitai-vos, pois, a Deus; resisti ao diabo, e ele fugirá de vós.', 'Tiago 4:7', 'Tiago', 4, 7, NULL),
  ('guerra-espiritual', 'Mas fiel é o Senhor, que vos confortará e guardará do maligno.', '2 Tessalonicenses 3:3', '2 Tessalonicenses', 3, 3, NULL),
  ('guerra-espiritual', 'No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder.', 'Efésios 6:10', 'Efésios', 6, 10, NULL),
  ('guerra-espiritual', 'Sede sóbrios, vigiai, porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar.', '1 Pedro 5:8', '1 Pedro', 5, 8, NULL),
  ('guerra-espiritual', 'Combati o bom combate, acabei a carreira, guardei a fé. Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele Dia; e não somente a mim, mas também a todos os que amarem a sua vinda.', '2 Timóteo 4:7-8', '2 Timóteo', 4, 7, 8),
  ('guerra-espiritual', 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo.', 'Efésios 6:11', 'Efésios', 6, 11, NULL),
  ('guerra-espiritual', 'Portanto, tomai toda a armadura de Deus, para que possais resistir no dia mau e, havendo feito tudo, ficar firmes.', 'Efésios 6:13', 'Efésios', 6, 13, NULL),
  ('guerra-espiritual', 'Tomai também o capacete da salvação e a espada do Espírito, que é a palavra de Deus.', 'Efésios 6:17', 'Efésios', 6, 17, NULL),
  ('guerra-espiritual', 'Ninguém, de maneira alguma, vos engane, porque não será assim sem que antes venha a apostasia e se manifeste o homem do pecado, o filho da perdição, o qual se opõe e se levanta contra tudo o que se chama Deus ou se adora; de sorte que se assentará, como Deus, no templo de Deus, querendo parecer Deus.', '2 Tessalonicenses 2:3-4', '2 Tessalonicenses', 2, 3, 4),
  ('guerra-espiritual', 'Milita a boa milícia da fé, toma posse da vida eterna, para a qual também foste chamado, tendo já feito boa confissão diante de muitas testemunhas.', '1 Timóteo 6:12', '1 Timóteo', 6, 12, NULL),
  ('honestidade', 'Meus filhinhos, não amemos de palavra, nem de língua, mas por obra e em verdade.', '1 João 3:18', '1 João', 3, 18, NULL),
  ('honestidade', 'A sinceridade dos sinceros os encaminhará, mas a perversidade dos desleais os destruirá.', 'Provérbios 11:3', 'Provérbios', 11, 3, NULL),
  ('honestidade', 'Fazer justiça e julgar com retidão é mais aceitável ao Senhor', 'Provérbios 21:3', 'Provérbios', 21, 3, NULL),
  ('honestidade', 'Se dissermos que temos comunhão com ele e andarmos em trevas, mentimos e não praticamos a verdade.', '1 João 1:6', '1 João', 1, 6, NULL),
  ('honestidade', 'Bem-aventurados os limpos de coração, porque eles verão a Deus.', 'Mateus 5:8', 'Mateus', 5, 8, NULL),
  ('honestidade', 'Portanto, dai a cada um o que deveis: a quem tributo, tributo; a quem imposto, imposto; a quem temor, temor; a quem honra, honra.', 'Romanos 13:7', 'Romanos', 13, 7, NULL),
  ('honestidade', 'Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade.', '2 Timóteo 2:15', '2 Timóteo', 2, 15, NULL),
  ('honestidade', 'Melhor é o pouco com justiça do que a abundância de colheita com injustiça.', 'Provérbios 16:8', 'Provérbios', 16, 8, NULL),
  ('honestidade', 'O homem perverso levanta a contenda, e o difamador separa os maiores amigos.', 'Provérbios 16:28', 'Provérbios', 16, 28, NULL),
  ('honestidade', 'Descansa no Senhor', 'Salmo 37:7', 'Salmo', 37, 7, NULL),
  ('honestidade', 'Mas a sabedoria que vem do alto é, primeiramente, pura, depois, pacífica, moderada, tratável, cheia de misericórdia e de bons frutos, sem parcialidade e sem hipocrisia.', 'Tiago 3:17', 'Tiago', 3, 17, NULL),
  ('honestidade', 'Não detenhas dos seus donos o bem, estando na tua mão poder fazê-lo.', 'Provérbios 3:27', 'Provérbios', 3, 27, NULL),
  ('honestidade', 'Os lábios mentirosos são abomináveis ao Senhor', 'Provérbios 12:22', 'Provérbios', 12, 22, NULL),
  ('honestidade', 'Os tesouros da impiedade de nada aproveitam; mas a justiça livra da morte.', 'Provérbios 10:2', 'Provérbios', 10, 2, NULL),
  ('honestidade', 'Mas, sobretudo, meus irmãos, não jureis nem pelo céu nem pela terra, nem façais qualquer outro juramento; mas que a vossa palavra seja sim, sim e não, não, para que não caiais em condenação.', 'Tiago 5:12', 'Tiago', 5, 12, NULL),
  ('honestidade', 'Bem irá ao homem que se compadece e empresta; disporá as suas coisas com juízo.', 'Salmo 112:5', 'Salmo', 112, 5, NULL),
  ('honestidade', 'E ninguém, acendendo uma candeia, a cobre com algum vaso ou a põe debaixo da cama; mas põe-na no velador, para que os que entram vejam a luz.', 'Lucas 8:16', 'Lucas', 8, 16, NULL),
  ('honestidade', 'Os teus olhos olhem direitos, e as tuas pálpebras olhem diretamente diante de ti.', 'Provérbios 4:25', 'Provérbios', 4, 25, NULL),
  ('honestidade', 'Então, entenderás justiça, e juízo, e equidade, e todas as boas veredas.', 'Provérbios 2:9', 'Provérbios', 2, 9, NULL),
  ('honestidade', 'Mas nada há encoberto que não haja de ser descoberto; nem oculto, que não haja de ser sabido.', 'Lucas 12:2', 'Lucas', 12, 2, NULL),
  ('honestidade', 'Por esta razão também pagais tributos, porque são ministros de Deus, atendendo sempre a isto mesmo.', 'Romanos 13:6', 'Romanos', 13, 6, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('honestidade', 'Disse, então, Pedro: Ananias, por que encheu Satanás o teu coração, para que mentisses ao Espírito Santo e retivesses parte do preço da herdade? Guardando-a, não ficava para ti? E, vendida, não estava em teu poder? Por que formaste este desígnio em teu coração? Não mentiste aos homens, mas a Deus.', 'Atos 5:3-4', 'Atos', 5, 3, 4),
  ('honestidade', 'Agora, pois, seja o temor do Senhor', '2 Crônicas 19:7', '2 Crônicas', 19, 7, NULL),
  ('humildade', 'Com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros em amor.', 'Efésios 4:2', 'Efésios', 4, 2, NULL),
  ('humildade', 'Nada façais por contenda ou por vanglória, mas por humildade; cada um considere os outros superiores a si mesmo.', 'Filipenses 2:3', 'Filipenses', 2, 3, NULL),
  ('humildade', 'Vindo a soberba, virá também a afronta; mas com os humildes está a sabedoria.', 'Provérbios 11:2', 'Provérbios', 11, 2, NULL),
  ('humildade', 'Humilhai-vos perante o Senhor, e ele vos exaltará.', 'Tiago 4:10', 'Tiago', 4, 10, NULL),
  ('humildade', 'Sede unânimes entre vós; não ambicioneis coisas altas, mas acomodai-vos às humildes; não sejais sábios em vós mesmos.', 'Romanos 12:16', 'Romanos', 12, 16, NULL),
  ('humildade', 'O enfeite delas não seja o exterior, no frisado dos cabelos, no uso de joias de ouro, na compostura de vestes, mas o homem encoberto no coração, no incorruptível trajo de um espírito manso e quieto, que é precioso diante de Deus.', '1 Pedro 3:3-4', '1 Pedro', 3, 3, 4),
  ('humildade', 'A soberba do homem o abaterá, mas o humilde de espírito obterá honra.', 'Provérbios 29:23', 'Provérbios', 29, 23, NULL),
  ('humildade', 'Revesti-vos, pois, como eleitos de Deus, santos e amados, de entranhas de misericórdia, de benignidade, humildade, mansidão, longanimidade.', 'Colossenses 3:12', 'Colossenses', 3, 12, NULL),
  ('humildade', 'O galardão da humildade e o temor do Senhor', 'Provérbios 22:4', 'Provérbios', 22, 4, NULL),
  ('humildade', 'Humilhai-vos, pois, debaixo da potente mão de Deus, para que, a seu tempo, vos exalte.', '1 Pedro 5:6', '1 Pedro', 5, 6, NULL),
  ('humildade', 'E se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar a minha face, e se converter dos seus maus caminhos, então, eu ouvirei dos céus, e perdoarei os seus pecados, e sararei a sua terra.', '2 Crônicas 7:14', '2 Crônicas', 7, 14, NULL),
  ('humildade', 'Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração, e encontrareis descanso para a vossa alma. Porque o meu jugo é suave, e o meu fardo é leve.', 'Mateus 11:29-30', 'Mateus', 11, 29, 30),
  ('humildade', 'Quem dentre vós é sábio e inteligente? Mostre, pelo seu bom trato, as suas obras em mansidão de sabedoria.', 'Tiago 3:13', 'Tiago', 3, 13, NULL),
  ('humildade', 'Antes de ser quebrantado, eleva-se o coração do homem; e, diante da honra, vai a humildade.', 'Provérbios 18:12', 'Provérbios', 18, 12, NULL),
  ('humildade', 'E ele, assentando-se, chamou os doze e disse-lhes: Se alguém quiser ser o primeiro, será o derradeiro de todos e o servo de todos.', 'Marcos 9:35', 'Marcos', 9, 35, NULL),
  ('humildade', 'E, finalmente, sede todos de um mesmo sentimento, compassivos, amando os irmãos, entranhavelmente misericordiosos e afáveis.', '1 Pedro 3:8', '1 Pedro', 3, 8, NULL),
  ('humildade', 'E Deus escolheu as coisas vis deste mundo, e as desprezíveis, e as que não são para aniquilar as que são; para que nenhuma carne se glorie perante ele.', '1 Coríntios 1:28-29', '1 Coríntios', 1, 28, 29),
  ('humildade', 'Ele te declarou, ó homem, o que é bom; e que é o que o Senhor', 'Miqueias 6:8', 'Miqueias', 6, 8, NULL),
  ('humildade', 'O temor do Senhor', 'Provérbios 15:33', 'Provérbios', 15, 33, NULL),
  ('humildade', 'Quando, pois, deres esmola, não faças tocar trombeta diante de ti, como fazem os hipócritas nas sinagogas e nas ruas, para serem glorificados pelos homens. Em verdade vos digo que já receberam o seu galardão.', 'Mateus 6:2', 'Mateus', 6, 2, NULL),
  ('humildade', 'É necessário que ele cresça e que eu diminua.', 'João 3:30', 'João', 3, 30, NULL),
  ('humildade', 'Bom e reto é o Senhor', 'Salmo 25:8-9', 'Salmo', 25, 8, 9),
  ('humildade', 'Vós, mulheres, estai sujeitas a vosso próprio marido, como convém no Senhor. Vós, maridos, amai a vossa mulher e não vos irriteis contra ela.', 'Colossenses 3:18-19', 'Colossenses', 3, 18, 19),
  ('humildade', 'E disse-lhes: Qualquer que receber esta criança em meu nome recebe-me a mim; e qualquer que me recebe a mim recebe o que me enviou; porque aquele que entre vós todos for o menor, esse mesmo é grande.', 'Lucas 9:48', 'Lucas', 9, 48, NULL),
  ('humildade', 'Porque vós, irmãos, fostes chamados à liberdade. Não useis, então, da liberdade para dar ocasião à carne, mas servi-vos uns aos outros pelo amor.', 'Gálatas 5:13', 'Gálatas', 5, 13, NULL),
  ('humildade', 'Ora, a nosso Deus e Pai seja dada glória para todo o sempre. Amém!', 'Filipenses 4:20', 'Filipenses', 4, 20, NULL),
  ('humildade', 'Porque o Senhor', 'Salmo 149:4', 'Salmo', 149, 4, NULL),
  ('humildade', 'Porque o Filho do Homem também não veio para ser servido, mas para servir e dar a sua vida em resgate de muitos.', 'Marcos 10:45', 'Marcos', 10, 45, NULL),
  ('humildade', 'Não a nós, Senhor', 'Salmo 115:1', 'Salmo', 115, 1, NULL),
  ('humildade', 'O Senhor', '1 Samuel 2:7', '1 Samuel', 2, 7, NULL),
  ('humildade', 'Ó, vinde, adoremos e prostremo-nos! Ajoelhemos diante do Senhor', 'Salmo 95:6', 'Salmo', 95, 6, NULL),
  ('humildade', 'Ai daquele que contende com o seu Criador, caco entre outros cacos de barro! Porventura, dirá o barro ao que o formou: Que fazes? Ou a tua obra: Não tens mãos?', 'Isaías 45:9', 'Isaías', 45, 9, NULL),
  ('humildade', 'Agora, pois, eu, Nabucodonosor, louvo, e exalço, e glorifico ao Rei dos céus; porque todas as suas obras são verdades; e os seus caminhos, juízo, e pode humilhar aos que andam na soberba.', 'Daniel 4:37', 'Daniel', 4, 37, NULL),
  ('humildade', 'Não será assim entre vós; mas todo aquele que quiser, entre vós, fazer-se grande, que seja vosso serviçal; e qualquer que, entre vós, quiser ser o primeiro, que seja vosso servo.', 'Mateus 20:26-27', 'Mateus', 20, 26, 27),
  ('humildade', 'Ora, se eu, Senhor e Mestre, vos lavei os pés, vós deveis também lavar os pés uns aos outros.', 'João 13:14', 'João', 13, 14, NULL),
  ('humildade', 'E, quando jejuardes, não vos mostreis contristados como os hipócritas, porque desfiguram o rosto, para que aos homens pareça que jejuam. Em verdade vos digo que já receberam o seu galardão.', 'Mateus 6:16', 'Mateus', 6, 16, NULL),
  ('humildade', 'Porque está escrito: Pela minha vida, diz o Senhor, todo joelho se dobrará diante de mim, e toda língua confessará a Deus.', 'Romanos 14:11', 'Romanos', 14, 11, NULL),
  ('humildade', 'Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera, a esse glória na igreja, por Jesus Cristo, em todas as gerações, para todo o sempre. Amém!', 'Efésios 3:20-21', 'Efésios', 3, 20, 21),
  ('humildade', 'Mas glorie-se o irmão abatido na sua exaltação, e o rico, em seu abatimento, porque ele passará como a flor da erva.', 'Tiago 1:9-10', 'Tiago', 1, 9, 10),
  ('humildade', 'Que é o homem mortal para que te lembres dele? E o filho do homem, para que o visites?', 'Salmo 8:4', 'Salmo', 8, 4, NULL),
  ('humildade', 'Ouve, Senhor', 'Salmo 39:12', 'Salmo', 39, 12, NULL),
  ('humildade', 'Portanto, vós orareis assim: Pai nosso, que estás nos céus, santificado seja o teu nome. Venha o teu Reino. Seja feita a tua vontade, tanto na terra como no céu.', 'Mateus 6:9-10', 'Mateus', 6, 9, 10),
  ('humildade', 'Alegra-te muito, ó filha de Sião; exulta, ó filha de Jerusalém; eis que o teu rei virá a ti, justo e Salvador, pobre e montado sobre um jumento, sobre um asninho, filho de jumenta.', 'Zacarias 9:9', 'Zacarias', 9, 9, NULL),
  ('humildade', 'Buscai o Senhor', 'Sofonias 2:3', 'Sofonias', 2, 3, NULL),
  ('humildade', 'Bem-aventurados os pobres de espírito, porque deles é o Reino dos céus.', 'Mateus 5:3', 'Mateus', 5, 3, NULL),
  ('humildade', 'Na verdade, na verdade vos digo que não é o servo maior do que o seu senhor, nem o enviado, maior do que aquele que o enviou.', 'João 13:16', 'João', 13, 16, NULL),
  ('humildade', 'O publicano, porém, estando em pé, de longe, nem ainda queria levantar os olhos ao céu, mas batia no peito, dizendo: Ó Deus, tem misericórdia de mim, pecador!', 'Lucas 18:13', 'Lucas', 18, 13, NULL),
  ('idolos', 'Filhinhos, guardai-vos dos ídolos. Amém!', '1 João 5:21', '1 João', 5, 21, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('idolos', 'Não fareis outros deuses comigo; deuses de prata ou deuses de ouro não fareis para vós.', 'Êxodo 20:23', 'Êxodo', 20, 23, NULL),
  ('idolos', 'Não sabeis que os injustos não hão de herdar o Reino de Deus? Não erreis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas, nem os ladrões, nem os avarentos, nem os bêbados, nem os maldizentes, nem os roubadores herdarão o Reino de Deus.', '1 Coríntios 6:9-10', '1 Coríntios', 6, 9, 10),
  ('idolos', 'Porque os costumes dos povos são vaidade; pois cortam do bosque um madeiro, obra das mãos do artífice, com machado. Com prata e com ouro o enfeitam, com pregos e com martelos o firmam, para que não se mova. São como a palmeira, obra torneada, mas não podem falar; necessitam de quem os leve, porquanto não podem andar; não tenhais receio deles, pois não podem fazer mal, nem tampouco têm poder de fazer bem.', 'Jeremias 10:3-5', 'Jeremias', 10, 3, 5),
  ('idolos', 'Após o Senhor', 'Deuteronômio 13:4', 'Deuteronômio', 13, 4, NULL),
  ('idolos', 'Pelo que hoje saberás e refletirás no teu coração que só o Senhor', 'Deuteronômio 4:39', 'Deuteronômio', 4, 39, NULL),
  ('idolos', 'E não comuniqueis com as obras infrutuosas das trevas, mas, antes, condenai-as. Porque o que eles fazem em oculto, até dizê-lo é torpe.', 'Efésios 5:11-12', 'Efésios', 5, 11, 12),
  ('idolos', 'Mortificai, pois, os vossos membros que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência e a avareza, que é idolatria.', 'Colossenses 3:5', 'Colossenses', 3, 5, NULL),
  ('idolos', 'Todavia, eu sou o Senhor', 'Oseias 13:4', 'Oseias', 13, 4, NULL),
  ('idolos', 'Porém, se vos parece mal aos vossos olhos servir ao Senhor', 'Josué 24:15', 'Josué', 24, 15, NULL),
  ('idolos', 'Toda ferramenta preparada contra ti não prosperará; e toda língua que se levantar contra ti em juízo, tu a condenarás; esta é a herança dos servos do Senhor', 'Isaías 54:17', 'Isaías', 54, 17, NULL),
  ('idolos', 'Porque o amor do dinheiro é a raiz de toda espécie de males; e nessa cobiça alguns se desviaram da fé e se traspassaram a si mesmos com muitas dores.', '1 Timóteo 6:10', '1 Timóteo', 6, 10, NULL),
  ('idolos', 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo.', 'Efésios 6:11', 'Efésios', 6, 11, NULL),
  ('idolos', 'Não te deixes vencer do mal, mas vence o mal com o bem.', 'Romanos 12:21', 'Romanos', 12, 21, NULL),
  ('idolos', 'Ora, o aguilhão da morte é o pecado, e a força do pecado é a lei.', '1 Coríntios 15:56', '1 Coríntios', 15, 56, NULL),
  ('idolos', 'Agora, pois, deitai fora os deuses estranhos que há no meio de vós: e inclinai o vosso coração ao Senhor', 'Josué 24:23', 'Josué', 24, 23, NULL),
  ('idolos', 'Não peço que os tires do mundo, mas que os livres do mal.', 'João 17:15', 'João', 17, 15, NULL),
  ('idolos', 'Aparta-te do mal e faze o bem; procura a paz e segue-a.', 'Salmo 34:14', 'Salmo', 34, 14, NULL),
  ('idolos', 'Pois mudaram a verdade de Deus em mentira e honraram e serviram mais a criatura do que o Criador, que é bendito eternamente. Amém! Pelo que Deus os abandonou às paixões infames. Porque até as suas mulheres mudaram o uso natural, no contrário à natureza. E, semelhantemente, também os varões, deixando o uso natural da mulher, se inflamaram em sua sensualidade uns para com os outros, varão com varão, cometendo torpeza e recebendo em si mesmos a recompensa que convinha ao seu erro. E, como eles se não importaram de ter conhecimento de Deus, assim Deus os entregou a um sentimento perverso, para fazerem coisas que não convém.', 'Romanos 1:25-28', 'Romanos', 1, 25, 28),
  ('idolos', 'Uns confiam em carros, e outros, em cavalos, mas nós faremos menção do nome do Senhor', 'Salmo 20:7', 'Salmo', 20, 7, NULL),
  ('idolos', 'Porque as obras da carne são manifestas, as quais são: prostituição, impureza, lascívia, idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias, invejas, homicídios, bebedices, glutonarias e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas não herdarão o Reino de Deus.', 'Gálatas 5:19-21', 'Gálatas', 5, 19, 21),
  ('idolos', 'Assim que, quanto ao comer das coisas sacrificadas aos ídolos, sabemos que o ídolo nada é no mundo e que não há outro Deus, senão um só.', '1 Coríntios 8:4', '1 Coríntios', 8, 4, NULL),
  ('idolos', 'Ninguém, de maneira alguma, vos engane, porque não será assim sem que antes venha a apostasia e se manifeste o homem do pecado, o filho da perdição, o qual se opõe e se levanta contra tudo o que se chama Deus ou se adora; de sorte que se assentará, como Deus, no templo de Deus, querendo parecer Deus.', '2 Tessalonicenses 2:3-4', '2 Tessalonicenses', 2, 3, 4),
  ('igreja', 'E consideremo-nos uns aos outros, para nos estimularmos ao amor e às boas obras, não deixando a nossa congregação, como é costume de alguns; antes, admoestando-nos uns aos outros; e tanto mais quanto vedes que se vai aproximando aquele Dia.', 'Hebreus 10:24-25', 'Hebreus', 10, 24, 25),
  ('igreja', 'Porque assim como em um corpo temos muitos membros, e nem todos os membros têm a mesma operação, assim nós, que somos muitos, somos um só corpo em Cristo, mas individualmente somos membros uns dos outros.', 'Romanos 12:4-5', 'Romanos', 12, 4, 5),
  ('igreja', 'Porque onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles.', 'Mateus 18:20', 'Mateus', 18, 20, NULL),
  ('igreja', 'Porque nós somos cooperadores de Deus; vós sois lavoura de Deus e edifício de Deus.', '1 Coríntios 3:9', '1 Coríntios', 3, 9, NULL),
  ('igreja', 'E, perseverando unânimes todos os dias no templo e partindo o pão em casa, comiam juntos com alegria e singeleza de coração, louvando a Deus e caindo na graça de todo o povo. E todos os dias acrescentava o Senhor à igreja aqueles que se haviam de salvar.', 'Atos 2:46-47', 'Atos', 2, 46, 47),
  ('igreja', 'Não sabeis vós que sois o templo de Deus e que o Espírito de Deus habita em vós?', '1 Coríntios 3:16', '1 Coríntios', 3, 16, NULL),
  ('igreja', 'Pois também eu te digo que tu és Pedro e sobre esta pedra edificarei a minha igreja, e as portas do inferno não prevalecerão contra ela.', 'Mateus 16:18', 'Mateus', 16, 18, NULL),
  ('igreja', 'Assim que já não sois estrangeiros, nem forasteiros, mas concidadãos dos Santos e da família de Deus; edificados sobre o fundamento dos apóstolos e dos profetas, de que Jesus Cristo é a principal pedra da esquina.', 'Efésios 2:19-20', 'Efésios', 2, 19, 20),
  ('igreja', 'E a paz de Deus, para a qual também fostes chamados em um corpo, domine em vossos corações; e sede agradecidos.', 'Colossenses 3:15', 'Colossenses', 3, 15, NULL),
  ('igreja', 'A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais; cantando ao Senhor com graça em vosso coração.', 'Colossenses 3:16', 'Colossenses', 3, 16, NULL),
  ('igreja', 'Se alguém destruir o templo de Deus, Deus o destruirá; porque o templo de Deus, que sois vós, é santo.', '1 Coríntios 3:17', '1 Coríntios', 3, 17, NULL),
  ('igreja', 'Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também.', '1 Coríntios 12:12', '1 Coríntios', 12, 12, NULL),
  ('igreja', 'Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera, a esse glória na igreja, por Jesus Cristo, em todas as gerações, para todo o sempre. Amém!', 'Efésios 3:20-21', 'Efésios', 3, 20, 21),
  ('igreja', 'Toda Escritura divinamente inspirada é proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça, para que o homem de Deus seja perfeito e perfeitamente instruído para toda boa obra.', '2 Timóteo 3:16-17', '2 Timóteo', 3, 16, 17),
  ('igreja', 'Vós, maridos, amai vossa mulher, como também Cristo amou a igreja e a si mesmo se entregou por ela, para a santificar, purificando-a com a lavagem da água, pela palavra.', 'Efésios 5:25-26', 'Efésios', 5, 25, 26),
  ('igreja', 'Assim, pois, as igrejas em toda a Judeia, e Galileia, e Samaria tinham paz e eram edificadas; e se multiplicavam, andando no temor do Senhor e na consolação do Espírito Santo.', 'Atos 9:31', 'Atos', 9, 31, NULL),
  ('igreja', 'Antes, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo.', 'Efésios 4:15', 'Efésios', 4, 15, NULL),
  ('igreja', 'E rogo-vos, irmãos, que noteis os que promovem dissensões e escândalos contra a doutrina que aprendestes; desviai-vos deles.', 'Romanos 16:17', 'Romanos', 16, 17, NULL),
  ('igreja', 'Mas vós, amados, edificando-vos a vós mesmos sobre a vossa santíssima fé, orando no Espírito Santo, conservai a vós mesmos no amor de Deus, esperando a misericórdia de nosso Senhor Jesus Cristo, para a vida eterna.', 'Judas 1:20-21', 'Judas', 1, 20, 21),
  ('igreja', 'Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo, nosso Senhor.', '1 Coríntios 1:9', '1 Coríntios', 1, 9, NULL),
  ('igreja', 'Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor; e a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados.', 'Tiago 5:14-15', 'Tiago', 5, 14, 15),
  ('igreja', 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações.', 'Atos 2:42', 'Atos', 2, 42, NULL),
  ('igreja', 'Pois todos nós fomos batizados em um Espírito, formando um corpo, quer judeus, quer gregos, quer servos, quer livres, e todos temos bebido de um Espírito.', '1 Coríntios 12:13', '1 Coríntios', 12, 13, NULL),
  ('igreja', 'Pedro, pois, era guardado na prisão; mas a igreja fazia contínua oração por ele a Deus.', 'Atos 12:5', 'Atos', 12, 5, NULL),
  ('igreja', 'Vós, mulheres, sujeitai-vos a vosso marido, como ao Senhor; porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo.', 'Efésios 5:22-23', 'Efésios', 5, 22, 23),
  ('igreja', 'E, se não as escutar, dize-o à igreja; e, se também não escutar a igreja, considera-o como um gentio e publicano.', 'Mateus 18:17', 'Mateus', 18, 17, NULL),
  ('igreja', 'De sorte que foram batizados os que de bom grado receberam a sua palavra; e, naquele dia, agregaram-se quase três mil almas.', 'Atos 2:41', 'Atos', 2, 41, NULL),
  ('igreja', 'E ele é a cabeça do corpo da igreja; é o princípio e o primogênito dentre os mortos, para que em tudo tenha a preeminência.', 'Colossenses 1:18', 'Colossenses', 1, 18, NULL);

