-- Parte 07: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('igreja', 'Os quais vos diziam que, no último tempo, haveria escarnecedores que andariam segundo as suas ímpias concupiscências. Estes são os que causam divisões, sensuais, que não têm o Espírito.', 'Judas 1:18-19', 'Judas', 1, 18, 19),
  ('inferno', 'E, no Hades, ergueu os olhos, estando em tormentos, e viu ao longe Abraão e Lázaro, no seu seio. E, clamando, disse: Abraão, meu pai, tem misericórdia de mim e manda a Lázaro que molhe na água a ponta do seu dedo e me refresque a língua, porque estou atormentado nesta chama.', 'Lucas 16:23-24', 'Lucas', 16, 23, 24),
  ('inferno', 'Portanto, se o teu olho direito te escandalizar, arranca-o e atira-o para longe de ti, pois te é melhor que se perca um dos teus membros do que todo o teu corpo seja lançado no inferno.', 'Mateus 5:29', 'Mateus', 5, 29, NULL),
  ('inferno', 'E não temais os que matam o corpo e não podem matar a alma; temei, antes, aquele que pode fazer perecer no inferno a alma e o corpo.', 'Mateus 10:28', 'Mateus', 10, 28, NULL),
  ('inferno', 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus, nosso Senhor.', 'Romanos 6:23', 'Romanos', 6, 23, NULL),
  ('inferno', 'Para onde me irei do teu Espírito ou para onde fugirei da tua face? Se subir ao céu, tu aí estás; se fizer no Seol a minha cama, eis que tu ali estás também.', 'Salmo 139:7-8', 'Salmo', 139, 7, 8),
  ('inferno', 'Portanto, agora, nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito. Porque a lei do Espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte.', 'Romanos 8:1-2', 'Romanos', 8, 1, 2),
  ('inferno', 'Porque todos os que sem lei pecaram sem lei também perecerão; e todos os que sob a lei pecaram pela lei serão julgados.', 'Romanos 2:12', 'Romanos', 2, 12, NULL),
  ('inferno', 'Pois também eu te digo que tu és Pedro e sobre esta pedra edificarei a minha igreja, e as portas do inferno não prevalecerão contra ela.', 'Mateus 16:18', 'Mateus', 16, 18, NULL),
  ('irrepreensivel', 'Aquele que anda em sinceridade, e pratica a justiça, e fala verazmente segundo o seu coração; aquele que não difama com a sua língua, nem faz mal ao seu próximo, nem aceita nenhuma afronta contra o seu próximo.', 'Salmo 15:2-3', 'Salmo', 15, 2, 3),
  ('irrepreensivel', 'Fazei todas as coisas sem murmurações nem contendas; para que sejais irrepreensíveis e sinceros, filhos de Deus inculpáveis no meio duma geração corrompida e perversa, entre a qual resplandeceis como astros no mundo; retendo a palavra da vida.', 'Filipenses 2:14-16a', 'Filipenses 2:14-16a', NULL, NULL, NULL),
  ('irrepreensivel', 'Porque todos tropeçamos em muitas coisas. Se alguém não tropeça em palavra, o tal varão é perfeito e poderoso para também refrear todo o corpo.', 'Tiago 3:2', 'Tiago', 3, 2, NULL),
  ('irrepreensivel', 'Vede que ninguém dê a outrem mal por mal, mas segui, sempre, o bem, tanto uns para com os outros como para com todos.', '1 Tessalonicenses 5:15', '1 Tessalonicenses', 5, 15, NULL),
  ('irrepreensivel', 'E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.', 'Romanos 12:2', 'Romanos', 12, 2, NULL),
  ('irrepreensivel', 'E, sobre tudo isto, revesti-vos de amor, que é o vínculo da perfeição.', 'Colossenses 3:14', 'Colossenses', 3, 14, NULL),
  ('irrepreensivel', 'O caminho de Deus é perfeito; a palavra do Senhor é provada; é um escudo para todos os que nele confiam.', 'Salmo 18:30', 'Salmo', 18, 30, NULL),
  ('irrepreensivel', 'Bem-aventurados os que trilham caminhos retos e andam na lei do Senhor.', 'Salmo 119:1', 'Salmo', 119, 1, NULL),
  ('irrepreensivel', 'Rogo-vos, porém, irmãos, pelo nome de nosso Senhor Jesus Cristo, que digais todos uma mesma coisa e que não haja entre vós dissensões; antes, sejais unidos, em um mesmo sentido e em um mesmo parecer.', '1 Coríntios 1:10', '1 Coríntios', 1, 10, NULL),
  ('irrepreensivel', 'Mas ele sabe o meu caminho; prove-me, e sairei como o ouro. Nas suas pisadas os meus pés se afirmaram; guardei o seu caminho e não me desviei dele.', 'Jó 23:10-11', 'Jó', 23, 10, 11),
  ('irrepreensivel', 'Ele reserva a verdadeira sabedoria para os retos; escudo é para os que caminham na sinceridade.', 'Provérbios 2:7', 'Provérbios', 2, 7, NULL),
  ('irrepreensivel', 'O caminho de Deus é perfeito, e a palavra do Senhor, refinada; ele é o escudo de todos os que nele confiam.', '2 Samuel 22:31', '2 Samuel', 22, 31, NULL),
  ('irrepreensivel', 'A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e guardar-se da corrupção do mundo.', 'Tiago 1:27', 'Tiago', 1, 27, NULL),
  ('irrepreensivel', 'Até agora, nada pedistes em meu nome; pedi e recebereis, para que a vossa alegria se cumpra.', 'João 16:24', 'João', 16, 24, NULL),
  ('irrepreensivel', 'E, sendo ele consumado, veio a ser a causa de eterna salvação para todos os que lhe obedecem.', 'Hebreus 5:9', 'Hebreus', 5, 9, NULL),
  ('irrepreensivel', 'Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes, em quem não há mudança, nem sombra de variação.', 'Tiago 1:17', 'Tiago', 1, 17, NULL),
  ('irrepreensivel', 'Tenho-vos dito isso para que a minha alegria permaneça em vós, e a vossa alegria seja completa.', 'João 15:11', 'João', 15, 11, NULL),
  ('irrepreensivel', 'Disse-lhe Jesus: Se queres ser perfeito, vai, vende tudo o que tens, dá-o aos pobres e terás um tesouro no céu; e vem e segue-me.', 'Mateus 19:21', 'Mateus', 19, 21, NULL),
  ('irrepreensivel', 'Com o benigno te mostrarás benigno; e com o homem sincero te mostrarás sincero.', 'Salmo 18:25', 'Salmo', 18, 25, NULL),
  ('jejum', 'Nós, pois, jejuamos e pedimos isso ao nosso Deus, e moveu-se pelas nossas orações.', 'Esdras 8:23', 'Esdras', 8, 23, NULL),
  ('jejum', 'Porventura, não é este o jejum que escolhi: que soltes as ligaduras da impiedade, que desfaças as ataduras do jugo, e que deixes livres os quebrantados, e que despedaces todo o jugo?', 'Isaías 58:6', 'Isaías', 58, 6, NULL),
  ('jejum', 'Porém tu, quando jejuares, unge a cabeça e lava o rosto, para não pareceres aos homens que jejuas, mas sim a teu Pai, que está oculto; e teu Pai, que vê o que está oculto, te recompensará.', 'Mateus 6:17-18', 'Mateus', 6, 17, 18),
  ('jejum', 'Ainda assim, agora mesmo diz o Senhor: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, e com choro, e com pranto.', 'Joel 2:12', 'Joel', 2, 12, NULL),
  ('jejum', 'E, quando jejuardes, não vos mostreis contristados como os hipócritas, porque desfiguram o rosto, para que aos homens pareça que jejuam. Em verdade vos digo que já receberam o seu galardão.', 'Mateus 6:16', 'Mateus', 6, 16, NULL),
  ('jejum', 'Manjar desejável não comi, nem carne nem vinho entraram na minha boca, nem me ungi com unguento, até que se cumpriram as três semanas.', 'Daniel 10:3', 'Daniel', 10, 3, NULL),
  ('jejum', 'Então, jejuando, e orando, e pondo sobre eles as mãos, os despediram.', 'Atos 13:3', 'Atos', 13, 3, NULL),
  ('jejum', 'E Jesus, cheio do Espírito Santo, voltou do Jordão e foi levado pelo Espírito ao deserto. E quarenta dias foi tentado pelo diabo, e, naqueles dias, não comeu coisa alguma, e, terminados eles, teve fome.', 'Lucas 4:1-2', 'Lucas', 4, 1, 2),
  ('jejum', 'E, servindo eles ao Senhor e jejuando, disse o Espírito Santo: Apartai-me a Barnabé e a Saulo para a obra a que os tenho chamado.', 'Atos 13:2', 'Atos', 13, 2, NULL),
  ('jejum', 'E esteve Moisés ali com o Senhor quarenta dias e quarenta noites; não comeu pão, nem bebeu água, e escreveu nas tábuas as palavras do concerto, os dez mandamentos.', 'Êxodo 34:28', 'Êxodo', 34, 28, NULL),
  ('jejum', 'Vai, e ajunta todos os judeus que se acharem em Susã, e jejuai por mim, e não comais nem bebais por três dias, nem de dia nem de noite, e eu e as minhas moças também assim jejuaremos; e assim irei ter com o rei, ainda que não é segundo a lei; e, perecendo, pereço.', 'Ester 4:16', 'Ester', 4, 16, NULL),
  ('jesus', 'Jesus, porém, olhando para eles, disse: Para os homens é impossível, mas não para Deus, porque para Deus todas as coisas são possíveis.', 'Marcos 10:27', 'Marcos', 10, 27, NULL),
  ('jesus', 'Olhando para Jesus, autor e consumador da fé, o qual, pelo gozo que lhe estava proposto, suportou a cruz, desprezando a afronta, e assentou-se à destra do trono de Deus.', 'Hebreus 12:2', 'Hebreus', 12, 2, NULL),
  ('jesus', 'Disse-lhe Jesus: Não te hei dito que, se creres, verás a glória de Deus?', 'João 11:40', 'João', 11, 40, NULL),
  ('jesus', 'Qualquer que confessar que Jesus é o Filho de Deus, Deus está nele e ele em Deus.', '1 João 4:15', '1 João', 4, 15, NULL),
  ('jesus', 'De sorte que haja em vós o mesmo sentimento que houve também em Cristo Jesus.', 'Filipenses 2:5', 'Filipenses', 2, 5, NULL),
  ('jesus', 'E dou-lhes a vida eterna, e nunca hão de perecer, e ninguém as arrebatará das minhas mãos. Meu Pai, que mas deu, é maior do que todos; e ninguém pode arrebatá-las das mãos de meu Pai. Eu e o Pai somos um.', 'João 10:28-30', 'João', 10, 28, 30),
  ('jesus', 'Mas ele foi ferido pelas nossas transgressões e moído pelas nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e, pelas suas pisaduras, fomos sarados.', 'Isaías 53:5', 'Isaías', 53, 5, NULL),
  ('jesus', 'E em nenhum outro há salvação, porque também debaixo do céu nenhum outro nome há, dado entre os homens, pelo qual devamos ser salvos.', 'Atos 4:12', 'Atos', 4, 12, NULL),
  ('jesus', 'Nisto se manifestou o amor de Deus para conosco: que Deus enviou seu Filho unigênito ao mundo, para que por ele vivamos.', '1 João 4:9', '1 João', 4, 9, NULL),
  ('jesus', 'Porque onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles.', 'Mateus 18:20', 'Mateus', 18, 20, NULL),
  ('jesus', 'Mas ele respondeu: As coisas que são impossíveis aos homens são possíveis a Deus.', 'Lucas 18:27', 'Lucas', 18, 27, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('jesus', 'Mas graças a Deus, que nos dá a vitória por nosso Senhor Jesus Cristo.', '1 Coríntios 15:57', '1 Coríntios', 15, 57, NULL),
  ('jesus', 'A saber: Se, com a tua boca, confessares ao Senhor Jesus e, em teu coração, creres que Deus o ressuscitou dos mortos, serás salvo.', 'Romanos 10:9', 'Romanos', 10, 9, NULL),
  ('jesus', 'O meu mandamento é este: Que vos ameis uns aos outros, assim como eu vos amei.', 'João 15:12', 'João', 15, 12, NULL),
  ('jesus', 'E quem não toma a sua cruz e não segue após mim não é digno de mim.', 'Mateus 10:38', 'Mateus', 10, 38, NULL),
  ('jesus', 'O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades em glória, por Cristo Jesus.', 'Filipenses 4:19', 'Filipenses', 4, 19, NULL),
  ('jesus', 'Porque há um só Deus e um só mediador entre Deus e os homens, Jesus Cristo, homem.', '1 Timóteo 2:5', '1 Timóteo', 2, 5, NULL),
  ('jesus', 'Falou-lhes, pois, Jesus outra vez, dizendo: Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.', 'João 8:12', 'João', 8, 12, NULL),
  ('jesus', 'A graça de nosso Senhor Jesus Cristo seja com o vosso espírito. Amém!', 'Filemom 1:25', 'Filemom', 1, 25, NULL),
  ('jesus', 'Jesus Cristo é o mesmo ontem, e hoje, e eternamente.', 'Hebreus 13:8', 'Hebreus', 13, 8, NULL),
  ('jesus', 'E andai em amor, como também Cristo vos amou e se entregou a si mesmo por nós, em oferta e sacrifício a Deus, em cheiro suave.', 'Efésios 5:2', 'Efésios', 5, 2, NULL),
  ('jesus', 'A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém!', 'Apocalipse 22:21', 'Apocalipse', 22, 21, NULL),
  ('jesus', 'Antes, santificai a Cristo, como Senhor, em vosso coração; e estai sempre preparados para responder com mansidão e temor a qualquer que vos pedir a razão da esperança que há em vós.', '1 Pedro 3:15', '1 Pedro', 3, 15, NULL),
  ('jesus', 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas.', 'Efésios 2:10', 'Efésios', 2, 10, NULL),
  ('jesus', 'Verdadeiramente, ele tomou sobre si as nossas enfermidades e as nossas dores levou sobre si; e nós o reputamos por aflito, ferido de Deus e oprimido.', 'Isaías 53:4', 'Isaías', 53, 4, NULL),
  ('jesus', 'E a paz de Deus, para a qual também fostes chamados em um corpo, domine em vossos corações; e sede agradecidos.', 'Colossenses 3:15', 'Colossenses', 3, 15, NULL),
  ('jesus', 'Que, sendo em forma de Deus, não teve por usurpação ser igual a Deus. Mas aniquilou-se a si mesmo, tomando a forma de servo, fazendo-se semelhante aos homens; e, achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte e morte de cruz.', 'Filipenses 2:6-8', 'Filipenses', 2, 6, 8),
  ('jesus', 'Na verdade, na verdade vos digo que se alguém receber o que eu enviar, me recebe a mim, e quem me recebe a mim recebe aquele que me enviou.', 'João 13:20', 'João', 13, 20, NULL),
  ('jesus', 'Porque o Filho do Homem veio buscar e salvar o que se havia perdido.', 'Lucas 19:10', 'Lucas', 19, 10, NULL),
  ('jesus', 'É necessário que ele cresça e que eu diminua.', 'João 3:30', 'João', 3, 30, NULL),
  ('jesus', 'Assim que, se alguém está em Cristo, nova criatura é: as coisas velhas já passaram; eis que tudo se fez novo.', '2 Coríntios 5:17', '2 Coríntios', 5, 17, NULL),
  ('jesus', 'Porque Deus enviou o seu Filho ao mundo não para que condenasse o mundo, mas para que o mundo fosse salvo por ele.', 'João 3:17', 'João', 3, 17, NULL),
  ('jesus', 'Eu sou a porta; se alguém entrar por mim, salvar-se-á, e entrará, e sairá, e achará pastagens.', 'João 10:9', 'João', 10, 9, NULL),
  ('jesus', 'Porque assim como em um corpo temos muitos membros, e nem todos os membros têm a mesma operação, assim nós, que somos muitos, somos um só corpo em Cristo, mas individualmente somos membros uns dos outros.', 'Romanos 12:4-5', 'Romanos', 12, 4, 5),
  ('jesus', 'Disse-lhes ele: E vós, quem dizeis que eu sou? E Simão Pedro, respondendo, disse: Tu és o Cristo, o Filho do Deus vivo.', 'Mateus 16:15-16', 'Mateus', 16, 15, 16),
  ('jesus', 'Antes, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo.', 'Efésios 4:15', 'Efésios', 4, 15, NULL),
  ('jesus', 'Se me amardes, guardareis os meus mandamentos.', 'João 14:15', 'João', 14, 15, NULL),
  ('jesus', 'Jesus respondeu e disse-lhes: A obra de Deus é esta: que creiais naquele que ele enviou.', 'João 6:29', 'João', 6, 29, NULL),
  ('jesus', 'Porque nele habita corporalmente toda a plenitude da divindade. E estais perfeitos nele, que é a cabeça de todo principado e potestade.', 'Colossenses 2:9-10', 'Colossenses', 2, 9, 10),
  ('jesus', 'Porque um menino nos nasceu, um filho se nos deu; e o principado está sobre os seus ombros; e o seu nome será Maravilhoso Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz.', 'Isaías 9:6', 'Isaías', 9, 6, NULL),
  ('jesus', 'Seja-vos, pois, notório, varões irmãos, que por este se vos anuncia a remissão dos pecados. E de tudo o que, pela lei de Moisés, não pudestes ser justificados, por ele é justificado todo aquele que crê.', 'Atos 13:38-39', 'Atos', 13, 38, 39),
  ('jesus', 'E a vida eterna é esta: que conheçam a ti só por único Deus verdadeiro e a Jesus Cristo, a quem enviaste.', 'João 17:3', 'João', 17, 3, NULL),
  ('jesus', 'Se o mundo vos aborrece, sabei que, primeiro do que a vós, me aborreceu a mim.', 'João 15:18', 'João', 15, 18, NULL),
  ('jesus', 'Eu sou a videira, vós, as varas; quem está em mim, e eu nele, este dá muito fruto, porque sem mim nada podereis fazer.', 'João 15:5', 'João', 15, 5, NULL),
  ('jesus', 'Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida.', '1 João 5:12', '1 João', 5, 12, NULL),
  ('jesus', 'Era desprezado e o mais indigno entre os homens, homem de dores, experimentado nos trabalhos e, como um de quem os homens escondiam o rosto, era desprezado, e não fizemos dele caso algum.', 'Isaías 53:3', 'Isaías', 53, 3, NULL),
  ('jesus', 'Pelo que também Deus o exaltou soberanamente e lhe deu um nome que é sobre todo o nome, para que ao nome de Jesus se dobre todo joelho dos que estão nos céus, e na terra, e debaixo da terra.', 'Filipenses 2:9-10', 'Filipenses', 2, 9, 10),
  ('jesus', 'Porque para mim o viver é Cristo, e o morrer é ganho.', 'Filipenses 1:21', 'Filipenses', 1, 21, NULL),
  ('jesus', 'E o Verbo se fez carne e habitou entre nós, e vimos a sua glória, como a glória do Unigênito do Pai, cheio de graça e de verdade.', 'João 1:14', 'João', 1, 14, NULL),
  ('jesus', 'Mas Deus, que é riquíssimo em misericórdia, pelo seu muito amor com que nos amou, estando nós ainda mortos em nossas ofensas, nos vivificou juntamente com Cristo (pela graça sois salvos).', 'Efésios 2:4-5', 'Efésios', 2, 4, 5),
  ('jesus', 'Todavia, para nós há um só Deus, o Pai, de quem é tudo e para quem nós vivemos; e um só Senhor, Jesus Cristo, pelo qual são todas as coisas, e nós por ele.', '1 Coríntios 8:6', '1 Coríntios', 8, 6, NULL),
  ('jesus', 'E o testemunho é este: que Deus nos deu a vida eterna; e esta vida está em seu Filho.', '1 João 5:11', '1 João', 5, 11, NULL),
  ('jesus', 'Se vós me conhecêsseis a mim, também conheceríeis a meu Pai; e já desde agora o conheceis e o tendes visto.', 'João 14:7', 'João', 14, 7, NULL),
  ('jesus', 'Conhecemos o amor nisto: que ele deu a sua vida por nós, e nós devemos dar a vida pelos irmãos.', '1 João 3:16', '1 João', 3, 16, NULL),
  ('jesus', 'Disse-lhe Jesus: Porque me viste, Tomé, creste; bem-aventurados os que não viram e creram!', 'João 20:29', 'João', 20, 29, NULL),
  ('jesus', 'Porque o Filho do Homem também não veio para ser servido, mas para servir e dar a sua vida em resgate de muitos.', 'Marcos 10:45', 'Marcos', 10, 45, NULL),
  ('jesus', 'Quem é que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus?', '1 João 5:5', '1 João', 5, 5, NULL),
  ('jesus', 'E disse-lhes: Ide por todo o mundo, pregai o evangelho a toda criatura.', 'Marcos 16:15', 'Marcos', 16, 15, NULL),
  ('jesus', 'Não vos deixarei órfãos; voltarei para vós.', 'João 14:18', 'João', 14, 18, NULL),
  ('jesus', 'Portanto, recebei-vos uns aos outros, como também Cristo nos recebeu para glória de Deus.', 'Romanos 15:7', 'Romanos', 15, 7, NULL),
  ('jesus', 'Sabendo que não foi com coisas corruptíveis, como prata ou ouro, que fostes resgatados da vossa vã maneira de viver que, por tradição, recebestes dos vossos pais, mas com o precioso sangue de Cristo, como de um cordeiro imaculado e incontaminado.', '1 Pedro 1:18-19', '1 Pedro', 1, 18, 19);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('jesus', 'Se guardardes os meus mandamentos, permanecereis no meu amor, do mesmo modo que eu tenho guardado os mandamentos de meu Pai e permaneço no seu amor.', 'João 15:10', 'João', 15, 10, NULL),
  ('jesus', 'Tu, pois, meu filho, fortifica-te na graça que há em Cristo Jesus.', '2 Timóteo 2:1', '2 Timóteo', 2, 1, NULL),
  ('jesus', 'Ele é a pedra que foi rejeitada por vós, os edificadores, a qual foi posta por cabeça de esquina.', 'Atos 4:11', 'Atos', 4, 11, NULL),
  ('jesus', 'Eu não vim chamar os justos, mas sim os pecadores, ao arrependimento.', 'Lucas 5:32', 'Lucas', 5, 32, NULL),
  ('jesus', 'Vós me chamais Mestre e Senhor e dizeis bem, porque eu o sou.', 'João 13:13', 'João', 13, 13, NULL),
  ('jesus', 'Estas coisas vos escrevi, para que saibais que tendes a vida eterna e para que creiais no nome do Filho de Deus.', '1 João 5:13', '1 João', 5, 13, NULL),
  ('jesus', 'E, estando ele ainda a falar, eis que uma nuvem luminosa os cobriu. E da nuvem saiu uma voz que dizia: Este é o meu Filho amado, em quem me comprazo; escutai-o.', 'Mateus 17:5', 'Mateus', 17, 5, NULL),
  ('jesus', 'Não cuideis que vim trazer a paz à terra; não vim trazer paz, mas espada.', 'Mateus 10:34', 'Mateus', 10, 34, NULL),
  ('jesus', 'E eis que cedo venho, e o meu galardão está comigo para dar a cada um segundo a sua obra.', 'Apocalipse 22:12', 'Apocalipse', 22, 12, NULL),
  ('jesus', 'Mas, por isso, alcancei misericórdia, para que em mim, que sou o principal, Jesus Cristo mostrasse toda a sua longanimidade, para exemplo dos que haviam de crer nele para a vida eterna.', '1 Timóteo 1:16', '1 Timóteo', 1, 16, NULL),
  ('jesus', 'E, se o Espírito daquele que dos mortos ressuscitou a Jesus habita em vós, aquele que dos mortos ressuscitou a Cristo também vivificará o vosso corpo mortal, pelo seu Espírito que em vós habita.', 'Romanos 8:11', 'Romanos', 8, 11, NULL),
  ('jesus', 'E sabemos que já o Filho de Deus é vindo e nos deu entendimento para conhecermos o que é verdadeiro; e no que é verdadeiro estamos, isto é, em seu Filho Jesus Cristo. Este é o verdadeiro Deus e a vida eterna.', '1 João 5:20', '1 João', 5, 20, NULL),
  ('jesus', 'Ao que vencer, lhe concederei que se assente comigo no meu trono, assim como eu venci e me assentei com meu Pai no seu trono.', 'Apocalipse 3:21', 'Apocalipse', 3, 21, NULL),
  ('jesus', 'E eu lhes fiz conhecer o teu nome e lho farei conhecer mais, para que o amor com que me tens amado esteja neles, e eu neles esteja.', 'João 17:26', 'João', 17, 26, NULL),
  ('jesus', 'Bem-aventurados sereis quando os homens vos aborrecerem, e quando vos separarem, e vos injuriarem, e rejeitarem o vosso nome como mau, por causa do Filho do Homem.', 'Lucas 6:22', 'Lucas', 6, 22, NULL),
  ('jesus', 'Porque Cristo, estando nós ainda fracos, morreu a seu tempo pelos ímpios.', 'Romanos 5:6', 'Romanos', 5, 6, NULL),
  ('jesus', 'Prossigo para o alvo, pelo prêmio da soberana vocação de Deus em Cristo Jesus.', 'Filipenses 3:14', 'Filipenses', 3, 14, NULL),
  ('jesus', 'Mas a nossa cidade está nos céus, donde também esperamos o Salvador, o Senhor Jesus Cristo.', 'Filipenses 3:20', 'Filipenses', 3, 20, NULL),
  ('jesus', 'Aquele que testifica estas coisas diz: Certamente, cedo venho. Amém! Ora, vem, Senhor Jesus!', 'Apocalipse 22:20', 'Apocalipse', 22, 20, NULL),
  ('jesus', 'A graça de nosso Senhor Jesus Cristo seja com vós todos. Amém!', 'Filipenses 4:23', 'Filipenses', 4, 23, NULL),
  ('jesus', 'Se vós estiverdes em mim, e as minhas palavras estiverem em vós, pedireis tudo o que quiserdes, e vos será feito.', 'João 15:7', 'João', 15, 7, NULL),
  ('jesus', 'Se, pois, o Filho vos libertar, verdadeiramente, sereis livres.', 'João 8:36', 'João', 8, 36, NULL),
  ('jesus', 'Disse-lhes, pois, Jesus: Ainda um pouco de tempo estou convosco e, depois, vou para aquele que me enviou.', 'João 7:33', 'João', 7, 33, NULL),
  ('jesus', 'Aos quais Deus quis fazer conhecer quais são as riquezas da glória deste mistério entre os gentios, que é Cristo em vós, esperança da glória.', 'Colossenses 1:27', 'Colossenses', 1, 27, NULL),
  ('jesus', 'Tendo por certo isto mesmo: que aquele que em vós começou a boa obra a aperfeiçoará até ao Dia de Jesus Cristo.', 'Filipenses 1:6', 'Filipenses', 1, 6, NULL),
  ('jesus', 'Eu sou o pão vivo que desceu do céu; se alguém comer desse pão, viverá para sempre; e o pão que eu der é a minha carne, que eu darei pela vida do mundo.', 'João 6:51', 'João', 6, 51, NULL),
  ('jesus', 'Porque, como as aflições de Cristo são abundantes em nós, assim também a nossa consolação sobeja por meio de Cristo.', '2 Coríntios 1:5', '2 Coríntios', 1, 5, NULL),
  ('jesus', 'Na casa de meu Pai há muitas moradas; se não fosse assim, eu vo-lo teria dito, pois vou preparar-vos lugar.', 'João 14:2', 'João', 14, 2, NULL),
  ('jesus', 'Porque, se cremos que Jesus morreu e ressuscitou, assim também aos que em Jesus dormem Deus os tornará a trazer com ele.', '1 Tessalonicenses 4:14', '1 Tessalonicenses', 4, 14, NULL),
  ('jesus', 'E, no último dia, o grande dia da festa, Jesus pôs-se em pé e clamou, dizendo: Se alguém tem sede, que venha a mim e beba.', 'João 7:37', 'João', 7, 37, NULL),
  ('jesus', 'Eis que vem com as nuvens, e todo olho o verá, até os mesmos que o traspassaram; e todas as tribos da terra se lamentarão sobre ele. Sim! Amém!', 'Apocalipse 1:7', 'Apocalipse', 1, 7, NULL),
  ('jesus', 'Trabalhai não pela comida que perece, mas pela comida que permanece para a vida eterna, a qual o Filho do Homem vos dará, porque a este o Pai, Deus, o selou.', 'João 6:27', 'João', 6, 27, NULL),
  ('jesus', 'Graça e paz de Deus, nosso Pai, e do Senhor Jesus Cristo.', 'Romanos 1:7b', 'Romanos 1:7b', NULL, NULL, NULL),
  ('jesus', 'A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com vós todos. Amém!', '2 Coríntios 13:13', '2 Coríntios', 13, 13, NULL),
  ('jesus', 'Tenho-vos dito isso para que a minha alegria permaneça em vós, e a vossa alegria seja completa.', 'João 15:11', 'João', 15, 11, NULL),
  ('jesus', 'E tudo quanto pedirdes em meu nome, eu o farei, para que o Pai seja glorificado no Filho.', 'João 14:13', 'João', 14, 13, NULL),
  ('jesus', 'E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. De boa vontade, pois, me gloriarei nas minhas fraquezas, para que em mim habite o poder de Cristo.', '2 Coríntios 12:9', '2 Coríntios', 12, 9, NULL),
  ('jesus', 'Mas revesti-vos do Senhor Jesus Cristo e não tenhais cuidado da carne em suas concupiscências.', 'Romanos 13:14', 'Romanos', 13, 14, NULL),
  ('jesus', 'Porque primeiramente vos entreguei o que também recebi: que Cristo morreu por nossos pecados, segundo as Escrituras, e que foi sepultado, e que ressuscitou ao terceiro dia, segundo as Escrituras.', '1 Coríntios 15:3-4', '1 Coríntios', 15, 3, 4),
  ('jesus', 'Ou não sabeis que todos quantos fomos batizados em Jesus Cristo fomos batizados na sua morte?', 'Romanos 6:3', 'Romanos', 6, 3, NULL),
  ('jesus', 'Qualquer que nega o Filho também não tem o Pai; e aquele que confessa o Filho tem também o Pai.', '1 João 2:23', '1 João', 2, 23, NULL),
  ('jesus', 'Mas agora alcançou ele ministério tanto mais excelente, quanto é mediador de um melhor concerto, que está confirmado em melhores promessas.', 'Hebreus 8:6', 'Hebreus', 8, 6, NULL),
  ('jesus', 'Assim que já não sois estrangeiros, nem forasteiros, mas concidadãos dos Santos e da família de Deus; edificados sobre o fundamento dos apóstolos e dos profetas, de que Jesus Cristo é a principal pedra da esquina.', 'Efésios 2:19-20', 'Efésios', 2, 19, 20),
  ('jesus', 'Estai, pois, firmes na liberdade com que Cristo nos libertou e não torneis a meter-vos debaixo do jugo da servidão.', 'Gálatas 5:1', 'Gálatas', 5, 1, NULL),
  ('jesus', 'E ele, assentando-se, chamou os doze e disse-lhes: Se alguém quiser ser o primeiro, será o derradeiro de todos e o servo de todos.', 'Marcos 9:35', 'Marcos', 9, 35, NULL),
  ('jesus', 'Não aniquilo a graça de Deus; porque, se a justiça provém da lei, segue-se que Cristo morreu debalde.', 'Gálatas 2:21', 'Gálatas', 2, 21, NULL),
  ('jesus', 'Se alguém me serve, siga-me; e, onde eu estiver, ali estará também o meu servo. E, se alguém me servir, meu Pai o honrará.', 'João 12:26', 'João', 12, 26, NULL),
  ('jesus', 'Desde então, começou Jesus a pregar e a dizer: Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 4:17', 'Mateus', 4, 17, NULL),
  ('jesus', 'E, por cima da sua cabeça, puseram escrita a sua acusação: Este é Jesus, O Rei dos Judeus.', 'Mateus 27:37', 'Mateus', 27, 37, NULL),
  ('jesus', 'E aconteceu que, estando eles ali, se cumpriram os dias em que ela havia de dar à luz. E deu à luz o seu filho primogênito, e envolveu-o em panos, e deitou-o numa manjedoura, porque não havia lugar para eles na estalagem.', 'Lucas 2:6-7', 'Lucas', 2, 6, 7);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('jesus', 'E também todos os que piamente querem viver em Cristo Jesus padecerão perseguições.', '2 Timóteo 3:12', '2 Timóteo', 3, 12, NULL),
  ('jesus', 'Assim como o Pai, que vive, me enviou, e eu vivo pelo Pai, assim quem de mim se alimenta também viverá por mim.', 'João 6:57', 'João', 6, 57, NULL),
  ('jesus', 'Mas, agora, em Cristo Jesus, vós, que antes estáveis longe, já pelo sangue de Cristo chegastes perto.', 'Efésios 2:13', 'Efésios', 2, 13, NULL),
  ('jesus', 'Pai, aqueles que me deste quero que, onde eu estiver, também eles estejam comigo, para que vejam a minha glória que me deste; porque tu me hás amado antes da criação do mundo.', 'João 17:24', 'João', 17, 24, NULL),
  ('jesus', 'Fiel é Deus, pelo qual fostes chamados para a comunhão de seu Filho Jesus Cristo, nosso Senhor.', '1 Coríntios 1:9', '1 Coríntios', 1, 9, NULL),
  ('jesus', 'Isto é, Deus estava em Cristo reconciliando consigo o mundo, não lhes imputando os seus pecados, e pôs em nós a palavra da reconciliação.', '2 Coríntios 5:19', '2 Coríntios', 5, 19, NULL),
  ('jesus', 'Deus nunca foi visto por alguém. O Filho unigênito, que está no seio do Pai, este o fez conhecer.', 'João 1:18', 'João', 1, 18, NULL),
  ('jesus', 'Quem come a minha carne e bebe o meu sangue permanece em mim, e eu, nele.', 'João 6:56', 'João', 6, 56, NULL),
  ('jesus', 'Portanto, se vos disserem: Eis que ele está no deserto, não saiais; ou: Eis que ele está no interior da casa, não acrediteis. Porque, assim como o relâmpago sai do oriente e se mostra até ao ocidente, assim será também a vinda do Filho do Homem.', 'Mateus 24:26-27', 'Mateus', 24, 26, 27),
  ('jesus', 'Disse-lhes, pois, Jesus outra vez: Paz seja convosco! Assim como o Pai me enviou, também eu vos envio a vós.', 'João 20:21', 'João', 20, 21, NULL),
  ('jesus', 'Bem como o Filho do Homem não veio para ser servido, mas para servir e para dar a sua vida em resgate de muitos.', 'Mateus 20:28', 'Mateus', 20, 28, NULL),
  ('jesus', 'Para conhecê-lo, e a virtude da sua ressurreição, e a comunicação de suas aflições, sendo feito conforme a sua morte.', 'Filipenses 3:10', 'Filipenses', 3, 10, NULL),
  ('jesus', 'Nisto não há judeu nem grego; não há servo nem livre; não há macho nem fêmea; porque todos vós sois um em Cristo Jesus.', 'Gálatas 3:28', 'Gálatas', 3, 28, NULL),
  ('jesus', 'E ela dará à luz um filho, e lhe porás o nome de Jesus, porque ele salvará o seu povo dos seus pecados.', 'Mateus 1:21', 'Mateus', 1, 21, NULL),
  ('jesus', 'E, se qualquer disser alguma palavra contra o Filho do Homem, ser-lhe-á perdoado, mas, se alguém falar contra o Espírito Santo, não lhe será perdoado, nem neste século nem no futuro.', 'Mateus 12:32', 'Mateus', 12, 32, NULL),
  ('jesus', 'E disse-lhes: Qualquer que receber esta criança em meu nome recebe-me a mim; e qualquer que me recebe a mim recebe o que me enviou; porque aquele que entre vós todos for o menor, esse mesmo é grande.', 'Lucas 9:48', 'Lucas', 9, 48, NULL),
  ('jesus', 'E, chamando a si a multidão, com os seus discípulos, disse-lhes: Se alguém quiser vir após mim, negue-se a si mesmo, e tome a sua cruz, e siga-me.', 'Marcos 8:34', 'Marcos', 8, 34, NULL),
  ('jesus', 'Portanto, o que desde o princípio ouvistes permaneça em vós. Se em vós permanecer o que desde o princípio ouvistes, também permanecereis no Filho e no Pai.', '1 João 2:24', '1 João', 2, 24, NULL),
  ('jesus', 'Disse-lhe Jesus: Não me detenhas, porque ainda não subi para meu Pai, mas vai para meus irmãos e dize-lhes que eu subo para meu Pai e vosso Pai, meu Deus e vosso Deus.', 'João 20:17', 'João', 20, 17, NULL),
  ('jesus', 'E disse-lhes: Vinde após mim, e eu vos farei pescadores de homens.', 'Mateus 4:19', 'Mateus', 4, 19, NULL),
  ('jesus', 'Portanto, cingindo os lombos do vosso entendimento, sede sóbrios e esperai inteiramente na graça que se vos ofereceu na revelação de Jesus Cristo.', '1 Pedro 1:13', '1 Pedro', 1, 13, NULL),
  ('jesus', 'Ora, o Senhor, depois de lhes ter falado, foi recebido no céu e assentou-se à direita de Deus.', 'Marcos 16:19', 'Marcos', 16, 19, NULL),
  ('jesus', 'Porque, em Jesus Cristo, nem a circuncisão nem a incircuncisão têm virtude alguma, mas, sim, a fé que opera por amor.', 'Gálatas 5:6', 'Gálatas', 5, 6, NULL),
  ('jesus', 'E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo e recebido acima, na glória.', '1 Timóteo 3:16', '1 Timóteo', 3, 16, NULL),
  ('jesus', 'Mas vós, amados, edificando-vos a vós mesmos sobre a vossa santíssima fé, orando no Espírito Santo, conservai a vós mesmos no amor de Deus, esperando a misericórdia de nosso Senhor Jesus Cristo, para a vida eterna.', 'Judas 1:20-21', 'Judas', 1, 20, 21),
  ('jesus', 'Para que os seus corações sejam consolados, e estejam unidos em amor e enriquecidos da plenitude da inteligência, para conhecimento do mistério de Deus — Cristo.', 'Colossenses 2:2', 'Colossenses', 2, 2, NULL),
  ('jesus', 'Portanto, ninguém vos julgue pelo comer, ou pelo beber, ou por causa dos dias de festa, ou da lua nova, ou dos sábados, que são sombras das coisas futuras, mas o corpo é de Cristo.', 'Colossenses 2:16-17', 'Colossenses', 2, 16, 17),
  ('jesus', 'Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor, em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados.', 'Colossenses 1:13-14', 'Colossenses', 1, 13, 14),
  ('jesus', 'Mas, quando vier o Consolador, que eu da parte do Pai vos hei de enviar, aquele Espírito da verdade, que procede do Pai, testificará de mim.', 'João 15:26', 'João', 15, 26, NULL),
  ('jesus', 'De sorte que, exaltado pela destra de Deus e tendo recebido do Pai a promessa do Espírito Santo, derramou isto que vós agora vedes e ouvis.', 'Atos 2:33', 'Atos', 2, 33, NULL),
  ('jesus', 'E levou-os fora, até Betânia; e, levantando as mãos, os abençoou. E aconteceu que, abençoando-os ele, se apartou deles e foi elevado ao céu.', 'Lucas 24:50-51', 'Lucas', 24, 50, 51),
  ('jesus', 'E, respondendo o anjo, disse-lhe: Descerá sobre ti o Espírito Santo, e a virtude do Altíssimo te cobrirá com a sua sombra; pelo que também o Santo, que de ti há de nascer, será chamado Filho de Deus.', 'Lucas 1:35', 'Lucas', 1, 35, NULL),
  ('jesus', 'Porém ele disse-lhes: Não vos assusteis; buscais a Jesus, o Nazareno, que foi crucificado; já ressuscitou, não está aqui; eis aqui o lugar onde o puseram.', 'Marcos 16:6', 'Marcos', 16, 6, NULL),
  ('jesus', 'Aba, Pai, todas as coisas te são possíveis; afasta de mim este cálice; não seja, porém, o que eu quero, mas o que tu queres.', 'Marcos 14:36', 'Marcos', 14, 36, NULL),
  ('jesus', 'Jesus respondeu e disse-lhes: A minha doutrina não é minha, mas daquele que me enviou.', 'João 7:16', 'João', 7, 16, NULL),
  ('jesus', 'Ou pensas tu que eu não poderia, agora, orar a meu Pai e que ele não me daria mais de doze legiões de anjos?', 'Mateus 26:53', 'Mateus', 26, 53, NULL),
  ('jesus', 'Ora, se eu, Senhor e Mestre, vos lavei os pés, vós deveis também lavar os pés uns aos outros.', 'João 13:14', 'João', 13, 14, NULL),
  ('jesus', 'E, tomando o pão e havendo dado graças, partiu-o e deu-lho, dizendo: Isto é o meu corpo, que por vós é dado; fazei isso em memória de mim.', 'Lucas 22:19', 'Lucas', 22, 19, NULL),
  ('jesus', 'Mas aquele Consolador, o Espírito Santo, que o Pai enviará em meu nome, vos ensinará todas as coisas e vos fará lembrar de tudo quanto vos tenho dito.', 'João 14:26', 'João', 14, 26, NULL),
  ('jesus', 'Porque, assim como a morte veio por um homem, também a ressurreição dos mortos veio por um homem.', '1 Coríntios 15:21', '1 Coríntios', 15, 21, NULL),
  ('jesus', 'Não cuideis que vim destruir a lei ou os profetas; não vim ab-rogar, mas cumprir.', 'Mateus 5:17', 'Mateus', 5, 17, NULL),
  ('jesus', 'Tudo isso aconteceu para que se cumprisse o que foi dito da parte do Senhor pelo profeta, que diz: Eis que a virgem conceberá e dará à luz um filho, e ele será chamado pelo nome de Emanuel. (Emanuel traduzido é: Deus conosco).', 'Mateus 1:22-23', 'Mateus', 1, 22, 23),
  ('jesus', 'Disse-lhe, então, o anjo: Maria, não temas, porque achaste graça diante de Deus, E eis que em teu ventre conceberás, e darás à luz um filho, e pôr-lhe-ás o nome de Jesus.', 'Lucas 1:30-31', 'Lucas', 1, 30, 31),
  ('jesus', 'Disse-lhe Jesus: Se queres ser perfeito, vai, vende tudo o que tens, dá-o aos pobres e terás um tesouro no céu; e vem e segue-me.', 'Mateus 19:21', 'Mateus', 19, 21, NULL),
  ('jesus', 'Porque nada me propus saber entre vós, senão a Jesus Cristo e este crucificado.', '1 Coríntios 2:2', '1 Coríntios', 2, 2, NULL),
  ('jesus', 'E, quando dizia isto, vendo-o eles, foi elevado às alturas, e uma nuvem o recebeu, ocultando-o a seus olhos.', 'Atos 1:9', 'Atos', 1, 9, NULL),
  ('jesus', 'E tu, Belém Efrata, posto que pequena entre milhares de Judá, de ti me sairá o que será Senhor em Israel, e cujas origens são desde os tempos antigos, desde os dias da eternidade.', 'Miqueias 5:2', 'Miqueias', 5, 2, NULL),
  ('jesus', 'Mas não é assim o dom gratuito como a ofensa; porque, se, pela ofensa de um, morreram muitos, muito mais a graça de Deus e o dom pela graça, que é de um só homem, Jesus Cristo, abundou sobre muitos.', 'Romanos 5:15', 'Romanos', 5, 15, NULL),
  ('jesus', 'E, estando com os olhos fitos no céu, enquanto ele subia, eis que junto deles se puseram dois varões vestidos de branco, os quais lhes disseram: Varões galileus, por que estais olhando para o céu? Esse Jesus, que dentre vós foi recebido em cima no céu, há de vir assim como para o céu o vistes ir.', 'Atos 1:10-11', 'Atos', 1, 10, 11),
  ('jesus', 'Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também.', '1 Coríntios 12:12', '1 Coríntios', 12, 12, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('jesus', 'Portanto, o mesmo Senhor vos dará um sinal: eis que uma virgem conceberá, e dará à luz um filho, e será o seu nome Emanuel.', 'Isaías 7:14', 'Isaías', 7, 14, NULL),
  ('jesus', 'Mas Paulo disse: Certamente João batizou com o batismo do arrependimento, dizendo ao povo que cresse no que após ele havia de vir, isto é, em Jesus Cristo.', 'Atos 19:4', 'Atos', 19, 4, NULL),
  ('jesus', 'Mas, quando eles o viram andar sobre o mar, pensaram que era um fantasma e deram grandes gritos. Porque todos o viram e perturbaram-se; mas logo falou com eles e disse-lhes: Tende bom ânimo, sou eu; não temais.', 'Marcos 6:49-50', 'Marcos', 6, 49, 50),
  ('jesus', 'E, quando Jesus tomou o vinagre, disse: Está consumado. E, inclinando a cabeça, entregou o espírito.', 'João 19:30', 'João', 19, 30, NULL),
  ('jesus', 'E Jesus, cheio do Espírito Santo, voltou do Jordão e foi levado pelo Espírito ao deserto. E quarenta dias foi tentado pelo diabo, e, naqueles dias, não comeu coisa alguma, e, terminados eles, teve fome.', 'Lucas 4:1-2', 'Lucas', 4, 1, 2),
  ('jesus', 'Não está aqui, mas ressuscitou. Lembrai-vos como vos falou, estando ainda na Galileia, dizendo: Convém que o Filho do Homem seja entregue nas mãos de homens pecadores, e seja crucificado, e, ao terceiro dia, ressuscite.', 'Lucas 24:6-7', 'Lucas', 24, 6, 7),
  ('jesus', 'Vós, mulheres, sujeitai-vos a vosso marido, como ao Senhor; porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo.', 'Efésios 5:22-23', 'Efésios', 5, 22, 23),
  ('jesus', 'Alegra-te muito, ó filha de Sião; exulta, ó filha de Jerusalém; eis que o teu rei virá a ti, justo e Salvador, pobre e montado sobre um jumento, sobre um asninho, filho de jumenta.', 'Zacarias 9:9', 'Zacarias', 9, 9, NULL),
  ('jesus', 'Quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus, purificará a vossa consciência das obras mortas, para servirdes ao Deus vivo?', 'Hebreus 9:14', 'Hebreus', 9, 14, NULL),
  ('jesus', 'E eu não o conhecia, mas o que me mandou a batizar com água, esse me disse: Sobre aquele que vires descer o Espírito e sobre ele repousar, esse é o que batiza com o Espírito Santo.', 'João 1:33', 'João', 1, 33, NULL),
  ('jesus', 'E aconteceu que, como todo o povo se batizava, sendo batizado também Jesus, orando ele, o céu se abriu, e o Espírito Santo desceu sobre ele em forma corpórea, como uma pomba; e ouviu-se uma voz do céu, que dizia: Tu és meu Filho amado; em ti me tenho comprazido.', 'Lucas 3:21-22', 'Lucas', 3, 21, 22),
  ('jesus', 'E, clamando Jesus com grande voz, disse: Pai, nas tuas mãos entrego o meu espírito. E, havendo dito isso, expirou.', 'Lucas 23:46', 'Lucas', 23, 46, NULL),
  ('jesus', 'Mas o anjo, respondendo, disse às mulheres: Não tenhais medo; pois eu sei que buscai a Jesus, que foi crucificado. Ele não está aqui, porque já ressuscitou, como tinha dito. Vinde e vede o lugar onde o Senhor jazia.', 'Mateus 28:5-6', 'Mateus', 28, 5, 6),
  ('jesus', 'Eis que vamos para Jerusalém, e o Filho do Homem será entregue aos príncipes dos sacerdotes e aos escribas, e condená-lo-ão à morte. E o entregarão aos gentios para que dele escarneçam, e o açoitem, e crucifiquem, e ao terceiro dia ressuscitará.', 'Mateus 20:18-19', 'Mateus', 20, 18, 19),
  ('jesus', 'Ressuscitando Deus a seu Filho Jesus, primeiro o enviou a vós, para que nisso vos abençoasse, e vos desviasse, a cada um, das vossas maldades.', 'Atos 3:26', 'Atos', 3, 26, NULL),
  ('jesus', 'E as multidões, tanto as que iam adiante como as que o seguiam, clamavam, dizendo: Hosana ao Filho de Davi! Bendito o que vem em nome do Senhor! Hosana nas alturas!', 'Mateus 21:9', 'Mateus', 21, 9, NULL),
  ('jesus', 'Nisto conhecereis o Espírito de Deus: todo espírito que confessa que Jesus Cristo veio em carne é de Deus; e todo espírito que não confessa que Jesus Cristo veio em carne não é de Deus; mas este é o espírito do anticristo, do qual já ouvistes que há de vir, e eis que está já no mundo.', '1 João 4:2-3', '1 João', 4, 2, 3),
  ('jesus', 'Eu sou o bom Pastor; o bom Pastor dá a sua vida pelas ovelhas.', 'João 10:11', 'João', 10, 11, NULL),
  ('jesus', 'Enquanto comiam, Jesus tomou o pão, e, abençoando-o, o partiu, e o deu aos discípulos, e disse: Tomai, comei, isto é o meu corpo.', 'Mateus 26:26', 'Mateus', 26, 26, NULL),
  ('jesus', 'E eis que uma voz dos céus dizia: Este é o meu Filho amado, em quem me comprazo.', 'Mateus 3:17', 'Mateus', 3, 17, NULL),
  ('jesus', 'Examinai-vos a vós mesmos se permaneceis na fé; provai-vos a vós mesmos. Ou não sabeis, quanto a vós mesmos, que Jesus Cristo está em vós? Se não é que já estais reprovados.', '2 Coríntios 13:5', '2 Coríntios', 13, 5, NULL),
  ('jesus', 'Separados estais de Cristo, vós os que vos justificais pela lei; da graça tendes caído.', 'Gálatas 5:4', 'Gálatas', 5, 4, NULL),
  ('jesus', 'E, tomando o cálice e dando graças, deu-lho, dizendo: Bebei dele todos. Porque isto é o meu sangue, o sangue do Novo Testamento, que é derramado por muitos, para remissão dos pecados.', 'Mateus 26:27-28', 'Mateus', 26, 27, 28),
  ('jesus', 'Porque o Filho do Homem virá na glória de seu Pai, com os seus anjos; e, então, dará a cada um segundo as suas obras.', 'Mateus 16:27', 'Mateus', 16, 27, NULL),
  ('jesus', 'E percorria Jesus toda a Galileia, ensinando nas suas sinagogas, e pregando o evangelho do Reino, e curando todas as enfermidades e moléstias entre o povo.', 'Mateus 4:23', 'Mateus', 4, 23, NULL),
  ('jesus', 'E ele é a cabeça do corpo da igreja; é o princípio e o primogênito dentre os mortos, para que em tudo tenha a preeminência.', 'Colossenses 1:18', 'Colossenses', 1, 18, NULL),
  ('jesus', 'A este dão testemunho todos os profetas, de que todos os que nele creem receberão o perdão dos pecados pelo seu nome.', 'Atos 10:43', 'Atos', 10, 43, NULL),
  ('jesus', 'Ressuscitou, verdadeiramente, o Senhor e já apareceu a Simão.', 'Lucas 24:34', 'Lucas', 24, 34, NULL),
  ('julgamento', 'Portanto, és inescusável quando julgas, ó homem, quem quer que sejas, porque te condenas a ti mesmo naquilo em que julgas a outro; pois tu, que julgas, fazes o mesmo.', 'Romanos 2:1', 'Romanos', 2, 1, NULL),
  ('julgamento', 'Não julgueis, para que não sejais julgados.', 'Mateus 7:1', 'Mateus', 7, 1, NULL),
  ('julgamento', 'Todo caminho do homem é reto aos seus olhos, mas o Senhor sonda os corações.', 'Provérbios 21:2', 'Provérbios', 21, 2, NULL),
  ('julgamento', 'Assim que não nos julguemos mais uns aos outros; antes, seja o vosso propósito não pôr tropeço ou escândalo ao irmão.', 'Romanos 14:13', 'Romanos', 14, 13, NULL),
  ('julgamento', 'Mas eu vos digo que de toda palavra ociosa que os homens disserem hão de dar conta no Dia do Juízo.', 'Mateus 12:36', 'Mateus', 12, 36, NULL),
  ('julgamento', 'E por que reparas tu no argueiro que está no olho do teu irmão e não vês a trave que está no teu olho?', 'Mateus 7:3', 'Mateus', 7, 3, NULL),
  ('julgamento', 'Não julgueis, e não sereis julgados; não condeneis, e não sereis condenados; soltai, e soltar-vos-ão.', 'Lucas 6:37', 'Lucas', 6, 37, NULL),
  ('julgamento', 'Quem és tu que julgas o servo alheio? Para seu próprio senhor ele está em pé ou cai; mas estará firme, porque poderoso é Deus para o firmar.', 'Romanos 14:4', 'Romanos', 14, 4, NULL),
  ('julgamento', 'Há só um Legislador e um Juiz, que pode salvar e destruir. Tu, porém, quem és, que julgas a outrem?', 'Tiago 4:12', 'Tiago', 4, 12, NULL),
  ('julgamento', 'Toda ferramenta preparada contra ti não prosperará; e toda língua que se levantar contra ti em juízo, tu a condenarás; esta é a herança dos servos do Senhor e a sua justiça que vem de mim, diz o Senhor.', 'Isaías 54:17', 'Isaías', 54, 17, NULL),
  ('julgamento', 'E vi os mortos, grandes e pequenos, que estavam diante do trono, e abriram-se os livros. E abriu-se outro livro, que é o da vida. E os mortos foram julgados pelas coisas que estavam escritas nos livros, segundo as suas obras. E deu o mar os mortos que nele havia; e a morte e o inferno deram os mortos que neles havia; e foram julgados cada um segundo as suas obras.', 'Apocalipse 20:12-13', 'Apocalipse', 20, 12, 13),
  ('julgamento', 'Porque todos os que sem lei pecaram sem lei também perecerão; e todos os que sob a lei pecaram pela lei serão julgados.', 'Romanos 2:12', 'Romanos', 2, 12, NULL),
  ('julgamento', 'Portanto, ninguém vos julgue pelo comer, ou pelo beber, ou por causa dos dias de festa, ou da lua nova, ou dos sábados, que são sombras das coisas futuras, mas o corpo é de Cristo.', 'Colossenses 2:16-17', 'Colossenses', 2, 16, 17),
  ('julgamento', 'Porque Deus enviou o seu Filho ao mundo não para que condenasse o mundo, mas para que o mundo fosse salvo por ele.', 'João 3:17', 'João', 3, 17, NULL),
  ('julgamento', 'Venerado seja entre todos o matrimônio e o leito sem mácula; porém aos que se dão à prostituição e aos adúlteros Deus os julgará.', 'Hebreus 13:4', 'Hebreus', 13, 4, NULL),
  ('julgamento', 'O que come não despreze o que não come; e o que não come não julgue o que come; porque Deus o recebeu por seu.', 'Romanos 14:3', 'Romanos', 14, 3, NULL),
  ('julgamento', 'Portanto, agora, nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito. Porque a lei do Espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte.', 'Romanos 8:1-2', 'Romanos', 8, 1, 2),
  ('julgamento', 'Quem crê nele não é condenado; mas quem não crê já está condenado, porquanto não crê no nome do unigênito Filho de Deus.', 'João 3:18', 'João', 3, 18, NULL),
  ('julgamento', 'Com minha alma te desejei de noite e, com o meu espírito, que está dentro de mim, madrugarei a buscar-te; porque, havendo os teus juízos na terra, os moradores do mundo aprendem justiça.', 'Isaías 26:9', 'Isaías', 26, 9, NULL),
  ('julgamento', 'Antes, subjugo o meu corpo e o reduzo à servidão, para que, pregando aos outros, eu mesmo não venha de alguma maneira a ficar reprovado.', '1 Coríntios 9:27', '1 Coríntios', 9, 27, NULL),
  ('julgamento', 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus, nosso Senhor.', 'Romanos 6:23', 'Romanos', 6, 23, NULL),
  ('julgamento', 'Assim, sabe o Senhor livrar da tentação os piedosos e reservar os injustos para o Dia de Juízo, para serem castigados.', '2 Pedro 2:9', '2 Pedro', 2, 9, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('julgamento', 'Combati o bom combate, acabei a carreira, guardei a fé. Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele Dia; e não somente a mim, mas também a todos os que amarem a sua vinda.', '2 Timóteo 4:7-8', '2 Timóteo', 4, 7, 8),
  ('julgamento', 'Mas, sobretudo, meus irmãos, não jureis nem pelo céu nem pela terra, nem façais qualquer outro juramento; mas que a vossa palavra seja sim, sim e não, não, para que não caiais em condenação.', 'Tiago 5:12', 'Tiago', 5, 12, NULL),
  ('julgamento', 'Quem crer e for batizado será salvo; mas quem não crer será condenado.', 'Marcos 16:16', 'Marcos', 16, 16, NULL),
  ('julgamento', 'Visto como se não executa logo o juízo sobre a má obra, por isso o coração dos filhos dos homens está inteiramente disposto para praticar o mal.', 'Eclesiastes 8:11', 'Eclesiastes', 8, 11, NULL),
  ('julgamento', 'Pelo que, deixando os rudimentos da doutrina de Cristo, prossigamos até a perfeição, não lançando de novo o fundamento do arrependimento de obras mortas e de fé em Deus, e da doutrina dos batismos, e da imposição das mãos, e da ressurreição dos mortos, e do juízo eterno.', 'Hebreus 6:1-2', 'Hebreus', 6, 1, 2),
  ('julgamento', 'E, quando ele vier, convencerá o mundo do pecado, e da justiça, e do juízo.', 'João 16:8', 'João', 16, 8, NULL),
  ('julgamento', 'Não vos vingueis a vós mesmos, amados, mas dai lugar à ira, porque está escrito: Minha é a vingança; eu recompensarei, diz o Senhor.', 'Romanos 12:19', 'Romanos', 12, 19, NULL),
  ('julgamento', 'Mas o Dia do Senhor virá como o ladrão de noite, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se desfarão, e a terra e as obras que nela há se queimarão.', '2 Pedro 3:10', '2 Pedro', 3, 10, NULL),
  ('justica', 'O que segue a justiça e a bondade achará a vida, a justiça e a honra.', 'Provérbios 21:21', 'Provérbios', 21, 21, NULL),
  ('justica', 'Mas tu, ó homem de Deus, foge destas coisas e segue a justiça, a piedade, a fé, o amor, a paciência, a mansidão.', '1 Timóteo 6:11', '1 Timóteo', 6, 11, NULL),
  ('justica', 'O qual recompensará cada um segundo as suas obras.', 'Romanos 2:6', 'Romanos', 2, 6, NULL),
  ('justica', 'Porque o Senhor ama o juízo e não desampara os seus santos; eles são preservados para sempre; mas a descendência dos ímpios será desarraigada.', 'Salmo 37:28', 'Salmo', 37, 28, NULL),
  ('justica', 'Não erreis: Deus não se deixa escarnecer; porque tudo o que o homem semear, isso também ceifará.', 'Gálatas 6:7', 'Gálatas', 6, 7, NULL),
  ('justica', 'Todo caminho do homem é reto aos seus olhos, mas o Senhor sonda os corações.', 'Provérbios 21:2', 'Provérbios', 21, 2, NULL),
  ('justica', 'Mas buscai primeiro o Reino de Deus, e a sua justiça, e todas essas coisas vos serão acrescentadas.', 'Mateus 6:33', 'Mateus', 6, 33, NULL),
  ('justica', 'Na verdade, nunca será abalado; o justo ficará em memória eterna.', 'Salmo 112:6', 'Salmo', 112, 6, NULL),
  ('justica', 'Os olhos do Senhor estão sobre os justos; e os seus ouvidos, atentos ao seu clamor.', 'Salmo 34:15', 'Salmo', 34, 15, NULL),
  ('justica', 'Fazer justiça e julgar com retidão é mais aceitável ao Senhor do que oferecer-lhe sacrifício.', 'Provérbios 21:3', 'Provérbios', 21, 3, NULL),
  ('justica', 'Mas também, se padecerdes por amor da justiça, sois bem-aventurados. E não temais com medo deles, nem vos turbeis.', '1 Pedro 3:14', '1 Pedro', 3, 14, NULL),
  ('justica', 'E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não houvermos desfalecido.', 'Gálatas 6:9', 'Gálatas', 6, 9, NULL),
  ('justica', 'Vede que ninguém dê a outrem mal por mal, mas segui, sempre, o bem, tanto uns para com os outros como para com todos.', '1 Tessalonicenses 5:15', '1 Tessalonicenses', 5, 15, NULL),
  ('justica', 'Àquele que não conheceu pecado, o fez pecado por nós; para que, nele, fôssemos feitos justiça de Deus.', '2 Coríntios 5:21', '2 Coríntios', 5, 21, NULL),
  ('justica', 'Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará. E ele fará sobressair a tua justiça como a luz; e o teu juízo, como o meio-dia.', 'Salmo 37:5-6', 'Salmo', 37, 5, 6),
  ('justica', 'Quanto ao mais, irmãos, tudo o que é verdadeiro, tudo o que é honesto, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se há alguma virtude, e se há algum louvor, nisso pensai.', 'Filipenses 4:8', 'Filipenses', 4, 8, NULL),
  ('justica', 'Ora, o fruto da justiça semeia-se na paz, para os que exercitam a paz.', 'Tiago 3:18', 'Tiago', 3, 18, NULL),
  ('justica', 'Porque a graça de Deus se há manifestado, trazendo salvação a todos os homens, ensinando-nos que, renunciando à impiedade e às concupiscências mundanas, vivamos neste presente século sóbria, justa e piamente.', 'Tito 2:11-12', 'Tito', 2, 11, 12),
  ('justica', 'Bem-aventurado o varão que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores.', 'Salmo 1:1', 'Salmo', 1, 1, NULL),
  ('justica', 'Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.', 'Mateus 5:6', 'Mateus', 5, 6, NULL),
  ('justica', 'Os tesouros da impiedade de nada aproveitam; mas a justiça livra da morte.', 'Provérbios 10:2', 'Provérbios', 10, 2, NULL),
  ('justica', 'O ímpio recebe um salário enganoso, mas, para o que semeia justiça, haverá galardão certo.', 'Provérbios 11:18', 'Provérbios', 11, 18, NULL),
  ('justica', 'E, se fizerdes bem aos que vos fazem bem, que recompensa tereis? Também os pecadores fazem o mesmo.', 'Lucas 6:33', 'Lucas', 6, 33, NULL),
  ('justica', 'Toda ferramenta preparada contra ti não prosperará; e toda língua que se levantar contra ti em juízo, tu a condenarás; esta é a herança dos servos do Senhor e a sua justiça que vem de mim, diz o Senhor.', 'Isaías 54:17', 'Isaías', 54, 17, NULL),
  ('justica', 'Laço é para o homem dizer precipitadamente: É santo; e, feitos os votos, então, inquirir.', 'Provérbios 20:25', 'Provérbios', 20, 25, NULL),
  ('justica', 'De todo o meu coração te busquei; não me deixes desviar dos teus mandamentos.', 'Salmo 119:10', 'Salmo', 119, 10, NULL),
  ('justica', 'Muitas são as aflições do justo, mas o Senhor o livra de todas.', 'Salmo 34:19', 'Salmo', 34, 19, NULL),
  ('justica', 'Abre a tua boca, julga retamente e faze justiça aos pobres e aos necessitados.', 'Provérbios 31:9', 'Provérbios', 31, 9, NULL),
  ('justica', 'Chegai-vos a Deus, e ele se chegará a vós. Limpai as mãos, pecadores; e, vós de duplo ânimo, purificai o coração.', 'Tiago 4:8', 'Tiago', 4, 8, NULL),
  ('justica', 'Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis; a oração feita por um justo pode muito em seus efeitos.', 'Tiago 5:16', 'Tiago', 5, 16, NULL),
  ('justica', 'Lança o teu cuidado sobre o Senhor, e ele te susterá; nunca permitirá que o justo seja abalado.', 'Salmo 55:22', 'Salmo', 55, 22, NULL),
  ('justica', 'Corra, porém, o juízo como as águas, e a justiça, como o ribeiro impetuoso.', 'Amós 5:24', 'Amós', 5, 24, NULL),
  ('justica', 'Então, entenderás justiça, e juízo, e equidade, e todas as boas veredas.', 'Provérbios 2:9', 'Provérbios', 2, 9, NULL),
  ('justica', 'Aprendei a fazer o bem; praticai o que é reto; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas.', 'Isaías 1:17', 'Isaías', 1, 17, NULL),
  ('justica', 'Porque nele se descobre a justiça de Deus de fé em fé, como está escrito: Mas o justo viverá da fé.', 'Romanos 1:17', 'Romanos', 1, 17, NULL),
  ('justica', 'Portanto, és inescusável quando julgas, ó homem, quem quer que sejas, porque te condenas a ti mesmo naquilo em que julgas a outro; pois tu, que julgas, fazes o mesmo.', 'Romanos 2:1', 'Romanos', 2, 1, NULL),
  ('justica', 'Sonda-me, ó Deus, e conhece o meu coração; prova-me e conhece os meus pensamentos. E vê se há em mim algum caminho mau e guia-me pelo caminho eterno.', 'Salmo 139:23-24', 'Salmo', 139, 23, 24),
  ('justica', 'Porque os olhos do Senhor estão sobre os justos, e os seus ouvidos, atentos às suas orações; mas o rosto do Senhor é contra os que fazem males.', '1 Pedro 3:12', '1 Pedro', 3, 12, NULL),
  ('justica', 'Bem-aventurados os que sofrem perseguição por causa da justiça, porque deles é o Reino dos céus.', 'Mateus 5:10', 'Mateus', 5, 10, NULL),
  ('justica', 'A justiça exalta as nações, mas o pecado é o opróbrio dos povos.', 'Provérbios 14:34', 'Provérbios', 14, 34, NULL),
  ('justica', 'Ele te declarou, ó homem, o que é bom; e que é o que o Senhor pede de ti, senão que pratiques a justiça, e ames a beneficência, e andes humildemente com o teu Deus?', 'Miqueias 6:8', 'Miqueias', 6, 8, NULL),
  ('justica', 'Melhor é o pouco com justiça do que a abundância de colheita com injustiça.', 'Provérbios 16:8', 'Provérbios', 16, 8, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('justica', 'Porque o fim da lei é Cristo para justiça de todo aquele que crê.', 'Romanos 10:4', 'Romanos', 10, 4, NULL),
  ('justica', 'Porque o Senhor é o nosso Juiz; o Senhor é o nosso Legislador; o Senhor é o nosso Rei; ele nos salvará.', 'Isaías 33:22', 'Isaías', 33, 22, NULL),
  ('justica', 'Mas, agora, se manifestou, sem a lei, a justiça de Deus, tendo o testemunho da Lei e dos Profetas, isto é, a justiça de Deus pela fé em Jesus Cristo para todos e sobre todos os que creem; porque não há diferença.', 'Romanos 3:21-22', 'Romanos', 3, 21, 22),
  ('justica', 'Vale mais o pouco que tem o justo do que as riquezas de muitos ímpios. Pois os braços dos ímpios se quebrarão, mas o Senhor sustém os justos.', 'Salmo 37:16-17', 'Salmo', 37, 16, 17),
  ('justica', 'O hipócrita, com a boca, danifica o seu próximo, mas os justos são libertados pelo conhecimento.', 'Provérbios 11:9', 'Provérbios', 11, 9, NULL),
  ('justica', 'E, na verdade, toda correção, ao presente, não parece ser de gozo, senão de tristeza, mas, depois, produz um fruto pacífico de justiça nos exercitados por ela.', 'Hebreus 12:11', 'Hebreus', 12, 11, NULL),
  ('justica', 'Ele ama a justiça e o juízo; a terra está cheia da bondade do Senhor.', 'Salmo 33:5', 'Salmo', 33, 5, NULL),
  ('justica', 'Não vos prendais a um jugo desigual com os infiéis; porque que sociedade tem a justiça com a injustiça? E que comunhão tem a luz com as trevas?', '2 Coríntios 6:14', '2 Coríntios', 6, 14, NULL),
  ('justica', 'Há caminho que ao homem parece direito, mas o fim dele são os caminhos da morte.', 'Provérbios 14:12', 'Provérbios', 14, 12, NULL),
  ('justica', 'Em ti, Senhor, confio; nunca me deixes confundido; livra-me pela tua justiça.', 'Salmo 31:1', 'Salmo', 31, 1, NULL),
  ('justica', 'Porque Deus não é injusto para se esquecer da vossa obra e do trabalho de amor que, para com o seu nome, mostrastes, enquanto servistes aos santos e ainda servis.', 'Hebreus 6:10', 'Hebreus', 6, 10, NULL),
  ('justica', 'Os lábios do justo sabem o que agrada, mas a boca dos ímpios anda cheia de perversidades.', 'Provérbios 10:32', 'Provérbios', 10, 32, NULL),
  ('justica', 'Ide, porém, e aprendei o que significa: Misericórdia quero e não sacrifício. Porque eu não vim para chamar os justos, mas os pecadores, ao arrependimento.', 'Mateus 9:13', 'Mateus', 9, 13, NULL),
  ('justica', 'Não tenhas inveja do homem violento, nem escolhas nenhum de seus caminhos. Porque o perverso é abominação para o Senhor, mas com os sinceros está o seu segredo.', 'Provérbios 3:31-32', 'Provérbios', 3, 31, 32),
  ('justica', 'Regozijar-me-ei muito no Senhor, a minha alma se alegra no meu Deus, porque me vestiu de vestes de salvação, me cobriu com o manto de justiça, como um noivo que se adorna com atavios e como noiva que se enfeita com as suas joias.', 'Isaías 61:10', 'Isaías', 61, 10, NULL),
  ('justica', 'Assim falou o Senhor dos Exércitos, dizendo: Executai juízo verdadeiro, mostrai piedade e misericórdia cada um a seu irmão; e não oprimais a viúva, nem o órfão, nem o estrangeiro, nem o pobre, nem intente o mal cada um contra o seu irmão, no seu coração.', 'Zacarias 7:9-10', 'Zacarias', 7, 9, 10),
  ('justica', 'Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, pudéssemos viver para a justiça; e pelas suas feridas fostes sarados.', '1 Pedro 2:24', '1 Pedro', 2, 24, NULL),
  ('justica', 'Justo é o Senhor em todos os seus caminhos e santo em todas as suas obras.', 'Salmo 145:17', 'Salmo', 145, 17, NULL),
  ('justica', 'Ó Senhor, ouve a minha oração! Inclina os ouvidos às minhas súplicas; escuta-me segundo a tua verdade e segundo a tua justiça.', 'Salmo 143:1', 'Salmo', 143, 1, NULL),
  ('justica', 'Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas eu não me deixarei dominar por nenhuma.', '1 Coríntios 6:12', '1 Coríntios', 6, 12, NULL),
  ('justica', 'Sendo, pois, justificados pela fé, temos paz com Deus por nosso Senhor Jesus Cristo.', 'Romanos 5:1', 'Romanos', 5, 1, NULL),
  ('justica', 'Vós sois a luz do mundo; não se pode esconder uma cidade edificada sobre um monte.', 'Mateus 5:14', 'Mateus', 5, 14, NULL),
  ('justica', 'Defendei o pobre e o órfão; fazei justiça ao aflito e necessitado.', 'Salmo 82:3', 'Salmo', 82, 3, NULL),
  ('justica', 'Mas para vós que temeis o meu nome nascerá o sol da justiça e salvação trará debaixo das suas asas; e saireis e crescereis como os bezerros do cevadouro.', 'Malaquias 4:2', 'Malaquias', 4, 2, NULL),
  ('justica', 'Por isso, o Senhor esperará para ter misericórdia de vós; e, por isso, será exalçado para se compadecer de vós, porque o Senhor é um Deus de equidade. Bem-aventurados todos os que nele esperam.', 'Isaías 30:18', 'Isaías', 30, 18, NULL),
  ('justica', 'Porque, como, pela desobediência de um só homem, muitos foram feitos pecadores, assim, pela obediência de um, muitos serão feitos justos.', 'Romanos 5:19', 'Romanos', 5, 19, NULL),
  ('justica', 'Qualquer que pratica o pecado também pratica iniquidade, porque o pecado é iniquidade.', '1 João 3:4', '1 João', 3, 4, NULL),
  ('justica', 'Não aniquilo a graça de Deus; porque, se a justiça provém da lei, segue-se que Cristo morreu debalde.', 'Gálatas 2:21', 'Gálatas', 2, 21, NULL),
  ('justica', 'E, abrindo Pedro a boca, disse: Reconheço, por verdade, que Deus não faz acepção de pessoas; mas que lhe é agradável aquele que, em qualquer nação, o teme e faz o que é justo.', 'Atos 10:34-35', 'Atos', 10, 34, 35),
  ('justica', 'Com minha alma te desejei de noite e, com o meu espírito, que está dentro de mim, madrugarei a buscar-te; porque, havendo os teus juízos na terra, os moradores do mundo aprendem justiça.', 'Isaías 26:9', 'Isaías', 26, 9, NULL),
  ('justica', 'Mas o que a não soube e fez coisas dignas de açoites com poucos açoites será castigado. E a qualquer que muito for dado, muito se lhe pedirá, e ao que muito se lhe confiou, muito mais se lhe pedirá.', 'Lucas 12:48', 'Lucas', 12, 48, NULL),
  ('justica', 'Ele reserva a verdadeira sabedoria para os retos; escudo é para os que caminham na sinceridade.', 'Provérbios 2:7', 'Provérbios', 2, 7, NULL),
  ('justica', 'Quem é sábio, para que entenda estas coisas? Prudente, para que as saiba? Porque os caminhos do Senhor são retos, e os justos andarão neles, mas os transgressores neles cairão.', 'Oseias 14:9', 'Oseias', 14, 9, NULL),
  ('justica', 'Bom e reto é o Senhor; pelo que ensinará o caminho aos pecadores. Guiará os mansos retamente; e aos mansos ensinará o seu caminho.', 'Salmo 25:8-9', 'Salmo', 25, 8, 9),
  ('justica', 'E será para nós justiça, quando tivermos cuidado de fazer todos estes mandamentos perante o Senhor, nosso Deus, como nos tem ordenado.', 'Deuteronômio 6:25', 'Deuteronômio', 6, 25, NULL),
  ('justica', 'Bênçãos há sobre a cabeça do justo, mas a violência cobre a boca dos ímpios.', 'Provérbios 10:6', 'Provérbios', 10, 6, NULL),
  ('justica', 'Nós somos judeus por natureza e não pecadores dentre os gentios. Sabendo que o homem não é justificado pelas obras da lei, mas pela fé em Jesus Cristo, temos também crido em Jesus Cristo, para sermos justificados pela fé de Cristo e não pelas obras da lei, porquanto pelas obras da lei nenhuma carne será justificada.', 'Gálatas 2:15-16', 'Gálatas', 2, 15, 16),
  ('justica', 'Porque o fruto do Espírito está em toda bondade, e justiça, e verdade.', 'Efésios 5:9', 'Efésios', 5, 9, NULL),
  ('justica', 'Por isso, nenhuma carne será justificada diante dele pelas obras da lei, porque pela lei vem o conhecimento do pecado.', 'Romanos 3:20', 'Romanos', 3, 20, NULL),
  ('justica', 'No caminho da sabedoria, te ensinei e, pelas carreiras direitas, te fiz andar.', 'Provérbios 4:11', 'Provérbios', 4, 11, NULL),
  ('justica', 'Bem-aventurados os que trilham caminhos retos e andam na lei do Senhor.', 'Salmo 119:1', 'Salmo', 119, 1, NULL),
  ('justica', 'Instrui o menino no caminho em que deve andar, e, até quando envelhecer, não se desviará dele.', 'Provérbios 22:6', 'Provérbios', 22, 6, NULL),
  ('justica', 'Eis que a sua alma se incha, não é reta nele; mas o justo, pela sua fé, viverá.', 'Habacuque 2:4', 'Habacuque', 2, 4, NULL),
  ('justica', 'Prata escolhida é a língua do justo; o coração dos ímpios é de nenhum preço.', 'Provérbios 10:20', 'Provérbios', 10, 20, NULL),
  ('justica', 'Mas ele sabe o meu caminho; prove-me, e sairei como o ouro. Nas suas pisadas os meus pés se afirmaram; guardei o seu caminho e não me desviei dele.', 'Jó 23:10-11', 'Jó', 23, 10, 11),
  ('justica', 'Vigiai justamente e não pequeis; porque alguns ainda não têm o conhecimento de Deus; digo-o para vergonha vossa.', '1 Coríntios 15:34', '1 Coríntios', 15, 34, NULL),
  ('justica', 'A esperança dos justos é alegria, mas a expectação dos ímpios perecerá.', 'Provérbios 10:28', 'Provérbios', 10, 28, NULL),
  ('justica', 'Ele é a Rocha cuja obra é perfeita, porque todos os seus caminhos juízo são; Deus é a verdade, e não há nele injustiça; justo e reto é.', 'Deuteronômio 32:4', 'Deuteronômio', 32, 4, NULL),
  ('justica', 'Ora, aquele que dá a semente ao que semeia e pão para comer também multiplicará a vossa sementeira e aumentará os frutos da vossa justiça.', '2 Coríntios 9:10', '2 Coríntios', 9, 10, NULL),
  ('justica', 'Combati o bom combate, acabei a carreira, guardei a fé. Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele Dia; e não somente a mim, mas também a todos os que amarem a sua vinda.', '2 Timóteo 4:7-8', '2 Timóteo', 4, 7, 8);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('justica', 'Pois tu, Senhor, abençoarás ao justo; circundá-lo-ás da tua benevolência como de um escudo.', 'Salmo 5:12', 'Salmo', 5, 12, NULL),
  ('justica', 'Nem tampouco apresenteis os vossos membros ao pecado por instrumentos de iniquidade; mas apresentai-vos a Deus, como vivos dentre mortos, e os vossos membros a Deus, como instrumentos de justiça.', 'Romanos 6:13', 'Romanos', 6, 13, NULL),
  ('justica', 'Os teus olhos olhem direitos, e as tuas pálpebras olhem diretamente diante de ti.', 'Provérbios 4:25', 'Provérbios', 4, 25, NULL),
  ('justica', 'A memória do justo é abençoada, mas o nome dos ímpios apodrecerá.', 'Provérbios 10:7', 'Provérbios', 10, 7, NULL),
  ('justica', 'Para que guarde as veredas do juízo e conserve o caminho dos seus santos.', 'Provérbios 2:8', 'Provérbios', 2, 8, NULL),
  ('justica', 'Se ouvires atento a voz do Senhor, teu Deus, e fizeres o que é reto diante de seus olhos, e inclinares os teus ouvidos aos seus mandamentos, e guardares todos os seus estatutos, nenhuma das enfermidades porei sobre ti, que pus sobre o Egito; porque eu sou o Senhor, que te sara.', 'Êxodo 15:26', 'Êxodo', 15, 26, NULL),
  ('justica', 'Não aproveitam as riquezas no dia da ira, mas a justiça livra da morte.', 'Provérbios 11:4', 'Provérbios', 11, 4, NULL),
  ('justica', 'Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas nem todas as coisas edificam.', '1 Coríntios 10:23', '1 Coríntios', 10, 23, NULL),
  ('justica', 'Porque não tomo prazer na morte do que morre, diz o Senhor Jeová; convertei-vos, pois, e vivei.', 'Ezequiel 18:32', 'Ezequiel', 18, 32, NULL),
  ('justica', 'Até no caminho dos teus juízos, Senhor, te esperamos; no teu nome e na tua memória está o desejo da nossa alma.', 'Isaías 26:8', 'Isaías', 26, 8, NULL),
  ('justica', 'Ao Todo-Poderoso não podemos alcançar; grande é em poder; porém a ninguém oprime em juízo e grandeza de justiça.', 'Jó 37:23', 'Jó', 37, 23, NULL),
  ('justica', 'Não pelas obras de justiça que houvéssemos feito, mas, segundo a sua misericórdia, nos salvou pela lavagem da regeneração e da renovação do Espírito Santo.', 'Tito 3:5', 'Tito', 3, 5, NULL),
  ('justica', 'Separados estais de Cristo, vós os que vos justificais pela lei; da graça tendes caído.', 'Gálatas 5:4', 'Gálatas', 5, 4, NULL),
  ('justica', 'Agora, pois, eu, Nabucodonosor, louvo, e exalço, e glorifico ao Rei dos céus; porque todas as suas obras são verdades; e os seus caminhos, juízo, e pode humilhar aos que andam na soberba.', 'Daniel 4:37', 'Daniel', 4, 37, NULL),
  ('justica', 'Há só um Legislador e um Juiz, que pode salvar e destruir. Tu, porém, quem és, que julgas a outrem?', 'Tiago 4:12', 'Tiago', 4, 12, NULL),
  ('justica', 'O Senhor abre os olhos aos cegos; o Senhor levanta os abatidos; o Senhor ama os justos.', 'Salmo 146:8', 'Salmo', 146, 8, NULL),
  ('justica', 'O ímpio toma emprestado e não paga; mas o justo se compadece e dá.', 'Salmo 37:21', 'Salmo', 37, 21, NULL),
  ('justica', 'Não declines nem para a direita nem para a esquerda; retira o teu pé do mal.', 'Provérbios 4:27', 'Provérbios', 4, 27, NULL),
  ('justica', 'Deixe o ímpio o seu caminho, e o homem maligno, os seus pensamentos e se converta ao Senhor, que se compadecerá dele; torne para o nosso Deus, porque grandioso é em perdoar.', 'Isaías 55:7', 'Isaías', 55, 7, NULL),
  ('justica', 'Alegra-te muito, ó filha de Sião; exulta, ó filha de Jerusalém; eis que o teu rei virá a ti, justo e Salvador, pobre e montado sobre um jumento, sobre um asninho, filho de jumenta.', 'Zacarias 9:9', 'Zacarias', 9, 9, NULL),
  ('justica', 'Agora, pois, seja o temor do Senhor convosco; guardai-o e fazei-o, porque não há no Senhor, nosso Deus, iniquidade, nem acepção de pessoas, nem aceitação de presentes.', '2 Crônicas 19:7', '2 Crônicas', 19, 7, NULL),
  ('justica', 'E, quando ele vier, convencerá o mundo do pecado, e da justiça, e do juízo.', 'João 16:8', 'João', 16, 8, NULL),
  ('justica', 'Buscai o Senhor, vós todos os mansos da terra, que pondes por obra o seu juízo; buscai a justiça, buscai a mansidão; porventura sereis escondidos no dia da ira do Senhor.', 'Sofonias 2:3', 'Sofonias', 2, 3, NULL),
  ('justica', 'Foge, também, dos desejos da mocidade; e segue a justiça, a fé, o amor e a paz com os que, com um coração puro, invocam o Senhor.', '2 Timóteo 2:22', '2 Timóteo', 2, 22, NULL),
  ('justica', 'Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça, e calçados os pés na preparação do evangelho da paz; tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno.', 'Efésios 6:14-16', 'Efésios', 6, 14, 16),
  ('justica', 'Na verdade, não há homem justo sobre a terra, que faça bem e nunca peque.', 'Eclesiastes 7:20', 'Eclesiastes', 7, 20, NULL),
  ('lei', 'E estas palavras que hoje te ordeno estarão no teu coração; e as intimarás a teus filhos e delas falarás assentado em tua casa, e andando pelo caminho, e deitando-te, e levantando-te.', 'Deuteronômio 6:6-7', 'Deuteronômio', 6, 6, 7),
  ('lei', 'Pois quê? Pecaremos porque não estamos debaixo da lei, mas debaixo da graça? De modo nenhum!', 'Romanos 6:15', 'Romanos', 6, 15, NULL),
  ('lei', 'Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas nem todas as coisas edificam.', '1 Coríntios 10:23', '1 Coríntios', 10, 23, NULL),
  ('lei', 'Porquanto te ordeno, hoje, que ames o Senhor, teu Deus, que andes nos seus caminhos e que guardes os seus mandamentos, e os seus estatutos, e os seus juízos, para que vivas e te multipliques, e o Senhor, teu Deus, te abençoe na terra, a qual passas a possuir.', 'Deuteronômio 30:16', 'Deuteronômio', 30, 16, NULL),
  ('lei', 'E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo. Não há outro mandamento maior do que estes.', 'Marcos 12:31', 'Marcos', 12, 31, NULL),
  ('lei', 'Não se aparte da tua boca o livro desta Lei; antes, medita nele dia e noite, para que tenhas cuidado de fazer conforme tudo quanto nele está escrito; porque, então, farás prosperar o teu caminho e, então, prudentemente te conduzirás.', 'Josué 1:8', 'Josué', 1, 8, NULL),
  ('lei', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('lei', 'Por isso, nenhuma carne será justificada diante dele pelas obras da lei, porque pela lei vem o conhecimento do pecado.', 'Romanos 3:20', 'Romanos', 3, 20, NULL),
  ('lei', 'E será que, se ouvires a voz do Senhor, teu Deus, tendo cuidado de guardar todos os seus mandamentos que eu te ordeno hoje, o Senhor, teu Deus, te exaltará sobre todas as nações da terra.', 'Deuteronômio 28:1', 'Deuteronômio', 28, 1, NULL),
  ('lei', 'A ninguém devais coisa alguma, a não ser o amor com que vos ameis uns aos outros; porque quem ama aos outros cumpriu a lei.', 'Romanos 13:8', 'Romanos', 13, 8, NULL),
  ('lei', 'Porque toda a lei se cumpre numa só palavra, nesta: Amarás o teu próximo como a ti mesmo.', 'Gálatas 5:14', 'Gálatas', 5, 14, NULL),
  ('lei', 'Portanto, tudo o que vós quereis que os homens vos façam, fazei-lho também vós, porque esta é a lei e os profetas.', 'Mateus 7:12', 'Mateus', 7, 12, NULL),
  ('lei', 'Mas a misericórdia do Senhor é de eternidade a eternidade sobre aqueles que o temem, e a sua justiça sobre os filhos dos filhos; sobre aqueles que guardam o seu concerto, e sobre os que se lembram dos seus mandamentos para os cumprirem.', 'Salmo 103:17-18', 'Salmo', 103, 17, 18),
  ('lei', 'Agora, pois, ó Israel, que é o que o Senhor, teu Deus, pede de ti, senão que temas o Senhor, teu Deus, e que andes em todos os seus caminhos, e o ames, e sirvas ao Senhor, teu Deus, com todo o teu coração e com toda a tua alma, para guardares os mandamentos do Senhor e os seus estatutos, que hoje te ordeno, para o teu bem?', 'Deuteronômio 10:12-13', 'Deuteronômio', 10, 12, 13),
  ('lei', 'Não vos prendais a um jugo desigual com os infiéis; porque que sociedade tem a justiça com a injustiça? E que comunhão tem a luz com as trevas?', '2 Coríntios 6:14', '2 Coríntios', 6, 14, NULL),
  ('lei', 'Ele te declarou, ó homem, o que é bom; e que é o que o Senhor pede de ti, senão que pratiques a justiça, e ames a beneficência, e andes humildemente com o teu Deus?', 'Miqueias 6:8', 'Miqueias', 6, 8, NULL),
  ('lei', 'E vós, pais, não provoqueis a ira a vossos filhos, mas criai-os na doutrina e admoestação do Senhor.', 'Efésios 6:4', 'Efésios', 6, 4, NULL),
  ('lei', 'Corra, porém, o juízo como as águas, e a justiça, como o ribeiro impetuoso.', 'Amós 5:24', 'Amós', 5, 24, NULL),
  ('lei', 'Levai as cargas uns dos outros e assim cumprireis a lei de Cristo.', 'Gálatas 6:2', 'Gálatas', 6, 2, NULL),
  ('lei', 'Porque todos os que sem lei pecaram sem lei também perecerão; e todos os que sob a lei pecaram pela lei serão julgados.', 'Romanos 2:12', 'Romanos', 2, 12, NULL),
  ('lei', 'De todo o meu coração te busquei; não me deixes desviar dos teus mandamentos.', 'Salmo 119:10', 'Salmo', 119, 10, NULL),
  ('lei', 'O meu mandamento é este: Que vos ameis uns aos outros, assim como eu vos amei.', 'João 15:12', 'João', 15, 12, NULL),
  ('lei', 'Porque o fim da lei é Cristo para justiça de todo aquele que crê.', 'Romanos 10:4', 'Romanos', 10, 4, NULL),
  ('lei', 'Amados, se o nosso coração nos não condena, temos confiança para com Deus; e qualquer coisa que lhe pedirmos, dele a receberemos, porque guardamos os seus mandamentos e fazemos o que é agradável à sua vista.', '1 João 3:21-22', '1 João', 3, 21, 22);

