-- Parte 08: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('lei', 'Escolhi o caminho da verdade; propus-me seguir os teus juízos.', 'Salmo 119:30', 'Salmo', 119, 30, NULL),
  ('lei', 'Tão somente tende cuidado de guardar com diligência o mandamento e a lei que Moisés, o servo do Senhor', 'Josué 22:5', 'Josué', 22, 5, NULL),
  ('lei', 'E dele temos este mandamento: que quem ama a Deus, ame também seu irmão.', '1 João 4:21', '1 João', 4, 21, NULL),
  ('lei', 'Porque o pecado não terá domínio sobre vós, pois não estais debaixo da lei, mas debaixo da graça.', 'Romanos 6:14', 'Romanos', 6, 14, NULL),
  ('lei', 'Se me amardes, guardareis os meus mandamentos.', 'João 14:15', 'João', 14, 15, NULL),
  ('lei', 'Que diremos, pois? É a lei pecado? De modo nenhum! Mas eu não conheci o pecado senão pela lei; porque eu não conheceria a concupiscência, se a lei não dissesse: Não cobiçarás.', 'Romanos 7:7', 'Romanos', 7, 7, NULL),
  ('lei', 'Ora, o aguilhão da morte é o pecado, e a força do pecado é a lei.', '1 Coríntios 15:56', '1 Coríntios', 15, 56, NULL),
  ('lei', 'E guarda a observância do Senhor', '1 Reis 2:3', '1 Reis', 2, 3, NULL),
  ('lei', 'Não julgueis, para que não sejais julgados.', 'Mateus 7:1', 'Mateus', 7, 1, NULL),
  ('lei', 'Então, vos anunciou ele o seu concerto, que vos prescreveu, os dez mandamentos, e os escreveu em duas tábuas de pedra.', 'Deuteronômio 4:13', 'Deuteronômio', 4, 13, NULL),
  ('lei', 'A lei do Senhor', 'Salmo 19:7', 'Salmo', 19, 7, NULL),
  ('lei', 'Muita paz têm os que amam a tua lei, e para eles não há tropeço.', 'Salmo 119:165', 'Salmo', 119, 165, NULL),
  ('lei', 'Separados estais de Cristo, vós os que vos justificais pela lei; da graça tendes caído.', 'Gálatas 5:4', 'Gálatas', 5, 4, NULL),
  ('lei', 'Com efeito: Não adulterarás, não matarás, não furtarás, não darás falso testemunho, não cobiçarás, e, se há algum outro mandamento, tudo nesta palavra se resume: Amarás ao teu próximo como a ti mesmo.', 'Romanos 13:9', 'Romanos', 13, 9, NULL),
  ('lei', 'O amor não faz mal ao próximo; de sorte que o cumprimento da lei é o amor.', 'Romanos 13:10', 'Romanos', 13, 10, NULL),
  ('lei', 'E aquele que guarda os seus mandamentos nele está, e ele nele. E nisto conhecemos que ele está em nós: pelo Espírito que nos tem dado.', '1 João 3:24', '1 João', 3, 24, NULL),
  ('lei', 'Seja-vos, pois, notório, varões irmãos, que por este se vos anuncia a remissão dos pecados. E de tudo o que, pela lei de Moisés, não pudestes ser justificados, por ele é justificado todo aquele que crê.', 'Atos 13:38-39', 'Atos', 13, 38, 39),
  ('lei', 'Ouve, Israel, o Senhor', 'Deuteronômio 6:4-5', 'Deuteronômio', 6, 4, 5),
  ('lei', 'Diligentemente guardareis os mandamentos do Senhor', 'Deuteronômio 6:17', 'Deuteronômio', 6, 17, NULL),
  ('lei', 'De tudo o que se tem ouvido, o fim é: Teme a Deus e guarda os seus mandamentos; porque este é o dever de todo homem.', 'Eclesiastes 12:13', 'Eclesiastes', 12, 13, NULL),
  ('lei', 'Não cuideis que vim destruir a lei ou os profetas; não vim ab-rogar, mas cumprir.', 'Mateus 5:17', 'Mateus', 5, 17, NULL),
  ('lei', 'Se guardardes os meus mandamentos, permanecereis no meu amor, do mesmo modo que eu tenho guardado os mandamentos de meu Pai e permaneço no seu amor.', 'João 15:10', 'João', 15, 10, NULL),
  ('lei', 'Louvai ao Senhor', 'Salmo 112:1', 'Salmo', 112, 1, NULL),
  ('lei', 'O sábio de coração aceita os mandamentos, mas o louco palrador será transtornado.', 'Provérbios 10:8', 'Provérbios', 10, 8, NULL),
  ('lei', 'Os preceitos do Senhor', 'Salmo 19:8', 'Salmo', 19, 8, NULL),
  ('lei', 'Pecamos, e cometemos iniquidade, e procedemos impiamente, e fomos rebeldes, apartando-nos dos teus mandamentos e dos teus juízos.', 'Daniel 9:5', 'Daniel', 9, 5, NULL),
  ('lei', 'Aquele, porém, que atenta bem para a lei perfeita da liberdade e nisso persevera, não sendo ouvinte esquecido, mas fazedor da obra, este tal será bem-aventurado no seu feito.', 'Tiago 1:25', 'Tiago', 1, 25, NULL),
  ('lei', 'O temor do Senhor', 'Salmo 111:10', 'Salmo', 111, 10, NULL),
  ('lei', 'Não fareis outros deuses comigo; deuses de prata ou deuses de ouro não fareis para vós.', 'Êxodo 20:23', 'Êxodo', 20, 23, NULL),
  ('lei', 'Eu sou o Senhor', 'Ezequiel 20:19-20', 'Ezequiel', 20, 19, 20),
  ('lei', 'Nunca me esquecerei dos teus preceitos, pois por eles me tens vivificado.', 'Salmo 119:93', 'Salmo', 119, 93, NULL),
  ('lei', 'Há só um Legislador e um Juiz, que pode salvar e destruir. Tu, porém, quem és, que julgas a outrem?', 'Tiago 4:12', 'Tiago', 4, 12, NULL),
  ('lei', 'Nós somos judeus por natureza e não pecadores dentre os gentios. Sabendo que o homem não é justificado pelas obras da lei, mas pela fé em Jesus Cristo, temos também crido em Jesus Cristo, para sermos justificados pela fé de Cristo e não pelas obras da lei, porquanto pelas obras da lei nenhuma carne será justificada.', 'Gálatas 2:15-16', 'Gálatas', 2, 15, 16),
  ('lei', 'Folgo mais com o caminho dos teus testemunhos do que com todas as riquezas.', 'Salmo 119:14', 'Salmo', 119, 14, NULL),
  ('lei', 'Qualquer, pois, que violar um destes menores mandamentos e assim ensinar aos homens será chamado o menor no Reino dos céus; aquele, porém, que os cumprir e ensinar será chamado grande no Reino dos céus.', 'Mateus 5:19', 'Mateus', 5, 19, NULL),
  ('lei', 'Qualquer que pratica o pecado também pratica iniquidade, porque o pecado é iniquidade.', '1 João 3:4', '1 João', 3, 4, NULL),
  ('lei', 'Aquele, pois, que vos dá o Espírito e que opera maravilhas entre vós o faz pelas obras da lei ou pela pregação da fé?', 'Gálatas 3:5', 'Gálatas', 3, 5, NULL),
  ('lei', 'Não matarás, não cometerás adultério, não furtarás, não dirás falso testemunho; honra teu pai e tua mãe, e amarás o teu próximo como a ti mesmo.', 'Mateus 19:18b-19', 'Mateus 19:18b-19', NULL, NULL, NULL),
  ('lei', 'E, se alguma pessoa pecar e fizer contra algum de todos os mandamentos do Senhor', 'Levítico 5:17', 'Levítico', 5, 17, NULL),
  ('lei', 'Inclina o meu coração a teus testemunhos e não à cobiça.', 'Salmo 119:36', 'Salmo', 119, 36, NULL),
  ('lei', 'O caminho do Senhor', 'Provérbios 10:29', 'Provérbios', 10, 29, NULL),
  ('lei', 'E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo.', 'Mateus 22:39', 'Mateus', 22, 39, NULL),
  ('lei', 'Pelo que guardareis os meus mandamentos e os fareis. Eu sou o Senhor', 'Levítico 22:31', 'Levítico', 22, 31, NULL),
  ('lei', 'Não aniquilo a graça de Deus; porque, se a justiça provém da lei, segue-se que Cristo morreu debalde.', 'Gálatas 2:21', 'Gálatas', 2, 21, NULL),
  ('lei', 'Nada acrescentareis à palavra que vos mando, nem diminuireis dela, para que guardeis os mandamentos do Senhor', 'Deuteronômio 4:2', 'Deuteronômio', 4, 2, NULL),
  ('lei', 'E guardarás os seus estatutos e os seus mandamentos, que te ordeno hoje, para que bem te vá a ti e a teus filhos depois de ti e para que prolongues os dias na terra que o Senhor', 'Deuteronômio 4:40', 'Deuteronômio', 4, 40, NULL),
  ('lei', 'Mas, agora, se manifestou, sem a lei, a justiça de Deus, tendo o testemunho da Lei e dos Profetas, isto é, a justiça de Deus pela fé em Jesus Cristo para todos e sobre todos os que creem; porque não há diferença.', 'Romanos 3:21-22', 'Romanos', 3, 21, 22),
  ('lei', 'Mas, se o ímpio se converter de todos os seus pecados que cometeu, e guardar todos os meus estatutos, e fizer juízo e justiça, certamente viverá; não morrerá.', 'Ezequiel 18:21', 'Ezequiel', 18, 21, NULL),
  ('lei', 'Aquele que tem os meus mandamentos e os guarda, este é o que me ama; e aquele que me ama será amado de meu Pai, e eu o amarei e me manifestarei a ele.', 'João 14:21', 'João', 14, 21, NULL),
  ('lei', 'E andarei em liberdade, pois busquei os teus preceitos.', 'Salmo 119:45', 'Salmo', 119, 45, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('lei', 'Não tomarás o nome do Senhor', 'Deuteronômio 5:11', 'Deuteronômio', 5, 11, NULL),
  ('lei', 'A tua palavra é a verdade desde o princípio, e cada um dos teus juízos dura para sempre.', 'Salmo 119:160', 'Salmo', 119, 160, NULL),
  ('lei', 'Então, disse o Senhor', 'Êxodo 24:12', 'Êxodo', 24, 12, NULL),
  ('lei', 'Filho meu, não te esqueças da minha lei, e o teu coração guarde os meus mandamentos. Porque eles aumentarão os teus dias e te acrescentarão anos de vida e paz.', 'Provérbios 3:1-2', 'Provérbios', 3, 1, 2),
  ('lei', 'Porque esta é a mensagem que ouvistes desde o princípio: que nos amemos uns aos outros.', '1 João 3:11', '1 João', 3, 11, NULL),
  ('lei', 'Louvar-te-ei com retidão de coração, quando tiver aprendido os teus justos juízos.', 'Salmo 119:7', 'Salmo', 119, 7, NULL),
  ('lei', 'O que guardar o mandamento guardará a sua alma; mas o que desprezar os seus caminhos morrerá.', 'Provérbios 19:16', 'Provérbios', 19, 16, NULL),
  ('lei', 'Os teus testemunhos tenho eu tomado por herança para sempre, pois são o gozo do meu coração.', 'Salmo 119:111', 'Salmo', 119, 111, NULL),
  ('lei', 'Bem-aventurados os que trilham caminhos retos e andam na lei do Senhor', 'Salmo 119:1', 'Salmo', 119, 1, NULL),
  ('lei', 'E multiplicarei a tua semente como as estrelas dos céus e darei à tua semente todas estas terras. E em tua semente serão benditas todas as nações da terra, porquanto Abraão obedeceu à minha voz e guardou o meu mandado, os meus preceitos, os meus estatutos e as minhas leis.', 'Gênesis 26:4-5', 'Gênesis', 26, 4, 5),
  ('lei', 'Portanto, agora, nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito. Porque a lei do Espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte.', 'Romanos 8:1-2', 'Romanos', 8, 1, 2),
  ('lei', 'E, por isso, é Mediador de um novo testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna.', 'Hebreus 9:15', 'Hebreus', 9, 15, NULL),
  ('lei', 'E porei dentro de vós o meu espírito e farei que andeis nos meus estatutos, e guardeis os meus juízos, e os observeis.', 'Ezequiel 36:27', 'Ezequiel', 36, 27, NULL),
  ('lei', 'Um novo mandamento vos dou: Que vos ameis uns aos outros; como eu vos amei a vós, que também vós uns aos outros vos ameis.', 'João 13:34', 'João', 13, 34, NULL),
  ('lei', 'Até no caminho dos teus juízos, Senhor', 'Isaías 26:8', 'Isaías', 26, 8, NULL),
  ('lei', 'Ouve, filho meu, e aceita as minhas palavras, e se te multiplicarão os anos de vida.', 'Provérbios 4:10', 'Provérbios', 4, 10, NULL),
  ('lei', 'Quem dera que eles tivessem tal coração que me temessem e guardassem todos os meus mandamentos todos os dias, para que bem lhes fosse a eles e a seus filhos, para sempre!', 'Deuteronômio 5:29', 'Deuteronômio', 5, 29, NULL),
  ('lei', 'Apressei-me e não me detive a observar os teus mandamentos.', 'Salmo 119:60', 'Salmo', 119, 60, NULL),
  ('lei', 'Porque em verdade vos digo que, até que o céu e a terra passem, nem um jota ou um til se omitirá da lei sem que tudo seja cumprido.', 'Mateus 5:18', 'Mateus', 5, 18, NULL),
  ('lei', 'E, respondendo ele, disse: Amarás ao Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todas as tuas forças, e de todo o teu entendimento e ao teu próximo como a ti mesmo.', 'Lucas 10:27', 'Lucas', 10, 27, NULL),
  ('lei', 'Saberás, pois, que o Senhor', 'Deuteronômio 7:9', 'Deuteronômio', 7, 9, NULL),
  ('lei', 'E nas franjas vos estará, para que o vejais, e vos lembreis de todos os mandamentos do Senhor', 'Números 15:39', 'Números', 15, 39, NULL),
  ('lei', 'E esteve Moisés ali com o Senhor', 'Êxodo 34:28', 'Êxodo', 34, 28, NULL),
  ('lei', 'Se ouvires atento a voz do Senhor', 'Êxodo 15:26', 'Êxodo', 15, 26, NULL),
  ('lei', 'Ora, o Deus de paz, que pelo sangue do concerto eterno tornou a trazer dos mortos a nosso Senhor Jesus Cristo, grande Pastor das ovelhas, vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável por Cristo Jesus, ao qual seja glória para todo o sempre. Amém!', 'Hebreus 13:20-21', 'Hebreus', 13, 20, 21),
  ('lei', 'Do preceito de seus lábios nunca me apartei e as palavras da sua boca prezei mais do que o meu alimento.', 'Jó 23:12', 'Jó', 23, 12, NULL),
  ('lei', 'Sabendo isto: que a lei não é feita para o justo, mas para os injustos e obstinados, para os ímpios e pecadores, para os profanos e irreligiosos, para os parricidas e matricidas, para os homicidas, para os fornicadores, para os sodomitas, para os roubadores de homens, para os mentirosos, para os perjuros e para o que for contrário à sã doutrina, conforme o evangelho da glória do Deus bem-aventurado, que me foi confiado.', '1 Timóteo 1:9-11', '1 Timóteo', 1, 9, 11),
  ('lei', 'Se andardes nos meus estatutos, e guardardes os meus mandamentos, e os fizerdes, então, eu vos darei as vossas chuvas a seu tempo; e a terra dará a sua novidade, e a árvore do campo dará o seu fruto.', 'Levítico 26:3-4', 'Levítico', 26, 3, 4),
  ('lei', 'E será para nós justiça, quando tivermos cuidado de fazer todos estes mandamentos perante o Senhor', 'Deuteronômio 6:25', 'Deuteronômio', 6, 25, NULL),
  ('lei', 'Não cobiçarás a casa do teu próximo; não cobiçarás a mulher do teu próximo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma do teu próximo.', 'Êxodo 20:17', 'Êxodo', 20, 17, NULL),
  ('lei', 'O que desvia os seus ouvidos de ouvir a lei, até a sua oração será abominável.', 'Provérbios 28:9', 'Provérbios', 28, 9, NULL),
  ('lei', 'E guarda os mandamentos do Senhor', 'Deuteronômio 8:6', 'Deuteronômio', 8, 6, NULL),
  ('lei', 'E o Senhor', 'Deuteronômio 6:24', 'Deuteronômio', 6, 24, NULL),
  ('lei', 'Deleito-me em fazer a tua vontade, ó Deus meu; sim, a tua lei está dentro do meu coração.', 'Salmo 40:8', 'Salmo', 40, 8, NULL),
  ('lei', 'E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão.', 'Hebreus 9:22', 'Hebreus', 9, 22, NULL),
  ('lei', 'A Lei e os Profetas duraram até João; desde então, é anunciado o Reino de Deus, e todo homem emprega força para entrar nele.', 'Lucas 16:16', 'Lucas', 16, 16, NULL),
  ('liberdade', 'Estai, pois, firmes na liberdade com que Cristo nos libertou e não torneis a meter-vos debaixo do jugo da servidão.', 'Gálatas 5:1', 'Gálatas', 5, 1, NULL),
  ('liberdade', 'Ora, o Senhor é Espírito; e onde está o Espírito do Senhor, aí há liberdade.', '2 Coríntios 3:17', '2 Coríntios', 3, 17, NULL),
  ('liberdade', 'Se, pois, o Filho vos libertar, verdadeiramente, sereis livres.', 'João 8:36', 'João', 8, 36, NULL),
  ('liberdade', 'Porque vós, irmãos, fostes chamados à liberdade. Não useis, então, da liberdade para dar ocasião à carne, mas servi-vos uns aos outros pelo amor.', 'Gálatas 5:13', 'Gálatas', 5, 13, NULL),
  ('liberdade', 'Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas eu não me deixarei dominar por nenhuma.', '1 Coríntios 6:12', '1 Coríntios', 6, 12, NULL),
  ('liberdade', 'E andarei em liberdade, pois busquei os teus preceitos.', 'Salmo 119:45', 'Salmo', 119, 45, NULL),
  ('liberdade', 'O Espírito do Senhor Jeová', 'Isaías 61:1', 'Isaías', 61, 1, NULL),
  ('liberdade', 'Muitas são as aflições do justo, mas o Senhor', 'Salmo 34:19', 'Salmo', 34, 19, NULL),
  ('liberdade', 'Como livres e não tendo a liberdade por cobertura da malícia, mas como servos de Deus.', '1 Pedro 2:16', '1 Pedro', 2, 16, NULL),
  ('liberdade', 'Jesus dizia, pois, aos judeus que criam nele: Se vós permanecerdes na minha palavra, verdadeiramente, sereis meus discípulos e conhecereis a verdade, e a verdade vos libertará.', 'João 8:31-32', 'João', 8, 31, 32),
  ('liberdade', 'Portanto, agora, nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito. Porque a lei do Espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte.', 'Romanos 8:1-2', 'Romanos', 8, 1, 2),
  ('liberdade', 'Mas, agora, libertados do pecado e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna.', 'Romanos 6:22', 'Romanos', 6, 22, NULL),
  ('liberdade', 'O Espírito do Senhor é sobre mim, pois que me ungiu para evangelizar os pobres, enviou-me a curar os quebrantados do coração.', 'Lucas 4:18', 'Lucas', 4, 18, NULL),
  ('liberdade', 'Aquele, porém, que atenta bem para a lei perfeita da liberdade e nisso persevera, não sendo ouvinte esquecido, mas fazedor da obra, este tal será bem-aventurado no seu feito.', 'Tiago 1:25', 'Tiago', 1, 25, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('liberdade', 'Deus faz que o solitário viva em família; liberta aqueles que estão presos em grilhões; mas os rebeldes habitam em terra seca.', 'Salmo 68:6', 'Salmo', 68, 6, NULL),
  ('liberdade', 'Pois quê? Pecaremos porque não estamos debaixo da lei, mas debaixo da graça? De modo nenhum!', 'Romanos 6:15', 'Romanos', 6, 15, NULL),
  ('liberdade', 'Ajuda-nos, ó Deus da nossa salvação, pela glória do teu nome; e livra-nos e perdoa os nossos pecados, por amor do teu nome.', 'Salmo 79:9', 'Salmo', 79, 9, NULL),
  ('liberdade', 'Seja-vos, pois, notório, varões irmãos, que por este se vos anuncia a remissão dos pecados. E de tudo o que, pela lei de Moisés, não pudestes ser justificados, por ele é justificado todo aquele que crê.', 'Atos 13:38-39', 'Atos', 13, 38, 39),
  ('liberdade', 'Vós que amais ao Senhor', 'Salmo 97:10', 'Salmo', 97, 10, NULL),
  ('louvor', 'Ó Senhor', 'Isaías 25:1', 'Isaías', 25, 1, NULL),
  ('louvor', 'Porque a tua benignidade é melhor do que a vida; os meus lábios te louvarão. Assim, eu te bendirei enquanto viver; em teu nome levantarei as minhas mãos.', 'Salmo 63:3-4', 'Salmo', 63, 3, 4),
  ('louvor', 'Tudo quanto tem fôlego louve ao Senhor', 'Salmo 150:6', 'Salmo', 150, 6, NULL),
  ('louvor', 'O Senhor', 'Salmo 28:7', 'Salmo', 28, 7, NULL),
  ('louvor', 'Bendize, ó minha alma, ao Senhor', 'Salmo 103:1', 'Salmo', 103, 1, NULL),
  ('louvor', 'Perto da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros presos os escutavam.', 'Atos 16:25', 'Atos', 16, 25, NULL),
  ('louvor', 'Eu te louvarei, Senhor', 'Salmo 9:1', 'Salmo', 9, 1, NULL),
  ('louvor', 'Grande é o Senhor', 'Salmo 145:3', 'Salmo', 145, 3, NULL),
  ('louvor', 'Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei. Ele é a salvação da minha face e o meu Deus.', 'Salmo 42:11', 'Salmo', 42, 11, NULL),
  ('louvor', 'Louvarei ao Senhor', 'Salmo 34:1', 'Salmo', 34, 1, NULL),
  ('louvor', 'Pois possuíste o meu interior; entreteceste-me no ventre de minha mãe. Eu te louvarei, porque de um modo terrível e tão maravilhoso fui formado; maravilhosas são as tuas obras, e a minha alma o sabe muito bem.', 'Salmo 139:13-14', 'Salmo', 139, 13, 14),
  ('louvor', 'E ouvi a toda criatura que está no céu, e na terra, e debaixo da terra, e que está no mar, e a todas as coisas que neles há, dizer: Ao que está assentado sobre o trono e ao Cordeiro sejam dadas ações de graças, e honra, e glória, e poder para todo o sempre.', 'Apocalipse 5:13', 'Apocalipse', 5, 13, NULL),
  ('louvor', 'Encha-se a minha boca do teu louvor e da tua glória todo o dia.', 'Salmo 71:8', 'Salmo', 71, 8, NULL),
  ('louvor', 'A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais; cantando ao Senhor com graça em vosso coração.', 'Colossenses 3:16', 'Colossenses', 3, 16, NULL),
  ('louvor', 'Eu te exaltarei, ó Deus, Rei meu, e bendirei o teu nome pelos séculos dos séculos.', 'Salmo 145:1', 'Salmo', 145, 1, NULL),
  ('louvor', 'Louvai ao Senhor', 'Salmo 105:1', 'Salmo', 105, 1, NULL),
  ('louvor', 'Sara-me, Senhor', 'Jeremias 17:14', 'Jeremias', 17, 14, NULL),
  ('louvor', 'E direis, naquele dia: Dai graças ao Senhor', 'Isaías 12:4', 'Isaías', 12, 4, NULL),
  ('louvor', 'Porque está escrito: Pela minha vida, diz o Senhor, todo joelho se dobrará diante de mim, e toda língua confessará a Deus.', 'Romanos 14:11', 'Romanos', 14, 11, NULL),
  ('louvor', 'Louvar-te-ei entre os povos, Senhor', 'Salmo 108:3', 'Salmo', 108, 3, NULL),
  ('louvor', 'Bendito o Deus e Pai de nosso Senhor Jesus Cristo, o qual nos abençoou com todas as bênçãos espirituais nos lugares celestiais em Cristo.', 'Efésios 1:3', 'Efésios', 1, 3, NULL),
  ('louvor', 'Quanto ao mais, irmãos, tudo o que é verdadeiro, tudo o que é honesto, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se há alguma virtude, e se há algum louvor, nisso pensai.', 'Filipenses 4:8', 'Filipenses', 4, 8, NULL),
  ('louvor', 'E, perseverando unânimes todos os dias no templo e partindo o pão em casa, comiam juntos com alegria e singeleza de coração, louvando a Deus e caindo na graça de todo o povo. E todos os dias acrescentava o Senhor à igreja aqueles que se haviam de salvar.', 'Atos 2:46-47', 'Atos', 2, 46, 47),
  ('louvor', 'A ele clamei com a minha boca, e ele foi exaltado pela minha língua.', 'Salmo 66:17', 'Salmo', 66, 17, NULL),
  ('louvor', 'Em Deus louvarei a sua palavra; em Deus pus a minha confiança e não temerei; que me pode fazer a carne?', 'Salmo 56:4', 'Salmo', 56, 4, NULL),
  ('louvor', 'Louvar-te-ei com retidão de coração, quando tiver aprendido os teus justos juízos.', 'Salmo 119:7', 'Salmo', 119, 7, NULL),
  ('louvor', 'Então, Jó se levantou, e rasgou o seu manto, e rapou a sua cabeça, e se lançou em terra, e adorou, e disse: Nu saí do ventre de minha mãe e nu tornarei para lá; o Senhor', 'Jó 1:20-21', 'Jó', 1, 20, 21),
  ('louvor', 'Ó Deus de meus pais, eu te louvo e celebro porque me deste sabedoria e força; e, agora, me fizeste saber o que te pedimos, porque nos fizeste saber este assunto do rei.', 'Daniel 2:23', 'Daniel', 2, 23, NULL),
  ('louvor', 'De uma mesma boca procede bênção e maldição. Meus irmãos, não convém que isto se faça assim.', 'Tiago 3:10', 'Tiago', 3, 10, NULL),
  ('louvor', 'E voltaram os pastores glorificando e louvando a Deus por tudo o que tinham ouvido e visto, como lhes havia sido dito.', 'Lucas 2:20', 'Lucas', 2, 20, NULL),
  ('luz', 'Levanta-te, resplandece, porque já vem a tua luz, e a glória do Senhor', 'Isaías 60:1', 'Isaías', 60, 1, NULL),
  ('luz', 'Falou-lhes, pois, Jesus outra vez, dizendo: Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.', 'João 8:12', 'João', 8, 12, NULL),
  ('luz', 'Lâmpada para os meus pés é tua palavra e luz, para o meu caminho.', 'Salmo 119:105', 'Salmo', 119, 105, NULL),
  ('luz', 'E a luz resplandece nas trevas, e as trevas não a compreenderam.', 'João 1:5', 'João', 1, 5, NULL),
  ('luz', 'Vós sois a luz do mundo; não se pode esconder uma cidade edificada sobre um monte.', 'Mateus 5:14', 'Mateus', 5, 14, NULL),
  ('luz', 'O Senhor', 'Números 6:24-26', 'Números', 6, 24, 26),
  ('luz', 'O Senhor', 'Salmo 27:1', 'Salmo', 27, 1, NULL),
  ('luz', 'Porque o Senhor assim no-lo mandou: Eu te pus para luz dos gentios, para que sejas de salvação até aos confins da terra.', 'Atos 13:47', 'Atos', 13, 47, NULL),
  ('luz', 'Nem se acende a candeia e se coloca debaixo do alqueire, mas, no velador, e dá luz a todos que estão na casa. Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem o vosso Pai, que está nos céus.', 'Mateus 5:15-16', 'Mateus', 5, 15, 16),
  ('luz', 'Ele revela o profundo e o escondido e conhece o que está em trevas; e com ele mora a luz.', 'Daniel 2:22', 'Daniel', 2, 22, NULL),
  ('luz', 'E esta é a mensagem que dele ouvimos e vos anunciamos: que Deus é luz, e não há nele treva nenhuma.', '1 João 1:5', '1 João', 1, 5, NULL),
  ('luz', 'A exposição das tuas palavras dá luz e dá entendimento aos símplices.', 'Salmo 119:130', 'Salmo', 119, 130, NULL),
  ('luz', 'Porque, noutro tempo, éreis trevas, mas, agora, sois luz no Senhor; andai como filhos da luz.', 'Efésios 5:8', 'Efésios', 5, 8, NULL),
  ('luz', 'Entrega o teu caminho ao Senhor', 'Salmo 37:5-6', 'Salmo', 37, 5, 6),
  ('luz', 'Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo pecado.', '1 João 1:7', '1 João', 1, 7, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('luz', 'E disse Deus: Haja luz. E houve luz.', 'Gênesis 1:3', 'Gênesis', 1, 3, NULL),
  ('luz', 'Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz.', '1 Pedro 2:9', '1 Pedro', 2, 9, NULL),
  ('luz', 'Tendo iluminados os olhos do vosso entendimento, para que saibais qual seja a esperança da sua vocação e quais as riquezas da glória da sua herança nos santos.', 'Efésios 1:18', 'Efésios', 1, 18, NULL),
  ('luz', 'E ninguém, acendendo uma candeia, a cobre com algum vaso ou a põe debaixo da cama; mas põe-na no velador, para que os que entram vejam a luz.', 'Lucas 8:16', 'Lucas', 8, 16, NULL),
  ('luz', 'Não vos prendais a um jugo desigual com os infiéis; porque que sociedade tem a justiça com a injustiça? E que comunhão tem a luz com as trevas?', '2 Coríntios 6:14', '2 Coríntios', 6, 14, NULL),
  ('luz', 'Porque o fruto do Espírito está em toda bondade, e justiça, e verdade.', 'Efésios 5:9', 'Efésios', 5, 9, NULL),
  ('luz', 'Porque tu acenderás a minha candeia; o Senhor', 'Salmo 18:28', 'Salmo', 18, 28, NULL),
  ('luz', 'Faze resplandecer o teu rosto sobre o teu servo; salva-me por tuas misericórdias.', 'Salmo 31:16', 'Salmo', 31, 16, NULL),
  ('luz', 'Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes, em quem não há mudança, nem sombra de variação.', 'Tiago 1:17', 'Tiago', 1, 17, NULL),
  ('luz', 'Faze-nos voltar, Senhor', 'Salmo 80:19', 'Salmo', 80, 19, NULL),
  ('luz', 'Porquanto tudo o que em trevas dissestes à luz será ouvido; e o que falastes ao ouvido no gabinete sobre os telhados será apregoado.', 'Lucas 12:3', 'Lucas', 12, 3, NULL),
  ('luz', 'Pois não conquistaram a terra pela sua espada, nem o seu braço os salvou, e sim a tua destra, e o teu braço, e a luz da tua face, porquanto te agradaste deles.', 'Salmo 44:3', 'Salmo', 44, 3, NULL),
  ('luz', 'Os preceitos do Senhor', 'Salmo 19:8', 'Salmo', 19, 8, NULL),
  ('luz', 'Mas, alcançando socorro de Deus, ainda até ao dia de hoje permaneço, dando testemunho, tanto a pequenos como a grandes, não dizendo nada mais do que o que os profetas e Moisés disseram que devia acontecer, isto é, que o Cristo devia padecer e, sendo o primeiro da ressurreição dos mortos, devia anunciar a luz a este povo e aos gentios.', 'Atos 26:22-23', 'Atos', 26, 22, 23),
  ('luz', 'Mas quem pratica a verdade vem para a luz, a fim de que as suas obras sejam manifestas, porque são feitas em Deus.', 'João 3:21', 'João', 3, 21, NULL),
  ('luz', 'A candeia do corpo são os olhos; de sorte que, se os teus olhos forem bons, todo o teu corpo terá luz. Se, porém, os teus olhos forem maus, o teu corpo será tenebroso. Se, portanto, a luz que em ti há são trevas, quão grandes serão tais trevas!', 'Mateus 6:22-23', 'Mateus', 6, 22, 23),
  ('mal', 'Não te deixes vencer do mal, mas vence o mal com o bem.', 'Romanos 12:21', 'Romanos', 12, 21, NULL),
  ('mal', 'O Senhor', 'Salmo 121:7-8', 'Salmo', 121, 7, 8),
  ('mal', 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo.', 'Efésios 6:11', 'Efésios', 6, 11, NULL),
  ('mal', 'Porque não temos que lutar contra carne e sangue, mas, sim, contra os principados, contra as potestades, contra os príncipes das trevas deste século, contra as hostes espirituais da maldade, nos lugares celestiais.', 'Efésios 6:12', 'Efésios', 6, 12, NULL),
  ('mal', 'E rogo-vos, irmãos, que noteis os que promovem dissensões e escândalos contra a doutrina que aprendestes; desviai-vos deles.', 'Romanos 16:17', 'Romanos', 16, 17, NULL),
  ('mal', 'E dizia: O que sai do homem, isso é que contamina o homem. Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios, os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura. Todos estes males procedem de dentro e contaminam o homem.', 'Marcos 7:20-23', 'Marcos', 7, 20, 23),
  ('mal', 'O temor do Senhor', 'Provérbios 8:13', 'Provérbios', 8, 13, NULL),
  ('mal', 'Vós bem intentastes mal contra mim, porém Deus o tornou em bem, para fazer como se vê neste dia, para conservar em vida a um povo grande.', 'Gênesis 50:20', 'Gênesis', 50, 20, NULL),
  ('mal', 'Vede que ninguém dê a outrem mal por mal, mas segui, sempre, o bem, tanto uns para com os outros como para com todos.', '1 Tessalonicenses 5:15', '1 Tessalonicenses', 5, 15, NULL),
  ('mal', 'Irai-vos e não pequeis; não se ponha o sol sobre a vossa ira. Não deis lugar ao diabo.', 'Efésios 4:26-27', 'Efésios', 4, 26, 27),
  ('mal', 'Examinai tudo. Retende o bem. Abstende-vos de toda aparência do mal.', '1 Tessalonicenses 5:21-22', '1 Tessalonicenses', 5, 21, 22),
  ('mal', 'Não sejas sábio a teus próprios olhos; teme ao Senhor', 'Provérbios 3:7-8', 'Provérbios', 3, 7, 8),
  ('mal', 'O amor seja não fingido. Aborrecei o mal e apegai-vos ao bem.', 'Romanos 12:9', 'Romanos', 12, 9, NULL),
  ('mal', 'Vós que amais ao Senhor', 'Salmo 97:10', 'Salmo', 97, 10, NULL),
  ('mal', 'Aparta-te do mal e faze o bem; procura a paz e segue-a.', 'Salmo 34:14', 'Salmo', 34, 14, NULL),
  ('mal', 'Não peço que os tires do mundo, mas que os livres do mal.', 'João 17:15', 'João', 17, 15, NULL),
  ('mal', 'O ódio excita contendas, mas o amor cobre todas as transgressões.', 'Provérbios 10:12', 'Provérbios', 10, 12, NULL),
  ('mal', 'E o Senhor me livrará de toda má obra e guardar-me-á para o seu Reino celestial; a quem seja glória para todo o sempre. Amém!', '2 Timóteo 4:18', '2 Timóteo', 4, 18, NULL),
  ('mal', 'Ordena os meus passos na tua palavra, e não se apodere de mim iniquidade alguma.', 'Salmo 119:133', 'Salmo', 119, 133, NULL),
  ('mal', 'Assim falou o Senhor', 'Zacarias 7:9-10', 'Zacarias', 7, 9, 10),
  ('mal', 'Lavai-vos, purificai-vos, tirai a maldade de vossos atos de diante dos meus olhos e cessai de fazer mal.', 'Isaías 1:16', 'Isaías', 1, 16, NULL),
  ('mal', 'E não nos induzas à tentação, mas livra-nos do mal; porque teu é o Reino, e o poder, e a glória, para sempre. Amém!', 'Mateus 6:13', 'Mateus', 6, 13, NULL),
  ('mal', 'Não vos enganeis: as más conversações corrompem os bons costumes.', '1 Coríntios 15:33', '1 Coríntios', 15, 33, NULL),
  ('mal', 'E a luz resplandece nas trevas, e as trevas não a compreenderam.', 'João 1:5', 'João', 1, 5, NULL),
  ('mal', 'A face do Senhor', 'Salmo 34:16', 'Salmo', 34, 16, NULL),
  ('mal', 'Pelo que, rejeitando toda imundícia e acúmulo de malícia, recebei com mansidão a palavra em vós enxertada, a qual pode salvar a vossa alma.', 'Tiago 1:21', 'Tiago', 1, 21, NULL),
  ('mal', 'Porque os olhos do Senhor estão sobre os justos, e os seus ouvidos, atentos às suas orações; mas o rosto do Senhor é contra os que fazem males.', '1 Pedro 3:12', '1 Pedro', 3, 12, NULL),
  ('mal', 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.', '1 João 1:9', '1 João', 1, 9, NULL),
  ('mal', 'Bem-aventurados sereis quando os homens vos aborrecerem, e quando vos separarem, e vos injuriarem, e rejeitarem o vosso nome como mau, por causa do Filho do Homem.', 'Lucas 6:22', 'Lucas', 6, 22, NULL),
  ('mal', 'Portanto, tomai toda a armadura de Deus, para que possais resistir no dia mau e, havendo feito tudo, ficar firmes.', 'Efésios 6:13', 'Efésios', 6, 13, NULL),
  ('mal', 'Porque, onde há inveja e espírito faccioso, aí há perturbação e toda obra perversa.', 'Tiago 3:16', 'Tiago', 3, 16, NULL),
  ('mal', 'Engano há no coração dos que maquinam mal, mas alegria têm os que aconselham a paz.', 'Provérbios 12:20', 'Provérbios', 12, 20, NULL),
  ('mal', 'Ele revela o profundo e o escondido e conhece o que está em trevas; e com ele mora a luz.', 'Daniel 2:22', 'Daniel', 2, 22, NULL),
  ('mal', 'Lembra-te do teu Criador nos dias da tua mocidade, antes que venham os maus dias, e cheguem os anos dos quais venhas a dizer: Não tenho neles contentamento.', 'Eclesiastes 12:1', 'Eclesiastes', 12, 1, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('mal', 'Porque o amor do dinheiro é a raiz de toda espécie de males; e nessa cobiça alguns se desviaram da fé e se traspassaram a si mesmos com muitas dores.', '1 Timóteo 6:10', '1 Timóteo', 6, 10, NULL),
  ('mal', 'Guarda a tua língua do mal e os teus lábios, de falarem enganosamente.', 'Salmo 34:13', 'Salmo', 34, 13, NULL),
  ('mal', 'E disse o Senhor', 'Jó 1:12', 'Jó', 1, 12, NULL),
  ('mal', 'E qual é aquele que vos fará mal, se fordes zelosos do bem?', '1 Pedro 3:13', '1 Pedro', 3, 13, NULL),
  ('mal', 'Como livres e não tendo a liberdade por cobertura da malícia, mas como servos de Deus.', '1 Pedro 2:16', '1 Pedro', 2, 16, NULL),
  ('mal', 'Seja, porém, o vosso falar: Sim, sim; não, não, porque o que passa disso é de procedência maligna.', 'Mateus 5:37', 'Mateus', 5, 37, NULL),
  ('mal', 'E não sejais como vossos pais, aos quais clamavam os primeiros profetas, dizendo: Assim diz o Senhor', 'Zacarias 1:4', 'Zacarias', 1, 4, NULL),
  ('mal', 'Não declines nem para a direita nem para a esquerda; retira o teu pé do mal.', 'Provérbios 4:27', 'Provérbios', 4, 27, NULL),
  ('mal', 'Bem-aventurados sois vós quando vos injuriarem, e perseguirem, e, mentindo, disserem todo o mal contra vós, por minha causa.', 'Mateus 5:11', 'Mateus', 5, 11, NULL),
  ('mal', 'Vede, irmãos, que nunca haja em qualquer de vós um coração mau e infiel, para se apartar do Deus vivo.', 'Hebreus 3:12', 'Hebreus', 3, 12, NULL),
  ('mal', 'Não folga com a injustiça, mas folga com a verdade; tudo sofre, tudo crê, tudo espera, tudo suporta.', '1 Coríntios 13:6-7', '1 Coríntios', 13, 6, 7),
  ('mal', 'Vós já estais limpos pela palavra que vos tenho falado.', 'João 15:3', 'João', 15, 3, NULL),
  ('mal', 'Visto como se não executa logo o juízo sobre a má obra, por isso o coração dos filhos dos homens está inteiramente disposto para praticar o mal.', 'Eclesiastes 8:11', 'Eclesiastes', 8, 11, NULL),
  ('mal', 'Então, disse o Senhor', 'Gênesis 3:22-23', 'Gênesis', 3, 22, 23),
  ('mal', 'Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça, e calçados os pés na preparação do evangelho da paz; tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno.', 'Efésios 6:14-16', 'Efésios', 6, 14, 16),
  ('mal', 'Foge, também, dos desejos da mocidade; e segue a justiça, a fé, o amor e a paz com os que, com um coração puro, invocam o Senhor.', '2 Timóteo 2:22', '2 Timóteo', 2, 22, NULL),
  ('mal', 'E Deus viu as obras deles, como se converteram do seu mau caminho; e Deus se arrependeu do mal que tinha dito lhes faria e não o fez.', 'Jonas 3:10', 'Jonas', 3, 10, NULL),
  ('materialismo', 'Porque nada trouxemos para este mundo e manifesto é que nada podemos levar dele. Tendo, porém, sustento e com que nos cobrirmos, estejamos com isso contentes.', '1 Timóteo 6:7-8', '1 Timóteo', 6, 7, 8),
  ('materialismo', 'O que amar o dinheiro nunca se fartará de dinheiro; e quem amar a abundância nunca se fartará da renda; também isso é vaidade.', 'Eclesiastes 5:10', 'Eclesiastes', 5, 10, NULL),
  ('materialismo', 'Não ajunteis tesouros na terra, onde a traça e a ferrugem tudo consomem, e onde os ladrões minam e roubam. Mas ajuntai tesouros no céu, onde nem a traça nem a ferrugem consomem, e onde os ladrões não minam, nem roubam.', 'Mateus 6:19-20', 'Mateus', 6, 19, 20),
  ('materialismo', 'Pois que aproveitaria ao homem ganhar todo o mundo e perder a sua alma?', 'Marcos 8:36', 'Marcos', 8, 36, NULL),
  ('materialismo', 'E disse-lhes: Acautelai-vos e guardai-vos da avareza, porque a vida de qualquer não consiste na abundância do que possui.', 'Lucas 12:15', 'Lucas', 12, 15, NULL),
  ('materialismo', 'Sejam vossos costumes sem avareza, contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei.', 'Hebreus 13:5', 'Hebreus', 13, 5, NULL),
  ('materialismo', 'Não atentando nós nas coisas que se veem, mas nas que se não veem; porque as que se veem são temporais, e as que se não veem são eternas.', '2 Coríntios 4:18', '2 Coríntios', 4, 18, NULL),
  ('materialismo', 'Melhor é o pouco com o temor do Senhor', 'Provérbios 15:16', 'Provérbios', 15, 16, NULL),
  ('materialismo', 'Mas os que querem ser ricos caem em tentação, e em laço, e em muitas concupiscências loucas e nocivas, que submergem os homens na perdição e ruína.', '1 Timóteo 6:9', '1 Timóteo', 6, 9, NULL),
  ('materialismo', 'Como saiu do ventre de sua mãe, assim nu voltará, indo-se como veio; e nada tomará do seu trabalho, que possa levar na sua mão.', 'Eclesiastes 5:15', 'Eclesiastes', 5, 15, NULL),
  ('materialismo', 'Porque onde estiver o vosso tesouro, aí estará também o vosso coração.', 'Mateus 6:21', 'Mateus', 6, 21, NULL),
  ('materialismo', 'Quanto melhor é adquirir a sabedoria do que o ouro! E quanto mais excelente, adquirir a prudência do que a prata!', 'Provérbios 16:16', 'Provérbios', 16, 16, NULL),
  ('materialismo', 'Disse-lhe Jesus: Se queres ser perfeito, vai, vende tudo o que tens, dá-o aos pobres e terás um tesouro no céu; e vem e segue-me.', 'Mateus 19:21', 'Mateus', 19, 21, NULL),
  ('materialismo', 'Que do mesmo modo as mulheres se ataviem em traje honesto, com pudor e modéstia, não com tranças, ou com ouro, ou pérolas, ou vestidos preciosos, mas (como convém a mulheres que fazem profissão de servir a Deus) com boas obras.', '1 Timóteo 2:9-10', '1 Timóteo', 2, 9, 10),
  ('materialismo', 'Manda aos ricos deste mundo que não sejam altivos, nem ponham a esperança na incerteza das riquezas, mas em Deus, que abundantemente nos dá todas as coisas para delas gozarmos.', '1 Timóteo 6:17', '1 Timóteo', 6, 17, NULL),
  ('materialismo', 'Afasta de mim a vaidade e a palavra mentirosa; não me dês nem a pobreza nem a riqueza; mantém-me do pão da minha porção acostumada.', 'Provérbios 30:8', 'Provérbios', 30, 8, NULL),
  ('materialismo', 'Mortificai, pois, os vossos membros que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência e a avareza, que é idolatria.', 'Colossenses 3:5', 'Colossenses', 3, 5, NULL),
  ('materialismo', 'Pois que aproveita ao homem ganhar o mundo inteiro, se perder a sua alma? Ou que dará o homem em recompensa da sua alma?', 'Mateus 16:26', 'Mateus', 16, 26, NULL),
  ('materialismo', 'Mas é grande ganho a piedade com contentamento.', '1 Timóteo 6:6', '1 Timóteo', 6, 6, NULL),
  ('materialismo', 'Mais digno de ser escolhido é o bom nome do que as muitas riquezas; e a graça é melhor do que a riqueza e o ouro.', 'Provérbios 22:1', 'Provérbios', 22, 1, NULL),
  ('materialismo', 'E era um o coração e a alma da multidão dos que criam, e ninguém dizia que coisa alguma do que possuía era sua própria, mas todas as coisas lhes eram comuns.', 'Atos 4:32', 'Atos', 4, 32, NULL),
  ('materialismo', 'Não aproveitam as riquezas no dia da ira, mas a justiça livra da morte.', 'Provérbios 11:4', 'Provérbios', 11, 4, NULL),
  ('materialismo', 'Todo o dia avidamente cobiça, mas o justo dá e nada retém.', 'Provérbios 21:26', 'Provérbios', 21, 26, NULL),
  ('materialismo', 'A fazenda do rico é sua cidade forte e, como um muro alto, na sua imaginação.', 'Provérbios 18:11', 'Provérbios', 18, 11, NULL),
  ('materialismo', 'Porventura, fitarás os olhos naquilo que não é nada? Porque, certamente, isso se fará asas e voará ao céu como a águia.', 'Provérbios 23:5', 'Provérbios', 23, 5, NULL),
  ('materialismo', 'Quem, pois, tiver bens do mundo e, vendo o seu irmão necessitado, lhe cerrar o seu coração, como estará nele o amor de Deus?', '1 João 3:17', '1 João', 3, 17, NULL),
  ('materialismo', 'Ninguém pode servir a dois senhores, porque ou há de odiar um e amar o outro ou se dedicará a um e desprezará o outro. Não podeis servir a Deus e a Mamom.', 'Mateus 6:24', 'Mateus', 6, 24, NULL),
  ('materialismo', 'Como contristados, mas sempre alegres; como pobres, mas enriquecendo a muitos; como nada tendo e possuindo tudo.', '2 Coríntios 6:10', '2 Coríntios', 6, 10, NULL),
  ('materialismo', 'A minha porção é o Senhor', 'Lamentações 3:24', 'Lamentações', 3, 24, NULL),
  ('materialismo', 'Onde a fazenda se multiplica, aí se multiplicam também os que a comem; que mais proveito, pois, têm os seus donos do que a verem com os seus olhos?', 'Eclesiastes 5:11', 'Eclesiastes', 5, 11, NULL),
  ('materialismo', 'Também vi eu que todo trabalho e toda destreza em obras trazem ao homem a inveja do seu próximo. Também isso é vaidade e aflição de espírito.', 'Eclesiastes 4:4', 'Eclesiastes', 4, 4, NULL),
  ('materialismo', 'E, respondendo ele, disse-lhes: Quem tiver duas túnicas, que reparta com o que não tem, e quem tiver alimentos, que faça da mesma maneira.', 'Lucas 3:11', 'Lucas', 3, 11, NULL),
  ('materialismo', 'Depois, eles se fartaram em proporção do seu pasto; estando fartos, ensoberbeceu-se o seu coração; por isso, se esqueceram de mim.', 'Oseias 13:6', 'Oseias', 13, 6, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('materialismo', 'O resgate da vida de cada um são as suas riquezas, mas o pobre não ouve as ameaças.', 'Provérbios 13:8', 'Provérbios', 13, 8, NULL),
  ('materialismo', 'Não cobiçarás a casa do teu próximo; não cobiçarás a mulher do teu próximo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma do teu próximo.', 'Êxodo 20:17', 'Êxodo', 20, 17, NULL),
  ('mediador', 'Porque há um só Deus e um só mediador entre Deus e os homens, Jesus Cristo, homem.', '1 Timóteo 2:5', '1 Timóteo', 2, 5, NULL),
  ('mediador', 'E, por isso, é Mediador de um novo testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna.', 'Hebreus 9:15', 'Hebreus', 9, 15, NULL),
  ('mediador', 'Ora, o medianeiro não o é de um só, mas Deus é um.', 'Gálatas 3:20', 'Gálatas', 3, 20, NULL),
  ('mediador', 'Disse-lhe Jesus: Eu sou o caminho, e a verdade, e a vida. Ninguém vem ao Pai senão por mim.', 'João 14:6', 'João', 14, 6, NULL),
  ('mediador', 'E aquele que examina os corações sabe qual é a intenção do Espírito; e é ele que segundo Deus intercede pelos santos.', 'Romanos 8:27', 'Romanos', 8, 27, NULL),
  ('mediador', 'Porque estou certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir, nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus, nosso Senhor!', 'Romanos 8:38-39', 'Romanos', 8, 38, 39),
  ('mediador', 'Não peço que os tires do mundo, mas que os livres do mal.', 'João 17:15', 'João', 17, 15, NULL),
  ('mediador', 'Àquele que não conheceu pecado, o fez pecado por nós; para que, nele, fôssemos feitos justiça de Deus.', '2 Coríntios 5:21', '2 Coríntios', 5, 21, NULL),
  ('mediador', 'Mas agora alcançou ele ministério tanto mais excelente, quanto é mediador de um melhor concerto, que está confirmado em melhores promessas.', 'Hebreus 8:6', 'Hebreus', 8, 6, NULL),
  ('mediador', 'E, quando ele vier, convencerá o mundo do pecado, e da justiça, e do juízo.', 'João 16:8', 'João', 16, 8, NULL),
  ('medo', 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te esforço, e te ajudo, e te sustento com a destra da minha justiça.', 'Isaías 41:10', 'Isaías', 41, 10, NULL),
  ('medo', 'No dia em que eu temer, hei de confiar em ti.', 'Salmo 56:3', 'Salmo', 56, 3, NULL),
  ('medo', 'Não to mandei eu? Esforça-te e tem bom ânimo; não pasmes, nem te espantes, porque o Senhor', 'Josué 1:9', 'Josué', 1, 9, NULL),
  ('medo', 'Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.', 'Filipenses 4:6-7', 'Filipenses', 4, 6, 7),
  ('medo', 'Porque eu, o Senhor', 'Isaías 41:13', 'Isaías', 41, 13, NULL),
  ('medo', 'O Senhor', 'Salmo 118:6', 'Salmo', 118, 6, NULL),
  ('medo', 'No amor, não há temor; antes, o perfeito amor lança fora o temor; porque o temor tem consigo a pena, e o que teme não é perfeito em amor.', '1 João 4:18', '1 João', 4, 18, NULL),
  ('medo', 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.', '1 Pedro 5:7', '1 Pedro', 5, 7, NULL),
  ('medo', 'Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo; a tua vara e o teu cajado me consolam.', 'Salmo 23:4', 'Salmo', 23, 4, NULL),
  ('medo', 'Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.', '2 Timóteo 1:7', '2 Timóteo', 1, 7, NULL),
  ('medo', 'Esforçai-vos, e animai-vos; não temais, nem vos espanteis diante deles, porque o Senhor', 'Deuteronômio 31:6', 'Deuteronômio', 31, 6, NULL),
  ('medo', 'O receio do homem armará laços, mas o que confia no Senhor', 'Provérbios 29:25', 'Provérbios', 29, 25, NULL),
  ('medo', 'Busquei ao Senhor', 'Salmo 34:4', 'Salmo', 34, 4, NULL),
  ('medo', 'O Senhor', 'Salmo 27:1', 'Salmo', 27, 1, NULL),
  ('medo', 'O Senhor', 'Deuteronômio 31:8', 'Deuteronômio', 31, 8, NULL),
  ('medo', 'Não se turbe o vosso coração; credes em Deus, crede também em mim.', 'João 14:1', 'João', 14, 1, NULL),
  ('medo', 'Porque não recebestes o espírito de escravidão, para, outra vez, estardes em temor, mas recebestes o espírito de adoção de filhos, pelo qual clamamos: Aba, Pai.', 'Romanos 8:15', 'Romanos', 8, 15, NULL),
  ('medo', 'Não se vendem dois passarinhos por um ceitil? E nenhum deles cairá em terra sem a vontade de vosso Pai. E até mesmo os cabelos da vossa cabeça estão todos contados. Não temais, pois; mais valeis vós do que muitos passarinhos.', 'Mateus 10:29-31', 'Mateus', 10, 29, 31),
  ('medo', 'E, assim, com confiança, ousemos dizer: O Senhor é o meu ajudador, e não temerei o que me possa fazer o homem.', 'Hebreus 13:6', 'Hebreus', 13, 6, NULL),
  ('medo', 'Mas, quando eles o viram andar sobre o mar, pensaram que era um fantasma e deram grandes gritos. Porque todos o viram e perturbaram-se; mas logo falou com eles e disse-lhes: Tende bom ânimo, sou eu; não temais.', 'Marcos 6:49-50', 'Marcos', 6, 49, 50),
  ('medo', 'Não temas, ó pequeno rebanho, porque a vosso Pai agradou dar-vos o Reino.', 'Lucas 12:32', 'Lucas', 12, 32, NULL),
  ('medo', 'Mas também, se padecerdes por amor da justiça, sois bem-aventurados. E não temais com medo deles, nem vos turbeis.', '1 Pedro 3:14', '1 Pedro', 3, 14, NULL),
  ('medo', 'Jesus, porém, ouvindo-o, respondeu-lhe, dizendo: Não temas; crê somente, e será salva.', 'Lucas 8:50', 'Lucas', 8, 50, NULL),
  ('medo', 'Em Deus louvarei a sua palavra; em Deus pus a minha confiança e não temerei; que me pode fazer a carne?', 'Salmo 56:4', 'Salmo', 56, 4, NULL),
  ('medo', 'Como um pai se compadece de seus filhos, assim o Senhor', 'Salmo 103:13', 'Salmo', 103, 13, NULL),
  ('medo', 'Disse-lhe, então, o anjo: Maria, não temas, porque achaste graça diante de Deus, E eis que em teu ventre conceberás, e darás à luz um filho, e pôr-lhe-ás o nome de Jesus.', 'Lucas 1:30-31', 'Lucas', 1, 30, 31),
  ('medo', 'Eu, eu sou aquele que vos consola; quem pois és tu, para que temas o homem, que é mortal, ou o filho do homem, que se tornará em feno?', 'Isaías 51:12', 'Isaías', 51, 12, NULL),
  ('medo', 'Ainda que um exército me cercasse, o meu coração não temeria; ainda que a guerra se levantasse contra mim, nele confiaria.', 'Salmo 27:3', 'Salmo', 27, 3, NULL),
  ('medo', 'Oh! Quão grande é a tua bondade, que guardaste para os que te temem, e que tu mostraste àqueles que em ti confiam na presença dos filhos dos homens!', 'Salmo 31:19', 'Salmo', 31, 19, NULL),
  ('medo', 'E não temais os que matam o corpo e não podem matar a alma; temei, antes, aquele que pode fazer perecer no inferno a alma e o corpo.', 'Mateus 10:28', 'Mateus', 10, 28, NULL),
  ('medo', 'Não se vendem cinco passarinhos por dois ceitis? E nenhum deles está esquecido diante de Deus. E até os cabelos da vossa cabeça estão todos contados. Não temais, pois; mais valeis vós do que muitos passarinhos.', 'Lucas 12:6-7', 'Lucas', 12, 6, 7),
  ('medo', 'E o anjo lhes disse: Não temais, porque eis aqui vos trago novas de grande alegria, que será para todo o povo.', 'Lucas 2:10', 'Lucas', 2, 10, NULL),
  ('medo', 'O resgate da vida de cada um são as suas riquezas, mas o pobre não ouve as ameaças.', 'Provérbios 13:8', 'Provérbios', 13, 8, NULL),
  ('medo', 'Porque os costumes dos povos são vaidade; pois cortam do bosque um madeiro, obra das mãos do artífice, com machado. Com prata e com ouro o enfeitam, com pregos e com martelos o firmam, para que não se mova. São como a palmeira, obra torneada, mas não podem falar; necessitam de quem os leve, porquanto não podem andar; não tenhais receio deles, pois não podem fazer mal, nem tampouco têm poder de fazer bem.', 'Jeremias 10:3-5', 'Jeremias', 10, 3, 5),
  ('mente', 'Pensai nas coisas que são de cima e não nas que são da terra.', 'Colossenses 3:2', 'Colossenses', 3, 2, NULL),
  ('mente', 'Portanto, vede prudentemente como andais, não como néscios, mas como sábios, remindo o tempo, porquanto os dias são maus.', 'Efésios 5:15-16', 'Efésios', 5, 15, 16),
  ('mente', 'E Jesus disse-lhe: Amarás o Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todo o teu pensamento.', 'Mateus 22:37', 'Mateus', 22, 37, NULL),
  ('mente', 'O que adquire entendimento ama a sua alma; o que conserva a inteligência achará o bem.', 'Provérbios 19:8', 'Provérbios', 19, 8, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('mente', 'Porque, na muita sabedoria, há muito enfado; e o que aumenta em ciência aumenta em trabalho.', 'Eclesiastes 1:18', 'Eclesiastes', 1, 18, NULL),
  ('mente', 'O avisado vê o mal e esconde-se; mas os simples passam e sofrem a pena.', 'Provérbios 27:12', 'Provérbios', 27, 12, NULL),
  ('mente', 'Bem-aventurado o homem que acha sabedoria, e o homem que adquire conhecimento.', 'Provérbios 3:13', 'Provérbios', 3, 13, NULL),
  ('mente', 'Como o ferro com o ferro se aguça, assim o homem afia o rosto do seu amigo.', 'Provérbios 27:17', 'Provérbios', 27, 17, NULL),
  ('mente', 'Quem dentre vós é sábio e inteligente? Mostre, pelo seu bom trato, as suas obras em mansidão de sabedoria.', 'Tiago 3:13', 'Tiago', 3, 13, NULL),
  ('mente', 'Todo aquele, pois, que escuta estas minhas palavras e as pratica, assemelhá-lo-ei ao homem prudente, que edificou a sua casa sobre a rocha.', 'Mateus 7:24', 'Mateus', 7, 24, NULL),
  ('mente', 'Até o tolo, quando se cala, será reputado por sábio; e o que cerrar os seus lábios, por sábio.', 'Provérbios 17:28', 'Provérbios', 17, 28, NULL),
  ('mente', 'Porque, pela graça que me é dada, digo a cada um dentre vós que não saiba mais do que convém saber, mas que saiba com temperança, conforme a medida da fé que Deus repartiu a cada um.', 'Romanos 12:3', 'Romanos', 12, 3, NULL),
  ('mente', 'Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder como a sua divindade, se entendem e claramente se veem pelas coisas que estão criadas, para que eles fiquem inescusáveis.', 'Romanos 1:20', 'Romanos', 1, 20, NULL),
  ('mente', 'Porque nada me propus saber entre vós, senão a Jesus Cristo e este crucificado.', '1 Coríntios 2:2', '1 Coríntios', 2, 2, NULL),
  ('mente', 'O tolo despreza a correção de seu pai, mas o que observa a repreensão prudentemente se haverá.', 'Provérbios 15:5', 'Provérbios', 15, 5, NULL),
  ('mente', 'E que amá-lo de todo o coração, e de todo o entendimento, e de toda a alma, e de todas as forças e amar o próximo como a si mesmo é mais do que todos os holocaustos e sacrifícios.', 'Marcos 12:33', 'Marcos', 12, 33, NULL),
  ('mentir', 'Os lábios mentirosos são abomináveis ao Senhor', 'Provérbios 12:22', 'Provérbios', 12, 22, NULL),
  ('mentir', 'Porque quem quer amar a vida e ver os dias bons, refreie a sua língua do mal, e os seus lábios não falem engano; aparte-se do mal e faça o bem; busque a paz e siga-a.', '1 Pedro 3:10-11', '1 Pedro', 3, 10, 11),
  ('mentir', 'Senhor', 'Salmo 120:2', 'Salmo', 120, 2, NULL),
  ('mentir', 'Aquele que anda em sinceridade, e pratica a justiça, e fala verazmente segundo o seu coração; aquele que não difama com a sua língua, nem faz mal ao seu próximo, nem aceita nenhuma afronta contra o seu próximo.', 'Salmo 15:2-3', 'Salmo', 15, 2, 3),
  ('mentir', 'Guarda a tua língua do mal e os teus lábios, de falarem enganosamente.', 'Salmo 34:13', 'Salmo', 34, 13, NULL),
  ('mentir', 'E dizia: O que sai do homem, isso é que contamina o homem. Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios, os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura. Todos estes males procedem de dentro e contaminam o homem.', 'Marcos 7:20-23', 'Marcos', 7, 20, 23),
  ('mentir', 'Não mintais uns aos outros, pois que já vos despistes do velho homem com os seus feitos e vos vestistes do novo, que se renova para o conhecimento, segundo a imagem daquele que o criou.', 'Colossenses 3:9-10', 'Colossenses', 3, 9, 10),
  ('mentir', 'O que encobre o ódio tem lábios falsos, e o que difama é um insensato.', 'Provérbios 10:18', 'Provérbios', 10, 18, NULL),
  ('mentir', 'Se dissermos que temos comunhão com ele e andarmos em trevas, mentimos e não praticamos a verdade.', '1 João 1:6', '1 João', 1, 6, NULL),
  ('mentir', 'Quem anda em sinceridade anda seguro, mas o que perverte os seus caminhos será conhecido.', 'Provérbios 10:9', 'Provérbios', 10, 9, NULL),
  ('mentir', 'A testemunha verdadeira não mentirá, mas a testemunha falsa se desboca em mentiras.', 'Provérbios 14:5', 'Provérbios', 14, 5, NULL),
  ('mentir', 'Vós tendes por pai ao diabo e quereis satisfazer os desejos de vosso pai; ele foi homicida desde o princípio e não se firmou na verdade, porque não há verdade nele; quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira.', 'João 8:44', 'João', 8, 44, NULL),
  ('mentir', 'O homem perverso levanta a contenda, e o difamador separa os maiores amigos.', 'Provérbios 16:28', 'Provérbios', 16, 28, NULL),
  ('mentir', 'Não matarás, não cometerás adultério, não furtarás, não dirás falso testemunho; honra teu pai e tua mãe, e amarás o teu próximo como a ti mesmo.', 'Mateus 19:18b-19', 'Mateus 19:18b-19', NULL, NULL, NULL),
  ('mentir', 'Afasta de mim a vaidade e a palavra mentirosa; não me dês nem a pobreza nem a riqueza; mantém-me do pão da minha porção acostumada.', 'Provérbios 30:8', 'Provérbios', 30, 8, NULL),
  ('mentir', 'Bem-aventurados sois vós quando vos injuriarem, e perseguirem, e, mentindo, disserem todo o mal contra vós, por minha causa.', 'Mateus 5:11', 'Mateus', 5, 11, NULL),
  ('mentir', 'O temor do Senhor', 'Provérbios 8:13', 'Provérbios', 8, 13, NULL),
  ('mentir', 'Disse, então, Pedro: Ananias, por que encheu Satanás o teu coração, para que mentisses ao Espírito Santo e retivesses parte do preço da herdade? Guardando-a, não ficava para ti? E, vendida, não estava em teu poder? Por que formaste este desígnio em teu coração? Não mentiste aos homens, mas a Deus.', 'Atos 5:3-4', 'Atos', 5, 3, 4),
  ('mentir', 'Uma língua saudável é árvore de vida, mas a perversidade nela quebranta o espírito.', 'Provérbios 15:4', 'Provérbios', 15, 4, NULL),
  ('mentir', 'Desvia de ti a tortuosidade da boca e alonga de ti a perversidade dos lábios.', 'Provérbios 4:24', 'Provérbios', 4, 24, NULL),
  ('mentir', 'Não convém ao tolo a fala excelente; quanto menos ao príncipe, o lábio mentiroso!', 'Provérbios 17:7', 'Provérbios', 17, 7, NULL),
  ('mentir', 'Os lábios do justo sabem o que agrada, mas a boca dos ímpios anda cheia de perversidades.', 'Provérbios 10:32', 'Provérbios', 10, 32, NULL),
  ('mentir', 'Deus não é homem, para que minta; nem filho de homem, para que se arrependa; porventura, diria ele e não o faria? Ou falaria e não o confirmaria?', 'Números 23:19', 'Números', 23, 19, NULL),
  ('mentir', 'O que anda praguejando descobre o segredo, mas o fiel de espírito encobre o negócio.', 'Provérbios 11:13', 'Provérbios', 11, 13, NULL),
  ('mentir', 'Sabendo isto: que a lei não é feita para o justo, mas para os injustos e obstinados, para os ímpios e pecadores, para os profanos e irreligiosos, para os parricidas e matricidas, para os homicidas, para os fornicadores, para os sodomitas, para os roubadores de homens, para os mentirosos, para os perjuros e para o que for contrário à sã doutrina, conforme o evangelho da glória do Deus bem-aventurado, que me foi confiado.', '1 Timóteo 1:9-11', '1 Timóteo', 1, 9, 11),
  ('messias', 'Disse-lhes ele: E vós, quem dizeis que eu sou? E Simão Pedro, respondendo, disse: Tu és o Cristo, o Filho do Deus vivo.', 'Mateus 16:15-16', 'Mateus', 16, 15, 16),
  ('messias', 'Porque um menino nos nasceu, um filho se nos deu; e o principado está sobre os seus ombros; e o seu nome será Maravilhoso Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz.', 'Isaías 9:6', 'Isaías', 9, 6, NULL),
  ('messias', 'Por isso, estai vós apercebidos também, porque o Filho do Homem há de vir à hora em que não penseis.', 'Mateus 24:44', 'Mateus', 24, 44, NULL),
  ('messias', 'Pois, na cidade de Davi, vos nasceu hoje o Salvador, que é Cristo, o Senhor.', 'Lucas 2:11', 'Lucas', 2, 11, NULL),
  ('messias', 'E todos os dias, no templo e nas casas, não cessavam de ensinar e de anunciar a Jesus Cristo.', 'Atos 5:42', 'Atos', 5, 42, NULL),
  ('messias', 'Mas, alcançando socorro de Deus, ainda até ao dia de hoje permaneço, dando testemunho, tanto a pequenos como a grandes, não dizendo nada mais do que o que os profetas e Moisés disseram que devia acontecer, isto é, que o Cristo devia padecer e, sendo o primeiro da ressurreição dos mortos, devia anunciar a luz a este povo e aos gentios.', 'Atos 26:22-23', 'Atos', 26, 22, 23),
  ('messias', 'Bem-aventurado e santo aquele que tem parte na primeira ressurreição; sobre estes não tem poder a segunda morte, mas serão sacerdotes de Deus e de Cristo e reinarão com ele mil anos.', 'Apocalipse 20:6', 'Apocalipse', 20, 6, NULL),
  ('milagres', 'Jesus, porém, olhando para eles, disse: Para os homens é impossível, mas não para Deus, porque para Deus todas as coisas são possíveis.', 'Marcos 10:27', 'Marcos', 10, 27, NULL),
  ('milagres', 'E Jesus disse-lhe: Se tu podes crer; tudo é possível ao que crê.', 'Marcos 9:23', 'Marcos', 9, 23, NULL),
  ('milagres', 'Eis que eu sou o Senhor', 'Jeremias 32:27', 'Jeremias', 32, 27, NULL),
  ('milagres', 'Mas ele respondeu: As coisas que são impossíveis aos homens são possíveis a Deus.', 'Lucas 18:27', 'Lucas', 18, 27, NULL),
  ('milagres', 'Jesus, porém, ouvindo-o, respondeu-lhe, dizendo: Não temas; crê somente, e será salva.', 'Lucas 8:50', 'Lucas', 8, 50, NULL),
  ('milagres', 'Porque para Deus nada é impossível.', 'Lucas 1:37', 'Lucas', 1, 37, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('milagres', 'Pois possuíste o meu interior; entreteceste-me no ventre de minha mãe. Eu te louvarei, porque de um modo terrível e tão maravilhoso fui formado; maravilhosas são as tuas obras, e a minha alma o sabe muito bem.', 'Salmo 139:13-14', 'Salmo', 139, 13, 14),
  ('milagres', 'E Jesus, olhando para eles, disse-lhes: Aos homens é isso impossível, mas a Deus tudo é possível.', 'Mateus 19:26', 'Mateus', 19, 26, NULL),
  ('milagres', 'E Jesus lhes disse: Por causa da vossa pequena fé; porque em verdade vos digo que, se tiverdes fé como um grão de mostarda, direis a este monte: Passa daqui para acolá — e há de passar; e nada vos será impossível.', 'Mateus 17:20', 'Mateus', 17, 20, NULL),
  ('milagres', 'Eu te louvarei, Senhor', 'Salmo 9:1', 'Salmo', 9, 1, NULL),
  ('milagres', 'E, tomando os cinco pães e os dois peixes e olhando para o céu, abençoou-os, e partiu-os, e deu-os aos seus discípulos para os porem diante da multidão. E comeram todos e saciaram-se; e levantaram, do que lhes sobejou, doze cestos de pedaços.', 'Lucas 9:16-17', 'Lucas', 9, 16, 17),
  ('milagres', 'Jesus, porém, respondendo, disse-lhes: Em verdade vos digo que, se tiverdes fé e não duvidardes, não só fareis o que foi feito à figueira, mas até, se a este monte disserdes: Ergue-te e precipita-te no mar, assim será feito.', 'Mateus 21:21', 'Mateus', 21, 21, NULL),
  ('milagres', 'E ensinava no sábado, numa das sinagogas. E eis que estava ali uma mulher que tinha um espírito de enfermidade havia já dezoito anos; e andava curvada e não podia de modo algum endireitar-se. E, vendo-a Jesus, chamou-a a si, e disse-lhe: Mulher, estás livre da tua enfermidade. E impôs as mãos sobre ela, e logo se endireitou e glorificava a Deus. E, tomando a palavra o príncipe da sinagoga, indignado porque Jesus curava no sábado, disse à multidão: Seis dias há em que é mister trabalhar; nestes, pois, vinde para serdes curados e não no dia de sábado. Respondeu-lhe, porém, o Senhor e disse: Hipócrita, no sábado não desprende da manjedoura cada um de vós o seu boi ou jumento e não o leva a beber água? E não convinha soltar desta prisão, no dia de sábado, esta filha de Abraão, a qual há dezoito anos Satanás mantinha presa? E, dizendo ele isso, todos os seus adversários ficaram envergonhados, e todo o povo se alegrava por todas as coisas gloriosas que eram feitas por ele.', 'Lucas 13:10-17', 'Lucas', 13, 10, 17),
  ('milagres', 'Mas, quando eles o viram andar sobre o mar, pensaram que era um fantasma e deram grandes gritos. Porque todos o viram e perturbaram-se; mas logo falou com eles e disse-lhes: Tende bom ânimo, sou eu; não temais.', 'Marcos 6:49-50', 'Marcos', 6, 49, 50),
  ('milagres', 'E caí por terra e ouvi uma voz que me dizia: Saulo, Saulo, por que me persegues?', 'Atos 22:7', 'Atos', 22, 7, NULL),
  ('milagres', 'E, tendo eles orado, moveu-se o lugar em que estavam reunidos; e todos foram cheios do Espírito Santo e anunciavam com ousadia a palavra de Deus.', 'Atos 4:31', 'Atos', 4, 31, NULL),
  ('milagres', 'Tão somente temei ao Senhor', '1 Samuel 12:24', '1 Samuel', 12, 24, NULL),
  ('milagres', 'E, quando dizia isto, vendo-o eles, foi elevado às alturas, e uma nuvem o recebeu, ocultando-o a seus olhos.', 'Atos 1:9', 'Atos', 1, 9, NULL),
  ('milagres', 'Portanto, o mesmo Senhor vos dará um sinal: eis que uma virgem conceberá, e dará à luz um filho, e será o seu nome Emanuel.', 'Isaías 7:14', 'Isaías', 7, 14, NULL),
  ('milagres', 'Tudo isso aconteceu para que se cumprisse o que foi dito da parte do Senhor pelo profeta, que diz: Eis que a virgem conceberá e dará à luz um filho, e ele será chamado pelo nome de Emanuel. (Emanuel traduzido é: Deus conosco).', 'Mateus 1:22-23', 'Mateus', 1, 22, 23),
  ('milagres', 'Então, entrou também o outro discípulo, que chegara primeiro ao sepulcro, e viu, e creu. Porque ainda não sabiam a Escritura, que diz que era necessário que ressuscitasse dos mortos.', 'João 20:8-9', 'João', 20, 8, 9),
  ('milagres', 'Ora, o nascimento de Jesus Cristo foi assim: Estando Maria, sua mãe, desposada com José, antes de se ajuntarem, achou-se ter concebido do Espírito Santo.', 'Mateus 1:18', 'Mateus', 1, 18, NULL),
  ('misericordia', 'Cheguemos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno.', 'Hebreus 4:16', 'Hebreus', 4, 16, NULL),
  ('misericordia', 'Ide, porém, e aprendei o que significa: Misericórdia quero e não sacrifício. Porque eu não vim para chamar os justos, mas os pecadores, ao arrependimento.', 'Mateus 9:13', 'Mateus', 9, 13, NULL),
  ('misericordia', 'Mas Deus, que é riquíssimo em misericórdia, pelo seu muito amor com que nos amou, estando nós ainda mortos em nossas ofensas, nos vivificou juntamente com Cristo (pela graça sois salvos).', 'Efésios 2:4-5', 'Efésios', 2, 4, 5),
  ('misericordia', 'Tem misericórdia de mim, ó Deus, segundo a tua benignidade; apaga as minhas transgressões, segundo a multidão das tuas misericórdias. Lava-me completamente da minha iniquidade e purifica-me do meu pecado.', 'Salmo 51:1-2', 'Salmo', 51, 1, 2),
  ('misericordia', 'Porque o Senhor', '2 Crônicas 30:9b', '2 Crônicas 30:9b', NULL, NULL, NULL),
  ('misericordia', 'Quem, ó Deus, é semelhante a ti, que perdoas a iniquidade e que te esqueces da rebelião do restante da tua herança? O Senhor', 'Miqueias 7:18', 'Miqueias', 7, 18, NULL),
  ('misericordia', 'Por isso, o Senhor', 'Isaías 30:18', 'Isaías', 30, 18, NULL),
  ('misericordia', 'Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós.', 'Mateus 6:14', 'Mateus', 6, 14, NULL),
  ('misericordia', 'Lembra-te, Senhor', 'Salmo 25:6-7', 'Salmo', 25, 6, 7),
  ('misericordia', 'Não detenhas para comigo, Senhor', 'Salmo 40:11', 'Salmo', 40, 11, NULL),
  ('misericordia', 'Rogo-vos, pois, irmãos, pela compaixão de Deus, que apresenteis o vosso corpo em sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional.', 'Romanos 12:1', 'Romanos', 12, 1, NULL),
  ('misericordia', 'Certamente que a bondade e a misericórdia me seguirão todos os dias da minha vida; e habitarei na Casa do Senhor', 'Salmo 23:6', 'Salmo', 23, 6, NULL),
  ('misericordia', 'E seja sobre nós a graça do Senhor, nosso Deus; e confirma sobre nós a obra das nossas mãos; sim, confirma a obra das nossas mãos.', 'Salmo 90:17', 'Salmo', 90, 17, NULL),
  ('misericordia', 'Pois quê? Pecaremos porque não estamos debaixo da lei, mas debaixo da graça? De modo nenhum!', 'Romanos 6:15', 'Romanos', 6, 15, NULL),
  ('misericordia', 'Mas, pela tua grande misericórdia, não os destruíste nem desamparaste; porque és um Deus clemente e misericordioso.', 'Neemias 9:31', 'Neemias', 9, 31, NULL),
  ('misericordia', 'Bem irá ao homem que se compadece e empresta; disporá as suas coisas com juízo.', 'Salmo 112:5', 'Salmo', 112, 5, NULL),
  ('misericordia', 'Das profundezas a ti clamo, ó Senhor', 'Salmo 130:1-2', 'Salmo', 130, 1, 2),
  ('misericordia', 'E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. De boa vontade, pois, me gloriarei nas minhas fraquezas, para que em mim habite o poder de Cristo.', '2 Coríntios 12:9', '2 Coríntios', 12, 9, NULL),
  ('misericordia', 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'João', 3, 16, NULL),
  ('misericordia', 'O que encobre as suas transgressões nunca prosperará; mas o que as confessa e deixa alcançará misericórdia.', 'Provérbios 28:13', 'Provérbios', 28, 13, NULL),
  ('misericordia', 'Deixe o ímpio o seu caminho, e o homem maligno, os seus pensamentos e se converta ao Senhor', 'Isaías 55:7', 'Isaías', 55, 7, NULL),
  ('misericordia', 'Mas não é assim o dom gratuito como a ofensa; porque, se, pela ofensa de um, morreram muitos, muito mais a graça de Deus e o dom pela graça, que é de um só homem, Jesus Cristo, abundou sobre muitos.', 'Romanos 5:15', 'Romanos', 5, 15, NULL),
  ('misericordia', 'Não pelas obras de justiça que houvéssemos feito, mas, segundo a sua misericórdia, nos salvou pela lavagem da regeneração e da renovação do Espírito Santo.', 'Tito 3:5', 'Tito', 3, 5, NULL),
  ('misericordia', 'Então, Pedro, aproximando-se dele, disse: Senhor, até quantas vezes pecará meu irmão contra mim, e eu lhe perdoarei? Até sete? Jesus lhe disse: Não te digo que até sete, mas até setenta vezes sete.', 'Mateus 18:21-22', 'Mateus', 18, 21, 22),
  ('misericordia', 'A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com vós todos. Amém!', '2 Coríntios 13:13', '2 Coríntios', 13, 13, NULL),
  ('misericordia', 'Volta, ó rebelde Israel, diz o Senhor', 'Jeremias 3:12b', 'Jeremias 3:12b', NULL, NULL, NULL),
  ('misericordia', 'Porque a vós vos foi concedido, em relação a Cristo, não somente crer nele, como também padecer por ele.', 'Filipenses 1:29', 'Filipenses', 1, 29, NULL),
  ('morte', 'Disse-lhe Jesus: Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá; e todo aquele que vive e crê em mim nunca morrerá. Crês tu isso?', 'João 11:25-26', 'João', 11, 25, 26),
  ('morte', 'Porque, se vivemos, para o Senhor vivemos; se morremos, para o Senhor morremos. De sorte que, ou vivamos ou morramos, somos do Senhor.', 'Romanos 14:8', 'Romanos', 14, 8, NULL),
  ('morte', 'Porque o mesmo Senhor descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus; e os que morreram em Cristo ressuscitarão primeiro; depois, nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o Senhor nos ares, e assim estaremos sempre com o Senhor.', '1 Tessalonicenses 4:16-17', '1 Tessalonicenses', 4, 16, 17),
  ('morte', 'Porque para mim o viver é Cristo, e o morrer é ganho.', 'Filipenses 1:21', 'Filipenses', 1, 21, NULL),
  ('morte', 'Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo; a tua vara e o teu cajado me consolam.', 'Salmo 23:4', 'Salmo', 23, 4, NULL),
  ('morte', 'Palavra fiel é esta: que, se morrermos com ele, também com ele viveremos.', '2 Timóteo 2:11', '2 Timóteo', 2, 11, NULL),
  ('morte', 'Põe-me como selo sobre o teu coração, como selo sobre o teu braço, porque o amor é forte como a morte, e duro como a sepultura o ciúme; as suas brasas são brasas de fogo, labaredas do Senhor', 'Cantares 8:6', 'Cantares', 8, 6, NULL);

