-- Parte 09: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('morte', 'Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo.', '1 Coríntios 15:22', '1 Coríntios', 15, 22, NULL),
  ('morte', 'Porque estou certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir, nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus, nosso Senhor!', 'Romanos 8:38-39', 'Romanos', 8, 38, 39),
  ('morte', 'Porque não tomo prazer na morte do que morre, diz o Senhor Jeová; convertei-vos, pois, e vivei.', 'Ezequiel 18:32', 'Ezequiel', 18, 32, NULL),
  ('morte', 'E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles e será o seu Deus. E Deus limpará de seus olhos toda lágrima, e não haverá mais morte, nem pranto, nem clamor, nem dor, porque já as primeiras coisas são passadas.', 'Apocalipse 21:3-4', 'Apocalipse', 21, 3, 4),
  ('morte', 'Porque sabemos que, se a nossa casa terrestre deste tabernáculo se desfizer, temos de Deus um edifício, uma casa não feita por mãos, eterna, nos céus.', '2 Coríntios 5:1', '2 Coríntios', 5, 1, NULL),
  ('morte', 'Mas de ambos os lados estou em aperto, tendo desejo de partir e estar com Cristo, porque isto é ainda muito melhor. Mas julgo mais necessário, por amor de vós, ficar na carne.', 'Filipenses 1:23-24', 'Filipenses', 1, 23, 24),
  ('morte', 'Porque, assim como a morte veio por um homem, também a ressurreição dos mortos veio por um homem.', '1 Coríntios 15:21', '1 Coríntios', 15, 21, NULL),
  ('morte', 'E, no Hades, ergueu os olhos, estando em tormentos, e viu ao longe Abraão e Lázaro, no seu seio. E, clamando, disse: Abraão, meu pai, tem misericórdia de mim e manda a Lázaro que molhe na água a ponta do seu dedo e me refresque a língua, porque estou atormentado nesta chama.', 'Lucas 16:23-24', 'Lucas', 16, 23, 24),
  ('morte', 'Porque aquele que quiser salvar a sua vida perdê-la-á, e quem perder a sua vida por amor de mim achá-la-á.', 'Mateus 16:25', 'Mateus', 16, 25, NULL),
  ('morte', 'Para onde me irei do teu Espírito ou para onde fugirei da tua face? Se subir ao céu, tu aí estás; se fizer no Seol a minha cama, eis que tu ali estás também.', 'Salmo 139:7-8', 'Salmo', 139, 7, 8),
  ('morte', 'E não temais os que matam o corpo e não podem matar a alma; temei, antes, aquele que pode fazer perecer no inferno a alma e o corpo.', 'Mateus 10:28', 'Mateus', 10, 28, NULL),
  ('morte', 'E, clamando Jesus com grande voz, disse: Pai, nas tuas mãos entrego o meu espírito. E, havendo dito isso, expirou.', 'Lucas 23:46', 'Lucas', 23, 46, NULL),
  ('morte', 'Bem-aventurado e santo aquele que tem parte na primeira ressurreição; sobre estes não tem poder a segunda morte, mas serão sacerdotes de Deus e de Cristo e reinarão com ele mil anos.', 'Apocalipse 20:6', 'Apocalipse', 20, 6, NULL),
  ('morte', 'Porque apenas alguém morrerá por um justo; pois poderá ser que pelo bom alguém ouse morrer. Mas Deus prova o seu amor para conosco em que Cristo morreu por nós, sendo nós ainda pecadores.', 'Romanos 5:7-8', 'Romanos', 5, 7, 8),
  ('morte', 'E eis aqui eu vou, hoje, pelo caminho de toda a terra; e vós bem sabeis, com todo o vosso coração e com toda a vossa alma que nem uma só palavra caiu de todas as boas palavras que falou de vós o Senhor, vosso Deus; todas vos sobrevieram, nem delas caiu uma só palavra.', 'Josué 23:14', 'Josué', 23, 14, NULL),
  ('morte', 'Vós tendes por pai ao diabo e quereis satisfazer os desejos de vosso pai; ele foi homicida desde o princípio e não se firmou na verdade, porque não há verdade nele; quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira.', 'João 8:44', 'João', 8, 44, NULL),
  ('morte', 'Desejaria eu, de qualquer maneira, a morte do ímpio? Diz o Senhor Jeová; não desejo, antes, que se converta dos seus caminhos e viva?', 'Ezequiel 18:23', 'Ezequiel', 18, 23, NULL),
  ('mundo', 'Não ameis o mundo, nem o que no mundo há. Se alguém ama o mundo, o amor do Pai não está nele.', '1 João 2:15', '1 João', 2, 15, NULL),
  ('mundo', 'E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.', 'Romanos 12:2', 'Romanos', 12, 2, NULL),
  ('mundo', 'Pois que aproveitaria ao homem ganhar todo o mundo e perder a sua alma?', 'Marcos 8:36', 'Marcos', 8, 36, NULL),
  ('mundo', 'Porque, andando na carne, não militamos segundo a carne.', '2 Coríntios 10:3', '2 Coríntios', 10, 3, NULL),
  ('mundo', 'Tenho-vos dito isso, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo; eu venci o mundo.', 'João 16:33', 'João', 16, 33, NULL),
  ('mundo', 'Porque a graça de Deus se há manifestado, trazendo salvação a todos os homens, ensinando-nos que, renunciando à impiedade e às concupiscências mundanas, vivamos neste presente século sóbria, justa e piamente.', 'Tito 2:11-12', 'Tito', 2, 11, 12),
  ('mundo', 'E o mundo passa, e a sua concupiscência; mas aquele que faz a vontade de Deus permanece para sempre.', '1 João 2:17', '1 João', 2, 17, NULL),
  ('mundo', 'Adúlteros e adúlteras, não sabeis vós que a amizade do mundo é inimizade contra Deus? Portanto, qualquer que quiser ser amigo do mundo constitui-se inimigo de Deus.', 'Tiago 4:4', 'Tiago', 4, 4, NULL),
  ('mundo', 'Porque tudo o que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a soberba da vida, não é do Pai, mas do mundo.', '1 João 2:16', '1 João', 2, 16, NULL),
  ('mundo', 'Porque nada trouxemos para este mundo e manifesto é que nada podemos levar dele. Tendo, porém, sustento e com que nos cobrirmos, estejamos com isso contentes.', '1 Timóteo 6:7-8', '1 Timóteo', 6, 7, 8),
  ('mundo', 'E disse-lhes: Ide por todo o mundo, pregai o evangelho a toda criatura.', 'Marcos 16:15', 'Marcos', 16, 15, NULL),
  ('mundo', 'Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.', '1 João 5:4', '1 João', 5, 4, NULL),
  ('mundo', 'Ninguém se engane a si mesmo: se alguém dentre vós se tem por sábio neste mundo, faça-se louco para ser sábio.', '1 Coríntios 3:18', '1 Coríntios', 3, 18, NULL),
  ('mundo', 'Falou-lhes, pois, Jesus outra vez, dizendo: Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.', 'João 8:12', 'João', 8, 12, NULL),
  ('mundo', 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.', 'João 14:27', 'João', 14, 27, NULL),
  ('mundo', 'Pois que aproveita ao homem ganhar o mundo inteiro, se perder a sua alma? Ou que dará o homem em recompensa da sua alma?', 'Mateus 16:26', 'Mateus', 16, 26, NULL),
  ('mundo', 'Pensai nas coisas que são de cima e não nas que são da terra.', 'Colossenses 3:2', 'Colossenses', 3, 2, NULL),
  ('mundo', 'E Deus escolheu as coisas vis deste mundo, e as desprezíveis, e as que não são para aniquilar as que são; para que nenhuma carne se glorie perante ele.', '1 Coríntios 1:28-29', '1 Coríntios', 1, 28, 29),
  ('mundo', 'Não peço que os tires do mundo, mas que os livres do mal.', 'João 17:15', 'João', 17, 15, NULL),
  ('mundo', 'Quem é que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus?', '1 João 5:5', '1 João', 5, 5, NULL),
  ('mundo', 'Se o mundo vos aborrece, sabei que, primeiro do que a vós, me aborreceu a mim.', 'João 15:18', 'João', 15, 18, NULL),
  ('mundo', 'Vede quão grande amor nos tem concedido o Pai: que fôssemos chamados filhos de Deus. Por isso, o mundo não nos conhece, porque não conhece a ele.', '1 João 3:1', '1 João', 3, 1, NULL),
  ('mundo', 'Pelas quais ele nos tem dado grandíssimas e preciosas promessas, para que por elas fiqueis participantes da natureza divina, havendo escapado da corrupção, que, pela concupiscência, há no mundo.', '2 Pedro 1:4', '2 Pedro', 1, 4, NULL),
  ('mundo', 'Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder como a sua divindade, se entendem e claramente se veem pelas coisas que estão criadas, para que eles fiquem inescusáveis.', 'Romanos 1:20', 'Romanos', 1, 20, NULL),
  ('mundo', 'A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e guardar-se da corrupção do mundo.', 'Tiago 1:27', 'Tiago', 1, 27, NULL),
  ('mundo', 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'João', 3, 16, NULL),
  ('mundo', 'Oh! Quão grande é a tua bondade, que guardaste para os que te temem, e que tu mostraste àqueles que em ti confiam na presença dos filhos dos homens!', 'Salmo 31:19', 'Salmo', 31, 19, NULL),
  ('mundo', 'E ele é a propiciação pelos nossos pecados e não somente pelos nossos, mas também pelos de todo o mundo.', '1 João 2:2', '1 João', 2, 2, NULL),
  ('mundo', 'Do Senhor é a terra e a sua plenitude, o mundo e aqueles que nele habitam.', 'Salmo 24:1', 'Salmo', 24, 1, NULL),
  ('mundo', 'Pelo que hoje saberás e refletirás no teu coração que só o Senhor é Deus em cima no céu e embaixo na terra; nenhum outro há.', 'Deuteronômio 4:39', 'Deuteronômio', 4, 39, NULL),
  ('mundo', 'Não cuideis que vim trazer a paz à terra; não vim trazer paz, mas espada.', 'Mateus 10:34', 'Mateus', 10, 34, NULL),
  ('mundo', 'E eu te darei as chaves do Reino dos céus, e tudo o que ligares na terra será ligado nos céus, e tudo o que desligares na terra será desligado nos céus.', 'Mateus 16:19', 'Mateus', 16, 19, NULL),
  ('mundo', 'Isto é, Deus estava em Cristo reconciliando consigo o mundo, não lhes imputando os seus pecados, e pôs em nós a palavra da reconciliação.', '2 Coríntios 5:19', '2 Coríntios', 5, 19, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('mundo', 'Filhinhos, sois de Deus e já os tendes vencido, porque maior é o que está em vós do que o que está no mundo.', '1 João 4:4', '1 João', 4, 4, NULL),
  ('mundo', 'Porque Deus enviou o seu Filho ao mundo não para que condenasse o mundo, mas para que o mundo fosse salvo por ele.', 'João 3:17', 'João', 3, 17, NULL),
  ('mundo', 'Pelo que também Deus o exaltou soberanamente e lhe deu um nome que é sobre todo o nome, para que ao nome de Jesus se dobre todo joelho dos que estão nos céus, e na terra, e debaixo da terra.', 'Filipenses 2:9-10', 'Filipenses', 2, 9, 10),
  ('mundo', 'Mas longe esteja de mim gloriar-me, a não ser na cruz de nosso Senhor Jesus Cristo, pela qual o mundo está crucificado para mim e eu, para o mundo.', 'Gálatas 6:14', 'Gálatas', 6, 14, NULL),
  ('mundo', 'Agora, pois, se diligentemente ouvirdes a minha voz e guardardes o meu concerto, então, sereis a minha propriedade peculiar dentre todos os povos; porque toda a terra é minha.', 'Êxodo 19:5', 'Êxodo', 19, 5, NULL),
  ('mundo', 'Louvar-te-ei entre os povos, Senhor, e a ti cantarei salmos entre as nações.', 'Salmo 108:3', 'Salmo', 108, 3, NULL),
  ('mundo', 'Saí do Pai e vim ao mundo; outra vez, deixo o mundo e vou para o Pai.', 'João 16:28', 'João', 16, 28, NULL),
  ('mundo', 'Nisto se manifestou o amor de Deus para conosco: que Deus enviou seu Filho unigênito ao mundo, para que por ele vivamos.', '1 João 4:9', '1 João', 4, 9, NULL),
  ('mundo', 'Sê exaltado, ó Deus, sobre os céus; seja a tua glória sobre toda a terra.', 'Salmo 57:5', 'Salmo', 57, 5, NULL),
  ('mundo', 'Porque em verdade vos digo que, até que o céu e a terra passem, nem um jota ou um til se omitirá da lei sem que tudo seja cumprido.', 'Mateus 5:18', 'Mateus', 5, 18, NULL),
  ('mundo', 'Portanto, vós orareis assim: Pai nosso, que estás nos céus, santificado seja o teu nome. Venha o teu Reino. Seja feita a tua vontade, tanto na terra como no céu.', 'Mateus 6:9-10', 'Mateus', 6, 9, 10),
  ('mundo', 'Cantai ao Senhor, porque fez coisas grandiosas; saiba-se isso em toda a terra.', 'Isaías 12:5', 'Isaías', 12, 5, NULL),
  ('mundo', 'E Deus os abençoou e Deus lhes disse: Frutificai, e multiplicai-vos, e enchei a terra, e sujeitai-a; e dominai sobre os peixes do mar, e sobre as aves dos céus, e sobre todo o animal que se move sobre a terra.', 'Gênesis 1:28', 'Gênesis', 1, 28, NULL),
  ('mundo', 'Eu, porém, vos digo que, de maneira nenhuma, jureis nem pelo céu, porque é o trono de Deus, nem pela terra, porque é o escabelo de seus pés, nem por Jerusalém, porque é a cidade do grande Rei.', 'Mateus 5:34-35', 'Mateus', 5, 34, 35),
  ('mundo', 'E, sem dúvida alguma, grande é o mistério da piedade: Aquele que se manifestou em carne foi justificado em espírito, visto dos anjos, pregado aos gentios, crido no mundo e recebido acima, na glória.', '1 Timóteo 3:16', '1 Timóteo', 3, 16, NULL),
  ('mundo', 'Eu sou o pão vivo que desceu do céu; se alguém comer desse pão, viverá para sempre; e o pão que eu der é a minha carne, que eu darei pela vida do mundo.', 'João 6:51', 'João', 6, 51, NULL),
  ('mundo', 'E este evangelho do Reino será pregado em todo o mundo, em testemunho a todas as gentes, e então virá o fim.', 'Mateus 24:14', 'Mateus', 24, 14, NULL),
  ('mundo', 'Na verdade, não há homem justo sobre a terra, que faça bem e nunca peque.', 'Eclesiastes 7:20', 'Eclesiastes', 7, 20, NULL),
  ('mundo', 'Mas o Dia do Senhor virá como o ladrão de noite, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se desfarão, e a terra e as obras que nela há se queimarão.', '2 Pedro 3:10', '2 Pedro', 3, 10, NULL),
  ('mundo', 'Respondeu Jesus: O meu Reino não é deste mundo; se o meu Reino fosse deste mundo, lutariam os meus servos, para que eu não fosse entregue aos judeus; mas, agora, o meu Reino não é daqui.', 'João 18:36', 'João', 18, 36, NULL),
  ('natal', 'E ela dará à luz um filho, e lhe porás o nome de Jesus, porque ele salvará o seu povo dos seus pecados.', 'Mateus 1:21', 'Mateus', 1, 21, NULL),
  ('natal', 'Pois, na cidade de Davi, vos nasceu hoje o Salvador, que é Cristo, o Senhor.', 'Lucas 2:11', 'Lucas', 2, 11, NULL),
  ('natal', 'Glória a Deus nas alturas, paz na terra, boa vontade para com os homens!', 'Lucas 2:14', 'Lucas', 2, 14, NULL),
  ('natal', 'Porque um menino nos nasceu, um filho se nos deu; e o principado está sobre os seus ombros; e o seu nome será Maravilhoso Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz.', 'Isaías 9:6', 'Isaías', 9, 6, NULL),
  ('natal', 'E o anjo lhes disse: Não temais, porque eis aqui vos trago novas de grande alegria, que será para todo o povo.', 'Lucas 2:10', 'Lucas', 2, 10, NULL),
  ('natal', 'Tudo isso aconteceu para que se cumprisse o que foi dito da parte do Senhor pelo profeta, que diz: Eis que a virgem conceberá e dará à luz um filho, e ele será chamado pelo nome de Emanuel. (Emanuel traduzido é: Deus conosco).', 'Mateus 1:22-23', 'Mateus', 1, 22, 23),
  ('natal', 'E aconteceu que, estando eles ali, se cumpriram os dias em que ela havia de dar à luz. E deu à luz o seu filho primogênito, e envolveu-o em panos, e deitou-o numa manjedoura, porque não havia lugar para eles na estalagem.', 'Lucas 2:6-7', 'Lucas', 2, 6, 7),
  ('natal', 'Portanto, o mesmo Senhor vos dará um sinal: eis que uma virgem conceberá, e dará à luz um filho, e será o seu nome Emanuel.', 'Isaías 7:14', 'Isaías', 7, 14, NULL),
  ('natal', 'E voltaram os pastores glorificando e louvando a Deus por tudo o que tinham ouvido e visto, como lhes havia sido dito.', 'Lucas 2:20', 'Lucas', 2, 20, NULL),
  ('natal', 'E, respondendo o anjo, disse-lhe: Descerá sobre ti o Espírito Santo, e a virtude do Altíssimo te cobrirá com a sua sombra; pelo que também o Santo, que de ti há de nascer, será chamado Filho de Deus.', 'Lucas 1:35', 'Lucas', 1, 35, NULL),
  ('natal', 'E subiu da Galileia também José, da cidade de Nazaré, à Judeia, à cidade de Davi chamada Belém (porque era da casa e família de Davi), a fim de alistar-se com Maria, sua mulher, que estava grávida.', 'Lucas 2:4-5', 'Lucas', 2, 4, 5),
  ('natal', 'Disse-lhe, então, o anjo: Maria, não temas, porque achaste graça diante de Deus, E eis que em teu ventre conceberás, e darás à luz um filho, e pôr-lhe-ás o nome de Jesus.', 'Lucas 1:30-31', 'Lucas', 1, 30, 31),
  ('natal', 'E, tendo nascido Jesus em Belém da Judeia, no tempo do rei Herodes, eis que uns magos vieram do Oriente a Jerusalém, e perguntaram: Onde está aquele que é nascido rei dos judeus? Porque vimos a sua estrela no Oriente e viemos a adorá-lo.', 'Mateus 2:1-2', 'Mateus', 2, 1, 2),
  ('natal', 'E, projetando ele isso, eis que, em sonho, lhe apareceu um anjo do Senhor, dizendo: José, filho de Davi, não temas receber a Maria, tua mulher, porque o que nela está gerado é do Espírito Santo.', 'Mateus 1:20', 'Mateus', 1, 20, NULL),
  ('natal', 'E tu, Belém Efrata, posto que pequena entre milhares de Judá, de ti me sairá o que será Senhor em Israel, e cujas origens são desde os tempos antigos, desde os dias da eternidade.', 'Miqueias 5:2', 'Miqueias', 5, 2, NULL),
  ('natal', 'Ora, o nascimento de Jesus Cristo foi assim: Estando Maria, sua mãe, desposada com José, antes de se ajuntarem, achou-se ter concebido do Espírito Santo.', 'Mateus 1:18', 'Mateus', 1, 18, NULL),
  ('obediencia', 'Jesus respondeu e disse-lhe: Se alguém me ama, guardará a minha palavra, e meu Pai o amará, e viremos para ele e faremos nele morada.', 'João 14:23', 'João', 14, 23, NULL),
  ('obediencia', 'E será que, se ouvires a voz do Senhor, teu Deus, tendo cuidado de guardar todos os seus mandamentos que eu te ordeno hoje, o Senhor, teu Deus, te exaltará sobre todas as nações da terra.', 'Deuteronômio 28:1', 'Deuteronômio', 28, 1, NULL),
  ('obediencia', 'Filho meu, guarda o mandamento de teu pai e não deixes a lei de tua mãe.', 'Provérbios 6:20', 'Provérbios', 6, 20, NULL),
  ('obediencia', 'Andareis em todo o caminho que vos manda o Senhor, vosso Deus, para que vivais, e bem vos suceda, e prolongueis os dias na terra que haveis de possuir.', 'Deuteronômio 5:33', 'Deuteronômio', 5, 33, NULL),
  ('obediencia', 'E sede cumpridores da palavra e não somente ouvintes, enganando-vos com falsos discursos.', 'Tiago 1:22', 'Tiago', 1, 22, NULL),
  ('obediencia', 'O caminho para a vida é daquele que guarda a correção, mas o que abandona a repreensão erra.', 'Provérbios 10:17', 'Provérbios', 10, 17, NULL),
  ('obediencia', 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.', '1 Coríntios 15:58', '1 Coríntios', 15, 58, NULL),
  ('obediencia', 'Não me escolhestes vós a mim, mas eu vos escolhi a vós, e vos nomeei, para que vades e deis fruto, e o vosso fruto permaneça, a fim de que tudo quanto em meu nome pedirdes ao Pai ele vos conceda.', 'João 15:16', 'João', 15, 16, NULL),
  ('obediencia', 'E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.', 'Romanos 12:2', 'Romanos', 12, 2, NULL),
  ('obediencia', 'E guarda a observância do Senhor, teu Deus, para andares nos seus caminhos e para guardares os seus estatutos, e os seus mandamentos, e os seus juízos, e os seus testemunhos, como está escrito na Lei de Moisés, para que prosperes em tudo quanto fizeres, para onde quer que te voltares.', '1 Reis 2:3', '1 Reis', 2, 3, NULL),
  ('obediencia', 'Porque, como, pela desobediência de um só homem, muitos foram feitos pecadores, assim, pela obediência de um, muitos serão feitos justos.', 'Romanos 5:19', 'Romanos', 5, 19, NULL),
  ('obediencia', 'Amados, se o nosso coração nos não condena, temos confiança para com Deus; e qualquer coisa que lhe pedirmos, dele a receberemos, porque guardamos os seus mandamentos e fazemos o que é agradável à sua vista.', '1 João 3:21-22', '1 João', 3, 21, 22),
  ('obediencia', 'Mas a vós, que ouvis, digo: Amai a vossos inimigos, fazei bem aos que vos aborrecem, bendizei os que vos maldizem e orai pelos que vos caluniam.', 'Lucas 6:27-28', 'Lucas', 6, 27, 28),
  ('obediencia', 'Sujeitai-vos, pois, a Deus; resisti ao diabo, e ele fugirá de vós.', 'Tiago 4:7', 'Tiago', 4, 7, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('obediencia', 'Não se aparte da tua boca o livro desta Lei; antes, medita nele dia e noite, para que tenhas cuidado de fazer conforme tudo quanto nele está escrito; porque, então, farás prosperar o teu caminho e, então, prudentemente te conduzirás.', 'Josué 1:8', 'Josué', 1, 8, NULL),
  ('obediencia', 'Bem-aventurado aquele que teme ao Senhor e anda nos seus caminhos!', 'Salmo 128:1', 'Salmo', 128, 1, NULL),
  ('obediencia', 'Se o não ouvirdes e se não propuserdes no vosso coração dar honra ao meu nome, diz o Senhor dos Exércitos, enviarei a maldição contra vós e amaldiçoarei as vossas bênçãos; e já as tenho amaldiçoado, porque vós não pondes isso no coração.', 'Malaquias 2:2', 'Malaquias', 2, 2, NULL),
  ('obediencia', 'Toda alma esteja sujeita às autoridades superiores; porque não há autoridade que não venha de Deus; e as autoridades que há foram ordenadas por Deus.', 'Romanos 13:1', 'Romanos', 13, 1, NULL),
  ('obediencia', 'Não sejais vagarosos no cuidado; sede fervorosos no espírito, servindo ao Senhor.', 'Romanos 12:11', 'Romanos', 12, 11, NULL),
  ('obediencia', 'Ensina-me a fazer a tua vontade, pois és o meu Deus; guie-me o teu bom Espírito por terra plana.', 'Salmo 143:10', 'Salmo', 143, 10, NULL),
  ('obediencia', 'E, respondendo ele, disse: Amarás ao Senhor, teu Deus, de todo o teu coração, e de toda a tua alma, e de todas as tuas forças, e de todo o teu entendimento e ao teu próximo como a ti mesmo.', 'Lucas 10:27', 'Lucas', 10, 27, NULL),
  ('obediencia', 'Porque todos os que são guiados pelo Espírito de Deus, esses são filhos de Deus.', 'Romanos 8:14', 'Romanos', 8, 14, NULL),
  ('obediencia', 'E dizia a todos: Se alguém quer vir após mim, negue-se a si mesmo, e tome cada dia a sua cruz, e siga-me.', 'Lucas 9:23', 'Lucas', 9, 23, NULL),
  ('obediencia', 'E nós somos testemunhas acerca destas palavras, nós e também o Espírito Santo, que Deus deu àqueles que lhe obedecem.', 'Atos 5:32', 'Atos', 5, 32, NULL),
  ('obediencia', 'Rogo-vos, pois, irmãos, pela compaixão de Deus, que apresenteis o vosso corpo em sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional.', 'Romanos 12:1', 'Romanos', 12, 1, NULL),
  ('obediencia', 'E toda língua confesse que Jesus Cristo é o Senhor, para glória de Deus Pai.', 'Filipenses 2:11', 'Filipenses', 2, 11, NULL),
  ('obediencia', 'A fim de que, pela vontade de Deus, chegue a vós com alegria e possa recrear-me convosco.', 'Romanos 15:32', 'Romanos', 15, 32, NULL),
  ('obediencia', 'Porque a carne cobiça contra o Espírito, e o Espírito, contra a carne; e estes opõem-se um ao outro; para que não façais o que quereis.', 'Gálatas 5:17', 'Gálatas', 5, 17, NULL),
  ('obediencia', 'E o mundo passa, e a sua concupiscência; mas aquele que faz a vontade de Deus permanece para sempre.', '1 João 2:17', '1 João', 2, 17, NULL),
  ('obediencia', 'Porque persuado eu agora a homens ou a Deus? Ou procuro agradar a homens? Se estivesse ainda agradando aos homens, não seria servo de Cristo.', 'Gálatas 1:10', 'Gálatas', 1, 10, NULL),
  ('obediencia', 'Filho meu, atenta para as minhas palavras; às minhas razões inclina o teu ouvido. Não as deixes apartar-se dos teus olhos; guarda-as no meio do teu coração.', 'Provérbios 4:20-21', 'Provérbios', 4, 20, 21),
  ('obediencia', 'Apressei-me e não me detive a observar os teus mandamentos.', 'Salmo 119:60', 'Salmo', 119, 60, NULL),
  ('obediencia', 'Os passos de um homem bom são confirmados pelo Senhor, e ele deleita-se no seu caminho.', 'Salmo 37:23', 'Salmo', 37, 23, NULL),
  ('obediencia', 'Pelo que guardareis os meus mandamentos e os fareis. Eu sou o Senhor.', 'Levítico 22:31', 'Levítico', 22, 31, NULL),
  ('obediencia', 'Aquele que crê no Filho tem a vida eterna, mas aquele que não crê no Filho não verá a vida, mas a ira de Deus sobre ele permanece.', 'João 3:36', 'João', 3, 36, NULL),
  ('obediencia', 'Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e com ele cearei, e ele, comigo.', 'Apocalipse 3:20', 'Apocalipse', 3, 20, NULL),
  ('obediencia', 'Aquele, porém, que atenta bem para a lei perfeita da liberdade e nisso persevera, não sendo ouvinte esquecido, mas fazedor da obra, este tal será bem-aventurado no seu feito.', 'Tiago 1:25', 'Tiago', 1, 25, NULL),
  ('obediencia', 'Que, sendo em forma de Deus, não teve por usurpação ser igual a Deus. Mas aniquilou-se a si mesmo, tomando a forma de servo, fazendo-se semelhante aos homens; e, achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte e morte de cruz.', 'Filipenses 2:6-8', 'Filipenses', 2, 6, 8),
  ('obediencia', 'Eu sou o Senhor, vosso Deus; andai nos meus estatutos, e guardai os meus juízos, e executai-os. E santificai os meus sábados, e servirão de sinal entre mim e vós, para que saibais que eu sou o Senhor, vosso Deus.', 'Ezequiel 20:19-20', 'Ezequiel', 20, 19, 20),
  ('obediencia', 'Agora, pois, se diligentemente ouvirdes a minha voz e guardardes o meu concerto, então, sereis a minha propriedade peculiar dentre todos os povos; porque toda a terra é minha.', 'Êxodo 19:5', 'Êxodo', 19, 5, NULL),
  ('obediencia', 'Tornai para mim, diz o Senhor dos Exércitos, e eu tornarei para vós, diz o Senhor dos Exércitos.', 'Zacarias 1:3b', 'Zacarias 1:3b', NULL, NULL, NULL),
  ('obediencia', 'E, abrindo Pedro a boca, disse: Reconheço, por verdade, que Deus não faz acepção de pessoas; mas que lhe é agradável aquele que, em qualquer nação, o teme e faz o que é justo.', 'Atos 10:34-35', 'Atos', 10, 34, 35),
  ('obediencia', 'E guarda os mandamentos do Senhor, teu Deus, para o temeres e andares nos seus caminhos.', 'Deuteronômio 8:6', 'Deuteronômio', 8, 6, NULL),
  ('obediencia', 'Ouve, filho meu, e aceita as minhas palavras, e se te multiplicarão os anos de vida.', 'Provérbios 4:10', 'Provérbios', 4, 10, NULL),
  ('obediencia', 'Portanto, irmãos, procurai fazer cada vez mais firme a vossa vocação e eleição; porque, fazendo isto, nunca jamais tropeçareis. Porque assim vos será amplamente concedida a entrada no Reino eterno de nosso Senhor e Salvador Jesus Cristo.', '2 Pedro 1:10-11', '2 Pedro', 1, 10, 11),
  ('obediencia', 'Procuremos, pois, entrar naquele repouso, para que ninguém caia no mesmo exemplo de desobediência.', 'Hebreus 4:11', 'Hebreus', 4, 11, NULL),
  ('obediencia', 'E, sendo ele consumado, veio a ser a causa de eterna salvação para todos os que lhe obedecem.', 'Hebreus 5:9', 'Hebreus', 5, 9, NULL),
  ('obediencia', 'Se andardes nos meus estatutos, e guardardes os meus mandamentos, e os fizerdes, então, eu vos darei as vossas chuvas a seu tempo; e a terra dará a sua novidade, e a árvore do campo dará o seu fruto.', 'Levítico 26:3-4', 'Levítico', 26, 3, 4),
  ('obediencia', 'Porque para isto sois chamados, pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas.', '1 Pedro 2:21', '1 Pedro', 2, 21, NULL),
  ('obediencia', 'Diligentemente guardareis os mandamentos do Senhor, vosso Deus, como também os seus testemunhos e seus estatutos, que te tem mandado.', 'Deuteronômio 6:17', 'Deuteronômio', 6, 17, NULL),
  ('obediencia', 'Mas o que a não soube e fez coisas dignas de açoites com poucos açoites será castigado. E a qualquer que muito for dado, muito se lhe pedirá, e ao que muito se lhe confiou, muito mais se lhe pedirá.', 'Lucas 12:48', 'Lucas', 12, 48, NULL),
  ('obediencia', 'Adquire a sabedoria, adquire a inteligência e não te esqueças nem te apartes das palavras da minha boca.', 'Provérbios 4:5', 'Provérbios', 4, 5, NULL),
  ('obediencia', 'Mas, se o ímpio se converter de todos os seus pecados que cometeu, e guardar todos os meus estatutos, e fizer juízo e justiça, certamente viverá; não morrerá.', 'Ezequiel 18:21', 'Ezequiel', 18, 21, NULL),
  ('obediencia', 'Nem todo o que me diz: Senhor, Senhor! entrará no Reino dos céus, mas aquele que faz a vontade de meu Pai, que está nos céus.', 'Mateus 7:21', 'Mateus', 7, 21, NULL),
  ('obediencia', 'Para que guarde as veredas do juízo e conserve o caminho dos seus santos.', 'Provérbios 2:8', 'Provérbios', 2, 8, NULL),
  ('obediencia', 'Se ouvires atento a voz do Senhor, teu Deus, e fizeres o que é reto diante de seus olhos, e inclinares os teus ouvidos aos seus mandamentos, e guardares todos os seus estatutos, nenhuma das enfermidades porei sobre ti, que pus sobre o Egito; porque eu sou o Senhor, que te sara.', 'Êxodo 15:26', 'Êxodo', 15, 26, NULL),
  ('obediencia', 'Do preceito de seus lábios nunca me apartei e as palavras da sua boca prezei mais do que o meu alimento.', 'Jó 23:12', 'Jó', 23, 12, NULL),
  ('obediencia', 'Portanto, dize-lhes: Assim diz o Senhor Jeová: Não será mais retardada nenhuma das minhas palavras, e a palavra que falei se cumprirá, diz o Senhor Jeová.', 'Ezequiel 12:28', 'Ezequiel', 12, 28, NULL),
  ('obediencia', 'E disse-lhes: Ide por todo o mundo, pregai o evangelho a toda criatura.', 'Marcos 16:15', 'Marcos', 16, 15, NULL),
  ('obediencia', 'Porque o exercício corporal para pouco aproveita, mas a piedade para tudo é proveitosa, tendo a promessa da vida presente e da que há de vir.', '1 Timóteo 4:8', '1 Timóteo', 4, 8, NULL),
  ('obediencia', 'Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos; o que votares, paga-o.', 'Eclesiastes 5:4', 'Eclesiastes', 5, 4, NULL),
  ('obediencia', 'Um faz diferença entre dia e dia, mas outro julga iguais todos os dias. Cada um esteja inteiramente seguro em seu próprio ânimo.', 'Romanos 14:5', 'Romanos', 14, 5, NULL),
  ('obediencia', 'E guardarás os seus estatutos e os seus mandamentos, que te ordeno hoje, para que bem te vá a ti e a teus filhos depois de ti e para que prolongues os dias na terra que o Senhor, teu Deus, te dá para todo o sempre.', 'Deuteronômio 4:40', 'Deuteronômio', 4, 40, NULL),
  ('obediencia', 'Nada acrescentareis à palavra que vos mando, nem diminuireis dela, para que guardeis os mandamentos do Senhor, vosso Deus, que eu vos mando.', 'Deuteronômio 4:2', 'Deuteronômio', 4, 2, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('obediencia', 'E multiplicarei a tua semente como as estrelas dos céus e darei à tua semente todas estas terras. E em tua semente serão benditas todas as nações da terra, porquanto Abraão obedeceu à minha voz e guardou o meu mandado, os meus preceitos, os meus estatutos e as minhas leis.', 'Gênesis 26:4-5', 'Gênesis', 26, 4, 5),
  ('obediencia', 'E será para nós justiça, quando tivermos cuidado de fazer todos estes mandamentos perante o Senhor, nosso Deus, como nos tem ordenado.', 'Deuteronômio 6:25', 'Deuteronômio', 6, 25, NULL),
  ('obediencia', 'Vós sois o sal da terra; e, se o sal for insípido, com que se há de salgar? Para nada mais presta, senão para se lançar fora e ser pisado pelos homens.', 'Mateus 5:13', 'Mateus', 5, 13, NULL),
  ('obediencia', 'Quem dera que eles tivessem tal coração que me temessem e guardassem todos os meus mandamentos todos os dias, para que bem lhes fosse a eles e a seus filhos, para sempre!', 'Deuteronômio 5:29', 'Deuteronômio', 5, 29, NULL),
  ('obediencia', 'Aba, Pai, todas as coisas te são possíveis; afasta de mim este cálice; não seja, porém, o que eu quero, mas o que tu queres.', 'Marcos 14:36', 'Marcos', 14, 36, NULL),
  ('obediencia', 'Qualquer, pois, que violar um destes menores mandamentos e assim ensinar aos homens será chamado o menor no Reino dos céus; aquele, porém, que os cumprir e ensinar será chamado grande no Reino dos céus.', 'Mateus 5:19', 'Mateus', 5, 19, NULL),
  ('obediencia', 'Deus faz que o solitário viva em família; liberta aqueles que estão presos em grilhões; mas os rebeldes habitam em terra seca.', 'Salmo 68:6', 'Salmo', 68, 6, NULL),
  ('obediencia', 'Mas eu te oferecerei sacrifício com a voz do agradecimento; o que votei pagarei; do Senhor vem a salvação.', 'Jonas 2:9', 'Jonas', 2, 9, NULL),
  ('obediencia', 'E nas franjas vos estará, para que o vejais, e vos lembreis de todos os mandamentos do Senhor, e os façais; e não seguireis após o vosso coração, nem após os vossos olhos, após os quais andais adulterando.', 'Números 15:39', 'Números', 15, 39, NULL),
  ('obediencia', 'Então, disse o Senhor a Moisés: Sobe a mim, ao monte, e fica lá; e dar-te-ei tábuas de pedra, e a lei, e os mandamentos que tenho escrito, para os ensinares.', 'Êxodo 24:12', 'Êxodo', 24, 12, NULL),
  ('obediencia', 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações.', 'Atos 2:42', 'Atos', 2, 42, NULL),
  ('obediencia', 'Porque necessitais de paciência, para que, depois de haverdes feito a vontade de Deus, possais alcançar a promessa.', 'Hebreus 10:36', 'Hebreus', 10, 36, NULL),
  ('obediencia', 'Porque os que são segundo a carne inclinam-se para as coisas da carne; mas os que são segundo o Espírito, para as coisas do Espírito.', 'Romanos 8:5', 'Romanos', 8, 5, NULL),
  ('obediencia', 'Deleito-me em fazer a tua vontade, ó Deus meu; sim, a tua lei está dentro do meu coração.', 'Salmo 40:8', 'Salmo', 40, 8, NULL),
  ('obediencia', 'Mas isto lhes ordenei, dizendo: Dai ouvidos à minha voz, e eu serei o vosso Deus, e vós sereis o meu povo; e andai em todo o caminho que eu vos mandar, para que vos vá bem.', 'Jeremias 7:23', 'Jeremias', 7, 23, NULL),
  ('obediencia', 'O que desvia os seus ouvidos de ouvir a lei, até a sua oração será abominável.', 'Provérbios 28:9', 'Provérbios', 28, 9, NULL),
  ('obediencia', 'Mas quem pratica a verdade vem para a luz, a fim de que as suas obras sejam manifestas, porque são feitas em Deus.', 'João 3:21', 'João', 3, 21, NULL),
  ('obediencia', 'Eu sou a videira verdadeira, e meu Pai é o lavrador. Toda vara em mim que não dá fruto, a tira; e limpa toda aquela que dá fruto, para que dê mais fruto.', 'João 15:1-2', 'João', 15, 1, 2),
  ('obediencia', 'E o Senhor nos ordenou que fizéssemos todos estes estatutos, para temermos ao Senhor, nosso Deus, para o nosso perpétuo bem, para nos guardar em vida, como no dia de hoje.', 'Deuteronômio 6:24', 'Deuteronômio', 6, 24, NULL),
  ('obediencia', 'A saber: a vida eterna aos que, com perseverança em fazer bem, procuram glória, e honra, e incorrupção.', 'Romanos 2:7', 'Romanos', 2, 7, NULL),
  ('obediencia', 'E disse o povo a Josué: Serviremos ao Senhor, nosso Deus, e obedeceremos à sua voz.', 'Josué 24:24', 'Josué', 24, 24, NULL),
  ('oracao', 'Regozijai-vos sempre. Orai sem cessar. Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.', '1 Tessalonicenses 5:16-18', '1 Tessalonicenses', 5, 16, 18),
  ('oracao', 'Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.', 'Filipenses 4:6-7', 'Filipenses', 4, 6, 7),
  ('oracao', 'E esta é a confiança que temos nele: que, se pedirmos alguma coisa, segundo a sua vontade, ele nos ouve.', '1 João 5:14', '1 João', 5, 14, NULL),
  ('oracao', 'Perseverai em oração, velando nela com ação de graças.', 'Colossenses 4:2', 'Colossenses', 4, 2, NULL),
  ('oracao', 'Então, me invocareis, e ireis, e orareis a mim, e eu vos ouvirei.', 'Jeremias 29:12', 'Jeremias', 29, 12, NULL),
  ('oracao', 'Por isso, vos digo que tudo o que pedirdes, orando, crede que o recebereis e tê-lo-eis.', 'Marcos 11:24', 'Marcos', 11, 24, NULL),
  ('oracao', 'Perto da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros presos os escutavam.', 'Atos 16:25', 'Atos', 16, 25, NULL),
  ('oracao', 'Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração.', 'Romanos 12:12', 'Romanos', 12, 12, NULL),
  ('oracao', 'Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade.', 'Salmo 145:18', 'Salmo', 145, 18, NULL),
  ('oracao', 'Clama a mim, e responder-te-ei e anunciar-te-ei coisas grandes e firmes, que não sabes.', 'Jeremias 33:3', 'Jeremias', 33, 3, NULL),
  ('oracao', 'E, orando, não useis de vãs repetições, como os gentios, que pensam que, por muito falarem, serão ouvidos.', 'Mateus 6:7', 'Mateus', 6, 7, NULL),
  ('oracao', 'Cheguemos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno.', 'Hebreus 4:16', 'Hebreus', 4, 16, NULL),
  ('oracao', 'Porque onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles.', 'Mateus 18:20', 'Mateus', 18, 20, NULL),
  ('oracao', 'Na angústia, invoquei ao Senhor e clamei ao meu Deus; desde o seu templo ouviu a minha voz e aos seus ouvidos chegou o meu clamor perante a sua face.', 'Salmo 18:6', 'Salmo', 18, 6, NULL),
  ('oracao', 'Mas tu, quando orares, entra no teu aposento e, fechando a tua porta, ora a teu Pai, que vê o que está oculto; e teu Pai, que vê o que está oculto, te recompensará.', 'Mateus 6:6', 'Mateus', 6, 6, NULL),
  ('oracao', 'E, se sabemos que nos ouve em tudo o que pedimos, sabemos que alcançamos as petições que lhe fizemos.', '1 João 5:15', '1 João', 5, 15, NULL),
  ('oracao', 'Confessai as vossas culpas uns aos outros e orai uns pelos outros, para que sareis; a oração feita por um justo pode muito em seus efeitos.', 'Tiago 5:16', 'Tiago', 5, 16, NULL),
  ('oracao', 'Peça-a, porém, com fé, não duvidando; porque o que duvida é semelhante à onda do mar, que é levada pelo vento e lançada de uma para outra parte.', 'Tiago 1:6', 'Tiago', 1, 6, NULL),
  ('oracao', 'E já está próximo o fim de todas as coisas; portanto, sede sóbrios e vigiai em oração.', '1 Pedro 4:7', '1 Pedro', 4, 7, NULL),
  ('oracao', 'Não me escolhestes vós a mim, mas eu vos escolhi a vós, e vos nomeei, para que vades e deis fruto, e o vosso fruto permaneça, a fim de que tudo quanto em meu nome pedirdes ao Pai ele vos conceda.', 'João 15:16', 'João', 15, 16, NULL),
  ('oracao', 'E tudo o que pedirdes na oração, crendo, o recebereis.', 'Mateus 21:22', 'Mateus', 21, 22, NULL),
  ('oracao', 'A ele clamei com a minha boca, e ele foi exaltado pela minha língua.', 'Salmo 66:17', 'Salmo', 66, 17, NULL),
  ('oracao', 'Todos estes perseveravam unanimemente em oração e súplicas, com as mulheres, e Maria, mãe de Jesus, e com seus irmãos.', 'Atos 1:14', 'Atos', 1, 14, NULL),
  ('oracao', 'E tudo quanto pedirdes em meu nome, eu o farei, para que o Pai seja glorificado no Filho.', 'João 14:13', 'João', 14, 13, NULL),
  ('oracao', 'Mas a vós, que ouvis, digo: Amai a vossos inimigos, fazei bem aos que vos aborrecem, bendizei os que vos maldizem e orai pelos que vos caluniam.', 'Lucas 6:27-28', 'Lucas', 6, 27, 28),
  ('oracao', 'Cobiçais e nada tendes; sois invejosos e cobiçosos e não podeis alcançar; combateis e guerreais e nada tendes, porque não pedis.', 'Tiago 4:2', 'Tiago', 4, 2, NULL),
  ('oracao', 'E da mesma maneira também o Espírito ajuda as nossas fraquezas; porque não sabemos o que havemos de pedir como convém, mas o mesmo Espírito intercede por nós com gemidos inexprimíveis.', 'Romanos 8:26', 'Romanos', 8, 26, NULL),
  ('oracao', 'Pela manhã, ouvirás a minha voz, ó Senhor; pela manhã, me apresentarei a ti, e vigiarei.', 'Salmo 5:3', 'Salmo', 5, 3, NULL),
  ('oracao', 'Contudo, o Senhor mandará de dia a sua misericórdia, e de noite a sua canção estará comigo: a oração ao Deus da minha vida.', 'Salmo 42:8', 'Salmo', 42, 8, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('oracao', 'Ó Senhor, ouve a minha oração! Inclina os ouvidos às minhas súplicas; escuta-me segundo a tua verdade e segundo a tua justiça.', 'Salmo 143:1', 'Salmo', 143, 1, NULL),
  ('oracao', 'Vigiai e orai, para que não entreis em tentação; na verdade, o espírito está pronto, mas a carne é fraca.', 'Mateus 26:41', 'Mateus', 26, 41, NULL),
  ('oracao', 'Amado, desejo que te vá bem em todas as coisas e que tenhas saúde, assim como bem vai a tua alma.', '3 João 1:2', '3 João', 1, 2, NULL),
  ('oracao', 'Porque os olhos do Senhor estão sobre os justos, e os seus ouvidos, atentos às suas orações; mas o rosto do Senhor é contra os que fazem males.', '1 Pedro 3:12', '1 Pedro', 3, 12, NULL),
  ('oracao', 'Invoquei o Senhor na angústia; o Senhor me ouviu e me pôs em um lugar largo.', 'Salmo 118:5', 'Salmo', 118, 5, NULL),
  ('oracao', 'Porque sei que disto me resultará salvação, pela vossa oração e pelo socorro do Espírito de Jesus Cristo.', 'Filipenses 1:19', 'Filipenses', 1, 19, NULL),
  ('oracao', 'Portanto, vós orareis assim: Pai nosso, que estás nos céus, santificado seja o teu nome. Venha o teu Reino. Seja feita a tua vontade, tanto na terra como no céu.', 'Mateus 6:9-10', 'Mateus', 6, 9, 10),
  ('oracao', 'Nós, pois, jejuamos e pedimos isso ao nosso Deus, e moveu-se pelas nossas orações.', 'Esdras 8:23', 'Esdras', 8, 23, NULL),
  ('oracao', 'Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, Senhor, rocha minha e libertador meu!', 'Salmo 19:14', 'Salmo', 19, 14, NULL),
  ('oracao', 'Clamou este pobre, e o Senhor o ouviu; e o salvou de todas as suas angústias.', 'Salmo 34:6', 'Salmo', 34, 6, NULL),
  ('oracao', 'E, quando estiverdes orando, perdoai, se tendes alguma coisa contra alguém, para que vosso Pai, que está nos céus, vos perdoe as vossas ofensas.', 'Marcos 11:25', 'Marcos', 11, 25, NULL),
  ('oracao', 'Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor; e a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados.', 'Tiago 5:14-15', 'Tiago', 5, 14, 15),
  ('oracao', 'E acontecerá que todo aquele que invocar o nome do Senhor será salvo.', 'Atos 2:21', 'Atos', 2, 21, NULL),
  ('oracao', 'Pedro, pois, era guardado na prisão; mas a igreja fazia contínua oração por ele a Deus.', 'Atos 12:5', 'Atos', 12, 5, NULL),
  ('oracao', 'E, tendo eles orado, moveu-se o lugar em que estavam reunidos; e todos foram cheios do Espírito Santo e anunciavam com ousadia a palavra de Deus.', 'Atos 4:31', 'Atos', 4, 31, NULL),
  ('oracao', 'E o Senhor virou o cativeiro de Jó, quando orava pelos seus amigos; e o Senhor acrescentou a Jó outro tanto em dobro a tudo quanto dantes possuía.', 'Jó 42:10', 'Jó', 42, 10, NULL),
  ('oracao', 'Orando em todo tempo com toda oração e súplica no Espírito e vigiando nisso com toda perseverança e súplica por todos os santos.', 'Efésios 6:18', 'Efésios', 6, 18, NULL),
  ('oracao', 'Volta e dize a Ezequias, chefe do meu povo: Assim diz o Senhor, Deus de Davi, teu pai: Ouvi a tua oração e vi as tuas lágrimas; eis que eu te sararei; ao terceiro dia subirás à Casa do Senhor.', '2 Reis 20:5', '2 Reis', 20, 5, NULL),
  ('oracao', 'Pois, se vós, sendo maus, sabeis dar boas dádivas aos vossos filhos, quanto mais dará o Pai celestial o Espírito Santo àqueles que lho pedirem?', 'Lucas 11:13', 'Lucas', 11, 13, NULL),
  ('oracao', 'Ó Deus de meus pais, eu te louvo e celebro porque me deste sabedoria e força; e, agora, me fizeste saber o que te pedimos, porque nos fizeste saber este assunto do rei.', 'Daniel 2:23', 'Daniel', 2, 23, NULL),
  ('oracao', 'Eu, porém, vos digo: Amai a vossos inimigos, bendizei os que vos maldizem, fazei bem aos que vos odeiam e orai pelos que vos maltratam e vos perseguem.', 'Mateus 5:44', 'Mateus', 5, 44, NULL),
  ('oracao', 'Então, jejuando, e orando, e pondo sobre eles as mãos, os despediram.', 'Atos 13:3', 'Atos', 13, 3, NULL),
  ('oracao', 'Levanta-te, Senhor! Ó Deus, levanta a tua mão; não te esqueças dos necessitados!', 'Salmo 10:12', 'Salmo', 10, 12, NULL),
  ('oracao', 'Ouve, Senhor, a minha oração, e inclina os teus ouvidos ao meu clamor; não te cales perante as minhas lágrimas, porque sou para contigo como um estranho, e peregrino como todos os meus pais.', 'Salmo 39:12', 'Salmo', 39, 12, NULL),
  ('oracao', 'Pai, aqueles que me deste quero que, onde eu estiver, também eles estejam comigo, para que vejam a minha glória que me deste; porque tu me hás amado antes da criação do mundo.', 'João 17:24', 'João', 17, 24, NULL),
  ('oracao', 'E eu lhes fiz conhecer o teu nome e lho farei conhecer mais, para que o amor com que me tens amado esteja neles, e eu neles esteja.', 'João 17:26', 'João', 17, 26, NULL),
  ('oracao', 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações.', 'Atos 2:42', 'Atos', 2, 42, NULL),
  ('oracao', 'Perdoa-nos as nossas dívidas, assim como nós perdoamos aos nossos devedores.', 'Mateus 6:12', 'Mateus', 6, 12, NULL),
  ('oracao', 'E não nos induzas à tentação, mas livra-nos do mal; porque teu é o Reino, e o poder, e a glória, para sempre. Amém!', 'Mateus 6:13', 'Mateus', 6, 13, NULL),
  ('oracao', 'O pão nosso de cada dia dá-nos hoje.', 'Mateus 6:11', 'Mateus', 6, 11, NULL),
  ('oracao', 'E, servindo eles ao Senhor e jejuando, disse o Espírito Santo: Apartai-me a Barnabé e a Saulo para a obra a que os tenho chamado.', 'Atos 13:2', 'Atos', 13, 2, NULL),
  ('oracao', 'E eu vos digo a vós: Pedi, e dar-se-vos-á; buscai, e achareis; batei, e abrir-se-vos-á.', 'Lucas 11:9', 'Lucas', 11, 9, NULL),
  ('oracao', 'O que desvia os seus ouvidos de ouvir a lei, até a sua oração será abominável.', 'Provérbios 28:9', 'Provérbios', 28, 9, NULL),
  ('oracao', 'E, tomando os cinco pães e os dois peixes e olhando para o céu, abençoou-os, e partiu-os, e deu-os aos seus discípulos para os porem diante da multidão. E comeram todos e saciaram-se; e levantaram, do que lhes sobejou, doze cestos de pedaços.', 'Lucas 9:16-17', 'Lucas', 9, 16, 17),
  ('oracao', 'Igualmente vós, maridos, coabitai com ela com entendimento, dando honra à mulher, como vaso mais fraco; como sendo vós os seus coerdeiros da graça da vida; para que não sejam impedidas as vossas orações.', '1 Pedro 3:7', '1 Pedro', 3, 7, NULL),
  ('oracao', 'E aconteceu que, como todo o povo se batizava, sendo batizado também Jesus, orando ele, o céu se abriu, e o Espírito Santo desceu sobre ele em forma corpórea, como uma pomba; e ouviu-se uma voz do céu, que dizia: Tu és meu Filho amado; em ti me tenho comprazido.', 'Lucas 3:21-22', 'Lucas', 3, 21, 22),
  ('oracao', 'E fortalecerei a casa de Judá, e salvarei a casa de José, e tornarei a plantá-los, porque me apiedei deles; e serão como se os não tivera rejeitado; porque eu sou o Senhor, seu Deus, e os ouvirei.', 'Zacarias 10:6', 'Zacarias', 10, 6, NULL),
  ('orfaos', 'A nenhuma viúva nem órfão afligireis. Se de alguma maneira os afligirdes, e eles clamarem a mim, eu certamente ouvirei o seu clamor, e a minha ira se acenderá, e vos matarei à espada; e vossas mulheres ficarão viúvas, e vossos filhos, órfãos.', 'Êxodo 22:22-24', 'Êxodo', 22, 22, 24),
  ('orfaos', 'Não vos deixarei órfãos; voltarei para vós.', 'João 14:18', 'João', 14, 18, NULL),
  ('orfaos', 'Aprendei a fazer o bem; praticai o que é reto; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas.', 'Isaías 1:17', 'Isaías', 1, 17, NULL),
  ('orfaos', 'A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e guardar-se da corrupção do mundo.', 'Tiago 1:27', 'Tiago', 1, 27, NULL),
  ('orfaos', 'Defendei o pobre e o órfão; fazei justiça ao aflito e necessitado.', 'Salmo 82:3', 'Salmo', 82, 3, NULL),
  ('orfaos', 'Cantai a Deus, cantai louvores ao seu nome; louvai aquele que vai sobre os céus, pois o seu nome é Jeová; exultai diante dele. Pai de órfãos e juiz de viúvas é Deus no seu lugar santo.', 'Salmo 68:4-5', 'Salmo', 68, 4, 5),
  ('orfaos', 'O Senhor guarda os estrangeiros; ampara o órfão e a viúva, mas transtorna o caminho dos ímpios.', 'Salmo 146:9', 'Salmo', 146, 9, NULL),
  ('orfaos', 'Assim falou o Senhor dos Exércitos, dizendo: Executai juízo verdadeiro, mostrai piedade e misericórdia cada um a seu irmão; e não oprimais a viúva, nem o órfão, nem o estrangeiro, nem o pobre, nem intente o mal cada um contra o seu irmão, no seu coração.', 'Zacarias 7:9-10', 'Zacarias', 7, 9, 10),
  ('orfaos', 'Porque eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse. A bênção do que ia perecendo vinha sobre mim, e eu fazia que rejubilasse o coração da viúva.', 'Jó 29:12-13', 'Jó', 29, 12, 13),
  ('orfaos', 'Mas, se deveras melhorardes os vossos caminhos e as vossas obras, se deveras fizerdes juízo entre um homem e entre o seu companheiro, se não oprimirdes o estrangeiro, e o órfão, e a viúva, nem derramardes sangue inocente neste lugar, nem andardes após outros deuses para vosso próprio mal, eu vos farei habitar neste lugar, na terra que dei a vossos pais, de século em século.', 'Jeremias 7:5-7', 'Jeremias', 7, 5, 7),
  ('orgulho', 'Vindo a soberba, virá também a afronta; mas com os humildes está a sabedoria.', 'Provérbios 11:2', 'Provérbios', 11, 2, NULL),
  ('orgulho', 'O temor do Senhor é aborrecer o mal; a soberba, e a arrogância, e o mau caminho, e a boca perversa aborreço.', 'Provérbios 8:13', 'Provérbios', 8, 13, NULL),
  ('orgulho', 'Sede unânimes entre vós; não ambicioneis coisas altas, mas acomodai-vos às humildes; não sejais sábios em vós mesmos.', 'Romanos 12:16', 'Romanos', 12, 16, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('orgulho', 'A soberba do homem o abaterá, mas o humilde de espírito obterá honra.', 'Provérbios 29:23', 'Provérbios', 29, 23, NULL),
  ('orgulho', 'Aquele, porém, que se gloria, glorie-se no Senhor. Porque não é aprovado quem a si mesmo se louva, mas, sim, aquele a quem o Senhor louva.', '2 Coríntios 10:17-18', '2 Coríntios', 10, 17, 18),
  ('orgulho', 'Porém o Senhor disse a Samuel: Não atentes para a sua aparência, nem para a altura da sua estatura, porque o tenho rejeitado; porque o Senhor não vê como vê o homem. Pois o homem vê o que está diante dos olhos, porém o Senhor olha para o coração.', '1 Samuel 16:7', '1 Samuel', 16, 7, NULL),
  ('orgulho', 'Antes de ser quebrantado, eleva-se o coração do homem; e, diante da honra, vai a humildade.', 'Provérbios 18:12', 'Provérbios', 18, 12, NULL),
  ('orgulho', 'E dizia: O que sai do homem, isso é que contamina o homem. Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios, os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura. Todos estes males procedem de dentro e contaminam o homem.', 'Marcos 7:20-23', 'Marcos', 7, 20, 23),
  ('orgulho', 'Porque tudo o que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a soberba da vida, não é do Pai, mas do mundo.', '1 João 2:16', '1 João', 2, 16, NULL),
  ('orgulho', 'E Deus escolheu as coisas vis deste mundo, e as desprezíveis, e as que não são para aniquilar as que são; para que nenhuma carne se glorie perante ele.', '1 Coríntios 1:28-29', '1 Coríntios', 1, 28, 29),
  ('orgulho', 'Agora, pois, eu, Nabucodonosor, louvo, e exalço, e glorifico ao Rei dos céus; porque todas as suas obras são verdades; e os seus caminhos, juízo, e pode humilhar aos que andam na soberba.', 'Daniel 4:37', 'Daniel', 4, 37, NULL),
  ('orgulho', 'Mas glorie-se o irmão abatido na sua exaltação, e o rico, em seu abatimento, porque ele passará como a flor da erva.', 'Tiago 1:9-10', 'Tiago', 1, 9, 10),
  ('orgulho', 'Manda aos ricos deste mundo que não sejam altivos, nem ponham a esperança na incerteza das riquezas, mas em Deus, que abundantemente nos dá todas as coisas para delas gozarmos.', '1 Timóteo 6:17', '1 Timóteo', 6, 17, NULL),
  ('orgulho', 'E ainda que distribuísse toda a minha fortuna para sustento dos pobres, e ainda que entregasse o meu corpo para ser queimado, e não tivesse amor, nada disso me aproveitaria.', '1 Coríntios 13:3', '1 Coríntios', 13, 3, NULL),
  ('orgulho', 'Depois, eles se fartaram em proporção do seu pasto; estando fartos, ensoberbeceu-se o seu coração; por isso, se esqueceram de mim.', 'Oseias 13:6', 'Oseias', 13, 6, NULL),
  ('ouvir', 'Sabeis isto, meus amados irmãos; mas todo o homem seja pronto para ouvir, tardio para falar, tardio para se irar.', 'Tiago 1:19', 'Tiago', 1, 19, NULL),
  ('ouvir', 'Mas ele disse: Antes, bem-aventurados os que ouvem a palavra de Deus e a guardam.', 'Lucas 11:28', 'Lucas', 11, 28, NULL),
  ('ouvir', 'Clama a mim, e responder-te-ei e anunciar-te-ei coisas grandes e firmes, que não sabes.', 'Jeremias 33:3', 'Jeremias', 33, 3, NULL),
  ('ouvir', 'E sede cumpridores da palavra e não somente ouvintes, enganando-vos com falsos discursos.', 'Tiago 1:22', 'Tiago', 1, 22, NULL),
  ('ouvir', 'E esta é a confiança que temos nele: que, se pedirmos alguma coisa, segundo a sua vontade, ele nos ouve.', '1 João 5:14', '1 João', 5, 14, NULL),
  ('ouvir', 'Então, me invocareis, e ireis, e orareis a mim, e eu vos ouvirei.', 'Jeremias 29:12', 'Jeremias', 29, 12, NULL),
  ('ouvir', 'Amo ao Senhor, porque ele ouviu a minha voz e a minha súplica. Porque inclinou para mim os seus ouvidos; portanto, invocá-lo-ei enquanto viver.', 'Salmo 116:1-2', 'Salmo', 116, 1, 2),
  ('ouvir', 'O que atenta prudentemente para a palavra achará o bem, e o que confia no Senhor será bem-aventurado.', 'Provérbios 16:20', 'Provérbios', 16, 20, NULL),
  ('ouvir', 'Todo aquele, pois, que escuta estas minhas palavras e as pratica, assemelhá-lo-ei ao homem prudente, que edificou a sua casa sobre a rocha.', 'Mateus 7:24', 'Mateus', 7, 24, NULL),
  ('ouvir', 'O que também aprendestes, e recebestes, e ouvistes, e vistes em mim, isso fazei; e o Deus de paz será convosco.', 'Filipenses 4:9', 'Filipenses', 4, 9, NULL),
  ('ouvir', 'E, se sabemos que nos ouve em tudo o que pedimos, sabemos que alcançamos as petições que lhe fizemos.', '1 João 5:15', '1 João', 5, 15, NULL),
  ('ouvir', 'Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e com ele cearei, e ele, comigo.', 'Apocalipse 3:20', 'Apocalipse', 3, 20, NULL),
  ('ouvir', 'De sorte que a fé é pelo ouvir, e o ouvir pela palavra de Deus.', 'Romanos 10:17', 'Romanos', 10, 17, NULL),
  ('ouvir', 'Na angústia, invoquei ao Senhor e clamei ao meu Deus; desde o seu templo ouviu a minha voz e aos seus ouvidos chegou o meu clamor perante a sua face.', 'Salmo 18:6', 'Salmo', 18, 6, NULL),
  ('ouvir', 'Filho meu, atenta para as minhas palavras; às minhas razões inclina o teu ouvido. Não as deixes apartar-se dos teus olhos; guarda-as no meio do teu coração.', 'Provérbios 4:20-21', 'Provérbios', 4, 20, 21),
  ('ouvir', 'O caminho para a vida é daquele que guarda a correção, mas o que abandona a repreensão erra.', 'Provérbios 10:17', 'Provérbios', 10, 17, NULL),
  ('ouvir', 'Pela manhã, ouvirás a minha voz, ó Senhor; pela manhã, me apresentarei a ti, e vigiarei.', 'Salmo 5:3', 'Salmo', 5, 3, NULL),
  ('ouvir', 'Os olhos do Senhor estão sobre os justos; e os seus ouvidos, atentos ao seu clamor.', 'Salmo 34:15', 'Salmo', 34, 15, NULL),
  ('ouvir', 'Se o não ouvirdes e se não propuserdes no vosso coração dar honra ao meu nome, diz o Senhor dos Exércitos, enviarei a maldição contra vós e amaldiçoarei as vossas bênçãos; e já as tenho amaldiçoado, porque vós não pondes isso no coração.', 'Malaquias 2:2', 'Malaquias', 2, 2, NULL),
  ('ouvir', 'Após o Senhor, vosso Deus, andareis, e a ele temereis, e os seus mandamentos guardareis, e a sua voz ouvireis, e a ele servireis, e a ele vos achegareis.', 'Deuteronômio 13:4', 'Deuteronômio', 13, 4, NULL),
  ('ouvir', 'Perto da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros presos os escutavam.', 'Atos 16:25', 'Atos', 16, 25, NULL),
  ('ouvir', 'Aquele, pois, que vos dá o Espírito e que opera maravilhas entre vós o faz pelas obras da lei ou pela pregação da fé?', 'Gálatas 3:5', 'Gálatas', 3, 5, NULL),
  ('ouvir', 'Busquei ao Senhor, e ele me respondeu; livrou-me de todos os meus temores.', 'Salmo 34:4', 'Salmo', 34, 4, NULL),
  ('ouvir', 'Ele, porém, respondendo, disse: Está escrito: Nem só de pão viverá o homem, mas de toda a palavra que sai da boca de Deus.', 'Mateus 4:4', 'Mateus', 4, 4, NULL),
  ('ouvir', 'Ora, se teu irmão pecar contra ti, vai e repreende-o entre ti e ele só; se te ouvir, ganhaste a teu irmão.', 'Mateus 18:15', 'Mateus', 18, 15, NULL),
  ('ouvir', 'Porquanto tudo o que em trevas dissestes à luz será ouvido; e o que falastes ao ouvido no gabinete sobre os telhados será apregoado.', 'Lucas 12:3', 'Lucas', 12, 3, NULL),
  ('ouvir', 'Filho meu, guarda o mandamento de teu pai e não deixes a lei de tua mãe.', 'Provérbios 6:20', 'Provérbios', 6, 20, NULL),
  ('ouvir', 'Eu, porém, esperarei no Senhor; esperei no Deus da minha salvação; o meu Deus me ouvirá.', 'Miqueias 7:7', 'Miqueias', 7, 7, NULL),
  ('ouvir', 'Aquele, porém, que atenta bem para a lei perfeita da liberdade e nisso persevera, não sendo ouvinte esquecido, mas fazedor da obra, este tal será bem-aventurado no seu feito.', 'Tiago 1:25', 'Tiago', 1, 25, NULL),
  ('ouvir', 'Se ouvires atento a voz do Senhor, teu Deus, e fizeres o que é reto diante de seus olhos, e inclinares os teus ouvidos aos seus mandamentos, e guardares todos os seus estatutos, nenhuma das enfermidades porei sobre ti, que pus sobre o Egito; porque eu sou o Senhor, que te sara.', 'Êxodo 15:26', 'Êxodo', 15, 26, NULL),
  ('ouvir', 'Fui buscado pelos que não perguntavam por mim; fui achado por aqueles que me não buscavam; a um povo que se não chamava do meu nome eu disse: Eis-me aqui.', 'Isaías 65:1', 'Isaías', 65, 1, NULL),
  ('ouvir', 'Porque os olhos do Senhor estão sobre os justos, e os seus ouvidos, atentos às suas orações; mas o rosto do Senhor é contra os que fazem males.', '1 Pedro 3:12', '1 Pedro', 3, 12, NULL),
  ('ouvir', 'Clamou este pobre, e o Senhor o ouviu; e o salvou de todas as suas angústias.', 'Salmo 34:6', 'Salmo', 34, 6, NULL),
  ('ouvir', 'Das profundezas a ti clamo, ó Senhor! Senhor, escuta a minha voz! Sejam os teus ouvidos atentos à voz das minhas súplicas.', 'Salmo 130:1-2', 'Salmo', 130, 1, 2),
  ('ouvir', 'O que ama a correção ama o conhecimento, mas o que aborrece a repreensão é um bruto.', 'Provérbios 12:1', 'Provérbios', 12, 1, NULL),
  ('ouvir', 'E não sejais como vossos pais, aos quais clamavam os primeiros profetas, dizendo: Assim diz o Senhor dos Exércitos: Convertei-vos, agora, dos vossos maus caminhos e das vossas más obras. Mas não ouviram, nem me escutaram, diz o Senhor.', 'Zacarias 1:4', 'Zacarias', 1, 4, NULL),
  ('ouvir', 'O que desvia os seus ouvidos de ouvir a lei, até a sua oração será abominável.', 'Provérbios 28:9', 'Provérbios', 28, 9, NULL),
  ('ouvir', 'Portanto, o que desde o princípio ouvistes permaneça em vós. Se em vós permanecer o que desde o princípio ouvistes, também permanecereis no Filho e no Pai.', '1 João 2:24', '1 João', 2, 24, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('ouvir', 'E multiplicarei a tua semente como as estrelas dos céus e darei à tua semente todas estas terras. E em tua semente serão benditas todas as nações da terra, porquanto Abraão obedeceu à minha voz e guardou o meu mandado, os meus preceitos, os meus estatutos e as minhas leis.', 'Gênesis 26:4-5', 'Gênesis', 26, 4, 5),
  ('ouvir', 'E, se não as escutar, dize-o à igreja; e, se também não escutar a igreja, considera-o como um gentio e publicano.', 'Mateus 18:17', 'Mateus', 18, 17, NULL),
  ('ouvir', 'E fortalecerei a casa de Judá, e salvarei a casa de José, e tornarei a plantá-los, porque me apiedei deles; e serão como se os não tivera rejeitado; porque eu sou o Senhor, seu Deus, e os ouvirei.', 'Zacarias 10:6', 'Zacarias', 10, 6, NULL),
  ('ouvir', 'E disse o povo a Josué: Serviremos ao Senhor, nosso Deus, e obedeceremos à sua voz.', 'Josué 24:24', 'Josué', 24, 24, NULL),
  ('paciencia', 'O longânimo é grande em entendimento, mas o de ânimo precipitado exalta a loucura.', 'Provérbios 14:29', 'Provérbios', 14, 29, NULL),
  ('paciencia', 'O amor é sofredor, é benigno; o amor não é invejoso; o amor não trata com leviandade, não se ensoberbece, não se porta com indecência, não busca os seus interesses, não se irrita, não suspeita mal.', '1 Coríntios 13:4-5', '1 Coríntios', 13, 4, 5),
  ('paciencia', 'Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração.', 'Romanos 12:12', 'Romanos', 12, 12, NULL),
  ('paciencia', 'Com toda a humildade e mansidão, com longanimidade, suportando-vos uns aos outros em amor.', 'Efésios 4:2', 'Efésios', 4, 2, NULL),
  ('paciencia', 'Mas, se esperamos o que não vemos, com paciência o esperamos.', 'Romanos 8:25', 'Romanos', 8, 25, NULL),
  ('paciencia', 'E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não houvermos desfalecido.', 'Gálatas 6:9', 'Gálatas', 6, 9, NULL),
  ('paciencia', 'Melhor é o longânimo do que o valente, e o que governa o seu espírito do que o que toma uma cidade.', 'Provérbios 16:32', 'Provérbios', 16, 32, NULL),
  ('paciencia', 'Descansa no Senhor e espera nele; não te indignes por causa daquele que prospera em seu caminho, por causa do homem que executa astutos intentos.', 'Salmo 37:7', 'Salmo', 37, 7, NULL),
  ('paciencia', 'Espera no Senhor, anima-te, e ele fortalecerá o teu coração; espera, pois, no Senhor.', 'Salmo 27:14', 'Salmo', 27, 14, NULL),
  ('paciencia', 'O Senhor pelejará por vós, e vos calareis.', 'Êxodo 14:14', 'Êxodo', 14, 14, NULL),
  ('paciencia', 'O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se.', '2 Pedro 3:9', '2 Pedro', 3, 9, NULL),
  ('paciencia', 'Revesti-vos, pois, como eleitos de Deus, santos e amados, de entranhas de misericórdia, de benignidade, humildade, mansidão, longanimidade.', 'Colossenses 3:12', 'Colossenses', 3, 12, NULL),
  ('paciencia', 'Ora, o Deus de paciência e consolação vos conceda o mesmo sentimento uns para com os outros, segundo Cristo Jesus.', 'Romanos 15:5', 'Romanos', 15, 5, NULL),
  ('paciencia', 'Porque a sua ira dura só um momento; no seu favor está a vida; o choro pode durar uma noite, mas a alegria vem pela manhã.', 'Salmo 30:5', 'Salmo', 30, 5, NULL),
  ('paciencia', 'Pela manhã, ouvirás a minha voz, ó Senhor; pela manhã, me apresentarei a ti, e vigiarei.', 'Salmo 5:3', 'Salmo', 5, 3, NULL),
  ('paciencia', 'Por isso, o Senhor esperará para ter misericórdia de vós; e, por isso, será exalçado para se compadecer de vós, porque o Senhor é um Deus de equidade. Bem-aventurados todos os que nele esperam.', 'Isaías 30:18', 'Isaías', 30, 18, NULL),
  ('paciencia', 'Misericordioso e piedoso é o Senhor; longânimo e grande em benignidade.', 'Salmo 103:8', 'Salmo', 103, 8, NULL),
  ('paciencia', 'Mas aquele que perseverar até ao fim será salvo.', 'Mateus 24:13', 'Mateus', 24, 13, NULL),
  ('paciencia', 'Mas, por isso, alcancei misericórdia, para que em mim, que sou o principal, Jesus Cristo mostrasse toda a sua longanimidade, para exemplo dos que haviam de crer nele para a vida eterna.', '1 Timóteo 1:16', '1 Timóteo', 1, 16, NULL),
  ('paciencia', 'Mas, amados, não ignoreis uma coisa: que um dia para o Senhor é como mil anos, e mil anos, como um dia.', '2 Pedro 3:8', '2 Pedro', 3, 8, NULL),
  ('paciencia', 'Que pregues a palavra, instes a tempo e fora de tempo, redarguas, repreendas, exortes, com toda a longanimidade e doutrina.', '2 Timóteo 4:2', '2 Timóteo', 4, 2, NULL),
  ('paciencia', 'Vigiai, pois, porque não sabeis a que hora há de vir o vosso Senhor.', 'Mateus 24:42', 'Mateus', 24, 42, NULL),
  ('paciencia', 'Eis que venho sem demora; guarda o que tens, para que ninguém tome a tua coroa.', 'Apocalipse 3:11', 'Apocalipse', 3, 11, NULL),
  ('paciencia', 'E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor, vosso Deus; porque ele é misericordioso, e compassivo, e tardio em irar-se, e grande em beneficência e se arrepende do mal.', 'Joel 2:13', 'Joel', 2, 13, NULL),
  ('paciencia', 'Porque necessitais de paciência, para que, depois de haverdes feito a vontade de Deus, possais alcançar a promessa.', 'Hebreus 10:36', 'Hebreus', 10, 36, NULL),
  ('paciencia', 'A esperança dos justos é alegria, mas a expectação dos ímpios perecerá.', 'Provérbios 10:28', 'Provérbios', 10, 28, NULL),
  ('paciencia', 'O Senhor é tardio em irar-se, mas grande em força e ao culpado não tem por inocente; o Senhor tem o seu caminho na tormenta e na tempestade, e as nuvens são o pó dos seus pés.', 'Naum 1:3', 'Naum', 1, 3, NULL),
  ('paciencia', 'Mas tu, Senhor, és um Deus cheio de compaixão, e piedoso, e sofredor, e grande em benignidade e em verdade.', 'Salmo 86:15', 'Salmo', 86, 15, NULL),
  ('pai', 'Como um pai se compadece de seus filhos, assim o Senhor se compadece daqueles que o temem.', 'Salmo 103:13', 'Salmo', 103, 13, NULL),
  ('pai', 'Vede quão grande amor nos tem concedido o Pai: que fôssemos chamados filhos de Deus. Por isso, o mundo não nos conhece, porque não conhece a ele.', '1 João 3:1', '1 João', 3, 1, NULL),
  ('pai', 'Filho meu, não rejeites a correção do Senhor, nem te enojes da sua repreensão. Porque o Senhor repreende aquele a quem ama, assim como o pai, ao filho a quem quer bem.', 'Provérbios 3:11-12', 'Provérbios', 3, 11, 12),
  ('pai', 'Mas tu, quando orares, entra no teu aposento e, fechando a tua porta, ora a teu Pai, que vê o que está oculto; e teu Pai, que vê o que está oculto, te recompensará.', 'Mateus 6:6', 'Mateus', 6, 6, NULL),
  ('pai', 'Pai, aqueles que me deste quero que, onde eu estiver, também eles estejam comigo, para que vejam a minha glória que me deste; porque tu me hás amado antes da criação do mundo.', 'João 17:24', 'João', 17, 24, NULL),
  ('pai', 'Olhai para as aves do céu, que não semeiam, nem segam, nem ajuntam em celeiros; e vosso Pai celestial as alimenta. Não tendes vós muito mais valor do que elas?', 'Mateus 6:26', 'Mateus', 6, 26, NULL),
  ('pai', 'Ora, a nosso Deus e Pai seja dada glória para todo o sempre. Amém!', 'Filipenses 4:20', 'Filipenses', 4, 20, NULL),
  ('pai', 'E dou-lhes a vida eterna, e nunca hão de perecer, e ninguém as arrebatará das minhas mãos. Meu Pai, que mas deu, é maior do que todos; e ninguém pode arrebatá-las das mãos de meu Pai. Eu e o Pai somos um.', 'João 10:28-30', 'João', 10, 28, 30),
  ('pai', 'Mas a todos quantos o receberam deu-lhes o poder de serem feitos filhos de Deus: aos que creem no seu nome.', 'João 1:12', 'João', 1, 12, NULL),
  ('pai', 'O tolo despreza a correção de seu pai, mas o que observa a repreensão prudentemente se haverá.', 'Provérbios 15:5', 'Provérbios', 15, 5, NULL),
  ('pai', 'Não ameis o mundo, nem o que no mundo há. Se alguém ama o mundo, o amor do Pai não está nele.', '1 João 2:15', '1 João', 2, 15, NULL),
  ('pai', 'Jesus respondeu e disse-lhe: Se alguém me ama, guardará a minha palavra, e meu Pai o amará, e viremos para ele e faremos nele morada.', 'João 14:23', 'João', 14, 23, NULL),
  ('pai', 'Não temas, ó pequeno rebanho, porque a vosso Pai agradou dar-vos o Reino.', 'Lucas 12:32', 'Lucas', 12, 32, NULL),
  ('pai', 'Não se vendem dois passarinhos por um ceitil? E nenhum deles cairá em terra sem a vontade de vosso Pai. E até mesmo os cabelos da vossa cabeça estão todos contados. Não temais, pois; mais valeis vós do que muitos passarinhos.', 'Mateus 10:29-31', 'Mateus', 10, 29, 31),
  ('pai', 'Toda boa dádiva e todo dom perfeito vêm do alto, descendo do Pai das luzes, em quem não há mudança, nem sombra de variação.', 'Tiago 1:17', 'Tiago', 1, 17, NULL),
  ('pai', 'Todavia, para nós há um só Deus, o Pai, de quem é tudo e para quem nós vivemos; e um só Senhor, Jesus Cristo, pelo qual são todas as coisas, e nós por ele.', '1 Coríntios 8:6', '1 Coríntios', 8, 6, NULL),
  ('pai', 'Ou pensas tu que eu não poderia, agora, orar a meu Pai e que ele não me daria mais de doze legiões de anjos?', 'Mateus 26:53', 'Mateus', 26, 53, NULL),
  ('pai', 'Disse-lhe Jesus: Eu sou o caminho, e a verdade, e a vida. Ninguém vem ao Pai senão por mim.', 'João 14:6', 'João', 14, 6, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('pai', 'Aquele que nem mesmo a seu próprio Filho poupou, antes, o entregou por todos nós, como nos não dará também com ele todas as coisas?', 'Romanos 8:32', 'Romanos', 8, 32, NULL),
  ('pai', 'Aquele que tem os meus mandamentos e os guarda, este é o que me ama; e aquele que me ama será amado de meu Pai, e eu o amarei e me manifestarei a ele.', 'João 14:21', 'João', 14, 21, NULL),
  ('pai', 'Porque a ardente expectação da criatura espera a manifestação dos filhos de Deus.', 'Romanos 8:19', 'Romanos', 8, 19, NULL),
  ('pai', 'E tudo quanto pedirdes em meu nome, eu o farei, para que o Pai seja glorificado no Filho.', 'João 14:13', 'João', 14, 13, NULL),
  ('pai', 'Porque um menino nos nasceu, um filho se nos deu; e o principado está sobre os seus ombros; e o seu nome será Maravilhoso Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz.', 'Isaías 9:6', 'Isaías', 9, 6, NULL),
  ('pai', 'Deus nunca foi visto por alguém. O Filho unigênito, que está no seio do Pai, este o fez conhecer.', 'João 1:18', 'João', 1, 18, NULL),
  ('pai', 'Disse-lhe Filipe: Senhor, mostra-nos o Pai, o que nos basta.', 'João 14:8', 'João', 14, 8, NULL),
  ('pai', 'Na casa de meu Pai há muitas moradas; se não fosse assim, eu vo-lo teria dito, pois vou preparar-vos lugar.', 'João 14:2', 'João', 14, 2, NULL),
  ('pai', 'Porém tu, quando jejuares, unge a cabeça e lava o rosto, para não pareceres aos homens que jejuas, mas sim a teu Pai, que está oculto; e teu Pai, que vê o que está oculto, te recompensará.', 'Mateus 6:17-18', 'Mateus', 6, 17, 18),
  ('pai', 'Sede, pois, misericordiosos, como também vosso Pai é misericordioso.', 'Lucas 6:36', 'Lucas', 6, 36, NULL),
  ('pai', 'Sede vós, pois, perfeitos, como é perfeito o vosso Pai, que está nos céus.', 'Mateus 5:48', 'Mateus', 5, 48, NULL),
  ('pai', 'Graça e paz de Deus, nosso Pai, e do Senhor Jesus Cristo.', 'Romanos 1:7b', 'Romanos 1:7b', NULL, NULL, NULL),
  ('pai', 'Confessa, pois, no teu coração que, como um homem castiga a seu filho, assim te castiga o Senhor, teu Deus.', 'Deuteronômio 8:5', 'Deuteronômio', 8, 5, NULL),
  ('pai', 'Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor, em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados.', 'Colossenses 1:13-14', 'Colossenses', 1, 13, 14),
  ('pai', 'Se vós me conhecêsseis a mim, também conheceríeis a meu Pai; e já desde agora o conheceis e o tendes visto.', 'João 14:7', 'João', 14, 7, NULL),
  ('pai', 'Portanto, vós orareis assim: Pai nosso, que estás nos céus, santificado seja o teu nome. Venha o teu Reino. Seja feita a tua vontade, tanto na terra como no céu.', 'Mateus 6:9-10', 'Mateus', 6, 9, 10),
  ('pai', 'E eu rogarei ao Pai, e ele vos dará outro Consolador, para que fique convosco para sempre.', 'João 14:16', 'João', 14, 16, NULL),
  ('pai', 'E, quando estiverdes orando, perdoai, se tendes alguma coisa contra alguém, para que vosso Pai, que está nos céus, vos perdoe as vossas ofensas.', 'Marcos 11:25', 'Marcos', 11, 25, NULL),
  ('pai', 'Se alguém me serve, siga-me; e, onde eu estiver, ali estará também o meu servo. E, se alguém me servir, meu Pai o honrará.', 'João 12:26', 'João', 12, 26, NULL),
  ('pai', 'Aba, Pai, todas as coisas te são possíveis; afasta de mim este cálice; não seja, porém, o que eu quero, mas o que tu queres.', 'Marcos 14:36', 'Marcos', 14, 36, NULL),
  ('pai', 'Porque tudo o que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a soberba da vida, não é do Pai, mas do mundo.', '1 João 2:16', '1 João', 2, 16, NULL),
  ('pai', 'Qualquer que nega o Filho também não tem o Pai; e aquele que confessa o Filho tem também o Pai.', '1 João 2:23', '1 João', 2, 23, NULL),
  ('pai', 'Ao que vencer, lhe concederei que se assente comigo no meu trono, assim como eu venci e me assentei com meu Pai no seu trono.', 'Apocalipse 3:21', 'Apocalipse', 3, 21, NULL),
  ('pai', 'Se, porém, não perdoardes aos homens as suas ofensas, também vosso Pai vos não perdoará as vossas ofensas.', 'Mateus 6:15', 'Mateus', 6, 15, NULL),
  ('pai', 'Nisto é glorificado meu Pai: que deis muito fruto; e assim sereis meus discípulos.', 'João 15:8', 'João', 15, 8, NULL),
  ('pai', 'Saí do Pai e vim ao mundo; outra vez, deixo o mundo e vou para o Pai.', 'João 16:28', 'João', 16, 28, NULL),
  ('pai', 'Disse-lhes, pois, Jesus outra vez: Paz seja convosco! Assim como o Pai me enviou, também eu vos envio a vós.', 'João 20:21', 'João', 20, 21, NULL),
  ('pai', 'Assim como o Pai, que vive, me enviou, e eu vivo pelo Pai, assim quem de mim se alimenta também viverá por mim.', 'João 6:57', 'João', 6, 57, NULL),
  ('pai', 'Nem todo o que me diz: Senhor, Senhor! entrará no Reino dos céus, mas aquele que faz a vontade de meu Pai, que está nos céus.', 'Mateus 7:21', 'Mateus', 7, 21, NULL),
  ('pai', 'O que vencer será vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; e confessarei o seu nome diante de meu Pai e diante dos seus anjos.', 'Apocalipse 3:5', 'Apocalipse', 3, 5, NULL),
  ('pai', 'Portanto, o que desde o princípio ouvistes permaneça em vós. Se em vós permanecer o que desde o princípio ouvistes, também permanecereis no Filho e no Pai.', '1 João 2:24', '1 João', 2, 24, NULL),
  ('pai', 'Mas aquele Consolador, o Espírito Santo, que o Pai enviará em meu nome, vos ensinará todas as coisas e vos fará lembrar de tudo quanto vos tenho dito.', 'João 14:26', 'João', 14, 26, NULL),
  ('pai', 'Disse-lhe Jesus: Não me detenhas, porque ainda não subi para meu Pai, mas vai para meus irmãos e dize-lhes que eu subo para meu Pai e vosso Pai, meu Deus e vosso Deus.', 'João 20:17', 'João', 20, 17, NULL),
  ('pai', 'De sorte que, exaltado pela destra de Deus e tendo recebido do Pai a promessa do Espírito Santo, derramou isto que vós agora vedes e ouvis.', 'Atos 2:33', 'Atos', 2, 33, NULL),
  ('pai', 'Mas, agora, ó Senhor, tu és o nosso Pai; nós, o barro, e tu, o nosso oleiro; e todos nós, obra das tuas mãos.', 'Isaías 64:8', 'Isaías', 64, 8, NULL),
  ('pai', 'Mas, quando tu deres esmola, não saiba a tua mão esquerda o que faz a tua direita, para que a tua esmola seja dada ocultamente, e teu Pai, que vê em secreto, te recompensará publicamente.', 'Mateus 6:3-4', 'Mateus', 6, 3, 4),
  ('pai', 'Mas, quando vier o Consolador, que eu da parte do Pai vos hei de enviar, aquele Espírito da verdade, que procede do Pai, testificará de mim.', 'João 15:26', 'João', 15, 26, NULL),
  ('pai', 'Na verdade, na verdade vos digo que aquele que crê em mim também fará as obras que eu faço e as fará maiores do que estas, porque eu vou para meu Pai.', 'João 14:12', 'João', 14, 12, NULL),
  ('pai', 'E, clamando Jesus com grande voz, disse: Pai, nas tuas mãos entrego o meu espírito. E, havendo dito isso, expirou.', 'Lucas 23:46', 'Lucas', 23, 46, NULL),
  ('pai', 'Porque o Filho do Homem virá na glória de seu Pai, com os seus anjos; e, então, dará a cada um segundo as suas obras.', 'Mateus 16:27', 'Mateus', 16, 27, NULL),
  ('palavra-de-deus', 'Toda Escritura divinamente inspirada é proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça, para que o homem de Deus seja perfeito e perfeitamente instruído para toda boa obra.', '2 Timóteo 3:16-17', '2 Timóteo', 3, 16, 17),
  ('palavra-de-deus', 'Porque a palavra de Deus é viva, e eficaz, e mais penetrante do que qualquer espada de dois gumes, e penetra até à divisão da alma, e do espírito, e das juntas e medulas, e é apta para discernir os pensamentos e intenções do coração.', 'Hebreus 4:12', 'Hebreus', 4, 12, NULL),
  ('palavra-de-deus', 'Lâmpada para os meus pés é tua palavra e luz, para o meu caminho.', 'Salmo 119:105', 'Salmo', 119, 105, NULL),
  ('palavra-de-deus', 'E sede cumpridores da palavra e não somente ouvintes, enganando-vos com falsos discursos.', 'Tiago 1:22', 'Tiago', 1, 22, NULL),
  ('palavra-de-deus', 'Como purificará o jovem o seu caminho? Observando-o conforme a tua palavra.', 'Salmo 119:9', 'Salmo', 119, 9, NULL),
  ('palavra-de-deus', 'Mas ele disse: Antes, bem-aventurados os que ouvem a palavra de Deus e a guardam.', 'Lucas 11:28', 'Lucas', 11, 28, NULL),
  ('palavra-de-deus', 'Seca-se a erva, e caem as flores, mas a palavra de nosso Deus subsiste eternamente.', 'Isaías 40:8', 'Isaías', 40, 8, NULL),
  ('palavra-de-deus', 'O caminho de Deus é perfeito; a palavra do Senhor é provada; é um escudo para todos os que nele confiam.', 'Salmo 18:30', 'Salmo', 18, 30, NULL),
  ('palavra-de-deus', 'Todo aquele, pois, que escuta estas minhas palavras e as pratica, assemelhá-lo-ei ao homem prudente, que edificou a sua casa sobre a rocha.', 'Mateus 7:24', 'Mateus', 7, 24, NULL),
  ('palavra-de-deus', 'O céu e a terra passarão, mas as minhas palavras não hão de passar.', 'Mateus 24:35', 'Mateus', 24, 35, NULL);

