-- Parte 10: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('palavra-de-deus', 'Fazei todas as coisas sem murmurações nem contendas; para que sejais irrepreensíveis e sinceros, filhos de Deus inculpáveis no meio duma geração corrompida e perversa, entre a qual resplandeceis como astros no mundo; retendo a palavra da vida.', 'Filipenses 2:14-16a', 'Filipenses 2:14-16a', NULL, NULL, NULL),
  ('palavra-de-deus', 'A exposição das tuas palavras dá luz e dá entendimento aos símplices.', 'Salmo 119:130', 'Salmo', 119, 130, NULL),
  ('palavra-de-deus', 'Ele, porém, respondendo, disse: Está escrito: Nem só de pão viverá o homem, mas de toda a palavra que sai da boca de Deus.', 'Mateus 4:4', 'Mateus', 4, 4, NULL),
  ('palavra-de-deus', 'No princípio, era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.', 'João 1:1', 'João', 1, 1, NULL),
  ('palavra-de-deus', 'Porque a palavra do Senhor é reta, e todas as suas obras são fiéis.', 'Salmo 33:4', 'Salmo', 33, 4, NULL),
  ('palavra-de-deus', 'Quem crê em mim, como diz a Escritura, rios de água viva correrão do seu ventre.', 'João 7:38', 'João', 7, 38, NULL),
  ('palavra-de-deus', 'Desejai afetuosamente, como meninos novamente nascidos, o leite racional, não falsificado, para que, por ele, vades crescendo.', '1 Pedro 2:2', '1 Pedro', 2, 2, NULL),
  ('palavra-de-deus', 'Em Deus louvarei a sua palavra; em Deus pus a minha confiança e não temerei; que me pode fazer a carne?', 'Salmo 56:4', 'Salmo', 56, 4, NULL),
  ('palavra-de-deus', 'Jesus dizia, pois, aos judeus que criam nele: Se vós permanecerdes na minha palavra, verdadeiramente, sereis meus discípulos e conhecereis a verdade, e a verdade vos libertará.', 'João 8:31-32', 'João', 8, 31, 32),
  ('palavra-de-deus', 'Porque o Senhor dá a sabedoria, e da sua boca vem o conhecimento e o entendimento.', 'Provérbios 2:6', 'Provérbios', 2, 6, NULL),
  ('palavra-de-deus', 'Tu és o meu refúgio e o meu escudo; espero na tua palavra.', 'Salmo 119:114', 'Salmo', 119, 114, NULL),
  ('palavra-de-deus', 'Assim será a palavra que sair da minha boca; ela não voltará para mim vazia; antes, fará o que me apraz e prosperará naquilo para que a enviei.', 'Isaías 55:11', 'Isaías', 55, 11, NULL),
  ('palavra-de-deus', 'Pelo que, rejeitando toda imundícia e acúmulo de malícia, recebei com mansidão a palavra em vós enxertada, a qual pode salvar a vossa alma.', 'Tiago 1:21', 'Tiago', 1, 21, NULL),
  ('palavra-de-deus', 'Filho meu, atenta para as minhas palavras; às minhas razões inclina o teu ouvido. Não as deixes apartar-se dos teus olhos; guarda-as no meio do teu coração.', 'Provérbios 4:20-21', 'Provérbios', 4, 20, 21),
  ('palavra-de-deus', 'Também me deste o escudo da tua salvação; a tua mão direita me susteve, e a tua mansidão me engrandeceu. Alargaste os meus passos e os meus artelhos não vacilaram.', 'Salmo 18:35-36', 'Salmo', 18, 35, 36),
  ('palavra-de-deus', 'Se vós estiverdes em mim, e as minhas palavras estiverem em vós, pedireis tudo o que quiserdes, e vos será feito.', 'João 15:7', 'João', 15, 7, NULL),
  ('palavra-de-deus', 'E o Verbo se fez carne e habitou entre nós, e vimos a sua glória, como a glória do Unigênito do Pai, cheio de graça e de verdade.', 'João 1:14', 'João', 1, 14, NULL),
  ('palavra-de-deus', 'Toda palavra de Deus é pura; escudo é para os que confiam nele.', 'Provérbios 30:5', 'Provérbios', 30, 5, NULL),
  ('palavra-de-deus', 'E te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conheceste, nem teus pais o conheceram, para te dar a entender que o homem não viverá só de pão, mas que de tudo o que sai da boca do Senhor viverá o homem.', 'Deuteronômio 8:3', 'Deuteronômio', 8, 3, NULL),
  ('palavra-de-deus', 'O qual, sendo o resplendor da sua glória, e a expressa imagem da sua pessoa, e sustentando todas as coisas pela palavra do seu poder, havendo feito por si mesmo a purificação dos nossos pecados, assentou-se à destra da Majestade, nas alturas.', 'Hebreus 1:3', 'Hebreus', 1, 3, NULL),
  ('palavra-de-deus', 'A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais; cantando ao Senhor com graça em vosso coração.', 'Colossenses 3:16', 'Colossenses', 3, 16, NULL),
  ('palavra-de-deus', 'O caminho de Deus é perfeito, e a palavra do Senhor, refinada; ele é o escudo de todos os que nele confiam.', '2 Samuel 22:31', '2 Samuel', 22, 31, NULL),
  ('palavra-de-deus', 'Escondi a tua palavra no meu coração, para eu não pecar contra ti.', 'Salmo 119:11', 'Salmo', 119, 11, NULL),
  ('palavra-de-deus', 'Porque a Escritura diz: Todo aquele que nele crer não será confundido.', 'Romanos 10:11', 'Romanos', 10, 11, NULL),
  ('palavra-de-deus', 'A tua palavra é a verdade desde o princípio, e cada um dos teus juízos dura para sempre.', 'Salmo 119:160', 'Salmo', 119, 160, NULL),
  ('palavra-de-deus', 'Aguardo o Senhor; a minha alma o aguarda, e espero na sua palavra.', 'Salmo 130:5', 'Salmo', 130, 5, NULL),
  ('palavra-de-deus', 'Sendo de novo gerados, não de semente corruptível, mas da incorruptível, pela palavra de Deus, viva e que permanece para sempre.', '1 Pedro 1:23', '1 Pedro', 1, 23, NULL),
  ('palavra-de-deus', 'Enviou a sua palavra, e os sarou, e os livrou da sua destruição.', 'Salmo 107:20', 'Salmo', 107, 20, NULL),
  ('palavra-de-deus', 'A lei do Senhor é perfeita e refrigera a alma; o testemunho do Senhor é fiel e dá sabedoria aos símplices.', 'Salmo 19:7', 'Salmo', 19, 7, NULL),
  ('palavra-de-deus', 'Portanto, dize-lhes: Assim diz o Senhor Jeová: Não será mais retardada nenhuma das minhas palavras, e a palavra que falei se cumprirá, diz o Senhor Jeová.', 'Ezequiel 12:28', 'Ezequiel', 12, 28, NULL),
  ('palavra-de-deus', 'E o que foi semeado entre espinhos é o que ouve a palavra, mas os cuidados deste mundo e a sedução das riquezas sufocam a palavra, e fica infrutífera.', 'Mateus 13:22', 'Mateus', 13, 22, NULL),
  ('palavra-de-deus', 'Adquire a sabedoria, adquire a inteligência e não te esqueças nem te apartes das palavras da minha boca.', 'Provérbios 4:5', 'Provérbios', 4, 5, NULL),
  ('palavra-de-deus', 'Fiel é o que vos chama, o qual também o fará.', '1 Tessalonicenses 5:24', '1 Tessalonicenses', 5, 24, NULL),
  ('palavra-de-deus', 'Ouve, filho meu, e aceita as minhas palavras, e se te multiplicarão os anos de vida.', 'Provérbios 4:10', 'Provérbios', 4, 10, NULL),
  ('palavra-de-deus', 'Vós já estais limpos pela palavra que vos tenho falado.', 'João 15:3', 'João', 15, 3, NULL),
  ('palavra-de-deus', 'Porque em verdade vos digo que, até que o céu e a terra passem, nem um jota ou um til se omitirá da lei sem que tudo seja cumprido.', 'Mateus 5:18', 'Mateus', 5, 18, NULL),
  ('palavra-de-deus', 'Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez.', 'João 1:3', 'João', 1, 3, NULL),
  ('palavra-de-deus', 'Tomai também o capacete da salvação e a espada do Espírito, que é a palavra de Deus.', 'Efésios 6:17', 'Efésios', 6, 17, NULL),
  ('palavra-de-deus', 'Jesus respondeu e disse-lhes: A minha doutrina não é minha, mas daquele que me enviou.', 'João 7:16', 'João', 7, 16, NULL),
  ('palavra-de-deus', 'Porque tudo que dantes foi escrito para nosso ensino foi escrito, para que, pela paciência e consolação das Escrituras, tenhamos esperança.', 'Romanos 15:4', 'Romanos', 15, 4, NULL),
  ('palavra-de-deus', 'Palavra fiel é esta: que, se morrermos com ele, também com ele viveremos.', '2 Timóteo 2:11', '2 Timóteo', 2, 11, NULL),
  ('palavra-de-deus', 'Goteje a minha doutrina como a chuva, destile o meu dito como o orvalho, como chuvisco sobre a erva e como gotas de água sobre a relva.', 'Deuteronômio 32:2', 'Deuteronômio', 32, 2, NULL),
  ('palavra-de-deus', 'Do preceito de seus lábios nunca me apartei e as palavras da sua boca prezei mais do que o meu alimento.', 'Jó 23:12', 'Jó', 23, 12, NULL),
  ('palavra-de-deus', 'E esteve Moisés ali com o Senhor quarenta dias e quarenta noites; não comeu pão, nem bebeu água, e escreveu nas tábuas as palavras do concerto, os dez mandamentos.', 'Êxodo 34:28', 'Êxodo', 34, 28, NULL),
  ('palavra-de-deus', 'De sorte que foram batizados os que de bom grado receberam a sua palavra; e, naquele dia, agregaram-se quase três mil almas.', 'Atos 2:41', 'Atos', 2, 41, NULL),
  ('pao', 'E Jesus lhes disse: Eu sou o pão da vida; aquele que vem a mim não terá fome; e quem crê em mim nunca terá sede.', 'João 6:35', 'João', 6, 35, NULL),
  ('pao', 'Ele, porém, respondendo, disse: Está escrito: Nem só de pão viverá o homem, mas de toda a palavra que sai da boca de Deus.', 'Mateus 4:4', 'Mateus', 4, 4, NULL),
  ('pao', 'Vai, pois, come com alegria o teu pão e bebe com bom coração o teu vinho, pois já Deus se agrada das tuas obras.', 'Eclesiastes 9:7', 'Eclesiastes', 9, 7, NULL),
  ('pao', 'E, tomando o pão e havendo dado graças, partiu-o e deu-lho, dizendo: Isto é o meu corpo, que por vós é dado; fazei isso em memória de mim.', 'Lucas 22:19', 'Lucas', 22, 19, NULL),
  ('pao', 'Ora, aquele que dá a semente ao que semeia e pão para comer também multiplicará a vossa sementeira e aumentará os frutos da vossa justiça.', '2 Coríntios 9:10', '2 Coríntios', 9, 10, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('pao', 'Eu sou o pão vivo que desceu do céu; se alguém comer desse pão, viverá para sempre; e o pão que eu der é a minha carne, que eu darei pela vida do mundo.', 'João 6:51', 'João', 6, 51, NULL),
  ('pao', 'O pão nosso de cada dia dá-nos hoje.', 'Mateus 6:11', 'Mateus', 6, 11, NULL),
  ('pao', 'E, perseverando unânimes todos os dias no templo e partindo o pão em casa, comiam juntos com alegria e singeleza de coração, louvando a Deus e caindo na graça de todo o povo. E todos os dias acrescentava o Senhor à igreja aqueles que se haviam de salvar.', 'Atos 2:46-47', 'Atos', 2, 46, 47),
  ('pao', 'E te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conheceste, nem teus pais o conheceram, para te dar a entender que o homem não viverá só de pão, mas que de tudo o que sai da boca do Senhor viverá o homem.', 'Deuteronômio 8:3', 'Deuteronômio', 8, 3, NULL),
  ('pao', 'E, tomando os cinco pães e os dois peixes e olhando para o céu, abençoou-os, e partiu-os, e deu-os aos seus discípulos para os porem diante da multidão. E comeram todos e saciaram-se; e levantaram, do que lhes sobejou, doze cestos de pedaços.', 'Lucas 9:16-17', 'Lucas', 9, 16, 17),
  ('pao', 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações.', 'Atos 2:42', 'Atos', 2, 42, NULL),
  ('pao', 'E aconteceu que, passando ele num sábado pelas searas, os seus discípulos, caminhando, começaram a colher espigas. E os fariseus lhe disseram: Vês? Por que fazem no sábado o que não é lícito? Mas ele disse-lhes: Nunca lestes o que fez Davi, quando estava em necessidade e teve fome, ele e os que com ele estavam? Como entrou na Casa de Deus, no tempo de Abiatar, sumo sacerdote, e comeu os pães da proposição, dos quais não era lícito comer senão aos sacerdotes, dando também aos que com ele estavam? E disse-lhes: O sábado foi feito por causa do homem, e não o homem, por causa do sábado. Assim, o Filho do Homem até do sábado é senhor.', 'Marcos 2:23-28', 'Marcos', 2, 23, 28),
  ('pao', 'Enquanto comiam, Jesus tomou o pão, e, abençoando-o, o partiu, e o deu aos discípulos, e disse: Tomai, comei, isto é o meu corpo.', 'Mateus 26:26', 'Mateus', 26, 26, NULL),
  ('pao', 'E esteve Moisés ali com o Senhor quarenta dias e quarenta noites; não comeu pão, nem bebeu água, e escreveu nas tábuas as palavras do concerto, os dez mandamentos.', 'Êxodo 34:28', 'Êxodo', 34, 28, NULL),
  ('pascoa', 'Mas o anjo, respondendo, disse às mulheres: Não tenhais medo; pois eu sei que buscai a Jesus, que foi crucificado. Ele não está aqui, porque já ressuscitou, como tinha dito. Vinde e vede o lugar onde o Senhor jazia.', 'Mateus 28:5-6', 'Mateus', 28, 5, 6),
  ('pascoa', 'Não está aqui, mas ressuscitou. Lembrai-vos como vos falou, estando ainda na Galileia, dizendo: Convém que o Filho do Homem seja entregue nas mãos de homens pecadores, e seja crucificado, e, ao terceiro dia, ressuscite.', 'Lucas 24:6-7', 'Lucas', 24, 6, 7),
  ('pascoa', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que, segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos.', '1 Pedro 1:3', '1 Pedro', 1, 3, NULL),
  ('pascoa', 'Porém ele disse-lhes: Não vos assusteis; buscais a Jesus, o Nazareno, que foi crucificado; já ressuscitou, não está aqui; eis aqui o lugar onde o puseram.', 'Marcos 16:6', 'Marcos', 16, 6, NULL),
  ('pascoa', 'Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, pudéssemos viver para a justiça; e pelas suas feridas fostes sarados.', '1 Pedro 2:24', '1 Pedro', 2, 24, NULL),
  ('pascoa', 'E, despindo-o, o cobriram com uma capa escarlate. E, tecendo uma coroa de espinhos, puseram-lha na cabeça e, em sua mão direita, uma cana; e, ajoelhando diante dele, o escarneciam, dizendo: Salve, Rei dos judeus!', 'Mateus 27:28-29', 'Mateus', 27, 28, 29),
  ('pascoa', 'E, quando Jesus tomou o vinagre, disse: Está consumado. E, inclinando a cabeça, entregou o espírito.', 'João 19:30', 'João', 19, 30, NULL),
  ('pascoa', 'Eis que vamos para Jerusalém, e o Filho do Homem será entregue aos príncipes dos sacerdotes e aos escribas, e condená-lo-ão à morte. E o entregarão aos gentios para que dele escarneçam, e o açoitem, e crucifiquem, e ao terceiro dia ressuscitará.', 'Mateus 20:18-19', 'Mateus', 20, 18, 19),
  ('pascoa', 'E as multidões, tanto as que iam adiante como as que o seguiam, clamavam, dizendo: Hosana ao Filho de Davi! Bendito o que vem em nome do Senhor! Hosana nas alturas!', 'Mateus 21:9', 'Mateus', 21, 9, NULL),
  ('pascoa', 'E, clamando Jesus com grande voz, disse: Pai, nas tuas mãos entrego o meu espírito. E, havendo dito isso, expirou.', 'Lucas 23:46', 'Lucas', 23, 46, NULL),
  ('pascoa', 'Oh! Salva, Senhor, nós te pedimos; ó Senhor, nós te pedimos, prospera! Bendito aquele que vem em nome do Senhor; nós vos bendizemos desde a Casa do Senhor.', 'Salmo 118:25-26', 'Salmo', 118, 25, 26),
  ('pascoa', 'Aba, Pai, todas as coisas te são possíveis; afasta de mim este cálice; não seja, porém, o que eu quero, mas o que tu queres.', 'Marcos 14:36', 'Marcos', 14, 36, NULL),
  ('pascoa', 'E, por cima da sua cabeça, puseram escrita a sua acusação: Este é Jesus, O Rei dos Judeus.', 'Mateus 27:37', 'Mateus', 27, 37, NULL),
  ('pascoa', 'Então, entrou também o outro discípulo, que chegara primeiro ao sepulcro, e viu, e creu. Porque ainda não sabiam a Escritura, que diz que era necessário que ressuscitasse dos mortos.', 'João 20:8-9', 'João', 20, 8, 9),
  ('pascoa', 'Alegra-te muito, ó filha de Sião; exulta, ó filha de Jerusalém; eis que o teu rei virá a ti, justo e Salvador, pobre e montado sobre um jumento, sobre um asninho, filho de jumenta.', 'Zacarias 9:9', 'Zacarias', 9, 9, NULL),
  ('pascoa', 'E dizia Jesus: Pai, perdoa-lhes, porque não sabem o que fazem. E, repartindo as suas vestes, lançaram sortes.', 'Lucas 23:34', 'Lucas', 23, 34, NULL),
  ('pascoa', 'Ressuscitou, verdadeiramente, o Senhor e já apareceu a Simão.', 'Lucas 24:34', 'Lucas', 24, 34, NULL),
  ('paz', 'O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti e tenha misericórdia de ti; o Senhor sobre ti levante o seu rosto e te dê a paz.', 'Números 6:24-26', 'Números', 6, 24, 26),
  ('paz', 'Tenho-vos dito isso, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo; eu venci o mundo.', 'João 16:33', 'João', 16, 33, NULL),
  ('paz', 'Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.', 'Filipenses 4:6-7', 'Filipenses', 4, 6, 7),
  ('paz', 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.', 'João 14:27', 'João', 14, 27, NULL),
  ('paz', 'Ora, o mesmo Senhor da paz vos dê sempre paz de toda maneira. O Senhor seja com todos vós.', '2 Tessalonicenses 3:16', '2 Tessalonicenses', 3, 16, NULL),
  ('paz', 'Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus.', 'Mateus 5:9', 'Mateus', 5, 9, NULL),
  ('paz', 'Porque quem quer amar a vida e ver os dias bons, refreie a sua língua do mal, e os seus lábios não falem engano; aparte-se do mal e faça o bem; busque a paz e siga-a.', '1 Pedro 3:10-11', '1 Pedro', 3, 10, 11),
  ('paz', 'Em paz também me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.', 'Salmo 4:8', 'Salmo', 4, 8, NULL),
  ('paz', 'Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti.', 'Isaías 26:3', 'Isaías', 26, 3, NULL),
  ('paz', 'E a paz de Deus, para a qual também fostes chamados em um corpo, domine em vossos corações; e sede agradecidos.', 'Colossenses 3:15', 'Colossenses', 3, 15, NULL),
  ('paz', 'A misericórdia, e a paz, e o amor vos sejam multiplicadas.', 'Judas 1:2', 'Judas', 1, 2, NULL),
  ('paz', 'Suportando-vos uns aos outros e perdoando-vos uns aos outros, se algum tiver queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também.', 'Colossenses 3:13', 'Colossenses', 3, 13, NULL),
  ('paz', 'Melhor é o longânimo do que o valente, e o que governa o seu espírito do que o que toma uma cidade.', 'Provérbios 16:32', 'Provérbios', 16, 32, NULL),
  ('paz', 'Aparta-te do mal e faze o bem; procura a paz e segue-a.', 'Salmo 34:14', 'Salmo', 34, 14, NULL),
  ('paz', 'Ora, o fruto da justiça semeia-se na paz, para os que exercitam a paz.', 'Tiago 3:18', 'Tiago', 3, 18, NULL),
  ('paz', 'Segui a paz com todos e a santificação, sem a qual ninguém verá o Senhor.', 'Hebreus 12:14', 'Hebreus', 12, 14, NULL),
  ('paz', 'Procurando guardar a unidade do Espírito pelo vínculo da paz.', 'Efésios 4:3', 'Efésios', 4, 3, NULL),
  ('paz', 'Muita paz têm os que amam a tua lei, e para eles não há tropeço.', 'Salmo 119:165', 'Salmo', 119, 165, NULL),
  ('paz', 'Mas a sabedoria que vem do alto é, primeiramente, pura, depois, pacífica, moderada, tratável, cheia de misericórdia e de bons frutos, sem parcialidade e sem hipocrisia.', 'Tiago 3:17', 'Tiago', 3, 17, NULL),
  ('paz', 'O Senhor dará força ao seu povo; o Senhor abençoará o seu povo com paz.', 'Salmo 29:11', 'Salmo', 29, 11, NULL),
  ('paz', 'Porque a inclinação da carne é morte; mas a inclinação do Espírito é vida e paz.', 'Romanos 8:6', 'Romanos', 8, 6, NULL),
  ('paz', 'O que também aprendestes, e recebestes, e ouvistes, e vistes em mim, isso fazei; e o Deus de paz será convosco.', 'Filipenses 4:9', 'Filipenses', 4, 9, NULL),
  ('paz', 'Aquietai-vos e sabei que eu sou Deus; serei exaltado entre as nações; serei exaltado sobre a terra.', 'Salmo 46:10', 'Salmo', 46, 10, NULL),
  ('paz', 'Quão suaves são sobre os montes os pés do que anuncia as boas-novas, que faz ouvir a paz, que anuncia o bem, que faz ouvir a salvação, que diz a Sião: O teu Deus reina!', 'Isaías 52:7', 'Isaías', 52, 7, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('paz', 'Honroso é para o homem o desviar-se de questões, mas todo tolo se entremete nelas.', 'Provérbios 20:3', 'Provérbios', 20, 3, NULL),
  ('paz', 'E, na verdade, toda correção, ao presente, não parece ser de gozo, senão de tristeza, mas, depois, produz um fruto pacífico de justiça nos exercitados por ela.', 'Hebreus 12:11', 'Hebreus', 12, 11, NULL),
  ('paz', 'Se for possível, quanto estiver em vós, tende paz com todos os homens.', 'Romanos 12:18', 'Romanos', 12, 18, NULL),
  ('paz', 'Quanto ao mais, irmãos, regozijai-vos, sede perfeitos, sede consolados, sede de um mesmo parecer, vivei em paz; e o Deus de amor e de paz será convosco.', '2 Coríntios 13:11', '2 Coríntios', 13, 11, NULL),
  ('paz', 'Porque as montanhas se desviarão e os outeiros tremerão; mas a minha benignidade não se desviará de ti, e o concerto da minha paz não mudará, diz o Senhor, que se compadece de ti.', 'Isaías 54:10', 'Isaías', 54, 10, NULL),
  ('paz', 'Sendo, pois, justificados pela fé, temos paz com Deus por nosso Senhor Jesus Cristo.', 'Romanos 5:1', 'Romanos', 5, 1, NULL),
  ('paz', 'Engano há no coração dos que maquinam mal, mas alegria têm os que aconselham a paz.', 'Provérbios 12:20', 'Provérbios', 12, 20, NULL),
  ('paz', 'Graça e paz de Deus, nosso Pai, e do Senhor Jesus Cristo.', 'Romanos 1:7b', 'Romanos 1:7b', NULL, NULL, NULL),
  ('paz', 'Não cuideis que vim trazer a paz à terra; não vim trazer paz, mas espada.', 'Mateus 10:34', 'Mateus', 10, 34, NULL),
  ('paz', 'Filho meu, não te esqueças da minha lei, e o teu coração guarde os meus mandamentos. Porque eles aumentarão os teus dias e te acrescentarão anos de vida e paz.', 'Provérbios 3:1-2', 'Provérbios', 3, 1, 2),
  ('paz', 'Disse-lhes, pois, Jesus outra vez: Paz seja convosco! Assim como o Pai me enviou, também eu vos envio a vós.', 'João 20:21', 'João', 20, 21, NULL),
  ('paz', 'Glória a Deus nas alturas, paz na terra, boa vontade para com os homens!', 'Lucas 2:14', 'Lucas', 2, 14, NULL),
  ('paz', 'Ora, o Deus de paz, que pelo sangue do concerto eterno tornou a trazer dos mortos a nosso Senhor Jesus Cristo, grande Pastor das ovelhas, vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável por Cristo Jesus, ao qual seja glória para todo o sempre. Amém!', 'Hebreus 13:20-21', 'Hebreus', 13, 20, 21),
  ('paz', 'E o Deus de paz esmagará em breve Satanás debaixo dos vossos pés. A graça de nosso Senhor Jesus Cristo seja convosco. Amém!', 'Romanos 16:20', 'Romanos', 16, 20, NULL),
  ('paz', 'Assim, pois, as igrejas em toda a Judeia, e Galileia, e Samaria tinham paz e eram edificadas; e se multiplicavam, andando no temor do Senhor e na consolação do Espírito Santo.', 'Atos 9:31', 'Atos', 9, 31, NULL),
  ('paz', 'Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça, e calçados os pés na preparação do evangelho da paz; tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno.', 'Efésios 6:14-16', 'Efésios', 6, 14, 16),
  ('paz', 'Foge, também, dos desejos da mocidade; e segue a justiça, a fé, o amor e a paz com os que, com um coração puro, invocam o Senhor.', '2 Timóteo 2:22', '2 Timóteo', 2, 22, NULL),
  ('pecado', 'Não sabeis que os injustos não hão de herdar o Reino de Deus? Não erreis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas, nem os ladrões, nem os avarentos, nem os bêbados, nem os maldizentes, nem os roubadores herdarão o Reino de Deus.', '1 Coríntios 6:9-10', '1 Coríntios', 6, 9, 10),
  ('pecado', 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.', '1 João 1:9', '1 João', 1, 9, NULL),
  ('pecado', 'Porque todos pecaram e destituídos estão da glória de Deus, sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus.', 'Romanos 3:23-24', 'Romanos', 3, 23, 24),
  ('pecado', 'Mortificai, pois, os vossos membros que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência e a avareza, que é idolatria.', 'Colossenses 3:5', 'Colossenses', 3, 5, NULL),
  ('pecado', 'Pois quê? Pecaremos porque não estamos debaixo da lei, mas debaixo da graça? De modo nenhum!', 'Romanos 6:15', 'Romanos', 6, 15, NULL),
  ('pecado', 'Ordena os meus passos na tua palavra, e não se apodere de mim iniquidade alguma.', 'Salmo 119:133', 'Salmo', 119, 133, NULL),
  ('pecado', 'Ora, se teu irmão pecar contra ti, vai e repreende-o entre ti e ele só; se te ouvir, ganhaste a teu irmão.', 'Mateus 18:15', 'Mateus', 18, 15, NULL),
  ('pecado', 'Adúlteros e adúlteras, não sabeis vós que a amizade do mundo é inimizade contra Deus? Portanto, qualquer que quiser ser amigo do mundo constitui-se inimigo de Deus.', 'Tiago 4:4', 'Tiago', 4, 4, NULL),
  ('pecado', 'Tem misericórdia de mim, ó Deus, segundo a tua benignidade; apaga as minhas transgressões, segundo a multidão das tuas misericórdias. Lava-me completamente da minha iniquidade e purifica-me do meu pecado.', 'Salmo 51:1-2', 'Salmo', 51, 1, 2),
  ('pecado', 'Quem anda em sinceridade anda seguro, mas o que perverte os seus caminhos será conhecido.', 'Provérbios 10:9', 'Provérbios', 10, 9, NULL),
  ('pecado', 'O homem bom, do bom tesouro do seu coração, tira o bem, e o homem mau, do mau tesouro do seu coração, tira o mal, porque da abundância do seu coração fala a boca.', 'Lucas 6:45', 'Lucas', 6, 45, NULL),
  ('pecado', 'E por que reparas tu no argueiro que está no olho do teu irmão e não vês a trave que está no teu olho?', 'Mateus 7:3', 'Mateus', 7, 3, NULL),
  ('pecado', 'Se dissermos que temos comunhão com ele e andarmos em trevas, mentimos e não praticamos a verdade.', '1 João 1:6', '1 João', 1, 6, NULL),
  ('pecado', 'E não comuniqueis com as obras infrutuosas das trevas, mas, antes, condenai-as. Porque o que eles fazem em oculto, até dizê-lo é torpe.', 'Efésios 5:11-12', 'Efésios', 5, 11, 12),
  ('pecado', 'Bem-aventurado o varão que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores.', 'Salmo 1:1', 'Salmo', 1, 1, NULL),
  ('pecado', 'Mas, sobretudo, tende ardente amor uns para com os outros, porque o amor cobrirá a multidão de pecados.', '1 Pedro 4:8', '1 Pedro', 4, 8, NULL),
  ('pecado', 'E dizia: O que sai do homem, isso é que contamina o homem. Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios, os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura. Todos estes males procedem de dentro e contaminam o homem.', 'Marcos 7:20-23', 'Marcos', 7, 20, 23),
  ('pecado', 'Irmãos, se algum homem chegar a ser surpreendido nalguma ofensa, vós, que sois espirituais, encaminhai o tal com espírito de mansidão, olhando por ti mesmo, para que não sejas também tentado.', 'Gálatas 6:1', 'Gálatas', 6, 1, NULL),
  ('pecado', 'Chegai-vos a Deus, e ele se chegará a vós. Limpai as mãos, pecadores; e, vós de duplo ânimo, purificai o coração.', 'Tiago 4:8', 'Tiago', 4, 8, NULL),
  ('pecado', 'Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, pudéssemos viver para a justiça; e pelas suas feridas fostes sarados.', '1 Pedro 2:24', '1 Pedro', 2, 24, NULL),
  ('pecado', 'De uma mesma boca procede bênção e maldição. Meus irmãos, não convém que isto se faça assim.', 'Tiago 3:10', 'Tiago', 3, 10, NULL),
  ('pecado', 'O que encobre as suas transgressões nunca prosperará; mas o que as confessa e deixa alcançará misericórdia.', 'Provérbios 28:13', 'Provérbios', 28, 13, NULL),
  ('pecado', 'Assim também Cristo, oferecendo-se uma vez, para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para a salvação.', 'Hebreus 9:28', 'Hebreus', 9, 28, NULL),
  ('pecado', 'Mas a prostituição e toda impureza ou avareza nem ainda se nomeiem entre vós, como convém a santos.', 'Efésios 5:3', 'Efésios', 5, 3, NULL),
  ('pecado', 'Por isso, nenhuma carne será justificada diante dele pelas obras da lei, porque pela lei vem o conhecimento do pecado.', 'Romanos 3:20', 'Romanos', 3, 20, NULL),
  ('pecado', 'Lembra-te, Senhor, das tuas misericórdias e das tuas benignidades, porque são desde a eternidade. Não te lembres dos pecados da minha mocidade nem das minhas transgressões; mas, segundo a tua misericórdia, lembra-te de mim, por tua bondade, Senhor.', 'Salmo 25:6-7', 'Salmo', 25, 6, 7),
  ('pecado', 'Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós.', 'Mateus 6:14', 'Mateus', 6, 14, NULL),
  ('pecado', 'Portanto, os que estão na carne não podem agradar a Deus.', 'Romanos 8:8', 'Romanos', 8, 8, NULL),
  ('pecado', 'Respondeu-lhes Jesus: Em verdade, em verdade vos digo que todo aquele que comete pecado é servo do pecado.', 'João 8:34', 'João', 8, 34, NULL),
  ('pecado', 'Porque o que semeia na sua carne da carne ceifará a corrupção; mas o que semeia no Espírito do Espírito ceifará a vida eterna.', 'Gálatas 6:8', 'Gálatas', 6, 8, NULL),
  ('pecado', 'Bem-aventurado aquele cuja transgressão é perdoada, e cujo pecado é coberto.', 'Salmo 32:1', 'Salmo', 32, 1, NULL),
  ('pecado', 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus, nosso Senhor.', 'Romanos 6:23', 'Romanos', 6, 23, NULL),
  ('pecado', 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, e venham, assim, os tempos do refrigério pela presença do Senhor.', 'Atos 3:19', 'Atos', 3, 19, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('pecado', 'A memória do justo é abençoada, mas o nome dos ímpios apodrecerá.', 'Provérbios 10:7', 'Provérbios', 10, 7, NULL),
  ('pecado', 'Irai-vos e não pequeis; não se ponha o sol sobre a vossa ira. Não deis lugar ao diabo.', 'Efésios 4:26-27', 'Efésios', 4, 26, 27),
  ('pecado', 'Ora, o aguilhão da morte é o pecado, e a força do pecado é a lei.', '1 Coríntios 15:56', '1 Coríntios', 15, 56, NULL),
  ('pecado', 'Vinde e convertei-vos de todas as vossas transgressões, e a iniquidade não vos servirá de tropeço.', 'Ezequiel 18:30b', 'Ezequiel 18:30b', NULL, NULL, NULL),
  ('pecado', 'Será, pois, que, culpado sendo numa destas coisas, confessará aquilo em que pecou.', 'Levítico 5:5', 'Levítico', 5, 5, NULL),
  ('pecado', 'Que diremos, pois? Permaneceremos no pecado, para que a graça seja mais abundante? De modo nenhum! Nós que estamos mortos para o pecado, como viveremos ainda nele?', 'Romanos 6:1-2', 'Romanos', 6, 1, 2),
  ('pecado', 'Há caminho que ao homem parece direito, mas o fim dele são os caminhos da morte.', 'Provérbios 14:12', 'Provérbios', 14, 12, NULL),
  ('pecado', 'Porque serei misericordioso para com as suas iniquidades e de seus pecados e de suas prevaricações não me lembrarei mais.', 'Hebreus 8:12', 'Hebreus', 8, 12, NULL),
  ('pecado', 'Quem pratica o pecado é do diabo, porque o diabo vive pecando desde o princípio. Para isto o Filho de Deus se manifestou: para desfazer as obras do diabo.', '1 João 3:8', '1 João', 3, 8, NULL),
  ('pecado', 'Àquele que não conheceu pecado, o fez pecado por nós; para que, nele, fôssemos feitos justiça de Deus.', '2 Coríntios 5:21', '2 Coríntios', 5, 21, NULL),
  ('pecado', 'Digo, porém: Andai em Espírito e não cumprireis a concupiscência da carne.', 'Gálatas 5:16', 'Gálatas', 5, 16, NULL),
  ('pecado', 'Pecamos, e cometemos iniquidade, e procedemos impiamente, e fomos rebeldes, apartando-nos dos teus mandamentos e dos teus juízos.', 'Daniel 9:5', 'Daniel', 9, 5, NULL),
  ('pecado', 'Mas a Escritura encerrou tudo debaixo do pecado, para que a promessa pela fé em Jesus Cristo fosse dada aos crentes.', 'Gálatas 3:22', 'Gálatas', 3, 22, NULL),
  ('pecado', 'E, se alguma pessoa pecar e fizer contra algum de todos os mandamentos do Senhor o que se não deve fazer, ainda que o não soubesse, contudo, será ela culpada e levará a sua iniquidade.', 'Levítico 5:17', 'Levítico', 5, 17, NULL),
  ('pecado', 'Não ameis o mundo, nem o que no mundo há. Se alguém ama o mundo, o amor do Pai não está nele.', '1 João 2:15', '1 João', 2, 15, NULL),
  ('pecado', 'Vigiai justamente e não pequeis; porque alguns ainda não têm o conhecimento de Deus; digo-o para vergonha vossa.', '1 Coríntios 15:34', '1 Coríntios', 15, 34, NULL),
  ('pecado', 'Qualquer que pratica o pecado também pratica iniquidade, porque o pecado é iniquidade.', '1 João 3:4', '1 João', 3, 4, NULL),
  ('pecado', 'Na multidão de palavras não falta transgressão, mas o que modera os seus lábios é prudente.', 'Provérbios 10:19', 'Provérbios', 10, 19, NULL),
  ('pecado', 'Confessei-te o meu pecado e a minha maldade não encobri; dizia eu: Confessarei ao Senhor as minhas transgressões; e tu perdoaste a maldade do meu pecado. (Selá)', 'Salmo 32:5', 'Salmo', 32, 5, NULL),
  ('pecado', 'Vinde, então, e argui-me, diz o Senhor; ainda que os vossos pecados sejam como a escarlata, eles se tornarão brancos como a neve; ainda que sejam vermelhos como o carmesim, se tornarão como a branca lã.', 'Isaías 1:18', 'Isaías', 1, 18, NULL),
  ('pecado', 'Escondi a tua palavra no meu coração, para eu não pecar contra ti.', 'Salmo 119:11', 'Salmo', 119, 11, NULL),
  ('pecado', 'A justiça exalta as nações, mas o pecado é o opróbrio dos povos.', 'Provérbios 14:34', 'Provérbios', 14, 34, NULL),
  ('pecado', 'Porque o pecado não terá domínio sobre vós, pois não estais debaixo da lei, mas debaixo da graça.', 'Romanos 6:14', 'Romanos', 6, 14, NULL),
  ('pecado', 'Eu não vim chamar os justos, mas sim os pecadores, ao arrependimento.', 'Lucas 5:32', 'Lucas', 5, 32, NULL),
  ('pecado', 'Porque, onde há inveja e espírito faccioso, aí há perturbação e toda obra perversa.', 'Tiago 3:16', 'Tiago', 3, 16, NULL),
  ('pecado', 'Mas ele foi ferido pelas nossas transgressões e moído pelas nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e, pelas suas pisaduras, fomos sarados.', 'Isaías 53:5', 'Isaías', 53, 5, NULL),
  ('pecado', 'Lavai-vos, purificai-vos, tirai a maldade de vossos atos de diante dos meus olhos e cessai de fazer mal.', 'Isaías 1:16', 'Isaías', 1, 16, NULL),
  ('pecado', 'Mas, se o ímpio se converter de todos os seus pecados que cometeu, e guardar todos os meus estatutos, e fizer juízo e justiça, certamente viverá; não morrerá.', 'Ezequiel 18:21', 'Ezequiel', 18, 21, NULL),
  ('pecado', 'O caminho do Senhor é fortaleza para os retos, mas ruína virá aos que praticam a iniquidade.', 'Provérbios 10:29', 'Provérbios', 10, 29, NULL),
  ('pecado', 'Nem tampouco apresenteis os vossos membros ao pecado por instrumentos de iniquidade; mas apresentai-vos a Deus, como vivos dentre mortos, e os vossos membros a Deus, como instrumentos de justiça.', 'Romanos 6:13', 'Romanos', 6, 13, NULL),
  ('pecado', 'Ora, pois, já que Cristo padeceu por nós na carne, armai-vos também vós com este pensamento: que aquele que padeceu na carne já cessou do pecado.', '1 Pedro 4:1', '1 Pedro', 4, 1, NULL),
  ('pecado', 'E esta é a mensagem que dele ouvimos e vos anunciamos: que Deus é luz, e não há nele treva nenhuma.', '1 João 1:5', '1 João', 1, 5, NULL),
  ('pecado', 'O que guardar o mandamento guardará a sua alma; mas o que desprezar os seus caminhos morrerá.', 'Provérbios 19:16', 'Provérbios', 19, 16, NULL),
  ('pecado', 'Então, foram abertos os olhos de ambos, e conheceram que estavam nus; e coseram folhas de figueira, e fizeram para si aventais.', 'Gênesis 3:7', 'Gênesis', 3, 7, NULL),
  ('pecado', 'Desfaço as tuas transgressões como a névoa, e os teus pecados, como a nuvem; torna-te para mim, porque eu te remi.', 'Isaías 44:22', 'Isaías', 44, 22, NULL),
  ('pecado', 'Isto é, Deus estava em Cristo reconciliando consigo o mundo, não lhes imputando os seus pecados, e pôs em nós a palavra da reconciliação.', '2 Coríntios 5:19', '2 Coríntios', 5, 19, NULL),
  ('pecado', 'Nisto está o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou e enviou seu Filho para propiciação pelos nossos pecados.', '1 João 4:10', '1 João', 4, 10, NULL),
  ('pecado', 'Enquanto eu me calei, envelheceram os meus ossos pelo meu bramido em todo o dia.', 'Salmo 32:3', 'Salmo', 32, 3, NULL),
  ('pecado', 'Cobiçais e nada tendes; sois invejosos e cobiçosos e não podeis alcançar; combateis e guerreais e nada tendes, porque não pedis.', 'Tiago 4:2', 'Tiago', 4, 2, NULL),
  ('pecado', 'Portanto, nós também, pois, que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo embaraço e o pecado que tão de perto nos rodeia e corramos, com paciência, a carreira que nos está proposta.', 'Hebreus 12:1', 'Hebreus', 12, 1, NULL),
  ('pecado', 'Se, porém, não perdoardes aos homens as suas ofensas, também vosso Pai vos não perdoará as vossas ofensas.', 'Mateus 6:15', 'Mateus', 6, 15, NULL),
  ('pecado', 'Quanto está longe o Oriente do Ocidente, assim afasta de nós as nossas transgressões.', 'Salmo 103:12', 'Salmo', 103, 12, NULL),
  ('pecado', 'Digo-vos que assim haverá alegria no céu por um pecador que se arrepende, mais do que por noventa e nove justos que não necessitam de arrependimento.', 'Lucas 15:7', 'Lucas', 15, 7, NULL),
  ('pecado', 'Porque vale mais um dia nos teus átrios do que, em outra parte, mil. Preferiria estar à porta da Casa do meu Deus, a habitar nas tendas da impiedade.', 'Salmo 84:10', 'Salmo', 84, 10, NULL),
  ('pecado', 'Quem, ó Deus, é semelhante a ti, que perdoas a iniquidade e que te esqueces da rebelião do restante da tua herança? O Senhor não retém a sua ira para sempre, porque tem prazer na benignidade.', 'Miqueias 7:18', 'Miqueias', 7, 18, NULL),
  ('pecado', 'E, se teu irmão pecar contra ti, repreende-o; e, se ele se arrepender, perdoa-lhe; e, se pecar contra ti sete vezes no dia e sete vezes no dia vier ter contigo, dizendo: Arrependo-me, perdoa-lhe.', 'Lucas 17:3b-4', 'Lucas 17:3b-4', NULL, NULL, NULL),
  ('pecado', 'Vale mais o pouco que tem o justo do que as riquezas de muitos ímpios. Pois os braços dos ímpios se quebrarão, mas o Senhor sustém os justos.', 'Salmo 37:16-17', 'Salmo', 37, 16, 17),
  ('pecado', 'E, se não as escutar, dize-o à igreja; e, se também não escutar a igreja, considera-o como um gentio e publicano.', 'Mateus 18:17', 'Mateus', 18, 17, NULL),
  ('pecado', 'O ímpio recebe um salário enganoso, mas, para o que semeia justiça, haverá galardão certo.', 'Provérbios 11:18', 'Provérbios', 11, 18, NULL),
  ('pecado', 'Porque apenas alguém morrerá por um justo; pois poderá ser que pelo bom alguém ouse morrer. Mas Deus prova o seu amor para conosco em que Cristo morreu por nós, sendo nós ainda pecadores.', 'Romanos 5:7-8', 'Romanos', 5, 7, 8);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('pecado', 'Em quem temos a redenção pelo seu sangue, a remissão das ofensas, segundo as riquezas da sua graça.', 'Efésios 1:7', 'Efésios', 1, 7, NULL),
  ('pecado', 'Tornará a apiedar-se de nós, subjugará as nossas iniquidades e lançará todos os nossos pecados nas profundezas do mar.', 'Miqueias 7:19', 'Miqueias', 7, 19, NULL),
  ('pecado', 'Ouvistes que foi dito aos antigos: Não cometerás adultério. Eu porém, vos digo que qualquer que atentar numa mulher para a cobiçar já em seu coração cometeu adultério com ela.', 'Mateus 5:27-28', 'Mateus', 5, 27, 28),
  ('pecado', 'Portanto, se o teu olho direito te escandalizar, arranca-o e atira-o para longe de ti, pois te é melhor que se perca um dos teus membros do que todo o teu corpo seja lançado no inferno.', 'Mateus 5:29', 'Mateus', 5, 29, NULL),
  ('pecado', 'E, agora, por que te deténs? Levanta-te, e batiza-te, e lava os teus pecados, invocando o nome do Senhor.', 'Atos 22:16', 'Atos', 22, 16, NULL),
  ('pecado', 'Muitos serão purificados, e embranquecidos, e provados; mas os ímpios procederão impiamente, e nenhum dos ímpios entenderá, mas os sábios entenderão.', 'Daniel 12:10', 'Daniel', 12, 10, NULL),
  ('pecado', 'Ajuda-nos, ó Deus da nossa salvação, pela glória do teu nome; e livra-nos e perdoa os nossos pecados, por amor do teu nome.', 'Salmo 79:9', 'Salmo', 79, 9, NULL),
  ('pecado', 'Ele revela o profundo e o escondido e conhece o que está em trevas; e com ele mora a luz.', 'Daniel 2:22', 'Daniel', 2, 22, NULL),
  ('pecado', 'A face do Senhor está contra os que fazem o mal, para desarraigar da terra a memória deles.', 'Salmo 34:16', 'Salmo', 34, 16, NULL),
  ('pecado', 'Ressuscitando Deus a seu Filho Jesus, primeiro o enviou a vós, para que nisso vos abençoasse, e vos desviasse, a cada um, das vossas maldades.', 'Atos 3:26', 'Atos', 3, 26, NULL),
  ('pecado', 'Porque todos os que sem lei pecaram sem lei também perecerão; e todos os que sob a lei pecaram pela lei serão julgados.', 'Romanos 2:12', 'Romanos', 2, 12, NULL),
  ('pecado', 'Que diremos, pois? É a lei pecado? De modo nenhum! Mas eu não conheci o pecado senão pela lei; porque eu não conheceria a concupiscência, se a lei não dissesse: Não cobiçarás.', 'Romanos 7:7', 'Romanos', 7, 7, NULL),
  ('pecado', 'Porque primeiramente vos entreguei o que também recebi: que Cristo morreu por nossos pecados, segundo as Escrituras, e que foi sepultado, e que ressuscitou ao terceiro dia, segundo as Escrituras.', '1 Coríntios 15:3-4', '1 Coríntios', 15, 3, 4),
  ('pecado', 'Porque, se fomos plantados juntamente com ele na semelhança da sua morte, também o seremos na da sua ressurreição; sabendo isto: que o nosso velho homem foi com ele crucificado, para que o corpo do pecado seja desfeito, a fim de que não sirvamos mais ao pecado.', 'Romanos 6:5-6', 'Romanos', 6, 5, 6),
  ('pecado', 'Visto como se não executa logo o juízo sobre a má obra, por isso o coração dos filhos dos homens está inteiramente disposto para praticar o mal.', 'Eclesiastes 8:11', 'Eclesiastes', 8, 11, NULL),
  ('pecado', 'Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado.', 'Hebreus 4:15', 'Hebreus', 4, 15, NULL),
  ('pecado', 'E ele é a propiciação pelos nossos pecados e não somente pelos nossos, mas também pelos de todo o mundo.', '1 João 2:2', '1 João', 2, 2, NULL),
  ('pecado', 'E eu santificarei o meu grande nome, que foi profanado entre as nações, o qual profanastes no meio delas; e as nações saberão que eu sou o Senhor, diz o Senhor Jeová, quando eu for santificado aos seus olhos.', 'Ezequiel 36:23', 'Ezequiel', 36, 23, NULL),
  ('pecado', 'Então, Pedro, aproximando-se dele, disse: Senhor, até quantas vezes pecará meu irmão contra mim, e eu lhe perdoarei? Até sete? Jesus lhe disse: Não te digo que até sete, mas até setenta vezes sete.', 'Mateus 18:21-22', 'Mateus', 18, 21, 22),
  ('pecado', 'Vós tendes por pai ao diabo e quereis satisfazer os desejos de vosso pai; ele foi homicida desde o princípio e não se firmou na verdade, porque não há verdade nele; quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira.', 'João 8:44', 'João', 8, 44, NULL),
  ('pecado', 'E, quando estiverdes orando, perdoai, se tendes alguma coisa contra alguém, para que vosso Pai, que está nos céus, vos perdoe as vossas ofensas.', 'Marcos 11:25', 'Marcos', 11, 25, NULL),
  ('pecado', 'Portanto, eu vos digo: todo pecado e blasfêmia se perdoará aos homens, mas a blasfêmia contra o Espírito não será perdoada aos homens.', 'Mateus 12:31', 'Mateus', 12, 31, NULL),
  ('pecado', 'Porquanto tudo o que em trevas dissestes à luz será ouvido; e o que falastes ao ouvido no gabinete sobre os telhados será apregoado.', 'Lucas 12:3', 'Lucas', 12, 3, NULL),
  ('pecado', 'O qual se deu a si mesmo por nós, para nos remir de toda iniquidade e purificar para si um povo seu especial, zeloso de boas obras.', 'Tito 2:14', 'Tito', 2, 14, NULL),
  ('pecado', 'Mas, agora, libertados do pecado e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna.', 'Romanos 6:22', 'Romanos', 6, 22, NULL),
  ('pecado', 'Quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus, purificará a vossa consciência das obras mortas, para servirdes ao Deus vivo?', 'Hebreus 9:14', 'Hebreus', 9, 14, NULL),
  ('pecado', 'O qual, sendo o resplendor da sua glória, e a expressa imagem da sua pessoa, e sustentando todas as coisas pela palavra do seu poder, havendo feito por si mesmo a purificação dos nossos pecados, assentou-se à destra da Majestade, nas alturas.', 'Hebreus 1:3', 'Hebreus', 1, 3, NULL),
  ('pecado', 'A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e guardar-se da corrupção do mundo.', 'Tiago 1:27', 'Tiago', 1, 27, NULL),
  ('pecado', 'Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor, em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados.', 'Colossenses 1:13-14', 'Colossenses', 1, 13, 14),
  ('pecado', 'Para que, assim como o pecado reinou na morte, também a graça reinasse pela justiça para a vida eterna, por Jesus Cristo, nosso Senhor.', 'Romanos 5:21', 'Romanos', 5, 21, NULL),
  ('pecado', 'Vós sois o sal da terra; e, se o sal for insípido, com que se há de salgar? Para nada mais presta, senão para se lançar fora e ser pisado pelos homens.', 'Mateus 5:13', 'Mateus', 5, 13, NULL),
  ('pecado', 'E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão.', 'Hebreus 9:22', 'Hebreus', 9, 22, NULL),
  ('pecado', 'Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor; e a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados.', 'Tiago 5:14-15', 'Tiago', 5, 14, 15),
  ('pecado', 'Porque as obras da carne são manifestas, as quais são: prostituição, impureza, lascívia, idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias, invejas, homicídios, bebedices, glutonarias e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas não herdarão o Reino de Deus.', 'Gálatas 5:19-21', 'Gálatas', 5, 19, 21),
  ('pecado', 'Eu sou a videira verdadeira, e meu Pai é o lavrador. Toda vara em mim que não dá fruto, a tira; e limpa toda aquela que dá fruto, para que dê mais fruto.', 'João 15:1-2', 'João', 15, 1, 2),
  ('pecado', 'Mas não é assim o dom gratuito como a ofensa; porque, se, pela ofensa de um, morreram muitos, muito mais a graça de Deus e o dom pela graça, que é de um só homem, Jesus Cristo, abundou sobre muitos.', 'Romanos 5:15', 'Romanos', 5, 15, NULL),
  ('pecado', 'E, quando ele vier, convencerá o mundo do pecado, e da justiça, e do juízo.', 'João 16:8', 'João', 16, 8, NULL),
  ('pecado', 'Fugi da prostituição. Todo pecado que o homem comete é fora do corpo; mas o que se prostitui peca contra o seu próprio corpo.', '1 Coríntios 6:18', '1 Coríntios', 6, 18, NULL),
  ('pecado', 'Então, disse o Senhor Deus: Eis que o homem é como um de nós, sabendo o bem e o mal; ora, pois, para que não estenda a sua mão, e tome também da árvore da vida, e coma, e viva eternamente, o Senhor Deus, pois, o lançou fora do jardim do Éden, para lavrar a terra, de que fora tomado.', 'Gênesis 3:22-23', 'Gênesis', 3, 22, 23),
  ('pecado', 'E, tomando o cálice e dando graças, deu-lho, dizendo: Bebei dele todos. Porque isto é o meu sangue, o sangue do Novo Testamento, que é derramado por muitos, para remissão dos pecados.', 'Mateus 26:27-28', 'Mateus', 26, 27, 28),
  ('pecado', 'Sabendo isto: que a lei não é feita para o justo, mas para os injustos e obstinados, para os ímpios e pecadores, para os profanos e irreligiosos, para os parricidas e matricidas, para os homicidas, para os fornicadores, para os sodomitas, para os roubadores de homens, para os mentirosos, para os perjuros e para o que for contrário à sã doutrina, conforme o evangelho da glória do Deus bem-aventurado, que me foi confiado.', '1 Timóteo 1:9-11', '1 Timóteo', 1, 9, 11),
  ('pecado', 'O publicano, porém, estando em pé, de longe, nem ainda queria levantar os olhos ao céu, mas batia no peito, dizendo: Ó Deus, tem misericórdia de mim, pecador!', 'Lucas 18:13', 'Lucas', 18, 13, NULL),
  ('pecado', 'A este dão testemunho todos os profetas, de que todos os que nele creem receberão o perdão dos pecados pelo seu nome.', 'Atos 10:43', 'Atos', 10, 43, NULL),
  ('pecado', 'Na verdade, não há homem justo sobre a terra, que faça bem e nunca peque.', 'Eclesiastes 7:20', 'Eclesiastes', 7, 20, NULL),
  ('pecado', 'E Deus viu as obras deles, como se converteram do seu mau caminho; e Deus se arrependeu do mal que tinha dito lhes faria e não o fez.', 'Jonas 3:10', 'Jonas', 3, 10, NULL),
  ('pecado', 'Aquele, pois, que sabe fazer o bem e o não faz comete pecado.', 'Tiago 4:17', 'Tiago', 4, 17, NULL),
  ('pensamentos', 'Sonda-me, ó Deus, e conhece o meu coração; prova-me e conhece os meus pensamentos. E vê se há em mim algum caminho mau e guia-me pelo caminho eterno.', 'Salmo 139:23-24', 'Salmo', 139, 23, 24),
  ('pensamentos', 'E dizia: O que sai do homem, isso é que contamina o homem. Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios, os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura. Todos estes males procedem de dentro e contaminam o homem.', 'Marcos 7:20-23', 'Marcos', 7, 20, 23),
  ('pensamentos', 'Porque os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos, os meus caminhos, diz o Senhor.', 'Isaías 55:8', 'Isaías', 55, 8, NULL),
  ('pensamentos', 'Confia ao Senhor as tuas obras, e teus pensamentos serão estabelecidos.', 'Provérbios 16:3', 'Provérbios', 16, 3, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('pensamentos', 'Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as saídas da vida.', 'Provérbios 4:23', 'Provérbios', 4, 23, NULL),
  ('pensamentos', 'E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.', 'Romanos 12:2', 'Romanos', 12, 2, NULL),
  ('pensamentos', 'Quanto ao mais, irmãos, tudo o que é verdadeiro, tudo o que é honesto, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se há alguma virtude, e se há algum louvor, nisso pensai.', 'Filipenses 4:8', 'Filipenses', 4, 8, NULL),
  ('pensamentos', 'Senhor, tu me sondaste e me conheces. Tu conheces o meu assentar e o meu levantar; de longe entendes o meu pensamento.', 'Salmo 139:1-2', 'Salmo', 139, 1, 2),
  ('pensamentos', 'Todo caminho do homem é reto aos seus olhos, mas o Senhor sonda os corações.', 'Provérbios 21:2', 'Provérbios', 21, 2, NULL),
  ('pensamentos', 'Porque a palavra de Deus é viva, e eficaz, e mais penetrante do que qualquer espada de dois gumes, e penetra até à divisão da alma, e do espírito, e das juntas e medulas, e é apta para discernir os pensamentos e intenções do coração.', 'Hebreus 4:12', 'Hebreus', 4, 12, NULL),
  ('pensamentos', 'Pondera a vereda de teus pés, e todos os teus caminhos sejam bem-ordenados!', 'Provérbios 4:26', 'Provérbios', 4, 26, NULL),
  ('pensamentos', 'Porque qual dos homens sabe as coisas do homem, senão o espírito do homem, que nele está? Assim também ninguém sabe as coisas de Deus, senão o Espírito de Deus.', '1 Coríntios 2:11', '1 Coríntios', 2, 11, NULL),
  ('pensamentos', 'Rogo-vos, porém, irmãos, pelo nome de nosso Senhor Jesus Cristo, que digais todos uma mesma coisa e que não haja entre vós dissensões; antes, sejais unidos, em um mesmo sentido e em um mesmo parecer.', '1 Coríntios 1:10', '1 Coríntios', 1, 10, NULL),
  ('pensamentos', 'Há caminho que ao homem parece direito, mas o fim dele são os caminhos da morte.', 'Provérbios 14:12', 'Provérbios', 14, 12, NULL),
  ('pensamentos', 'Ninguém se engane a si mesmo: se alguém dentre vós se tem por sábio neste mundo, faça-se louco para ser sábio.', '1 Coríntios 3:18', '1 Coríntios', 3, 18, NULL),
  ('pensamentos', 'Portanto, cingindo os lombos do vosso entendimento, sede sóbrios e esperai inteiramente na graça que se vos ofereceu na revelação de Jesus Cristo.', '1 Pedro 1:13', '1 Pedro', 1, 13, NULL),
  ('pensamentos', 'Fiz concerto com os meus olhos; como, pois, os fixaria numa virgem?', 'Jó 31:1', 'Jó', 31, 1, NULL),
  ('pensamentos', 'E, orando, não useis de vãs repetições, como os gentios, que pensam que, por muito falarem, serão ouvidos.', 'Mateus 6:7', 'Mateus', 6, 7, NULL),
  ('pensamentos', 'Deixe o ímpio o seu caminho, e o homem maligno, os seus pensamentos e se converta ao Senhor, que se compadecerá dele; torne para o nosso Deus, porque grandioso é em perdoar.', 'Isaías 55:7', 'Isaías', 55, 7, NULL),
  ('pensamentos', 'Por isso, vos digo: não andeis cuidadosos quanto à vossa vida, pelo que haveis de comer ou pelo que haveis de beber; nem quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o mantimento, e o corpo, mais do que a vestimenta?', 'Mateus 6:25', 'Mateus', 6, 25, NULL),
  ('pensamentos', 'Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos, segundo o poder que em nós opera, a esse glória na igreja, por Jesus Cristo, em todas as gerações, para todo o sempre. Amém!', 'Efésios 3:20-21', 'Efésios', 3, 20, 21),
  ('pensamentos', 'Porque, pela graça que me é dada, digo a cada um dentre vós que não saiba mais do que convém saber, mas que saiba com temperança, conforme a medida da fé que Deus repartiu a cada um.', 'Romanos 12:3', 'Romanos', 12, 3, NULL),
  ('pensamentos', 'Não estejais apreensivos pela vossa vida, sobre o que comereis, nem pelo corpo, sobre o que vestireis. Mais é a vida do que o sustento, e o corpo, mais do que as vestes.', 'Lucas 12:22b-23', 'Lucas 12:22b-23', NULL, NULL, NULL),
  ('pensamentos', 'Porque os que são segundo a carne inclinam-se para as coisas da carne; mas os que são segundo o Espírito, para as coisas do Espírito.', 'Romanos 8:5', 'Romanos', 8, 5, NULL),
  ('pentecostes', 'Cumprindo-se o dia de Pentecostes, estavam todos reunidos no mesmo lugar; e, de repente, veio do céu um som, como de um vento veemente e impetuoso, e encheu toda a casa em que estavam assentados.', 'Atos 2:1-2', 'Atos', 2, 1, 2),
  ('pentecostes', 'E foram vistas por eles línguas repartidas, como que de fogo, as quais pousaram sobre cada um deles. E todos foram cheios do Espírito Santo e começaram a falar em outras línguas, conforme o Espírito Santo lhes concedia que falassem.', 'Atos 2:3-4', 'Atos', 2, 3, 4),
  ('pentecostes', 'E, tendo eles orado, moveu-se o lugar em que estavam reunidos; e todos foram cheios do Espírito Santo e anunciavam com ousadia a palavra de Deus.', 'Atos 4:31', 'Atos', 4, 31, NULL),
  ('pentecostes', 'Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas tanto em Jerusalém como em toda a Judeia e Samaria e até aos confins da terra.', 'Atos 1:8', 'Atos', 1, 8, NULL),
  ('pentecostes', 'Mas aquele Consolador, o Espírito Santo, que o Pai enviará em meu nome, vos ensinará todas as coisas e vos fará lembrar de tudo quanto vos tenho dito.', 'João 14:26', 'João', 14, 26, NULL),
  ('pentecostes', 'E, quando comecei a falar, caiu sobre eles o Espírito Santo, como também sobre nós ao princípio.', 'Atos 11:15', 'Atos', 11, 15, NULL),
  ('pentecostes', 'Até que se derrame sobre nós o Espírito lá do alto; então, o deserto se tornará em campo fértil, e o campo fértil será reputado por um bosque.', 'Isaías 32:15', 'Isaías', 32, 15, NULL),
  ('pentecostes', 'E eu rogarei ao Pai, e ele vos dará outro Consolador, para que fique convosco para sempre.', 'João 14:16', 'João', 14, 16, NULL),
  ('pentecostes', 'E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo.', 'Atos 2:38', 'Atos', 2, 38, NULL),
  ('pentecostes', 'De sorte que, exaltado pela destra de Deus e tendo recebido do Pai a promessa do Espírito Santo, derramou isto que vós agora vedes e ouvis.', 'Atos 2:33', 'Atos', 2, 33, NULL),
  ('pentecostes', 'Todavia, digo-vos a verdade: que vos convém que eu vá, porque, se eu não for, o Consolador não virá a vós; mas, se eu for, enviar-vo-lo-ei.', 'João 16:7', 'João', 16, 7, NULL),
  ('perdao', 'O que encobre a transgressão busca a amizade, mas o que renova a questão separa os maiores amigos.', 'Provérbios 17:9', 'Provérbios', 17, 9, NULL),
  ('perdao', 'Antes, sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.', 'Efésios 4:32', 'Efésios', 4, 32, NULL),
  ('perdao', 'Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós.', 'Mateus 6:14', 'Mateus', 6, 14, NULL),
  ('perdao', 'Suportando-vos uns aos outros e perdoando-vos uns aos outros, se algum tiver queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também.', 'Colossenses 3:13', 'Colossenses', 3, 13, NULL),
  ('perdao', 'E se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar a minha face, e se converter dos seus maus caminhos, então, eu ouvirei dos céus, e perdoarei os seus pecados, e sararei a sua terra.', '2 Crônicas 7:14', '2 Crônicas', 7, 14, NULL),
  ('perdao', 'Não julgueis, e não sereis julgados; não condeneis, e não sereis condenados; soltai, e soltar-vos-ão.', 'Lucas 6:37', 'Lucas', 6, 37, NULL),
  ('perdao', 'Então, Pedro, aproximando-se dele, disse: Senhor, até quantas vezes pecará meu irmão contra mim, e eu lhe perdoarei? Até sete? Jesus lhe disse: Não te digo que até sete, mas até setenta vezes sete.', 'Mateus 18:21-22', 'Mateus', 18, 21, 22),
  ('perdao', 'O que encobre as suas transgressões nunca prosperará; mas o que as confessa e deixa alcançará misericórdia.', 'Provérbios 28:13', 'Provérbios', 28, 13, NULL),
  ('perdao', 'Pois tu, Senhor, és bom, e pronto a perdoar, e abundante em benignidade para com todos os que te invocam.', 'Salmo 86:5', 'Salmo', 86, 5, NULL),
  ('perdao', 'E, quando estiverdes orando, perdoai, se tendes alguma coisa contra alguém, para que vosso Pai, que está nos céus, vos perdoe as vossas ofensas.', 'Marcos 11:25', 'Marcos', 11, 25, NULL),
  ('perdao', 'Quem, ó Deus, é semelhante a ti, que perdoas a iniquidade e que te esqueces da rebelião do restante da tua herança? O Senhor não retém a sua ira para sempre, porque tem prazer na benignidade.', 'Miqueias 7:18', 'Miqueias', 7, 18, NULL),
  ('perdao', 'Porque o Senhor, vosso Deus, é piedoso e misericordioso e não desviará de vós o rosto, se vos converterdes a ele.', '2 Crônicas 30:9b', '2 Crônicas 30:9b', NULL, NULL, NULL),
  ('perdao', 'Seja-vos, pois, notório, varões irmãos, que por este se vos anuncia a remissão dos pecados. E de tudo o que, pela lei de Moisés, não pudestes ser justificados, por ele é justificado todo aquele que crê.', 'Atos 13:38-39', 'Atos', 13, 38, 39),
  ('perdao', 'E ele é a propiciação pelos nossos pecados e não somente pelos nossos, mas também pelos de todo o mundo.', '1 João 2:2', '1 João', 2, 2, NULL),
  ('perdao', 'Confessei-te o meu pecado e a minha maldade não encobri; dizia eu: Confessarei ao Senhor as minhas transgressões; e tu perdoaste a maldade do meu pecado. (Selá)', 'Salmo 32:5', 'Salmo', 32, 5, NULL),
  ('perdao', 'Perdoa-nos as nossas dívidas, assim como nós perdoamos aos nossos devedores.', 'Mateus 6:12', 'Mateus', 6, 12, NULL),
  ('perdao', 'Em quem temos a redenção pelo seu sangue, a remissão das ofensas, segundo as riquezas da sua graça.', 'Efésios 1:7', 'Efésios', 1, 7, NULL),
  ('perdao', 'E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor, vosso Deus; porque ele é misericordioso, e compassivo, e tardio em irar-se, e grande em beneficência e se arrepende do mal.', 'Joel 2:13', 'Joel', 2, 13, NULL),
  ('perdao', 'E, se teu irmão pecar contra ti, repreende-o; e, se ele se arrepender, perdoa-lhe; e, se pecar contra ti sete vezes no dia e sete vezes no dia vier ter contigo, dizendo: Arrependo-me, perdoa-lhe.', 'Lucas 17:3b-4', 'Lucas 17:3b-4', NULL, NULL, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('perdao', 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, e venham, assim, os tempos do refrigério pela presença do Senhor.', 'Atos 3:19', 'Atos', 3, 19, NULL),
  ('perdao', 'E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo.', 'Atos 2:38', 'Atos', 2, 38, NULL),
  ('perdao', 'Se, porém, não perdoardes aos homens as suas ofensas, também vosso Pai vos não perdoará as vossas ofensas.', 'Mateus 6:15', 'Mateus', 6, 15, NULL),
  ('perdao', 'Porque serei misericordioso para com as suas iniquidades e de seus pecados e de suas prevaricações não me lembrarei mais.', 'Hebreus 8:12', 'Hebreus', 8, 12, NULL),
  ('perdao', 'Está alguém entre vós doente? Chame os presbíteros da igreja, e orem sobre ele, ungindo-o com azeite em nome do Senhor; e a oração da fé salvará o doente, e o Senhor o levantará; e, se houver cometido pecados, ser-lhe-ão perdoados.', 'Tiago 5:14-15', 'Tiago', 5, 14, 15),
  ('perdao', 'Deixe o ímpio o seu caminho, e o homem maligno, os seus pensamentos e se converta ao Senhor, que se compadecerá dele; torne para o nosso Deus, porque grandioso é em perdoar.', 'Isaías 55:7', 'Isaías', 55, 7, NULL),
  ('perdao', 'Mas Deus, não tendo em conta os tempos da ignorância, anuncia agora a todos os homens, em todo lugar, que se arrependam.', 'Atos 17:30', 'Atos', 17, 30, NULL),
  ('perdao', 'Volta, ó rebelde Israel, diz o Senhor, e não farei cair a minha ira sobre vós; porque benigno sou, diz o Senhor, e não conservarei para sempre a minha ira.', 'Jeremias 3:12b', 'Jeremias 3:12b', NULL, NULL, NULL),
  ('perdao', 'Mas, pela tua grande misericórdia, não os destruíste nem desamparaste; porque és um Deus clemente e misericordioso.', 'Neemias 9:31', 'Neemias', 9, 31, NULL),
  ('perdao', 'Bem-aventurado aquele cuja transgressão é perdoada, e cujo pecado é coberto.', 'Salmo 32:1', 'Salmo', 32, 1, NULL),
  ('perdao', 'Jesus, porém, ouvindo, disse-lhes: Não necessitam de médico os sãos, mas sim, os doentes.', 'Mateus 9:12', 'Mateus', 9, 12, NULL),
  ('perdao', 'Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor, em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados.', 'Colossenses 1:13-14', 'Colossenses', 1, 13, 14),
  ('perdao', 'Vinde, então, e argui-me, diz o Senhor; ainda que os vossos pecados sejam como a escarlata, eles se tornarão brancos como a neve; ainda que sejam vermelhos como o carmesim, se tornarão como a branca lã.', 'Isaías 1:18', 'Isaías', 1, 18, NULL),
  ('perdao', 'E, se qualquer disser alguma palavra contra o Filho do Homem, ser-lhe-á perdoado, mas, se alguém falar contra o Espírito Santo, não lhe será perdoado, nem neste século nem no futuro.', 'Mateus 12:32', 'Mateus', 12, 32, NULL),
  ('perdao', 'Portanto, eu vos digo: todo pecado e blasfêmia se perdoará aos homens, mas a blasfêmia contra o Espírito não será perdoada aos homens.', 'Mateus 12:31', 'Mateus', 12, 31, NULL),
  ('perdao', 'Tornará a apiedar-se de nós, subjugará as nossas iniquidades e lançará todos os nossos pecados nas profundezas do mar.', 'Miqueias 7:19', 'Miqueias', 7, 19, NULL),
  ('perdao', 'E dizia Jesus: Pai, perdoa-lhes, porque não sabem o que fazem. E, repartindo as suas vestes, lançaram sortes.', 'Lucas 23:34', 'Lucas', 23, 34, NULL),
  ('perdao', 'E, tomando o cálice e dando graças, deu-lho, dizendo: Bebei dele todos. Porque isto é o meu sangue, o sangue do Novo Testamento, que é derramado por muitos, para remissão dos pecados.', 'Mateus 26:27-28', 'Mateus', 26, 27, 28),
  ('perdao', 'Tomai convosco palavras e convertei-vos ao Senhor; dizei-lhe: Expulsa toda a iniquidade e recebe o bem; e daremos como bezerros os sacrifícios dos nossos lábios.', 'Oseias 14:2', 'Oseias', 14, 2, NULL),
  ('perdao', 'E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão.', 'Hebreus 9:22', 'Hebreus', 9, 22, NULL),
  ('perdao', 'A este dão testemunho todos os profetas, de que todos os que nele creem receberão o perdão dos pecados pelo seu nome.', 'Atos 10:43', 'Atos', 10, 43, NULL),
  ('perdao', 'E Deus viu as obras deles, como se converteram do seu mau caminho; e Deus se arrependeu do mal que tinha dito lhes faria e não o fez.', 'Jonas 3:10', 'Jonas', 3, 10, NULL),
  ('perseguicao', 'E também todos os que piamente querem viver em Cristo Jesus padecerão perseguições.', '2 Timóteo 3:12', '2 Timóteo', 3, 12, NULL),
  ('perseguicao', 'Bem-aventurados os que sofrem perseguição por causa da justiça, porque deles é o Reino dos céus.', 'Mateus 5:10', 'Mateus', 5, 10, NULL),
  ('perseguicao', 'Pelo que sinto prazer nas fraquezas, nas injúrias, nas necessidades, nas perseguições, nas angústias, por amor de Cristo. Porque, quando estou fraco, então, sou forte.', '2 Coríntios 12:10', '2 Coríntios', 12, 10, NULL),
  ('perseguicao', 'Se o mundo vos aborrece, sabei que, primeiro do que a vós, me aborreceu a mim.', 'João 15:18', 'João', 15, 18, NULL),
  ('perseguicao', 'Bem-aventurados sereis quando os homens vos aborrecerem, e quando vos separarem, e vos injuriarem, e rejeitarem o vosso nome como mau, por causa do Filho do Homem.', 'Lucas 6:22', 'Lucas', 6, 22, NULL),
  ('perseguicao', 'Quem nos separará do amor de Cristo? A tribulação, ou a angústia, ou a perseguição, ou a fome, ou a nudez, ou o perigo, ou a espada?', 'Romanos 8:35', 'Romanos', 8, 35, NULL),
  ('perseguicao', 'Bem-aventurados sois vós quando vos injuriarem, e perseguirem, e, mentindo, disserem todo o mal contra vós, por minha causa.', 'Mateus 5:11', 'Mateus', 5, 11, NULL),
  ('perseguicao', 'Eu, porém, vos digo: Amai a vossos inimigos, bendizei os que vos maldizem, fazei bem aos que vos odeiam e orai pelos que vos maltratam e vos perseguem.', 'Mateus 5:44', 'Mateus', 5, 44, NULL),
  ('perseguicao', 'E Jesus, respondendo, disse: Em verdade vos digo que ninguém há, que tenha deixado casa, ou irmãos, ou irmãs, ou pai, ou mãe, ou mulher, ou filhos, ou campos, por amor de mim e do evangelho, que não receba cem vezes tanto, já neste tempo, em casas, e irmãos, e irmãs, e mães, e filhos, e campos, com perseguições, e, no século futuro, a vida eterna.', 'Marcos 10:29-30', 'Marcos', 10, 29, 30),
  ('perseguicao', 'Os meus tempos estão nas tuas mãos; livra-me das mãos dos meus inimigos e dos que me perseguem.', 'Salmo 31:15', 'Salmo', 31, 15, NULL),
  ('perseguicao', 'Abençoai aos que vos perseguem; abençoai e não amaldiçoeis.', 'Romanos 12:14', 'Romanos', 12, 14, NULL),
  ('perseguicao', 'Sede sóbrios, vigiai, porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar.', '1 Pedro 5:8', '1 Pedro', 5, 8, NULL),
  ('perseguicao', 'Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo; a tua vara e o teu cajado me consolam.', 'Salmo 23:4', 'Salmo', 23, 4, NULL),
  ('perseguicao', 'E caí por terra e ouvi uma voz que me dizia: Saulo, Saulo, por que me persegues?', 'Atos 22:7', 'Atos', 22, 7, NULL),
  ('planejamento', 'Confia ao Senhor as tuas obras, e teus pensamentos serão estabelecidos.', 'Provérbios 16:3', 'Provérbios', 16, 3, NULL),
  ('planejamento', 'Pois qual de vós, querendo edificar uma torre, não se assenta primeiro a fazer as contas dos gastos, para ver se tem com que a acabar?', 'Lucas 14:28', 'Lucas', 14, 28, NULL),
  ('planejamento', 'Porque eu bem sei os pensamentos que penso de vós, diz o Senhor; pensamentos de paz e não de mal, para vos dar o fim que esperais.', 'Jeremias 29:11', 'Jeremias', 29, 11, NULL),
  ('planejamento', 'O coração do homem considera o seu caminho, mas o Senhor lhe dirige os passos.', 'Provérbios 16:9', 'Provérbios', 16, 9, NULL),
  ('planejamento', 'Conceda-te conforme o teu coração e cumpra todo o teu desígnio.', 'Salmo 20:4', 'Salmo', 20, 4, NULL),
  ('planejamento', 'Onde não há conselho os projetos saem vãos, mas, com a multidão de conselheiros, se confirmarão.', 'Provérbios 15:22', 'Provérbios', 15, 22, NULL),
  ('planejamento', 'Muitos propósitos há no coração do homem, mas o conselho do Senhor permanecerá.', 'Provérbios 19:21', 'Provérbios', 19, 21, NULL),
  ('planejamento', 'Faze-me ouvir a tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti levanto a minha alma.', 'Salmo 143:8', 'Salmo', 143, 8, NULL),
  ('planejamento', 'Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu.', 'Eclesiastes 3:1', 'Eclesiastes', 3, 1, NULL),
  ('planejamento', 'Porque os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos, os meus caminhos, diz o Senhor.', 'Isaías 55:8', 'Isaías', 55, 8, NULL),
  ('planejamento', 'Não te canses para enriqueceres; dá de mão à tua própria sabedoria.', 'Provérbios 23:4', 'Provérbios', 23, 4, NULL),
  ('planejamento', 'Ensina-nos a contar os nossos dias, de tal maneira que alcancemos coração sábio.', 'Salmo 90:12', 'Salmo', 90, 12, NULL),
  ('planejamento', 'Porque, assim como os céus são mais altos do que a terra, assim são os meus caminhos mais altos do que os vossos caminhos, e os meus pensamentos, mais altos do que os vossos pensamentos.', 'Isaías 55:9', 'Isaías', 55, 9, NULL),
  ('planejamento', 'Até isto procede do Senhor dos Exércitos, porque é maravilhoso em conselho e grande em obra.', 'Isaías 28:29', 'Isaías', 28, 29, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('planejamento', 'Mas Deus no-las revelou pelo seu Espírito; porque o Espírito penetra todas as coisas, ainda as profundezas de Deus.', '1 Coríntios 2:10', '1 Coríntios', 2, 10, NULL),
  ('planejamento', 'Não tenhas inveja do homem violento, nem escolhas nenhum de seus caminhos. Porque o perverso é abominação para o Senhor, mas com os sinceros está o seu segredo.', 'Provérbios 3:31-32', 'Provérbios', 3, 31, 32),
  ('planejamento', 'Certamente o Senhor Jeová não fará coisa alguma, sem ter revelado o seu segredo aos seus servos, os profetas.', 'Amós 3:7', 'Amós', 3, 7, NULL),
  ('planejamento', 'Todos os caminhos do homem são limpos aos seus olhos, mas o Senhor pesa os espíritos.', 'Provérbios 16:2', 'Provérbios', 16, 2, NULL),
  ('pobreza', 'Disse-lhe Jesus: Se queres ser perfeito, vai, vende tudo o que tens, dá-o aos pobres e terás um tesouro no céu; e vem e segue-me.', 'Mateus 19:21', 'Mateus', 19, 21, NULL),
  ('pobreza', 'Sei estar abatido e sei também ter abundância; em toda a maneira e em todas as coisas, estou instruído, tanto a ter fartura como a ter fome, tanto a ter abundância como a padecer necessidade.', 'Filipenses 4:12', 'Filipenses', 4, 12, NULL),
  ('pobreza', 'Abre a tua boca, julga retamente e faze justiça aos pobres e aos necessitados.', 'Provérbios 31:9', 'Provérbios', 31, 9, NULL),
  ('pobreza', 'Em todo trabalho há proveito, mas a palavra dos lábios só encaminha para a pobreza.', 'Provérbios 14:23', 'Provérbios', 14, 23, NULL),
  ('pobreza', 'Como contristados, mas sempre alegres; como pobres, mas enriquecendo a muitos; como nada tendo e possuindo tudo.', '2 Coríntios 6:10', '2 Coríntios', 6, 10, NULL),
  ('pobreza', 'Defendei o pobre e o órfão; fazei justiça ao aflito e necessitado.', 'Salmo 82:3', 'Salmo', 82, 3, NULL),
  ('pobreza', 'O Senhor empobrece e enriquece; abaixa e também exalta.', '1 Samuel 2:7', '1 Samuel', 2, 7, NULL),
  ('pobreza', 'E, respondendo ele, disse-lhes: Quem tiver duas túnicas, que reparta com o que não tem, e quem tiver alimentos, que faça da mesma maneira.', 'Lucas 3:11', 'Lucas', 3, 11, NULL),
  ('pobreza', 'Assim falou o Senhor dos Exércitos, dizendo: Executai juízo verdadeiro, mostrai piedade e misericórdia cada um a seu irmão; e não oprimais a viúva, nem o órfão, nem o estrangeiro, nem o pobre, nem intente o mal cada um contra o seu irmão, no seu coração.', 'Zacarias 7:9-10', 'Zacarias', 7, 9, 10),
  ('pobreza', 'Clamou este pobre, e o Senhor o ouviu; e o salvou de todas as suas angústias.', 'Salmo 34:6', 'Salmo', 34, 6, NULL),
  ('pobreza', 'O rico domina sobre os pobres, e o que toma emprestado é servo do que empresta.', 'Provérbios 22:7', 'Provérbios', 22, 7, NULL),
  ('pobreza', 'Quem nos separará do amor de Cristo? A tribulação, ou a angústia, ou a perseguição, ou a fome, ou a nudez, ou o perigo, ou a espada?', 'Romanos 8:35', 'Romanos', 8, 35, NULL),
  ('pobreza', 'Afasta de mim a vaidade e a palavra mentirosa; não me dês nem a pobreza nem a riqueza; mantém-me do pão da minha porção acostumada.', 'Provérbios 30:8', 'Provérbios', 30, 8, NULL),
  ('pobreza', 'O resgate da vida de cada um são as suas riquezas, mas o pobre não ouve as ameaças.', 'Provérbios 13:8', 'Provérbios', 13, 8, NULL),
  ('pobreza', 'Porque eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse. A bênção do que ia perecendo vinha sobre mim, e eu fazia que rejubilasse o coração da viúva.', 'Jó 29:12-13', 'Jó', 29, 12, 13),
  ('pobreza', 'O desejo do homem é a sua beneficência; mas o pobre é melhor do que o mentiroso.', 'Provérbios 19:22', 'Provérbios', 19, 22, NULL),
  ('pobreza', 'O Espírito do Senhor é sobre mim, pois que me ungiu para evangelizar os pobres, enviou-me a curar os quebrantados do coração.', 'Lucas 4:18', 'Lucas', 4, 18, NULL),
  ('pobreza', 'E ainda que distribuísse toda a minha fortuna para sustento dos pobres, e ainda que entregasse o meu corpo para ser queimado, e não tivesse amor, nada disso me aproveitaria.', '1 Coríntios 13:3', '1 Coríntios', 13, 3, NULL),
  ('pobreza', 'O Espírito do Senhor Jeová está sobre mim, porque o Senhor me ungiu para pregar boas-novas aos mansos; enviou-me a restaurar os contritos de coração, a proclamar liberdade aos cativos e a abertura de prisão aos presos.', 'Isaías 61:1', 'Isaías', 61, 1, NULL),
  ('pobreza', 'Levanta-te, Senhor! Ó Deus, levanta a tua mão; não te esqueças dos necessitados!', 'Salmo 10:12', 'Salmo', 10, 12, NULL),
  ('preocupacao', 'Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.', 'Filipenses 4:6-7', 'Filipenses', 4, 6, 7),
  ('preocupacao', 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te esforço, e te ajudo, e te sustento com a destra da minha justiça.', 'Isaías 41:10', 'Isaías', 41, 10, NULL),
  ('preocupacao', 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.', '1 Pedro 5:7', '1 Pedro', 5, 7, NULL),
  ('preocupacao', 'Por isso, vos digo: não andeis cuidadosos quanto à vossa vida, pelo que haveis de comer ou pelo que haveis de beber; nem quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o mantimento, e o corpo, mais do que a vestimenta?', 'Mateus 6:25', 'Mateus', 6, 25, NULL),
  ('preocupacao', 'Não vos inquieteis, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal.', 'Mateus 6:34', 'Mateus', 6, 34, NULL),
  ('preocupacao', 'Multiplicando-se dentro de mim os meus cuidados, as tuas consolações reanimaram a minha alma.', 'Salmo 94:19', 'Salmo', 94, 19, NULL),
  ('preocupacao', 'Não se turbe o vosso coração; credes em Deus, crede também em mim.', 'João 14:1', 'João', 14, 1, NULL),
  ('preocupacao', 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.', 'João 14:27', 'João', 14, 27, NULL),
  ('preocupacao', 'A solicitude no coração do homem o abate, mas uma boa palavra o alegra.', 'Provérbios 12:25', 'Provérbios', 12, 25, NULL),
  ('preocupacao', 'Porque, na muita sabedoria, há muito enfado; e o que aumenta em ciência aumenta em trabalho.', 'Eclesiastes 1:18', 'Eclesiastes', 1, 18, NULL),
  ('preocupacao', 'Senhor, diante de ti está todo o meu desejo, e o meu gemido não te é oculto.', 'Salmo 38:9', 'Salmo', 38, 9, NULL),
  ('preocupacao', 'Não estejais apreensivos pela vossa vida, sobre o que comereis, nem pelo corpo, sobre o que vestireis. Mais é a vida do que o sustento, e o corpo, mais do que as vestes.', 'Lucas 12:22b-23', 'Lucas 12:22b-23', NULL, NULL, NULL),
  ('preocupacao', 'E Deus é poderoso para tornar abundante em vós toda graça, a fim de que, tendo sempre, em tudo, toda suficiência, superabundeis em toda boa obra.', '2 Coríntios 9:8', '2 Coríntios', 9, 8, NULL),
  ('preocupacao', 'Afasta, pois, a ira do teu coração e remove da tua carne o mal, porque a adolescência e a juventude são vaidade.', 'Eclesiastes 11:10', 'Eclesiastes', 11, 10, NULL),
  ('preocupacao', 'Quando, pois, vos conduzirem para vos entregarem, não estejais solícitos de antemão pelo que haveis de dizer; mas o que vos for dado naquela hora, isso falai; porque não sois vós os que falais, mas o Espírito Santo.', 'Marcos 13:11', 'Marcos', 13, 11, NULL),
  ('preocupacao', 'E o que foi semeado entre espinhos é o que ouve a palavra, mas os cuidados deste mundo e a sedução das riquezas sufocam a palavra, e fica infrutífera.', 'Mateus 13:22', 'Mateus', 13, 22, NULL),
  ('preocupacao', 'E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles e será o seu Deus. E Deus limpará de seus olhos toda lágrima, e não haverá mais morte, nem pranto, nem clamor, nem dor, porque já as primeiras coisas são passadas.', 'Apocalipse 21:3-4', 'Apocalipse', 21, 3, 4),
  ('preocupacao', 'Considerai os corvos, que nem semeiam, nem segam, nem têm despensa nem celeiro, e Deus os alimenta; quanto mais valeis vós do que as aves?', 'Lucas 12:24', 'Lucas', 12, 24, NULL),
  ('preocupacao', 'Então, Jó se levantou, e rasgou o seu manto, e rapou a sua cabeça, e se lançou em terra, e adorou, e disse: Nu saí do ventre de minha mãe e nu tornarei para lá; o Senhor o deu e o Senhor o tomou; bendito seja o nome do Senhor.', 'Jó 1:20-21', 'Jó', 1, 20, 21),
  ('preocupacao', 'Porque eu sei que o meu Redentor vive, e que por fim se levantará sobre a terra.', 'Jó 19:25', 'Jó', 19, 25, NULL),
  ('preocupacao', 'Porque a tristeza segundo Deus opera arrependimento para a salvação, da qual ninguém se arrepende; mas a tristeza do mundo opera a morte.', '2 Coríntios 7:10', '2 Coríntios', 7, 10, NULL),
  ('profecia', 'Examinai tudo. Retende o bem. Abstende-vos de toda aparência do mal.', '1 Tessalonicenses 5:21-22', '1 Tessalonicenses', 5, 21, 22),
  ('profecia', 'Porque a profecia nunca foi produzida por vontade de homem algum, mas os homens santos de Deus falaram inspirados pelo Espírito Santo.', '2 Pedro 1:21', '2 Pedro', 1, 21, NULL),
  ('profecia', 'E ainda que tivesse o dom de profecia, e conhecesse todos os mistérios e toda a ciência, e ainda que tivesse toda a fé, de maneira tal que transportasse os montes, e não tivesse amor, nada seria.', '1 Coríntios 13:2', '1 Coríntios', 13, 2, NULL),
  ('profecia', 'Amados, não creiais em todo espírito, mas provai se os espíritos são de Deus, porque já muitos falsos profetas se têm levantado no mundo.', '1 João 4:1', '1 João', 4, 1, NULL),
  ('profecia', 'Certamente o Senhor Jeová não fará coisa alguma, sem ter revelado o seu segredo aos seus servos, os profetas.', 'Amós 3:7', 'Amós', 3, 7, NULL);

