-- Parte 11: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('profecia', 'Volta e dize a Ezequias, chefe do meu povo: Assim diz o Senhor, Deus de Davi, teu pai: Ouvi a tua oração e vi as tuas lágrimas; eis que eu te sararei; ao terceiro dia subirás à Casa do Senhor.', '2 Reis 20:5', '2 Reis', 20, 5, NULL),
  ('profecia', 'Acautelai-vos, porém, dos falsos profetas, que vêm até vós vestidos como ovelhas, mas interiormente são lobos devoradores.', 'Mateus 7:15', 'Mateus', 7, 15, NULL),
  ('profecia', 'E se disseres no teu coração: Como conheceremos a palavra que o Senhor não falou? Quando o tal profeta falar em nome do Senhor, e tal palavra se não cumprir, nem suceder assim, esta é palavra que o Senhor não falou; com soberba a falou o tal profeta; não tenhas temor dele.', 'Deuteronômio 18:21-22', 'Deuteronômio', 18, 21, 22),
  ('profecia', 'E os que ouviram foram batizados em nome do Senhor Jesus. E, impondo-lhes Paulo as mãos, veio sobre eles o Espírito Santo; e falavam línguas e profetizavam.', 'Atos 19:5-6', 'Atos', 19, 5, 6),
  ('profecia', 'Filhinhos, sois de Deus e já os tendes vencido, porque maior é o que está em vós do que o que está no mundo.', '1 João 4:4', '1 João', 4, 4, NULL),
  ('profecia', 'Assim que já não sois estrangeiros, nem forasteiros, mas concidadãos dos Santos e da família de Deus; edificados sobre o fundamento dos apóstolos e dos profetas, de que Jesus Cristo é a principal pedra da esquina.', 'Efésios 2:19-20', 'Efésios', 2, 19, 20),
  ('profecia', 'Portanto, tudo o que vós quereis que os homens vos façam, fazei-lho também vós, porque esta é a lei e os profetas.', 'Mateus 7:12', 'Mateus', 7, 12, NULL),
  ('profecia', 'Portanto, o mesmo Senhor vos dará um sinal: eis que uma virgem conceberá, e dará à luz um filho, e será o seu nome Emanuel.', 'Isaías 7:14', 'Isaías', 7, 14, NULL),
  ('profecia', 'Mas, agora, se manifestou, sem a lei, a justiça de Deus, tendo o testemunho da Lei e dos Profetas, isto é, a justiça de Deus pela fé em Jesus Cristo para todos e sobre todos os que creem; porque não há diferença.', 'Romanos 3:21-22', 'Romanos', 3, 21, 22),
  ('profecia', 'Alegra-te muito, ó filha de Sião; exulta, ó filha de Jerusalém; eis que o teu rei virá a ti, justo e Salvador, pobre e montado sobre um jumento, sobre um asninho, filho de jumenta.', 'Zacarias 9:9', 'Zacarias', 9, 9, NULL),
  ('profecia', 'Não cuideis que vim destruir a lei ou os profetas; não vim ab-rogar, mas cumprir.', 'Mateus 5:17', 'Mateus', 5, 17, NULL),
  ('profecia', 'Tudo isso aconteceu para que se cumprisse o que foi dito da parte do Senhor pelo profeta, que diz: Eis que a virgem conceberá e dará à luz um filho, e ele será chamado pelo nome de Emanuel. (Emanuel traduzido é: Deus conosco).', 'Mateus 1:22-23', 'Mateus', 1, 22, 23),
  ('profecia', 'Depois disso, ouvi a voz do Senhor, que dizia: A quem enviarei, e quem há de ir por nós? Então, disse eu: eis-me aqui, envia-me a mim.', 'Isaías 6:8', 'Isaías', 6, 8, NULL),
  ('profecia', 'E tu, Belém Efrata, posto que pequena entre milhares de Judá, de ti me sairá o que será Senhor em Israel, e cujas origens são desde os tempos antigos, desde os dias da eternidade.', 'Miqueias 5:2', 'Miqueias', 5, 2, NULL),
  ('profecia', 'A este dão testemunho todos os profetas, de que todos os que nele creem receberão o perdão dos pecados pelo seu nome.', 'Atos 10:43', 'Atos', 10, 43, NULL),
  ('promessas', 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te esforço, e te ajudo, e te sustento com a destra da minha justiça.', 'Isaías 41:10', 'Isaías', 41, 10, NULL),
  ('promessas', 'Porque eu bem sei os pensamentos que penso de vós, diz o Senhor; pensamentos de paz e não de mal, para vos dar o fim que esperais.', 'Jeremias 29:11', 'Jeremias', 29, 11, NULL),
  ('promessas', 'Retenhamos firmes a confissão da nossa esperança, porque fiel é o que prometeu.', 'Hebreus 10:23', 'Hebreus', 10, 23, NULL),
  ('promessas', 'Mas os que esperam no Senhor renovarão as suas forças e subirão com asas como águias; correrão e não se cansarão; caminharão e não se fatigarão.', 'Isaías 40:31', 'Isaías', 40, 31, NULL),
  ('promessas', 'Fiel é o que vos chama, o qual também o fará.', '1 Tessalonicenses 5:24', '1 Tessalonicenses', 5, 24, NULL),
  ('promessas', 'Quando passares pelas águas, estarei contigo, e, quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti.', 'Isaías 43:2', 'Isaías', 43, 2, NULL),
  ('promessas', 'E o Deus de toda a graça, que em Cristo Jesus vos chamou à sua eterna glória, depois de haverdes padecido um pouco, ele mesmo vos aperfeiçoará, confirmará, fortificará e fortalecerá.', '1 Pedro 5:10', '1 Pedro', 5, 10, NULL),
  ('promessas', 'Pedi, e dar-se-vos-á; buscai e encontrareis; batei, e abrir-se-vos-á.', 'Mateus 7:7', 'Mateus', 7, 7, NULL),
  ('promessas', 'O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se.', '2 Pedro 3:9', '2 Pedro', 3, 9, NULL),
  ('promessas', 'Saberás, pois, que o Senhor, teu Deus, é Deus, o Deus fiel, que guarda o concerto e a misericórdia até mil gerações aos que o amam e guardam os seus mandamentos.', 'Deuteronômio 7:9', 'Deuteronômio', 7, 9, NULL),
  ('promessas', 'Disse-lhe Jesus: Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá; e todo aquele que vive e crê em mim nunca morrerá. Crês tu isso?', 'João 11:25-26', 'João', 11, 25, 26),
  ('promessas', 'Deus não é homem, para que minta; nem filho de homem, para que se arrependa; porventura, diria ele e não o faria? Ou falaria e não o confirmaria?', 'Números 23:19', 'Números', 23, 19, NULL),
  ('promessas', 'Ora, amados, pois que temos tais promessas, purifiquemo-nos de toda imundícia da carne e do espírito, aperfeiçoando a santificação no temor de Deus.', '2 Coríntios 7:1', '2 Coríntios', 7, 1, NULL),
  ('promessas', 'Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e com ele cearei, e ele, comigo.', 'Apocalipse 3:20', 'Apocalipse', 3, 20, NULL),
  ('promessas', 'O que vencer será vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; e confessarei o seu nome diante de meu Pai e diante dos seus anjos.', 'Apocalipse 3:5', 'Apocalipse', 3, 5, NULL),
  ('promessas', 'Pelas quais ele nos tem dado grandíssimas e preciosas promessas, para que por elas fiqueis participantes da natureza divina, havendo escapado da corrupção, que, pela concupiscência, há no mundo.', '2 Pedro 1:4', '2 Pedro', 1, 4, NULL),
  ('promessas', 'O meu arco tenho posto na nuvem; este será por sinal do concerto entre mim e a terra.', 'Gênesis 9:13', 'Gênesis', 9, 13, NULL),
  ('promessas', 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'João', 3, 16, NULL),
  ('promessas', 'E eis aqui eu vou, hoje, pelo caminho de toda a terra; e vós bem sabeis, com todo o vosso coração e com toda a vossa alma que nem uma só palavra caiu de todas as boas palavras que falou de vós o Senhor, vosso Deus; todas vos sobrevieram, nem delas caiu uma só palavra.', 'Josué 23:14', 'Josué', 23, 14, NULL),
  ('promessas', 'Porque o exercício corporal para pouco aproveita, mas a piedade para tudo é proveitosa, tendo a promessa da vida presente e da que há de vir.', '1 Timóteo 4:8', '1 Timóteo', 4, 8, NULL),
  ('promessas', 'Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos; o que votares, paga-o.', 'Eclesiastes 5:4', 'Eclesiastes', 5, 4, NULL),
  ('promessas', 'Amados, agora somos filhos de Deus, e ainda não é manifesto o que havemos de ser. Mas sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como é o veremos. E qualquer que nele tem esta esperança purifica-se a si mesmo, como também ele é puro.', '1 João 3:2-3', '1 João', 3, 2, 3),
  ('promessas', 'Mas a Escritura encerrou tudo debaixo do pecado, para que a promessa pela fé em Jesus Cristo fosse dada aos crentes.', 'Gálatas 3:22', 'Gálatas', 3, 22, NULL),
  ('promessas', 'Porque necessitais de paciência, para que, depois de haverdes feito a vontade de Deus, possais alcançar a promessa.', 'Hebreus 10:36', 'Hebreus', 10, 36, NULL),
  ('promessas', 'E, por isso, é Mediador de um novo testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna.', 'Hebreus 9:15', 'Hebreus', 9, 15, NULL),
  ('promessas', 'E eu convosco estabeleço o meu concerto, que não será mais destruída toda carne pelas águas do dilúvio e que não haverá mais dilúvio para destruir a terra.', 'Gênesis 9:11', 'Gênesis', 9, 11, NULL),
  ('promessas', 'Mas, se deveras melhorardes os vossos caminhos e as vossas obras, se deveras fizerdes juízo entre um homem e entre o seu companheiro, se não oprimirdes o estrangeiro, e o órfão, e a viúva, nem derramardes sangue inocente neste lugar, nem andardes após outros deuses para vosso próprio mal, eu vos farei habitar neste lugar, na terra que dei a vossos pais, de século em século.', 'Jeremias 7:5-7', 'Jeremias', 7, 5, 7),
  ('promessas', 'Mas agora alcançou ele ministério tanto mais excelente, quanto é mediador de um melhor concerto, que está confirmado em melhores promessas.', 'Hebreus 8:6', 'Hebreus', 8, 6, NULL),
  ('protecao', 'Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo.', 'Efésios 6:11', 'Efésios', 6, 11, NULL),
  ('protecao', 'Tu és o lugar em que me escondo; tu me preservas da angústia; tu me cinges de alegres cantos de livramento. (Selá)', 'Salmo 32:7', 'Salmo', 32, 7, NULL),
  ('protecao', 'Deus é o nosso refúgio e fortaleza, socorro bem-presente na angústia.', 'Salmo 46:1', 'Salmo', 46, 1, NULL),
  ('protecao', 'Esforçai-vos, e animai-vos; não temais, nem vos espanteis diante deles, porque o Senhor, vosso Deus, é o que vai convosco; não vos deixará nem vos desamparará.', 'Deuteronômio 31:6', 'Deuteronômio', 31, 6, NULL),
  ('protecao', 'Toda ferramenta preparada contra ti não prosperará; e toda língua que se levantar contra ti em juízo, tu a condenarás; esta é a herança dos servos do Senhor e a sua justiça que vem de mim, diz o Senhor.', 'Isaías 54:17', 'Isaías', 54, 17, NULL),
  ('protecao', 'E, assim, com confiança, ousemos dizer: O Senhor é o meu ajudador, e não temerei o que me possa fazer o homem.', 'Hebreus 13:6', 'Hebreus', 13, 6, NULL),
  ('protecao', 'Também me deste o escudo da tua salvação; a tua mão direita me susteve, e a tua mansidão me engrandeceu. Alargaste os meus passos e os meus artelhos não vacilaram.', 'Salmo 18:35-36', 'Salmo', 18, 35, 36);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('protecao', 'Guarda-me, ó Deus, porque em ti confio.', 'Salmo 16:1', 'Salmo', 16, 1, NULL),
  ('protecao', 'O Senhor pelejará por vós, e vos calareis.', 'Êxodo 14:14', 'Êxodo', 14, 14, NULL),
  ('protecao', 'O Senhor está comigo; não temerei o que me pode fazer o homem.', 'Salmo 118:6', 'Salmo', 118, 6, NULL),
  ('protecao', 'Tu és o meu refúgio e o meu escudo; espero na tua palavra.', 'Salmo 119:114', 'Salmo', 119, 114, NULL),
  ('protecao', 'Posso todas as coisas naquele que me fortalece.', 'Filipenses 4:13', 'Filipenses', 4, 13, NULL),
  ('protecao', 'E até à velhice eu serei o mesmo e ainda até às cãs eu vos trarei; eu o fiz, e eu vos levarei, e eu vos trarei e vos guardarei.', 'Isaías 46:4', 'Isaías', 46, 4, NULL),
  ('protecao', 'O caminho de Deus é perfeito; a palavra do Senhor é provada; é um escudo para todos os que nele confiam.', 'Salmo 18:30', 'Salmo', 18, 30, NULL),
  ('protecao', 'Ele te cobrirá com as suas penas, e debaixo das suas asas estarás seguro; a sua verdade é escudo e broquel.', 'Salmo 91:4', 'Salmo', 91, 4, NULL),
  ('protecao', 'Eu, porém, cantarei a tua força; pela manhã, louvarei com alegria a tua misericórdia, porquanto tu foste o meu alto refúgio e proteção no dia da minha angústia.', 'Salmo 59:16', 'Salmo', 59, 16, NULL),
  ('protecao', 'Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as saídas da vida.', 'Provérbios 4:23', 'Provérbios', 4, 23, NULL),
  ('protecao', 'Que diremos, pois, a estas coisas? Se Deus é por nós, quem será contra nós?', 'Romanos 8:31', 'Romanos', 8, 31, NULL),
  ('protecao', 'Mas tu, Senhor, és um escudo para mim, a minha glória e o que exalta a minha cabeça.', 'Salmo 3:3', 'Salmo', 3, 3, NULL),
  ('protecao', 'Ou pensas tu que eu não poderia, agora, orar a meu Pai e que ele não me daria mais de doze legiões de anjos?', 'Mateus 26:53', 'Mateus', 26, 53, NULL),
  ('protecao', 'Tenho posto o Senhor continuamente diante de mim; por isso que ele está à minha mão direita, nunca vacilarei.', 'Salmo 16:8', 'Salmo', 16, 8, NULL),
  ('protecao', 'É melhor confiar no Senhor do que confiar no homem.', 'Salmo 118:8', 'Salmo', 118, 8, NULL),
  ('protecao', 'Toda palavra de Deus é pura; escudo é para os que confiam nele.', 'Provérbios 30:5', 'Provérbios', 30, 5, NULL),
  ('protecao', 'Torre forte é o nome do Senhor; para ela correrá o justo e estará em alto retiro.', 'Provérbios 18:10', 'Provérbios', 18, 10, NULL),
  ('protecao', 'E o Senhor me livrará de toda má obra e guardar-me-á para o seu Reino celestial; a quem seja glória para todo o sempre. Amém!', '2 Timóteo 4:18', '2 Timóteo', 4, 18, NULL),
  ('protecao', 'O Senhor é bom, uma fortaleza no dia da angústia, e conhece os que confiam nele.', 'Naum 1:7', 'Naum', 1, 7, NULL),
  ('protecao', 'Porque, quem é Deus, senão o Senhor? E quem é rochedo, senão o nosso Deus?', '2 Samuel 22:32', '2 Samuel', 22, 32, NULL),
  ('protecao', 'Aprendei a fazer o bem; praticai o que é reto; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas.', 'Isaías 1:17', 'Isaías', 1, 17, NULL),
  ('protecao', 'O Senhor resgata a alma dos seus servos, e nenhum dos que nele confiam será condenado.', 'Salmo 34:22', 'Salmo', 34, 22, NULL),
  ('protecao', 'Só ele é a minha rocha e a minha salvação; é a minha defesa; não serei grandemente abalado.', 'Salmo 62:2', 'Salmo', 62, 2, NULL),
  ('protecao', 'O caminho de Deus é perfeito, e a palavra do Senhor, refinada; ele é o escudo de todos os que nele confiam.', '2 Samuel 22:31', '2 Samuel', 22, 31, NULL),
  ('protecao', 'Para que guarde as veredas do juízo e conserve o caminho dos seus santos.', 'Provérbios 2:8', 'Provérbios', 2, 8, NULL),
  ('protecao', 'Não detenhas para comigo, Senhor, as tuas misericórdias; guardem-me continuamente a tua benignidade e a tua verdade.', 'Salmo 40:11', 'Salmo', 40, 11, NULL),
  ('protecao', 'Nunca mais terão fome, nunca mais terão sede; nem sol nem calma alguma cairá sobre eles, porque o Cordeiro que está no meio do trono os apascentará e lhes servirá de guia para as fontes das águas da vida; e Deus limpará de seus olhos toda lágrima.', 'Apocalipse 7:16-17', 'Apocalipse', 7, 16, 17),
  ('protecao', 'O avisado vê o mal e esconde-se; mas os simples passam e sofrem a pena.', 'Provérbios 27:12', 'Provérbios', 27, 12, NULL),
  ('protecao', 'Portanto, tomai toda a armadura de Deus, para que possais resistir no dia mau e, havendo feito tudo, ficar firmes.', 'Efésios 6:13', 'Efésios', 6, 13, NULL),
  ('protecao', 'Se alguém destruir o templo de Deus, Deus o destruirá; porque o templo de Deus, que sois vós, é santo.', '1 Coríntios 3:17', '1 Coríntios', 3, 17, NULL),
  ('protecao', 'O Senhor será também um alto refúgio para o oprimido; um alto refúgio em tempos de angústia.', 'Salmo 9:9', 'Salmo', 9, 9, NULL),
  ('protecao', 'Ele reserva a verdadeira sabedoria para os retos; escudo é para os que caminham na sinceridade.', 'Provérbios 2:7', 'Provérbios', 2, 7, NULL),
  ('protecao', 'Só ele é a minha rocha e a minha salvação; é a minha defesa; não serei abalado.', 'Salmo 62:6', 'Salmo', 62, 6, NULL),
  ('protecao', 'E não nos induzas à tentação, mas livra-nos do mal; porque teu é o Reino, e o poder, e a glória, para sempre. Amém!', 'Mateus 6:13', 'Mateus', 6, 13, NULL),
  ('protecao', 'Não folga com a injustiça, mas folga com a verdade; tudo sofre, tudo crê, tudo espera, tudo suporta.', '1 Coríntios 13:6-7', '1 Coríntios', 13, 6, 7),
  ('protecao', 'Pois tu, Senhor, abençoarás ao justo; circundá-lo-ás da tua benevolência como de um escudo.', 'Salmo 5:12', 'Salmo', 5, 12, NULL),
  ('protecao', 'O Senhor guarda os estrangeiros; ampara o órfão e a viúva, mas transtorna o caminho dos ímpios.', 'Salmo 146:9', 'Salmo', 146, 9, NULL),
  ('protecao', 'E disse o Senhor a Satanás: Eis que tudo quanto tem está na tua mão; somente contra ele não estendas a tua mão. E Satanás saiu da presença do Senhor.', 'Jó 1:12', 'Jó', 1, 12, NULL),
  ('protecao', 'Porque tu acenderás a minha candeia; o Senhor, meu Deus, alumiará as minhas trevas.', 'Salmo 18:28', 'Salmo', 18, 28, NULL),
  ('protecao', 'Buscai o Senhor, vós todos os mansos da terra, que pondes por obra o seu juízo; buscai a justiça, buscai a mansidão; porventura sereis escondidos no dia da ira do Senhor.', 'Sofonias 2:3', 'Sofonias', 2, 3, NULL),
  ('protecao', 'Na verdade, nunca será abalado; o justo ficará em memória eterna.', 'Salmo 112:6', 'Salmo', 112, 6, NULL),
  ('proximidade', 'O Senhor está convosco, enquanto vós estais com ele, e, se o buscardes, o achareis; porém, se o deixardes, vos deixará.', '2 Crônicas 15:2b', '2 Crônicas 15:2b', NULL, NULL, NULL),
  ('proximidade', 'Buscai o Senhor e a sua força; buscai a sua face continuamente.', '1 Crônicas 16:11', '1 Crônicas', 16, 11, NULL),
  ('proximidade', 'Os justos clamam, e o Senhor os ouve e os livra de todas as suas angústias. Perto está o Senhor dos que têm o coração quebrantado e salva os contritos de espírito.', 'Salmo 34:17-18', 'Salmo', 34, 17, 18),
  ('proximidade', 'Ora, o mesmo Senhor da paz vos dê sempre paz de toda maneira. O Senhor seja com todos vós.', '2 Tessalonicenses 3:16', '2 Tessalonicenses', 3, 16, NULL),
  ('proximidade', 'Seja a vossa equidade notória a todos os homens. Perto está o Senhor.', 'Filipenses 4:5', 'Filipenses', 4, 5, NULL),
  ('proximidade', 'Uma coisa pedi ao Senhor e a buscarei: que possa morar na Casa do Senhor todos os dias da minha vida, para contemplar a formosura do Senhor e aprender no seu templo.', 'Salmo 27:4', 'Salmo', 27, 4, NULL),
  ('proximidade', 'Far-me-ás ver a vereda da vida; na tua presença há abundância de alegrias; à tua mão direita há delícias perpetuamente.', 'Salmo 16:11', 'Salmo', 16, 11, NULL),
  ('proximidade', 'Mas, agora, em Cristo Jesus, vós, que antes estáveis longe, já pelo sangue de Cristo chegastes perto.', 'Efésios 2:13', 'Efésios', 2, 13, NULL),
  ('proximidade', 'Nisto conhecemos que estamos nele, e ele em nós, pois que nos deu do seu Espírito.', '1 João 4:13', '1 João', 4, 13, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('proximidade', 'Buscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto.', 'Isaías 55:6', 'Isaías', 55, 6, NULL),
  ('proximidade', 'Buscai ao Senhor e a sua força; buscai a sua face continuamente.', 'Salmo 105:4', 'Salmo', 105, 4, NULL),
  ('proximidade', 'Não vos deixarei órfãos; voltarei para vós.', 'João 14:18', 'João', 14, 18, NULL),
  ('proximidade', 'Quanto ao mais, irmãos, regozijai-vos, sede perfeitos, sede consolados, sede de um mesmo parecer, vivei em paz; e o Deus de amor e de paz será convosco.', '2 Coríntios 13:11', '2 Coríntios', 13, 11, NULL),
  ('proximidade', 'Certamente que a bondade e a misericórdia me seguirão todos os dias da minha vida; e habitarei na Casa do Senhor por longos dias.', 'Salmo 23:6', 'Salmo', 23, 6, NULL),
  ('proximidade', 'Porque vale mais um dia nos teus átrios do que, em outra parte, mil. Preferiria estar à porta da Casa do meu Deus, a habitar nas tendas da impiedade.', 'Salmo 84:10', 'Salmo', 84, 10, NULL),
  ('proximidade', 'O Senhor, nosso Deus, seja conosco, como foi com nossos pais; não nos desampare e não nos deixe.', '1 Reis 8:57', '1 Reis', 8, 57, NULL),
  ('proximidade', 'Mas, pela tua grande misericórdia, não os destruíste nem desamparaste; porque és um Deus clemente e misericordioso.', 'Neemias 9:31', 'Neemias', 9, 31, NULL),
  ('proximidade', 'Deus nunca foi visto por alguém. O Filho unigênito, que está no seio do Pai, este o fez conhecer.', 'João 1:18', 'João', 1, 18, NULL),
  ('proximidade', 'E curai os enfermos que nela houver e dizei-lhes: É chegado a vós o Reino de Deus.', 'Lucas 10:9', 'Lucas', 10, 9, NULL),
  ('proximidade', 'Quem come a minha carne e bebe o meu sangue permanece em mim, e eu, nele.', 'João 6:56', 'João', 6, 56, NULL),
  ('proximidade', 'E esteve Moisés ali com o Senhor quarenta dias e quarenta noites; não comeu pão, nem bebeu água, e escreveu nas tábuas as palavras do concerto, os dez mandamentos.', 'Êxodo 34:28', 'Êxodo', 34, 28, NULL),
  ('proximidade', 'A minha alma tem sede de Deus, do Deus vivo; quando entrarei e me apresentarei ante a face de Deus?', 'Salmo 42:2', 'Salmo', 42, 2, NULL),
  ('proximidade', 'Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 3:2', 'Mateus', 3, 2, NULL),
  ('punicao', 'Filho meu, não rejeites a correção do Senhor, nem te enojes da sua repreensão. Porque o Senhor repreende aquele a quem ama, assim como o pai, ao filho a quem quer bem.', 'Provérbios 3:11-12', 'Provérbios', 3, 11, 12),
  ('punicao', 'Eu repreendo e castigo a todos quantos amo; sê, pois, zeloso e arrepende-te.', 'Apocalipse 3:19', 'Apocalipse', 3, 19, NULL),
  ('punicao', 'O avisado vê o mal e esconde-se; mas os simples passam e sofrem a pena.', 'Provérbios 27:12', 'Provérbios', 27, 12, NULL),
  ('punicao', 'Porque todos os que sem lei pecaram sem lei também perecerão; e todos os que sob a lei pecaram pela lei serão julgados.', 'Romanos 2:12', 'Romanos', 2, 12, NULL),
  ('punicao', 'E, na verdade, toda correção, ao presente, não parece ser de gozo, senão de tristeza, mas, depois, produz um fruto pacífico de justiça nos exercitados por ela.', 'Hebreus 12:11', 'Hebreus', 12, 11, NULL),
  ('punicao', 'E, se alguma pessoa pecar e fizer contra algum de todos os mandamentos do Senhor o que se não deve fazer, ainda que o não soubesse, contudo, será ela culpada e levará a sua iniquidade.', 'Levítico 5:17', 'Levítico', 5, 17, NULL),
  ('punicao', 'Mas o que a não soube e fez coisas dignas de açoites com poucos açoites será castigado. E a qualquer que muito for dado, muito se lhe pedirá, e ao que muito se lhe confiou, muito mais se lhe pedirá.', 'Lucas 12:48', 'Lucas', 12, 48, NULL),
  ('punicao', 'Vinde e convertei-vos de todas as vossas transgressões, e a iniquidade não vos servirá de tropeço.', 'Ezequiel 18:30b', 'Ezequiel 18:30b', NULL, NULL, NULL),
  ('punicao', 'No amor, não há temor; antes, o perfeito amor lança fora o temor; porque o temor tem consigo a pena, e o que teme não é perfeito em amor.', '1 João 4:18', '1 João', 4, 18, NULL),
  ('punicao', 'Não tomarás o nome do Senhor, teu Deus, em vão, porque o Senhor não terá por inocente ao que tomar o seu nome em vão.', 'Deuteronômio 5:11', 'Deuteronômio', 5, 11, NULL),
  ('punicao', 'Eis que bem-aventurado é o homem a quem Deus castiga; não desprezes, pois, o castigo do Todo-Poderoso.', 'Jó 5:17', 'Jó', 5, 17, NULL),
  ('punicao', 'Confessa, pois, no teu coração que, como um homem castiga a seu filho, assim te castiga o Senhor, teu Deus.', 'Deuteronômio 8:5', 'Deuteronômio', 8, 5, NULL),
  ('punicao', 'Anda com os sábios e serás sábio, mas o companheiro dos tolos será afligido.', 'Provérbios 13:20', 'Provérbios', 13, 20, NULL),
  ('punicao', 'Não, vos digo; antes, se vos não arrependerdes, todos de igual modo perecereis.', 'Lucas 13:3', 'Lucas', 13, 3, NULL),
  ('punicao', 'Quem crer e for batizado será salvo; mas quem não crer será condenado.', 'Marcos 16:16', 'Marcos', 16, 16, NULL),
  ('punicao', 'Assim, sabe o Senhor livrar da tentação os piedosos e reservar os injustos para o Dia de Juízo, para serem castigados.', '2 Pedro 2:9', '2 Pedro', 2, 9, NULL),
  ('punicao', 'Portanto, agora, nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito. Porque a lei do Espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte.', 'Romanos 8:1-2', 'Romanos', 8, 1, 2),
  ('punicao', 'Que pregues a palavra, instes a tempo e fora de tempo, redarguas, repreendas, exortes, com toda a longanimidade e doutrina.', '2 Timóteo 4:2', '2 Timóteo', 4, 2, NULL),
  ('punicao', 'Mas, sobretudo, meus irmãos, não jureis nem pelo céu nem pela terra, nem façais qualquer outro juramento; mas que a vossa palavra seja sim, sim e não, não, para que não caiais em condenação.', 'Tiago 5:12', 'Tiago', 5, 12, NULL),
  ('punicao', 'Deus faz que o solitário viva em família; liberta aqueles que estão presos em grilhões; mas os rebeldes habitam em terra seca.', 'Salmo 68:6', 'Salmo', 68, 6, NULL),
  ('punicao', 'O Senhor guarda os estrangeiros; ampara o órfão e a viúva, mas transtorna o caminho dos ímpios.', 'Salmo 146:9', 'Salmo', 146, 9, NULL),
  ('punicao', 'Portanto, eu vos digo: todo pecado e blasfêmia se perdoará aos homens, mas a blasfêmia contra o Espírito não será perdoada aos homens.', 'Mateus 12:31', 'Mateus', 12, 31, NULL),
  ('punicao', 'Mas não é assim o dom gratuito como a ofensa; porque, se, pela ofensa de um, morreram muitos, muito mais a graça de Deus e o dom pela graça, que é de um só homem, Jesus Cristo, abundou sobre muitos.', 'Romanos 5:15', 'Romanos', 5, 15, NULL),
  ('punicao', 'Não aproveitam as riquezas no dia da ira, mas a justiça livra da morte.', 'Provérbios 11:4', 'Provérbios', 11, 4, NULL),
  ('punicao', 'Visto como se não executa logo o juízo sobre a má obra, por isso o coração dos filhos dos homens está inteiramente disposto para praticar o mal.', 'Eclesiastes 8:11', 'Eclesiastes', 8, 11, NULL),
  ('punicao', 'Não vos vingueis a vós mesmos, amados, mas dai lugar à ira, porque está escrito: Minha é a vingança; eu recompensarei, diz o Senhor.', 'Romanos 12:19', 'Romanos', 12, 19, NULL),
  ('punicao', 'O Senhor é tardio em irar-se, mas grande em força e ao culpado não tem por inocente; o Senhor tem o seu caminho na tormenta e na tempestade, e as nuvens são o pó dos seus pés.', 'Naum 1:3', 'Naum', 1, 3, NULL),
  ('purificacao', 'Ora, amados, pois que temos tais promessas, purifiquemo-nos de toda imundícia da carne e do espírito, aperfeiçoando a santificação no temor de Deus.', '2 Coríntios 7:1', '2 Coríntios', 7, 1, NULL),
  ('purificacao', 'Cria em mim, ó Deus, um coração puro e renova em mim um espírito reto.', 'Salmo 51:10', 'Salmo', 51, 10, NULL),
  ('purificacao', 'E dizia: O que sai do homem, isso é que contamina o homem. Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios, os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura. Todos estes males procedem de dentro e contaminam o homem.', 'Marcos 7:20-23', 'Marcos', 7, 20, 23),
  ('purificacao', 'Tem misericórdia de mim, ó Deus, segundo a tua benignidade; apaga as minhas transgressões, segundo a multidão das tuas misericórdias. Lava-me completamente da minha iniquidade e purifica-me do meu pecado.', 'Salmo 51:1-2', 'Salmo', 51, 1, 2),
  ('purificacao', 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.', '1 João 1:9', '1 João', 1, 9, NULL),
  ('purificacao', 'Chegai-vos a Deus, e ele se chegará a vós. Limpai as mãos, pecadores; e, vós de duplo ânimo, purificai o coração.', 'Tiago 4:8', 'Tiago', 4, 8, NULL),
  ('purificacao', 'Vós já estais limpos pela palavra que vos tenho falado.', 'João 15:3', 'João', 15, 3, NULL),
  ('purificacao', 'Lavai-vos, purificai-vos, tirai a maldade de vossos atos de diante dos meus olhos e cessai de fazer mal.', 'Isaías 1:16', 'Isaías', 1, 16, NULL),
  ('purificacao', 'Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo pecado.', '1 João 1:7', '1 João', 1, 7, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('purificacao', 'Amados, agora somos filhos de Deus, e ainda não é manifesto o que havemos de ser. Mas sabemos que, quando ele se manifestar, seremos semelhantes a ele; porque assim como é o veremos. E qualquer que nele tem esta esperança purifica-se a si mesmo, como também ele é puro.', '1 João 3:2-3', '1 João', 3, 2, 3),
  ('purificacao', 'Muitos serão purificados, e embranquecidos, e provados; mas os ímpios procederão impiamente, e nenhum dos ímpios entenderá, mas os sábios entenderão.', 'Daniel 12:10', 'Daniel', 12, 10, NULL),
  ('purificacao', 'O qual se deu a si mesmo por nós, para nos remir de toda iniquidade e purificar para si um povo seu especial, zeloso de boas obras.', 'Tito 2:14', 'Tito', 2, 14, NULL),
  ('purificacao', 'E, agora, por que te deténs? Levanta-te, e batiza-te, e lava os teus pecados, invocando o nome do Senhor.', 'Atos 22:16', 'Atos', 22, 16, NULL),
  ('purificacao', 'Quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus, purificará a vossa consciência das obras mortas, para servirdes ao Deus vivo?', 'Hebreus 9:14', 'Hebreus', 9, 14, NULL),
  ('purificacao', 'Vós, maridos, amai vossa mulher, como também Cristo amou a igreja e a si mesmo se entregou por ela, para a santificar, purificando-a com a lavagem da água, pela palavra.', 'Efésios 5:25-26', 'Efésios', 5, 25, 26),
  ('purificacao', 'Que também, como uma verdadeira figura, agora vos salva, batismo, não do despojamento da imundícia da carne, mas da indagação de uma boa consciência para com Deus, pela ressurreição de Jesus Cristo.', '1 Pedro 3:21', '1 Pedro', 3, 21, NULL),
  ('purificacao', 'O qual, sendo o resplendor da sua glória, e a expressa imagem da sua pessoa, e sustentando todas as coisas pela palavra do seu poder, havendo feito por si mesmo a purificação dos nossos pecados, assentou-se à destra da Majestade, nas alturas.', 'Hebreus 1:3', 'Hebreus', 1, 3, NULL),
  ('purificacao', 'Vinde, então, e argui-me, diz o Senhor; ainda que os vossos pecados sejam como a escarlata, eles se tornarão brancos como a neve; ainda que sejam vermelhos como o carmesim, se tornarão como a branca lã.', 'Isaías 1:18', 'Isaías', 1, 18, NULL),
  ('purificacao', 'Pois tu, ó Deus, nos provaste; tu nos afinaste como se afina a prata.', 'Salmo 66:10', 'Salmo', 66, 10, NULL),
  ('purificacao', 'Agora, pois, deitai fora os deuses estranhos que há no meio de vós: e inclinai o vosso coração ao Senhor, Deus de Israel.', 'Josué 24:23', 'Josué', 24, 23, NULL),
  ('purificacao', 'Porque, com uma só oblação, aperfeiçoou para sempre os que são santificados.', 'Hebreus 10:14', 'Hebreus', 10, 14, NULL),
  ('raiva', 'Irai-vos e não pequeis; não se ponha o sol sobre a vossa ira. Não deis lugar ao diabo.', 'Efésios 4:26-27', 'Efésios', 4, 26, 27),
  ('raiva', 'O amor é sofredor, é benigno; o amor não é invejoso; o amor não trata com leviandade, não se ensoberbece, não se porta com indecência, não busca os seus interesses, não se irrita, não suspeita mal.', '1 Coríntios 13:4-5', '1 Coríntios', 13, 4, 5),
  ('raiva', 'Não aborrecerás a teu irmão no teu coração; não deixarás de repreender o teu próximo e nele não sofrerás pecado. Não te vingarás, nem guardarás ira contra os filhos do teu povo; mas amarás o teu próximo como a ti mesmo. Eu sou o Senhor.', 'Levítico 19:17-18', 'Levítico', 19, 17, 18),
  ('raiva', 'O ódio excita contendas, mas o amor cobre todas as transgressões.', 'Provérbios 10:12', 'Provérbios', 10, 12, NULL),
  ('raiva', 'A resposta branda desvia o furor, mas a palavra dura suscita a ira.', 'Provérbios 15:1', 'Provérbios', 15, 1, NULL),
  ('raiva', 'Sabeis isto, meus amados irmãos; mas todo o homem seja pronto para ouvir, tardio para falar, tardio para se irar.', 'Tiago 1:19', 'Tiago', 1, 19, NULL),
  ('raiva', 'O longânimo é grande em entendimento, mas o de ânimo precipitado exalta a loucura.', 'Provérbios 14:29', 'Provérbios', 14, 29, NULL),
  ('raiva', 'Um tolo expande toda a sua ira, mas o sábio a encobre e reprime.', 'Provérbios 29:11', 'Provérbios', 29, 11, NULL),
  ('raiva', 'E dizia: O que sai do homem, isso é que contamina o homem. Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios, os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura. Todos estes males procedem de dentro e contaminam o homem.', 'Marcos 7:20-23', 'Marcos', 7, 20, 23),
  ('raiva', 'A ira do louco se conhece no mesmo dia, mas o avisado encobre a afronta.', 'Provérbios 12:16', 'Provérbios', 12, 16, NULL),
  ('raiva', 'Honroso é para o homem o desviar-se de questões, mas todo tolo se entremete nelas.', 'Provérbios 20:3', 'Provérbios', 20, 3, NULL),
  ('raiva', 'Da soberba só provém a contenda, mas com os que se aconselham se acha a sabedoria.', 'Provérbios 13:10', 'Provérbios', 13, 10, NULL),
  ('raiva', 'Vede, irmãos, que nunca haja em qualquer de vós um coração mau e infiel, para se apartar do Deus vivo.', 'Hebreus 3:12', 'Hebreus', 3, 12, NULL),
  ('raiva', 'Volta, ó rebelde Israel, diz o Senhor, e não farei cair a minha ira sobre vós; porque benigno sou, diz o Senhor, e não conservarei para sempre a minha ira.', 'Jeremias 3:12b', 'Jeremias 3:12b', NULL, NULL, NULL),
  ('raiva', 'Porque as obras da carne são manifestas, as quais são: prostituição, impureza, lascívia, idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias, invejas, homicídios, bebedices, glutonarias e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas não herdarão o Reino de Deus.', 'Gálatas 5:19-21', 'Gálatas', 5, 19, 21),
  ('raiva', 'Não vos vingueis a vós mesmos, amados, mas dai lugar à ira, porque está escrito: Minha é a vingança; eu recompensarei, diz o Senhor.', 'Romanos 12:19', 'Romanos', 12, 19, NULL),
  ('recebimento', 'Por isso, vos digo que tudo o que pedirdes, orando, crede que o recebereis e tê-lo-eis.', 'Marcos 11:24', 'Marcos', 11, 24, NULL),
  ('recebimento', 'E, tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens, sabendo que recebereis do Senhor o galardão da herança, porque a Cristo, o Senhor, servis.', 'Colossenses 3:23-24', 'Colossenses', 3, 23, 24),
  ('recebimento', 'Até agora, nada pedistes em meu nome; pedi e recebereis, para que a vossa alegria se cumpra.', 'João 16:24', 'João', 16, 24, NULL),
  ('recebimento', 'Pedi, e dar-se-vos-á; buscai e encontrareis; batei, e abrir-se-vos-á.', 'Mateus 7:7', 'Mateus', 7, 7, NULL),
  ('recebimento', 'E Deus é poderoso para tornar abundante em vós toda graça, a fim de que, tendo sempre, em tudo, toda suficiência, superabundeis em toda boa obra.', '2 Coríntios 9:8', '2 Coríntios', 9, 8, NULL),
  ('recebimento', 'Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando vos darão; porque com a mesma medida com que medirdes também vos medirão de novo.', 'Lucas 6:38', 'Lucas', 6, 38, NULL),
  ('recebimento', 'E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada.', 'Tiago 1:5', 'Tiago', 1, 5, NULL),
  ('recebimento', 'Estendo para ti as minhas mãos; a minha alma tem sede de ti como terra sedenta. (Selá)', 'Salmo 143:6', 'Salmo', 143, 6, NULL),
  ('recebimento', 'Por isso, não desfalecemos; mas, ainda que o nosso homem exterior se corrompa, o interior, contudo, se renova de dia em dia.', '2 Coríntios 4:16', '2 Coríntios', 4, 16, NULL),
  ('recebimento', 'Curai os enfermos, limpai os leprosos, ressuscitai os mortos, expulsai os demônios; de graça recebestes, de graça dai.', 'Mateus 10:8', 'Mateus', 10, 8, NULL),
  ('recebimento', 'E a unção que vós recebestes dele fica em vós, e não tendes necessidade de que alguém vos ensine; mas, como a sua unção vos ensina todas as coisas, e é verdadeira, e não é mentira, como ela vos ensinou, assim nele permanecereis.', '1 João 2:27', '1 João', 2, 27, NULL),
  ('recebimento', 'E quanto ao homem, a quem Deus deu riquezas e fazenda e lhe deu poder para delas comer, e tomar a sua porção, e gozar do seu trabalho, isso é dom de Deus.', 'Eclesiastes 5:19', 'Eclesiastes', 5, 19, NULL),
  ('recebimento', 'Aquele que nem mesmo a seu próprio Filho poupou, antes, o entregou por todos nós, como nos não dará também com ele todas as coisas?', 'Romanos 8:32', 'Romanos', 8, 32, NULL),
  ('recebimento', 'Já tenho conhecido que não há coisa melhor para eles do que se alegrarem e fazerem bem na sua vida; e também que todo homem coma e beba e goze do bem de todo o seu trabalho. Isso é um dom de Deus.', 'Eclesiastes 3:12-13', 'Eclesiastes', 3, 12, 13),
  ('recebimento', 'Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.', 'Mateus 5:6', 'Mateus', 5, 6, NULL),
  ('recebimento', 'Visto como o seu divino poder nos deu tudo o que diz respeito à vida e piedade, pelo conhecimento daquele que nos chamou por sua glória e virtude.', '2 Pedro 1:3', '2 Pedro', 1, 3, NULL),
  ('recebimento', 'Mas aquele que beber da água que eu lhe der nunca terá sede, porque a água que eu lhe der se fará nele uma fonte de água a jorrar para a vida eterna.', 'João 4:14', 'João', 4, 14, NULL),
  ('recebimento', 'Tendo iluminados os olhos do vosso entendimento, para que saibais qual seja a esperança da sua vocação e quais as riquezas da glória da sua herança nos santos.', 'Efésios 1:18', 'Efésios', 1, 18, NULL),
  ('recebimento', 'E nós somos testemunhas acerca destas palavras, nós e também o Espírito Santo, que Deus deu àqueles que lhe obedecem.', 'Atos 5:32', 'Atos', 5, 32, NULL),
  ('recebimento', 'E a esperança não traz confusão, porquanto o amor de Deus está derramado em nosso coração pelo Espírito Santo que nos foi dado.', 'Romanos 5:5', 'Romanos', 5, 5, NULL),
  ('recebimento', 'Porque necessitais de paciência, para que, depois de haverdes feito a vontade de Deus, possais alcançar a promessa.', 'Hebreus 10:36', 'Hebreus', 10, 36, NULL),
  ('recebimento', 'Todavia, digo-vos a verdade: que vos convém que eu vá, porque, se eu não for, o Consolador não virá a vós; mas, se eu for, enviar-vo-lo-ei.', 'João 16:7', 'João', 16, 7, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('recebimento', 'Eis aqui o que eu vi, uma boa e bela coisa: comer, e beber, e gozar cada um do bem de todo o seu trabalho, em que trabalhou debaixo do sol, todos os dias da sua vida que Deus lhe deu; porque esta é a sua porção.', 'Eclesiastes 5:18', 'Eclesiastes', 5, 18, NULL),
  ('recebimento', 'Então, disse o Senhor a Moisés: Sobe a mim, ao monte, e fica lá; e dar-te-ei tábuas de pedra, e a lei, e os mandamentos que tenho escrito, para os ensinares.', 'Êxodo 24:12', 'Êxodo', 24, 12, NULL),
  ('recompensa', 'E, tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens, sabendo que recebereis do Senhor o galardão da herança, porque a Cristo, o Senhor, servis.', 'Colossenses 3:23-24', 'Colossenses', 3, 23, 24),
  ('recompensa', 'O qual recompensará cada um segundo as suas obras.', 'Romanos 2:6', 'Romanos', 2, 6, NULL),
  ('recompensa', 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.', '1 Coríntios 15:58', '1 Coríntios', 15, 58, NULL),
  ('recompensa', 'E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não houvermos desfalecido.', 'Gálatas 6:9', 'Gálatas', 6, 9, NULL),
  ('recompensa', 'E o seu senhor lhe disse: Bem está, servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor.', 'Mateus 25:21', 'Mateus', 25, 21, NULL),
  ('recompensa', 'Não te desamparem a benignidade e a fidelidade; ata-as ao teu pescoço; escreve-as na tábua do teu coração e acharás graça e bom entendimento aos olhos de Deus e dos homens.', 'Provérbios 3:3-4', 'Provérbios', 3, 3, 4),
  ('recompensa', 'O presente do homem alarga-lhe o caminho e leva-o à presença dos grandes.', 'Provérbios 18:16', 'Provérbios', 18, 16, NULL),
  ('recompensa', 'Bem-aventurado o varão que sofre a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam.', 'Tiago 1:12', 'Tiago', 1, 12, NULL),
  ('recompensa', 'Mas, como está escrito: As coisas que o olho não viu, e o ouvido não ouviu, e não subiram ao coração do homem são as que Deus preparou para os que o amam.', '1 Coríntios 2:9', '1 Coríntios', 2, 9, NULL),
  ('recompensa', 'O galardão da humildade e o temor do Senhor são riquezas, e honra, e vida.', 'Provérbios 22:4', 'Provérbios', 22, 4, NULL),
  ('recompensa', 'Quando, pois, deres esmola, não faças tocar trombeta diante de ti, como fazem os hipócritas nas sinagogas e nas ruas, para serem glorificados pelos homens. Em verdade vos digo que já receberam o seu galardão.', 'Mateus 6:2', 'Mateus', 6, 2, NULL),
  ('recompensa', 'Andareis em todo o caminho que vos manda o Senhor, vosso Deus, para que vivais, e bem vos suceda, e prolongueis os dias na terra que haveis de possuir.', 'Deuteronômio 5:33', 'Deuteronômio', 5, 33, NULL),
  ('recompensa', 'Prossigo para o alvo, pelo prêmio da soberana vocação de Deus em Cristo Jesus.', 'Filipenses 3:14', 'Filipenses', 3, 14, NULL),
  ('recompensa', 'Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando vos darão; porque com a mesma medida com que medirdes também vos medirão de novo.', 'Lucas 6:38', 'Lucas', 6, 38, NULL),
  ('recompensa', 'Pedi, e dar-se-vos-á; buscai e encontrareis; batei, e abrir-se-vos-á.', 'Mateus 7:7', 'Mateus', 7, 7, NULL),
  ('recompensa', 'E, se fizerdes bem aos que vos fazem bem, que recompensa tereis? Também os pecadores fazem o mesmo.', 'Lucas 6:33', 'Lucas', 6, 33, NULL),
  ('recompensa', 'Ora, sem fé é impossível agradar-lhe, porque é necessário que aquele que se aproxima de Deus creia que ele existe e que é galardoador dos que o buscam.', 'Hebreus 11:6', 'Hebreus', 11, 6, NULL),
  ('recompensa', 'Então, dali, buscarás ao Senhor, teu Deus, e o acharás, quando o buscares de todo o teu coração e de toda a tua alma.', 'Deuteronômio 4:29', 'Deuteronômio', 4, 29, NULL),
  ('recompensa', 'E eis que cedo venho, e o meu galardão está comigo para dar a cada um segundo a sua obra.', 'Apocalipse 22:12', 'Apocalipse', 22, 12, NULL),
  ('recompensa', 'Porém muitos primeiros serão derradeiros, e muitos derradeiros serão primeiros.', 'Mateus 19:30', 'Mateus', 19, 30, NULL),
  ('recompensa', 'O ímpio recebe um salário enganoso, mas, para o que semeia justiça, haverá galardão certo.', 'Provérbios 11:18', 'Provérbios', 11, 18, NULL),
  ('recompensa', 'Mas tu, quando orares, entra no teu aposento e, fechando a tua porta, ora a teu Pai, que vê o que está oculto; e teu Pai, que vê o que está oculto, te recompensará.', 'Mateus 6:6', 'Mateus', 6, 6, NULL),
  ('recompensa', 'Humilhai-vos, pois, debaixo da potente mão de Deus, para que, a seu tempo, vos exalte.', '1 Pedro 5:6', '1 Pedro', 5, 6, NULL),
  ('recompensa', 'Enganoso é o coração, mais do que todas as coisas, e perverso; quem o conhecerá? Eu, o Senhor, esquadrinho o coração, eu provo os pensamentos; e isso para dar a cada um segundo os seus caminhos e segundo o fruto das suas ações.', 'Jeremias 17:9-10', 'Jeremias', 17, 9, 10),
  ('recompensa', 'Buscai o bem e não o mal, para que vivais; e assim o Senhor, o Deus dos Exércitos, estará convosco, como dizeis.', 'Amós 5:14', 'Amós', 5, 14, NULL),
  ('recompensa', 'Humilhai-vos perante o Senhor, e ele vos exaltará.', 'Tiago 4:10', 'Tiago', 4, 10, NULL),
  ('recompensa', 'Olhai por vós mesmos, para que não percamos o que temos ganhado; antes, recebamos o inteiro galardão.', '2 João 1:8', '2 João', 1, 8, NULL),
  ('recompensa', 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus, nosso Senhor.', 'Romanos 6:23', 'Romanos', 6, 23, NULL),
  ('recompensa', 'Se vós estiverdes em mim, e as minhas palavras estiverem em vós, pedireis tudo o que quiserdes, e vos será feito.', 'João 15:7', 'João', 15, 7, NULL),
  ('recompensa', 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente.', '2 Coríntios 4:17', '2 Coríntios', 4, 17, NULL),
  ('recompensa', 'E todo aquele que luta de tudo se abstém; eles o fazem para alcançar uma coroa corruptível, nós, porém, uma incorruptível.', '1 Coríntios 9:25', '1 Coríntios', 9, 25, NULL),
  ('recompensa', 'Porque persuado eu agora a homens ou a Deus? Ou procuro agradar a homens? Se estivesse ainda agradando aos homens, não seria servo de Cristo.', 'Gálatas 1:10', 'Gálatas', 1, 10, NULL),
  ('recompensa', 'Como contristados, mas sempre alegres; como pobres, mas enriquecendo a muitos; como nada tendo e possuindo tudo.', '2 Coríntios 6:10', '2 Coríntios', 6, 10, NULL),
  ('recompensa', 'Eis que venho sem demora; guarda o que tens, para que ninguém tome a tua coroa.', 'Apocalipse 3:11', 'Apocalipse', 3, 11, NULL),
  ('recompensa', 'Portanto, irmãos, procurai fazer cada vez mais firme a vossa vocação e eleição; porque, fazendo isto, nunca jamais tropeçareis. Porque assim vos será amplamente concedida a entrada no Reino eterno de nosso Senhor e Salvador Jesus Cristo.', '2 Pedro 1:10-11', '2 Pedro', 1, 10, 11),
  ('recompensa', 'A mão dos diligentes dominará, mas os enganadores serão tributários.', 'Provérbios 12:24', 'Provérbios', 12, 24, NULL),
  ('recompensa', 'Ao que vencer, lhe concederei que se assente comigo no meu trono, assim como eu venci e me assentei com meu Pai no seu trono.', 'Apocalipse 3:21', 'Apocalipse', 3, 21, NULL),
  ('recompensa', 'Combati o bom combate, acabei a carreira, guardei a fé. Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele Dia; e não somente a mim, mas também a todos os que amarem a sua vinda.', '2 Timóteo 4:7-8', '2 Timóteo', 4, 7, 8),
  ('recompensa', 'Eu sou a videira, vós, as varas; quem está em mim, e eu nele, este dá muito fruto, porque sem mim nada podereis fazer.', 'João 15:5', 'João', 15, 5, NULL),
  ('recompensa', 'Bem-aventurada é a nação cujo Deus é o Senhor, e o povo que ele escolheu para a sua herança.', 'Salmo 33:12', 'Salmo', 33, 12, NULL),
  ('recompensa', 'A ti também, Senhor, pertence a misericórdia; pois retribuirás a cada um segundo a sua obra.', 'Salmo 62:12', 'Salmo', 62, 12, NULL),
  ('recompensa', 'E, quando jejuardes, não vos mostreis contristados como os hipócritas, porque desfiguram o rosto, para que aos homens pareça que jejuam. Em verdade vos digo que já receberam o seu galardão.', 'Mateus 6:16', 'Mateus', 6, 16, NULL),
  ('recompensa', 'Pelas quais ele nos tem dado grandíssimas e preciosas promessas, para que por elas fiqueis participantes da natureza divina, havendo escapado da corrupção, que, pela concupiscência, há no mundo.', '2 Pedro 1:4', '2 Pedro', 1, 4, NULL),
  ('recompensa', 'Pela fé, também a mesma Sara recebeu a virtude de conceber e deu à luz já fora da idade; porquanto teve por fiel aquele que lho tinha prometido.', 'Hebreus 11:11', 'Hebreus', 11, 11, NULL),
  ('recompensa', 'Mas, quando tu deres esmola, não saiba a tua mão esquerda o que faz a tua direita, para que a tua esmola seja dada ocultamente, e teu Pai, que vê em secreto, te recompensará publicamente.', 'Mateus 6:3-4', 'Mateus', 6, 3, 4),
  ('recompensa', 'Porém tu, quando jejuares, unge a cabeça e lava o rosto, para não pareceres aos homens que jejuas, mas sim a teu Pai, que está oculto; e teu Pai, que vê o que está oculto, te recompensará.', 'Mateus 6:17-18', 'Mateus', 6, 17, 18),
  ('recompensa', 'Mas, se deveras melhorardes os vossos caminhos e as vossas obras, se deveras fizerdes juízo entre um homem e entre o seu companheiro, se não oprimirdes o estrangeiro, e o órfão, e a viúva, nem derramardes sangue inocente neste lugar, nem andardes após outros deuses para vosso próprio mal, eu vos farei habitar neste lugar, na terra que dei a vossos pais, de século em século.', 'Jeremias 7:5-7', 'Jeremias', 7, 5, 7),
  ('recompensa', 'E eles serão meus, diz o Senhor dos Exércitos, naquele dia que farei, serão para mim particular tesouro; poupá-los-ei como um homem poupa a seu filho que o serve.', 'Malaquias 3:17', 'Malaquias', 3, 17, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('recompensa', 'Porque o Filho do Homem virá na glória de seu Pai, com os seus anjos; e, então, dará a cada um segundo as suas obras.', 'Mateus 16:27', 'Mateus', 16, 27, NULL),
  ('reconciliacao', 'Isto é, Deus estava em Cristo reconciliando consigo o mundo, não lhes imputando os seus pecados, e pôs em nós a palavra da reconciliação.', '2 Coríntios 5:19', '2 Coríntios', 5, 19, NULL),
  ('reconciliacao', 'Antes, sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo.', 'Efésios 4:32', 'Efésios', 4, 32, NULL),
  ('reconciliacao', 'Suportando-vos uns aos outros e perdoando-vos uns aos outros, se algum tiver queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também.', 'Colossenses 3:13', 'Colossenses', 3, 13, NULL),
  ('reconciliacao', 'Ora, se teu irmão pecar contra ti, vai e repreende-o entre ti e ele só; se te ouvir, ganhaste a teu irmão.', 'Mateus 18:15', 'Mateus', 18, 15, NULL),
  ('reconciliacao', 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, e venham, assim, os tempos do refrigério pela presença do Senhor.', 'Atos 3:19', 'Atos', 3, 19, NULL),
  ('reconciliacao', 'Porque, se nós, sendo inimigos, fomos reconciliados com Deus pela morte de seu Filho, muito mais, estando já reconciliados, seremos salvos pela sua vida.', 'Romanos 5:10', 'Romanos', 5, 10, NULL),
  ('reconciliacao', 'Segui a paz com todos e a santificação, sem a qual ninguém verá o Senhor.', 'Hebreus 12:14', 'Hebreus', 12, 14, NULL),
  ('reconciliacao', 'Nisto está o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou e enviou seu Filho para propiciação pelos nossos pecados.', '1 João 4:10', '1 João', 4, 10, NULL),
  ('reconciliacao', 'E tudo isso provém de Deus, que nos reconciliou consigo mesmo por Jesus Cristo e nos deu o ministério da reconciliação.', '2 Coríntios 5:18', '2 Coríntios', 5, 18, NULL),
  ('reconciliacao', 'Ajuda-nos, ó Deus da nossa salvação, pela glória do teu nome; e livra-nos e perdoa os nossos pecados, por amor do teu nome.', 'Salmo 79:9', 'Salmo', 79, 9, NULL),
  ('reconciliacao', 'E ele é a propiciação pelos nossos pecados e não somente pelos nossos, mas também pelos de todo o mundo.', '1 João 2:2', '1 João', 2, 2, NULL),
  ('reconhecer', 'Qualquer que confessar que Jesus é o Filho de Deus, Deus está nele e ele em Deus.', '1 João 4:15', '1 João', 4, 15, NULL),
  ('reconhecer', 'Retenhamos firmes a confissão da nossa esperança, porque fiel é o que prometeu.', 'Hebreus 10:23', 'Hebreus', 10, 23, NULL),
  ('reconhecer', 'E toda língua confesse que Jesus Cristo é o Senhor, para glória de Deus Pai.', 'Filipenses 2:11', 'Filipenses', 2, 11, NULL),
  ('reconhecer', 'A minha porção é o Senhor, diz a minha alma; portanto, esperarei nele.', 'Lamentações 3:24', 'Lamentações', 3, 24, NULL),
  ('reconhecer', 'Visto que com o coração se crê para a justiça, e com a boca se faz confissão para a salvação.', 'Romanos 10:10', 'Romanos', 10, 10, NULL),
  ('reconhecer', 'Porque está escrito: Pela minha vida, diz o Senhor, todo joelho se dobrará diante de mim, e toda língua confessará a Deus.', 'Romanos 14:11', 'Romanos', 14, 11, NULL),
  ('reconhecer', 'A saber: Se, com a tua boca, confessares ao Senhor Jesus e, em teu coração, creres que Deus o ressuscitou dos mortos, serás salvo.', 'Romanos 10:9', 'Romanos', 10, 9, NULL),
  ('reconhecer', 'Milita a boa milícia da fé, toma posse da vida eterna, para a qual também foste chamado, tendo já feito boa confissão diante de muitas testemunhas.', '1 Timóteo 6:12', '1 Timóteo', 6, 12, NULL),
  ('reconhecer', 'Confessei-te o meu pecado e a minha maldade não encobri; dizia eu: Confessarei ao Senhor as minhas transgressões; e tu perdoaste a maldade do meu pecado. (Selá)', 'Salmo 32:5', 'Salmo', 32, 5, NULL),
  ('reconhecer', 'Quem é este Rei da Glória? O Senhor dos Exércitos; ele é o Rei da Glória. (Selá)', 'Salmo 24:10', 'Salmo', 24, 10, NULL),
  ('reconhecer', 'O que vencer será vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; e confessarei o seu nome diante de meu Pai e diante dos seus anjos.', 'Apocalipse 3:5', 'Apocalipse', 3, 5, NULL),
  ('reconhecer', 'Qualquer que nega o Filho também não tem o Pai; e aquele que confessa o Filho tem também o Pai.', '1 João 2:23', '1 João', 2, 23, NULL),
  ('reconhecer', 'Nisto conhecereis o Espírito de Deus: todo espírito que confessa que Jesus Cristo veio em carne é de Deus; e todo espírito que não confessa que Jesus Cristo veio em carne não é de Deus; mas este é o espírito do anticristo, do qual já ouvistes que há de vir, e eis que está já no mundo.', '1 João 4:2-3', '1 João', 4, 2, 3),
  ('reconhecer', 'E eis que uma voz dos céus dizia: Este é o meu Filho amado, em quem me comprazo.', 'Mateus 3:17', 'Mateus', 3, 17, NULL),
  ('redentor', 'O Senhor, teu Deus, está no meio de ti, poderoso para te salvar; ele se deleitará em ti com alegria; calar-se-á por seu amor, regozijar-se-á em ti com júbilo.', 'Sofonias 3:17', 'Sofonias', 3, 17, NULL),
  ('redentor', 'Eu te amarei do coração, ó Senhor, fortaleza minha. O Senhor é o meu rochedo, e o meu lugar forte, e o meu libertador; o meu Deus, a minha fortaleza, em quem confio; o meu escudo, a força da minha salvação e o meu alto refúgio.', 'Salmo 18:1-2', 'Salmo', 18, 1, 2),
  ('redentor', 'O qual se deu a si mesmo por nós, para nos remir de toda iniquidade e purificar para si um povo seu especial, zeloso de boas obras.', 'Tito 2:14', 'Tito', 2, 14, NULL),
  ('redentor', 'Estai, pois, firmes na liberdade com que Cristo nos libertou e não torneis a meter-vos debaixo do jugo da servidão.', 'Gálatas 5:1', 'Gálatas', 5, 1, NULL),
  ('redentor', 'Os justos clamam, e o Senhor os ouve e os livra de todas as suas angústias. Perto está o Senhor dos que têm o coração quebrantado e salva os contritos de espírito.', 'Salmo 34:17-18', 'Salmo', 34, 17, 18),
  ('redentor', 'Desfaço as tuas transgressões como a névoa, e os teus pecados, como a nuvem; torna-te para mim, porque eu te remi.', 'Isaías 44:22', 'Isaías', 44, 22, NULL),
  ('redentor', 'Se, pois, o Filho vos libertar, verdadeiramente, sereis livres.', 'João 8:36', 'João', 8, 36, NULL),
  ('redentor', 'Muitas são as aflições do justo, mas o Senhor o livra de todas.', 'Salmo 34:19', 'Salmo', 34, 19, NULL),
  ('redentor', 'Portanto, agora, nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o espírito. Porque a lei do Espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte.', 'Romanos 8:1-2', 'Romanos', 8, 1, 2),
  ('redentor', 'Regozijar-me-ei muito no Senhor, a minha alma se alegra no meu Deus, porque me vestiu de vestes de salvação, me cobriu com o manto de justiça, como um noivo que se adorna com atavios e como noiva que se enfeita com as suas joias.', 'Isaías 61:10', 'Isaías', 61, 10, NULL),
  ('redentor', 'Os meus lábios exultarão quando eu te cantar, assim como a minha alma que tu remiste.', 'Salmo 71:23', 'Salmo', 71, 23, NULL),
  ('redentor', 'Os meus tempos estão nas tuas mãos; livra-me das mãos dos meus inimigos e dos que me perseguem.', 'Salmo 31:15', 'Salmo', 31, 15, NULL),
  ('redentor', 'E ela dará à luz um filho, e lhe porás o nome de Jesus, porque ele salvará o seu povo dos seus pecados.', 'Mateus 1:21', 'Mateus', 1, 21, NULL),
  ('redentor', 'O Espírito do Senhor Jeová está sobre mim, porque o Senhor me ungiu para pregar boas-novas aos mansos; enviou-me a restaurar os contritos de coração, a proclamar liberdade aos cativos e a abertura de prisão aos presos.', 'Isaías 61:1', 'Isaías', 61, 1, NULL),
  ('redentor', 'Em ti, Senhor, confio; nunca me deixes confundido; livra-me pela tua justiça.', 'Salmo 31:1', 'Salmo', 31, 1, NULL),
  ('redentor', 'Mas, agora, libertados do pecado e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna.', 'Romanos 6:22', 'Romanos', 6, 22, NULL),
  ('redentor', 'Vós que amais ao Senhor, aborrecei o mal; ele guarda a alma dos seus santos, ele os livra das mãos dos ímpios.', 'Salmo 97:10', 'Salmo', 97, 10, NULL),
  ('redentor', 'Ajuda-nos, ó Deus da nossa salvação, pela glória do teu nome; e livra-nos e perdoa os nossos pecados, por amor do teu nome.', 'Salmo 79:9', 'Salmo', 79, 9, NULL),
  ('redentor', 'Senhor, livra a minha alma dos lábios mentirosos e da língua enganadora.', 'Salmo 120:2', 'Salmo', 120, 2, NULL),
  ('reino', 'Não sabeis que os injustos não hão de herdar o Reino de Deus? Não erreis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas, nem os ladrões, nem os avarentos, nem os bêbados, nem os maldizentes, nem os roubadores herdarão o Reino de Deus.', '1 Coríntios 6:9-10', '1 Coríntios', 6, 9, 10),
  ('reino', 'Mas buscai primeiro o Reino de Deus, e a sua justiça, e todas essas coisas vos serão acrescentadas.', 'Mateus 6:33', 'Mateus', 6, 33, NULL),
  ('reino', 'Tua é, Senhor, a magnificência, e o poder, e a honra, e a vitória, e a majestade; porque teu é tudo quanto há nos céus e na terra; teu é, Senhor, o reino, e tu te exaltaste sobre todos como chefe.', '1 Crônicas 29:11', '1 Crônicas', 29, 11, NULL),
  ('reino', 'Não temas, ó pequeno rebanho, porque a vosso Pai agradou dar-vos o Reino.', 'Lucas 12:32', 'Lucas', 12, 32, NULL),
  ('reino', 'Desde então, começou Jesus a pregar e a dizer: Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 4:17', 'Mateus', 4, 17, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('reino', 'Jesus, porém, disse: Deixai os pequeninos e não os estorveis de vir a mim, porque dos tais é o Reino dos céus.', 'Mateus 19:14', 'Mateus', 19, 14, NULL),
  ('reino', 'Jesus respondeu e disse-lhe: Na verdade, na verdade te digo que aquele que não nascer de novo não pode ver o Reino de Deus.', 'João 3:3', 'João', 3, 3, NULL),
  ('reino', 'E eu te darei as chaves do Reino dos céus, e tudo o que ligares na terra será ligado nos céus, e tudo o que desligares na terra será desligado nos céus.', 'Mateus 16:19', 'Mateus', 16, 19, NULL),
  ('reino', 'E o Senhor será rei sobre toda a terra; naquele dia, um será o Senhor, e um será o seu nome.', 'Zacarias 14:9', 'Zacarias', 14, 9, NULL),
  ('reino', 'Assim que já não sois estrangeiros, nem forasteiros, mas concidadãos dos Santos e da família de Deus; edificados sobre o fundamento dos apóstolos e dos profetas, de que Jesus Cristo é a principal pedra da esquina.', 'Efésios 2:19-20', 'Efésios', 2, 19, 20),
  ('reino', 'Portanto, irmãos, procurai fazer cada vez mais firme a vossa vocação e eleição; porque, fazendo isto, nunca jamais tropeçareis. Porque assim vos será amplamente concedida a entrada no Reino eterno de nosso Senhor e Salvador Jesus Cristo.', '2 Pedro 1:10-11', '2 Pedro', 1, 10, 11),
  ('reino', 'O tempo está cumprido, e o Reino de Deus está próximo. Arrependei-vos e crede no evangelho.', 'Marcos 1:15', 'Marcos', 1, 15, NULL),
  ('reino', 'E curai os enfermos que nela houver e dizei-lhes: É chegado a vós o Reino de Deus.', 'Lucas 10:9', 'Lucas', 10, 9, NULL),
  ('reino', 'Quão suaves são sobre os montes os pés do que anuncia as boas-novas, que faz ouvir a paz, que anuncia o bem, que faz ouvir a salvação, que diz a Sião: O teu Deus reina!', 'Isaías 52:7', 'Isaías', 52, 7, NULL),
  ('reino', 'Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor, em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados.', 'Colossenses 1:13-14', 'Colossenses', 1, 13, 14),
  ('reino', 'Bem-aventurados os que sofrem perseguição por causa da justiça, porque deles é o Reino dos céus.', 'Mateus 5:10', 'Mateus', 5, 10, NULL),
  ('reino', 'Porque o Senhor é o nosso Juiz; o Senhor é o nosso Legislador; o Senhor é o nosso Rei; ele nos salvará.', 'Isaías 33:22', 'Isaías', 33, 22, NULL),
  ('reino', 'Jesus respondeu: Na verdade, na verdade te digo que aquele que não nascer da água e do Espírito não pode entrar no Reino de Deus.', 'João 3:5', 'João', 3, 5, NULL),
  ('reino', 'Quem é este Rei da Glória? O Senhor dos Exércitos; ele é o Rei da Glória. (Selá)', 'Salmo 24:10', 'Salmo', 24, 10, NULL),
  ('reino', 'Qualquer, pois, que violar um destes menores mandamentos e assim ensinar aos homens será chamado o menor no Reino dos céus; aquele, porém, que os cumprir e ensinar será chamado grande no Reino dos céus.', 'Mateus 5:19', 'Mateus', 5, 19, NULL),
  ('reino', 'Nem todo o que me diz: Senhor, Senhor! entrará no Reino dos céus, mas aquele que faz a vontade de meu Pai, que está nos céus.', 'Mateus 7:21', 'Mateus', 7, 21, NULL),
  ('reino', 'Portanto, vós orareis assim: Pai nosso, que estás nos céus, santificado seja o teu nome. Venha o teu Reino. Seja feita a tua vontade, tanto na terra como no céu.', 'Mateus 6:9-10', 'Mateus', 6, 9, 10),
  ('reino', 'Bem-aventurado e santo aquele que tem parte na primeira ressurreição; sobre estes não tem poder a segunda morte, mas serão sacerdotes de Deus e de Cristo e reinarão com ele mil anos.', 'Apocalipse 20:6', 'Apocalipse', 20, 6, NULL),
  ('reino', 'Ora, ao Rei dos séculos, imortal, invisível, ao único Deus seja honra e glória para todo o sempre. Amém!', '1 Timóteo 1:17', '1 Timóteo', 1, 17, NULL),
  ('reino', 'Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 3:2', 'Mateus', 3, 2, NULL),
  ('reino', 'Porque as obras da carne são manifestas, as quais são: prostituição, impureza, lascívia, idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias, invejas, homicídios, bebedices, glutonarias e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas não herdarão o Reino de Deus.', 'Gálatas 5:19-21', 'Gálatas', 5, 19, 21),
  ('reino', 'Tu, Senhor, permaneces eternamente, e o teu trono, de geração em geração.', 'Lamentações 5:19', 'Lamentações', 5, 19, NULL),
  ('reino', 'E este evangelho do Reino será pregado em todo o mundo, em testemunho a todas as gentes, e então virá o fim.', 'Mateus 24:14', 'Mateus', 24, 14, NULL),
  ('reino', 'Bem-aventurados os pobres de espírito, porque deles é o Reino dos céus.', 'Mateus 5:3', 'Mateus', 5, 3, NULL),
  ('reino', 'E percorria Jesus toda a Galileia, ensinando nas suas sinagogas, e pregando o evangelho do Reino, e curando todas as enfermidades e moléstias entre o povo.', 'Mateus 4:23', 'Mateus', 4, 23, NULL),
  ('reino', 'Também o Reino dos céus é semelhante a um tesouro escondido n um campo que um homem achou e escondeu; e, pelo gozo dele, vai, vende tudo quanto tem e compra aquele campo.', 'Mateus 13:44', 'Mateus', 13, 44, NULL),
  ('reino', 'Respondeu Jesus: O meu Reino não é deste mundo; se o meu Reino fosse deste mundo, lutariam os meus servos, para que eu não fosse entregue aos judeus; mas, agora, o meu Reino não é daqui.', 'João 18:36', 'João', 18, 36, NULL),
  ('reino', 'A Lei e os Profetas duraram até João; desde então, é anunciado o Reino de Deus, e todo homem emprega força para entrar nele.', 'Lucas 16:16', 'Lucas', 16, 16, NULL),
  ('relacionamentos', 'E, se alguém quiser prevalecer contra um, os dois lhe resistirão; e o cordão de três dobras não se quebra tão depressa.', 'Eclesiastes 4:12', 'Eclesiastes', 4, 12, NULL),
  ('relacionamentos', 'Mulher virtuosa, quem a achará? O seu valor muito excede o de rubins.', 'Provérbios 31:10', 'Provérbios', 31, 10, NULL),
  ('relacionamentos', 'Porque, se um cair, o outro levanta o seu companheiro; mas ai do que estiver só; pois, caindo, não haverá outro que o levante.', 'Eclesiastes 4:10', 'Eclesiastes', 4, 10, NULL),
  ('relacionamentos', 'Tu és toda formosa, amiga minha, e em ti não há mancha.', 'Cantares 4:7', 'Cantares', 4, 7, NULL),
  ('relacionamentos', 'E vós também, pondo nisto mesmo toda a diligência, acrescentai à vossa fé a virtude, e à virtude, a ciência, e à ciência, a temperança, e à temperança, a paciência, e à paciência, a piedade, e à piedade, a fraternidade, e à fraternidade, o amor.', '2 Pedro 1:5-7', '2 Pedro', 1, 5, 7),
  ('relacionamentos', 'Melhor é serem dois do que um, porque têm melhor paga do seu trabalho.', 'Eclesiastes 4:9', 'Eclesiastes', 4, 9, NULL),
  ('relacionamentos', 'Vós, maridos, amai vossa mulher, como também Cristo amou a igreja e a si mesmo se entregou por ela, para a santificar, purificando-a com a lavagem da água, pela palavra.', 'Efésios 5:25-26', 'Efésios', 5, 25, 26),
  ('relacionamentos', 'E o Senhor vos aumente e faça crescer em amor uns para com os outros e para com todos, como também nós para convosco.', '1 Tessalonicenses 3:12', '1 Tessalonicenses', 3, 12, NULL),
  ('relacionamentos', 'Portanto, tudo o que vós quereis que os homens vos façam, fazei-lho também vós, porque esta é a lei e os profetas.', 'Mateus 7:12', 'Mateus', 7, 12, NULL),
  ('relacionamentos', 'Não vos prendais a um jugo desigual com os infiéis; porque que sociedade tem a justiça com a injustiça? E que comunhão tem a luz com as trevas?', '2 Coríntios 6:14', '2 Coríntios', 6, 14, NULL),
  ('relacionamentos', 'Vós, mulheres, estai sujeitas a vosso próprio marido, como convém no Senhor. Vós, maridos, amai a vossa mulher e não vos irriteis contra ela.', 'Colossenses 3:18-19', 'Colossenses', 3, 18, 19),
  ('relacionamentos', 'A casa e a fazenda são a herança dos pais; mas do Senhor vem a mulher prudente.', 'Provérbios 19:14', 'Provérbios', 19, 14, NULL),
  ('relacionamentos', 'E disse o Senhor Deus: Não é bom que o homem esteja só; far-lhe-ei uma adjutora que esteja como diante dele.', 'Gênesis 2:18', 'Gênesis', 2, 18, NULL),
  ('relacionamentos', 'Mas, por causa da prostituição, cada um tenha a sua própria mulher, e cada uma tenha o seu próprio marido.', '1 Coríntios 7:2', '1 Coríntios', 7, 2, NULL),
  ('relacionamentos', 'Como o ferro com o ferro se aguça, assim o homem afia o rosto do seu amigo.', 'Provérbios 27:17', 'Provérbios', 27, 17, NULL),
  ('relacionamentos', 'Porque persuado eu agora a homens ou a Deus? Ou procuro agradar a homens? Se estivesse ainda agradando aos homens, não seria servo de Cristo.', 'Gálatas 1:10', 'Gálatas', 1, 10, NULL),
  ('relacionamentos', 'Mas, se alguém não tem cuidado dos seus e principalmente dos da sua família, negou a fé e é pior do que o infiel.', '1 Timóteo 5:8', '1 Timóteo', 5, 8, NULL),
  ('relacionamentos', 'Em todo o tempo ama o amigo; e na angústia nasce o irmão.', 'Provérbios 17:17', 'Provérbios', 17, 17, NULL),
  ('relacionamentos', 'Vós, mulheres, sujeitai-vos a vosso marido, como ao Senhor; porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo.', 'Efésios 5:22-23', 'Efésios', 5, 22, 23),
  ('relacionamentos', 'Assim devem os maridos amar a sua própria mulher como a seu próprio corpo. Quem ama a sua mulher ama-se a si mesmo.', 'Efésios 5:28', 'Efésios', 5, 28, NULL),
  ('relacionamentos', 'Mais digno de ser escolhido é o bom nome do que as muitas riquezas; e a graça é melhor do que a riqueza e o ouro.', 'Provérbios 22:1', 'Provérbios', 22, 1, NULL),
  ('relacionamentos', 'Assim também vós, cada um em particular ame a sua própria mulher como a si mesmo, e a mulher reverencie o marido.', 'Efésios 5:33', 'Efésios', 5, 33, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('relacionamentos', 'Não matarás, não cometerás adultério, não furtarás, não dirás falso testemunho; honra teu pai e tua mãe, e amarás o teu próximo como a ti mesmo.', 'Mateus 19:18b-19', 'Mateus 19:18b-19', NULL, NULL, NULL),
  ('renascimento', 'Assim que, se alguém está em Cristo, nova criatura é: as coisas velhas já passaram; eis que tudo se fez novo.', '2 Coríntios 5:17', '2 Coríntios', 5, 17, NULL),
  ('renascimento', 'Jesus respondeu e disse-lhe: Na verdade, na verdade te digo que aquele que não nascer de novo não pode ver o Reino de Deus.', 'João 3:3', 'João', 3, 3, NULL),
  ('renascimento', 'Sendo de novo gerados, não de semente corruptível, mas da incorruptível, pela palavra de Deus, viva e que permanece para sempre.', '1 Pedro 1:23', '1 Pedro', 1, 23, NULL),
  ('renascimento', 'Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.', '1 João 5:4', '1 João', 5, 4, NULL),
  ('renascimento', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que, segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos.', '1 Pedro 1:3', '1 Pedro', 1, 3, NULL),
  ('renascimento', 'Tendo por certo isto mesmo: que aquele que em vós começou a boa obra a aperfeiçoará até ao Dia de Jesus Cristo.', 'Filipenses 1:6', 'Filipenses', 1, 6, NULL),
  ('renascimento', 'Não pelas obras de justiça que houvéssemos feito, mas, segundo a sua misericórdia, nos salvou pela lavagem da regeneração e da renovação do Espírito Santo.', 'Tito 3:5', 'Tito', 3, 5, NULL),
  ('renascimento', 'O que é nascido da carne é carne, e o que é nascido do Espírito é espírito.', 'João 3:6', 'João', 3, 6, NULL),
  ('renascimento', 'Jesus respondeu: Na verdade, na verdade te digo que aquele que não nascer da água e do Espírito não pode entrar no Reino de Deus.', 'João 3:5', 'João', 3, 5, NULL),
  ('renascimento', 'Amados, amemo-nos uns aos outros, porque o amor é de Deus; e qualquer que ama é nascido de Deus e conhece a Deus.', '1 João 4:7', '1 João', 4, 7, NULL),
  ('renascimento', 'Desejai afetuosamente, como meninos novamente nascidos, o leite racional, não falsificado, para que, por ele, vades crescendo.', '1 Pedro 2:2', '1 Pedro', 2, 2, NULL),
  ('ressurreicao', 'Disse-lhe Jesus: Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá; e todo aquele que vive e crê em mim nunca morrerá. Crês tu isso?', 'João 11:25-26', 'João', 11, 25, 26),
  ('ressurreicao', 'Porém ele disse-lhes: Não vos assusteis; buscais a Jesus, o Nazareno, que foi crucificado; já ressuscitou, não está aqui; eis aqui o lugar onde o puseram.', 'Marcos 16:6', 'Marcos', 16, 6, NULL),
  ('ressurreicao', 'Não está aqui, mas ressuscitou. Lembrai-vos como vos falou, estando ainda na Galileia, dizendo: Convém que o Filho do Homem seja entregue nas mãos de homens pecadores, e seja crucificado, e, ao terceiro dia, ressuscite.', 'Lucas 24:6-7', 'Lucas', 24, 6, 7),
  ('ressurreicao', 'Porque, se cremos que Jesus morreu e ressuscitou, assim também aos que em Jesus dormem Deus os tornará a trazer com ele.', '1 Tessalonicenses 4:14', '1 Tessalonicenses', 4, 14, NULL),
  ('ressurreicao', 'Mas o anjo, respondendo, disse às mulheres: Não tenhais medo; pois eu sei que buscai a Jesus, que foi crucificado. Ele não está aqui, porque já ressuscitou, como tinha dito. Vinde e vede o lugar onde o Senhor jazia.', 'Mateus 28:5-6', 'Mateus', 28, 5, 6),
  ('ressurreicao', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que, segundo a sua grande misericórdia, nos gerou de novo para uma viva esperança, pela ressurreição de Jesus Cristo dentre os mortos.', '1 Pedro 1:3', '1 Pedro', 1, 3, NULL),
  ('ressurreicao', 'Porque o amor de Cristo nos constrange, julgando nós assim: que, se um morreu por todos, logo, todos morreram. E ele morreu por todos, para que os que vivem não vivam mais para si, mas para aquele que por eles morreu e ressuscitou.', '2 Coríntios 5:14-15', '2 Coríntios', 5, 14, 15),
  ('ressurreicao', 'Porque primeiramente vos entreguei o que também recebi: que Cristo morreu por nossos pecados, segundo as Escrituras, e que foi sepultado, e que ressuscitou ao terceiro dia, segundo as Escrituras.', '1 Coríntios 15:3-4', '1 Coríntios', 15, 3, 4),
  ('ressurreicao', 'Porque, assim como a morte veio por um homem, também a ressurreição dos mortos veio por um homem.', '1 Coríntios 15:21', '1 Coríntios', 15, 21, NULL),
  ('ressurreicao', 'Porque, se fomos plantados juntamente com ele na semelhança da sua morte, também o seremos na da sua ressurreição; sabendo isto: que o nosso velho homem foi com ele crucificado, para que o corpo do pecado seja desfeito, a fim de que não sirvamos mais ao pecado.', 'Romanos 6:5-6', 'Romanos', 6, 5, 6),
  ('ressurreicao', 'Ora, o Deus de paz, que pelo sangue do concerto eterno tornou a trazer dos mortos a nosso Senhor Jesus Cristo, grande Pastor das ovelhas, vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável por Cristo Jesus, ao qual seja glória para todo o sempre. Amém!', 'Hebreus 13:20-21', 'Hebreus', 13, 20, 21),
  ('ressurreicao', 'Para conhecê-lo, e a virtude da sua ressurreição, e a comunicação de suas aflições, sendo feito conforme a sua morte.', 'Filipenses 3:10', 'Filipenses', 3, 10, NULL),
  ('ressurreicao', 'Eis que vamos para Jerusalém, e o Filho do Homem será entregue aos príncipes dos sacerdotes e aos escribas, e condená-lo-ão à morte. E o entregarão aos gentios para que dele escarneçam, e o açoitem, e crucifiquem, e ao terceiro dia ressuscitará.', 'Mateus 20:18-19', 'Mateus', 20, 18, 19),
  ('ressurreicao', 'Então, entrou também o outro discípulo, que chegara primeiro ao sepulcro, e viu, e creu. Porque ainda não sabiam a Escritura, que diz que era necessário que ressuscitasse dos mortos.', 'João 20:8-9', 'João', 20, 8, 9),
  ('ressurreicao', 'E vi os mortos, grandes e pequenos, que estavam diante do trono, e abriram-se os livros. E abriu-se outro livro, que é o da vida. E os mortos foram julgados pelas coisas que estavam escritas nos livros, segundo as suas obras. E deu o mar os mortos que nele havia; e a morte e o inferno deram os mortos que neles havia; e foram julgados cada um segundo as suas obras.', 'Apocalipse 20:12-13', 'Apocalipse', 20, 12, 13),
  ('ressurreicao', 'Bem-aventurado e santo aquele que tem parte na primeira ressurreição; sobre estes não tem poder a segunda morte, mas serão sacerdotes de Deus e de Cristo e reinarão com ele mil anos.', 'Apocalipse 20:6', 'Apocalipse', 20, 6, NULL),
  ('ressurreicao', 'Que também, como uma verdadeira figura, agora vos salva, batismo, não do despojamento da imundícia da carne, mas da indagação de uma boa consciência para com Deus, pela ressurreição de Jesus Cristo.', '1 Pedro 3:21', '1 Pedro', 3, 21, NULL),
  ('ressurreicao', 'Mas, alcançando socorro de Deus, ainda até ao dia de hoje permaneço, dando testemunho, tanto a pequenos como a grandes, não dizendo nada mais do que o que os profetas e Moisés disseram que devia acontecer, isto é, que o Cristo devia padecer e, sendo o primeiro da ressurreição dos mortos, devia anunciar a luz a este povo e aos gentios.', 'Atos 26:22-23', 'Atos', 26, 22, 23),
  ('ressurreicao', 'Ressuscitando Deus a seu Filho Jesus, primeiro o enviou a vós, para que nisso vos abençoasse, e vos desviasse, a cada um, das vossas maldades.', 'Atos 3:26', 'Atos', 3, 26, NULL),
  ('ressurreicao', 'Pelo que, deixando os rudimentos da doutrina de Cristo, prossigamos até a perfeição, não lançando de novo o fundamento do arrependimento de obras mortas e de fé em Deus, e da doutrina dos batismos, e da imposição das mãos, e da ressurreição dos mortos, e do juízo eterno.', 'Hebreus 6:1-2', 'Hebreus', 6, 1, 2),
  ('ressurreicao', 'E ele é a cabeça do corpo da igreja; é o princípio e o primogênito dentre os mortos, para que em tudo tenha a preeminência.', 'Colossenses 1:18', 'Colossenses', 1, 18, NULL),
  ('ressurreicao', 'Ressuscitou, verdadeiramente, o Senhor e já apareceu a Simão.', 'Lucas 24:34', 'Lucas', 24, 34, NULL),
  ('resto', 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.', 'Mateus 11:28', 'Mateus', 11, 28, NULL),
  ('resto', 'A minha alma espera somente em Deus; dele vem a minha salvação.', 'Salmo 62:1', 'Salmo', 62, 1, NULL),
  ('resto', 'Em paz também me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.', 'Salmo 4:8', 'Salmo', 4, 8, NULL),
  ('resto', 'Assim diz o Senhor: Ponde-vos nos caminhos, e vede, e perguntai pelas veredas antigas, qual é o bom caminho, e andai por ele; e achareis descanso para a vossa alma; mas eles dizem: Não andaremos.', 'Jeremias 6:16', 'Jeremias', 6, 16, NULL),
  ('resto', 'O Senhor é o meu pastor; nada me faltará. Deitar-me faz em verdes pastos, guia-me mansamente a águas tranquilas.', 'Salmo 23:1-2', 'Salmo', 23, 1, 2),
  ('resto', 'Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. Direi do Senhor: Ele é o meu Deus, o meu refúgio, a minha fortaleza, e nele confiarei.', 'Salmo 91:1-2', 'Salmo', 91, 1, 2),
  ('resto', 'Portanto, resta ainda um repouso para o povo de Deus. Porque aquele que entrou no seu repouso, ele próprio repousou de suas obras, como Deus das suas.', 'Hebreus 4:9-10', 'Hebreus', 4, 9, 10),
  ('resto', 'Tomai sobre vós o meu jugo, e aprendei de mim, que sou manso e humilde de coração, e encontrareis descanso para a vossa alma. Porque o meu jugo é suave, e o meu fardo é leve.', 'Mateus 11:29-30', 'Mateus', 11, 29, 30),
  ('resto', 'Provai e vede que o Senhor é bom; bem-aventurado o homem que nele confia.', 'Salmo 34:8', 'Salmo', 34, 8, NULL),
  ('resto', 'Procuremos, pois, entrar naquele repouso, para que ninguém caia no mesmo exemplo de desobediência.', 'Hebreus 4:11', 'Hebreus', 4, 11, NULL),
  ('resto', 'Ó minha alma, espera somente em Deus, porque dele vem a minha esperança.', 'Salmo 62:5', 'Salmo', 62, 5, NULL),
  ('resto', 'E já está próximo o fim de todas as coisas; portanto, sede sóbrios e vigiai em oração.', '1 Pedro 4:7', '1 Pedro', 4, 7, NULL),
  ('resto', 'Guarda o dia de sábado, para o santificar, como te ordenou o Senhor, teu Deus. Seis dias trabalharás e farás toda a tua obra. Mas o sétimo dia é o sábado do Senhor, teu Deus; não farás nenhuma obra nele, nem tu, nem teu filho, nem tua filha, nem o teu servo, nem a tua serva, nem o teu boi, nem o teu jumento, nem animal algum teu, nem o estrangeiro que está dentro de tuas portas; para que o teu servo e a tua serva descansem como tu.', 'Deuteronômio 5:12-14', 'Deuteronômio', 5, 12, 14),
  ('roupas', 'O enfeite delas não seja o exterior, no frisado dos cabelos, no uso de joias de ouro, na compostura de vestes, mas o homem encoberto no coração, no incorruptível trajo de um espírito manso e quieto, que é precioso diante de Deus.', '1 Pedro 3:3-4', '1 Pedro', 3, 3, 4),
  ('roupas', 'Que do mesmo modo as mulheres se ataviem em traje honesto, com pudor e modéstia, não com tranças, ou com ouro, ou pérolas, ou vestidos preciosos, mas (como convém a mulheres que fazem profissão de servir a Deus) com boas obras.', '1 Timóteo 2:9-10', '1 Timóteo', 2, 9, 10),
  ('roupas', 'Revesti-vos, pois, como eleitos de Deus, santos e amados, de entranhas de misericórdia, de benignidade, humildade, mansidão, longanimidade.', 'Colossenses 3:12', 'Colossenses', 3, 12, NULL);

