-- Parte 12: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('roupas', 'Por isso, vos digo: não andeis cuidadosos quanto à vossa vida, pelo que haveis de comer ou pelo que haveis de beber; nem quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o mantimento, e o corpo, mais do que a vestimenta?', 'Mateus 6:25', 'Mateus', 6, 25, NULL),
  ('roupas', 'E fez o Senhor', 'Gênesis 3:21', 'Gênesis', 3, 21, NULL),
  ('roupas', 'Regozijar-me-ei muito no Senhor', 'Isaías 61:10', 'Isaías', 61, 10, NULL),
  ('roupas', 'Porque todos sois filhos de Deus pela fé em Cristo Jesus; porque todos quantos fostes batizados em Cristo já vos revestistes de Cristo.', 'Gálatas 3:26-27', 'Gálatas', 3, 26, 27),
  ('roupas', 'O que vencer será vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; e confessarei o seu nome diante de meu Pai e diante dos seus anjos.', 'Apocalipse 3:5', 'Apocalipse', 3, 5, NULL),
  ('roupas', 'Porque nada trouxemos para este mundo e manifesto é que nada podemos levar dele. Tendo, porém, sustento e com que nos cobrirmos, estejamos com isso contentes.', '1 Timóteo 6:7-8', '1 Timóteo', 6, 7, 8),
  ('roupas', 'Não estejais apreensivos pela vossa vida, sobre o que comereis, nem pelo corpo, sobre o que vestireis. Mais é a vida do que o sustento, e o corpo, mais do que as vestes.', 'Lucas 12:22b-23', 'Lucas 12:22b-23', NULL, NULL, NULL),
  ('roupas', 'E, respondendo ele, disse-lhes: Quem tiver duas túnicas, que reparta com o que não tem, e quem tiver alimentos, que faça da mesma maneira.', 'Lucas 3:11', 'Lucas', 3, 11, NULL),
  ('roupas', 'Acautelai-vos, porém, dos falsos profetas, que vêm até vós vestidos como ovelhas, mas interiormente são lobos devoradores.', 'Mateus 7:15', 'Mateus', 7, 15, NULL),
  ('roupas', 'E este João tinha a sua veste de pelos de camelo e um cinto de couro em torno de seus lombos e alimentava-se de gafanhotos e de mel silvestre.', 'Mateus 3:4', 'Mateus', 3, 4, NULL),
  ('roupas', 'Então, foram abertos os olhos de ambos, e conheceram que estavam nus; e coseram folhas de figueira, e fizeram para si aventais.', 'Gênesis 3:7', 'Gênesis', 3, 7, NULL),
  ('sabado', 'Lembra-te do dia do sábado, para o santificar. Seis dias trabalharás e farás toda a tua obra, mas o sétimo dia é o sábado do Senhor', 'Êxodo 20:8-11', 'Êxodo', 20, 8, 11),
  ('sabado', 'Eu sou o Senhor', 'Ezequiel 20:19-20', 'Ezequiel', 20, 19, 20),
  ('sabado', 'Guarda o dia de sábado, para o santificar, como te ordenou o Senhor', 'Deuteronômio 5:12-14', 'Deuteronômio', 5, 12, 14),
  ('sabado', 'Se desviares o teu pé do sábado, de fazer a tua vontade no meu santo dia, e se chamares ao sábado deleitoso e santo dia do Senhor', 'Isaías 58:13-14', 'Isaías', 58, 13, 14),
  ('sabado', 'E abençoou Deus o dia sétimo e o santificou; porque nele descansou de toda a sua obra, que Deus criara e fizera.', 'Gênesis 2:3', 'Gênesis', 2, 3, NULL),
  ('sabado', 'E aconteceu que, passando ele num sábado pelas searas, os seus discípulos, caminhando, começaram a colher espigas. E os fariseus lhe disseram: Vês? Por que fazem no sábado o que não é lícito? Mas ele disse-lhes: Nunca lestes o que fez Davi, quando estava em necessidade e teve fome, ele e os que com ele estavam? Como entrou na Casa de Deus, no tempo de Abiatar, sumo sacerdote, e comeu os pães da proposição, dos quais não era lícito comer senão aos sacerdotes, dando também aos que com ele estavam? E disse-lhes: O sábado foi feito por causa do homem, e não o homem, por causa do sábado. Assim, o Filho do Homem até do sábado é senhor.', 'Marcos 2:23-28', 'Marcos', 2, 23, 28),
  ('sabado', 'Um faz diferença entre dia e dia, mas outro julga iguais todos os dias. Cada um esteja inteiramente seguro em seu próprio ânimo.', 'Romanos 14:5', 'Romanos', 14, 5, NULL),
  ('sabado', 'Pois quanto mais vale um homem do que uma ovelha? É, por consequência, lícito fazer bem nos sábados.', 'Mateus 12:12', 'Mateus', 12, 12, NULL),
  ('sabado', 'Portanto, ninguém vos julgue pelo comer, ou pelo beber, ou por causa dos dias de festa, ou da lua nova, ou dos sábados, que são sombras das coisas futuras, mas o corpo é de Cristo.', 'Colossenses 2:16-17', 'Colossenses', 2, 16, 17),
  ('sabado', 'Portanto, resta ainda um repouso para o povo de Deus. Porque aquele que entrou no seu repouso, ele próprio repousou de suas obras, como Deus das suas.', 'Hebreus 4:9-10', 'Hebreus', 4, 9, 10),
  ('sabado', 'Seis dias obra se fará, mas o sétimo dia será o sábado do descanso, santa convocação; nenhuma obra fareis; sábado do Senhor', 'Levítico 23:3', 'Levítico', 23, 3, NULL),
  ('sabado', 'Guardareis os meus sábados e reverenciareis o meu santuário. Eu sou o Senhor', 'Levítico 26:2', 'Levítico', 26, 2, NULL),
  ('sabado', 'Procuremos, pois, entrar naquele repouso, para que ninguém caia no mesmo exemplo de desobediência.', 'Hebreus 4:11', 'Hebreus', 4, 11, NULL),
  ('sabado', 'E ensinava no sábado, numa das sinagogas. E eis que estava ali uma mulher que tinha um espírito de enfermidade havia já dezoito anos; e andava curvada e não podia de modo algum endireitar-se. E, vendo-a Jesus, chamou-a a si, e disse-lhe: Mulher, estás livre da tua enfermidade. E impôs as mãos sobre ela, e logo se endireitou e glorificava a Deus. E, tomando a palavra o príncipe da sinagoga, indignado porque Jesus curava no sábado, disse à multidão: Seis dias há em que é mister trabalhar; nestes, pois, vinde para serdes curados e não no dia de sábado. Respondeu-lhe, porém, o Senhor e disse: Hipócrita, no sábado não desprende da manjedoura cada um de vós o seu boi ou jumento e não o leva a beber água? E não convinha soltar desta prisão, no dia de sábado, esta filha de Abraão, a qual há dezoito anos Satanás mantinha presa? E, dizendo ele isso, todos os seus adversários ficaram envergonhados, e todo o povo se alegrava por todas as coisas gloriosas que eram feitas por ele.', 'Lucas 13:10-17', 'Lucas', 13, 10, 17),
  ('sabado', 'Porque te lembrarás que foste servo na terra do Egito e que o Senhor', 'Deuteronômio 5:15', 'Deuteronômio', 5, 15, NULL),
  ('sabedoria', 'Porque o Senhor', 'Provérbios 2:6', 'Provérbios', 2, 6, NULL),
  ('sabedoria', 'Portanto, vede prudentemente como andais, não como néscios, mas como sábios, remindo o tempo, porquanto os dias são maus.', 'Efésios 5:15-16', 'Efésios', 5, 15, 16),
  ('sabedoria', 'E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada.', 'Tiago 1:5', 'Tiago', 1, 5, NULL),
  ('sabedoria', 'Mas a sabedoria que vem do alto é, primeiramente, pura, depois, pacífica, moderada, tratável, cheia de misericórdia e de bons frutos, sem parcialidade e sem hipocrisia.', 'Tiago 3:17', 'Tiago', 3, 17, NULL),
  ('sabedoria', 'Quanto melhor é adquirir a sabedoria do que o ouro! E quanto mais excelente, adquirir a prudência do que a prata!', 'Provérbios 16:16', 'Provérbios', 16, 16, NULL),
  ('sabedoria', 'Nunca digas: Por que foram os dias passados melhores do que estes? Porque nunca com sabedoria isso perguntarias.', 'Eclesiastes 7:10', 'Eclesiastes', 7, 10, NULL),
  ('sabedoria', 'Andai com sabedoria para com os que estão de fora, remindo o tempo. A vossa palavra seja sempre agradável, temperada com sal, para que saibais como vos convém responder a cada um.', 'Colossenses 4:5-6', 'Colossenses', 4, 5, 6),
  ('sabedoria', 'Da soberba só provém a contenda, mas com os que se aconselham se acha a sabedoria.', 'Provérbios 13:10', 'Provérbios', 13, 10, NULL),
  ('sabedoria', 'O que adquire entendimento ama a sua alma; o que conserva a inteligência achará o bem.', 'Provérbios 19:8', 'Provérbios', 19, 8, NULL),
  ('sabedoria', 'Ninguém se engane a si mesmo: se alguém dentre vós se tem por sábio neste mundo, faça-se louco para ser sábio.', '1 Coríntios 3:18', '1 Coríntios', 3, 18, NULL),
  ('sabedoria', 'O que guarda a sua boca conserva a sua alma, mas o que muito abre os lábios tem perturbação.', 'Provérbios 13:3', 'Provérbios', 13, 3, NULL),
  ('sabedoria', 'Quem dentre vós é sábio e inteligente? Mostre, pelo seu bom trato, as suas obras em mansidão de sabedoria.', 'Tiago 3:13', 'Tiago', 3, 13, NULL),
  ('sabedoria', 'Ensina-nos a contar os nossos dias, de tal maneira que alcancemos coração sábio.', 'Salmo 90:12', 'Salmo', 90, 12, NULL),
  ('sabedoria', 'Todo aquele, pois, que escuta estas minhas palavras e as pratica, assemelhá-lo-ei ao homem prudente, que edificou a sua casa sobre a rocha.', 'Mateus 7:24', 'Mateus', 7, 24, NULL),
  ('sabedoria', 'O temor do Senhor', 'Provérbios 15:33', 'Provérbios', 15, 33, NULL),
  ('sabedoria', 'Vindo a soberba, virá também a afronta; mas com os humildes está a sabedoria.', 'Provérbios 11:2', 'Provérbios', 11, 2, NULL),
  ('sabedoria', 'Porque o que me achar achará a vida e alcançará favor do Senhor', 'Provérbios 8:35', 'Provérbios', 8, 35, NULL),
  ('sabedoria', 'Para que o Deus de nosso Senhor Jesus Cristo, o Pai da glória, vos dê em seu conhecimento o espírito de sabedoria e de revelação.', 'Efésios 1:17', 'Efésios', 1, 17, NULL),
  ('sabedoria', 'A sabedoria é a coisa principal; adquire, pois, a sabedoria; sim, com tudo o que possuis, adquire o conhecimento.', 'Provérbios 4:7', 'Provérbios', 4, 7, NULL),
  ('sabedoria', 'Porque os meus pensamentos não são os vossos pensamentos, nem os vossos caminhos, os meus caminhos, diz o Senhor', 'Isaías 55:8', 'Isaías', 55, 8, NULL),
  ('sabedoria', 'Não toma prazer o tolo no entendimento, senão em que se descubra o seu coração.', 'Provérbios 18:2', 'Provérbios', 18, 2, NULL),
  ('sabedoria', 'O sábio de coração aceita os mandamentos, mas o louco palrador será transtornado.', 'Provérbios 10:8', 'Provérbios', 10, 8, NULL),
  ('sabedoria', 'Até isto procede do Senhor', 'Isaías 28:29', 'Isaías', 28, 29, NULL),
  ('sabedoria', 'Não sabes, não ouviste que o eterno Deus, o Senhor', 'Isaías 40:28', 'Isaías', 40, 28, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('sabedoria', 'Ó Deus de meus pais, eu te louvo e celebro porque me deste sabedoria e força; e, agora, me fizeste saber o que te pedimos, porque nos fizeste saber este assunto do rei.', 'Daniel 2:23', 'Daniel', 2, 23, NULL),
  ('sabedoria', 'Até o tolo, quando se cala, será reputado por sábio; e o que cerrar os seus lábios, por sábio.', 'Provérbios 17:28', 'Provérbios', 17, 28, NULL),
  ('sabedoria', 'O longânimo é grande em entendimento, mas o de ânimo precipitado exalta a loucura.', 'Provérbios 14:29', 'Provérbios', 14, 29, NULL),
  ('sabedoria', 'Bem-aventurado o homem que acha sabedoria, e o homem que adquire conhecimento.', 'Provérbios 3:13', 'Provérbios', 3, 13, NULL),
  ('sabedoria', 'Porque, na muita sabedoria, há muito enfado; e o que aumenta em ciência aumenta em trabalho.', 'Eclesiastes 1:18', 'Eclesiastes', 1, 18, NULL),
  ('sabedoria', 'O temor do Senhor', 'Provérbios 1:7', 'Provérbios', 1, 7, NULL),
  ('sabedoria', 'Tal será o conhecimento da sabedoria para a tua alma; se a achares, haverá para ti galardão, e não será cortada a tua expectação.', 'Provérbios 24:14', 'Provérbios', 24, 14, NULL),
  ('sabedoria', 'O temor do Senhor', 'Provérbios 9:10', 'Provérbios', 9, 10, NULL),
  ('sabedoria', 'No caminho da sabedoria, te ensinei e, pelas carreiras direitas, te fiz andar.', 'Provérbios 4:11', 'Provérbios', 4, 11, NULL),
  ('sabedoria', 'Ó profundidade das riquezas, tanto da sabedoria, como da ciência de Deus! Quão insondáveis são os seus juízos, e quão inescrutáveis, os seus caminhos!', 'Romanos 11:33', 'Romanos', 11, 33, NULL),
  ('sabedoria', 'Anda com os sábios e serás sábio, mas o companheiro dos tolos será afligido.', 'Provérbios 13:20', 'Provérbios', 13, 20, NULL),
  ('sabedoria', 'Adquire a sabedoria, adquire a inteligência e não te esqueças nem te apartes das palavras da minha boca.', 'Provérbios 4:5', 'Provérbios', 4, 5, NULL),
  ('sabedoria', 'O temor do Senhor', 'Salmo 111:10', 'Salmo', 111, 10, NULL),
  ('sabedoria', 'Nas palavras da boca do sábio, há favor, mas os lábios do tolo o devoram.', 'Eclesiastes 10:12', 'Eclesiastes', 10, 12, NULL),
  ('sabedoria', 'Para que os seus corações sejam consolados, e estejam unidos em amor e enriquecidos da plenitude da inteligência, para conhecimento do mistério de Deus — Cristo.', 'Colossenses 2:2', 'Colossenses', 2, 2, NULL),
  ('sabedoria', 'Filho meu, se o teu coração for sábio, alegrar-se-á o meu coração, sim, o meu próprio.', 'Provérbios 23:15', 'Provérbios', 23, 15, NULL),
  ('sabedoria', 'A lei do Senhor', 'Salmo 19:7', 'Salmo', 19, 7, NULL),
  ('sabedoria', 'Um faz diferença entre dia e dia, mas outro julga iguais todos os dias. Cada um esteja inteiramente seguro em seu próprio ânimo.', 'Romanos 14:5', 'Romanos', 14, 5, NULL),
  ('sabedoria', 'O hipócrita, com a boca, danifica o seu próximo, mas os justos são libertados pelo conhecimento.', 'Provérbios 11:9', 'Provérbios', 11, 9, NULL),
  ('sabedoria', 'Um tolo expande toda a sua ira, mas o sábio a encobre e reprime.', 'Provérbios 29:11', 'Provérbios', 29, 11, NULL),
  ('sabedoria', 'Os lábios do tolo entram na contenda, e a sua boca brada por açoites.', 'Provérbios 18:6', 'Provérbios', 18, 6, NULL),
  ('sabedoria', 'A ira do louco se conhece no mesmo dia, mas o avisado encobre a afronta.', 'Provérbios 12:16', 'Provérbios', 12, 16, NULL),
  ('sabedoria', 'Convertei-vos pela minha repreensão; eis que abundantemente derramarei sobre vós meu espírito e vos farei saber as minhas palavras.', 'Provérbios 1:23', 'Provérbios', 1, 23, NULL),
  ('sabedoria', 'Muitos serão purificados, e embranquecidos, e provados; mas os ímpios procederão impiamente, e nenhum dos ímpios entenderá, mas os sábios entenderão.', 'Daniel 12:10', 'Daniel', 12, 10, NULL),
  ('sabedoria', 'O tolo despreza a correção de seu pai, mas o que observa a repreensão prudentemente se haverá.', 'Provérbios 15:5', 'Provérbios', 15, 5, NULL),
  ('sabedoria', 'Grandemente se regozijará o pai do justo, e o que gerar a um sábio se alegrará nele.', 'Provérbios 23:24', 'Provérbios', 23, 24, NULL),
  ('sabedoria', 'O filho sábio alegra a seu pai, mas o filho louco é a tristeza de sua mãe.', 'Provérbios 10:1', 'Provérbios', 10, 1, NULL),
  ('sabedoria', 'Quem é sábio, para que entenda estas coisas? Prudente, para que as saiba? Porque os caminhos do Senhor', 'Oseias 14:9', 'Oseias', 14, 9, NULL),
  ('sabedoria', 'Não convém ao tolo a fala excelente; quanto menos ao príncipe, o lábio mentiroso!', 'Provérbios 17:7', 'Provérbios', 17, 7, NULL),
  ('sacrificio', 'Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus amigos.', 'João 15:13', 'João', 15, 13, NULL),
  ('sacrificio', 'E andai em amor, como também Cristo vos amou e se entregou a si mesmo por nós, em oferta e sacrifício a Deus, em cheiro suave.', 'Efésios 5:2', 'Efésios', 5, 2, NULL),
  ('sacrificio', 'Assim também Cristo, oferecendo-se uma vez, para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para a salvação.', 'Hebreus 9:28', 'Hebreus', 9, 28, NULL),
  ('sacrificio', 'Porque qualquer que quiser salvar a sua vida perdê-la-á; mas qualquer que, por amor de mim, perder a sua vida a salvará.', 'Lucas 9:24', 'Lucas', 9, 24, NULL),
  ('sacrificio', 'Fazer justiça e julgar com retidão é mais aceitável ao Senhor', 'Provérbios 21:3', 'Provérbios', 21, 3, NULL),
  ('sacrificio', 'Ide, porém, e aprendei o que significa: Misericórdia quero e não sacrifício. Porque eu não vim para chamar os justos, mas os pecadores, ao arrependimento.', 'Mateus 9:13', 'Mateus', 9, 13, NULL),
  ('sacrificio', 'O qual se deu a si mesmo por nós, para nos remir de toda iniquidade e purificar para si um povo seu especial, zeloso de boas obras.', 'Tito 2:14', 'Tito', 2, 14, NULL),
  ('sacrificio', 'Porque primeiramente vos entreguei o que também recebi: que Cristo morreu por nossos pecados, segundo as Escrituras, e que foi sepultado, e que ressuscitou ao terceiro dia, segundo as Escrituras.', '1 Coríntios 15:3-4', '1 Coríntios', 15, 3, 4),
  ('sacrificio', 'Porque o Filho do Homem também não veio para ser servido, mas para servir e dar a sua vida em resgate de muitos.', 'Marcos 10:45', 'Marcos', 10, 45, NULL),
  ('sacrificio', 'E, despindo-o, o cobriram com uma capa escarlate. E, tecendo uma coroa de espinhos, puseram-lha na cabeça e, em sua mão direita, uma cana; e, ajoelhando diante dele, o escarneciam, dizendo: Salve, Rei dos judeus!', 'Mateus 27:28-29', 'Mateus', 27, 28, 29),
  ('sacrificio', 'Aquele que nem mesmo a seu próprio Filho poupou, antes, o entregou por todos nós, como nos não dará também com ele todas as coisas?', 'Romanos 8:32', 'Romanos', 8, 32, NULL),
  ('sacrificio', 'Porque Cristo, estando nós ainda fracos, morreu a seu tempo pelos ímpios.', 'Romanos 5:6', 'Romanos', 5, 6, NULL),
  ('sacrificio', 'Mas eu te oferecerei sacrifício com a voz do agradecimento; o que votei pagarei; do Senhor', 'Jonas 2:9', 'Jonas', 2, 9, NULL),
  ('sacrificio', 'Honra ao Senhor', 'Provérbios 3:9', 'Provérbios', 3, 9, NULL),
  ('sacrificio', 'Nem tampouco apresenteis os vossos membros ao pecado por instrumentos de iniquidade; mas apresentai-vos a Deus, como vivos dentre mortos, e os vossos membros a Deus, como instrumentos de justiça.', 'Romanos 6:13', 'Romanos', 6, 13, NULL),
  ('sacrificio', 'Quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus, purificará a vossa consciência das obras mortas, para servirdes ao Deus vivo?', 'Hebreus 9:14', 'Hebreus', 9, 14, NULL),
  ('sacrificio', 'Bem como o Filho do Homem não veio para ser servido, mas para servir e para dar a sua vida em resgate de muitos.', 'Mateus 20:28', 'Mateus', 20, 28, NULL),
  ('sacrificio', 'Os sacrifícios para Deus são o espírito quebrantado; a um coração quebrantado e contrito não desprezarás, ó Deus.', 'Salmo 51:17', 'Salmo', 51, 17, NULL),
  ('sacrificio', 'Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo pecado.', '1 João 1:7', '1 João', 1, 7, NULL),
  ('sacrificio', 'Aba, Pai, todas as coisas te são possíveis; afasta de mim este cálice; não seja, porém, o que eu quero, mas o que tu queres.', 'Marcos 14:36', 'Marcos', 14, 36, NULL),
  ('sacrificio', 'E, clamando Jesus com grande voz, disse: Pai, nas tuas mãos entrego o meu espírito. E, havendo dito isso, expirou.', 'Lucas 23:46', 'Lucas', 23, 46, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('sacrificio', 'Eis que vamos para Jerusalém, e o Filho do Homem será entregue aos príncipes dos sacerdotes e aos escribas, e condená-lo-ão à morte. E o entregarão aos gentios para que dele escarneçam, e o açoitem, e crucifiquem, e ao terceiro dia ressuscitará.', 'Mateus 20:18-19', 'Mateus', 20, 18, 19),
  ('sacrificio', 'E que amá-lo de todo o coração, e de todo o entendimento, e de toda a alma, e de todas as forças e amar o próximo como a si mesmo é mais do que todos os holocaustos e sacrifícios.', 'Marcos 12:33', 'Marcos', 12, 33, NULL),
  ('sacrificio', 'Porque, com uma só oblação, aperfeiçoou para sempre os que são santificados.', 'Hebreus 10:14', 'Hebreus', 10, 14, NULL),
  ('sacrificio', 'Eu sou o bom Pastor; o bom Pastor dá a sua vida pelas ovelhas.', 'João 10:11', 'João', 10, 11, NULL),
  ('salvacao', 'E em nenhum outro há salvação, porque também debaixo do céu nenhum outro nome há, dado entre os homens, pelo qual devamos ser salvos.', 'Atos 4:12', 'Atos', 4, 12, NULL),
  ('salvacao', 'E eles disseram: Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa.', 'Atos 16:31', 'Atos', 16, 31, NULL),
  ('salvacao', 'Que nos salvou e chamou com uma santa vocação; não segundo as nossas obras, mas segundo o seu próprio propósito e graça que nos foi dada em Cristo Jesus, antes dos tempos dos séculos.', '2 Timóteo 1:9', '2 Timóteo', 1, 9, NULL),
  ('salvacao', 'A minha alma espera somente em Deus; dele vem a minha salvação.', 'Salmo 62:1', 'Salmo', 62, 1, NULL),
  ('salvacao', 'E acontecerá que todo aquele que invocar o nome do Senhor será salvo.', 'Atos 2:21', 'Atos', 2, 21, NULL),
  ('salvacao', 'Não sabeis que os injustos não hão de herdar o Reino de Deus? Não erreis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas, nem os ladrões, nem os avarentos, nem os bêbados, nem os maldizentes, nem os roubadores herdarão o Reino de Deus.', '1 Coríntios 6:9-10', '1 Coríntios', 6, 9, 10),
  ('salvacao', 'Visto que com o coração se crê para a justiça, e com a boca se faz confissão para a salvação.', 'Romanos 10:10', 'Romanos', 10, 10, NULL),
  ('salvacao', 'Porque a graça de Deus se há manifestado, trazendo salvação a todos os homens, ensinando-nos que, renunciando à impiedade e às concupiscências mundanas, vivamos neste presente século sóbria, justa e piamente.', 'Tito 2:11-12', 'Tito', 2, 11, 12),
  ('salvacao', 'Porque o Filho do Homem veio buscar e salvar o que se havia perdido.', 'Lucas 19:10', 'Lucas', 19, 10, NULL),
  ('salvacao', 'O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é longânimo para convosco, não querendo que alguns se percam, senão que todos venham a arrepender-se.', '2 Pedro 3:9', '2 Pedro', 3, 9, NULL),
  ('salvacao', 'Mas ele respondeu: As coisas que são impossíveis aos homens são possíveis a Deus.', 'Lucas 18:27', 'Lucas', 18, 27, NULL),
  ('salvacao', 'Entrai pela porta estreita, porque larga é a porta, e espaçoso, o caminho que conduz à perdição, e muitos são os que entram por ela; E porque estreita é a porta, e apertado, o caminho que leva à vida, e poucos há que a encontrem.', 'Mateus 7:13-14', 'Mateus', 7, 13, 14),
  ('salvacao', 'Quem crer e for batizado será salvo; mas quem não crer será condenado.', 'Marcos 16:16', 'Marcos', 16, 16, NULL),
  ('salvacao', 'Assim também Cristo, oferecendo-se uma vez, para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que o esperam para a salvação.', 'Hebreus 9:28', 'Hebreus', 9, 28, NULL),
  ('salvacao', 'Ao qual, não o havendo visto, amais; no qual, não o vendo agora, mas crendo, vos alegrais com gozo inefável e glorioso, alcançando o fim da vossa fé, a salvação da alma.', '1 Pedro 1:8-9', '1 Pedro', 1, 8, 9),
  ('salvacao', 'Porque pela graça sois salvos, por meio da fé; e isso não vem de vós; é dom de Deus. Não vem das obras, para que ninguém se glorie.', 'Efésios 2:8-9', 'Efésios', 2, 8, 9),
  ('salvacao', 'Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo.', '1 Coríntios 15:22', '1 Coríntios', 15, 22, NULL),
  ('salvacao', 'Porque o Senhor assim no-lo mandou: Eu te pus para luz dos gentios, para que sejas de salvação até aos confins da terra.', 'Atos 13:47', 'Atos', 13, 47, NULL),
  ('salvacao', 'Porque Deus enviou o seu Filho ao mundo não para que condenasse o mundo, mas para que o mundo fosse salvo por ele.', 'João 3:17', 'João', 3, 17, NULL),
  ('salvacao', 'Porque não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê, primeiro do judeu e também do grego.', 'Romanos 1:16', 'Romanos', 1, 16, NULL),
  ('salvacao', 'Porque apenas alguém morrerá por um justo; pois poderá ser que pelo bom alguém ouse morrer. Mas Deus prova o seu amor para conosco em que Cristo morreu por nós, sendo nós ainda pecadores.', 'Romanos 5:7-8', 'Romanos', 5, 7, 8),
  ('salvacao', 'Porque, se nós, sendo inimigos, fomos reconciliados com Deus pela morte de seu Filho, muito mais, estando já reconciliados, seremos salvos pela sua vida.', 'Romanos 5:10', 'Romanos', 5, 10, NULL),
  ('salvacao', 'Também me deste o escudo da tua salvação; a tua mão direita me susteve, e a tua mansidão me engrandeceu. Alargaste os meus passos e os meus artelhos não vacilaram.', 'Salmo 18:35-36', 'Salmo', 18, 35, 36),
  ('salvacao', 'E Jesus lhe disse: Vai, a tua fé te salvou. E logo viu, e seguiu a Jesus pelo caminho.', 'Marcos 10:52', 'Marcos', 10, 52, NULL),
  ('salvacao', 'Jesus, porém, olhando para eles, disse: Para os homens é impossível, mas não para Deus, porque para Deus todas as coisas são possíveis.', 'Marcos 10:27', 'Marcos', 10, 27, NULL),
  ('salvacao', 'Porquanto, ainda que a figueira não floresça, nem haja fruto na vide; o produto da oliveira minta, e os campos não produzam mantimento; as ovelhas da malhada sejam arrebatadas, e nos currais não haja vacas, todavia, eu me alegrarei no Senhor', 'Habacuque 3:17-18', 'Habacuque', 3, 17, 18),
  ('salvacao', 'Porque todo aquele que invocar o nome do Senhor será salvo.', 'Romanos 10:13', 'Romanos', 10, 13, NULL),
  ('salvacao', 'Em Deus está a minha salvação e a minha glória; a rocha da minha fortaleza e o meu refúgio estão em Deus.', 'Salmo 62:7', 'Salmo', 62, 7, NULL),
  ('salvacao', 'Enquanto foste precioso aos meus olhos, também foste glorificado, e eu te amei, pelo que dei os homens por ti, e os povos, pela tua alma.', 'Isaías 43:4', 'Isaías', 43, 4, NULL),
  ('salvacao', 'Eu sou a porta; se alguém entrar por mim, salvar-se-á, e entrará, e sairá, e achará pastagens.', 'João 10:9', 'João', 10, 9, NULL),
  ('salvacao', 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'João', 3, 16, NULL),
  ('salvacao', 'Porque a palavra da cruz é loucura para os que perecem; mas para nós, que somos salvos, é o poder de Deus.', '1 Coríntios 1:18', '1 Coríntios', 1, 18, NULL),
  ('salvacao', 'Mas aquele que perseverar até ao fim será salvo.', 'Mateus 24:13', 'Mateus', 24, 13, NULL),
  ('salvacao', 'Porque o mesmo Senhor descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus; e os que morreram em Cristo ressuscitarão primeiro; depois, nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o Senhor nos ares, e assim estaremos sempre com o Senhor.', '1 Tessalonicenses 4:16-17', '1 Tessalonicenses', 4, 16, 17),
  ('salvacao', 'Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida.', '1 João 5:12', '1 João', 5, 12, NULL),
  ('salvacao', 'E vos darei um coração novo e porei dentro de vós um espírito novo; e tirarei o coração de pedra da vossa carne e vos darei um coração de carne.', 'Ezequiel 36:26', 'Ezequiel', 36, 26, NULL),
  ('salvacao', 'Sara-me, Senhor', 'Jeremias 17:14', 'Jeremias', 17, 14, NULL),
  ('salvacao', 'Portanto, pode também salvar perfeitamente os que por ele se chegam a Deus, vivendo sempre para interceder por eles.', 'Hebreus 7:25', 'Hebreus', 7, 25, NULL),
  ('salvacao', 'Eu te amarei do coração, ó Senhor', 'Salmo 18:1-2', 'Salmo', 18, 1, 2),
  ('salvacao', 'Isto é, Deus estava em Cristo reconciliando consigo o mundo, não lhes imputando os seus pecados, e pôs em nós a palavra da reconciliação.', '2 Coríntios 5:19', '2 Coríntios', 5, 19, NULL),
  ('salvacao', 'Também vos notifico, irmãos, o evangelho que já vos tenho anunciado, o qual também recebestes e no qual também permaneceis; pelo qual também sois salvos, se o retiverdes tal como vo-lo tenho anunciado, se não é que crestes em vão.', '1 Coríntios 15:1-2', '1 Coríntios', 15, 1, 2),
  ('salvacao', 'Porque aquele que quiser salvar a sua vida perdê-la-á, e quem perder a sua vida por amor de mim achá-la-á.', 'Mateus 16:25', 'Mateus', 16, 25, NULL),
  ('salvacao', 'Os justos clamam, e o Senhor', 'Salmo 34:17-18', 'Salmo', 34, 17, 18),
  ('salvacao', 'Não pelas obras de justiça que houvéssemos feito, mas, segundo a sua misericórdia, nos salvou pela lavagem da regeneração e da renovação do Espírito Santo.', 'Tito 3:5', 'Tito', 3, 5, NULL),
  ('salvacao', 'Aquele que crê no Filho tem a vida eterna, mas aquele que não crê no Filho não verá a vida, mas a ira de Deus sobre ele permanece.', 'João 3:36', 'João', 3, 36, NULL),
  ('salvacao', 'Mas a nossa cidade está nos céus, donde também esperamos o Salvador, o Senhor Jesus Cristo.', 'Filipenses 3:20', 'Filipenses', 3, 20, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('salvacao', 'O ladrão não vem senão a roubar, a matar e a destruir; eu vim para que tenham vida e a tenham com abundância.', 'João 10:10', 'João', 10, 10, NULL),
  ('salvacao', 'E, sendo ele consumado, veio a ser a causa de eterna salvação para todos os que lhe obedecem.', 'Hebreus 5:9', 'Hebreus', 5, 9, NULL),
  ('salvacao', 'Pelo que, rejeitando toda imundícia e acúmulo de malícia, recebei com mansidão a palavra em vós enxertada, a qual pode salvar a vossa alma.', 'Tiago 1:21', 'Tiago', 1, 21, NULL),
  ('salvacao', 'Guia-me na tua verdade e ensina-me, pois tu és o Deus da minha salvação; por ti estou esperando todo o dia.', 'Salmo 25:5', 'Salmo', 25, 5, NULL),
  ('salvacao', 'Porque, como, pela desobediência de um só homem, muitos foram feitos pecadores, assim, pela obediência de um, muitos serão feitos justos.', 'Romanos 5:19', 'Romanos', 5, 19, NULL),
  ('salvacao', 'Quanto está longe o Oriente do Ocidente, assim afasta de nós as nossas transgressões.', 'Salmo 103:12', 'Salmo', 103, 12, NULL),
  ('salvacao', 'Porque sei que disto me resultará salvação, pela vossa oração e pelo socorro do Espírito de Jesus Cristo.', 'Filipenses 1:19', 'Filipenses', 1, 19, NULL),
  ('salvacao', 'Porque nele se descobre a justiça de Deus de fé em fé, como está escrito: Mas o justo viverá da fé.', 'Romanos 1:17', 'Romanos', 1, 17, NULL),
  ('salvacao', 'Desfaço as tuas transgressões como a névoa, e os teus pecados, como a nuvem; torna-te para mim, porque eu te remi.', 'Isaías 44:22', 'Isaías', 44, 22, NULL),
  ('salvacao', 'Porque o Senhor', 'Isaías 33:22', 'Isaías', 33, 22, NULL),
  ('salvacao', 'Porque para mim tenho por certo que as aflições deste tempo presente não são para comparar com a glória que em nós há de ser revelada.', 'Romanos 8:18', 'Romanos', 8, 18, NULL),
  ('salvacao', 'O Senhor', 'Salmo 34:22', 'Salmo', 34, 22, NULL),
  ('salvacao', 'Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor, em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados.', 'Colossenses 1:13-14', 'Colossenses', 1, 13, 14),
  ('salvacao', 'Porque assim diz o Alto e o Sublime, que habita na eternidade e cujo nome é Santo: Em um alto e santo lugar habito e também com o contrito e abatido de espírito, para vivificar o espírito dos abatidos e para vivificar o coração dos contritos.', 'Isaías 57:15', 'Isaías', 57, 15, NULL),
  ('salvacao', 'Nem todo o que me diz: Senhor, Senhor! entrará no Reino dos céus, mas aquele que faz a vontade de meu Pai, que está nos céus.', 'Mateus 7:21', 'Mateus', 7, 21, NULL),
  ('salvacao', 'A salvação vem do Senhor', 'Salmo 3:8', 'Salmo', 3, 8, NULL),
  ('salvacao', 'Porque qualquer que quiser salvar a sua vida perdê-la-á, mas qualquer que perder a sua vida por amor de mim e do evangelho, esse a salvará.', 'Marcos 8:35', 'Marcos', 8, 35, NULL),
  ('salvacao', 'Porque eu sei que o meu Redentor vive, e que por fim se levantará sobre a terra.', 'Jó 19:25', 'Jó', 19, 25, NULL),
  ('salvacao', 'Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz.', '1 Pedro 2:9', '1 Pedro', 2, 9, NULL),
  ('salvacao', 'Que também, como uma verdadeira figura, agora vos salva, batismo, não do despojamento da imundícia da carne, mas da indagação de uma boa consciência para com Deus, pela ressurreição de Jesus Cristo.', '1 Pedro 3:21', '1 Pedro', 3, 21, NULL),
  ('salvacao', 'Porque o Filho do Homem também não veio para ser servido, mas para servir e dar a sua vida em resgate de muitos.', 'Marcos 10:45', 'Marcos', 10, 45, NULL),
  ('salvacao', 'Eu, porém, esperarei no Senhor', 'Miqueias 7:7', 'Miqueias', 7, 7, NULL),
  ('salvacao', 'E Jesus, olhando para eles, disse-lhes: Aos homens é isso impossível, mas a Deus tudo é possível.', 'Mateus 19:26', 'Mateus', 19, 26, NULL),
  ('salvacao', 'Só ele é a minha rocha e a minha salvação; é a minha defesa; não serei grandemente abalado.', 'Salmo 62:2', 'Salmo', 62, 2, NULL),
  ('salvacao', 'Faze-nos voltar, Senhor', 'Salmo 80:19', 'Salmo', 80, 19, NULL),
  ('salvacao', 'Quão suaves são sobre os montes os pés do que anuncia as boas-novas, que faz ouvir a paz, que anuncia o bem, que faz ouvir a salvação, que diz a Sião: O teu Deus reina!', 'Isaías 52:7', 'Isaías', 52, 7, NULL),
  ('salvacao', 'E, chamando a si a multidão, com os seus discípulos, disse-lhes: Se alguém quiser vir após mim, negue-se a si mesmo, e tome a sua cruz, e siga-me.', 'Marcos 8:34', 'Marcos', 8, 34, NULL),
  ('salvacao', 'Desejai afetuosamente, como meninos novamente nascidos, o leite racional, não falsificado, para que, por ele, vades crescendo.', '1 Pedro 2:2', '1 Pedro', 2, 2, NULL),
  ('salvacao', 'Não aniquilo a graça de Deus; porque, se a justiça provém da lei, segue-se que Cristo morreu debalde.', 'Gálatas 2:21', 'Gálatas', 2, 21, NULL),
  ('salvacao', 'Ajuda-nos, ó Deus da nossa salvação, pela glória do teu nome; e livra-nos e perdoa os nossos pecados, por amor do teu nome.', 'Salmo 79:9', 'Salmo', 79, 9, NULL),
  ('salvacao', 'Bem como o Filho do Homem não veio para ser servido, mas para servir e para dar a sua vida em resgate de muitos.', 'Mateus 20:28', 'Mateus', 20, 28, NULL),
  ('salvacao', 'Os meus tempos estão nas tuas mãos; livra-me das mãos dos meus inimigos e dos que me perseguem.', 'Salmo 31:15', 'Salmo', 31, 15, NULL),
  ('salvacao', 'Clamou este pobre, e o Senhor', 'Salmo 34:6', 'Salmo', 34, 6, NULL),
  ('salvacao', 'Filhinhos, sois de Deus e já os tendes vencido, porque maior é o que está em vós do que o que está no mundo.', '1 João 4:4', '1 João', 4, 4, NULL),
  ('salvacao', 'Mas eu te oferecerei sacrifício com a voz do agradecimento; o que votei pagarei; do Senhor', 'Jonas 2:9', 'Jonas', 2, 9, NULL),
  ('salvacao', 'Bendito seja o Senhor, que de dia em dia nos cumula de benefícios; o Deus que é a nossa salvação. (Selá)', 'Salmo 68:19', 'Salmo', 68, 19, NULL),
  ('salvacao', 'Porque a tristeza segundo Deus opera arrependimento para a salvação, da qual ninguém se arrepende; mas a tristeza do mundo opera a morte.', '2 Coríntios 7:10', '2 Coríntios', 7, 10, NULL),
  ('salvacao', 'Oh! Salva, Senhor', 'Salmo 118:25-26', 'Salmo', 118, 25, 26),
  ('salvacao', 'Assim, sabe o Senhor livrar da tentação os piedosos e reservar os injustos para o Dia de Juízo, para serem castigados.', '2 Pedro 2:9', '2 Pedro', 2, 9, NULL),
  ('salvacao', 'Faze resplandecer o teu rosto sobre o teu servo; salva-me por tuas misericórdias.', 'Salmo 31:16', 'Salmo', 31, 16, NULL),
  ('salvacao', 'Há só um Legislador e um Juiz, que pode salvar e destruir. Tu, porém, quem és, que julgas a outrem?', 'Tiago 4:12', 'Tiago', 4, 12, NULL),
  ('salvacao', 'Vós, mulheres, sujeitai-vos a vosso marido, como ao Senhor; porque o marido é a cabeça da mulher, como também Cristo é a cabeça da igreja, sendo ele próprio o salvador do corpo.', 'Efésios 5:22-23', 'Efésios', 5, 22, 23),
  ('salvacao', 'Tomai também o capacete da salvação e a espada do Espírito, que é a palavra de Deus.', 'Efésios 6:17', 'Efésios', 6, 17, NULL),
  ('salvacao', 'E eles serão meus, diz o Senhor', 'Malaquias 3:17', 'Malaquias', 3, 17, NULL),
  ('salvacao', 'Examinai-vos a vós mesmos se permaneceis na fé; provai-vos a vós mesmos. Ou não sabeis, quanto a vós mesmos, que Jesus Cristo está em vós? Se não é que já estais reprovados.', '2 Coríntios 13:5', '2 Coríntios', 13, 5, NULL),
  ('salvador', 'Nisto está o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou e enviou seu Filho para propiciação pelos nossos pecados.', '1 João 4:10', '1 João', 4, 10, NULL),
  ('salvador', 'Porque eu sei que o meu Redentor vive, e que por fim se levantará sobre a terra.', 'Jó 19:25', 'Jó', 19, 25, NULL),
  ('salvador', 'Pois, na cidade de Davi, vos nasceu hoje o Salvador, que é Cristo, o Senhor.', 'Lucas 2:11', 'Lucas', 2, 11, NULL),
  ('salvador', 'E ele é a propiciação pelos nossos pecados e não somente pelos nossos, mas também pelos de todo o mundo.', '1 João 2:2', '1 João', 2, 2, NULL),
  ('salvador', 'Que, sendo em forma de Deus, não teve por usurpação ser igual a Deus. Mas aniquilou-se a si mesmo, tomando a forma de servo, fazendo-se semelhante aos homens; e, achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte e morte de cruz.', 'Filipenses 2:6-8', 'Filipenses', 2, 6, 8);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('salvador', 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne vivo-a na fé do Filho de Deus, o qual me amou e se entregou a si mesmo por mim.', 'Gálatas 2:20', 'Gálatas', 2, 20, NULL),
  ('salvador', 'Porque todos pecaram e destituídos estão da glória de Deus, sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus.', 'Romanos 3:23-24', 'Romanos', 3, 23, 24),
  ('salvador', 'Portanto, pode também salvar perfeitamente os que por ele se chegam a Deus, vivendo sempre para interceder por eles.', 'Hebreus 7:25', 'Hebreus', 7, 25, NULL),
  ('salvador', 'Em quem temos a redenção pelo seu sangue, a remissão das ofensas, segundo as riquezas da sua graça.', 'Efésios 1:7', 'Efésios', 1, 7, NULL),
  ('salvador', 'Sabendo que não foi com coisas corruptíveis, como prata ou ouro, que fostes resgatados da vossa vã maneira de viver que, por tradição, recebestes dos vossos pais, mas com o precioso sangue de Cristo, como de um cordeiro imaculado e incontaminado.', '1 Pedro 1:18-19', '1 Pedro', 1, 18, 19),
  ('salvador', 'Olhando para Jesus, autor e consumador da fé, o qual, pelo gozo que lhe estava proposto, suportou a cruz, desprezando a afronta, e assentou-se à destra do trono de Deus.', 'Hebreus 12:2', 'Hebreus', 12, 2, NULL),
  ('salvador', 'Todavia, eu sou o Senhor', 'Oseias 13:4', 'Oseias', 13, 4, NULL),
  ('salvador', 'E, sendo ele consumado, veio a ser a causa de eterna salvação para todos os que lhe obedecem.', 'Hebreus 5:9', 'Hebreus', 5, 9, NULL),
  ('salvador', 'Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor, em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados.', 'Colossenses 1:13-14', 'Colossenses', 1, 13, 14),
  ('salvador', 'Porque, se nós, sendo inimigos, fomos reconciliados com Deus pela morte de seu Filho, muito mais, estando já reconciliados, seremos salvos pela sua vida.', 'Romanos 5:10', 'Romanos', 5, 10, NULL),
  ('salvador', 'E, por isso, é Mediador de um novo testamento, para que, intervindo a morte para remissão das transgressões que havia debaixo do primeiro testamento, os chamados recebam a promessa da herança eterna.', 'Hebreus 9:15', 'Hebreus', 9, 15, NULL),
  ('salvador', 'Mas, alcançando socorro de Deus, ainda até ao dia de hoje permaneço, dando testemunho, tanto a pequenos como a grandes, não dizendo nada mais do que o que os profetas e Moisés disseram que devia acontecer, isto é, que o Cristo devia padecer e, sendo o primeiro da ressurreição dos mortos, devia anunciar a luz a este povo e aos gentios.', 'Atos 26:22-23', 'Atos', 26, 22, 23),
  ('salvador', 'Mas o anjo, respondendo, disse às mulheres: Não tenhais medo; pois eu sei que buscai a Jesus, que foi crucificado. Ele não está aqui, porque já ressuscitou, como tinha dito. Vinde e vede o lugar onde o Senhor jazia.', 'Mateus 28:5-6', 'Mateus', 28, 5, 6),
  ('sangue', 'Ele nos tirou da potestade das trevas e nos transportou para o Reino do Filho do seu amor, em quem temos a redenção pelo seu sangue, a saber, a remissão dos pecados.', 'Colossenses 1:13-14', 'Colossenses', 1, 13, 14),
  ('sangue', 'Em quem temos a redenção pelo seu sangue, a remissão das ofensas, segundo as riquezas da sua graça.', 'Efésios 1:7', 'Efésios', 1, 7, NULL),
  ('sangue', 'Sabendo que não foi com coisas corruptíveis, como prata ou ouro, que fostes resgatados da vossa vã maneira de viver que, por tradição, recebestes dos vossos pais, mas com o precioso sangue de Cristo, como de um cordeiro imaculado e incontaminado.', '1 Pedro 1:18-19', '1 Pedro', 1, 18, 19),
  ('sangue', 'Mas, agora, em Cristo Jesus, vós, que antes estáveis longe, já pelo sangue de Cristo chegastes perto.', 'Efésios 2:13', 'Efésios', 2, 13, NULL),
  ('sangue', 'Quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus, purificará a vossa consciência das obras mortas, para servirdes ao Deus vivo?', 'Hebreus 9:14', 'Hebreus', 9, 14, NULL),
  ('sangue', 'Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo pecado.', '1 João 1:7', '1 João', 1, 7, NULL),
  ('sangue', 'Quem come a minha carne e bebe o meu sangue permanece em mim, e eu, nele.', 'João 6:56', 'João', 6, 56, NULL),
  ('sangue', 'Ora, o Deus de paz, que pelo sangue do concerto eterno tornou a trazer dos mortos a nosso Senhor Jesus Cristo, grande Pastor das ovelhas, vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável por Cristo Jesus, ao qual seja glória para todo o sempre. Amém!', 'Hebreus 13:20-21', 'Hebreus', 13, 20, 21),
  ('sangue', 'Vinde, então, e argui-me, diz o Senhor', 'Isaías 1:18', 'Isaías', 1, 18, NULL),
  ('sangue', 'Semelhantemente, tomou o cálice, depois da ceia, dizendo: Este cálice é o Novo Testamento no meu sangue, que é derramado por vós.', 'Lucas 22:20', 'Lucas', 22, 20, NULL),
  ('sangue', 'Tudo quanto se move, que é vivente, será para vosso mantimento; tudo vos tenho dado, como a erva verde. A carne, porém, com sua vida, isto é, com seu sangue, não comereis.', 'Gênesis 9:3-4', 'Gênesis', 9, 3, 4),
  ('sangue', 'E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão.', 'Hebreus 9:22', 'Hebreus', 9, 22, NULL),
  ('sangue', 'E, tomando o cálice e dando graças, deu-lho, dizendo: Bebei dele todos. Porque isto é o meu sangue, o sangue do Novo Testamento, que é derramado por muitos, para remissão dos pecados.', 'Mateus 26:27-28', 'Mateus', 26, 27, 28),
  ('sangue', 'Mas, se deveras melhorardes os vossos caminhos e as vossas obras, se deveras fizerdes juízo entre um homem e entre o seu companheiro, se não oprimirdes o estrangeiro, e o órfão, e a viúva, nem derramardes sangue inocente neste lugar, nem andardes após outros deuses para vosso próprio mal, eu vos farei habitar neste lugar, na terra que dei a vossos pais, de século em século.', 'Jeremias 7:5-7', 'Jeremias', 7, 5, 7),
  ('santidade', 'Ora, amados, pois que temos tais promessas, purifiquemo-nos de toda imundícia da carne e do espírito, aperfeiçoando a santificação no temor de Deus.', '2 Coríntios 7:1', '2 Coríntios', 7, 1, NULL),
  ('santidade', 'Mas, como é santo aquele que vos chamou, sede vós também santos em toda a vossa maneira de viver, porquanto escrito está: Sede santos, porque eu sou santo.', '1 Pedro 1:15-16', '1 Pedro', 1, 15, 16),
  ('santidade', 'Segui a paz com todos e a santificação, sem a qual ninguém verá o Senhor.', 'Hebreus 12:14', 'Hebreus', 12, 14, NULL),
  ('santidade', 'Como purificará o jovem o seu caminho? Observando-o conforme a tua palavra.', 'Salmo 119:9', 'Salmo', 119, 9, NULL),
  ('santidade', 'Que nos salvou e chamou com uma santa vocação; não segundo as nossas obras, mas segundo o seu próprio propósito e graça que nos foi dada em Cristo Jesus, antes dos tempos dos séculos.', '2 Timóteo 1:9', '2 Timóteo', 1, 9, NULL),
  ('santidade', 'Sonda-me, ó Deus, e conhece o meu coração; prova-me e conhece os meus pensamentos. E vê se há em mim algum caminho mau e guia-me pelo caminho eterno.', 'Salmo 139:23-24', 'Salmo', 139, 23, 24),
  ('santidade', 'De sorte que haja em vós o mesmo sentimento que houve também em Cristo Jesus.', 'Filipenses 2:5', 'Filipenses', 2, 5, NULL),
  ('santidade', 'E ser-me-eis santos, porque eu, o Senhor', 'Levítico 20:26', 'Levítico', 20, 26, NULL),
  ('santidade', 'Fazei todas as coisas sem murmurações nem contendas; para que sejais irrepreensíveis e sinceros, filhos de Deus inculpáveis no meio duma geração corrompida e perversa, entre a qual resplandeceis como astros no mundo; retendo a palavra da vida.', 'Filipenses 2:14-16a', 'Filipenses 2:14-16a', NULL, NULL, NULL),
  ('santidade', 'Não há santo como é o Senhor', '1 Samuel 2:2', '1 Samuel', 2, 2, NULL),
  ('santidade', 'Mas a prostituição e toda impureza ou avareza nem ainda se nomeiem entre vós, como convém a santos.', 'Efésios 5:3', 'Efésios', 5, 3, NULL),
  ('santidade', 'Rogo-vos, pois, irmãos, pela compaixão de Deus, que apresenteis o vosso corpo em sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional.', 'Romanos 12:1', 'Romanos', 12, 1, NULL),
  ('santidade', 'Mas, agora, libertados do pecado e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna.', 'Romanos 6:22', 'Romanos', 6, 22, NULL),
  ('santidade', 'Porque assim diz o Alto e o Sublime, que habita na eternidade e cujo nome é Santo: Em um alto e santo lugar habito e também com o contrito e abatido de espírito, para vivificar o espírito dos abatidos e para vivificar o coração dos contritos.', 'Isaías 57:15', 'Isaías', 57, 15, NULL),
  ('santidade', 'Sede vós, pois, perfeitos, como é perfeito o vosso Pai, que está nos céus.', 'Mateus 5:48', 'Mateus', 5, 48, NULL),
  ('santidade', 'Não sabeis vós que sois o templo de Deus e que o Espírito de Deus habita em vós?', '1 Coríntios 3:16', '1 Coríntios', 3, 16, NULL),
  ('santidade', 'E rogo-vos, irmãos, que noteis os que promovem dissensões e escândalos contra a doutrina que aprendestes; desviai-vos deles.', 'Romanos 16:17', 'Romanos', 16, 17, NULL),
  ('santidade', 'Assim, eu me engrandecerei, e me santificarei, e me farei conhecer aos olhos de muitas nações; e saberão que eu sou o Senhor', 'Ezequiel 38:23', 'Ezequiel', 38, 23, NULL),
  ('santidade', 'E ali haverá um alto caminho, um caminho que se chamará O Caminho Santo; o imundo não passará por ele, mas será para o povo de Deus; os caminhantes, até mesmo os loucos, não errarão.', 'Isaías 35:8', 'Isaías', 35, 8, NULL),
  ('santidade', 'Buscai o bem e não o mal, para que vivais; e assim o Senhor', 'Amós 5:14', 'Amós', 5, 14, NULL),
  ('santidade', 'Bendize, ó minha alma, ao Senhor', 'Salmo 103:1', 'Salmo', 103, 1, NULL),
  ('santidade', 'O temor do Senhor', 'Provérbios 9:10', 'Provérbios', 9, 10, NULL),
  ('santidade', 'Laço é para o homem dizer precipitadamente: É santo; e, feitos os votos, então, inquirir.', 'Provérbios 20:25', 'Provérbios', 20, 25, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('santidade', 'E eu santificarei o meu grande nome, que foi profanado entre as nações, o qual profanastes no meio delas; e as nações saberão que eu sou o Senhor', 'Ezequiel 36:23', 'Ezequiel', 36, 23, NULL),
  ('santidade', 'E ninguém, acendendo uma candeia, a cobre com algum vaso ou a põe debaixo da cama; mas põe-na no velador, para que os que entram vejam a luz.', 'Lucas 8:16', 'Lucas', 8, 16, NULL),
  ('santidade', 'Cantai a Deus, cantai louvores ao seu nome; louvai aquele que vai sobre os céus, pois o seu nome é Jeová', 'Salmo 68:4-5', 'Salmo', 68, 4, 5),
  ('santidade', 'Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz.', '1 Pedro 2:9', '1 Pedro', 2, 9, NULL),
  ('santidade', 'Se alguém destruir o templo de Deus, Deus o destruirá; porque o templo de Deus, que sois vós, é santo.', '1 Coríntios 3:17', '1 Coríntios', 3, 17, NULL),
  ('santidade', 'Porque esta é a vontade de Deus, a vossa santificação: que vos abstenhais da prostituição, que cada um de vós saiba possuir o seu vaso em santificação e honra, não na paixão de concupiscência, como os gentios, que não conhecem a Deus.', '1 Tessalonicenses 4:3-5', '1 Tessalonicenses', 4, 3, 5),
  ('santidade', 'Ele é a Rocha cuja obra é perfeita, porque todos os seus caminhos juízo são; Deus é a verdade, e não há nele injustiça; justo e reto é.', 'Deuteronômio 32:4', 'Deuteronômio', 32, 4, NULL),
  ('santidade', 'Porque, com uma só oblação, aperfeiçoou para sempre os que são santificados.', 'Hebreus 10:14', 'Hebreus', 10, 14, NULL),
  ('santidade', 'Todos os caminhos do homem são limpos aos seus olhos, mas o Senhor', 'Provérbios 16:2', 'Provérbios', 16, 2, NULL),
  ('saude', 'E servireis ao Senhor', 'Êxodo 23:25', 'Êxodo', 23, 25, NULL),
  ('saude', 'Amado, desejo que te vá bem em todas as coisas e que tenhas saúde, assim como bem vai a tua alma.', '3 João 1:2', '3 João', 1, 2, NULL),
  ('saude', 'Sara os quebrantados de coração e liga-lhes as feridas.', 'Salmo 147:3', 'Salmo', 147, 3, NULL),
  ('saude', 'O coração alegre serve de bom remédio, mas o espírito abatido virá a secar os ossos.', 'Provérbios 17:22', 'Provérbios', 17, 22, NULL),
  ('saude', 'Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos? Porque fostes comprados por bom preço; glorificai, pois, a Deus no vosso corpo e no vosso espírito, os quais pertencem a Deus.', '1 Coríntios 6:19-20', '1 Coríntios', 6, 19, 20),
  ('saude', 'Curai os enfermos, limpai os leprosos, ressuscitai os mortos, expulsai os demônios; de graça recebestes, de graça dai.', 'Mateus 10:8', 'Mateus', 10, 8, NULL),
  ('saude', 'Favo de mel são as palavras suaves: doces para a alma e saúde para os ossos.', 'Provérbios 16:24', 'Provérbios', 16, 24, NULL),
  ('saude', 'Não sejas sábio a teus próprios olhos; teme ao Senhor', 'Provérbios 3:7-8', 'Provérbios', 3, 7, 8),
  ('saude', 'Jesus, porém, ouvindo, disse-lhes: Não necessitam de médico os sãos, mas sim, os doentes.', 'Mateus 9:12', 'Mateus', 9, 12, NULL),
  ('saude', 'Afasta, pois, a ira do teu coração e remove da tua carne o mal, porque a adolescência e a juventude são vaidade.', 'Eclesiastes 11:10', 'Eclesiastes', 11, 10, NULL),
  ('saude', 'Porque o exercício corporal para pouco aproveita, mas a piedade para tudo é proveitosa, tendo a promessa da vida presente e da que há de vir.', '1 Timóteo 4:8', '1 Timóteo', 4, 8, NULL),
  ('saude', 'A esperança demorada enfraquece o coração, mas o desejo chegado é árvore de vida.', 'Provérbios 13:12', 'Provérbios', 13, 12, NULL),
  ('seguir', 'Andareis em todo o caminho que vos manda o Senhor', 'Deuteronômio 5:33', 'Deuteronômio', 5, 33, NULL),
  ('seguir', 'O Senhor', 'Deuteronômio 31:8', 'Deuteronômio', 31, 8, NULL),
  ('seguir', 'Ordena os meus passos na tua palavra, e não se apodere de mim iniquidade alguma.', 'Salmo 119:133', 'Salmo', 119, 133, NULL),
  ('seguir', 'Falou-lhes, pois, Jesus outra vez, dizendo: Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.', 'João 8:12', 'João', 8, 12, NULL),
  ('seguir', 'Ora, o Senhor encaminhe o vosso coração no amor de Deus e na paciência de Cristo.', '2 Tessalonicenses 3:5', '2 Tessalonicenses', 3, 5, NULL),
  ('seguir', 'Após o Senhor', 'Deuteronômio 13:4', 'Deuteronômio', 13, 4, NULL),
  ('seguir', 'E quem não toma a sua cruz e não segue após mim não é digno de mim.', 'Mateus 10:38', 'Mateus', 10, 38, NULL),
  ('seguir', 'E, chamando a si a multidão, com os seus discípulos, disse-lhes: Se alguém quiser vir após mim, negue-se a si mesmo, e tome a sua cruz, e siga-me.', 'Marcos 8:34', 'Marcos', 8, 34, NULL),
  ('seguir', 'Se alguém me serve, siga-me; e, onde eu estiver, ali estará também o meu servo. E, se alguém me servir, meu Pai o honrará.', 'João 12:26', 'João', 12, 26, NULL),
  ('seguir', 'Se vivemos no Espírito, andemos também no Espírito.', 'Gálatas 5:25', 'Gálatas', 5, 25, NULL),
  ('seguir', 'Porque para isto sois chamados, pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas.', '1 Pedro 2:21', '1 Pedro', 2, 21, NULL),
  ('seguir', 'Sede, pois, imitadores de Deus, como filhos amados.', 'Efésios 5:1', 'Efésios', 5, 1, NULL),
  ('seguir', 'Bem-aventurado aquele que teme ao Senhor', 'Salmo 128:1', 'Salmo', 128, 1, NULL),
  ('seguir', 'Os passos de um homem bom são confirmados pelo Senhor', 'Salmo 37:23', 'Salmo', 37, 23, NULL),
  ('seguir', 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas.', 'Efésios 2:10', 'Efésios', 2, 10, NULL),
  ('seguir', 'E, quanto fizerdes por palavras ou por obras, fazei tudo em nome do Senhor Jesus, dando por ele graças a Deus Pai.', 'Colossenses 3:17', 'Colossenses', 3, 17, NULL),
  ('seguir', 'Jesus dizia, pois, aos judeus que criam nele: Se vós permanecerdes na minha palavra, verdadeiramente, sereis meus discípulos e conhecereis a verdade, e a verdade vos libertará.', 'João 8:31-32', 'João', 8, 31, 32),
  ('seguir', 'Disse-lhe Jesus: Se queres ser perfeito, vai, vende tudo o que tens, dá-o aos pobres e terás um tesouro no céu; e vem e segue-me.', 'Mateus 19:21', 'Mateus', 19, 21, NULL),
  ('seguir', 'Não declines nem para a direita nem para a esquerda; retira o teu pé do mal.', 'Provérbios 4:27', 'Provérbios', 4, 27, NULL),
  ('seguir', 'Ora, o Deus de paz, que pelo sangue do concerto eterno tornou a trazer dos mortos a nosso Senhor Jesus Cristo, grande Pastor das ovelhas, vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável por Cristo Jesus, ao qual seja glória para todo o sempre. Amém!', 'Hebreus 13:20-21', 'Hebreus', 13, 20, 21),
  ('seguir', 'Assim também a fé, se não tiver as obras, é morta em si mesma.', 'Tiago 2:17', 'Tiago', 2, 17, NULL),
  ('seguir', 'Nisto todos conhecerão que sois meus discípulos, se vos amardes uns aos outros.', 'João 13:35', 'João', 13, 35, NULL),
  ('seguir', 'Porém, se vos parece mal aos vossos olhos servir ao Senhor', 'Josué 24:15', 'Josué', 24, 15, NULL),
  ('seguir', 'Apressei-me e não me detive a observar os teus mandamentos.', 'Salmo 119:60', 'Salmo', 119, 60, NULL),
  ('seguir', 'Nisto é glorificado meu Pai: que deis muito fruto; e assim sereis meus discípulos.', 'João 15:8', 'João', 15, 8, NULL),
  ('seguir', 'E disse-lhes: Vinde após mim, e eu vos farei pescadores de homens.', 'Mateus 4:19', 'Mateus', 4, 19, NULL),
  ('seguir', 'E porei dentro de vós o meu espírito e farei que andeis nos meus estatutos, e guardeis os meus juízos, e os observeis.', 'Ezequiel 36:27', 'Ezequiel', 36, 27, NULL),
  ('seguir', 'E guarda os mandamentos do Senhor', 'Deuteronômio 8:6', 'Deuteronômio', 8, 6, NULL),
  ('seguir', 'Nada acrescentareis à palavra que vos mando, nem diminuireis dela, para que guardeis os mandamentos do Senhor', 'Deuteronômio 4:2', 'Deuteronômio', 4, 2, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('seguir', 'Então, vos anunciou ele o seu concerto, que vos prescreveu, os dez mandamentos, e os escreveu em duas tábuas de pedra.', 'Deuteronômio 4:13', 'Deuteronômio', 4, 13, NULL),
  ('segunda-vinda', 'Por isso, estai vós apercebidos também, porque o Filho do Homem há de vir à hora em que não penseis.', 'Mateus 24:44', 'Mateus', 24, 44, NULL),
  ('segunda-vinda', 'E consideremo-nos uns aos outros, para nos estimularmos ao amor e às boas obras, não deixando a nossa congregação, como é costume de alguns; antes, admoestando-nos uns aos outros; e tanto mais quanto vedes que se vai aproximando aquele Dia.', 'Hebreus 10:24-25', 'Hebreus', 10, 24, 25),
  ('segunda-vinda', 'Aquele que testifica estas coisas diz: Certamente, cedo venho. Amém! Ora, vem, Senhor Jesus!', 'Apocalipse 22:20', 'Apocalipse', 22, 20, NULL),
  ('segunda-vinda', 'E eis que cedo venho, e o meu galardão está comigo para dar a cada um segundo a sua obra.', 'Apocalipse 22:12', 'Apocalipse', 22, 12, NULL),
  ('segunda-vinda', 'Vigiai, pois, porque não sabeis a que hora há de vir o vosso Senhor.', 'Mateus 24:42', 'Mateus', 24, 42, NULL),
  ('segunda-vinda', 'E já está próximo o fim de todas as coisas; portanto, sede sóbrios e vigiai em oração.', '1 Pedro 4:7', '1 Pedro', 4, 7, NULL),
  ('segunda-vinda', 'Eis que vem com as nuvens, e todo olho o verá, até os mesmos que o traspassaram; e todas as tribos da terra se lamentarão sobre ele. Sim! Amém!', 'Apocalipse 1:7', 'Apocalipse', 1, 7, NULL),
  ('segunda-vinda', 'Eis que venho sem demora; guarda o que tens, para que ninguém tome a tua coroa.', 'Apocalipse 3:11', 'Apocalipse', 3, 11, NULL),
  ('segunda-vinda', 'Eu sou o Alfa e o Ômega, o Princípio e o Fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-Poderoso.', 'Apocalipse 1:8', 'Apocalipse', 1, 8, NULL),
  ('segunda-vinda', 'E, estando com os olhos fitos no céu, enquanto ele subia, eis que junto deles se puseram dois varões vestidos de branco, os quais lhes disseram: Varões galileus, por que estais olhando para o céu? Esse Jesus, que dentre vós foi recebido em cima no céu, há de vir assim como para o céu o vistes ir.', 'Atos 1:10-11', 'Atos', 1, 10, 11),
  ('segunda-vinda', 'E agora, filhinhos, permanecei nele, para que, quando ele se manifestar, tenhamos confiança e não sejamos confundidos por ele na sua vinda.', '1 João 2:28', '1 João', 2, 28, NULL),
  ('segunda-vinda', 'Mas, amados, não ignoreis uma coisa: que um dia para o Senhor é como mil anos, e mil anos, como um dia.', '2 Pedro 3:8', '2 Pedro', 3, 8, NULL),
  ('segunda-vinda', 'Acautelai-vos, porém, dos falsos profetas, que vêm até vós vestidos como ovelhas, mas interiormente são lobos devoradores.', 'Mateus 7:15', 'Mateus', 7, 15, NULL),
  ('segunda-vinda', 'Portanto, se vos disserem: Eis que ele está no deserto, não saiais; ou: Eis que ele está no interior da casa, não acrediteis. Porque, assim como o relâmpago sai do oriente e se mostra até ao ocidente, assim será também a vinda do Filho do Homem.', 'Mateus 24:26-27', 'Mateus', 24, 26, 27),
  ('segunda-vinda', 'Tendo por certo isto mesmo: que aquele que em vós começou a boa obra a aperfeiçoará até ao Dia de Jesus Cristo.', 'Filipenses 1:6', 'Filipenses', 1, 6, NULL),
  ('segunda-vinda', 'E não entristeçais o Espírito Santo de Deus, no qual estais selados para o Dia da redenção.', 'Efésios 4:30', 'Efésios', 4, 30, NULL),
  ('segunda-vinda', 'Porque o mesmo Senhor descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus; e os que morreram em Cristo ressuscitarão primeiro; depois, nós, os que ficarmos vivos, seremos arrebatados juntamente com eles nas nuvens, a encontrar o Senhor nos ares, e assim estaremos sempre com o Senhor.', '1 Tessalonicenses 4:16-17', '1 Tessalonicenses', 4, 16, 17),
  ('segunda-vinda', 'Ninguém, de maneira alguma, vos engane, porque não será assim sem que antes venha a apostasia e se manifeste o homem do pecado, o filho da perdição, o qual se opõe e se levanta contra tudo o que se chama Deus ou se adora; de sorte que se assentará, como Deus, no templo de Deus, querendo parecer Deus.', '2 Tessalonicenses 2:3-4', '2 Tessalonicenses', 2, 3, 4),
  ('segunda-vinda', 'Porque o Filho do Homem virá na glória de seu Pai, com os seus anjos; e, então, dará a cada um segundo as suas obras.', 'Mateus 16:27', 'Mateus', 16, 27, NULL),
  ('segunda-vinda', 'Mas o Dia do Senhor virá como o ladrão de noite, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se desfarão, e a terra e as obras que nela há se queimarão.', '2 Pedro 3:10', '2 Pedro', 3, 10, NULL),
  ('seguranca', 'Mas fiel é o Senhor, que vos confortará e guardará do maligno.', '2 Tessalonicenses 3:3', '2 Tessalonicenses', 3, 3, NULL),
  ('seguranca', 'O Senhor', 'Salmo 27:1', 'Salmo', 27, 1, NULL),
  ('seguranca', 'Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. Direi do Senhor', 'Salmo 91:1-2', 'Salmo', 91, 1, 2),
  ('seguranca', 'Deus é o nosso refúgio e fortaleza, socorro bem-presente na angústia.', 'Salmo 46:1', 'Salmo', 46, 1, NULL),
  ('seguranca', 'Tu és o lugar em que me escondo; tu me preservas da angústia; tu me cinges de alegres cantos de livramento. (Selá)', 'Salmo 32:7', 'Salmo', 32, 7, NULL),
  ('seguranca', 'Em paz também me deitarei e dormirei, porque só tu, Senhor', 'Salmo 4:8', 'Salmo', 4, 8, NULL),
  ('seguranca', 'O Senhor', 'Naum 1:7', 'Naum', 1, 7, NULL),
  ('seguranca', 'Lança o teu cuidado sobre o Senhor', 'Salmo 55:22', 'Salmo', 55, 22, NULL),
  ('seguranca', 'Ele te cobrirá com as suas penas, e debaixo das suas asas estarás seguro; a sua verdade é escudo e broquel.', 'Salmo 91:4', 'Salmo', 91, 4, NULL),
  ('seguranca', 'O avisado vê o mal e esconde-se; mas os simples passam e sofrem a pena.', 'Provérbios 27:12', 'Provérbios', 27, 12, NULL),
  ('seguranca', 'Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti.', 'Isaías 26:3', 'Isaías', 26, 3, NULL),
  ('seguranca', 'Quem anda em sinceridade anda seguro, mas o que perverte os seus caminhos será conhecido.', 'Provérbios 10:9', 'Provérbios', 10, 9, NULL),
  ('seguranca', 'O Senhor', 'Salmo 138:8', 'Salmo', 138, 8, NULL),
  ('seguranca', 'Não peço que os tires do mundo, mas que os livres do mal.', 'João 17:15', 'João', 17, 15, NULL),
  ('seguranca', 'Não durmamos, pois, como os demais, mas vigiemos e sejamos sóbrios.', '1 Tessalonicenses 5:6', '1 Tessalonicenses', 5, 6, NULL),
  ('seguranca', 'É melhor confiar no Senhor', 'Salmo 118:8', 'Salmo', 118, 8, NULL),
  ('seguranca', 'Porque satisfiz a alma cansada, e toda a alma entristecida saciei.', 'Jeremias 31:25', 'Jeremias', 31, 25, NULL),
  ('seguranca', 'Torre forte é o nome do Senhor', 'Provérbios 18:10', 'Provérbios', 18, 10, NULL),
  ('seguranca', 'Só ele é a minha rocha e a minha salvação; é a minha defesa; não serei grandemente abalado.', 'Salmo 62:2', 'Salmo', 62, 2, NULL),
  ('seguranca', 'Confia no Senhor', 'Salmo 37:3', 'Salmo', 37, 3, NULL),
  ('seguranca', 'Ainda que um exército me cercasse, o meu coração não temeria; ainda que a guerra se levantasse contra mim, nele confiaria.', 'Salmo 27:3', 'Salmo', 27, 3, NULL),
  ('seguranca', 'O Senhor', 'Salmo 9:9', 'Salmo', 9, 9, NULL),
  ('seguranca', 'Portanto, tomai toda a armadura de Deus, para que possais resistir no dia mau e, havendo feito tudo, ficar firmes.', 'Efésios 6:13', 'Efésios', 6, 13, NULL),
  ('seguranca', 'Sujeitai-vos, pois, a Deus; resisti ao diabo, e ele fugirá de vós.', 'Tiago 4:7', 'Tiago', 4, 7, NULL),
  ('seguranca', 'Sara-me, Senhor', 'Jeremias 17:14', 'Jeremias', 17, 14, NULL),
  ('seguranca', 'Cantai a Deus, cantai louvores ao seu nome; louvai aquele que vai sobre os céus, pois o seu nome é Jeová', 'Salmo 68:4-5', 'Salmo', 68, 4, 5),
  ('seguranca', 'E eu convosco estabeleço o meu concerto, que não será mais destruída toda carne pelas águas do dilúvio e que não haverá mais dilúvio para destruir a terra.', 'Gênesis 9:11', 'Gênesis', 9, 11, NULL),
  ('servir', 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.', '1 Coríntios 15:58', '1 Coríntios', 15, 58, NULL),
  ('servir', 'Não sejais vagarosos no cuidado; sede fervorosos no espírito, servindo ao Senhor.', 'Romanos 12:11', 'Romanos', 12, 11, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('servir', 'Se alguém me serve, siga-me; e, onde eu estiver, ali estará também o meu servo. E, se alguém me servir, meu Pai o honrará.', 'João 12:26', 'João', 12, 26, NULL),
  ('servir', 'E ele, assentando-se, chamou os doze e disse-lhes: Se alguém quiser ser o primeiro, será o derradeiro de todos e o servo de todos.', 'Marcos 9:35', 'Marcos', 9, 35, NULL),
  ('servir', 'Porque o Filho do Homem também não veio para ser servido, mas para servir e dar a sua vida em resgate de muitos.', 'Marcos 10:45', 'Marcos', 10, 45, NULL),
  ('servir', 'E o seu senhor lhe disse: Bem está, servo bom e fiel. Sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor.', 'Mateus 25:21', 'Mateus', 25, 21, NULL),
  ('servir', 'Porque nós somos cooperadores de Deus; vós sois lavoura de Deus e edifício de Deus.', '1 Coríntios 3:9', '1 Coríntios', 3, 9, NULL),
  ('servir', 'Após o Senhor', 'Deuteronômio 13:4', 'Deuteronômio', 13, 4, NULL),
  ('servir', 'Agora, pois, ó Israel, que é o que o Senhor', 'Deuteronômio 10:12-13', 'Deuteronômio', 10, 12, 13),
  ('servir', 'Porque vós, irmãos, fostes chamados à liberdade. Não useis, então, da liberdade para dar ocasião à carne, mas servi-vos uns aos outros pelo amor.', 'Gálatas 5:13', 'Gálatas', 5, 13, NULL),
  ('servir', 'Bem como o Filho do Homem não veio para ser servido, mas para servir e para dar a sua vida em resgate de muitos.', 'Mateus 20:28', 'Mateus', 20, 28, NULL),
  ('servir', 'Toda Escritura divinamente inspirada é proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça, para que o homem de Deus seja perfeito e perfeitamente instruído para toda boa obra.', '2 Timóteo 3:16-17', '2 Timóteo', 3, 16, 17),
  ('servir', 'Porque Deus não é injusto para se esquecer da vossa obra e do trabalho de amor que, para com o seu nome, mostrastes, enquanto servistes aos santos e ainda servis.', 'Hebreus 6:10', 'Hebreus', 6, 10, NULL),
  ('servir', 'Os passos de um homem bom são confirmados pelo Senhor', 'Salmo 37:23', 'Salmo', 37, 23, NULL),
  ('servir', 'Não será assim entre vós; mas todo aquele que quiser, entre vós, fazer-se grande, que seja vosso serviçal; e qualquer que, entre vós, quiser ser o primeiro, que seja vosso servo.', 'Mateus 20:26-27', 'Mateus', 20, 26, 27),
  ('servir', 'Ora, se eu, Senhor e Mestre, vos lavei os pés, vós deveis também lavar os pés uns aos outros.', 'João 13:14', 'João', 13, 14, NULL),
  ('servir', 'Tão somente temei ao Senhor', '1 Samuel 12:24', '1 Samuel', 12, 24, NULL),
  ('servir', 'Porém, se vos parece mal aos vossos olhos servir ao Senhor', 'Josué 24:15', 'Josué', 24, 15, NULL),
  ('servir', 'Tão somente tende cuidado de guardar com diligência o mandamento e a lei que Moisés, o servo do Senhor', 'Josué 22:5', 'Josué', 22, 5, NULL),
  ('servir', 'Ninguém pode servir a dois senhores, porque ou há de odiar um e amar o outro ou se dedicará a um e desprezará o outro. Não podeis servir a Deus e a Mamom.', 'Mateus 6:24', 'Mateus', 6, 24, NULL),
  ('servir', 'Como livres e não tendo a liberdade por cobertura da malícia, mas como servos de Deus.', '1 Pedro 2:16', '1 Pedro', 2, 16, NULL),
  ('servir', 'O Senhor', 'Salmo 34:22', 'Salmo', 34, 22, NULL),
  ('servir', 'Nem tampouco apresenteis os vossos membros ao pecado por instrumentos de iniquidade; mas apresentai-vos a Deus, como vivos dentre mortos, e os vossos membros a Deus, como instrumentos de justiça.', 'Romanos 6:13', 'Romanos', 6, 13, NULL),
  ('servir', 'Quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo imaculado a Deus, purificará a vossa consciência das obras mortas, para servirdes ao Deus vivo?', 'Hebreus 9:14', 'Hebreus', 9, 14, NULL),
  ('servir', 'Na verdade, na verdade vos digo que não é o servo maior do que o seu senhor, nem o enviado, maior do que aquele que o enviou.', 'João 13:16', 'João', 13, 16, NULL),
  ('servir', 'E eles serão meus, diz o Senhor', 'Malaquias 3:17', 'Malaquias', 3, 17, NULL),
  ('servir', 'E disse o povo a Josué: Serviremos ao Senhor', 'Josué 24:24', 'Josué', 24, 24, NULL),
  ('servir', 'Respondeu Jesus: O meu Reino não é deste mundo; se o meu Reino fosse deste mundo, lutariam os meus servos, para que eu não fosse entregue aos judeus; mas, agora, o meu Reino não é daqui.', 'João 18:36', 'João', 18, 36, NULL),
  ('sexualidade', 'Porque esta é a vontade de Deus, a vossa santificação: que vos abstenhais da prostituição, que cada um de vós saiba possuir o seu vaso em santificação e honra, não na paixão de concupiscência, como os gentios, que não conhecem a Deus.', '1 Tessalonicenses 4:3-5', '1 Tessalonicenses', 4, 3, 5),
  ('sexualidade', 'Não vos defraudeis um ao outro, senão por consentimento mútuo, por algum tempo, para vos aplicardes à oração; e, depois, ajuntai-vos outra vez, para que Satanás vos não tente pela vossa incontinência.', '1 Coríntios 7:5', '1 Coríntios', 7, 5, NULL),
  ('sexualidade', 'Não sabeis que os injustos não hão de herdar o Reino de Deus? Não erreis: nem os devassos, nem os idólatras, nem os adúlteros, nem os efeminados, nem os sodomitas, nem os ladrões, nem os avarentos, nem os bêbados, nem os maldizentes, nem os roubadores herdarão o Reino de Deus.', '1 Coríntios 6:9-10', '1 Coríntios', 6, 9, 10),
  ('sexualidade', 'O marido pague à mulher a devida benevolência, e da mesma sorte a mulher, ao marido. A mulher não tem poder sobre o seu próprio corpo, mas tem-no o marido; e também, da mesma maneira, o marido não tem poder sobre o seu próprio corpo, mas tem-no a mulher.', '1 Coríntios 7:3-4', '1 Coríntios', 7, 3, 4),
  ('sexualidade', 'Pois mudaram a verdade de Deus em mentira e honraram e serviram mais a criatura do que o Criador, que é bendito eternamente. Amém! Pelo que Deus os abandonou às paixões infames. Porque até as suas mulheres mudaram o uso natural, no contrário à natureza. E, semelhantemente, também os varões, deixando o uso natural da mulher, se inflamaram em sua sensualidade uns para com os outros, varão com varão, cometendo torpeza e recebendo em si mesmos a recompensa que convinha ao seu erro. E, como eles se não importaram de ter conhecimento de Deus, assim Deus os entregou a um sentimento perverso, para fazerem coisas que não convém.', 'Romanos 1:25-28', 'Romanos', 1, 25, 28),
  ('sexualidade', 'Igualmente vós, maridos, coabitai com ela com entendimento, dando honra à mulher, como vaso mais fraco; como sendo vós os seus coerdeiros da graça da vida; para que não sejam impedidas as vossas orações.', '1 Pedro 3:7', '1 Pedro', 3, 7, NULL),
  ('sexualidade', 'Venerado seja entre todos o matrimônio e o leito sem mácula; porém aos que se dão à prostituição e aos adúlteros Deus os julgará.', 'Hebreus 13:4', 'Hebreus', 13, 4, NULL),
  ('sexualidade', 'Mortificai, pois, os vossos membros que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência e a avareza, que é idolatria.', 'Colossenses 3:5', 'Colossenses', 3, 5, NULL),
  ('sexualidade', 'Ouvistes que foi dito aos antigos: Não cometerás adultério. Eu porém, vos digo que qualquer que atentar numa mulher para a cobiçar já em seu coração cometeu adultério com ela.', 'Mateus 5:27-28', 'Mateus', 5, 27, 28),
  ('sexualidade', 'E nas franjas vos estará, para que o vejais, e vos lembreis de todos os mandamentos do Senhor', 'Números 15:39', 'Números', 15, 39, NULL),
  ('sexualidade', 'Por isso, deixará o homem seu pai e sua mãe e se unirá à sua mulher; e serão dois numa carne.', 'Efésios 5:31', 'Efésios', 5, 31, NULL),
  ('sexualidade', 'Fugi da prostituição. Todo pecado que o homem comete é fora do corpo; mas o que se prostitui peca contra o seu próprio corpo.', '1 Coríntios 6:18', '1 Coríntios', 6, 18, NULL),
  ('sexualidade', 'Mas, por causa da prostituição, cada um tenha a sua própria mulher, e cada uma tenha o seu próprio marido.', '1 Coríntios 7:2', '1 Coríntios', 7, 2, NULL),
  ('sexualidade', 'Fiz concerto com os meus olhos; como, pois, os fixaria numa virgem?', 'Jó 31:1', 'Jó', 31, 1, NULL),
  ('sexualidade', 'Porque as obras da carne são manifestas, as quais são: prostituição, impureza, lascívia, idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias, invejas, homicídios, bebedices, glutonarias e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas não herdarão o Reino de Deus.', 'Gálatas 5:19-21', 'Gálatas', 5, 19, 21),
  ('sexualidade', 'Porém, desde o princípio da criação, Deus os fez macho e fêmea. Por isso, deixará o homem a seu pai e a sua mãe e unir-se-á a sua mulher. E serão os dois uma só carne e, assim, já não serão dois, mas uma só carne. Portanto, o que Deus ajuntou, não o separe o homem.', 'Marcos 10:6-9', 'Marcos', 10, 6, 9),
  ('sexualidade', 'Mas a prostituição e toda impureza ou avareza nem ainda se nomeiem entre vós, como convém a santos.', 'Efésios 5:3', 'Efésios', 5, 3, NULL),
  ('sexualidade', 'Ele, porém, respondendo, disse-lhes: Não tendes lido que, no princípio, o Criador os fez macho e fêmea e disse: Portanto, deixará o homem pai e mãe e se unirá à sua mulher, e serão dois numa só carne? Assim não são mais dois, mas uma só carne. Portanto, o que Deus ajuntou não separe o homem.', 'Mateus 19:4-6', 'Mateus', 19, 4, 6),
  ('sexualidade', 'Sabendo isto: que a lei não é feita para o justo, mas para os injustos e obstinados, para os ímpios e pecadores, para os profanos e irreligiosos, para os parricidas e matricidas, para os homicidas, para os fornicadores, para os sodomitas, para os roubadores de homens, para os mentirosos, para os perjuros e para o que for contrário à sã doutrina, conforme o evangelho da glória do Deus bem-aventurado, que me foi confiado.', '1 Timóteo 1:9-11', '1 Timóteo', 1, 9, 11),
  ('sexualidade', 'E Deus os abençoou e Deus lhes disse: Frutificai, e multiplicai-vos, e enchei a terra, e sujeitai-a; e dominai sobre os peixes do mar, e sobre as aves dos céus, e sobre todo o animal que se move sobre a terra.', 'Gênesis 1:28', 'Gênesis', 1, 28, NULL),
  ('sexualidade', 'E da costela que o Senhor', 'Gênesis 2:22-24', 'Gênesis', 2, 22, 24),
  ('sexualidade', 'E dizia: O que sai do homem, isso é que contamina o homem. Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios, os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura. Todos estes males procedem de dentro e contaminam o homem.', 'Marcos 7:20-23', 'Marcos', 7, 20, 23),
  ('sofrimento', 'E o Deus de toda a graça, que em Cristo Jesus vos chamou à sua eterna glória, depois de haverdes padecido um pouco, ele mesmo vos aperfeiçoará, confirmará, fortificará e fortalecerá.', '1 Pedro 5:10', '1 Pedro', 5, 10, NULL),
  ('sofrimento', 'E não somente isto, mas também nos gloriamos nas tribulações, sabendo que a tribulação produz a paciência; e a paciência, a experiência; e a experiência, a esperança.', 'Romanos 5:3-4', 'Romanos', 5, 3, 4);

