-- Parte 13: versículos (8 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('sofrimento', 'Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda consolação, que nos consola em toda a nossa tribulação, para que também possamos consolar os que estiverem em alguma tribulação, com a consolação com que nós mesmos somos consolados de Deus.', '2 Coríntios 1:3-4', '2 Coríntios', 1, 3, 4),
  ('sofrimento', 'Porque para mim tenho por certo que as aflições deste tempo presente não são para comparar com a glória que em nós há de ser revelada.', 'Romanos 8:18', 'Romanos', 8, 18, NULL),
  ('sofrimento', 'Muitas são as aflições do justo, mas o Senhor', 'Salmo 34:19', 'Salmo', 34, 19, NULL),
  ('sofrimento', 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente.', '2 Coríntios 4:17', '2 Coríntios', 4, 17, NULL),
  ('sofrimento', 'Quem nos separará do amor de Cristo? A tribulação, ou a angústia, ou a perseguição, ou a fome, ou a nudez, ou o perigo, ou a espada?', 'Romanos 8:35', 'Romanos', 8, 35, NULL),
  ('sofrimento', 'Ora, pois, já que Cristo padeceu por nós na carne, armai-vos também vós com este pensamento: que aquele que padeceu na carne já cessou do pecado.', '1 Pedro 4:1', '1 Pedro', 4, 1, NULL),
  ('sofrimento', 'Mas também, se padecerdes por amor da justiça, sois bem-aventurados. E não temais com medo deles, nem vos turbeis.', '1 Pedro 3:14', '1 Pedro', 3, 14, NULL),
  ('sofrimento', 'Porque a vós vos foi concedido, em relação a Cristo, não somente crer nele, como também padecer por ele.', 'Filipenses 1:29', 'Filipenses', 1, 29, NULL),
  ('sofrimento', 'Levai as cargas uns dos outros e assim cumprireis a lei de Cristo.', 'Gálatas 6:2', 'Gálatas', 6, 2, NULL),
  ('sofrimento', 'Era desprezado e o mais indigno entre os homens, homem de dores, experimentado nos trabalhos e, como um de quem os homens escondiam o rosto, era desprezado, e não fizemos dele caso algum.', 'Isaías 53:3', 'Isaías', 53, 3, NULL),
  ('sofrimento', 'E quem não toma a sua cruz e não segue após mim não é digno de mim.', 'Mateus 10:38', 'Mateus', 10, 38, NULL),
  ('sofrimento', 'Porque, como as aflições de Cristo são abundantes em nós, assim também a nossa consolação sobeja por meio de Cristo.', '2 Coríntios 1:5', '2 Coríntios', 1, 5, NULL),
  ('sofrimento', 'Porque para isto sois chamados, pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas.', '1 Pedro 2:21', '1 Pedro', 2, 21, NULL),
  ('sofrimento', 'Verdadeiramente, ele tomou sobre si as nossas enfermidades e as nossas dores levou sobre si; e nós o reputamos por aflito, ferido de Deus e oprimido.', 'Isaías 53:4', 'Isaías', 53, 4, NULL),
  ('sofrimento', 'Para conhecê-lo, e a virtude da sua ressurreição, e a comunicação de suas aflições, sendo feito conforme a sua morte.', 'Filipenses 3:10', 'Filipenses', 3, 10, NULL),
  ('sofrimento', 'Então, Jó se levantou, e rasgou o seu manto, e rapou a sua cabeça, e se lançou em terra, e adorou, e disse: Nu saí do ventre de minha mãe e nu tornarei para lá; o Senhor', 'Jó 1:20-21', 'Jó', 1, 20, 21),
  ('sofrimento', 'Quem achar a sua vida perdê-la-á; e quem perder a sua vida por amor de mim achá-la-á.', 'Mateus 10:39', 'Mateus', 10, 39, NULL),
  ('sofrimento', 'E te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conheceste, nem teus pais o conheceram, para te dar a entender que o homem não viverá só de pão, mas que de tudo o que sai da boca do Senhor', 'Deuteronômio 8:3', 'Deuteronômio', 8, 3, NULL),
  ('sofrimento', 'E, despindo-o, o cobriram com uma capa escarlate. E, tecendo uma coroa de espinhos, puseram-lha na cabeça e, em sua mão direita, uma cana; e, ajoelhando diante dele, o escarneciam, dizendo: Salve, Rei dos judeus!', 'Mateus 27:28-29', 'Mateus', 27, 28, 29),
  ('sofrimento', 'E ainda que distribuísse toda a minha fortuna para sustento dos pobres, e ainda que entregasse o meu corpo para ser queimado, e não tivesse amor, nada disso me aproveitaria.', '1 Coríntios 13:3', '1 Coríntios', 13, 3, NULL),
  ('sofrimento', 'Eis que bem-aventurado é o homem a quem Deus castiga; não desprezes, pois, o castigo do Todo-Poderoso.', 'Jó 5:17', 'Jó', 5, 17, NULL),
  ('sofrimento', 'E, no Hades, ergueu os olhos, estando em tormentos, e viu ao longe Abraão e Lázaro, no seu seio. E, clamando, disse: Abraão, meu pai, tem misericórdia de mim e manda a Lázaro que molhe na água a ponta do seu dedo e me refresque a língua, porque estou atormentado nesta chama.', 'Lucas 16:23-24', 'Lucas', 16, 23, 24),
  ('sofrimento', 'Mas, alcançando socorro de Deus, ainda até ao dia de hoje permaneço, dando testemunho, tanto a pequenos como a grandes, não dizendo nada mais do que o que os profetas e Moisés disseram que devia acontecer, isto é, que o Cristo devia padecer e, sendo o primeiro da ressurreição dos mortos, devia anunciar a luz a este povo e aos gentios.', 'Atos 26:22-23', 'Atos', 26, 22, 23),
  ('sofrimento', 'Pois tu, ó Deus, nos provaste; tu nos afinaste como se afina a prata.', 'Salmo 66:10', 'Salmo', 66, 10, NULL),
  ('superacao', 'Tenho-vos dito isso, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo; eu venci o mundo.', 'João 16:33', 'João', 16, 33, NULL),
  ('superacao', 'Não te deixes vencer do mal, mas vence o mal com o bem.', 'Romanos 12:21', 'Romanos', 12, 21, NULL),
  ('superacao', 'Porque para Deus nada é impossível.', 'Lucas 1:37', 'Lucas', 1, 37, NULL),
  ('superacao', 'Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.', '1 João 5:4', '1 João', 5, 4, NULL),
  ('superacao', 'Mas em todas estas coisas somos mais do que vencedores, por aquele que nos amou.', 'Romanos 8:37', 'Romanos', 8, 37, NULL),
  ('superacao', 'Mas graças a Deus, que nos dá a vitória por nosso Senhor Jesus Cristo.', '1 Coríntios 15:57', '1 Coríntios', 15, 57, NULL),
  ('superacao', 'Mas tu, Senhor', 'Salmo 3:3', 'Salmo', 3, 3, NULL),
  ('superacao', 'Portanto, nós também, pois, que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo embaraço e o pecado que tão de perto nos rodeia e corramos, com paciência, a carreira que nos está proposta.', 'Hebreus 12:1', 'Hebreus', 12, 1, NULL),
  ('superacao', 'E a luz resplandece nas trevas, e as trevas não a compreenderam.', 'João 1:5', 'João', 1, 5, NULL),
  ('superacao', 'Milita a boa milícia da fé, toma posse da vida eterna, para a qual também foste chamado, tendo já feito boa confissão diante de muitas testemunhas.', '1 Timóteo 6:12', '1 Timóteo', 6, 12, NULL),
  ('superacao', 'Filhinhos, sois de Deus e já os tendes vencido, porque maior é o que está em vós do que o que está no mundo.', '1 João 4:4', '1 João', 4, 4, NULL),
  ('superacao', 'Sede sóbrios, vigiai, porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar.', '1 Pedro 5:8', '1 Pedro', 5, 8, NULL),
  ('superacao', 'Quem é que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus?', '1 João 5:5', '1 João', 5, 5, NULL),
  ('superacao', 'Ao que vencer, lhe concederei que se assente comigo no meu trono, assim como eu venci e me assentei com meu Pai no seu trono.', 'Apocalipse 3:21', 'Apocalipse', 3, 21, NULL),
  ('superacao', 'O que vencer será vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; e confessarei o seu nome diante de meu Pai e diante dos seus anjos.', 'Apocalipse 3:5', 'Apocalipse', 3, 5, NULL),
  ('superacao', 'Oh! Salva, Senhor', 'Salmo 118:25-26', 'Salmo', 118, 25, 26),
  ('superacao', 'Alegra-te muito, ó filha de Sião; exulta, ó filha de Jerusalém; eis que o teu rei virá a ti, justo e Salvador, pobre e montado sobre um jumento, sobre um asninho, filho de jumenta.', 'Zacarias 9:9', 'Zacarias', 9, 9, NULL),
  ('tentacao', 'Não veio sobre vós tentação, senão humana; mas fiel é Deus, que vos não deixará tentar acima do que podeis; antes, com a tentação dará também o escape, para que a possais suportar.', '1 Coríntios 10:13', '1 Coríntios', 10, 13, NULL),
  ('tentacao', 'Vigiai e orai, para que não entreis em tentação; na verdade, o espírito está pronto, mas a carne é fraca.', 'Mateus 26:41', 'Mateus', 26, 41, NULL),
  ('tentacao', 'Bem-aventurado o varão que sofre a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam.', 'Tiago 1:12', 'Tiago', 1, 12, NULL),
  ('tentacao', 'Ou andará alguém sobre as brasas, sem que se queimem os seus pés?', 'Provérbios 6:28', 'Provérbios', 6, 28, NULL),
  ('tentacao', 'E dizia: O que sai do homem, isso é que contamina o homem. Porque do interior do coração dos homens saem os maus pensamentos, os adultérios, as prostituições, os homicídios, os furtos, a avareza, as maldades, o engano, a dissolução, a inveja, a blasfêmia, a soberba, a loucura. Todos estes males procedem de dentro e contaminam o homem.', 'Marcos 7:20-23', 'Marcos', 7, 20, 23),
  ('tentacao', 'Ninguém, sendo tentado, diga: De Deus sou tentado; porque Deus não pode ser tentado pelo mal e a ninguém tenta.', 'Tiago 1:13', 'Tiago', 1, 13, NULL),
  ('tentacao', 'E não nos induzas à tentação, mas livra-nos do mal; porque teu é o Reino, e o poder, e a glória, para sempre. Amém!', 'Mateus 6:13', 'Mateus', 6, 13, NULL),
  ('tentacao', 'E Jesus, cheio do Espírito Santo, voltou do Jordão e foi levado pelo Espírito ao deserto. E quarenta dias foi tentado pelo diabo, e, naqueles dias, não comeu coisa alguma, e, terminados eles, teve fome.', 'Lucas 4:1-2', 'Lucas', 4, 1, 2),
  ('tentacao', 'Senhor, diante de ti está todo o meu desejo, e o meu gemido não te é oculto.', 'Salmo 38:9', 'Salmo', 38, 9, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('tentacao', 'Sabendo que a prova da vossa fé produz a paciência.', 'Tiago 1:3', 'Tiago', 1, 3, NULL),
  ('tentacao', 'Portanto, tomai toda a armadura de Deus, para que possais resistir no dia mau e, havendo feito tudo, ficar firmes.', 'Efésios 6:13', 'Efésios', 6, 13, NULL),
  ('tentacao', 'Irmãos, se algum homem chegar a ser surpreendido nalguma ofensa, vós, que sois espirituais, encaminhai o tal com espírito de mansidão, olhando por ti mesmo, para que não sejas também tentado.', 'Gálatas 6:1', 'Gálatas', 6, 1, NULL),
  ('tentacao', 'Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; porém um que, como nós, em tudo foi tentado, mas sem pecado.', 'Hebreus 4:15', 'Hebreus', 4, 15, NULL),
  ('tentacao', 'Assim, sabe o Senhor livrar da tentação os piedosos e reservar os injustos para o Dia de Juízo, para serem castigados.', '2 Pedro 2:9', '2 Pedro', 2, 9, NULL),
  ('tentacao', 'Mas revesti-vos do Senhor Jesus Cristo e não tenhais cuidado da carne em suas concupiscências.', 'Romanos 13:14', 'Romanos', 13, 14, NULL),
  ('tentacao', 'E o que foi semeado entre espinhos é o que ouve a palavra, mas os cuidados deste mundo e a sedução das riquezas sufocam a palavra, e fica infrutífera.', 'Mateus 13:22', 'Mateus', 13, 22, NULL),
  ('tentacao', 'Foge, também, dos desejos da mocidade; e segue a justiça, a fé, o amor e a paz com os que, com um coração puro, invocam o Senhor.', '2 Timóteo 2:22', '2 Timóteo', 2, 22, NULL),
  ('tentacao', 'Pois tu, ó Deus, nos provaste; tu nos afinaste como se afina a prata.', 'Salmo 66:10', 'Salmo', 66, 10, NULL),
  ('tentacao', 'O que encobre as suas transgressões nunca prosperará; mas o que as confessa e deixa alcançará misericórdia.', 'Provérbios 28:13', 'Provérbios', 28, 13, NULL),
  ('todo-poderoso', 'Tua é, Senhor', '1 Crônicas 29:11', '1 Crônicas', 29, 11, NULL),
  ('todo-poderoso', 'Eis que eu sou o Senhor', 'Jeremias 32:27', 'Jeremias', 32, 27, NULL),
  ('todo-poderoso', 'Eu sou o Alfa e o Ômega, o Princípio e o Fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-Poderoso.', 'Apocalipse 1:8', 'Apocalipse', 1, 8, NULL),
  ('todo-poderoso', 'Porque para Deus nada é impossível.', 'Lucas 1:37', 'Lucas', 1, 37, NULL),
  ('todo-poderoso', 'Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. Direi do Senhor', 'Salmo 91:1-2', 'Salmo', 91, 1, 2),
  ('todo-poderoso', 'Ah! Senhor Jeová', 'Jeremias 32:17', 'Jeremias', 32, 17, NULL),
  ('todo-poderoso', 'Grande é o Senhor', 'Salmo 145:3', 'Salmo', 145, 3, NULL),
  ('todo-poderoso', 'Faze-nos voltar, Senhor', 'Salmo 80:19', 'Salmo', 80, 19, NULL),
  ('todo-poderoso', 'E riquezas e glória vêm de diante de ti, e tu dominas sobre tudo, e na tua mão há força e poder; e na tua mão está o engrandecer e dar força a tudo.', '1 Crônicas 29:12', '1 Crônicas', 29, 12, NULL),
  ('todo-poderoso', 'Porque estou certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir, nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus, nosso Senhor!', 'Romanos 8:38-39', 'Romanos', 8, 38, 39),
  ('todo-poderoso', 'Ora, ao Rei dos séculos, imortal, invisível, ao único Deus seja honra e glória para todo o sempre. Amém!', '1 Timóteo 1:17', '1 Timóteo', 1, 17, NULL),
  ('todo-poderoso', 'Do Senhor', 'Salmo 24:1', 'Salmo', 24, 1, NULL),
  ('todo-poderoso', 'Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder como a sua divindade, se entendem e claramente se veem pelas coisas que estão criadas, para que eles fiquem inescusáveis.', 'Romanos 1:20', 'Romanos', 1, 20, NULL),
  ('todo-poderoso', 'No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder.', 'Efésios 6:10', 'Efésios', 6, 10, NULL),
  ('todo-poderoso', 'Ele revela o profundo e o escondido e conhece o que está em trevas; e com ele mora a luz.', 'Daniel 2:22', 'Daniel', 2, 22, NULL),
  ('todo-poderoso', 'Filhinhos, sois de Deus e já os tendes vencido, porque maior é o que está em vós do que o que está no mundo.', '1 João 4:4', '1 João', 4, 4, NULL),
  ('todo-poderoso', 'Sem que haja uma palavra na minha língua, eis que, ó Senhor', 'Salmo 139:4', 'Salmo', 139, 4, NULL),
  ('todo-poderoso', 'O Senhor', '1 Samuel 2:7', '1 Samuel', 2, 7, NULL),
  ('todo-poderoso', 'E a elas e aos lugares ao redor do meu outeiro, eu porei por bênção; e farei descer a chuva a seu tempo; chuvas de bênção serão.', 'Ezequiel 34:26', 'Ezequiel', 34, 26, NULL),
  ('todo-poderoso', 'Aba, Pai, todas as coisas te são possíveis; afasta de mim este cálice; não seja, porém, o que eu quero, mas o que tu queres.', 'Marcos 14:36', 'Marcos', 14, 36, NULL),
  ('todo-poderoso', 'E disse o Senhor', 'Jó 1:12', 'Jó', 1, 12, NULL),
  ('trabalho', 'E, tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens, sabendo que recebereis do Senhor o galardão da herança, porque a Cristo, o Senhor, servis.', 'Colossenses 3:23-24', 'Colossenses', 3, 23, 24),
  ('trabalho', 'Confia ao Senhor', 'Provérbios 16:3', 'Provérbios', 16, 3, NULL),
  ('trabalho', 'Todas as vossas coisas sejam feitas com amor.', '1 Coríntios 16:14', '1 Coríntios', 16, 14, NULL),
  ('trabalho', 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.', '1 Coríntios 15:58', '1 Coríntios', 15, 58, NULL),
  ('trabalho', 'A mão dos diligentes dominará, mas os enganadores serão tributários.', 'Provérbios 12:24', 'Provérbios', 12, 24, NULL),
  ('trabalho', 'A bênção do Senhor', 'Provérbios 10:22', 'Provérbios', 10, 22, NULL),
  ('trabalho', 'E, quanto fizerdes por palavras ou por obras, fazei tudo em nome do Senhor Jesus, dando por ele graças a Deus Pai.', 'Colossenses 3:17', 'Colossenses', 3, 17, NULL),
  ('trabalho', 'Já tenho conhecido que não há coisa melhor para eles do que se alegrarem e fazerem bem na sua vida; e também que todo homem coma e beba e goze do bem de todo o seu trabalho. Isso é um dom de Deus.', 'Eclesiastes 3:12-13', 'Eclesiastes', 3, 12, 13),
  ('trabalho', 'A fazenda que procede da vaidade diminuirá, mas quem a ajunta pelo trabalho terá aumento.', 'Provérbios 13:11', 'Provérbios', 13, 11, NULL),
  ('trabalho', 'E Deus é poderoso para tornar abundante em vós toda graça, a fim de que, tendo sempre, em tudo, toda suficiência, superabundeis em toda boa obra.', '2 Coríntios 9:8', '2 Coríntios', 9, 8, NULL),
  ('trabalho', 'E seja sobre nós a graça do Senhor, nosso Deus; e confirma sobre nós a obra das nossas mãos; sim, confirma a obra das nossas mãos.', 'Salmo 90:17', 'Salmo', 90, 17, NULL),
  ('trabalho', 'Olhai por vós mesmos, para que não percamos o que temos ganhado; antes, recebamos o inteiro galardão.', '2 João 1:8', '2 João', 1, 8, NULL),
  ('trabalho', 'Melhor é serem dois do que um, porque têm melhor paga do seu trabalho.', 'Eclesiastes 4:9', 'Eclesiastes', 4, 9, NULL),
  ('trabalho', 'Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade.', '2 Timóteo 2:15', '2 Timóteo', 2, 15, NULL),
  ('trabalho', 'E quanto ao homem, a quem Deus deu riquezas e fazenda e lhe deu poder para delas comer, e tomar a sua porção, e gozar do seu trabalho, isso é dom de Deus.', 'Eclesiastes 5:19', 'Eclesiastes', 5, 19, NULL),
  ('trabalho', 'Olhai para as aves do céu, que não semeiam, nem segam, nem ajuntam em celeiros; e vosso Pai celestial as alimenta. Não tendes vós muito mais valor do que elas?', 'Mateus 6:26', 'Mateus', 6, 26, NULL),
  ('trabalho', 'E qual é aquele que vos fará mal, se fordes zelosos do bem?', '1 Pedro 3:13', '1 Pedro', 3, 13, NULL),
  ('trabalho', 'Eis aqui o que eu vi, uma boa e bela coisa: comer, e beber, e gozar cada um do bem de todo o seu trabalho, em que trabalhou debaixo do sol, todos os dias da sua vida que Deus lhe deu; porque esta é a sua porção.', 'Eclesiastes 5:18', 'Eclesiastes', 5, 18, NULL),
  ('trabalho', 'Porque Deus não é injusto para se esquecer da vossa obra e do trabalho de amor que, para com o seu nome, mostrastes, enquanto servistes aos santos e ainda servis.', 'Hebreus 6:10', 'Hebreus', 6, 10, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('trabalho', 'Também vi eu que todo trabalho e toda destreza em obras trazem ao homem a inveja do seu próximo. Também isso é vaidade e aflição de espírito.', 'Eclesiastes 4:4', 'Eclesiastes', 4, 4, NULL),
  ('trabalho', 'Mas em nada tenho a minha vida por preciosa, contanto que cumpra com alegria a minha carreira e o ministério que recebi do Senhor Jesus, para dar testemunho do evangelho da graça de Deus.', 'Atos 20:24', 'Atos', 20, 24, NULL),
  ('trabalho', 'Toda Escritura divinamente inspirada é proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça, para que o homem de Deus seja perfeito e perfeitamente instruído para toda boa obra.', '2 Timóteo 3:16-17', '2 Timóteo', 3, 16, 17),
  ('trabalho', 'Na verdade, na verdade vos digo que aquele que crê em mim também fará as obras que eu faço e as fará maiores do que estas, porque eu vou para meu Pai.', 'João 14:12', 'João', 14, 12, NULL),
  ('trabalho', 'Portanto, resta ainda um repouso para o povo de Deus. Porque aquele que entrou no seu repouso, ele próprio repousou de suas obras, como Deus das suas.', 'Hebreus 4:9-10', 'Hebreus', 4, 9, 10),
  ('trabalho', 'Exorta os servos a que se sujeitem a seu senhor e em tudo agradem, não contradizendo, não defraudando; antes, mostrando toda a boa lealdade, para que, em tudo, sejam ornamento da doutrina de Deus, nosso Salvador.', 'Tito 2:9-10', 'Tito', 2, 9, 10),
  ('trabalho', 'Se o Senhor', 'Salmo 127:1', 'Salmo', 127, 1, NULL),
  ('transformacao', 'Mas todos nós, com cara descoberta, refletindo, como um espelho, a glória do Senhor, somos transformados de glória em glória, na mesma imagem, como pelo Espírito do Senhor.', '2 Coríntios 3:18', '2 Coríntios', 3, 18, NULL),
  ('transformacao', 'E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.', 'Romanos 12:2', 'Romanos', 12, 2, NULL),
  ('transformacao', 'Ora, o Senhor encaminhe o vosso coração no amor de Deus e na paciência de Cristo.', '2 Tessalonicenses 3:5', '2 Tessalonicenses', 3, 5, NULL),
  ('transformacao', 'Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança. Contra essas coisas não há lei.', 'Gálatas 5:22-23', 'Gálatas', 5, 22, 23),
  ('transformacao', 'Mortificai, pois, os vossos membros que estão sobre a terra: a prostituição, a impureza, o apetite desordenado, a vil concupiscência e a avareza, que é idolatria.', 'Colossenses 3:5', 'Colossenses', 3, 5, NULL),
  ('transformacao', 'Rogo-vos, porém, irmãos, pelo nome de nosso Senhor Jesus Cristo, que digais todos uma mesma coisa e que não haja entre vós dissensões; antes, sejais unidos, em um mesmo sentido e em um mesmo parecer.', '1 Coríntios 1:10', '1 Coríntios', 1, 10, NULL),
  ('transformacao', 'Mas aquele que beber da água que eu lhe der nunca terá sede, porque a água que eu lhe der se fará nele uma fonte de água a jorrar para a vida eterna.', 'João 4:14', 'João', 4, 14, NULL),
  ('transformacao', 'E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor', 'Joel 2:13', 'Joel', 2, 13, NULL),
  ('transformacao', 'Arrependei-vos, pois, e convertei-vos, para que sejam apagados os vossos pecados, e venham, assim, os tempos do refrigério pela presença do Senhor.', 'Atos 3:19', 'Atos', 3, 19, NULL),
  ('transformacao', 'Não mintais uns aos outros, pois que já vos despistes do velho homem com os seus feitos e vos vestistes do novo, que se renova para o conhecimento, segundo a imagem daquele que o criou.', 'Colossenses 3:9-10', 'Colossenses', 3, 9, 10),
  ('transformacao', 'Porque Cristo, estando nós ainda fracos, morreu a seu tempo pelos ímpios.', 'Romanos 5:6', 'Romanos', 5, 6, NULL),
  ('transformacao', 'Desde então, começou Jesus a pregar e a dizer: Arrependei-vos, porque é chegado o Reino dos céus.', 'Mateus 4:17', 'Mateus', 4, 17, NULL),
  ('transformacao', 'E disse-lhes Pedro: Arrependei-vos, e cada um de vós seja batizado em nome de Jesus Cristo para perdão dos pecados, e recebereis o dom do Espírito Santo.', 'Atos 2:38', 'Atos', 2, 38, NULL),
  ('tristeza', 'Os justos clamam, e o Senhor', 'Salmo 34:17-18', 'Salmo', 34, 17, 18),
  ('tristeza', 'O Senhor', 'Deuteronômio 31:8', 'Deuteronômio', 31, 8, NULL),
  ('tristeza', 'Bem-aventurados os que choram, porque eles serão consolados.', 'Mateus 5:4', 'Mateus', 5, 4, NULL),
  ('tristeza', 'Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.', '1 Pedro 5:7', '1 Pedro', 5, 7, NULL),
  ('tristeza', 'Porque, na muita sabedoria, há muito enfado; e o que aumenta em ciência aumenta em trabalho.', 'Eclesiastes 1:18', 'Eclesiastes', 1, 18, NULL),
  ('tristeza', 'Porque a sua ira dura só um momento; no seu favor está a vida; o choro pode durar uma noite, mas a alegria vem pela manhã.', 'Salmo 30:5', 'Salmo', 30, 5, NULL),
  ('tristeza', 'Senhor, diante de ti está todo o meu desejo, e o meu gemido não te é oculto.', 'Salmo 38:9', 'Salmo', 38, 9, NULL),
  ('tristeza', 'Como contristados, mas sempre alegres; como pobres, mas enriquecendo a muitos; como nada tendo e possuindo tudo.', '2 Coríntios 6:10', '2 Coríntios', 6, 10, NULL),
  ('tristeza', 'E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles e será o seu Deus. E Deus limpará de seus olhos toda lágrima, e não haverá mais morte, nem pranto, nem clamor, nem dor, porque já as primeiras coisas são passadas.', 'Apocalipse 21:3-4', 'Apocalipse', 21, 3, 4),
  ('tristeza', 'Afasta, pois, a ira do teu coração e remove da tua carne o mal, porque a adolescência e a juventude são vaidade.', 'Eclesiastes 11:10', 'Eclesiastes', 11, 10, NULL),
  ('tristeza', 'Nunca mais terão fome, nunca mais terão sede; nem sol nem calma alguma cairá sobre eles, porque o Cordeiro que está no meio do trono os apascentará e lhes servirá de guia para as fontes das águas da vida; e Deus limpará de seus olhos toda lágrima.', 'Apocalipse 7:16-17', 'Apocalipse', 7, 16, 17),
  ('tristeza', 'Alegrai-vos com os que se alegram e chorai com os que choram.', 'Romanos 12:15', 'Romanos', 12, 15, NULL),
  ('tristeza', 'Ouve, Senhor', 'Salmo 39:12', 'Salmo', 39, 12, NULL),
  ('tristeza', 'Ainda assim, agora mesmo diz o Senhor', 'Joel 2:12', 'Joel', 2, 12, NULL),
  ('tristeza', 'Então, Jó se levantou, e rasgou o seu manto, e rapou a sua cabeça, e se lançou em terra, e adorou, e disse: Nu saí do ventre de minha mãe e nu tornarei para lá; o Senhor', 'Jó 1:20-21', 'Jó', 1, 20, 21),
  ('tristeza', 'Porque a tristeza segundo Deus opera arrependimento para a salvação, da qual ninguém se arrepende; mas a tristeza do mundo opera a morte.', '2 Coríntios 7:10', '2 Coríntios', 7, 10, NULL),
  ('tristeza', 'O Senhor', 'Salmo 146:8', 'Salmo', 146, 8, NULL),
  ('tristeza', 'O filho sábio alegra a seu pai, mas o filho louco é a tristeza de sua mãe.', 'Provérbios 10:1', 'Provérbios', 10, 1, NULL),
  ('tristeza', 'Volta e dize a Ezequias, chefe do meu povo: Assim diz o Senhor', '2 Reis 20:5', '2 Reis', 20, 5, NULL),
  ('tristeza', 'E não entristeçais o Espírito Santo de Deus, no qual estais selados para o Dia da redenção.', 'Efésios 4:30', 'Efésios', 4, 30, NULL),
  ('tristeza', 'A vide se secou, a figueira se murchou; a romeira também, e a palmeira, e a macieira; todas as árvores do campo se secaram, e a alegria se secou entre os filhos dos homens.', 'Joel 1:12', 'Joel', 1, 12, NULL),
  ('tristeza', 'Um abismo chama outro abismo, ao ruído das tuas catadupas; todas as tuas ondas e vagas têm passado sobre mim.', 'Salmo 42:7', 'Salmo', 42, 7, NULL),
  ('valioso', 'Enquanto foste precioso aos meus olhos, também foste glorificado, e eu te amei, pelo que dei os homens por ti, e os povos, pela tua alma.', 'Isaías 43:4', 'Isaías', 43, 4, NULL),
  ('valioso', 'Mulher virtuosa, quem a achará? O seu valor muito excede o de rubins.', 'Provérbios 31:10', 'Provérbios', 31, 10, NULL),
  ('valioso', 'Levanta-te, resplandece, porque já vem a tua luz, e a glória do Senhor', 'Isaías 60:1', 'Isaías', 60, 1, NULL),
  ('valioso', 'Não te desamparem a benignidade e a fidelidade; ata-as ao teu pescoço; escreve-as na tábua do teu coração e acharás graça e bom entendimento aos olhos de Deus e dos homens.', 'Provérbios 3:3-4', 'Provérbios', 3, 3, 4),
  ('valioso', 'Olhai para as aves do céu, que não semeiam, nem segam, nem ajuntam em celeiros; e vosso Pai celestial as alimenta. Não tendes vós muito mais valor do que elas?', 'Mateus 6:26', 'Mateus', 6, 26, NULL),
  ('valioso', 'Não se vendem dois passarinhos por um ceitil? E nenhum deles cairá em terra sem a vontade de vosso Pai. E até mesmo os cabelos da vossa cabeça estão todos contados. Não temais, pois; mais valeis vós do que muitos passarinhos.', 'Mateus 10:29-31', 'Mateus', 10, 29, 31),
  ('valioso', 'Mas em nada tenho a minha vida por preciosa, contanto que cumpra com alegria a minha carreira e o ministério que recebi do Senhor Jesus, para dar testemunho do evangelho da graça de Deus.', 'Atos 20:24', 'Atos', 20, 24, NULL),
  ('valioso', 'Não se vendem cinco passarinhos por dois ceitis? E nenhum deles está esquecido diante de Deus. E até os cabelos da vossa cabeça estão todos contados. Não temais, pois; mais valeis vós do que muitos passarinhos.', 'Lucas 12:6-7', 'Lucas', 12, 6, 7);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('valioso', 'Pois quanto mais vale um homem do que uma ovelha? É, por consequência, lícito fazer bem nos sábados.', 'Mateus 12:12', 'Mateus', 12, 12, NULL),
  ('valioso', 'Agora, pois, se diligentemente ouvirdes a minha voz e guardardes o meu concerto, então, sereis a minha propriedade peculiar dentre todos os povos; porque toda a terra é minha.', 'Êxodo 19:5', 'Êxodo', 19, 5, NULL),
  ('valioso', 'Prata escolhida é a língua do justo; o coração dos ímpios é de nenhum preço.', 'Provérbios 10:20', 'Provérbios', 10, 20, NULL),
  ('valioso', 'Porque, em Jesus Cristo, nem a circuncisão nem a incircuncisão têm virtude alguma, mas, sim, a fé que opera por amor.', 'Gálatas 5:6', 'Gálatas', 5, 6, NULL),
  ('valioso', 'Considerai os corvos, que nem semeiam, nem segam, nem têm despensa nem celeiro, e Deus os alimenta; quanto mais valeis vós do que as aves?', 'Lucas 12:24', 'Lucas', 12, 24, NULL),
  ('verdade', 'Aquele que anda em sinceridade, e pratica a justiça, e fala verazmente segundo o seu coração; aquele que não difama com a sua língua, nem faz mal ao seu próximo, nem aceita nenhuma afronta contra o seu próximo.', 'Salmo 15:2-3', 'Salmo', 15, 2, 3),
  ('verdade', 'Não tenho maior gozo do que este: o de ouvir que os meus filhos andam na verdade.', '3 João 1:4', '3 João', 1, 4, NULL),
  ('verdade', 'Meus filhinhos, não amemos de palavra, nem de língua, mas por obra e em verdade.', '1 João 3:18', '1 João', 3, 18, NULL),
  ('verdade', 'Jesus dizia, pois, aos judeus que criam nele: Se vós permanecerdes na minha palavra, verdadeiramente, sereis meus discípulos e conhecereis a verdade, e a verdade vos libertará.', 'João 8:31-32', 'João', 8, 31, 32),
  ('verdade', 'Se dissermos que temos comunhão com ele e andarmos em trevas, mentimos e não praticamos a verdade.', '1 João 1:6', '1 João', 1, 6, NULL),
  ('verdade', 'Disse-lhe Jesus: Eu sou o caminho, e a verdade, e a vida. Ninguém vem ao Pai senão por mim.', 'João 14:6', 'João', 14, 6, NULL),
  ('verdade', 'Quanto ao mais, irmãos, tudo o que é verdadeiro, tudo o que é honesto, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se há alguma virtude, e se há algum louvor, nisso pensai.', 'Filipenses 4:8', 'Filipenses', 4, 8, NULL),
  ('verdade', 'Antes, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo.', 'Efésios 4:15', 'Efésios', 4, 15, NULL),
  ('verdade', 'Guia-me na tua verdade e ensina-me, pois tu és o Deus da minha salvação; por ti estou esperando todo o dia.', 'Salmo 25:5', 'Salmo', 25, 5, NULL),
  ('verdade', 'Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade.', '2 Timóteo 2:15', '2 Timóteo', 2, 15, NULL),
  ('verdade', 'Os lábios do justo sabem o que agrada, mas a boca dos ímpios anda cheia de perversidades.', 'Provérbios 10:32', 'Provérbios', 10, 32, NULL),
  ('verdade', 'Guarda a tua língua do mal e os teus lábios, de falarem enganosamente.', 'Salmo 34:13', 'Salmo', 34, 13, NULL),
  ('verdade', 'Ora, a fé é o firme fundamento das coisas que se esperam e a prova das coisas que se não veem.', 'Hebreus 11:1', 'Hebreus', 11, 1, NULL),
  ('verdade', 'Toda palavra de Deus é pura; escudo é para os que confiam nele.', 'Provérbios 30:5', 'Provérbios', 30, 5, NULL),
  ('verdade', 'Escolhi o caminho da verdade; propus-me seguir os teus juízos.', 'Salmo 119:30', 'Salmo', 119, 30, NULL),
  ('verdade', 'Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade.', 'João 4:24', 'João', 4, 24, NULL),
  ('verdade', 'Mas nada há encoberto que não haja de ser descoberto; nem oculto, que não haja de ser sabido.', 'Lucas 12:2', 'Lucas', 12, 2, NULL),
  ('verdade', 'Os lábios mentirosos são abomináveis ao Senhor', 'Provérbios 12:22', 'Provérbios', 12, 22, NULL),
  ('verdade', 'Mas, sobretudo, meus irmãos, não jureis nem pelo céu nem pela terra, nem façais qualquer outro juramento; mas que a vossa palavra seja sim, sim e não, não, para que não caiais em condenação.', 'Tiago 5:12', 'Tiago', 5, 12, NULL),
  ('verdade', 'Não folga com a injustiça, mas folga com a verdade; tudo sofre, tudo crê, tudo espera, tudo suporta.', '1 Coríntios 13:6-7', '1 Coríntios', 13, 6, 7),
  ('verdade', 'E sabemos que já o Filho de Deus é vindo e nos deu entendimento para conhecermos o que é verdadeiro; e no que é verdadeiro estamos, isto é, em seu Filho Jesus Cristo. Este é o verdadeiro Deus e a vida eterna.', '1 João 5:20', '1 João', 5, 20, NULL),
  ('verdade', 'E a unção que vós recebestes dele fica em vós, e não tendes necessidade de que alguém vos ensine; mas, como a sua unção vos ensina todas as coisas, e é verdadeira, e não é mentira, como ela vos ensinou, assim nele permanecereis.', '1 João 2:27', '1 João', 2, 27, NULL),
  ('verdade', 'Segundo a sua vontade, ele nos gerou pela palavra da verdade, para que fôssemos como primícias das suas criaturas.', 'Tiago 1:18', 'Tiago', 1, 18, NULL),
  ('verdade', 'Desvia de ti a tortuosidade da boca e alonga de ti a perversidade dos lábios.', 'Provérbios 4:24', 'Provérbios', 4, 24, NULL),
  ('verdade', 'Porque a palavra do Senhor', 'Salmo 33:4', 'Salmo', 33, 4, NULL),
  ('verdade', 'E o Verbo se fez carne e habitou entre nós, e vimos a sua glória, como a glória do Unigênito do Pai, cheio de graça e de verdade.', 'João 1:14', 'João', 1, 14, NULL),
  ('verdade', 'Mas, quando vier o Consolador, que eu da parte do Pai vos hei de enviar, aquele Espírito da verdade, que procede do Pai, testificará de mim.', 'João 15:26', 'João', 15, 26, NULL),
  ('verdade', 'Ensina-me, Senhor', 'Salmo 86:11', 'Salmo', 86, 11, NULL),
  ('verdade', 'A testemunha verdadeira não mentirá, mas a testemunha falsa se desboca em mentiras.', 'Provérbios 14:5', 'Provérbios', 14, 5, NULL),
  ('verdade', 'Vós tendes por pai ao diabo e quereis satisfazer os desejos de vosso pai; ele foi homicida desde o princípio e não se firmou na verdade, porque não há verdade nele; quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira.', 'João 8:44', 'João', 8, 44, NULL),
  ('verdade', 'Porque o fruto do Espírito está em toda bondade, e justiça, e verdade.', 'Efésios 5:9', 'Efésios', 5, 9, NULL),
  ('verdade', 'Todavia, digo-vos a verdade: que vos convém que eu vá, porque, se eu não for, o Consolador não virá a vós; mas, se eu for, enviar-vo-lo-ei.', 'João 16:7', 'João', 16, 7, NULL),
  ('verdade', 'Mas quem pratica a verdade vem para a luz, a fim de que as suas obras sejam manifestas, porque são feitas em Deus.', 'João 3:21', 'João', 3, 21, NULL),
  ('verdade', 'E se disseres no teu coração: Como conheceremos a palavra que o Senhor', 'Deuteronômio 18:21-22', 'Deuteronômio', 18, 21, 22),
  ('verdade', 'Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestida a couraça da justiça, e calçados os pés na preparação do evangelho da paz; tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno.', 'Efésios 6:14-16', 'Efésios', 6, 14, 16),
  ('vicio', 'Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas eu não me deixarei dominar por nenhuma.', '1 Coríntios 6:12', '1 Coríntios', 6, 12, NULL),
  ('vicio', 'Não veio sobre vós tentação, senão humana; mas fiel é Deus, que vos não deixará tentar acima do que podeis; antes, com a tentação dará também o escape, para que a possais suportar.', '1 Coríntios 10:13', '1 Coríntios', 10, 13, NULL),
  ('vicio', 'Vigiai e orai, para que não entreis em tentação; na verdade, o espírito está pronto, mas a carne é fraca.', 'Mateus 26:41', 'Mateus', 26, 41, NULL),
  ('vicio', 'Estai, pois, firmes na liberdade com que Cristo nos libertou e não torneis a meter-vos debaixo do jugo da servidão.', 'Gálatas 5:1', 'Gálatas', 5, 1, NULL),
  ('vicio', 'Sujeitai-vos, pois, a Deus; resisti ao diabo, e ele fugirá de vós.', 'Tiago 4:7', 'Tiago', 4, 7, NULL),
  ('vicio', 'Porque, se fomos plantados juntamente com ele na semelhança da sua morte, também o seremos na da sua ressurreição; sabendo isto: que o nosso velho homem foi com ele crucificado, para que o corpo do pecado seja desfeito, a fim de que não sirvamos mais ao pecado.', 'Romanos 6:5-6', 'Romanos', 6, 5, 6),
  ('vicio', 'Porque tudo o que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a soberba da vida, não é do Pai, mas do mundo.', '1 João 2:16', '1 João', 2, 16, NULL),
  ('vicio', 'Porque a graça de Deus se há manifestado, trazendo salvação a todos os homens, ensinando-nos que, renunciando à impiedade e às concupiscências mundanas, vivamos neste presente século sóbria, justa e piamente.', 'Tito 2:11-12', 'Tito', 2, 11, 12),
  ('vicio', 'Respondeu-lhes Jesus: Em verdade, em verdade vos digo que todo aquele que comete pecado é servo do pecado.', 'João 8:34', 'João', 8, 34, NULL),
  ('vicio', 'Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos? Porque fostes comprados por bom preço; glorificai, pois, a Deus no vosso corpo e no vosso espírito, os quais pertencem a Deus.', '1 Coríntios 6:19-20', '1 Coríntios', 6, 19, 20);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('vicio', 'Sabendo que a prova da vossa fé produz a paciência.', 'Tiago 1:3', 'Tiago', 1, 3, NULL),
  ('vicio', 'E não nos induzas à tentação, mas livra-nos do mal; porque teu é o Reino, e o poder, e a glória, para sempre. Amém!', 'Mateus 6:13', 'Mateus', 6, 13, NULL),
  ('vicio', 'Se, pois, o Filho vos libertar, verdadeiramente, sereis livres.', 'João 8:36', 'João', 8, 36, NULL),
  ('vicio', 'Vós sois o sal da terra; e, se o sal for insípido, com que se há de salgar? Para nada mais presta, senão para se lançar fora e ser pisado pelos homens.', 'Mateus 5:13', 'Mateus', 5, 13, NULL),
  ('vicio', 'Jesus dizia, pois, aos judeus que criam nele: Se vós permanecerdes na minha palavra, verdadeiramente, sereis meus discípulos e conhecereis a verdade, e a verdade vos libertará.', 'João 8:31-32', 'João', 8, 31, 32),
  ('vicio', 'Mas revesti-vos do Senhor Jesus Cristo e não tenhais cuidado da carne em suas concupiscências.', 'Romanos 13:14', 'Romanos', 13, 14, NULL),
  ('vida', 'O Senhor', 'Salmo 121:7-8', 'Salmo', 121, 7, 8),
  ('vida', 'Portanto, vede prudentemente como andais, não como néscios, mas como sábios, remindo o tempo, porquanto os dias são maus.', 'Efésios 5:15-16', 'Efésios', 5, 15, 16),
  ('vida', 'Como na água o rosto corresponde ao rosto, assim o coração do homem ao homem.', 'Provérbios 27:19', 'Provérbios', 27, 19, NULL),
  ('vida', 'Porque andamos por fé e não por vista.', '2 Coríntios 5:7', '2 Coríntios', 5, 7, NULL),
  ('vida', 'E, tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens, sabendo que recebereis do Senhor o galardão da herança, porque a Cristo, o Senhor, servis.', 'Colossenses 3:23-24', 'Colossenses', 3, 23, 24),
  ('vida', 'O que segue a justiça e a bondade achará a vida, a justiça e a honra.', 'Provérbios 21:21', 'Provérbios', 21, 21, NULL),
  ('vida', 'Pois que aproveitaria ao homem ganhar todo o mundo e perder a sua alma?', 'Marcos 8:36', 'Marcos', 8, 36, NULL),
  ('vida', 'A minha carne e o meu coração desfalecem; mas Deus é a fortaleza do meu coração e a minha porção para sempre.', 'Salmo 73:26', 'Salmo', 73, 26, NULL),
  ('vida', 'Porque quem quer amar a vida e ver os dias bons, refreie a sua língua do mal, e os seus lábios não falem engano; aparte-se do mal e faça o bem; busque a paz e siga-a.', '1 Pedro 3:10-11', '1 Pedro', 3, 10, 11),
  ('vida', 'Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu.', 'Eclesiastes 3:1', 'Eclesiastes', 3, 1, NULL),
  ('vida', 'Porque tu és a minha rocha e a minha fortaleza; pelo que, por amor do teu nome, guia-me e encaminha-me.', 'Salmo 31:3', 'Salmo', 31, 3, NULL),
  ('vida', 'Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as saídas da vida.', 'Provérbios 4:23', 'Provérbios', 4, 23, NULL),
  ('vida', 'Faze-me saber os teus caminhos, Senhor', 'Salmo 25:4', 'Salmo', 25, 4, NULL),
  ('vida', 'E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável e perfeita vontade de Deus.', 'Romanos 12:2', 'Romanos', 12, 2, NULL),
  ('vida', 'E Jesus lhes disse: Eu sou o pão da vida; aquele que vem a mim não terá fome; e quem crê em mim nunca terá sede.', 'João 6:35', 'João', 6, 35, NULL),
  ('vida', 'Descansa no Senhor', 'Salmo 37:7', 'Salmo', 37, 7, NULL),
  ('vida', 'Certamente que a bondade e a misericórdia me seguirão todos os dias da minha vida; e habitarei na Casa do Senhor', 'Salmo 23:6', 'Salmo', 23, 6, NULL),
  ('vida', 'O que guarda a sua boca conserva a sua alma, mas o que muito abre os lábios tem perturbação.', 'Provérbios 13:3', 'Provérbios', 13, 3, NULL),
  ('vida', 'Porquanto te ordeno, hoje, que ames o Senhor', 'Deuteronômio 30:16', 'Deuteronômio', 30, 16, NULL),
  ('vida', 'No dia da prosperidade, goza do bem, mas, no dia da adversidade, considera; porque também Deus fez este em oposição àquele, para que o homem nada ache que tenha de vir depois dele.', 'Eclesiastes 7:14', 'Eclesiastes', 7, 14, NULL),
  ('vida', 'Nunca digas: Por que foram os dias passados melhores do que estes? Porque nunca com sabedoria isso perguntarias.', 'Eclesiastes 7:10', 'Eclesiastes', 7, 10, NULL),
  ('vida', 'Quem crê em mim, como diz a Escritura, rios de água viva correrão do seu ventre.', 'João 7:38', 'João', 7, 38, NULL),
  ('vida', 'O caminho para a vida é daquele que guarda a correção, mas o que abandona a repreensão erra.', 'Provérbios 10:17', 'Provérbios', 10, 17, NULL),
  ('vida', 'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne vivo-a na fé do Filho de Deus, o qual me amou e se entregou a si mesmo por mim.', 'Gálatas 2:20', 'Gálatas', 2, 20, NULL),
  ('vida', 'Segui a paz com todos e a santificação, sem a qual ninguém verá o Senhor.', 'Hebreus 12:14', 'Hebreus', 12, 14, NULL),
  ('vida', 'Entrega o teu caminho ao Senhor', 'Salmo 37:5-6', 'Salmo', 37, 5, 6),
  ('vida', 'Quem dentre vós é sábio e inteligente? Mostre, pelo seu bom trato, as suas obras em mansidão de sabedoria.', 'Tiago 3:13', 'Tiago', 3, 13, NULL),
  ('vida', 'Não vos inquieteis, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal.', 'Mateus 6:34', 'Mateus', 6, 34, NULL),
  ('vida', 'O que adquire entendimento ama a sua alma; o que conserva a inteligência achará o bem.', 'Provérbios 19:8', 'Provérbios', 19, 8, NULL),
  ('vida', 'Porque aquele que quiser salvar a sua vida perdê-la-á, e quem perder a sua vida por amor de mim achá-la-á.', 'Mateus 16:25', 'Mateus', 16, 25, NULL),
  ('vida', 'Ninguém despreze a tua mocidade; mas sê o exemplo dos fiéis, na palavra, no trato, no amor, no espírito, na fé, na pureza.', '1 Timóteo 4:12', '1 Timóteo', 4, 12, NULL),
  ('vida', 'Fazei todas as coisas sem murmurações nem contendas; para que sejais irrepreensíveis e sinceros, filhos de Deus inculpáveis no meio duma geração corrompida e perversa, entre a qual resplandeceis como astros no mundo; retendo a palavra da vida.', 'Filipenses 2:14-16a', 'Filipenses 2:14-16a', NULL, NULL, NULL),
  ('vida', 'Este é o dia que fez o Senhor', 'Salmo 118:24', 'Salmo', 118, 24, NULL),
  ('vida', 'Eis que Deus é o meu ajudador; o Senhor', 'Salmo 54:4', 'Salmo', 54, 4, NULL),
  ('vida', 'Quem achar a sua vida perdê-la-á; e quem perder a sua vida por amor de mim achá-la-á.', 'Mateus 10:39', 'Mateus', 10, 39, NULL),
  ('vida', 'Porque sabemos que, se a nossa casa terrestre deste tabernáculo se desfizer, temos de Deus um edifício, uma casa não feita por mãos, eterna, nos céus.', '2 Coríntios 5:1', '2 Coríntios', 5, 1, NULL),
  ('vida', 'Enganoso é o coração, mais do que todas as coisas, e perverso; quem o conhecerá? Eu, o Senhor', 'Jeremias 17:9-10', 'Jeremias', 17, 9, 10),
  ('vida', 'Filho meu, não te esqueças da minha lei, e o teu coração guarde os meus mandamentos. Porque eles aumentarão os teus dias e te acrescentarão anos de vida e paz.', 'Provérbios 3:1-2', 'Provérbios', 3, 1, 2),
  ('vida', 'Tudo fez formoso em seu tempo; também pôs o mundo no coração deles, sem que o homem possa descobrir a obra que Deus fez desde o princípio até ao fim.', 'Eclesiastes 3:11', 'Eclesiastes', 3, 11, NULL),
  ('vida', 'Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas eu não me deixarei dominar por nenhuma.', '1 Coríntios 6:12', '1 Coríntios', 6, 12, NULL),
  ('vida', 'Porque para mim o viver é Cristo, e o morrer é ganho.', 'Filipenses 1:21', 'Filipenses', 1, 21, NULL),
  ('vida', 'Nisto se manifestou o amor de Deus para conosco: que Deus enviou seu Filho unigênito ao mundo, para que por ele vivamos.', '1 João 4:9', '1 João', 4, 9, NULL),
  ('vida', 'Pondera a vereda de teus pés, e todos os teus caminhos sejam bem-ordenados!', 'Provérbios 4:26', 'Provérbios', 4, 26, NULL),
  ('vida', 'Porque a tua benignidade é melhor do que a vida; os meus lábios te louvarão. Assim, eu te bendirei enquanto viver; em teu nome levantarei as minhas mãos.', 'Salmo 63:3-4', 'Salmo', 63, 3, 4);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('vida', 'Disse-lhe Jesus: Eu sou o caminho, e a verdade, e a vida. Ninguém vem ao Pai senão por mim.', 'João 14:6', 'João', 14, 6, NULL),
  ('vida', 'Far-me-ás ver a vereda da vida; na tua presença há abundância de alegrias; à tua mão direita há delícias perpetuamente.', 'Salmo 16:11', 'Salmo', 16, 11, NULL),
  ('vida', 'Se vivemos no Espírito, andemos também no Espírito.', 'Gálatas 5:25', 'Gálatas', 5, 25, NULL),
  ('vida', 'Por isso, vos digo: não andeis cuidadosos quanto à vossa vida, pelo que haveis de comer ou pelo que haveis de beber; nem quanto ao vosso corpo, pelo que haveis de vestir. Não é a vida mais do que o mantimento, e o corpo, mais do que a vestimenta?', 'Mateus 6:25', 'Mateus', 6, 25, NULL),
  ('vida', 'A esperança demorada enfraquece o coração, mas o desejo chegado é árvore de vida.', 'Provérbios 13:12', 'Provérbios', 13, 12, NULL),
  ('vida', 'Bem-aventurado o varão que sofre a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam.', 'Tiago 1:12', 'Tiago', 1, 12, NULL),
  ('vida', 'Vós sois a luz do mundo; não se pode esconder uma cidade edificada sobre um monte.', 'Mateus 5:14', 'Mateus', 5, 14, NULL),
  ('vida', 'Mas ele disse: Antes, bem-aventurados os que ouvem a palavra de Deus e a guardam.', 'Lucas 11:28', 'Lucas', 11, 28, NULL),
  ('vida', 'Porque, se vivemos, para o Senhor vivemos; se morremos, para o Senhor morremos. De sorte que, ou vivamos ou morramos, somos do Senhor.', 'Romanos 14:8', 'Romanos', 14, 8, NULL),
  ('vida', 'Já tenho conhecido que não há coisa melhor para eles do que se alegrarem e fazerem bem na sua vida; e também que todo homem coma e beba e goze do bem de todo o seu trabalho. Isso é um dom de Deus.', 'Eclesiastes 3:12-13', 'Eclesiastes', 3, 12, 13),
  ('vida', 'Nunca me esquecerei dos teus preceitos, pois por eles me tens vivificado.', 'Salmo 119:93', 'Salmo', 119, 93, NULL),
  ('vida', 'Porque, assim como todos morrem em Adão, assim também todos serão vivificados em Cristo.', '1 Coríntios 15:22', '1 Coríntios', 15, 22, NULL),
  ('vida', 'Se for possível, quanto estiver em vós, tende paz com todos os homens.', 'Romanos 12:18', 'Romanos', 12, 18, NULL),
  ('vida', 'O ladrão não vem senão a roubar, a matar e a destruir; eu vim para que tenham vida e a tenham com abundância.', 'João 10:10', 'João', 10, 10, NULL),
  ('vida', 'Porque a inclinação da carne é morte; mas a inclinação do Espírito é vida e paz.', 'Romanos 8:6', 'Romanos', 8, 6, NULL),
  ('vida', 'Há caminho que ao homem parece direito, mas o fim dele são os caminhos da morte.', 'Provérbios 14:12', 'Provérbios', 14, 12, NULL),
  ('vida', 'Qualquer que confessar que Jesus é o Filho de Deus, Deus está nele e ele em Deus.', '1 João 4:15', '1 João', 4, 15, NULL),
  ('vida', 'Portanto, quer comais, quer bebais ou façais outra qualquer coisa, fazei tudo para a glória de Deus.', '1 Coríntios 10:31', '1 Coríntios', 10, 31, NULL),
  ('vida', 'Estai, pois, firmes na liberdade com que Cristo nos libertou e não torneis a meter-vos debaixo do jugo da servidão.', 'Gálatas 5:1', 'Gálatas', 5, 1, NULL),
  ('vida', 'Quanto ao mais, irmãos, regozijai-vos, sede perfeitos, sede consolados, sede de um mesmo parecer, vivei em paz; e o Deus de amor e de paz será convosco.', '2 Coríntios 13:11', '2 Coríntios', 13, 11, NULL),
  ('vida', 'Assim também a fé, se não tiver as obras, é morta em si mesma.', 'Tiago 2:17', 'Tiago', 2, 17, NULL),
  ('vida', 'Quem anda em sinceridade anda seguro, mas o que perverte os seus caminhos será conhecido.', 'Provérbios 10:9', 'Provérbios', 10, 9, NULL),
  ('vida', 'Sei estar abatido e sei também ter abundância; em toda a maneira e em todas as coisas, estou instruído, tanto a ter fartura como a ter fome, tanto a ter abundância como a padecer necessidade.', 'Filipenses 4:12', 'Filipenses', 4, 12, NULL),
  ('vida', 'Pois que aproveita ao homem ganhar o mundo inteiro, se perder a sua alma? Ou que dará o homem em recompensa da sua alma?', 'Mateus 16:26', 'Mateus', 16, 26, NULL),
  ('vida', 'Falou-lhes, pois, Jesus outra vez, dizendo: Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.', 'João 8:12', 'João', 8, 12, NULL),
  ('vida', 'Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos? Porque fostes comprados por bom preço; glorificai, pois, a Deus no vosso corpo e no vosso espírito, os quais pertencem a Deus.', '1 Coríntios 6:19-20', '1 Coríntios', 6, 19, 20),
  ('vida', 'Todavia, para nós há um só Deus, o Pai, de quem é tudo e para quem nós vivemos; e um só Senhor, Jesus Cristo, pelo qual são todas as coisas, e nós por ele.', '1 Coríntios 8:6', '1 Coríntios', 8, 6, NULL),
  ('vida', 'Lembra-te do teu Criador nos dias da tua mocidade, antes que venham os maus dias, e cheguem os anos dos quais venhas a dizer: Não tenho neles contentamento.', 'Eclesiastes 12:1', 'Eclesiastes', 12, 1, NULL),
  ('vida', 'Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida.', '1 João 5:12', '1 João', 5, 12, NULL),
  ('vida', 'Porque, andando na carne, não militamos segundo a carne.', '2 Coríntios 10:3', '2 Coríntios', 10, 3, NULL),
  ('vida', 'Não estejais apreensivos pela vossa vida, sobre o que comereis, nem pelo corpo, sobre o que vestireis. Mais é a vida do que o sustento, e o corpo, mais do que as vestes.', 'Lucas 12:22b-23', 'Lucas 12:22b-23', NULL, NULL, NULL),
  ('vida', 'Toda Escritura divinamente inspirada é proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça, para que o homem de Deus seja perfeito e perfeitamente instruído para toda boa obra.', '2 Timóteo 3:16-17', '2 Timóteo', 3, 16, 17),
  ('vida', 'Porque nele vivemos, e nos movemos, e existimos, como também alguns dos vossos poetas disseram: Pois somos também sua geração.', 'Atos 17:28', 'Atos', 17, 28, NULL),
  ('vida', 'E, se o Espírito daquele que dos mortos ressuscitou a Jesus habita em vós, aquele que dos mortos ressuscitou a Cristo também vivificará o vosso corpo mortal, pelo seu Espírito que em vós habita.', 'Romanos 8:11', 'Romanos', 8, 11, NULL),
  ('vida', 'Porque assim diz o Alto e o Sublime, que habita na eternidade e cujo nome é Santo: Em um alto e santo lugar habito e também com o contrito e abatido de espírito, para vivificar o espírito dos abatidos e para vivificar o coração dos contritos.', 'Isaías 57:15', 'Isaías', 57, 15, NULL),
  ('vida', 'Ensina-me, Senhor', 'Salmo 86:11', 'Salmo', 86, 11, NULL),
  ('vida', 'Porque assim diz o Senhor', 'Amós 5:4', 'Amós', 5, 4, NULL),
  ('vida', 'Eu repreendo e castigo a todos quantos amo; sê, pois, zeloso e arrepende-te.', 'Apocalipse 3:19', 'Apocalipse', 3, 19, NULL),
  ('vida', 'Ouve, filho meu, e aceita as minhas palavras, e se te multiplicarão os anos de vida.', 'Provérbios 4:10', 'Provérbios', 4, 10, NULL),
  ('vida', 'O Senhor', 'Salmo 34:22', 'Salmo', 34, 22, NULL),
  ('vida', 'Do Senhor', 'Salmo 24:1', 'Salmo', 24, 1, NULL),
  ('vida', 'E ser-me-eis santos, porque eu, o Senhor', 'Levítico 20:26', 'Levítico', 20, 26, NULL),
  ('vida', 'Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez.', 'João 1:3', 'João', 1, 3, NULL),
  ('vida', 'Mas de ambos os lados estou em aperto, tendo desejo de partir e estar com Cristo, porque isto é ainda muito melhor. Mas julgo mais necessário, por amor de vós, ficar na carne.', 'Filipenses 1:23-24', 'Filipenses', 1, 23, 24),
  ('vida', 'Vós bem intentastes mal contra mim, porém Deus o tornou em bem, para fazer como se vê neste dia, para conservar em vida a um povo grande.', 'Gênesis 50:20', 'Gênesis', 50, 20, NULL),
  ('vida', 'Então, disse o Senhor', 'Gênesis 3:22-23', 'Gênesis', 3, 22, 23),
  ('vida', 'De tudo o que se tem ouvido, o fim é: Teme a Deus e guarda os seus mandamentos; porque este é o dever de todo homem.', 'Eclesiastes 12:13', 'Eclesiastes', 12, 13, NULL),
  ('vida', 'Bem-aventurados os que trilham caminhos retos e andam na lei do Senhor', 'Salmo 119:1', 'Salmo', 119, 1, NULL),
  ('vida', 'Portanto, nós também, pois, que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo embaraço e o pecado que tão de perto nos rodeia e corramos, com paciência, a carreira que nos está proposta.', 'Hebreus 12:1', 'Hebreus', 12, 1, NULL),
  ('vida', 'Segundo a sua vontade, ele nos gerou pela palavra da verdade, para que fôssemos como primícias das suas criaturas.', 'Tiago 1:18', 'Tiago', 1, 18, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('vida', 'Porque o amor de Cristo nos constrange, julgando nós assim: que, se um morreu por todos, logo, todos morreram. E ele morreu por todos, para que os que vivem não vivam mais para si, mas para aquele que por eles morreu e ressuscitou.', '2 Coríntios 5:14-15', '2 Coríntios', 5, 14, 15),
  ('vida', 'Porque, noutro tempo, éreis trevas, mas, agora, sois luz no Senhor; andai como filhos da luz.', 'Efésios 5:8', 'Efésios', 5, 8, NULL),
  ('vida', 'Produzi, pois, frutos dignos de arrependimento.', 'Mateus 3:8', 'Mateus', 3, 8, NULL),
  ('vida', 'Visto como o seu divino poder nos deu tudo o que diz respeito à vida e piedade, pelo conhecimento daquele que nos chamou por sua glória e virtude.', '2 Pedro 1:3', '2 Pedro', 1, 3, NULL),
  ('vida', 'Porque qualquer que quiser salvar a sua vida perdê-la-á; mas qualquer que, por amor de mim, perder a sua vida a salvará.', 'Lucas 9:24', 'Lucas', 9, 24, NULL),
  ('vida', 'Eis que a sua alma se incha, não é reta nele; mas o justo, pela sua fé, viverá.', 'Habacuque 2:4', 'Habacuque', 2, 4, NULL),
  ('vida', 'Porque nos tornamos participantes de Cristo, se retivermos firmemente o princípio da nossa confiança até ao fim.', 'Hebreus 3:14', 'Hebreus', 3, 14, NULL),
  ('vida', 'O que vencer será vestido de vestes brancas, e de maneira nenhuma riscarei o seu nome do livro da vida; e confessarei o seu nome diante de meu Pai e diante dos seus anjos.', 'Apocalipse 3:5', 'Apocalipse', 3, 5, NULL),
  ('vida', 'Porque o exercício corporal para pouco aproveita, mas a piedade para tudo é proveitosa, tendo a promessa da vida presente e da que há de vir.', '1 Timóteo 4:8', '1 Timóteo', 4, 8, NULL),
  ('vida', 'Mas, como é santo aquele que vos chamou, sede vós também santos em toda a vossa maneira de viver, porquanto escrito está: Sede santos, porque eu sou santo.', '1 Pedro 1:15-16', '1 Pedro', 1, 15, 16),
  ('vida', 'Vai, pois, come com alegria o teu pão e bebe com bom coração o teu vinho, pois já Deus se agrada das tuas obras.', 'Eclesiastes 9:7', 'Eclesiastes', 9, 7, NULL),
  ('vida', 'Porque mil anos são aos teus olhos como o dia de ontem que passou, e como a vigília da noite.', 'Salmo 90:4', 'Salmo', 90, 4, NULL),
  ('vida', 'Mas em nada tenho a minha vida por preciosa, contanto que cumpra com alegria a minha carreira e o ministério que recebi do Senhor Jesus, para dar testemunho do evangelho da graça de Deus.', 'Atos 20:24', 'Atos', 20, 24, NULL),
  ('vida', 'Sabendo que não foi com coisas corruptíveis, como prata ou ouro, que fostes resgatados da vossa vã maneira de viver que, por tradição, recebestes dos vossos pais, mas com o precioso sangue de Cristo, como de um cordeiro imaculado e incontaminado.', '1 Pedro 1:18-19', '1 Pedro', 1, 18, 19),
  ('vida', 'Que diremos, pois? Permaneceremos no pecado, para que a graça seja mais abundante? De modo nenhum! Nós que estamos mortos para o pecado, como viveremos ainda nele?', 'Romanos 6:1-2', 'Romanos', 6, 1, 2),
  ('vida', 'Porque qualquer que quiser salvar a sua vida perdê-la-á, mas qualquer que perder a sua vida por amor de mim e do evangelho, esse a salvará.', 'Marcos 8:35', 'Marcos', 8, 35, NULL),
  ('vida', 'Assim como o Pai, que vive, me enviou, e eu vivo pelo Pai, assim quem de mim se alimenta também viverá por mim.', 'João 6:57', 'João', 6, 57, NULL),
  ('vida', 'Deixe o ímpio o seu caminho, e o homem maligno, os seus pensamentos e se converta ao Senhor', 'Isaías 55:7', 'Isaías', 55, 7, NULL),
  ('vida', 'Eis aqui o que eu vi, uma boa e bela coisa: comer, e beber, e gozar cada um do bem de todo o seu trabalho, em que trabalhou debaixo do sol, todos os dias da sua vida que Deus lhe deu; porque esta é a sua porção.', 'Eclesiastes 5:18', 'Eclesiastes', 5, 18, NULL),
  ('vida', 'Como livres e não tendo a liberdade por cobertura da malícia, mas como servos de Deus.', '1 Pedro 2:16', '1 Pedro', 2, 16, NULL),
  ('vida', 'Cantarei ao Senhor', 'Salmo 104:33', 'Salmo', 104, 33, NULL),
  ('vida', 'E também todos os que piamente querem viver em Cristo Jesus padecerão perseguições.', '2 Timóteo 3:12', '2 Timóteo', 3, 12, NULL),
  ('vida', 'E guardarás os seus estatutos e os seus mandamentos, que te ordeno hoje, para que bem te vá a ti e a teus filhos depois de ti e para que prolongues os dias na terra que o Senhor', 'Deuteronômio 4:40', 'Deuteronômio', 4, 40, NULL),
  ('vida', 'E disse Deus: Façamos o homem à nossa imagem, conforme a nossa semelhança; e domine sobre os peixes do mar, e sobre as aves dos céus, e sobre o gado, e sobre toda a terra, e sobre todo réptil que se move sobre a terra.', 'Gênesis 1:26', 'Gênesis', 1, 26, NULL),
  ('vida', 'E disse Deus: Eis que vos tenho dado toda erva que dá semente e que está sobre a face de toda a terra e toda árvore em que há fruto de árvore que dá semente; ser-vos-ão para mantimento.', 'Gênesis 1:29', 'Gênesis', 1, 29, NULL),
  ('vida', 'Considerai os corvos, que nem semeiam, nem segam, nem têm despensa nem celeiro, e Deus os alimenta; quanto mais valeis vós do que as aves?', 'Lucas 12:24', 'Lucas', 12, 24, NULL),
  ('vida', 'E te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conheceste, nem teus pais o conheceram, para te dar a entender que o homem não viverá só de pão, mas que de tudo o que sai da boca do Senhor', 'Deuteronômio 8:3', 'Deuteronômio', 8, 3, NULL),
  ('vida', 'Esquadrinhemos os nossos caminhos, experimentemo-los e voltemos para o Senhor', 'Lamentações 3:40', 'Lamentações', 3, 40, NULL),
  ('vida', 'Não mintais uns aos outros, pois que já vos despistes do velho homem com os seus feitos e vos vestistes do novo, que se renova para o conhecimento, segundo a imagem daquele que o criou.', 'Colossenses 3:9-10', 'Colossenses', 3, 9, 10),
  ('vida', 'Mas quem pratica a verdade vem para a luz, a fim de que as suas obras sejam manifestas, porque são feitas em Deus.', 'João 3:21', 'João', 3, 21, NULL),
  ('vida', 'Porque os que são segundo a carne inclinam-se para as coisas da carne; mas os que são segundo o Espírito, para as coisas do Espírito.', 'Romanos 8:5', 'Romanos', 8, 5, NULL),
  ('vida', 'Desejaria eu, de qualquer maneira, a morte do ímpio? Diz o Senhor Jeová', 'Ezequiel 18:23', 'Ezequiel', 18, 23, NULL),
  ('vida', 'Eu sou o bom Pastor; o bom Pastor dá a sua vida pelas ovelhas.', 'João 10:11', 'João', 10, 11, NULL),
  ('vida', 'Todos os caminhos do homem são limpos aos seus olhos, mas o Senhor', 'Provérbios 16:2', 'Provérbios', 16, 2, NULL),
  ('vida-eterna', 'E dou-lhes a vida eterna, e nunca hão de perecer, e ninguém as arrebatará das minhas mãos. Meu Pai, que mas deu, é maior do que todos; e ninguém pode arrebatá-las das mãos de meu Pai. Eu e o Pai somos um.', 'João 10:28-30', 'João', 10, 28, 30),
  ('vida-eterna', 'Porque o que me achar achará a vida e alcançará favor do Senhor', 'Provérbios 8:35', 'Provérbios', 8, 35, NULL),
  ('vida-eterna', 'E o mundo passa, e a sua concupiscência; mas aquele que faz a vontade de Deus permanece para sempre.', '1 João 2:17', '1 João', 2, 17, NULL),
  ('vida-eterna', 'E o testemunho é este: que Deus nos deu a vida eterna; e esta vida está em seu Filho.', '1 João 5:11', '1 João', 5, 11, NULL),
  ('vida-eterna', 'E o Deus de toda a graça, que em Cristo Jesus vos chamou à sua eterna glória, depois de haverdes padecido um pouco, ele mesmo vos aperfeiçoará, confirmará, fortificará e fortalecerá.', '1 Pedro 5:10', '1 Pedro', 5, 10, NULL),
  ('vida-eterna', 'Não atentando nós nas coisas que se veem, mas nas que se não veem; porque as que se veem são temporais, e as que se não veem são eternas.', '2 Coríntios 4:18', '2 Coríntios', 4, 18, NULL),
  ('vida-eterna', 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.', 'João 3:16', 'João', 3, 16, NULL),
  ('vida-eterna', 'Porque a nossa leve e momentânea tribulação produz para nós um peso eterno de glória mui excelente.', '2 Coríntios 4:17', '2 Coríntios', 4, 17, NULL),
  ('vida-eterna', 'Estas coisas vos escrevi, para que saibais que tendes a vida eterna e para que creiais no nome do Filho de Deus.', '1 João 5:13', '1 João', 5, 13, NULL),
  ('vida-eterna', 'Sonda-me, ó Deus, e conhece o meu coração; prova-me e conhece os meus pensamentos. E vê se há em mim algum caminho mau e guia-me pelo caminho eterno.', 'Salmo 139:23-24', 'Salmo', 139, 23, 24),
  ('vida-eterna', 'E a vida eterna é esta: que conheçam a ti só por único Deus verdadeiro e a Jesus Cristo, a quem enviaste.', 'João 17:3', 'João', 17, 3, NULL),
  ('vida-eterna', 'E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles e será o seu Deus. E Deus limpará de seus olhos toda lágrima, e não haverá mais morte, nem pranto, nem clamor, nem dor, porque já as primeiras coisas são passadas.', 'Apocalipse 21:3-4', 'Apocalipse', 21, 3, 4),
  ('vida-eterna', 'Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus, nosso Senhor.', 'Romanos 6:23', 'Romanos', 6, 23, NULL),
  ('vida-eterna', 'Aquele que crê no Filho tem a vida eterna, mas aquele que não crê no Filho não verá a vida, mas a ira de Deus sobre ele permanece.', 'João 3:36', 'João', 3, 36, NULL),
  ('vida-eterna', 'Entrai pela porta estreita, porque larga é a porta, e espaçoso, o caminho que conduz à perdição, e muitos são os que entram por ela; E porque estreita é a porta, e apertado, o caminho que leva à vida, e poucos há que a encontrem.', 'Mateus 7:13-14', 'Mateus', 7, 13, 14),
  ('vida-eterna', 'Milita a boa milícia da fé, toma posse da vida eterna, para a qual também foste chamado, tendo já feito boa confissão diante de muitas testemunhas.', '1 Timóteo 6:12', '1 Timóteo', 6, 12, NULL);


INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('vida-eterna', 'Porque para mim tenho por certo que as aflições deste tempo presente não são para comparar com a glória que em nós há de ser revelada.', 'Romanos 8:18', 'Romanos', 8, 18, NULL),
  ('vida-eterna', 'Mas aquele que beber da água que eu lhe der nunca terá sede, porque a água que eu lhe der se fará nele uma fonte de água a jorrar para a vida eterna.', 'João 4:14', 'João', 4, 14, NULL),
  ('vida-eterna', 'Nunca mais terão fome, nunca mais terão sede; nem sol nem calma alguma cairá sobre eles, porque o Cordeiro que está no meio do trono os apascentará e lhes servirá de guia para as fontes das águas da vida; e Deus limpará de seus olhos toda lágrima.', 'Apocalipse 7:16-17', 'Apocalipse', 7, 16, 17),
  ('vida-eterna', 'Quem achar a sua vida perdê-la-á; e quem perder a sua vida por amor de mim achá-la-á.', 'Mateus 10:39', 'Mateus', 10, 39, NULL),
  ('vida-eterna', 'Porque o que semeia na sua carne da carne ceifará a corrupção; mas o que semeia no Espírito do Espírito ceifará a vida eterna.', 'Gálatas 6:8', 'Gálatas', 6, 8, NULL),
  ('vida-eterna', 'Eu sou o Alfa e o Ômega, o Princípio e o Fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-Poderoso.', 'Apocalipse 1:8', 'Apocalipse', 1, 8, NULL),
  ('vida-eterna', 'Palavra fiel é esta: que, se morrermos com ele, também com ele viveremos.', '2 Timóteo 2:11', '2 Timóteo', 2, 11, NULL),
  ('vida-eterna', 'Portanto, pode também salvar perfeitamente os que por ele se chegam a Deus, vivendo sempre para interceder por eles.', 'Hebreus 7:25', 'Hebreus', 7, 25, NULL),
  ('vida-eterna', 'Mas, por isso, alcancei misericórdia, para que em mim, que sou o principal, Jesus Cristo mostrasse toda a sua longanimidade, para exemplo dos que haviam de crer nele para a vida eterna.', '1 Timóteo 1:16', '1 Timóteo', 1, 16, NULL),
  ('vida-eterna', 'Trabalhai não pela comida que perece, mas pela comida que permanece para a vida eterna, a qual o Filho do Homem vos dará, porque a este o Pai, Deus, o selou.', 'João 6:27', 'João', 6, 27, NULL),
  ('vida-eterna', 'Para que, assim como o pecado reinou na morte, também a graça reinasse pela justiça para a vida eterna, por Jesus Cristo, nosso Senhor.', 'Romanos 5:21', 'Romanos', 5, 21, NULL),
  ('vida-eterna', 'Combati o bom combate, acabei a carreira, guardei a fé. Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele Dia; e não somente a mim, mas também a todos os que amarem a sua vinda.', '2 Timóteo 4:7-8', '2 Timóteo', 4, 7, 8),
  ('vida-eterna', 'Porque não tomo prazer na morte do que morre, diz o Senhor Jeová', 'Ezequiel 18:32', 'Ezequiel', 18, 32, NULL),
  ('vida-eterna', 'Porque o Senhor', 'Salmo 37:28', 'Salmo', 37, 28, NULL),
  ('vida-eterna', 'Porque sabemos que, se a nossa casa terrestre deste tabernáculo se desfizer, temos de Deus um edifício, uma casa não feita por mãos, eterna, nos céus.', '2 Coríntios 5:1', '2 Coríntios', 5, 1, NULL),
  ('vida-eterna', 'E Jesus, respondendo, disse: Em verdade vos digo que ninguém há, que tenha deixado casa, ou irmãos, ou irmãs, ou pai, ou mãe, ou mulher, ou filhos, ou campos, por amor de mim e do evangelho, que não receba cem vezes tanto, já neste tempo, em casas, e irmãos, e irmãs, e mães, e filhos, e campos, com perseguições, e, no século futuro, a vida eterna.', 'Marcos 10:29-30', 'Marcos', 10, 29, 30),
  ('vida-eterna', 'Mas não vos alegreis porque se vos sujeitem os espíritos; alegrai-vos, antes, por estar o vosso nome escrito nos céus.', 'Lucas 10:20', 'Lucas', 10, 20, NULL),
  ('vida-eterna', 'O que guardar o mandamento guardará a sua alma; mas o que desprezar os seus caminhos morrerá.', 'Provérbios 19:16', 'Provérbios', 19, 16, NULL),
  ('vida-eterna', 'Eu te exaltarei, ó Deus, Rei meu, e bendirei o teu nome pelos séculos dos séculos.', 'Salmo 145:1', 'Salmo', 145, 1, NULL),
  ('vida-eterna', 'E sabemos que já o Filho de Deus é vindo e nos deu entendimento para conhecermos o que é verdadeiro; e no que é verdadeiro estamos, isto é, em seu Filho Jesus Cristo. Este é o verdadeiro Deus e a vida eterna.', '1 João 5:20', '1 João', 5, 20, NULL),
  ('vida-eterna', 'E todo aquele que luta de tudo se abstém; eles o fazem para alcançar uma coroa corruptível, nós, porém, uma incorruptível.', '1 Coríntios 9:25', '1 Coríntios', 9, 25, NULL),
  ('vida-eterna', 'Mas vós, amados, edificando-vos a vós mesmos sobre a vossa santíssima fé, orando no Espírito Santo, conservai a vós mesmos no amor de Deus, esperando a misericórdia de nosso Senhor Jesus Cristo, para a vida eterna.', 'Judas 1:20-21', 'Judas', 1, 20, 21),
  ('vida-eterna', 'Então, disse o Senhor', 'Gênesis 3:22-23', 'Gênesis', 3, 22, 23),
  ('vida-eterna', 'Mas, agora, libertados do pecado e feitos servos de Deus, tendes o vosso fruto para santificação, e por fim a vida eterna.', 'Romanos 6:22', 'Romanos', 6, 22, NULL),
  ('vida-eterna', 'E, sendo ele consumado, veio a ser a causa de eterna salvação para todos os que lhe obedecem.', 'Hebreus 5:9', 'Hebreus', 5, 9, NULL),
  ('vida-eterna', 'E, se qualquer disser alguma palavra contra o Filho do Homem, ser-lhe-á perdoado, mas, se alguém falar contra o Espírito Santo, não lhe será perdoado, nem neste século nem no futuro.', 'Mateus 12:32', 'Mateus', 12, 32, NULL),
  ('vida-eterna', 'A saber: a vida eterna aos que, com perseverança em fazer bem, procuram glória, e honra, e incorrupção.', 'Romanos 2:7', 'Romanos', 2, 7, NULL),
  ('vinho', 'Vai, pois, come com alegria o teu pão e bebe com bom coração o teu vinho, pois já Deus se agrada das tuas obras.', 'Eclesiastes 9:7', 'Eclesiastes', 9, 7, NULL),
  ('vinho', 'Eu sou a videira, vós, as varas; quem está em mim, e eu nele, este dá muito fruto, porque sem mim nada podereis fazer.', 'João 15:5', 'João', 15, 5, NULL),
  ('vinho', 'Semelhantemente, tomou o cálice, depois da ceia, dizendo: Este cálice é o Novo Testamento no meu sangue, que é derramado por vós.', 'Lucas 22:20', 'Lucas', 22, 20, NULL),
  ('vinho', 'Porquanto, ainda que a figueira não floresça, nem haja fruto na vide; o produto da oliveira minta, e os campos não produzam mantimento; as ovelhas da malhada sejam arrebatadas, e nos currais não haja vacas, todavia, eu me alegrarei no Senhor', 'Habacuque 3:17-18', 'Habacuque', 3, 17, 18),
  ('vinho', 'E, quando Jesus tomou o vinagre, disse: Está consumado. E, inclinando a cabeça, entregou o espírito.', 'João 19:30', 'João', 19, 30, NULL),
  ('vinho', 'E, tomando o cálice e dando graças, deu-lho, dizendo: Bebei dele todos. Porque isto é o meu sangue, o sangue do Novo Testamento, que é derramado por muitos, para remissão dos pecados.', 'Mateus 26:27-28', 'Mateus', 26, 27, 28),
  ('vinho', 'Manjar desejável não comi, nem carne nem vinho entraram na minha boca, nem me ungi com unguento, até que se cumpriram as três semanas.', 'Daniel 10:3', 'Daniel', 10, 3, NULL),
  ('vinho', 'A vide se secou, a figueira se murchou; a romeira também, e a palmeira, e a macieira; todas as árvores do campo se secaram, e a alegria se secou entre os filhos dos homens.', 'Joel 1:12', 'Joel', 1, 12, NULL),
  ('vuivas', 'Honra as viúvas que verdadeiramente são viúvas.', '1 Timóteo 5:3', '1 Timóteo', 5, 3, NULL),
  ('vuivas', 'A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e guardar-se da corrupção do mundo.', 'Tiago 1:27', 'Tiago', 1, 27, NULL),
  ('vuivas', 'A nenhuma viúva nem órfão afligireis. Se de alguma maneira os afligirdes, e eles clamarem a mim, eu certamente ouvirei o seu clamor, e a minha ira se acenderá, e vos matarei à espada; e vossas mulheres ficarão viúvas, e vossos filhos, órfãos.', 'Êxodo 22:22-24', 'Êxodo', 22, 22, 24),
  ('vuivas', 'Cantai a Deus, cantai louvores ao seu nome; louvai aquele que vai sobre os céus, pois o seu nome é Jeová', 'Salmo 68:4-5', 'Salmo', 68, 4, 5),
  ('vuivas', 'Aprendei a fazer o bem; praticai o que é reto; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas.', 'Isaías 1:17', 'Isaías', 1, 17, NULL),
  ('vuivas', 'Assim falou o Senhor', 'Zacarias 7:9-10', 'Zacarias', 7, 9, 10),
  ('vuivas', 'O Senhor', 'Salmo 146:9', 'Salmo', 146, 9, NULL),
  ('vuivas', 'Porque eu livrava o miserável, que clamava, como também o órfão que não tinha quem o socorresse. A bênção do que ia perecendo vinha sobre mim, e eu fazia que rejubilasse o coração da viúva.', 'Jó 29:12-13', 'Jó', 29, 12, 13),
  ('vuivas', 'Abre a tua boca, julga retamente e faze justiça aos pobres e aos necessitados.', 'Provérbios 31:9', 'Provérbios', 31, 9, NULL),
  ('vuivas', 'Mas, se deveras melhorardes os vossos caminhos e as vossas obras, se deveras fizerdes juízo entre um homem e entre o seu companheiro, se não oprimirdes o estrangeiro, e o órfão, e a viúva, nem derramardes sangue inocente neste lugar, nem andardes após outros deuses para vosso próprio mal, eu vos farei habitar neste lugar, na terra que dei a vossos pais, de século em século.', 'Jeremias 7:5-7', 'Jeremias', 7, 5, 7),
  ('vizinho', 'E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo. Não há outro mandamento maior do que estes.', 'Marcos 12:31', 'Marcos', 12, 31, NULL),
  ('vizinho', 'E, finalmente, sede todos de um mesmo sentimento, compassivos, amando os irmãos, entranhavelmente misericordiosos e afáveis.', '1 Pedro 3:8', '1 Pedro', 3, 8, NULL),
  ('vizinho', 'Ninguém busque o proveito próprio; antes, cada um, o que é de outrem.', '1 Coríntios 10:24', '1 Coríntios', 10, 24, NULL),
  ('vizinho', 'Pelo que exortai-vos uns aos outros e edificai-vos uns aos outros, como também o fazeis.', '1 Tessalonicenses 5:11', '1 Tessalonicenses', 5, 11, NULL),
  ('vizinho', 'Levai as cargas uns dos outros e assim cumprireis a lei de Cristo.', 'Gálatas 6:2', 'Gálatas', 6, 2, NULL);

