-- Parte 14: versículos (1 blocos INSERT).
-- Execute bible-verses-by-theme.sql e 00-truncate-themes.sql antes.
INSERT INTO bible_verses_by_theme (theme_slug, texto, referencia, livro, capitulo, versiculo, versiculo_fim) VALUES
  ('vizinho', 'Permaneça o amor fraternal. Não vos esqueçais da hospitalidade, porque, por ela, alguns, não o sabendo, hospedaram anjos.', 'Hebreus 13:1-2', 'Hebreus', 13, 1, 2),
  ('vizinho', 'Porque toda a lei se cumpre numa só palavra, nesta: Amarás o teu próximo como a ti mesmo.', 'Gálatas 5:14', 'Gálatas', 5, 14, NULL),
  ('vizinho', 'Portanto, tudo o que vós quereis que os homens vos façam, fazei-lho também vós, porque esta é a lei e os profetas.', 'Mateus 7:12', 'Mateus', 7, 12, NULL),
  ('vizinho', 'Nada façais por contenda ou por vanglória, mas por humildade; cada um considere os outros superiores a si mesmo.', 'Filipenses 2:3', 'Filipenses', 2, 3, NULL),
  ('vizinho', 'Portanto, cada um de nós agrade ao seu próximo no que é bom para edificação.', 'Romanos 15:2', 'Romanos', 15, 2, NULL),
  ('vizinho', 'Então, enquanto temos tempo, façamos o bem a todos, mas principalmente aos domésticos da fé.', 'Gálatas 6:10', 'Gálatas', 6, 10, NULL),
  ('vizinho', 'Assim que não nos julguemos mais uns aos outros; antes, seja o vosso propósito não pôr tropeço ou escândalo ao irmão.', 'Romanos 14:13', 'Romanos', 14, 13, NULL),
  ('vizinho', 'Suportando-vos uns aos outros e perdoando-vos uns aos outros, se algum tiver queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também.', 'Colossenses 3:13', 'Colossenses', 3, 13, NULL),
  ('vizinho', 'Um novo mandamento vos dou: Que vos ameis uns aos outros; como eu vos amei a vós, que também vós uns aos outros vos ameis.', 'João 13:34', 'João', 13, 34, NULL),
  ('vizinho', 'Aprendei a fazer o bem; praticai o que é reto; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas.', 'Isaías 1:17', 'Isaías', 1, 17, NULL),
  ('vizinho', 'O amor não faz mal ao próximo; de sorte que o cumprimento da lei é o amor.', 'Romanos 13:10', 'Romanos', 13, 10, NULL),
  ('vizinho', 'Portanto, és inescusável quando julgas, ó homem, quem quer que sejas, porque te condenas a ti mesmo naquilo em que julgas a outro; pois tu, que julgas, fazes o mesmo.', 'Romanos 2:1', 'Romanos', 2, 1, NULL),
  ('vizinho', 'E o Senhor vos aumente e faça crescer em amor uns para com os outros e para com todos, como também nós para convosco.', '1 Tessalonicenses 3:12', '1 Tessalonicenses', 3, 12, NULL),
  ('vizinho', 'Mas, sobretudo, tende ardente amor uns para com os outros, porque o amor cobrirá a multidão de pecados.', '1 Pedro 4:8', '1 Pedro', 4, 8, NULL),
  ('vizinho', 'Com efeito: Não adulterarás, não matarás, não furtarás, não darás falso testemunho, não cobiçarás, e, se há algum outro mandamento, tudo nesta palavra se resume: Amarás ao teu próximo como a ti mesmo.', 'Romanos 13:9', 'Romanos', 13, 9, NULL),
  ('vizinho', 'Ao que está aflito devia o amigo mostrar compaixão, ainda ao que deixasse o temor do Todo-Poderoso.', 'Jó 6:14', 'Jó', 6, 14, NULL),
  ('vizinho', 'Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros.', 'Romanos 12:10', 'Romanos', 12, 10, NULL),
  ('vizinho', 'Porque esta é a mensagem que ouvistes desde o princípio: que nos amemos uns aos outros.', '1 João 3:11', '1 João', 3, 11, NULL),
  ('vizinho', 'Um faz diferença entre dia e dia, mas outro julga iguais todos os dias. Cada um esteja inteiramente seguro em seu próprio ânimo.', 'Romanos 14:5', 'Romanos', 14, 5, NULL),
  ('vizinho', 'A religião pura e imaculada para com Deus, o Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e guardar-se da corrupção do mundo.', 'Tiago 1:27', 'Tiago', 1, 27, NULL),
  ('vizinho', 'Quem, pois, tiver bens do mundo e, vendo o seu irmão necessitado, lhe cerrar o seu coração, como estará nele o amor de Deus?', '1 João 3:17', '1 João', 3, 17, NULL),
  ('vizinho', 'Assim falou o Senhor dos Exércitos, dizendo: Executai juízo verdadeiro, mostrai piedade e misericórdia cada um a seu irmão; e não oprimais a viúva, nem o órfão, nem o estrangeiro, nem o pobre, nem intente o mal cada um contra o seu irmão, no seu coração.', 'Zacarias 7:9-10', 'Zacarias', 7, 9, 10),
  ('vizinho', 'Amados, amemo-nos uns aos outros, porque o amor é de Deus; e qualquer que ama é nascido de Deus e conhece a Deus.', '1 João 4:7', '1 João', 4, 7, NULL),
  ('vizinho', 'E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo.', 'Mateus 22:39', 'Mateus', 22, 39, NULL),
  ('vizinho', 'Porque, se um cair, o outro levanta o seu companheiro; mas ai do que estiver só; pois, caindo, não haverá outro que o levante.', 'Eclesiastes 4:10', 'Eclesiastes', 4, 10, NULL),
  ('vizinho', 'Conhecemos o amor nisto: que ele deu a sua vida por nós, e nós devemos dar a vida pelos irmãos.', '1 João 3:16', '1 João', 3, 16, NULL),
  ('vizinho', 'Não abandones o teu amigo, nem o amigo de teu pai, nem entres na casa de teu irmão no dia da tua adversidade; melhor é o vizinho perto do que o irmão longe.', 'Provérbios 27:10', 'Provérbios', 27, 10, NULL),
  ('vizinho', 'Se for possível, quanto estiver em vós, tende paz com todos os homens.', 'Romanos 12:18', 'Romanos', 12, 18, NULL),
  ('vizinho', 'Portanto, recebei-vos uns aos outros, como também Cristo nos recebeu para glória de Deus.', 'Romanos 15:7', 'Romanos', 15, 7, NULL),
  ('vizinho', 'Sede, pois, misericordiosos, como também vosso Pai é misericordioso.', 'Lucas 6:36', 'Lucas', 6, 36, NULL),
  ('vizinho', 'E vós também, pondo nisto mesmo toda a diligência, acrescentai à vossa fé a virtude, e à virtude, a ciência, e à ciência, a temperança, e à temperança, a paciência, e à paciência, a piedade, e à piedade, a fraternidade, e à fraternidade, o amor.', '2 Pedro 1:5-7', '2 Pedro', 1, 5, 7),
  ('vizinho', 'Ninguém jamais viu a Deus; se nós amamos uns aos outros, Deus está em nós, e em nós é perfeito o seu amor.', '1 João 4:12', '1 João', 4, 12, NULL),
  ('vizinho', 'Porventura, não é este o jejum que escolhi: que soltes as ligaduras da impiedade, que desfaças as ataduras do jugo, e que deixes livres os quebrantados, e que despedaces todo o jugo?', 'Isaías 58:6', 'Isaías', 58, 6, NULL),
  ('vizinho', 'Então, Pedro, aproximando-se dele, disse: Senhor, até quantas vezes pecará meu irmão contra mim, e eu lhe perdoarei? Até sete? Jesus lhe disse: Não te digo que até sete, mas até setenta vezes sete.', 'Mateus 18:21-22', 'Mateus', 18, 21, 22),
  ('vizinho', 'Levanta-te, Senhor! Ó Deus, levanta a tua mão; não te esqueças dos necessitados!', 'Salmo 10:12', 'Salmo', 10, 12, NULL),
  ('vizinho', 'Não cobiçarás a casa do teu próximo; não cobiçarás a mulher do teu próximo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma do teu próximo.', 'Êxodo 20:17', 'Êxodo', 20, 17, NULL),
  ('vizinho', 'Defendei o pobre e o órfão; fazei justiça ao aflito e necessitado.', 'Salmo 82:3', 'Salmo', 82, 3, NULL),
  ('vizinho', 'Vede, irmãos, que nunca haja em qualquer de vós um coração mau e infiel, para se apartar do Deus vivo.', 'Hebreus 3:12', 'Hebreus', 3, 12, NULL),
  ('vizinho', 'Ora, se eu, Senhor e Mestre, vos lavei os pés, vós deveis também lavar os pés uns aos outros.', 'João 13:14', 'João', 13, 14, NULL),
  ('vizinho', 'E, respondendo ele, disse-lhes: Quem tiver duas túnicas, que reparta com o que não tem, e quem tiver alimentos, que faça da mesma maneira.', 'Lucas 3:11', 'Lucas', 3, 11, NULL),
  ('vizinho', 'Honra as viúvas que verdadeiramente são viúvas.', '1 Timóteo 5:3', '1 Timóteo', 5, 3, NULL),
  ('vizinho', 'Também vi eu que todo trabalho e toda destreza em obras trazem ao homem a inveja do seu próximo. Também isso é vaidade e aflição de espírito.', 'Eclesiastes 4:4', 'Eclesiastes', 4, 4, NULL),
  ('vizinho', 'Há só um Legislador e um Juiz, que pode salvar e destruir. Tu, porém, quem és, que julgas a outrem?', 'Tiago 4:12', 'Tiago', 4, 12, NULL),
  ('vizinho', 'Não será assim entre vós; mas todo aquele que quiser, entre vós, fazer-se grande, que seja vosso serviçal; e qualquer que, entre vós, quiser ser o primeiro, que seja vosso servo.', 'Mateus 20:26-27', 'Mateus', 20, 26, 27),
  ('vizinho', 'Não aborrecerás a teu irmão no teu coração; não deixarás de repreender o teu próximo e nele não sofrerás pecado. Não te vingarás, nem guardarás ira contra os filhos do teu povo; mas amarás o teu próximo como a ti mesmo. Eu sou o Senhor.', 'Levítico 19:17-18', 'Levítico', 19, 17, 18),
  ('vizinho', 'E que amá-lo de todo o coração, e de todo o entendimento, e de toda a alma, e de todas as forças e amar o próximo como a si mesmo é mais do que todos os holocaustos e sacrifícios.', 'Marcos 12:33', 'Marcos', 12, 33, NULL),
  ('vizinho', 'Pedro, pois, era guardado na prisão; mas a igreja fazia contínua oração por ele a Deus.', 'Atos 12:5', 'Atos', 12, 5, NULL);

