import { VIGILANCE_SCALES_UI } from '@/lib/dashboardCardThemes';
import { MINIMAL_UI } from '@/lib/minimalUiTheme';
import { ACCESS_PIN_SECTION_BODY_MIN_HEIGHT } from '@/lib/manageProfile/shared';
import { Platform, StyleSheet } from 'react-native';

/** Ícones azul escuro — identidade vigilance_scales / minimal. */
export const PROFILE_CLASS_ICON_COLOR = '#1B4F8A';

const SURFACE = '#FFFFFF';
const TEXT = MINIMAL_UI.text;
const TEXT_MUTED = MINIMAL_UI.textMuted;
const ACCENT = VIGILANCE_SCALES_UI.accent;
const DIVIDER = MINIMAL_UI.divider;
const HAIRLINE = StyleSheet.hairlineWidth;

export const profileClassStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: SURFACE },
  header: { padding: 20, paddingBottom: 10 },
  titleCentered: {
    fontSize: 20,
    fontWeight: 'bold',
    color: TEXT,
    textAlign: 'center',
  },
  onboardingHint: {
    marginTop: 8,
    color: ACCENT,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 12,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  selfieCard: {
    backgroundColor: SURFACE,
    paddingVertical: 16,
    marginBottom: 16,
    borderBottomWidth: HAIRLINE,
    borderBottomColor: DIVIDER,
    gap: 14,
  },
  selfieRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  selfieFrame: {
    width: '34%',
    maxWidth: 140,
    minWidth: 124,
    aspectRatio: 3 / 4,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: MINIMAL_UI.rowHover,
    borderWidth: HAIRLINE,
    borderColor: ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selfieImage: {
    width: '100%',
    height: '100%',
  },
  selfieAside: {
    flex: 1,
    gap: 10,
    alignSelf: 'stretch',
    justifyContent: 'space-between',
  },
  selfieSummary: {
    gap: 6,
    alignSelf: 'flex-start',
    paddingTop: 2,
  },
  lgpdActionButton: {
    alignSelf: 'stretch',
    backgroundColor: '#B91C1C',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lgpdActionButtonText: {
    color: MINIMAL_UI.onDark,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  summaryName: {
    color: TEXT,
    fontSize: 18,
    fontWeight: '800',
  },
  summaryMeta: {
    color: TEXT_MUTED,
    fontSize: 13,
  },
  summaryBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: MINIMAL_UI.rowHover,
    color: ACCENT,
    fontSize: 12,
    fontWeight: '700',
  },
  selfieActionButton: {
    backgroundColor: ACCENT,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  selfieActionText: {
    color: MINIMAL_UI.onDark,
    fontSize: 15,
    fontWeight: '800',
  },
  accessPinSectionBody: {
    paddingHorizontal: 15,
    paddingBottom: 15,
    minHeight: ACCESS_PIN_SECTION_BODY_MIN_HEIGHT,
  },
  recoveryAccessPinSectionCard: {
    borderBottomColor: ACCENT,
    borderBottomWidth: 2,
  },
  accessPinHint: {
    color: TEXT_MUTED,
    fontSize: 13,
    lineHeight: 18,
    height: 54,
    marginBottom: 12,
  },
  accessPinFieldLabel: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 6,
  },
  accessPinErrorSlot: {
    height: 40,
    justifyContent: 'center',
    marginBottom: 4,
  },
  accessPinErrorText: {
    color: '#DC2626',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  accessPinErrorTextPlaceholder: {
    color: 'transparent',
  },
  accessPinSaveButton: {
    backgroundColor: ACCENT,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editorCard: {
    backgroundColor: SURFACE,
    padding: 15,
    marginBottom: 16,
    borderBottomWidth: HAIRLINE,
    borderBottomColor: DIVIDER,
  },
  editorLabel: {
    color: ACCENT,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 10,
    textAlign: 'center',
  },
  input: {
    backgroundColor: SURFACE,
    color: TEXT,
    padding: 15,
    borderRadius: 10,
    marginBottom: 12,
    borderWidth: HAIRLINE,
    borderColor: MINIMAL_UI.border,
  },
  editorActions: {
    flexDirection: 'row',
    gap: 10,
  },
  saveButton: {
    flex: 1,
    backgroundColor: ACCENT,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  saveButtonText: {
    color: MINIMAL_UI.onDark,
    fontWeight: '800',
  },
  cancelButton: {
    flex: 1,
    backgroundColor: MINIMAL_UI.rowHover,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: HAIRLINE,
    borderColor: DIVIDER,
  },
  cancelButtonText: {
    color: TEXT,
    fontWeight: '700',
  },
  disabledButton: {
    opacity: 0.45,
  },
  sectionCard: {
    backgroundColor: SURFACE,
    marginBottom: 0,
    borderBottomWidth: HAIRLINE,
    borderBottomColor: DIVIDER,
    overflow: 'hidden',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 14,
  },
  sectionTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '800',
  },
  sectionMeta: {
    color: TEXT_MUTED,
    fontSize: 12,
    marginTop: 2,
  },
  sectionFields: {
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  fieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: SURFACE,
    borderRadius: 10,
    padding: 14,
    marginTop: 8,
    borderBottomWidth: HAIRLINE,
    borderBottomColor: DIVIDER,
  },
  fieldInfoRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  fieldLabel: {
    width: '34%',
    maxWidth: 112,
    flexShrink: 0,
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    lineHeight: 16,
  },
  fieldValue: {
    flex: 1,
    minWidth: 0,
    color: TEXT,
    fontSize: 13,
    lineHeight: 18,
  },
  actionsRow: {
    width: 40,
    marginLeft: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  editButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ACCENT,
  },
  vehicleActionsColumn: {
    marginLeft: 12,
    alignItems: 'center',
    gap: 8,
  },
  vehicleEditor: {
    marginTop: 16,
    padding: 12,
    borderRadius: 12,
    backgroundColor: MINIMAL_UI.rowHover,
    borderBottomWidth: HAIRLINE,
    borderBottomColor: DIVIDER,
    gap: 0,
  },
  vehicleEditorTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 10,
  },
  vehicleFormRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  vehicleFormLabel: {
    width: '30%',
    maxWidth: 100,
    flexShrink: 0,
    paddingTop: 13,
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '600',
  },
  vehicleFormInput: {
    flex: 1,
    minWidth: 0,
    marginBottom: 0,
    paddingVertical: 11,
    paddingHorizontal: 12,
    fontSize: 14,
  },
  vehicleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: HAIRLINE,
    borderBottomColor: DIVIDER,
  },
  vehicleInfo: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
    gap: 4,
  },
  vehicleDetailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  vehicleDetailLabel: {
    width: '30%',
    maxWidth: 100,
    flexShrink: 0,
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '600',
  },
  vehicleDetailValue: {
    flex: 1,
    minWidth: 0,
    color: TEXT,
    fontSize: 14,
    lineHeight: 20,
  },
  newVehicleButton: {
    marginTop: 12,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: HAIRLINE,
    borderColor: ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newVehicleButtonText: {
    color: ACCENT,
    fontSize: 14,
    fontWeight: '600',
  },
  disabledIconButton: {
    opacity: 0.35,
  },
  emptyText: {
    color: TEXT_MUTED,
    fontSize: 16,
    textAlign: 'center',
    paddingVertical: 20,
  },
  footerContainer: {
    backgroundColor: SURFACE,
    paddingHorizontal: 20,
    paddingTop: 10,
    borderTopWidth: HAIRLINE,
    borderTopColor: DIVIDER,
  },
  backButton: {
    backgroundColor: MINIMAL_UI.rowHover,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: HAIRLINE,
    borderColor: DIVIDER,
  },
  backButtonText: {
    color: TEXT,
    fontWeight: 'bold',
    fontSize: 14,
  },
  cameraScreen: {
    flex: 1,
    backgroundColor: SURFACE,
  },
  cameraView: {
    flex: 1,
  },
  cameraStage: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  cameraHint: {
    color: TEXT,
    textAlign: 'center',
    marginBottom: 14,
    fontSize: 14,
    fontWeight: '600',
  },
  cameraFrame: {
    width: '100%',
    aspectRatio: 3 / 4,
    borderRadius: 28,
    overflow: 'hidden',
    alignSelf: 'center',
    borderWidth: HAIRLINE,
    borderColor: ACCENT,
    backgroundColor: MINIMAL_UI.rowHover,
  },
  cameraActions: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 36,
    flexDirection: 'row',
    gap: 10,
  },
  cameraPrimaryButton: {
    flex: 1,
    backgroundColor: ACCENT,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
  },
  cameraPrimaryButtonText: {
    color: MINIMAL_UI.onDark,
    fontWeight: '800',
  },
  cameraSecondaryButton: {
    flex: 1,
    backgroundColor: SURFACE,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: HAIRLINE,
    borderColor: DIVIDER,
  },
  cameraSecondaryButtonText: {
    color: TEXT,
    fontWeight: '700',
  },
  cepLookupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
  },
  cepLookupText: {
    color: TEXT_MUTED,
    fontSize: 13,
  },
});
