-- Temas do eixo identidade enviados no seed (98 linhas). Reexecutar substitui só esta categoria.
-- Aplica: npx supabase db query --linked -f scripts/curated-lesson-themes-identidade.sql

delete from public.curated_lesson_themes
 where category = 'identidade';

insert into public.curated_lesson_themes (category, title, bible_passage, core_lesson, activity_suggestion) values
('identidade', 'Fui Criado com Propósito e Arte', 'Salmos 139:14', 'Deus planejou cada detalhe da nossa vida e somos obras de arte feitas por Ele com muito carinho e intenção.', 'Espelho e Elogio: Cada criança olha num espelho de mão, diz "Deus me fez de propósito e sou especial!" e elogia o colega ao lado.'),
('identidade', 'Conhecido e Chamado pelo Nome', 'Isaías 43:1', 'Deus não nos vê como uma multidão genérica; Ele nos conhece individualmente, sabe o nosso nome e nos ama de perto.', 'O Chamado: Esconder crachás com os nomes das crianças pela sala para que cada um ache o seu e entenda que Deus o conhece.'),
('identidade', 'Filho Amado, Herdeiro do Pai', '1 João 3:1', 'Nossa maior identidade não está no que fazemos, mas no fato de pertencermos à família do Criador como filhos amados.', 'O Crachá de Filho: Entregar um crachá em formato de coração escrito "Filho(a) Amado de Deus" para usarem durante a aula.'),
('identidade', 'Brilhando como Luz no Escuro', 'Mateus 5:16', 'Temos a luz de Jesus dentro de nós e podemos refletir o amor Dele por onde passarmos através de boas atitudes.', 'A Lanterna: Apagar as luzes e acender uma lanterna para mostrar como um feixe pequeno ilumina o ambiente escuro.'),
('identidade', 'Tesouro Precioso nas Mãos do Criador', 'Êxodo 19:5', 'Deus nos comprou, nos guarda e nos valoriza como a sua joia mais rara e preciosa.', 'A Caixa de Tesouro: Mostrar uma caixinha bonita fechada contendo um espelho no fundo para que cada criança se veja como o tesouro.'),
('identidade', 'Forte e Corajoso porque Ele é Comigo', 'Josué 1:9', 'A verdadeira coragem não vem da nossa própria força, mas da certeza de que Deus segura a nossa mão em qualquer medo.', 'Caminhada Guiada: Uma criança caminha de olhos fechados com segurança, guiada pelo colega, sentindo o apoio e a confiança.'),
('identidade', 'O Oleiro e o Barro: Em Construção', 'Jeremias 18:6', 'Deus está moldando o nosso caráter todos os dias com paciência e amor, transformando nossas imperfeições.', 'Modelagem com Massinha: Dar massinha para criarem formas livres, conversando sobre como Deus modela nossas vidas com carinho.'),
('identidade', 'Diferentes e Especiais no Corpo de Cristo', '1 Coríntios 12:27', 'Cada um tem dons, jeitos e características únicas, e todos são importantes e necessários na comunidade de fé.', 'O Quebra-Cabeça Humano: Desenhar partes de um grande painel em peças separadas e uni-las para formar uma grande imagem conjunta.'),
('identidade', 'Perdoados e Limpos por Inteiro', 'Salmos 103:12', 'Nossos erros não definem quem nós somos, pois o perdão de Deus nos limpa e nos dá um recomeço limpinho todos os dias.', 'O Papel Amassado: Amassar uma folha de papel representando os erros e depois abri-la e alisá-la, simbolizando o perdão que restaura.'),
('identidade', 'Seguros no Colo do Pai', 'Salmos 91:4', 'Estamos seguros e protegidos pelo cuidado amoroso de Deus, mesmo quando há tempestades ou barulhos ao nosso redor.', 'Abraço Coletivo: Fazer uma roda e dar um abraço coletivo ou abraçar a si mesmo com força, lembrando da proteção de Deus.'),
('identidade', 'Nascidos para a Liberdade', 'Gálatas 5:1', 'Em Cristo fomos libertos do medo e da culpa para vivermos uma vida cheia de alegria e amor.', 'O Desatar de Laços: Brincar levemente de desatar fitas soltas amarradas nos pulsos, simbolizando a liberdade que Jesus traz.'),
('identidade', 'Minha Voz Importa para Deus', '1 Samuel 3:10', 'Deus ouve a nossa voz, seja em oração, em um louvor ou quando conversamos com Ele de coração aberto.', 'O Telefone sem Fio da Oração: Passar uma mensagem de carinho baixinho para treinar que Deus ouve até o sussurro.'),
('identidade', 'Pensamentos que Elevam', 'Filipenses 4:8', 'Nossa identidade se reflete em enchermos a mente com o que é verdadeiro, puro, amável e de boa fama.', 'Caça às Palavras Boas: Encontrar cartões espalhados pela sala com palavras edificantes e colá-los num mural.'),
('identidade', 'O Rosto Amigo de Deus', 'Números 6:25-26', 'Deus olha para nós com graça, favor e um sorriso de amor incondicional todos os dias.', 'Espelho de Sorrisos: Olhar para o colega e sorrir, lembrando que o sorriso de Deus nos acolhe e nos dá paz.'),
('identidade', 'Um Nome Gravado nas Mãos de Deus', 'Isaías 49:16', 'Deus jamais se esquece de nós; nossos nomes estão gravados na palma das mãos dEle para sempre.', 'Mão Carimbada: Carimbar a mão em uma folha de papel com tinta atóxica e escrever o nome de cada criança dentro.'),
('identidade', 'Segurança na Rocha Firme', 'Salmos 62:2', 'Nossa identidade e estabilidade vêm de estarmos firmados em Deus, que é a nossa rocha inabalável.', 'Equilíbrio na Rocha: Ficar em cima de um tapete ou almofada firme enquanto o professor simula ventos fracos, mostrando firmeza.'),
('identidade', 'Amados Antes do Início de Tudo', 'Efésios 1:4', 'Antes mesmo de nascermos, Deus já sonhava conosco e nos escolheu para sermos santos e irrepreensíveis.', 'Linha do Tempo dos Sonhos: Desenhar o sol e as estrelas, conversando sobre o plano de Deus antes da fundação do mundo.'),
('identidade', 'Um Coração Puro e Renovado', 'Salmos 51:10', 'Podemos pedir a Deus um coração limpo e renovado todas as vezes que erramos ou nos sentimos distantes.', 'Água Limpa no Copo: Jogar água suja fora de um copo e enchê-lo com água limpa, ilustrando a renovação do coração.'),
('identidade', 'Criados para Fazer o Bem', 'Efésios 2:10', 'Deus preparou antecipadamente boas obras para caminharmos nelas, abençoando outras pessoas.', 'Pegadas de Bondade: Recortar pegadas de papel, escrever boas ações nelas e criar uma trilha no chão da sala.'),
('identidade', 'Valiosos Mais do que os Pássaros', 'Mateus 6:26', 'Se Deus cuida com tanto carinho das aves do céu, quanto mais Ele cuida de nós, que somos Seus filhos!', 'Olhando o Céu: Olhar pela janela ou desenhar passarinhos livres, lembrando do cuidado diário de Deus.'),
('identidade', 'Herdeiros da Promessa', 'Gálatas 3:29', 'Pertencemos à família da fé e herdamos todas as promessas maravilhosas de amor e salvação em Cristo.', 'Coroa de Promessas: Confeccionar uma coroa simples de papel com a frase "Herdeiro do Reino" para as crianças levarem.'),
('identidade', 'Alvo do Amor Mais Alto', 'Efésios 3:18', 'O amor de Deus por nós é tão largo, comprido, alto e profundo que nenhuma medida consegue alcançar.', 'Medindo o Abraço: Abrir os braços bem abertos para tentar medir um abraço gigante, simbolizando o amor de Deus.'),
('identidade', 'Livres da Ansiedade e do Medo', 'Filipenses 4:6', 'Não precisamos carregar preocupações sozinhos; podemos entregar tudo a Deus em oração.', 'Caixinha de Entregas: Escrever preocupações fictícias num papelzinho, dobrar e colocar numa caixinha, simbolizando entregar a Deus.'),
('identidade', 'Alegria que Transborda', 'Salmos 16:11', 'Na presença de Deus encontramos alegria verdadeira, paz e plenitude para o nosso dia a dia.', 'Dança de Louvor: Colocar uma música alegre e dançar celebrando a alegria que vem do alto com gratidão.'),
('identidade', 'Seguros sob as Asas do Criador', 'Salmos 17:8', 'Deus nos guarda como a menina dos olhos e nos esconde debaixo da sombra de Suas asas protetoras.', 'Asas Protetoras: Dois colegas formam uma "tenda" com os braços para proteger o outro, ilustrando o refúgio em Deus.'),
('identidade', 'Chamados para a Luz e a Verdade', '1 Pedro 2:9', 'Somos raça eleita, sacerdócio real e nação santa para proclamar as grandezas dAquele que nos chamou.', 'O Crachá Real: Distribuir crachás com distintivos de embaixadores do Reino de Deus na Terra.'),
('identidade', 'Embaixadores do Reino dos Céus', '2 Coríntios 5:20', 'Representamos a Jesus onde quer que formos, espalhando bondade, paz e boas novas.', 'Desfile de Embaixadores: Caminhar pela sala cumprimentando os colegas com um sorriso e palavras de paz.'),
('identidade', 'Sementes de Amor Frutuosas', 'Gálatas 5:22', 'O Espírito Santo produz em nós frutos maravilhosos como amor, paz, paciência e bondade.', 'Plantando a Semente: Plantar um feijãozinho no algodão para observar o crescimento e associar ao fruto do Espírito.'),
('identidade', 'Calçados com a Paz de Cristo', 'Efésios 6:15', 'Nossa identidade nos capacita a caminhar levando a mensagem de paz e reconciliação por onde passarmos.', 'A Corrida da Paz: Simular uma caminhada em círculo onde todos carregam um símbolo de paz para o colega.'),
('identidade', 'Coragem para Fazer o Certo', 'Provérbios 28:1', 'O justo é corajoso como um leão; sabemos que Deus nos dá forças para escolher o bem mesmo quando é difícil.', 'Rugido de Coragem: Fazer uma dinâmica de expressão corporal sobre ficar firmes na verdade com coragem e mansidão.'),
('identidade', 'Filhos da Luz, Não das Trevas', 'Efésios 5:8', 'Antes éramos trevas, mas agora somos luz no Senhor; devemos andar como filhos da luz.', 'O Jogo das Cores: Acender luzes coloridas ou usar refletores para mostrar a diferença que a luz faz no ambiente.'),
('identidade', 'Um Templo do Espírito Santo', '1 Coríntios 6:19', 'Nosso corpo e nossa mente são moradia do Espírito Santo, por isso devemos cuidar deles com carinho.', 'Cuidando do Jardim: Imaginar o coração como um jardim que regamos e limpamos para florescer para Deus.'),
('identidade', 'Nossa Força Vem do Alto', 'Isaías 40:31', 'Aqueles que confiam no Senhor renovam as suas forças, voam com asas como águias e não se cansam.', 'Voo da Águia: Simular o movimento suave dos braços como asas de águia, lembrando que Deus renova nossas energias.'),
('identidade', 'A Graça que Nos Alcança', 'Efésios 2:8', 'Somos salvos pela graça de Deus, um presente imerecido que nos dá valor e identidade eterna.', 'Caixa de Presente Surpresa: Abrir uma caixa de presente vazia com um bilhete dizendo "O maior presente é a graça de Deus".'),
('identidade', 'Pacientes e Mansos de Coração', 'Colossenses 3:12', 'Como eleitos de Deus, santos e amados, revestimo-nos de profunda compaixão, bondade e mansidão.', 'O Abraço da Calma: Praticar um momento de silêncio e respiração profunda, sentindo a mansidão de Deus.'),
('identidade', 'Seguros no Abraço do Pai', 'Lucas 15:20', 'Assim como o pai da parábola correu para abraçar o filho, Deus nos recebe de braços abertos sempre.', 'O Abraço de Boas-Vindas: Um abraço acolhedor em duplas, celebrando que somos aceitos e amados por Deus.'),
('identidade', 'Amigos de Deus e Servidores', 'João 15:15', 'Jesus nos chamou de amigos e nos confia a missão de amar e servir uns aos outros com alegria.', 'Circuito da Amizade: Passar uma bola de lã entre as crianças para formar uma rede de amizade e união.'),
('identidade', 'Guiados pelo Bom Pastor', 'Salmos 23:1', 'O Senhor é o nosso pastor; Ele nos guia a verdes pastos e águas tranquilas, cuidando de cada passo.', 'O Pastor e as Ovelhinhas: Brincadeira leve onde um guia os colegas de olhos vendados com segurança pela voz amável.'),
('identidade', 'Ricos em Obras Boas', '1 Timóteo 6:18', 'Nossa verdadeira riqueza está em praticar o bem, ser generosos e compartilhar o que temos.', 'Cofre do Bem: Desenhar moedinhas de papel onde cada criança escreve uma boa ação que pode fazer hoje.'),
('identidade', 'Sempre Acolhidos na Casa do Pai', 'Salmos 84:10', 'Estar na presença de Deus é o melhor lugar do mundo; somos bem-vindos na Sua casa.', 'Montando a Tenda: Criar uma cabaninha simbólica com lençóis na sala para lembrar do aconchego da presença de Deus.'),
('identidade', 'Vencedores por Meio de Cristo', 'Romanos 8:37', 'Em todas as lutas, somos mais do que vencedores por meio daquele que nos amou intensamente.', 'Medalha de Vencedor: Entregar medalhas de papel com a frase "Vencedor em Cristo" para cada criança.'),
('identidade', 'Mãos Prontas para Ajudar', 'Eclesiastes 4:9', 'Deus nos deu mãos para abençoar, levantar quem caiu e construir pontes de amor ao invés de muros.', 'Carimbo das Mãos: Pintar levemente as mãos com tinta lavável e carimbar em um cartaz coletivo de ajuda mútua.'),
('identidade', 'Pés Firmados na Verdade', 'Efésios 6:14', 'Nossa identidade nos dá estabilidade para caminhar firmes na verdade da Palavra de Deus.', 'Trilha de Pegadas: Seguir uma trilha desenhada no chão com passagens bíblicas curtas em cada passo.'),
('identidade', 'O Escudo da Fé que Protege', 'Efésios 6:16', 'Podemos confiar em Deus como nosso escudo contra o medo, a mentira e a dúvida.', 'O Escudo de Papelão: Confeccionar pequenos escudos de papelão com símbolos de fé e confiança em Deus.'),
('identidade', 'O Capacete da Salvação', 'Efésios 6:17', 'Nossa mente é guardada pela certeza de que pertencemos a Jesus e temos a salvação garantida.', 'Chapéu de Papel: Dobrar chapéus de marinheiro ou explorador em papel, simbolizando a proteção dos pensamentos em Deus.'),
('identidade', 'A Espada do Espírito', 'Efésios 6:17', 'A Palavra de Deus é viva e eficaz; conhecê-la nos dá sabedoria para vencer qualquer confusão.', 'Caça aos Versículos: Encontrar cartões com pequenos versículos escondidos na sala e ler juntos.'),
('identidade', 'Generosos como o Pai', 'Provérbios 22:9', 'Quem tem o olhar generoso é abençoado, porque reparte o seu pão e o seu amor com quem precisa.', 'Partilha de Lanches: Simular a partilha de um lanche ou fruta, entendendo a alegria de dividir com o colega.'),
('identidade', 'Humildes e Servidores', 'Filipenses 2:3', 'A verdadeira grandeza no Reino de Deus está em servir aos outros com amor e simplicidade.', 'Lavando os Pés (Ilustrativo): Simular o ato de cuidado lavando simbolicamente as mãos com carinho em uma bacia com água.'),
('identidade', 'Pacificadores Bem-Aventurados', 'Mateus 5:9', 'Bem-aventurados os pacificadores, porque serão chamados filhos de Deus; levamos paz onde há conflito.', 'O Aperto de Mãos da Paz: Cumprimentar o colega do lado com um abraço ou aperto de mãos e dizer "A paz de Jesus".'),
('identidade', 'Perseverantes na Orações', 'Romanos 12:12', 'Podemos conversar com Deus em todo tempo, com alegria na esperança e paciência na tribulação.', 'O Mural de Pedidos: Escrever pedidos simples em post-its e colar em um mural de oração da turma.'),
('identidade', 'Músicos de Louvor no Coração', 'Efésios 5:19', 'Nossa identidade transborda em salmos, hinos e cânticos espirituais cantados ao Senhor de coração.', 'Instrumentos Caseiros: Criar barulhinhos rítmicos com chocalhos de garrafa pet e louvar a Deus juntos.'),
('identidade', 'Discernimento para Escolher o Bem', 'Hebreus 5:14', 'Exercitamos nossos sentidos espirituais para discernir entre o bem e o mal através da prática da Palavra.', 'O Caminho Certo: Um pequeno labirinto no papel onde a criança escolhe a atitude bondosa para vencer o jogo.'),
('identidade', 'Resilientes nas Dificuldades', 'Tiago 1:2-4', 'As provações produzem perseverança em nós, tornando-nos maduros e completos em Deus.', 'A Torre de Blocos: Montar uma torre de blocos de madeira e conversar sobre como persistir mesmo se cair.'),
('identidade', 'Alegres na Esperança', 'Romanos 12:12', 'Sabemos que o futuro está nas mãos de Deus, por isso nossa esperança é firme e cheia de alegria.', 'Balões da Esperança: Encher balões coloridos e brincar mantendo-os no ar, simbolizando a alegria que se mantém.'),
('identidade', 'Prudentes nas Palavras', 'Provérbios 15:1', 'A resposta branda desvia o furor; nossas palavras têm o poder de sarar e abençoar vidas.', 'O Pote de Palavras Doces: Escrever palavras gentis em papéis coloridos e colocar em um pote para sortear.'),
('identidade', 'Misericordiosos como o Pai', 'Lucas 6:36', 'Assim como nosso Pai celestial é misericordioso, somos chamados a perdoar e ajudar quem errou.', 'O Abraço do Perdão: Reconciliar duplas que brincam de fazer as pazes com sorrisos e um abraço.'),
('identidade', 'Satisfeitos na Presença de Deus', 'Salmos 63:5', 'Nossa alma fica farta e saciada quando buscamos a presença de Deus acima de tudo.', 'Picnic Simulado: Sentar em roda no chão com uma toalha fingindo um lanche especial na presença de Deus.'),
('identidade', 'Honrosos com a Família', 'Efésios 6:2', 'Honrar pai e mãe é o primeiro mandamento com promessa de que tudo nos irá bem.', 'Cartão de Honra: Desenhar um cartão especial para entregar aos pais em casa como sinal de carinho e honra.'),
('identidade', 'Justos e Íntegros', 'Provérbios 11:3', 'A integridade dos retos os guia; ser honesto em tudo agrada o coração de Deus.', 'O Jogo da Verdade: Situar escolhas do dia a dia e votar qual é a atitude honesta e correta a tomar.'),
('identidade', 'Trabalhadores Dedicados', 'Colossenses 3:23', 'Tudo o que fizermos, façamos de todo o coração, como para o Senhor e não para os homens.', 'A Tarefa Caprichada: Organizar os materiais da sala com capricho, mostrando zelo pelo que fazemos.'),
('identidade', 'Luzes que Não se Escondem', 'Mateus 5:14', 'Somos como uma cidade construída sobre um monte que não pode ser oculta; nossa fé transparece.', 'Estrelas Brilhantes: Recortar estrelas de papel prateado e colar crachás com a frase "Luz de Jesus".'),
('identidade', 'Acolhedores de Estrangeiros', 'Levítico 19:34', 'Devemos amar o próximo como a nós mesmos e acolher quem chega com o coração aberto.', 'Cadeira do Acolhimento: Convidar um colega novo para sentar no centro e receber boas-vindas calorosas.'),
('identidade', 'Mates da Fé Inspiradores', 'Hebreus 11:1', 'A fé é a certeza das coisas que se esperam e a convicção de fatos que não se veem.', 'A Galeria da Fé: Desenhar heróis da fé da Bíblia e expor os desenhos como uma galeria de inspiração.'),
('identidade', 'Livres da Condenação', 'Romanos 8:1', 'Portanto, agora nenhuma condenação há para os que estão em Cristo Jesus, livres para recomeçar.', 'O Carimbo de Recomeço: Carimbar um "OK" ou um coração carinhoso em um papel velho, simbolizando a nova chance.'),
('identidade', 'Temperantes e Donos de Si', 'Gálatas 5:23', 'O domínio próprio é fruto do Espírito; conseguimos respirar fundo antes de agir com impulso.', 'Respiração da Calma: Praticar inspirar contando até três e expirar devagar para exercitar o autocontrole.'),
('identidade', 'Fieis nas Pequenas Coisas', 'Lucas 16:10', 'Quem é fiel no pouco também é fiel no muito; nossas pequenas atitudes diárias importam para Deus.', 'Contando Moedinhas: Brincadeira de organizar objetos em fileiras corretas para treinar o capricho nos detalhes.'),
('identidade', 'Mansos de Coração', 'Mateus 11:29', 'Aprendemos com Jesus, que é manso e humilde de coração, achando descanso para as nossas almas.', 'Momento de Silêncio: Ouvir o som do ambiente por trinta segundos em silêncio absoluto para acalmar o coração.'),
('identidade', 'Prontos para Ouvir', 'Tiago 1:19', 'Todo homem seja pronto para ouvir, tardio para falar e tardio para se irar.', 'O Jogo das Orelhas Grandes: Desenhar orelhas grandes de papel e brincar de quem ouve a história com mais atenção.'),
('identidade', 'Hospitalares e Alegres', 'Romanos 12:13', 'Praticai a hospitalidade com alegria, repartindo o espaço e o afeto com quem chega.', 'A Roda do Chá: Sentar em roda tomando água ou suco juntos, celebrando a comunhão e a amizade.'),
('identidade', 'Buscadores da Sabedoria', 'Provérbios 2:3-4', 'Se clamarmos por inteligência e buscarmos a sabedoria como a tesouros escondidos, a acharemos.', 'Caça ao Tesouro da Sabedoria: Encontrar pistas com provérbios escondidos pela sala para desvendar o segredo.'),
('identidade', 'Curados pelas Feridas de Cristo', 'Isaías 53:5', 'Pelas Suas pisaduras fomos sarados; Jesus cuida das nossas dores físicas e emocionais.', 'O Curativo do Amor: Colocar um band-aid simbólico no braço para lembrar que Jesus sara o nosso coração.'),
('identidade', 'Resgatados das Trevas', 'Colossenses 1:13', 'Deus nos tirou do império das trevas e nos trasladou para o Reino do Filho do Seu amor.', 'Da Noite para o Dia: Abrir a cortina da janela para deixar a luz do sol entrar, ilustrando a mudança de vida.'),
('identidade', 'Criados para a Comunhão', 'Salmos 133:1', 'Oh! Quão bom e quão suave é que os irmãos vivam em união e harmonia!', 'O Abraço de Cadeia: Dar as mãos em roda e balançar juntos cantando uma música de união e amor fraterno.'),
('identidade', 'Providos pelo Pai Celestial', 'Filipenses 4:19', 'O meu Deus suprirá todas as vossas necessidades segundo as Suas riquezas em glória em Cristo Jesus.', 'Cesta de Frutas: Mostrar uma cesta cheia de frutas para conversar sobre como Deus sustenta a nossa vida com provisão.'),
('identidade', 'Valentes na Batalha da Fé', 'Efésios 6:11', 'Vestimos toda a armadura de Deus para poder resistir no dia mau e permanecer firmes.', 'Postura de Campeões: Ficar em pé com firmeza e postura alegre, prontos para fazer o bem e vencer o mal com amor.'),
('identidade', 'Filhos que Obedecem com Alegria', 'Efésios 6:1', 'Obedecer aos pais e líderes no Senhor é correto e traz paz e proteção para o nosso caminho.', 'O Eco da Obediência: O professor diz uma regra boa e as crianças repetem em coro com alegria obedecendo.'),
('identidade', 'Sua Graça nos Basta', '2 Coríntios 12:9', 'A graça de Deus é suficiente para nós, pois o Seu poder se perfecciona na nossa fraqueza.', 'O Abraço Forte: Abraçar a si mesmo bem forte lembrando que a graça de Deus nos sustenta em todo tempo.'),
('identidade', 'Lâmpada para os Pés', 'Salmos 119:105', 'A Palavra de Deus é lâmpada para os nossos pés e luz para o nosso caminho escuro.', 'A Lanterninha Bíblica: Usar uma lanterna apontada para uma Bíblia aberta para mostrar que a Palavra guia nossos passos.'),
('identidade', 'Seguros no Nome do Senhor', 'Provérbios 18:10', 'O nome do Senhor é uma torre forte; para ela corre o justo e está seguro.', 'A Torre Forte: Juntar blocos para formar uma torre alta, simbolizando a proteção indestrutível do nome de Deus.'),
('identidade', 'Ungidos com Óleo de Alegria', 'Salmos 45:7', 'Deus nos ungiu com óleo de alegria acima dos nossos companheiros, enchendo nossa vida de louvor.', 'Sorriso no Rosto: Pintar um rostinho feliz num papel para lembrar que a alegria do Senhor é a nossa força.'),
('identidade', 'Testemunhas Vivas do Amor', 'Atos 1:8', 'Recebemos poder quando o Espírito Santo desce sobre nós para sermos testemunhas de Jesus.', 'O Testemunho do Bem: Cada criança conta em dez segundos uma coisa boa que Deus fez na sua semana.'),
('identidade', 'Satisfeitos nas Fontes de Água Viva', 'Jeremias 2:13', 'Deus é a fonte de água viva; quem bebe dela nunca mais terá sede espiritual.', 'Copo d’Água Fresca: Tomar um gole d’água fresca conversando sobre como Jesus satisfaz a alma.'),
('identidade', 'Santuários de Oração', 'Mateus 6:6', 'Podemos entrar no nosso quarto, fechar a porta e orar ao nosso Pai que vê em secreto.', 'A Janela do Céu: Fechar os olhos por um instante e imaginar conversando diretamente com o Pai celestial.'),
('identidade', 'Perfeitos na Unidade', 'João 17:23', 'Jesus orou para que sejamos um, assim como Ele e o Pai são um, demonstrando amor ao mundo.', 'Dadas as Mãos: Formar um círculo perfeito de mãos dadas, simbolizando que juntos somos fortes em Cristo.'),
('identidade', 'Confiantes na Promessa', 'Hebreus 10:23', 'Retenhamos firmes a confissão da nossa esperança, porque fiel é o que prometeu.', 'O Abraço da Promessa: Dar um abraço de incentivo no colega dizendo "Deus cumpre o que promete!".'),
('identidade', 'Corações Gratos em Todo Tempo', '1 Tessalonicenses 5:18', 'Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.', 'A Ciranda da Gratidão: Cada criança diz rapidamente uma coisa pela qual agradece a Deus hoje em roda.'),
('identidade', 'Herdeiros de um Reino Inabalável', 'Hebreus 12:28', 'Recebemos um Reino que não pode ser abalado; retenhamos a graça para servir a Deus com temor.', 'A coroa de Rei: Desenhar coroas brilhantes no papel e conversar sobre o Reino eterno de Deus.'),
('identidade', 'Guiados pelo Espírito', 'Gálatas 5:25', 'Se vivemos pelo Espírito, andemos também pelo Espírito, ouvindo Sua voz em nossas escolhas.', 'Passos Sincronizados: Caminhar em ritmo suave pela sala seguindo os passos calmos do líder.'),
('identidade', 'Amigos que Ajudam a Carregar o Leito', 'Marcos 2:4', 'Amigos de verdade ajudam uns aos outros a chegar até Jesus nos momentos de dificuldade.', 'Carregar o Colega (Lúdico): Dar as mãos em duplas para ajudar o colega a atravessar um obstáculo leve na sala.'),
('identidade', 'O Sal da Terra', 'Mateus 5:13', 'Somos o sal da terra; nossa presença traz sabor, bondade e faz diferença no ambiente onde estamos.', 'Toque de Sal: Provar um grãozinho mínimo de sal para entender como uma pitada faz diferença no alimento.'),
('identidade', 'Firmes e Constantes', '1 Coríntios 15:58', 'Portanto, meus amados irmãos, sede firmes, inabaláveis e sempre abundantes na obra do Senhor.', 'Estátua de Cristal: Brincar de estátua onde todos devem ficar bem firmes e imóveis como rochas na fé.'),
('identidade', 'Raios de Esperança', 'Lamentações 3:22-23', 'As misericórdias do Senhor se renovam a cada manhã; grande é a Sua fidelidade.', 'O Sol da Manhã: Desenhar um sol radiante com raios coloridos representando as novas misericórdias diárias.'),
('identidade', 'Vestidos de Linho Brino e Justiça', 'Apocalipse 19:8', 'Foi dado à noiva vestir-se de linho finíssimo, puro e resplandecente, que são os atos de justiça.', 'Roupa de Ouro e Luz: Imaginar vestes de bondade e amor cobrindo o nosso coração para abençoar os outros.'),
('identidade', 'Seguros na Palma da Mão de Deus', 'João 10:28', 'Eu lhes dou a vida eterna, e jamais perecerão; ninguém as arrebatará da Minha mão.', 'Mãos Encaixadas: Encaixar as mãos firmemente com o colega, simbolizando a segurança eterna nos braços de Deus.'),
('identidade', 'Príncipes e Princesas do Rei', 'Salmos 45:16', 'Somos filhos do Grande Rei do Universo, coroados de graça, amor e misericórdia.', 'Coroa de Papelão: Confeccionar tiaras e coroas simples com brilhantes de papel para celebrar nossa filiação real.'),
('identidade', 'Livre para Amar sem Medo', '1 João 4:18', 'No amor não há medo antes o perfeito amor lança fora o medo, trazendo paz ao coração.', 'O Balão do Medo: Amassar um papel escrito "Medo" e jogá-lo fora na lixeira, respirando a paz do amor de Deus.'),
('identidade', 'Criados para a Glória de Deus', 'Isaías 43:7', 'Todos os que são chamados pelo meu nome, os criei para a minha glória, os formei e os fiz.', 'Louvor com Palmas: Bater palmas com entusiasmo celebrando que fomos criados para louvar a Deus com alegria.'),
('identidade', 'Amados com Amor Eterno', 'Jeremias 31:3', 'Com amor eterno eu te amei; por isso com benignidade te atraí para mim.', 'Coração Gigante: Desenhar um coração enorme no chão com giz ou fita e sentar todos dentro dele com alegria.');

do $$
declare
  n integer;
  incompletos integer;
begin
  select count(*) into n
    from public.curated_lesson_themes
   where category = 'identidade';

  select count(*) into incompletos
    from public.curated_lesson_themes
   where category = 'identidade'
     and (
       length(btrim(title)) < 2
       or length(btrim(bible_passage)) < 1
       or length(btrim(core_lesson)) < 1
       or length(btrim(activity_suggestion)) < 1
     );

  if n <> 98 or incompletos <> 0 then
    raise exception 'Seed de identidade inválido: % temas, % incompletos.', n, incompletos;
  end if;
end;
$$;
