-- Diagnóstico legado — scripts separados em scripts/test-media-auth/
--
-- 01-config-email.sql         — config Resend/Gmail + URL
-- 02-functions-exist.sql      — funções RPC instaladas
-- 03-send-test-email.sql      — envio de teste
-- 04-list-pending.sql         — pendências
-- 05-list-confirmed.sql       — confirmadas
-- 06-check-token-from-link.sql — validar token do link
-- 07-set-production-url.sql   — cadastrar URL do app
-- 08-confirm-token-manual.sql — confirmar token via SQL
