-- DEPRECADO — não execute.
-- Este script priorizava super_admin ao resolver telefone duplicado e permitia
-- login como gestor após "Esqueci minha senha" (PIN gravado no perfil errado).
--
-- Use em produção:
--   scripts/fix-login-auth-avoid-super-admin-escalation.sql
--
-- Para restaurar papel super_admin no perfil correto, ajuste os dados (telefone único
-- ou papel no perfil certo) e consulte scripts/restore-super-admin-by-phone.sql.
